### ISSUE TITLE
Cmd + ` does not switch VSCode windows on Mac using french keyboard layout

### ISSUE THREAD

**Issue by janmarek** [Microsoft/vscode#10021]
- VSCode Version: 1.3.1
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:
1. open multiple windows of VSCode
2. press Cmd + `

It does not switch application windows. In every other app it does.

**Comment by richarddavenport** [comment]
I just tested with VSCode 1.3.1 and OS X 10.11.6 and it is working for me. Sounds like there may be a system related setting causing this.

**Comment by chaskim** [comment]
I have the same issue with the same setup (VSCode 1.3.1, OS X 10.11.6). I don't know if this makes any difference, but I have a French keyboard, which has the \` key just to the left of the Enter key (circled in red below):

<img width="435" alt="frenchkeyboard" src="https://cloud.githubusercontent.com/assets/12981330/17319220/6fc5e14e-588c-11e6-974f-f767a41df854.png">

When I press Cmd + \`, VSCode actually types the \` character in the editor, which isn't "correct" (that is, only the \` key by itself should type the \` character).

Other apps, like TextWrangler and Sublime Text 3 and Apple's TextEdit and Safari correctly switches windows when Cmd + \` is pressed.

**Comment by janmarek** [comment]
I use czech keyboard layout.

**Comment by bpasero** [comment]
Electron issue.

**Comment by bpasero** [comment]
@janmarek @chaskim  we just released a new insiders build with a newer Electron. maybe you could give that build a try to see if it fixes this issue.

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by octref** [comment]
Still typing <kbd>`</kbd> using French layout.

However, under French layout this is behavior for Chrome:

![french](https://cloud.githubusercontent.com/assets/4033249/18969886/eb8ac030-8643-11e6-9247-3dd3a6a6fc9c.gif)

Only happens when you are in a input.

**Comment by chaskim** [comment]
@bpasero 
Sorry, I've been away for a while and only just saw the note on the new insiders build with the newer Electron. Yes, just to confirm, I just installed VS Code 1.6.0 and Cmd + &#96; still doesn't work with my MacBook's french keyboard.

I don't know if this will help, but with the cursor in a .ts, .js or .json file, Cmd + &#96; types a double grave accent and places the cursor in between the two as if I had typed a double quote or curly bracket:

<img width="42" alt="capture d ecran 2016-10-11 a 01 21 20" src="https://cloud.githubusercontent.com/assets/12981330/19254156/1d2411b2-8f51-11e6-9fc0-92393d997491.png">

In a .html or .cs file, Cmd + &#96; types a single grave accent. 

Actually nothing should be typed into an editor window with Cmd + &#96; since the Cmd key is being used.

**Comment by bpasero** [comment]
@janmarek do you still get this with our current 1.12 release?

**Comment by chaskim** [comment]
Hi. Still getting the same issue here. With the cursor in an editor, cmd + \` still types the \` character rather than switches windows. But this may help: if the focus is in the _**sidebar**_, say on a folder or file, cmd + \` correctly switches windows.

El Capitan 10.11.6, VS Code 1.12.1, French keyboard.

**Comment by bpasero** [comment]
With current insiders release we added a new command to switch windows. For example:

```json
{ "key": "ctrl+r", "command": "workbench.action.quickSwitchWindows" },
{ "key": "ctrl+r", "command": "workbench.action.quickOpenNavigateNext", "when": "inQuickOpen" }
```

You can keep `Ctrl` pressed when hitting `R` to cycle through windows and pick the one you want when releasing `Ctrl`.

**Comment by bpasero** [comment]
Closing as per https://github.com/Microsoft/vscode/issues/10021#issuecomment-307637284
