### ISSUE TITLE
Jupyter Notebook stopped working

### ISSUE THREAD

**Issue by yeellow** [microsoft/vscode#100846]
Issue Type: <b>Bug</b>

Jupyter notebook cannot be created (the window is blank with both scrollbars visible). It was caused by the last update, everything worked yesterday (checked on two separate machines).

VS Code version: Code - Insiders 1.47.0-insider (0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69, 2020-06-23T09:03:35.861Z)
OS version: Windows_NT x64 10.0.19041

**Comment by dbaeumer** [comment]
Are you using the Python extension?

**Comment by yeellow** [comment]
Yes, please find a list of my extensions below. Jupyter notebook stopped working after the last update (everything was fine yesterday) and the extensions were not updated.


stack-overflow-view | 4tr | 0.1.1
-- | -- | --
vscode-sqlite | ale | 0.8.2
bracket-pair-colorizer-2 | Coe | 0.1.4
vscode-eslint | dba | 2.1.5
gitlens | eam | 10.2.2
vscode-test-explorer | hbe | 2.19.1
plantuml | jeb | 2.13.12
vsc-python-indent | Kev | 1.10.1
vscode-python-test-adapter | lit | 0.4.3
MagicPython | mag | 1.1.0
python | ms- | 2020.6.89148
remote-containers | ms- | 0.123.0
remote-ssh | ms- | 0.51.0
remote-ssh-edit | ms- | 0.51.0
remote-wsl | ms- | 0.44.4
vscode-remote-extensionpack | ms- | 0.20.0
powershell-preview | ms- | 2020.6.1
debugger-for-chrome | msj | 4.12.8
autodocstring | njp | 0.5.3
vscode-data-preview | Ran | 2.0.0
multi-command | ryu | 1.4.0
vscodeintellicode | Vis | 1.2.8
vscode-icons | vsc | 10.1.1
jinja | who | 0.0.8

**Comment by yeellow** [comment]
OK, I've disabled all extensions but python and the issue is still there.

**Comment by zy452608532** [comment]
same issue here... after update.. so what happened to the new update?

**Comment by dbaeumer** [comment]
Very likely caused by the Electron 8 update. Assigning to @deepak1556 and @mjbvz. Could be a combination with the WebView.

**Comment by deepak1556** [comment]
This issue is from webview, @mjbvz this repro is reliable

* Install python extension
* open a jupyter notebook file

The webview devtools has the error log

`Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME`

All the failed requests have url format `vscode-webview-resource://787e559f-185c-4d86-aebc-400191530e52/file///Users/demohan/.vscode-insiders/extensions/ms-python.python-2020.6.89148/out/datascience-ui/notebook/require.js`

The `file///` makes the scheme invalid, removing that should fix the error.

**Comment by sweettyler** [comment]
As I reported in "https://github.com/microsoft/vscode/issues/98354" and "https://github.com/microsoft/vscode/issues/100889", several insider versions showed the exact same issue. Don't know why.

**Comment by mjbvz** [comment]
Duplicate of #100879. Let me know this is not fixed in the next insiders build

**Comment by sweettyler** [comment]
@mjbvz the latest insider version (which was released 5 min ago) doesn't solve the blank window problem reported in https://github.com/microsoft/vscode/issues/100889.

**Comment by mjbvz** [comment]
@sweettyler This issue is about blank webviews, not about the entire window being blank. Please follow up on the original issue
