### ISSUE TITLE
Missing git file status icons with Remote-SSH

### ISSUE THREAD

**Issue by ShoshinNikita** [microsoft/vscode#103073]
Original [issue](https://github.com/microsoft/vscode-remote-release/issues/2703) was opened in [microsoft/vscode-remote-release](https://github.com/microsoft/vscode-remote-release) repo. But after 3 months of inactivity I decided to open a new one here. Especially, I think the problem lay in VSCode

- **VSCode Version:** 1.41.0-1.47.2
- **Local OS Version:** Windows 10
- **Remote OS Version:** Ubuntu 18.04.3

**Steps to Reproduce:**

1. Open any directory with git repository
2. Edit, remove or add file
3. Open `Source Control`
4. Icons are missing:

    ![image](https://user-images.githubusercontent.com/30220965/78702385-2b889e00-7911-11ea-8a2a-56616fea7290.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

***

It seems VSCode tries to load icons from remote machine:

![image](https://user-images.githubusercontent.com/30220965/78703058-3db70c00-7912-11ea-8d45-8a308ca24be8.png)

These icons do exist:

![image](https://user-images.githubusercontent.com/30220965/78703095-4e678200-7912-11ea-8a57-f47103440898.png)

If I change the path to local one an icon will appear:

![image](https://user-images.githubusercontent.com/30220965/78703449-d77eb900-7912-11ea-8a75-cbe7a44c9c37.png)

**Comment by joaomoreno** [comment]
I believe this got fixed earlier this year in https://github.com/microsoft/vscode-remote-release/issues/2115, strange that you still see it.

@mjbvz You might know more about the content policies which might block these requests. Can you help out here?

**Comment by ShoshinNikita** [comment]
Thanks a lot for the quick response! According to the discussion in [vscode-remote-release/issues/2115](https://github.com/microsoft/vscode-remote-release/issues/2115) there were 2 issues:

1. with usage of `string` instead of `UriComponents `. It **was** resolved in https://github.com/microsoft/vscode/commit/788cfa0767b37666827e670ac4b0d8440f29b531
2. with *Content Security Policy*. It **wasn't** resolved and has the separate issue - [vscode-remote-release/issues/2829](https://github.com/microsoft/vscode-remote-release/issues/2829)

**Comment by mjbvz** [comment]
@joaomoreno Our content security policy allows images from `vscode-remote-resource://` uris but not from `vscode-remote` uris. I believe other images in the UI are loaded over `vscode-remote-resource`, so there may be a bug with how we resolve the scm icon image paths

**Comment by joaomoreno** [comment]
> 1. with usage of `string` instead of `UriComponents `. It **was** resolved in [788cfa0](https://github.com/microsoft/vscode/commit/788cfa0767b37666827e670ac4b0d8440f29b531)

@alexdima [On the last episode](https://github.com/microsoft/vscode-remote-release/issues/2115#issuecomment-579970604). Switching from `string` to `UriComponents` did take us further, but didn't fix the entire issue. Do you know what needs to be done in order to get `vscode-remote-resource` instead of `vscode-remote` uris?

**Comment by alexdima** [comment]
@joaomoreno I'm sorry, it is weird how your code missed all the adoptions we did.

Whenever putting a resource URI coming in from an extension in the dom, we now need to use [`asDomUri`](https://github.com/microsoft/vscode/blob/cbb179a52a37dd5fc8fbaa6ca15b79008d7a5103/src/vs/base/browser/dom.ts#L1230) if you use it like `<img src="...">` or [`asCSSUrl`](https://github.com/microsoft/vscode/blob/cbb179a52a37dd5fc8fbaa6ca15b79008d7a5103/src/vs/base/browser/dom.ts#L1243) if you generate CSS.

I think this is the last piece of the puzzle.

**Comment by roblourens** [comment]
Dumb question, how do I get it to use the svg icons instead of what is apparently just text here?

![image](https://user-images.githubusercontent.com/323878/94878878-8a882500-0413-11eb-8c05-06819c64b2f7.png)

**Comment by joaomoreno** [comment]
Oh, right, disable `git.decorations.enabled`.
