### ISSUE TITLE
v1.49 creates debug.log automatically

### ISSUE THREAD

**Issue by hiredtocode** [microsoft/vscode#105191]
- VSCode Version:Version: 1.49.0-insider 
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Run VSCode and in working directory "debug.log" appears (not sure what creates it nor how to disable it.) which contains: 
```
[0818/104648.606:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0818/104652.360:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
``` 
Not sure what it means since there's no info on web about this specific error log so I can't reproduce this error on purpose. Sorry.
 
2. Added *.log to gitignore file which did the trick until I restarted Code and later I noticed that debug.log files on other directories are grayed out but my current working folder is white and it's getting updated in the Source Control tab. So, I added another gitignore command by making a "directory/debug.log". This works until the Code is restarted. 

![debug](https://user-images.githubusercontent.com/68050282/90935229-c061e300-e43d-11ea-9158-7ee5952fb412.JPG)

As you can see in the picture the debug.log file is grayed out but other one isn't . (all other debug.log files are all grayed out)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aquacash5** [comment]
Version: 1.49.0 (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

---

I think I have some helpful information. 

This happens whether or not you have extensions disabled, but it doesn't happen when both processes are run as **Administrator**.

Steps to Reproduce:
1) Open a project in _Visual Studio Code_.
2) Open a file that is rendered in color.
3) Open a second project in a new _Visual Studio Code_ window. Without closing the first window.
4) Open a file that is rendered in color in the second window.
5) A `debug.log` file should now exist in the directory of the file opened in the second _Visual Studio Code_ window.

Example:
1) Open `C:\Users\user\Documents\GitHub\awsome_project_1`.
2) Open `C:\Users\user\Documents\GitHub\awsome_project_1\package.json`.
3) Open `C:\Users\user\Documents\GitHub\awsome_project_2` in a new code window.
4) Open `C:\Users\user\Documents\GitHub\awsome_project_2\package.json`.
5) There is now a `C:\Users\user\Documents\GitHub\awsome_project_2\debug.log`

**Comment by leosdad** [comment]
It also happens without .gitignore present. It's happening in several of projects where I have no GIT integration. I found out that ESLint reports several such errors. Some examples:

```
[0911/174625.932:ERROR:registration_protocol_win.cc(103)] CreateFile: O sistema n�o pode encontrar o arquivo especificado. (0x2)
[0911/174710.611:ERROR:registration_protocol_win.cc(103)] CreateFile: O sistema n�o pode encontrar o arquivo especificado. (0x2)
```

(Incidentally, there are some character encondng errors as you can see above.)

Maybe you could also rename this issue to something like [v1.49 creates debug.log automatically](https://github.com/microsoft/vscode/issues/106474).

**Comment by ent3r** [comment]
Seems to happen any time you open any directory at all. For me its enough to open a folder, and its created:

```log
//debug.log
[0911/231918.764:ERROR:registration_protocol_win.cc(103)] CreateFile: Systemet finner ikke angitt fil. (0x2)
```

**Comment by bbaltutat** [comment]
Creates in multiple directories.
[0911/172355.455:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0911/172357.298:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0911/172357.540:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)

**Comment by rkeithhill** [comment]
This is super annoying.  You can delete the file but it comes right back.

**Comment by Dam1ran** [comment]
It seems that this bug is not reproducing(at least for now trying) after installing User Version:

![Screenshot 2020-09-14 095811](https://user-images.githubusercontent.com/53400364/93053715-e8c1b380-f670-11ea-886f-e53b01d3c5a4.png)

I will update if it happens again.

**Comment by ericrichtert** [comment]
I just upgraded to 1.49, and I have the same issue. 

Version info:
Version: 1.49.0 (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by artaommahe** [comment]
Can we do smth with this? :/ it's very annoying.. file is created for any selected folder in second vscode window
![image](https://user-images.githubusercontent.com/1944061/93079564-ff7a0180-f694-11ea-9a8d-8566f055a056.png)

Also it's adding more lines to this file (mb on each folder access)

Version: 1.49.0 (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by glek** [comment]
I might have found a workaround for this issue. I'm not sure what's causing it, but changing the permissions on the folder `C:\Program Files\Microsoft VS Code Insiders` seems to have made the issue go away. What I changed was:

1. Open the folder properties
2. Go to the security tab
3. Click `Edit` -> `Add...`
4. Add my user
5. Give my user the `Full Control` permissions

I no longer get the `debug.log` mysteriously spawning in my workspaces, at least with my limited testing.

```
Version: 1.49.0-insider (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-09T08:15:09.223Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by cecilemuller** [comment]
Perhaps a clue, I noticed it doesn't always create the debug.log file:
 - if I create an empty `.md` text file in Windows Explorer, then drag-drop it in VSCode, it creates a `debug.log` in the folder
 - however if I do the exact same thing with a `.txt` file, no debug.log file gets created

**Comment by TriStarGod** [comment]
This issue also has started occurring after updating vscode. It would sporadically generated debug.logs on some of folders in my existing repositories that I pulled for recent updates.

A work around I am using is to rename/delete the existing local repository and git clone the repository. No debug.logs.

**Comment by bbaltutat** [comment]
I recently installed the settings sync right before this started happening. I have located '[0914/144720.188:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)' errors in the output window in several extensions. I am attempting to walk through each of them to see if I can fix the problem.

**Comment by deepak1556** [comment]
I am looking to repro this issue on my machine, seems like everyone affected here has a system install , does it not repro when you have a user install ?

I am unable to repro with the following steps

* Install system version of code
* Open any project using `code.cmd <path>`
* check for presence of debug.log in the working directory


Is there some step I am missing ? Also those logs are from the runtime chromium and not the app vscode, but they should not be generated unless a debug version of the runtime is used.

**Comment by bbaltutat** [comment]
I am running the system install. not a debug, not an insider version. i have gotten it to stop. I have had to disable all of the extensions and rebooted the computer. I had tried reinstalling the system install over the top originally but that didnt help. The errors appeared to happen in 1 of 2 places. At startup when extensions were initialized, or when a certain file type was open and it was associated with it. As i said before, I had recently added the system sync functionality. The issues appear that they could have been related to that and/or merging the settings at the beginning from multiple workstations. 

I have not enabled any extensions yet to see if they come back again. Thats what I will be doing next.

**Comment by artaommahe** [comment]
> Is there some step I am missing

for me it's happening only in second vscode window. Everything is fine in the first one.

**Comment by deepak1556** [comment]
Thanks @artaommahe that helped, have a reliable repro now

* Install system code
* Open project1 with code.cmd <path> --disable-extensions
* Open project2 with code.cmd <path> --disable-extensions
* Open a `.md` file in project2 (for now this is the file I was able to see repro)
* `debug.log` generated in the working directory

**Comment by JohnnyDevNull** [comment]
> > Is there some step I am missing
> 
> for me it's happening only in second vscode window. Everything is fine in the first one.

Same here, only in second vscode window + system install

**Comment by Aravin** [comment]
I am also getting the same debug.log everything where I start the applications.

`debug.log`
```
[0914/101119.781:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0914/101120.409:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0914/101146.995:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0914/110623.984:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0914/110624.809:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0914/125059.341:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0915/102026.138:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0915/102026.977:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0915/114404.743:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0915/114405.534:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0915/120953.237:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)

```

**Comment by deepak1556** [comment]
The issue has been narrowed down, will update here once the fix is available. It would be better if further reports are avoided and instead subscribe to the issue for updates. Thanks!

**Comment by najimali** [comment]
Getting the same ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file spec
The system cannot find the file specified. (0x2) only when I am opening two projects in vs code without closing the first window.

For me **issue is resolved by closing both the project & restarting the only one project.**

**Comment by starjet** [comment]
Happening after the August update which hit just now. Incredibly annoying.

**Comment by katlimruiz** [comment]
+1

**Comment by amroczeK** [comment]
Still getting the issue. NOTE: This is happening on work laptop, permissions are locked down heavily and I have to open installers with '(Avecto) Run with elevated privileges'. Will remove my group policies and test again after.

Version: 1.49.0 (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by abhijit-hota** [comment]
It's like this for me:
- Open a folder.
- Go to a subdirectory (or root, doesn't matter)
- Open a file.
- A `debug.log` appears with the following message:

```log
[0917/125412.476:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
```
Every time I open a file, the corresponding `debug.log` file gets updated with a new line with the same message.

**Comment by Aravin** [comment]
This issue fixed if I ran with administrator permission.

**Comment by alokraj68** [comment]
The only workaround now is to either run using admin privileges or add debuug.log to .gitignore

**Comment by Aravin** [comment]
Adding `debuug.log` to .gitignore is not a solution.

File is keep on adding cause confusion.
@alokraj68

**Comment by Ciantic** [comment]
One way to fix this is reinstall the VSCode using the "User setup" instead of "System setup". It will give more permissions to the files.

**Comment by jackieldev** [comment]
Yesterday I opened how administrator and worked.
Today I opening normally and .log does not comes.

**Comment by umairkhan-dev** [comment]
Issue still persists after 1.49.1 update.
```
Version: 1.49.1 (system setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

> The only workaround now is to either run using admin privileges or add debuug.log to .gitignore

> Yesterday I opened how administrator and worked.
> Today I opening normally and .log does not comes.

BTW, Can't open another instance of VSCode if one is already running using admin privileges.
![image](https://user-images.githubusercontent.com/16460954/93593205-1d18d500-f9cd-11ea-9b6d-758baf10746e.png)

**Comment by bbaltutat** [comment]
> Issue still persists after 1.49.1 update.
> 
> ```
> Version: 1.49.1 (system setup)
> Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
> Date: 2020-09-16T23:27:51.792Z
> Electron: 9.2.1
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.19041
> ```
> 
> > The only workaround now is to either run using admin privileges or add debuug.log to .gitignore
> 
> BTW, Can't open another instance of VSCode if one is already running using admin privileges.
> ![image](https://user-images.githubusercontent.com/16460954/93593205-1d18d500-f9cd-11ea-9b6d-758baf10746e.png)

You have to open additional windows from within the existing instance.

**Comment by cbprosser** [comment]
I too am having this error.
`Version: 1.49.1 (system setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:23:38.048Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT ia32 10.0.19041`

I notice that the output terminal is showing the logs are coming from JSON Language Server. Perhaps that can help narrow things a little?
![image](https://user-images.githubusercontent.com/52571711/93687938-038c9180-fa90-11ea-9083-e8cdbac54683.png)

**Comment by Ciantic** [comment]
@cbprosser I don't think it will. For instance I get the error inside PHP Language Server too: ![image](https://user-images.githubusercontent.com/64731/93588708-732d4e80-f9b4-11ea-9a77-2920521c00ac.png)

**Comment by deepak1556** [comment]
This will be fixed in next recovery release this week `1.49.2`. I am locking the issue since no new information is required. Thanks for the inputs so far.

**Comment by deepak1556** [comment]
`1.49.2` has been released with the fix, please update and verify. Thanks all for the patience!

**Comment by Projkt-James** [comment]
Update looks to be the goods, after testing various actions in 2 projects.

**Comment by JW9506** [comment]
Good stuff

**Comment by DaelonSuzuka** [comment]
Multiple projects that were getting debug.log are now behaving properly. 

Thank you guys very much for fixing this so promptly.

**Comment by flyq** [comment]
I'm going crazy with these endless debug.logs, Fuck

**Comment by ZukenHammer** [comment]
> I'm going crazy with these endless debug.logs, Fuck:
> 
> #105161

Why didn't you go back to version 1.48.2? Now just install 1.49.2.

**Comment by starjet** [comment]
It appears the update has indeed fixed this problem. Thank you.

**Comment by ent3r** [comment]
Seems this issue has been resolved, and I'm suggesting that the issue is locked to prevent additional "This update fixed it, thanks" style comments.
