### ISSUE TITLE
Integrated Terminal Lags Intermittently 

### ISSUE THREAD

**Issue by davidzech** [microsoft/vscode#105446]
- VSCode Version: 1.48.2(macOS Stable)
- OS Version: macOS Big Sur 11.0 Beta (20A5354i) (Public Beta Release 2)

Steps to Reproduce:

1. Open Terminal
2. ~~Spam random keys until lag is experienced~~ Press enter, then continuously type (anything) for about 2 seconds.
3. Experience a very long stutter

Does this issue occur when all extensions are disabled?: Yes

This occurs on a public beta build of macOS 11. I've confirmed the same issue on two different MacBook Pro's on the same OS version, and same VS Code version.

Attached is a performance profile. You can see the spike in the integrated terminal response time at around 23000ms - 24000ms

![image](https://user-images.githubusercontent.com/1009039/91350255-457d2d00-e79b-11ea-9b9b-f644dc1af082.png)

[Profile-20200826T124154.json.zip](https://github.com/microsoft/vscode/files/5132524/Profile-20200826T124154.json.zip)

**Comment by davidzech** [comment]
It seems like https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/workbench/contrib/terminal/node/terminalProcess.ts#L276
is taking a long time.

**Comment by davidzech** [comment]
Benchmarking this call, it takes on average 800ms. It doesn't make sense, but this seems to be a `Node.js x macOS beta` type of issue.

**Comment by nerdthatnoonelikes** [comment]
I have been having this issue as well with the insiders build of vscode

**Comment by Tyriar** [comment]
@deepak1556 do you know why an `exec` call would be blocking the thread?

**Comment by davidzech** [comment]
Some further notes for reference:

Monkey patching
https://github.com/microsoft/vscode/blob/a4befc3d68695645063a257493eec7957d4f7064/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1194

to be 
```suggestion
async() => { this._updateProcessCwd(); }
```

Seems to fix the terminal from being blocked. It's still a bandaid over the underlying problem, which is `child_process.exec()` taking a long time to execute on macOS Big Sur Beta.

**Comment by matinzd** [comment]
I have this issue either. +1

**Comment by tolgaerdonmez** [comment]
> +1
> I have this issue either and it happened after updating to macOS 11 (Big Sur) beta. I am currently on beta 9 and the issue still exists.
> 
> ```
> Version: 1.50.0
> Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
> Date: 2020-10-07T06:00:00.397Z (6 days ago)
> Electron: 9.2.1
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Darwin x64 20.1.0
> ```

It also occurred with me after updating to Big Sur Beta, I think it is about the beta.

**Comment by davidzech** [comment]
Some further insights:

I have done some debugging with `lldb`, and have narrowed it down to `fork()` being the bottleneck here.

**Comment by Vardiak** [comment]
@davidzech Don't you think this might be a bug from the macOS kernel then?

**Comment by Adam2Marsh** [comment]
+1 for having this issue; only remember seeing this issue after upgrading to Big Sur. Happy to run some debugging if anyone has any ideas.

Thanks.

**Comment by davidzech** [comment]
@Adam2Marsh Have you built locally? To my surprise, I ran my tests on `master` and tag `1.50.1` and I do not experience this lag at all, yet is persistent in both Stable and Insider public releases.

An useful bisection perhaps.

**Comment by KangDroid** [comment]
@davidzech 
+1 Agree, I built Code-OSS[master branch] with macOS 11.0.1[build = 20B5012d]
and I see no problem with input-lag with integrated terminal. Only for local build.
Public version of vscode still has that problem tho.

**Comment by deepak1556** [comment]
Thanks for narrowing down the issue @davidzech , we do use a custom electron build for the stable and insiders while we use https://electronjs.org/ releases for the OSS build. But I don't see any patches around the child_process code path.

Can you run the test on following electron builds, you can extract and run the electron binary, toggle developer tools from the View menu

* [Custom electron build v9.3.3](https://github.com/deepak1556/electron-debug-version/releases/download/v9.3.3/electron-v9.3.3-darwin-x64.zip)
* [OSS electron build v9.3.3](https://github.com/electron/electron/releases/download/v9.3.3/electron-v9.3.3-darwin-x64.zip)

**Comment by KangDroid** [comment]
@deepak1556 

I've done some quick-test, by swapping Electron binaries on latest stable release vscode, both custom electron | oss electron. The issue still remains. 

Also I bulit vscode-darwin[oss package] and swapped electron binaries with custom electron version, there is no issue at all.
Which might indicates it is not the problem of electron[perhaps?]

**Comment by deepak1556** [comment]
> Also I bulit vscode-darwin[oss package] and swapped electron binaries with custom electron version, there is no issue at all.
Which might indicates it is not the problem of electron[perhaps?]

Interesting, then this might indicate the problem is with a packaged app vs running out of sources. @davidzech are you aware of any entitlement changes that would impact this ?

**Comment by davidzech** [comment]
@deepak1556 I am not aware of anything intentional, but I can confirm that stripping code signature from `Code Helper (Renderer)` makes the problem go away. 

So unfortunately, it looks like my guess from https://github.com/microsoft/vscode/issues/107103#issuecomment-696454728 looks to be accurate.

**Comment by deepak1556** [comment]
I don't think there is much to debug on electron or vscode end, would like to report this issue to apple. What is best way to do it ?

**Comment by bmstefanski** [comment]
Last os update resolves the issue for me

OS: macOS Big Sur 11.0.1 20B5022a x86_64
Kernel: 20.1.0
VSCode: 1.51

**Comment by flash-gordon** [comment]
I cannot confirm this, installed the latest beta yesterday. The termial had been laggish until I stripped the signature.

**Comment by yay** [comment]
The issue persists with the latest macOS 11.0.1 RC2 released today. Stripping the signature helped though.

**Comment by marcello3d** [comment]
This looks similar to a problem we found: https://github.com/electron/electron/issues/26143

It seems to an Electron bug since it's reproducible when using child_process.spawn in the renderer process but not in main

**Comment by matinzd** [comment]
This may be an Electron bug since we had these problems on Big Sur when on release.

**Comment by Zehua-Chen** [comment]
I am on macOS Big Sur 11.0.1. In addition to the terminal freezing, every time I switched back to the code editor from the terminal, the code editor would also freeze.

**Comment by jaikens19** [comment]
Having the same issue on VSCode as well. Upgraded to Big Sur from Catalina last night and started having the freezing issue instantly.

**Comment by paulfsheridan** [comment]
@jaikens19 Same issue here.

**Comment by jaikens19** [comment]
@paulfsheridan @davidzech suggested running this in terminal: `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`

it ended up fixing the issue for me.

**Comment by findtravishere** [comment]
Same issue, thought there was something wrong with my laptop. On top of the delay in the terminal, i'm experiencing delay while typing and backspacing continuously both in terminal and while working on any files.

**Comment by etpstevenk** [comment]
I am experiencing the same

**Comment by paulfsheridan** [comment]
@jaikens19, unfortunately, had no luck with this. Thanks though.

**Comment by caburj** [comment]
> @paulfsheridan @davidzech suggested running this in terminal: `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`
> 
> it ended up fixing the issue for me.

This worked for me.

**Comment by itsjoeoui** [comment]
> @paulfsheridan @davidzech suggested running this in terminal: `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`
> 
> it ended up fixing the issue for me.

I can confirm this worked for me as well!

**Comment by tolgaerdonmez** [comment]
> @paulfsheridan @davidzech suggested running this in terminal: `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`
> 
> it ended up fixing the issue for me.

This also worked for me, thanks!

**Comment by kwent** [comment]
Above fix works for me as well. Don't forget to relaunch vscode.

**Comment by pixelomer** [comment]
> @paulfsheridan @davidzech suggested running this in terminal: `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`
> 
> it ended up fixing the issue for me.

This fix seems to work for me as well.

**Comment by matinzd** [comment]
> @paulfsheridan @davidzech suggested running this in terminal: `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`
> 
> it ended up fixing the issue for me.

This workaround worked for me too ;)

**Comment by lenaschimmel** [comment]
Has anybody checked if this is related to [Apple's recent usage of OSCP to check the validity of developer certificates](https://blog.jacopo.io/en/post/apple-ocsp/) when launching an executable? According to that blog post, this should only happen once for each executable, so I guess this is something else. Also, maybe I'm mixing up signatures and certificates here?

**Comment by marcello3d** [comment]
@lenaschimmel: yea, I looked at that, and it appears to be unrelated. it happens even if wifi/ethernet are off, and it's only reproducible in the electron renderer process, not the main process

**Comment by rhyek** [comment]
Are there any drawbacks to removing the signature as suggested? Perhaps related to future updates?

**Comment by herberthobregon** [comment]
You’re just removing the signature from the original app. Signatures are meant to prove the app came from a certain developer. If you know that this app you downloaded is legit, then there is no danger in removing the signature. `I GUESS` ⚠️⚠️⚠️⚠️.

**Comment by memeplex** [comment]
I'm having this issue in Big Sur and removing signature as suggested above "fixes" it.

**Comment by aviramha** [comment]
Affected also by this

**Comment by dylvaz** [comment]
I tried ran the command `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app` and am still experiencing lagging in terminal. On macOs 11.0.1.

**Comment by JeffreyCA** [comment]
> I ran the command `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app` and am still experiencing lagging in terminal. On macOs 11.0.1.

Did you relaunch VS Code?

**Comment by karlhorky** [comment]
> Did you relaunch VS Code?

I did, when I tried this out. It also didn't seem to do anything.

**Comment by dylvaz** [comment]
> > I ran the command `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app` and am still experiencing lagging in terminal. On macOs 11.0.1.
> 
> Did you relaunch VS Code?

Don't hurt me but it worked after I relaunched lol.

**Comment by piotrsynowiec** [comment]
> I ran the command `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app` and am still experiencing lagging in terminal. On macOs 11.0.1.

It's lagging as it was, and now Little Snitch tells me that VSCode is not signed and it's probably a malware.

Could you share with me how can is sign it again? Re-Installing the app didn't change much.

**Comment by davidzech** [comment]
On macOS 11.0.1, `fork()` seems to physically copy all JIT memory regions (no-copy-on-write). On previous OS, these regions weren't accessible at all in the forked process, sort of explaining the _"regression"_. 

You can test by making a lot of `mmap()` calls with `MAP_JIT`, and then calling `fork()` in a playground project. (make sure you have `com.apple.security.cs.allow-jit` entitlement)

It would be nice if `libuv` used `posix_spawn` instead.

**Comment by deepak1556** [comment]
Aha that would also explain why the issue is not seen for child processes forked from browser process as reported by @marcello3d in the electron issue. The reason being until recently https://github.com/electron/electron/pull/26331 we have been using a different memory allocator on the browser process that doesn't `MAP_JIT` regions allocated, hence fork didn't have JIT regions to copy over. If this is true, @marcello3d you should see this issue in browser process with nightly release of electron https://www.electronjs.org/releases/nightly, can you confirm ?

> It would be nice if libuv used posix_spawn instead.

@davidzech there seems to be an active issue about using `posix_spawn` for a different scenario on all platforms https://github.com/libuv/libuv/issues/2133 , lets make this suggestion in the electron thread so that the team can drive the effort to make the change atleast on macOS to circumvent this issue.

**Comment by srubin** [comment]
@deepak1556  Yes, I just confirmed that the problem exists in the browser process (electron "main") with the latest nightly.

**Comment by deepak1556** [comment]
thanks for confirming!

**Comment by jchappelle** [comment]
This started happening for me when I upgraded to macOS Big Sur 11.0.1. Here's the vscode version info.
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (1 wk ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0
```

**Comment by wulorn** [comment]
> > @paulfsheridan @davidzech suggested running this in terminal: `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`
> +1  thanks.

**Comment by flash-gordon** [comment]
Pls stop posting "it works"/"it helped me" comments, use 👍

**Comment by deepak1556** [comment]
Since we have narrowed down the root cause and the next step is to get a fix up in libuv. I am going to lock this thread to reduce noise, will reopen once fix is available to verify. Thanks all!

**Comment by Tyriar** [comment]
@deepak1556 I wasn't able to test it, but I've disable this `lsof` call on Big Sur+, here's the workaround that we will want to remove when the fix lands in Electron:

https://github.com/microsoft/vscode/commit/d964664da291f28372a02d3d7ce82d650a98c890

All this should do is disable current working directory-based links, so relative links will only work from the initial directory. This won't work for example:

```
cd src 
echo './somefile'
```

**Comment by deepak1556** [comment]
Thanks @Tyriar , I am opening the issue for users to verify the temporary fix.

**Comment by akshajmody** [comment]
This issue is still persisting for me. In general I'm noticing a small lag in typing even when using Slack but definitely the most lag is with VScode terminal where it freezes for a whole second or so every now and then.

**Comment by richardsimko** [comment]
@deepak1556 Has the fix been shipped? Because I've noticed things have gone back to normal but I don't know if it's related to me removing the code signature from all VSCode Helper apps or if it's thanks to this.

**Comment by m1nkeh** [comment]
I don't think so @richardsimko , unless it's in the insiders build?

**Comment by otimong** [comment]
Insiders build is still laggy for me

**Comment by nuBacuk** [comment]
it helped me https://shageevan.medium.com/vs-codes-in-built-terminal-is-slow-or-laggy-on-macos-big-sur-d5867a7d9771

**Comment by piotrsynowiec** [comment]
Unfortunately it doesn't work for me, but I have a question – is removing this signature a good choice in terms of security measures?

**Comment by nuBacuk** [comment]
completely restarted the application?

**Comment by nuBacuk** [comment]
> Unfortunately it doesn't work for me, but I have a question – is removing this signature a good choice in terms of security measures?

completely restarted the application?

**Comment by piotrsynowiec** [comment]
> > Unfortunately it doesn't work for me, but I have a question – is removing this signature a good choice in terms of security measures?
> 
> completely restarted the application?

I've restarted the app & the mac. The app is still laggy.

**Comment by focused** [comment]
The command `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app` worked for me, but each time after restart I need to execute it again.

**Comment by deepak1556** [comment]
Thanks for the reports, we will soon have a fix from electron and libuv for this issue, will report back once the fix has been released.

**Comment by MaciekBaron** [comment]
Had the same issue and signature removal worked for me. Just wanted to add that the same issue was present when performing a file search, or doing a search and replace, and this was also fixed by the command.

**Comment by carlosamoreno** [comment]
Just my two cents: the command listed above helped, I don't have the lag anymore, but it broke some of my VSCode configuration, like fonts, terminal... so be careful if you execute it!

**Comment by docwhat** [comment]
The call to `lsof` could be replaced with a [simple C program](https://gist.github.com/docwhat/03a77a3950a696b2bc243a6df005128f):

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <libproc.h>

// Works on macOS using libproc.

int main(int argc, char *argv[])
{
  int ret;
  pid_t pid;
  char pathbuf[PROC_PIDPATHINFO_MAXSIZE];
  struct proc_vnodepathinfo vpi;

  if (argc == 2)
  {
    pid = (pid_t)atoi(argv[1]);
    ret = proc_pidinfo(pid, PROC_PIDVNODEPATHINFO, 0, &vpi, PROC_PIDVNODEPATHINFO_SIZE);
    if (ret <= 0)
    {
      fprintf(stderr, "%s\n", strerror(errno));
      return 1;
    }
    printf("%s\n", vpi.pvi_cdir.vip_path);
  }
  else
  {
    printf("Usage: %s <pid>\n\n", argv[0]);
    printf("Print the current working directory for <pid> to stdout.\n");
  }

  return 0;
}
```

**Comment by dikshantpatodia** [comment]
I don't think its a good idea to remove the signature.

Instead do the following:
1. Open terminal in VS code
2. Open to-right dropdown in terminal and select `Configure Terminal Settings`
3. In first option check **Terminal: Explorer Kind** and select `external`

Problem solved, will update here if I find any lag issue (currently not at all), just try this out

**Comment by dikshantpatodia** [comment]
I don't think its a good idea to remove the signature.

Instead do the following:
1. Open terminal in VS code
2. Open to-right dropdown in terminal and select `Select Default Shell`
3. Here select **sh** `/bin/sh`

Problem solved, will update here if I find any lag issue (currently not at all), just try this out

**Comment by MaciekBaron** [comment]
I don't think removing the signature can cause any harm, its main purpose is to secure software distribution and verifying the original executable. Once you have downloaded the verified executable and removed the signature, this shouldn't open up any security holes, unless your system is already infected.

I might be wrong though - would be nice to learn if there is a possible attack vector here.

**Comment by sergerad** [comment]
> I don't think its a good idea to remove the signature.
> 
> Instead do the following:
> 
> 1. Open terminal in VS code
> 2. Open to-right dropdown in terminal and select `Select Default Shell`
> 3. Here select **sh** `/bin/sh`
> 
> Problem solved, will update here if I find any lag issue (currently not at all), just try this out

Many users will want to use bash or zsh for example (myself included). So this is not an appropriate solution in those cases.

**Comment by wjv** [comment]
I think this may be a system-wide issue, rather than one specific to VSCode or even Electron. (I could speculate that VSCode in particular and Electron in general do something that causes them to be severely impacted.)

I recently switched to a 2019 16" MBP running Big Sur (from a 2014 15" running Catalina), and immediately noticed inconsistent keyboard lag in practically all apps. (Caveat: I'm a fairly quick touch typist.)

The lag is particularly noticeable when working in the shell under Terminal.app. Try this: Simply hit `ls<enter>` a number of times, waiting after each invocation to see what happens. Within the first ~20 invocations, one should encounter an instance where it takes ~8 seconds for the output of `ls` to appear. (That seems to be consistent with the delay measured in electron/electron/issues/26143.)

Bizarrely, the issue disappears entirely if one forces the use of the discrete GPU by disabling automatic graphics switching, as referenced in #110683.

I tried to see if @davidzech's suggestion of disabling code signing seems to be applicable to the system-wide problem, and it does seem to be. I installed an (unsigned) zsh binary from Homebrew. When using this instead of the (signed) `/bin/zsh`, it becomes nearly impossible to replicate the issue as long as one invokes only other unsigned binaries (e.g. a manually built GNU ls instead of the signed `/bin/ls`.)

**Comment by leafac** [comment]
@wjv I typed `ls<enter>` more than 20 times and couldn’t reproduce what you described.

**Comment by clouedoc** [comment]
I couldn't reproduce typing `ls<enter>` multiple times.

**Comment by itstrueimryan** [comment]
> I think this may be a system-wide issue, rather than one specific to VSCode or even Electron. (I could speculate that VSCode in particular and Electron in general do something that causes them to be severely impacted.)
> 
> I recently switched to a 2019 16" MBP running Big Sur (from a 2014 15" running Catalina), and immediately noticed inconsistent keyboard lag in practically all apps. (Caveat: I'm a fairly quick touch typist.)
> 
> The lag is particularly noticeable when working in the shell under Terminal.app. Try this: Simply hit `ls<enter>` a number of times, waiting after each invocation to see what happens. Within the first ~20 invocations, one should encounter an instance where it takes ~8 seconds for the output of `ls` to appear. (That seems to be consistent with the delay measured in [electron/electron/issues/26143](https://github.com/electron/electron/issues/26143).)
> 
> Bizarrely, the issue disappears entirely if one forces the use of the discrete GPU by disabling automatic graphics switching, as referenced in #110683.
> 
> I tried to see if @davidzech's suggestion of disabling code signing seems to be applicable to the system-wide problem, and it does seem to be. I installed an (unsigned) zsh binary from Homebrew. When using this instead of the (signed) `/bin/zsh`, it becomes nearly impossible to replicate the issue as long as one invokes only other unsigned binaries (e.g. a manually built GNU ls instead of the signed `/bin/ls`.)

I've been experiencing this since upgrading to Big Sur (16 inch, 2019 Mac). It's driving me crazy.

**Comment by wjv** [comment]
@leafac and @clouedoc, thanks for testing that. Are you saying that you _are_ observing the VSCode behaviour that’s the subject of this Issue, but _not_ seeing the problem in Terminal (or elsewhere)? Also, are you sure that you’re currently using the integrated Intel GPU?

The fact that this isn’t much more widely reported makes me think it only affects certain hardware configurations. But if you’re definitely seeing the VSCode issue and at the same time no keyboard lag anywhere else — especially not at the shell in Terminal — then my guess could be wrong and these issues are not connected. (But that would seem odd, since both issues seem to be addressed by using non-signed code.)

@itstrueimryan, sounds like you’re seeing the same thing I am, on a very similar hardware config. Does forcing the use of the discrete GPU (by disabling automatic graphics switching) make it better?

**Comment by leafac** [comment]
> Are you saying that you _are_ observing the VSCode behaviour that’s the subject of this Issue, but _not_ seeing the problem in Terminal (or elsewhere)?

👍 Exactly.

What fixed the issue for me was running `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`. I tested Terminal.app after having ran this (but it shouldn’t matter, because Terminal.app has nothing to do with Code Helper (Renderer).app).

> Also, are you sure that you’re currently using the integrated Intel GPU?

I suppose I am because that’d be the only option:

<img width="698" alt="Screen Shot 2021-01-23 at 20 23 53" src="https://user-images.githubusercontent.com/586813/105613191-16ee9700-5db9-11eb-8b79-79a357e06598.png">

How do I check?

**Comment by clouedoc** [comment]
I thought that my Mac was defective too. It's a 16" 2020 I've got with a
discount on Amazon.
I'm using integrated graphics
I can't reproduce the issue either on Terminal.app or vscode anymore.

The issue also happened in other apps, such as Chrome when typing in the
address bar.
The issue also happened while typing code in the editor window.
I used the temporary codesign fix and it worked fine. It has been driving
me crazy too. I even contacted Amazon for an exchange (which they refused
unless I sent my mac + password to their repair center...)

I don't really experience the issue anymore, even after updating VSCode and
restarting my device.

What changed:
- Now, I mainly use my mac unplugged -> it uses the integrated graphics card
- Mac OS X updated itself

*Forcing usage of the dedicated graphics cards using gfxCardStatus has no
effect.* So all good on my end.

[image: image.png]

**Comment by ArthurGuez** [comment]
I've also been experiencing lags using VS Code integrated terminal or Spotlight since I updated my Macbook Air (Early 2014) to Big Sur. Removing VS Code signature seemed to work for a while but that's no longer the case...

**Comment by pdkovacs** [comment]
Re possible system-wide issue brought up by @wjv :
Since upgrading to Big Sure, I am experiencing a terrible lag during login with a MacMini most recent Magic Keyboard combo.  Even characters are dropped when entering my password, so I have to type characters at least 1 second (sometimes longer) apart to make sure each of them gets registered. Note that FileVault is turned on, so the login is preceding any actual system startup activity. (My password is needed to unlock the system files as well, AFAIK.)

**Comment by d-malashin** [comment]
> What fixed the issue for me was running `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`.

this helped me with lags and slow terminal open

**Comment by nkaminski** [comment]
> I think this may be a system-wide issue, rather than one specific to VSCode or even Electron. (I could speculate that VSCode in particular and Electron in general do something that causes them to be severely impacted.)
> 
> I recently switched to a 2019 16" MBP running Big Sur (from a 2014 15" running Catalina), and immediately noticed inconsistent keyboard lag in practically all apps. (Caveat: I'm a fairly quick touch typist.)
> 
> The lag is particularly noticeable when working in the shell under Terminal.app. Try this: Simply hit `ls<enter>` a number of times, waiting after each invocation to see what happens. Within the first ~20 invocations, one should encounter an instance where it takes ~8 seconds for the output of `ls` to appear. (That seems to be consistent with the delay measured in [electron/electron/issues/26143](https://github.com/electron/electron/issues/26143).)
> 
> Bizarrely, the issue disappears entirely if one forces the use of the discrete GPU by disabling automatic graphics switching, as referenced in #110683.
> 
> I tried to see if @davidzech's suggestion of disabling code signing seems to be applicable to the system-wide problem, and it does seem to be. I installed an (unsigned) zsh binary from Homebrew. When using this instead of the (signed) `/bin/zsh`, it becomes nearly impossible to replicate the issue as long as one invokes only other unsigned binaries (e.g. a manually built GNU ls instead of the signed `/bin/ls`.)

+1 on this being a system-wide issue affecting the 2019 MBP; I experience **identical** behavior in both VSCode as well as iTerm and Terminal.app since updating to Big Sur on my 2019 16" MacBook Pro as well. 

Issue has been reproducible across all public and beta releases from 11.0 to 11.2 and forcing discrete GPU usage by disabling automatic graphics switching prevents the issue from happening.

**Comment by ujwal-setlur** [comment]
How do you disable this?

**Comment by stellirin** [comment]
I also see the issue 'system wide', VSCode is simply the place I see it most, most notably in the integrated terminal. GPU usage is likely a placebo / red herring, I use two 4K monitors over usb-c with my MacBook Pro, which forces discrete graphics at all times, and I have the issue.

Removing the signature did appear to help for a while, but VSCode updated itself and I haven't run the command again since then.

**Comment by alexus1024** [comment]
I have experienced the problem too.

- vscode Version: 1.52.1 (and in older versions for a half of the year)
- macOs Big Sur 11.1 (20C69)
- MacBook Pro (16-inch, 2019)

Steps to reproduce:
1. open integrated terminal in vscode
2. press any letter continuously 
3. after ~10 repetitions of letter there will be a hang for a second. THe hang does not repeat while on the same line.
5. press enter and try again. There will be hang again.

Tried with "terminal.integrated.shell.osx": "/bin/zsh" and "/bin/bash". Hang appears in both.

Command `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app` solved an issue for me. Maybe until next vscode udate.

**Comment by nkaminski** [comment]
@ujwal-setlur
To turn off automatic graphics switching, go to system preferences > Battery > Automatic Graphics Switching and uncheck the box.

Be aware that this results in a ~30%

**Comment by jonjaques** [comment]
> +1 on this being a system-wide issue affecting the 2019 MBP; I experience **identical** behavior in both VSCode as well as iTerm and Terminal.app since updating to Big Sur on my 2019 16" MacBook Pro as well.
> 
> Issue has been reproducible across all public and beta releases from 11.0 to 11.2 and forcing discrete GPU usage by disabling automatic graphics switching prevents the issue from happening.

Sorry to add a layer of complication to this, but I have discrete graphics switching disabled (2018 mbp) for battery and power adaptor (pre-update). This term lag issue exists for me in vscode since Big Sur, but not in iterm - though I do subscribe to the beta channel of iterm and have a variety of custom settings 🤷 

`codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app` did the trick as others have suggested.

**Comment by ay0o** [comment]
On MacBook Pro Retina 15" (Mid 2015), I can confirm this is not system-wide, only on VSCode.

iTerm2 is as smooth as ever. However, I had to use the `codesign` command mentioned throughout the issue to make the VSCode's built-in terminal usable again, otherwise it was a very unpleasant experience.

**Comment by docwhat** [comment]
Does anyone have a theory for why removing the signature "fixes" the problem that we can test?

**Comment by sveggiani** [comment]
@docwhat perhaps every executed process is being validated by macOs trustd service?

**Comment by docwhat** [comment]
How could we test that?

**Comment by marcello3d** [comment]
FYI the root cause has already been tracked down and being fixed in libuv/electron, see: 
- https://github.com/microsoft/vscode/issues/105446#issuecomment-730342806 (a comment on this issue)
- https://github.com/electron/electron/pull/27026
- https://github.com/libuv/libuv/pull/3064

**Comment by pdesantis** [comment]
To piggyback on what @marcello3d said, this was affecting our own Electron app, so we built a custom version of Electron using that libuv patch and it solved the issue for us. Hopefully this will be merged upstream soon, but in the meantime, other developers can try building Electron with that patch.

**Comment by deepak1556** [comment]
Thanks @marcello3d @pdesantis for the work on fix.

Just to update, whenever upstream releases a new version with the patch vscode will update to it. Also we didn't build the patch internally because it was too late in the current January iteration to get enough testing before stable release `1.53` that will happen next week. We will get this fix in to our internal builds next February iteration for early testing if there is no release from upstream.

I see that the issue is getting side tracked again, will lock until further updates.

**Comment by deepak1556** [comment]
The libuv fix has been backported internally and is available in latest insiders, please verify if this issue is fixed. Thanks!

**Comment by deepak1556** [comment]
\closedWith ff85144fdd3244ffe4a5da08354667c7e57e45ef

**Comment by davidzech** [comment]
/verified

Insiders Build 52838cf6799cc448e738677ec37e86cf62a5bd89:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/1009039/107074579-c8200480-679d-11eb-89a2-86bd264d276d.png">

Current Stable Build 8490d3dde47c57ba65ec40dd192d014fd2113496:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/1009039/107074634-dbcb6b00-679d-11eb-95b4-3d989ffaf860.png">

**Comment by m1nkeh** [comment]
I got an update of the non-insiders today, and it seems to be fixed there also?!

**Comment by darrenjennings** [comment]
oh thank God this was driving me crazy, thank you for fixing 🙏🏻

**Comment by ay0o** [comment]
so, what's the correct way of undoing `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`.

Guess we need to sign the app again. But with which key?

**Comment by MaciekBaron** [comment]
@ay0o the update should have installed a new signed binary

**Comment by superandrew** [comment]
is this distributed to everyone or just in a beta channel?

**Comment by gquittet** [comment]
I've received the update today and I can feel the improvement !
Thank you ! You rocks ! 💪

**Comment by leafac** [comment]
I’m running version 1.53.2 and I still see a significant lag when opening new terminal panes. I ran the `codesign` command and it fixed the issue (I’ve been doing that for every new version…).

I think the issue hasn’t been solved for me. Am I doing something wrong?

**Comment by flash-gordon** [comment]
@leafac [the fix](https://github.com/microsoft/vscode/commit/52838cf6799cc448e738677ec37e86cf62a5bd89) is available in the [insiders builds](https://code.visualstudio.com/insiders/) **only** as of now. Switch to insiders builds or stick to the `codesign` workaround for the time being.

**Comment by leafac** [comment]
@flash-gordon: Ah, I had misunderstood the previous comments and I thought the fix was generally available. Thanks for the clarification 👍

**Comment by calrsom** [comment]
Heads up, the fix was reverted upstream: https://github.com/libuv/libuv/issues/3050#issuecomment-778495429

I'm not sure what that means for VSCode or if this issue should be reopened?

**Comment by deepak1556** [comment]
FYI, the fix is reverted in electron but I have added workarounds for the failing test cases mentioned in the libuv repo while it is being investigated, so I have not reverted the fix internally for vscode.
