### ISSUE TITLE
The window has crashed

### ISSUE THREAD

**Issue by dustinself** [microsoft/vscode#105507]
- Version: 1.48.2 (user setup)
- Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
- Date: 2020-08-25T10:13:11.295Z
- Electron: 7.3.2
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. Open vscode
2. Get crash window

Does this issue occur when all extensions are disabled?: Yes

I have been dealing with this bug for months now. I am using vscode insider to keep my work going, but would like to get vscode fixed. I have tried as fresh of an install as I know to do (uninstalled vscode, deleted C:\Users\<user>\AppData\Roaming\Code folder as well as C:\Users\<user>\.vscode folder, and reinstalled)

The interesting part is that it will open on a fresh install if I check the "Launch Visual Studio Code" box on the final install screen. But if I close vscode and try to reopen, I get the crash message.

I have tried everything I could find on similar bug reports, but nothing works. Help would be appreciated.

Thanks,
Dustin

**Comment by dustinself** [comment]
![2020-08-27_11-02-09](https://user-images.githubusercontent.com/49281379/91466616-01e6f980-e855-11ea-8457-5529bd0432ff.gif)

**Comment by deepak1556** [comment]
Can you launch with `code --crash-reporter-directory <path>` and attach the dmp files generated in the `<path>`

Also side note, there is a runtime version difference between insiders and stable, its most likely possible the crash is fixed in the runtime. If insiders is working fine, then the stable coming out this month should also be fine.

**Comment by dustinself** [comment]
[VSCode Crashes.zip](https://github.com/microsoft/vscode/files/5137956/VSCode.Crashes.zip)

I attached the folder that was generated via your instructions. Let me know if I missed anything! Thank you for the info!

**Comment by deepak1556** [comment]
Thanks! but I don't see any crash dump generated. Does the crash happen when you launch with `code --user-data-dir <path>` ?

**Comment by dustinself** [comment]
Yes, it still crashes.

I don't know if this helps, but here is the contents of the main.log file:

[2020-08-27 15:39:03.480] [main] [info] update#setState idle
[2020-08-27 15:39:03.586] [main] [error] [VS Code]: renderer process crashed!
[2020-08-27 15:39:06.282] [main] [error] [VS Code]: renderer process crashed!
[2020-08-27 15:39:06.989] [main] [error] [VS Code]: renderer process crashed!

**Comment by deepak1556** [comment]
Nope it doesn't contain any additional details than what we already know.

**Comment by dustinself** [comment]
Thanks for looking into it for me. Hopefully it gets fixed in the next stable release.

**Comment by dustinself** [comment]
I found out what the problem was. It was because my company uses something called CyberArk, and it was blocking code.exe for some reason. If I renamed code.exe to code1.exe, it would work fine. Additionally, once I turned CyberArk off locally, code.exe would start opening as well.
