### ISSUE TITLE
 issue with creating and opening .ipynb files

### ISSUE THREAD

**Issue by arezaz** [microsoft/vscode#106547]
- VSCode Version: 1.49.0
- OS Version: Windows_NT x64 10.0.18363

I have an issue with creating/opening Jupiter notebook files (.ipynb).

Steps to Reproduce:

1. Python: Create New Blank Jupiter Notebook
2. this pops up: "Unable to open 'Untitled-1.ipynb': [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character."

attaching a screenshot for more details.
![image](https://user-images.githubusercontent.com/45867828/92998226-483b8a00-f4de-11ea-872a-a9c93d7d1662.png)

I did not have this problem before in VSCode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by DominguesPH** [comment]
Same:
- VSCode Version: 1.49.0
- OS Version: Windows_NT x64 10.0.18363

I'm having the same problem!
It started after I update the VS code version form 1.48 to 1.49.
I just made a plot, closed the window and when returned, this error appeared.
Also, when I try to open saved jupyter notebooks, it don't stop loading.

**Comment by rahul-raj** [comment]
I have same problem as well!

**Comment by FuriouStyles** [comment]
I don't know if it's related, but I can't open an existing notebook either. I tried creating a new one just to see what would happen and this error popped up!

**Comment by DiaAzul** [comment]
Unable to open any Python Jupyter Notebooks (.ipynb) following upgrade to VSCode Version: 1.49.0

When trying to open a notebook there is a cylon progress bar circulating at the top of the frame with the notebook name, however, no notebook contents. Doesn't appear to time out.

**Comment by SharoonSaxena** [comment]
I am having similar issue! Updated to 1.49.0 and the notebook simply keeps loading the ipynb file without any response.
Tried uninstalling and reinstalling the older 1.48.2 version. Still the same problem. Notebook simply keeps loading.
[Screenshot](https://ibb.co/L6vqpg3):

Unfortunately this happened during a presentation. :-[]

**Comment by Sricharan2402** [comment]
Same problem here.
Tried using vscode-insiders, didn't work either.

**Comment by rahul-raj** [comment]
![image](https://user-images.githubusercontent.com/517415/93000261-d9dde280-f544-11ea-936c-2e963c095b09.png)
Attaching screenshot for reference.

**Comment by RSalu** [comment]
me too I have the same problem.

**Comment by arezaz** [comment]
I did this and was able to pull up a Jupyter notebook in the VSCode insider release:
(not sure what the logic is!)

1. uninstall VSCode
2. press **win + R**, type in _%appdata%_
3. find the **Code** folder and delete it
4. install the VSCode Insider

**Comment by DominguesPH** [comment]
> I did this and was able to pull up a Jupyter notebook in the VSCode insider release:
> (not sure what the logic is!)
> 
> 1. uninstall VSCode
> 2. press **win + R**, type in _%appdata%_
> 3. find the **Code** folder and delete it
> 4. install the VSCode Insider

I did the same, the problem persists

**Comment by Meet19aug** [comment]
i also did it but still facing same problem .

**Comment by edinsonAC** [comment]
some solution?

**Comment by dshot92** [comment]
Same problem Here as well.
I was actually a version earsling of the 1.49.
I updated hoping that was it.

No luck.
Tried a fresh install but it doesn't work either.

**Comment by Rajwantmishra** [comment]
Same problem,

**Comment by Rajwantmishra** [comment]
I download only insider (https://code.visualstudio.com/insiders/) and python extension, but now I have a different VS code (VS Insider ) that works.

**Comment by Meet19aug** [comment]
![Capture](https://user-images.githubusercontent.com/61558893/93009859-759e3b80-f5a3-11ea-837b-990ec07456ad.PNG)
still facing issue

**Comment by jfbldevs** [comment]
Same problem

**Comment by calbertrov** [comment]
I have the same issue on one system which uses version 3.8.5, but the version 3.8.2 works on my other system works.

**Comment by aman17ashray** [comment]
I am facing the same issue. With the latest vscode version.

**Comment by calbertrov** [comment]
They heard the voices! VSC 1.49 is fixed. I am able to access Jupyter Notebook!!!!

**Comment by calbertrov** [comment]
Spoke toooo Soon...

**Comment by rahul-raj** [comment]
My vscode version is 1.49 and I'm still having the issue.

**Comment by fuzzyudo** [comment]
Have got the same Problem on a machine with W10, Python 3.8.5, VSC 1.49.0 and Python extension v2020.8.108011.
On a different machine I have no problems: W10, Python 3.7.0, VSC 1.49.0 and Python extension v2020v8v108011.
It seems to be an issue of the combination of versions of VSC and python.

**Comment by fuzzyudo** [comment]
> They heard the voices! VSC 1.49 is fixed. I am able to access Jupyter Notebook!!!!

What version of python are you running?

**Comment by shashwatk1** [comment]
Just uninstalled everything and then reinstalled everything, problem still persists

**Comment by RSalu** [comment]
after resetting completly my Python installation and make a fresh install of anaconda, the problem still persist.
Notebook doesn't run under VS Code!  On the other side Anaconda Notebook run perfectly without issue. 
The issue is by VS Code, I hope MS will corect this next week.

**Comment by mcaires2** [comment]
The same problem here.  What's happening? Is there a way to solve? 

Unable to open 'Untitled-2.ipynb': [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character.

**Comment by RSalu** [comment]
I've just installed the insider Version: [](https://code.visualstudio.com/insiders/). It's work fine

**Comment by Meet19aug** [comment]
@RSalu  can see the screenshot which i have shared in these conversation is from vscode insider but still facing same issue

**Comment by haclark30** [comment]
I'm having the same problem in any version of VS Code I've tried. I uninstalled VS Code completely and installed the Insider version and it still didn't work. I tried downloading the older 1.48.2 version and that still doesn't work. It was working fine up until yesterday.

I've tried running Jupyter notebooks in both plain Windows and in Ubuntu-20.4 WSL and both have the same issue of the notebook preview never loading. Running the same notebooks from the command line and accessing in a browser works fine.

**Comment by HenriqueAJNB** [comment]
I've opened a similar issue [here](https://github.com/microsoft/vscode-python/issues/13901). Any solutions?

I've tried to downgrade VS Code from 1.49 to 1.46 but problem still persists. Other with the blue bar forever loading (1.49) and with this error `unable to open jupyter notebook` file (1.46).

**Comment by jonykarki** [comment]
Had the same problem while trying to ssh into the server. The .ipynb file never opens.

**Comment by ozkan** [comment]
they broke the working plugin

**Comment by sarossilli** [comment]
Same issue, with Ubuntu 20.04.1 LTS.
Tried uninstalling VS Code and Installing VS Code Insiders, but still does not work.

**Comment by jill123-cc** [comment]
I encountered the same problem. I tried to use the previous version: VSCode Version: 1.48.2 (user setup); Pylance: 2020.9.0; python version: 2020.8.106424/2020.8.105045; It still does not work;
My environment: OS: Windows_NT x64 10.0.18362;
VSCode-insider can use it successfully. 

error: _Unable to open 'Untitled-1.ipynb': [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character._

**Comment by smallbal** [comment]
Same issue today when I opened VS Code.

**Comment by smallbal** [comment]
Same issue today when I opened VS Code.  
The Version of VS Code is : 1.49.0

**Comment by smallbal** [comment]
Same issue today when I opened VS Code.
The Version of VS Code is : 1.49.0  
System Platform: Windows 10  
Updated the VS Code was the only thing I did before this issue came up.

**Comment by czescmateusz** [comment]
Same problem here, downgrade doesn't work, neither does vs code insiders

**Comment by saurabhv1** [comment]
Same problem - restart, downgrade, vscode-insiders - nothing works

**Comment by Kurkulis** [comment]
Same problem here. Tried deleting vscode and installing insider version, did not work.

I got the notebooks working again by doing this:

1. Deleted vscode. I am on Linux so I did ```sudo apt remove code``` 
2. Manually deleted vscode appdata folder from ```$HOME/.config/Code/``` 
3. Downloaded and Installed vscode insiders ```sudo dpkg -i code-insiders_1.50.0-1600060713_amd64.deb``` 
4. Opened vscode and an .ipynb file before syncing settings and it worked as excpected.
5. Synced settings and it is still working as expected.

Removing the appdata folder seemed to be the answer. I do not know why it worked or if it is safe to delete it, but for me it fixed the problem.

On Windows the folder should be at: %APPDATA%\Code\
And on macOS it should be at: $HOME/Library/Application Support/Code/

**Comment by justinstolzenberg** [comment]
> Same problem here. Tried deleting vscode and installing insider version, did not work.
> 
> I got the notebooks working again by doing this:
> 
> 1. Deleted vscode. I am on Linux so I did `sudo apt remove code`
> 2. Manually deleted vscode appdata folder from `$HOME/.config/Code/`
> 3. Downloaded and Installed vscode insiders `sudo dpkg -i code-insiders_1.50.0-1600060713_amd64.deb`
> 4. Opened vscode and an .ipynb file before syncing settings and it worked as excpected.
> 5. Synced settings and it is still working as expected.
> 
> Removing the appdata folder seemed to be the answer. I do not know why it worked or if it is safe to delete it, but for me it fixed the problem.
> 
> On Windows the folder should be at: %APPDATA%\Code
> And on macOS it should be at: $HOME/Library/Application Support/Code/

Thank you - following exactly these steps on MacOS resolved (or better: circumvents) the issue

**Comment by saurabhv1** [comment]
> > Same problem here. Tried deleting vscode and installing insider version, did not work.
> > I got the notebooks working again by doing this:
> > 
> > 1. Deleted vscode. I am on Linux so I did `sudo apt remove code`
> > 2. Manually deleted vscode appdata folder from `$HOME/.config/Code/`
> > 3. Downloaded and Installed vscode insiders `sudo dpkg -i code-insiders_1.50.0-1600060713_amd64.deb`
> > 4. Opened vscode and an .ipynb file before syncing settings and it worked as excpected.
> > 5. Synced settings and it is still working as expected.
> > 
> > Removing the appdata folder seemed to be the answer. I do not know why it worked or if it is safe to delete it, but for me it fixed the problem.
> > On Windows the folder should be at: %APPDATA%\Code
> > And on macOS it should be at: $HOME/Library/Application Support/Code/
> 
> Thank you - following exactly these steps on MacOS resolved (or better: circumvents) the issue

Can you please elaborate a little more ?
On my macOS Catalina, I am unable to find 'appdata' directory inside `$HOME/Library/Application Support/Code`

**Comment by justinstolzenberg** [comment]
> > > Same problem here. Tried deleting vscode and installing insider version, did not work.
> > > I got the notebooks working again by doing this:
> > > 
> > > 1. Deleted vscode. I am on Linux so I did `sudo apt remove code`
> > > 2. Manually deleted vscode appdata folder from `$HOME/.config/Code/`
> > > 3. Downloaded and Installed vscode insiders `sudo dpkg -i code-insiders_1.50.0-1600060713_amd64.deb`
> > > 4. Opened vscode and an .ipynb file before syncing settings and it worked as excpected.
> > > 5. Synced settings and it is still working as expected.
> > > 
> > > Removing the appdata folder seemed to be the answer. I do not know why it worked or if it is safe to delete it, but for me it fixed the problem.
> > > On Windows the folder should be at: %APPDATA%\Code
> > > And on macOS it should be at: $HOME/Library/Application Support/Code/
> > 
> > 
> > Thank you - following exactly these steps on MacOS resolved (or better: circumvents) the issue
> 
> Can you please elaborate a little more ?
> On my macOS Catalina, I am unable to find `appdata` directory inside `$HOME/Library/Application Support/Code`

delete the whole folder `$HOME/Library/Application Support/Code` (which is the appdata folder)

**Comment by Kurkulis** [comment]
> > > Same problem here. Tried deleting vscode and installing insider version, did not work.
> > > I got the notebooks working again by doing this:
> > > 
> > > 1. Deleted vscode. I am on Linux so I did `sudo apt remove code`
> > > 2. Manually deleted vscode appdata folder from `$HOME/.config/Code/`
> > > 3. Downloaded and Installed vscode insiders `sudo dpkg -i code-insiders_1.50.0-1600060713_amd64.deb`
> > > 4. Opened vscode and an .ipynb file before syncing settings and it worked as excpected.
> > > 5. Synced settings and it is still working as expected.
> > > 
> > > Removing the appdata folder seemed to be the answer. I do not know why it worked or if it is safe to delete it, but for me it fixed the problem.
> > > On Windows the folder should be at: %APPDATA%\Code
> > > And on macOS it should be at: $HOME/Library/Application Support/Code/
> > 
> > 
> > Thank you - following exactly these steps on MacOS resolved (or better: circumvents) the issue
> 
> Can you please elaborate a little more ?
> On my macOS Catalina, I am unable to find `appdata` directory inside `$HOME/Library/Application Support/Code`

Sorry, I was unclear earlier. As @justinstolzenberg said, delete the whole Code folder. 

It might be a good idea to create a backup of it first, just to be sure. The folder contains backups, caches, user settings, extensions etc. I am using Settings Sync so I just loaded the settings and extensions again after the install.

**Comment by saurabhv1** [comment]
> > > > Same problem here. Tried deleting vscode and installing insider version, did not work.
> > > > I got the notebooks working again by doing this:
> > > > 
> > > > 1. Deleted vscode. I am on Linux so I did `sudo apt remove code`
> > > > 2. Manually deleted vscode appdata folder from `$HOME/.config/Code/`
> > > > 3. Downloaded and Installed vscode insiders `sudo dpkg -i code-insiders_1.50.0-1600060713_amd64.deb`
> > > > 4. Opened vscode and an .ipynb file before syncing settings and it worked as excpected.
> > > > 5. Synced settings and it is still working as expected.
> > > > 
> > > > Removing the appdata folder seemed to be the answer. I do not know why it worked or if it is safe to delete it, but for me it fixed the problem.
> > > > On Windows the folder should be at: %APPDATA%\Code
> > > > And on macOS it should be at: $HOME/Library/Application Support/Code/
> > > 
> > > 
> > > Thank you - following exactly these steps on MacOS resolved (or better: circumvents) the issue
> > 
> > 
> > Can you please elaborate a little more ?
> > On my macOS Catalina, I am unable to find `appdata` directory inside `$HOME/Library/Application Support/Code`
> 
> Sorry, I was unclear earlier. As @justinstolzenberg said, delete the whole Code folder.
> 
> It might be a good idea to create a backup of it first, just to be sure. The folder contains backups, caches, user settings, extensions etc. I am using Settings Sync so I just loaded the settings and extensions again after the install.

This is not working properly on a remote-ssh setup.
After deleting the 'code' dir in my local machine, I was able to create new jupyter-notebook.
However, on doing a remote-ssh, the problem persists.
Then, after restarting vs-code, the problem came back even to my local machine

**Comment by Kurkulis** [comment]
> > > > > Same problem here. Tried deleting vscode and installing insider version, did not work.
> > > > > I got the notebooks working again by doing this:
> > > > > 
> > > > > 1. Deleted vscode. I am on Linux so I did `sudo apt remove code`
> > > > > 2. Manually deleted vscode appdata folder from `$HOME/.config/Code/`
> > > > > 3. Downloaded and Installed vscode insiders `sudo dpkg -i code-insiders_1.50.0-1600060713_amd64.deb`
> > > > > 4. Opened vscode and an .ipynb file before syncing settings and it worked as excpected.
> > > > > 5. Synced settings and it is still working as expected.
> > > > > 
> > > > > Removing the appdata folder seemed to be the answer. I do not know why it worked or if it is safe to delete it, but for me it fixed the problem.
> > > > > On Windows the folder should be at: %APPDATA%\Code
> > > > > And on macOS it should be at: $HOME/Library/Application Support/Code/
> > > > 
> > > > 
> > > > Thank you - following exactly these steps on MacOS resolved (or better: circumvents) the issue
> > > 
> > > 
> > > Can you please elaborate a little more ?
> > > On my macOS Catalina, I am unable to find `appdata` directory inside `$HOME/Library/Application Support/Code`
> > 
> > 
> > Sorry, I was unclear earlier. As @justinstolzenberg said, delete the whole Code folder.
> > It might be a good idea to create a backup of it first, just to be sure. The folder contains backups, caches, user settings, extensions etc. I am using Settings Sync so I just loaded the settings and extensions again after the install.
> 
> This is not working properly on a remote-ssh setup.
> After deleting the 'code' dir in my local machine, I was able to create new jupyter-notebook.
> However, on doing a remote-ssh, the problem persists on remote machine.
> Then, after restarting vs-code, the problem came back even to my local machine

You are correct. I just tested restarting vscode and indeed the problem came back.

I tested this further and found out that Pylance was the cause of this problem (at least for me). 

The following steps helped for now:

1. Disable Pylance.
2. Quit vscode.
3. Delete the Code folder again.
4. Restart vscode and sync settings. Now it is working as expected.
5. Quit and start vscode again and it still works as expected.

Tried restarting vscode many times and opening different .ipynb files and the problem stays away as long as Pylance is disabled.
If I enable Pylance the problem comes back. Can anyone confirm?

Unfortunately, I do not know about the remote-ssh situation.

**Comment by saurabhv1** [comment]
> > > > > > Same problem here. Tried deleting vscode and installing insider version, did not work.
> > > > > > I got the notebooks working again by doing this:
> > > > > > 
> > > > > > 1. Deleted vscode. I am on Linux so I did `sudo apt remove code`
> > > > > > 2. Manually deleted vscode appdata folder from `$HOME/.config/Code/`
> > > > > > 3. Downloaded and Installed vscode insiders `sudo dpkg -i code-insiders_1.50.0-1600060713_amd64.deb`
> > > > > > 4. Opened vscode and an .ipynb file before syncing settings and it worked as excpected.
> > > > > > 5. Synced settings and it is still working as expected.
> > > > > > 
> > > > > > Removing the appdata folder seemed to be the answer. I do not know why it worked or if it is safe to delete it, but for me it fixed the problem.
> > > > > > On Windows the folder should be at: %APPDATA%\Code
> > > > > > And on macOS it should be at: $HOME/Library/Application Support/Code/
> > > > > 
> > > > > 
> > > > > Thank you - following exactly these steps on MacOS resolved (or better: circumvents) the issue
> > > > 
> > > > 
> > > > Can you please elaborate a little more ?
> > > > On my macOS Catalina, I am unable to find `appdata` directory inside `$HOME/Library/Application Support/Code`
> > > 
> > > 
> > > Sorry, I was unclear earlier. As @justinstolzenberg said, delete the whole Code folder.
> > > It might be a good idea to create a backup of it first, just to be sure. The folder contains backups, caches, user settings, extensions etc. I am using Settings Sync so I just loaded the settings and extensions again after the install.
> > 
> > 
> > This is not working properly on a remote-ssh setup.
> > After deleting the 'code' dir in my local machine, I was able to create new jupyter-notebook.
> > However, on doing a remote-ssh, the problem persists on remote machine.
> > Then, after restarting vs-code, the problem came back even to my local machine
> 
> You are correct. I just tested restarting vscode and indeed the problem came back.
> 
> I tested this further and found out that Pylance was the cause of this problem (at least for me).
> 
> The following steps helped for now:
> 
> 1. Disable Pylance.
> 2. Quit vscode.
> 3. Delete the Code folder again.
> 4. Restart vscode and sync settings. Now it is working as expected.
> 5. Quit and start vscode again and it still works as expected.
> 
> Tried restarting vscode many times and opening different .ipynb files and the problem stays away as long as Pylance is disabled.
> If I enable Pylance the problem comes back. Can anyone confirm?
> 
> Unfortunately, I do not know about the remote-ssh situation.

I'm having this problem without installing Pylance

**Comment by gjsjohnmurray** [comment]
Unverified by me, but https://github.com/microsoft/vscode-python/issues/13901#issuecomment-691625412 seems to offer a workaround.

**Comment by saaltfiish** [comment]
> Unverified by me, but [microsoft/vscode-python#13901 (comment)](https://github.com/microsoft/vscode-python/issues/13901#issuecomment-691625412) seems to offer a workaround.

Worked for me. Thanks.

**Comment by JoshyB14** [comment]
Still having issues opening existing notebooks and attempting to create new ones...

**Comment by joyceerhl** [comment]
Here's a stack trace from dev tools:
![image](https://user-images.githubusercontent.com/30305945/93112218-92eb0c80-f66c-11ea-9fb6-1174c6fbe21d.png)

**Comment by jrieken** [comment]
@mjbvz stack trace links `toWorkingCopyResource` which dangerously creates URI. E.g if the path isn't rooted then this error happens. 

https://github.com/microsoft/vscode/blob/6e022766d135689a6a5f92a4f3d9ebf97b238dd0/src/vs/workbench/api/browser/mainThreadCustomEditors.ts#L348-L355

![c201a31e-5bd6-4a4b-83b0-a9f69935fac1](https://user-images.githubusercontent.com/1794099/93111957-aa031c00-f6b7-11ea-8070-597a78259d27.jpg)

**Comment by Rajwantmishra** [comment]
Work with VS insider. Install (https://code.visualstudio.com/insiders/) and install python extension, it works, while we wait for real fix.

**Comment by Loligplayer33** [comment]
What i think is strange that it works for me on windows but not on linux...

**Comment by mjbvz** [comment]
@jrieken That looks like a bug on the VS Code side but people also are reporting this in 1.48 and we haven't touched that code recently

@joyceerhl or someone from the Python team: was there a new python release that enabled new functionality that trigged this bug (such as the release on the 9th)? Also this may be related to an experiment. Is there a way to force the extension into the broken state?

**Comment by rchiodo** [comment]
@mjbvz  yes I believe it was a change to our experiments that might have caused it. 

You can set this in your user settings.json to repro I believe:

```json
    "python.experiments.optInto": [
        "CustomEditorSupport - experiment"
    ],
```

That experiment was enabled on Friday by mistake.

**Comment by rchiodo** [comment]
Also explains why not everybody is hitting this. That experiment turns on our usage the custom editor API.

**Comment by rebornix** [comment]
@rchiodo I can reproduce with experiment optInfo posted above, is there any way for me to opt out after adding that setting? I removed it but it still tries to ope with custom editor.

**Comment by rchiodo** [comment]
Turning off that setting is supposed to opt out, but if that doesn't work you might also have to remove the python extension and reinstall it.

Turning on that setting modifies the python package's package.json on disk (or at least it used to).

**Comment by rebornix** [comment]
Thanks, removing the optInfo and uninstalling the extension then re-install fixes this problem. It can be a workaround recommended to users before we ship the recovery build.

**Comment by DiaAzul** [comment]
> 
> 
> Thanks, removing the optInfo and uninstalling the extension then re-install fixes this problem. It can be a workaround recommended to users before we ship the recovery build.

Confirmed works

**Comment by mjbvz** [comment]
@rchiodo Can you please revert the experiment change on the Python side? Again, while there does seem to be a bug on the VS Code side, it does not appear to be a VS Code regression. I'd prefer avoiding the risk of a patch fix in VS Code 1.49. Better to fix this in insiders so we get additional testing before it goes out with 1.50

**Comment by rchiodo** [comment]
That requires us to ship a fix then too (as it doesn't seem that undoing the experiment is enough - experiment is actually downloaded from github on startup). Our next shipping date should be a week from today

**Comment by rchiodo** [comment]
Or we can try and fix a patch release just to fix the bug where the experiment requires a reinstall.

**Comment by rchiodo** [comment]
Actually just revving the version number should fix the problem. That should be easier to get out.

**Comment by anupampydey** [comment]
I too faced the URIError day before yesterday. The jupyter notebooks won't open in VS code. Wasted considerable time in uninstalling the current version and reinstalling the older version but the error persisted. Today I updated by windows 10 and problem has gone automatically. Don't know what happened but now with VS Code I can open both saved notebooks and new notebooks.

**Comment by rchiodo** [comment]
Python extension released a new version. That should alleviate the problem for most people.

**Comment by jill123-cc** [comment]
@rchiodo It works for me when I use the latest version of python extension (2020.8.109390), thank you!

**Comment by mjbvz** [comment]
@rchiodo I pushed a fix into VS Code insiders. However I still don't see the Python custom editor successfully loading after pushing this (it looks like it never resolves). I also can't get it working on MacOS using VS Code 1.49, so this may be an issue with the custom editor implementation.

Please test out the next insiders build and let me know if you think something is off on the VS Code side

**Comment by songpr** [comment]
I have try the insider release, however the .ipynb is still show as blank
![image](https://user-images.githubusercontent.com/3700356/93475882-56950600-f923-11ea-8ec4-22f119ef9899.png)

**Comment by rchiodo** [comment]
@mjbvz the latest insider's build still repros the problem. To repro:

1. Install python extension (not the insiders version of this as the insiders is disabling custom editor at the moment)
1. Set this in your global user settings:
```json
    "python.experiments.optInto": [
        "CustomEditorSupport - experiment"
    ],
```
3. Open a python file
3. Reload VS code when it asks (if it doesn't, do it manually). This step is necessary because enabling the custom editor experiment will rewrite our package.json.
3. Try opening a notebook. 

You should end up with the screen like @songpr  had. If you run ```Toggle Maximize Panel``` and reopen the notebook, it will open correctly.

However the other bug - creating a new blank notebook, that has been fixed. The notebook just hits the same problem where you have to maximize the panel first.

**Comment by rchiodo** [comment]
The blank ipynb is really this issue here (which for us is more important than fixing the URI problem).
https://github.com/microsoft/vscode/issues/106673

**Comment by songpr** [comment]
@rchiodo so you mean if I turn off custom editor it will work right?

Could you let me know how to do it I search the setting but cannot found the option that you show.

**Comment by rchiodo** [comment]
Custom editor is an opt in only scenario at the moment. 

We accidentally enabled it for 20% of users on the 11th. If you reinstall the python extension it should go back to not being enabled.

If that still doesn't work, double check this value isn't set in your settings.json:

```json
    "python.experiments.optInto": [
        "CustomEditorSupport - experiment"
    ],
```

**Comment by songpr** [comment]
![image](https://user-images.githubusercontent.com/3700356/93704920-b1587880-fb42-11ea-8967-bdbdddb31495.png)
@rchiodo the value is not in setting.json.
However the jupyter file still cannot open

**Comment by Saiful-Islam-Sakib** [comment]
I have solved the issues in my vscode like below:

1. Open vscode and search for  "python.pythonPath"
2. Change the path by replacing all " \ " with " / " and save it.
    ex: "C:\\py3.8\python.exe"   ->   "C://py3.8/python.exe"

Happy Coding
