### ISSUE TITLE
Terminal Cursor Ghosting When Window Zoom Set To -1

### ISSUE THREAD

**Issue by JT114881** [microsoft/vscode#106981]
Issue Type: <b>Bug</b>

1. Set "window.zoomLevel": -1
2. Click into terminal window (Tested using powershell terminals both integrated and included)
3. Remove cursor from window
4. Place cursor in window and press enter to new line.
5. Observe square cursor ghosting outline

Expected Result: No ghosted cursor outline when moving to new line in terminal
![Ghosting](https://user-images.githubusercontent.com/18473943/93556165-b8626980-f93d-11ea-919b-8e9fe8a3b8ed.png)

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
prettier-vscode|esb|5.6.0
powershell-preview|ms-|2020.9.0
material-icon-theme|PKi|4.3.0
vscodeintellicode|Vis|1.2.10

(1 theme extensions excluded)

</details>

**Comment by AxonneQ** [comment]
Same issue here.

![Code_2020-09-20_18-42-41](https://user-images.githubusercontent.com/40044656/93718001-2e024b80-fb71-11ea-8b64-d3a7e1c8009e.png)

**Comment by JT114881** [comment]
Yup @AxonneQ that's exactly what my terminal looks like after a while. Really annoying and distracting.

**Comment by Tyriar** [comment]
Can you share your settings.json file? A workaround is to set `terminal.integrated.rendererType` to `dom`

**Comment by JT114881** [comment]
{
  "workbench.iconTheme": "material-icon-theme",
  "[powershell]": {
    "editor.renderWhitespace":"selection",
    "editor.renderControlCharacters": false,
    "files.trimTrailingWhitespace": true,
    "files.encoding": "utf8bom",
    "files.autoGuessEncoding": true,
    "editor.tabCompletion": "on"
  },
  "bracket-pair-colorizer-2.activeScopeCSS": [
    "borderStyle : solid",
    "borderWidth : 2px",
    "borderColor : {color}",
    "opacity: 0.8"
],
"bracket-pair-colorizer-2.showBracketsInGutter": true,
"editor.suggestSelection": "first",
"vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
"files.autoSave": "afterDelay",
"powershell.codeFormatting.autoCorrectAliases": true,
"powershell.integratedConsole.suppressStartupBanner": true,
"terminal.integrated.automationShell.linux": "",
"powershell.powerShellDefaultVersion": "Windows PowerShell (x64)",
"powershell.codeFormatting.useCorrectCasing": true,
"terminal.integrated.cursorBlinking": false,
"workbench.colorCustomizations": {
  "terminalCursor.foreground": "#FFFFFF",
  "terminalCursor.background": "#1e1e1e"  
},
"workbench.view.alwaysShowHeaderActions": true,
"window.zoomLevel": -1
}

**Comment by AxonneQ** [comment]
Looks like the issue is with the ```window.zoomLevel: -1``` when the value is 0 or higher, ghosting disappears. Kind of sucks since on 1440p, the UI is a bit too big for me. that's why I zoomed it out.

**Comment by Tyriar** [comment]
Can you try close vscode and launch using `code --disable-featuers="LayoutNG"` to see if the issue still happens?

**Comment by JT114881** [comment]
> Can you try close vscode and launch using `code --disable-featuers="LayoutNG"` to see if the issue still happens?

Removed the workaround and tried starting using what you suggested. Issue is still happening. Here is the output of the command prompt:

C:\Users\jt114881\AppData\Local\Programs\Microsoft VS Code> code --disable-featuers="LayoutNG"
Warning: 'disable-featuers' is not in the list of known options, but still passed to Electron/Chromium.
[main 2020-09-23T23:38:52.827Z] update#setState idle
(node:109112) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\jt114881\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:109112) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\jt114881\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\node-pty\build\Release\conpty.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:109112) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\jt114881\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\windows-process-tree\build\Release\windows_process_tree.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:109112) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\jt114881\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:113736) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\jt114881\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[main 2020-09-23T23:39:22.827Z] update#setState checking for updates
[main 2020-09-23T23:39:23.205Z] update#setState idle

**Comment by lucas-rds** [comment]
Having the same issue here, VSCode 1.49.1, windows 10

**Comment by amyspark** [comment]
Can confirm with Manjaro and the Snap version.

```
Versión: 1.50.0-insider
Confirmación: e6a742d2407c4a94c6540b49aa5f801468dbd1c8
Fecha: 2020-09-22T18:12:43.551Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Sistema Operativo: Linux x64 5.4.64-1-MANJARO snap
```

Window zoom level, `--disable-features` flag have no effect. DOM renderer is a workaround, although I end up with a sort-of-shaved-off cursor.

**Comment by JT114881** [comment]
@Tyriar this is still marked as 'needs more info', do you require any more information from me?

**Comment by deepak1556** [comment]
I was able to repro with stable but I cannot repro the issue with our insiders https://code.visualstudio.com/insiders/, can others confirm ?

**Comment by JT114881** [comment]
@deepak1556 confirmed issue still happening on latest insiders build as well. 
Set it up with the same extensions and settings file, minus the workaround.

**Comment by deepak1556** [comment]
I followed your steps and reused same settings but wasn't able to repro the issue with insiders. Attaching the screen recording from both stable and insiders.



[cursor_ghosting.zip](https://github.com/microsoft/vscode/files/5380166/cursor_ghosting.zip)

**Comment by JT114881** [comment]
> I followed your steps and reused same settings but wasn't able to repro the issue with insiders. Attaching the screen recording from both stable and insiders.
> 
> [cursor_ghosting.zip](https://github.com/microsoft/vscode/files/5380166/cursor_ghosting.zip)

See my repro attached. 
[Confirmation.zip](https://github.com/microsoft/vscode/files/5380239/Confirmation.zip)

**Comment by AregGhazaryan** [comment]
@deepak1556  unfortunately, it's still ghosting even on insiders build 
![image](https://user-images.githubusercontent.com/38076644/96033427-1ae15380-0e71-11eb-85bf-cc7c1737941f.png)

**Comment by deepak1556** [comment]
thanks for confirming, couple of things I want to check

* Can you launch with `code --disable-features=LayoutNG` , I know that it was requested in https://github.com/microsoft/vscode/issues/106981#issuecomment-697971958 but the flag has a typo in that comment.

* Can you launch with `code --disable-gpu`

* Can you check with our exploration builds https://az764295.vo.msecnd.net/exploration/a9522785ef3c54961079e12afab9d3915ea68e08/VSCodeUserSetup-x64-1.51.0-exploration.exe that comes with newer chromium runtime.

let me know which of these work and don't.

**Comment by AregGhazaryan** [comment]
> thanks for confirming, couple of things I want to check
> 
> * Can you launch with `code --disable-features=LayoutNG` , I know that it was requested in [#106981 (comment)](https://github.com/microsoft/vscode/issues/106981#issuecomment-697971958) but the flag has a typo in that comment.
> * Can you launch with `code --disable-gpu`
> * Can you check with our exploration builds https://az764295.vo.msecnd.net/exploration/a9522785ef3c54961079e12afab9d3915ea68e08/VSCodeUserSetup-x64-1.51.0-exploration.exe that comes with newer chromium runtime.
> 
> let me know which of these work and don't.

I have tried `code --disable-gpu` and it seems that the ghosting has stopped but when you use `--disable-features=LayoutNG` its still there.

**Comment by deepak1556** [comment]
@Tyriar considering this is a gpu specific issue, next step would be create a minimal repro and file report in chromium, can you help with that ?

**Comment by Ofsen** [comment]
Same issue. `"terminal.integrated.rendererType": "dom"` and `code --disable-gpu` are both confirmed workarounds.
I just want to add that adjusting the size of the terminal makes the effect go away, for me at least, but it comes back after some time.

It also seem that the ghosting only shows when : 
- `"window.zoomLevel"` is less than 0
- clicking out of terminal and then getting back in it

here's a gif of how i repro
![ghost-cursor](https://user-images.githubusercontent.com/24249806/97061118-963bb700-158d-11eb-8f1c-de5d34dc48d6.gif)

**Comment by Tyriar** [comment]
Can anyone confirm whether `"terminal.integrated.rendererType": "experimentalWebgl"` also works around the issue?

**Comment by colinpmillar** [comment]
works for me

**Comment by Tyriar** [comment]
@colinpmillar great to hear! So this is restricted to the canvas renderer that while it is the default, I want to get rid of in favor of webgl with a fallback of dom based on some automatic detection https://github.com/microsoft/vscode/issues/106202. This is after we close the gap in functionality, which I think is only context loss and underline support at this point https://github.com/xtermjs/xterm.js/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Faddon%2Fwebgl

**Comment by Ofsen** [comment]
`"terminal.integrated.rendererType": "experimentalWebgl"` doesn't work for me, unfortunately.

I also noticed that this "cube" shows up on `experimentalWebgl` , `canvas` and `auto`
![1](https://user-images.githubusercontent.com/24249806/97625985-8eff2800-1a29-11eb-86cf-167026423342.jpg)

But when i set it on `dom` this shows up
![2](https://user-images.githubusercontent.com/24249806/97626238-d7b6e100-1a29-11eb-87c4-94e39581a084.jpg)

These two pictures shows the cursor when i clic away from the terminal

**Comment by Juanpam** [comment]
I also see the "two-lines" cursor when using the `"terminal.integrated.rendererType": "dom" ` setting!

**Comment by Tyriar** [comment]
> I also see the "two-lines" cursor that @Ofsen mentions when using the "terminal.integrated.rendererType": "dom" setting!

This sounds like a separate bug as this issue is specifically about canvas changes in Chromium. I don't think that's been reported yet so feel free to create it.

**Comment by oliversalzburg** [comment]
`experimentalWebgl` produces the exact same artifacts for me.

But, upon switching the renderer, the terminal gets fully redrawn, which termporarily fixes it. The artifacts reappear soon enough though.

**Comment by geneowak** [comment]
I had a similar problem, pressing backspace left residue cursors and setting `"terminal.integrated.rendererType": "dom"` solved the problem...

![back space line](https://user-images.githubusercontent.com/13153526/105610626-89fc0b80-5dc1-11eb-8387-fdeb28a599d6.png)

**Comment by bencresty** [comment]
Can confirm this issue too in 1.52.1.

![render-errors](https://user-images.githubusercontent.com/69322733/107327910-315d8b80-6aae-11eb-92eb-683ede47735d.png)

After reading this thread I've tried:
- setting `"terminal.integrated.rendererType": "experimentalWebgl"`: doesn't help, same issue
- starting with `--disable-features="LayoutNG"`: doesn't help
- setting `"terminal.integrated.rendererType": "dom"`: makes VS Code unbearably slow. Not sure if this works around/fixes the render issue, but it makes everything so slow that it's unworkable

settings:
- `"terminal.integrated.shell.windows"` is set to PowerShell.exe
- `"terminal.integrated.fontSize": 12`

**Comment by nelsonec87** [comment]
Same problem here.. Just wanted to share one thing that I've noticed about this: if you resize the terminal panel the artifacts are gone. Maybe it helps to figure out the inner problem and/or solution.

**Comment by altjx** [comment]
A workaround for me with the "double lined" block was to change the **Cursor Style** from **block** to **line**, and increase the **Cursor Width** to 8, which is approximately the same size as the "block" style.

![Screen Shot 2021-04-12 at 3 59 38 PM](https://user-images.githubusercontent.com/4023423/114453969-17245480-9ba8-11eb-82b0-023149189d85.png)

![Screen Shot 2021-04-12 at 3 59 48 PM](https://user-images.githubusercontent.com/4023423/114453993-1c819f00-9ba8-11eb-9746-8e960b75bd86.png)

**Comment by altjx** [comment]
Has there been any other alternative workarounds for this? For me, when changing the render type, it causes my terminal to be extremely slow, so watching logs and what not just take much longer.

**Comment by sudokillpid** [comment]
VSCode updated this morning, and now the issue seems to have returned for me... I too work on a zoomed environment of -1 and can confirm that anything less than zoom level 0 causes this.

**Comment by DD-Diana** [comment]
I could easily reproduce the problem with `"window.zoomLevel": -1` and `"terminal.integrated.gpuAcceleration": "on"` (or auto).

Disabling GPU acceleration fixed it regardless of zoom level.

![terminal-ghost-cursor_zoom-level_gpu-acceleration](https://user-images.githubusercontent.com/52296908/117538230-7f2e5500-b005-11eb-89ef-42703141ea6c.gif)

**Comment by bencresty** [comment]
> Disabling GPU acceleration fixed it regardless of zoom level.

@DD-Diana  Not here:
![image](https://user-images.githubusercontent.com/69322733/117546417-9af82200-b02a-11eb-9c4c-eb98d509705d.png)

And it made the terminal way slower too. So unfortunately it's not fixing the issue here.

Would be nice though if Microsoft finally starts looking into this and fix this as this is a pretty annoying bug we're facing this issue everyday for months to a year now.

**Comment by krzyhan** [comment]
> VSCode updated this morning, and now the issue seems to have returned for me... I too work on a zoomed environment of -1 and can confirm that anything less than zoom level 0 causes this.
> 
> Edit:
> As a workaround, I've changed cursorStyle to "underlined". No more ghosting. Though I'm not a fan of this cursor style, it will have to do.

The same for me - changing to `underlined` "fix" this issue.

**Comment by seahindeniz** [comment]
I'm not a fan of underline or block size looking cursor. Setting the cursor width to 2 worked for me and I hope it works for you if you are a fan of line cursor style...
```
  "terminal.integrated.cursorStyle": "line",
  "terminal.integrated.cursorWidth": 2
```


https://user-images.githubusercontent.com/5789670/119606908-0ea47800-bdfc-11eb-9c52-5bd52f7cdac2.mp4

**Comment by Tyriar** [comment]
xterm.js issue: https://github.com/xtermjs/xterm.js/issues/3391

**Comment by Tyriar** [comment]
While this does appear to be a regression due to a Chromium update, looks like the fix can be done on our end without much compromise.

**Comment by JustinGrote** [comment]
This was driving me crazy, can't believe I came to this issue to find out it will probably be fixed in Insiders on monday, guess I'm a lucky boy :)

![image](https://user-images.githubusercontent.com/15258962/126053966-dcb4fe5e-f143-4657-b6aa-b7077875ac5d.png)

**Comment by connor4312** [comment]
I wasn't able to repro in stable so couldn't verify. If anyone hits this on their machine, please appease the bot above https://github.com/microsoft/vscode/issues/106981#issuecomment-889223678

**Comment by MurzNN** [comment]
For me this issue is gone on stable 1.58.2 too, great!

**Comment by Juanpam** [comment]
I'm still experiencing this on stable 1.58.2 in MacOS 11.5.1 (M1 version) :(

**Comment by connor4312** [comment]
@Juanpam please try Insiders https://github.com/microsoft/vscode/issues/106981#issuecomment-889223678

**Comment by Juanpam** [comment]
@connor4312 May I install this one side by side with the stable release? Also, I noticed the terminal.integrated.rendererType config option is no longer available :(

**Comment by Juanpam** [comment]
@connor4312 Can confirm the bug is gone on Insiders (at least for me) version:

Version: 1.59.0-insider (Universal)
Commit: 8f58c1f457bd2ddf6cf81120c450c783b6e8c01b
Date: 2021-08-04T08:44:13.089Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin arm64 20.6.0

**Comment by connor4312** [comment]
Thanks!
