### ISSUE TITLE
Double comma conflict with Prettier on ES6 imports when auto-importing

### ISSUE THREAD

**Issue by tonix-tuft** [microsoft/vscode#107057]
- VSCode Version:
Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:21:17.533Z (2 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

- OS Version: macOS High Sierra 10.13.6

Since Prettier version `^2.0.0`, the default value for the `Prettier: Trailing Comma (trailingComma)` option of the Prettier VS Code extension (https://github.com/prettier/prettier-vscode) is `es5`:

![Screen Shot 2020-09-19 at 10 52 38](https://user-images.githubusercontent.com/10134421/93663225-708b3180-fa66-11ea-939e-44d4aabd0b89.png)

This makes Prettier to add a trailing comma to ES6 imports as well, e.g. given this code (unsaved):

```js
import {
  Tag1,
  Tag2,
  Tag3
} from "./some-module";

// ...
```

When saved (`Cmd+S`/`Ctrl+S`):

```js
import {
  Tag1,
  Tag2,
  Tag3,
} from "./some-module";

// ...
```

Now, when I reference another component (let's say `Tag4`) in the same file containing the code above, VS Code prompts me to auto import this component too:

![Screen Shot 2020-09-19 at 10 57 59](https://user-images.githubusercontent.com/10134421/93663286-18086400-fa67-11ea-8c10-08d347f53400.png)

And when I type `Enter` to auto import the component this is what I end up with:

```js
import {
  Tag1,
  Tag2,
  Tag3,, Tag4
} from "./some-module";

Tag4

// ...
```

VS Code adds another trailing comma after `Tag3,` before adding `Tag4`, leading to two subsequent commas and of course  causing a parse error.

The expected behaviour would be for VS Code to check if the import statement already has a trailing comma, and add it only if it's missing.

For now, the only way to fix this would be to add the following config option to a `.prettierrc` file in the project:

```
{
  "trailingComma": "none"
}
```

This makes Prettier to not add trailing commas at all. But again, I think it would be great if VS Code would check for that trailing comma on its own before auto importing a component.

Thank you for your attention and for this IDE, I feel very comfortable to work with it!

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/40561. Should be fixed in VS Code insiders

**Comment by tonix-tuft** [comment]
Thank you for your reply.

> Should be fixed in VS Code insiders

What do you mean? Will it be fixed in the next patch/minor version of VS Code `> 1.49.1`? Thank you.

**Comment by mjbvz** [comment]
[VS Code insiders](https://code.visualstudio.com/insiders/) always tracks the next VS Code version, so 1.50

**Comment by tonix-tuft** [comment]
Thank you for your reply! Will wait for the 1.50 update on VS Code.

**Comment by landonalder** [comment]
I'm still having this same issue with vscode 1.50.1 and typescript 4.0.2

**Comment by mjbvz** [comment]
This was fixed in TypeScript 4.0.3 (which is the default for VS Code 1.50)

**Comment by landonalder** [comment]
Ah, thanks Matt! I’ll update the typescript version
