### ISSUE TITLE
"No quick fixes available" flashes with the mouse move

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#108266]
Version: 1.50.0-insider
Commit: 772aa0723f7f6b04b710bc3a92b7a904b60ef439
Date: 2020-09-28T05:38:20.490Z
Browser: Edge

![Kapture 2020-10-07 at 20 27 09](https://user-images.githubusercontent.com/5047891/95372270-9e33ff80-08db-11eb-9ffe-54f3ee1e3a04.gif)

There is only one error at that location:

![image](https://user-images.githubusercontent.com/5047891/95372429-d20f2500-08db-11eb-9c04-057cb347ef71.png)

**Comment by mjbvz** [comment]
@sandy081 Can you please take ownership of this since it is problems UI. If there is something wrong with the code actions apis, let me know

**Comment by sandy081** [comment]
I transferred it because the feature `No quick fixes available` was implemented by you.

Sure, I can look into this.

**Comment by sandy081** [comment]
@alexdima I am not able to reproduce it.

Can you please provide the sample to repro? It will be easy to diagnose and fix then.

**Comment by alexdima** [comment]
@sandy081 I'm sorry, I missed the notification. Here are the steps:
- in Edge create a codespace of https://github.com/microsoft/vscode-oniguruma
- open `src/index.ts`
- at lines 317 and 319, remove the last argument, `options`
- here is the diff, it should lead to errors:
![image](https://user-images.githubusercontent.com/5047891/98702603-de731b80-237a-11eb-8775-aec7eec0f526.png)
- place mouse over the error and move the mouse slowly to the right:
- observe how "No quick fixes available" appears and disappears as the mouse is moved:
![Kapture 2020-11-10 at 17 34 57](https://user-images.githubusercontent.com/5047891/98702811-23974d80-237b-11eb-83c2-9d668008c314.gif)

**Comment by rzhao271** [comment]
Still shows for me, though now with a "Checking for quick fixes..." string

Version: 1.52.0-insider
Commit: 5e350b1b79675cecdff224eb00f7bf62ae8789fc
Date: 2020-12-04T10:14:10.583Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.55

![recording (6)](https://user-images.githubusercontent.com/7199958/101204745-8c43b400-3621-11eb-93da-3b8e1a0733d0.gif)
