### ISSUE TITLE
File closes when network drive goes away

### ISSUE THREAD

**Issue by spraguey** [Microsoft/vscode#10890]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 14.5.0

Steps to Reproduce:

1.Connect to a network drive using SMB or AFP
2.Open a file on one of those drives in VSCode
3.Disconnect the drive.
4.VSCode crashes

Sublime does NOT behave this way. 

Here's why it is a problem... I'm working on a set of files on a network drive. I move my laptop to a different location, or switch from wired to wireless. The network drive disconnects. Now, I lose all the files I was working on and have to re-open them all. 

Another example...  I'm working on 10+ files at the end of the day and I close my laptop and go home. The next morning I come in, and I have to re-open all 10 of those files (assuming I remember what they were).

Correct behavior should be to keep the file open.  Of course, you can't save it until you reconnect the network drives, but at least it is there.  This is how Sublime works.

**Comment by jcw007** [comment]
I am experiencing a similar issue.

1. Open a folder on a network drive mounted using NFS. Everything works fine, no problem there.
2. Close folder and close VSCode
3. Mount the same network drive with a different path (e.g. NFS server has been rebooted and assigned different IP)
4. Open VSCode and try to open a file/folder

Expected: VSCode should launch the file/folder open dialog
Actual: VSCode does not launch the file/folder open dialog and becomes unresponsive after multiple attempts to open file/folder.

**Comment by bpasero** [comment]
@spraguey @jcw007 can you share more details how it crashes? does it show a crash dialog?

**Comment by spraguey** [comment]
@bpasero All of the tabs disappear, and there is a small dialog window that says "The window has crashed. We are sorry for the inconvenience! You can reopen the window to continue where you left off." There are close and reopen buttons. Even if I reconnect the drive and click Reopen, it does not recover. It just brings be to the editor with no files/tabs open.

![screen shot 2016-08-25 at 9 05 07 am](https://cloud.githubusercontent.com/assets/7975874/17970082/0c0b0962-6aa3-11e6-8e5f-2fab9bf2cfef.jpg)

**Comment by bpasero** [comment]
@spraguey can you check if this happens with Atom editor too?

**Comment by spraguey** [comment]
@bpasero No, this does not happen in Atom.  In Atom, the file remains open and indicates that it is unsaved (small blue dot in the tab). This is what I would expect in VSCode. It obviously cannot save the file, but it remains open.

Wow, all this time I thought VSCode was based on Sublime. It's Atom. Oops.

**Comment by bpasero** [comment]
@spraguey would you be able and willing to run VS Code out of its source code to try some things out for me in order to nail this issue down? The instructions are here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by spraguey** [comment]
This is definitely not something I have done before, so not sure how useful I will be.  I was able to get through the entire process up to the npm install.  I tried the Incremental Build, though, and it fails with a segmentation fault: 11. This is node 6.2.0, npm 3.8.9.

**Comment by bpasero** [comment]
Weird that should work though. I am always using node.js 5.10.0. Might be due to out of memory. Does it repeat the error all the time?

**Comment by jcw007** [comment]
@bpasero In my case, I didn't see any crash dialog. VS Code just became unresponsive. I had to close it though Task Manager. Btw, I am using Node 4.4.5.

**Comment by spraguey** [comment]
@bpasero Okay, I rolled back to Node 5.10 and it works. What do you need me to do? Would you prefer to PM?

**Comment by bpasero** [comment]
@spraguey awesome, can you reproduce the error while doing your steps from the version that you run out of sources?

**Comment by spraguey** [comment]
@bpasero Funny thing about that... The npm install runs and the watcher seems to work and recompile it when I change a file. However, nothing I see in the instructions tells me how to run the application or where it is.

**Comment by bpasero** [comment]
@spraguey see https://github.com/Microsoft/vscode/wiki/How-to-Contribute#validate-your-changes

**Comment by spraguey** [comment]
@bpasero Sorry, found it under "Validate your changes".  Yes, I can replicate the issue on the source version.

**Comment by bpasero** [comment]
@spraguey great, so lets start to comment out some things. Can you comment out https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L109 and https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L111 to disable our file watcher and try if it still reproduces?

You are on Mac OS X right?

**Comment by spraguey** [comment]
@bpasero Yes, Mac OSX. I changed those two lines, and watch process appeared to compile it.  I can Code again from there, and it appears to show the same error behavior.

Terminal shows this, among other things...
2016-08-26 09:24:14.435 Electron[69990:5847776] Communications error: <OS_xpc_error: <error: 0x7fff794a6b60> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x7fff794a6fa8> { length = 22, contents = "Connection interrupted" }
}>

**Comment by bpasero** [comment]
@spraguey can you open the Console application and see if you find the full crash dump in there? See my screenshot where to look for:

![image](https://cloud.githubusercontent.com/assets/900690/18007237/77be1068-6ba3-11e6-8ad9-d0c969c91778.png)

**Comment by spraguey** [comment]
@bpasero Yes, I have it. "Code - OSS Helper", though, not Electron right?  I don't have anything that says Electron. Do you want me to paste the entire thing here?

**Comment by bpasero** [comment]
@spraguey yes Code OSS helper is also good, can you attach the log you have there? This might point to the reason of the crash.

**Comment by spraguey** [comment]
@bpasero 
[Code - OSS Helper_2016-08-26-092437_mac-6.txt](https://github.com/Microsoft/vscode/files/442397/Code.-.OSS.Helper_2016-08-26-092437_mac-6.txt)

**Comment by bpasero** [comment]
@spraguey is it ok to share this with the Electron team via issue? I can file it if you want.

**Comment by spraguey** [comment]
@bpasero Yes, feel free to share.

**Comment by bpasero** [comment]
@spraguey ok filed as https://github.com/electron/electron/issues/7022

Back to trying to understand what is going on, some questions:
* does it also happen if you do File > Close Folder, then open any file from the drive via File > Open and then the network drive going down?
* does it happen if you open a folder from the network drive without having any file open? try to close all files first and then reload the window to get into a clean state (View > Command Palette > Reload Window)

**Comment by bpasero** [comment]
@spraguey you still there?

**Comment by spraguey** [comment]
@bpasero No matter what method I use to open a file, the crash occurs when the file's source drive becomes unavailable. 

It happens regardless of whether the folder is open/closed in Code.
It does happen with a single file opened from the network drive.

It does not happen if I simply open a folder in Code (WITHOUT opening a file), and then make the source folder go away.

**Comment by bpasero** [comment]
@spraguey I find the case very interesting where you start with an empty VS Code (no folder open) you open a file from that drive and VS Code crashes when the drive is disconnected! Because that is a very isolated thing to test. 

Can we try something again? Please get latest from master and run these commands:
* `git clean -xfd` (this removes e.g. the node_modules folder)
* `scripts/npm.sh install` (this ensures you get our latest modules back)
* comment out this line: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/electron-browser/fileService.ts#L118
* `gulp watch` (compile!)

This basically disables our file watching for files which are not in your workspace. I wonder if it is related.

**Comment by spraguey** [comment]
@bpasero Sorry, Benjamin, but I have to bail out of this for now. I tried the steps above, and I end up with 
"The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/electron/electron/tree/v0.37.6/docs

Error: Cannot find module '/Users/msprague/Applications/vscodedev/vscode'"

I'm in the middle of a major project right now, and have devoted a lot of time to trying to troubleshoot this. I'm hoping someone else can replicate it and help.  I can't devote more time in the next 6 weeks.

1. Open Code
2. Connect to a network drive (smb://server/share).
3. Open a file on the network drive, either by File>Open or by browsing and opening in VS Code
4. Disconnect the network drive
5. Wait about a minute and go back to your Code window (or close/reopen your laptop lid)

It appears that the watcher can't find the file and instead of just leaving it open and unsaved (like Atom does), it actually crashes and pops up an error/reload window.

**Comment by bpasero** [comment]
@spraguey thanks for your time, I am sure someone else can chime in.

**Comment by bpasero** [comment]
@spraguey just a quick question: we recently did a major update of our Electron framework and there is a potential that this issue got fixed by the update. If you could just try your steps on our Insider build to see if it reproduces?

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by spraguey** [comment]
Well, it's good news and bad. The tab no longer crashes and forces a reload. However, the file actually closes. It really should just leave the file open. Displaying an error saying it cannot save or cannot be found is fine, but the file should not go away!  So, the crash is fixed, but the underlying problem remains. If you leave files open to work on later, they will all get closed on you.

![screen shot 2016-09-17 at 3 14 31 pm](https://cloud.githubusercontent.com/assets/7975874/18610402/7a41cd00-7ce9-11e6-97cf-d8b3821a1958.jpg)

**Comment by bpasero** [comment]
@spraguey I think this is still very good news because a crash is the worst case that can happen. 

I find it interesting that the tab would close... so you say you say:
* you have a file open
* you disconnect the drive
* the file tab closes in VS Code and this error message shows up?

**Comment by spraguey** [comment]
@bpasero Yes, that is correct. The problem that creates is that all the files I had open for a project will close and I have to go find and re-open them all every time I move from wired to wireless, or work to home.

**Comment by bpasero** [comment]
@spraguey can you run `code-insiders --verbose` and open the developer console (Help > Toggle Developer Tools) and when the network drive goes away look and attach the output you see? The interesting part is the output for the file watcher which I suspect throws a lot of file delete notifications. This in turn causes us to close files:

![image](https://cloud.githubusercontent.com/assets/900690/18657521/3a1e0a4a-7efb-11e6-8cf3-997c3cca8a51.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13665
