### ISSUE TITLE
The Ctrl+R in integrated ZSH terminal does not open `bck-i-search`

### ISSUE THREAD

**Issue by memee** [microsoft/vscode#109078]
- VSCode Version: 1.50.1
- OS Version: Darwin x64 19.6.0 / MacOS Catalina 10.15.7

Steps to Reproduce:

1. Open integrated terminal
2. Press Ctrl+R

Does this issue occur when all extensions are disabled?: Yes

My settings:

```
{
  "editor.accessibilitySupport": "off",
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "[javascript]": {
    "editor.formatOnSave": true
  },
  "[typescript]": {
    "editor.formatOnSave": true
  },
  "editor.tabSize": 2,
  "editor.parameterHints.enabled": false,
  "editor.acceptSuggestionOnCommitCharacter": false,
  "editor.quickSuggestionsDelay": 10,
  "editor.wordBasedSuggestions": false,
  "editor.acceptSuggestionOnEnter": "on",
  "editor.quickSuggestions": {
    "other": false,
    "comments": false,
    "strings": false
  },
  "files.insertFinalNewline": true,
  "javascript.implicitProjectConfig.checkJs": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "window.autoDetectColorScheme": true,
  "terminal.integrated.macOptionIsMeta": true,
  "terminal.integrated.allowChords": false,
  "terminal.integrated.shell.osx": "/bin/zsh",
  "workbench.colorTheme": "Default Light+"
}
```

**Comment by Tyriar** [comment]
Does something else happen when you press ctrl+r? What I suspect is happening is some keybinding either that you have setup or from an extension is being run instead of passing to the terminal. Things you could check:

- Try closing all windows and running with `code --disable-extensions`
- Use escape sequence logging to confirm whether ctrl+r is being sent to zsh https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by memee** [comment]
@Tyriar I've tried with `--disable-extensions` as well. No visible things are happening when `Ctrl+R` is pressed inside terminal or in other words nothing's happening.
After I did escape sequence logging, I got following message in the console:
```
xterm.js: parsing data 

[0m[27m[24m[Jmacio@MacBook-Pro ~ % [K
```
<img width="515" alt="image" src="https://user-images.githubusercontent.com/1036737/97915408-b91a5800-1d51-11eb-8071-f3bc87020f14.png">

**Comment by Tyriar** [comment]
Ok it looks like nothing happened when you pressed ctrl+r, otherwise it would say "sending data". Try searching your keybindings (cmd+k, cmd+s) for "ctrl+r" and see what results come up.

**Comment by memee** [comment]
@Tyriar, I got this:
<img width="1066" alt="Zrzut ekranu 2020-11-3 o 13 06 46" src="https://user-images.githubusercontent.com/1036737/97983450-9e89c280-1dd5-11eb-8c2f-c62f3a943da4.png">

**Comment by Tyriar** [comment]
Ok that's seems like the problem then, open up your keybindings.json file to inspect what it's meant to be doing and removing it or commenting it out should fix the problem.

**Comment by memee** [comment]
@Tyriar problem is that my keybindings are empty:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1036737/98013544-c93a4200-1dfa-11eb-8948-cceb3a7c4a21.png">
I don't know where it comes from. I even can't remove that entry from UI editor.

**Comment by Tyriar** [comment]
Can you right click delete the keybinding?

![image](https://user-images.githubusercontent.com/2193314/98014438-805d9b80-1db0-11eb-8fb5-1362ba1f7b84.png)

**Comment by memee** [comment]
@Tyriar I could delete it, but `Ctrl+R` still does not work in terminal
<img width="721" alt="image" src="https://user-images.githubusercontent.com/1036737/98017403-7ca53580-1dff-11eb-9e6d-f9db928a9f3d.png">
I tried again with disabled extensions but it still doesn't work.

**Comment by Tyriar** [comment]
Does it work if you install the Insiders build or close all windows and launch with `code --disable-extensions --user-data-dir ./temp` (this will create a `temp` folder in that folder that you can delete later)

**Comment by memee** [comment]
@Tyriar I've tried with `code --disable-extensions --user-data-dir ./temp`. Still doesn't work. Nothing happens.
I also tried Insiders build. Same results.

**Comment by Tyriar** [comment]
@memee do you have `terminal.integrated.commandsToSkipShell` in your settings file by chance? I'm starting to run out of ideas of what could be your issue 😛

**Comment by memee** [comment]
@Tyriar definetely not both for workspace and user settings:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/1036737/98078832-1b1eae80-1e73-11eb-9594-536e0c815b10.png">
<img width="375" alt="image" src="https://user-images.githubusercontent.com/1036737/98079005-6cc73900-1e73-11eb-9b6f-97337ce4bd06.png">

I also have following settings:
```
  "terminal.integrated.macOptionIsMeta": true,
  "terminal.integrated.allowChords": false,
  "terminal.integrated.shell.osx": "/bin/zsh",
```

**Comment by memee** [comment]
@Tyriar I temporarily changed to `"terminal.integrated.shell.osx": "/bin/bash"` and it works for bash though.

**Comment by Tyriar** [comment]
@memee 🤔 if that's the case then escape sequence logging should have shown ctrl+r get sent here:

https://github.com/microsoft/vscode/issues/109078#issuecomment-720704597

**Comment by memee** [comment]
@Tyriar when on `/bin/zsh` this is sent to console:
![image](https://user-images.githubusercontent.com/1036737/98211959-2b05c380-1f43-11eb-8657-28bc9576f693.png)
when on `/bin/bash` I see this in the console:
<img width="1191" alt="Zrzut ekranu 2020-11-5 o 08 42 37" src="https://user-images.githubusercontent.com/1036737/98212016-453fa180-1f43-11eb-986d-2cdc25358193.png">

**Comment by memee** [comment]
@Tyriar Hmm, it looks like **VIM** bindings are enabled and ctrl+r acts as redo. Once I had vim extension installed now I uninstalled that. When i write sth into terminal hit `<ESC>` and then `u` (undoes) then `Ctrl+R` redos. I have not enabled vim bindings anywhere. I don't know if it's the real cause.

**Comment by Tyriar** [comment]
Are these vim bindings actually within the terminal or do you mean a VS Code extension? I looked at the vscodevim extension and it has ctrl+r bound but it also have context keys that should not impact the terminal when it's focused:

https://github.com/VSCodeVim/Vim/blob/edc87d87c6505a1d15c5e90bb5d255a114815db9/package.json#L251-L255

Inside the terminal you were using plain bash/zsh right, so no vim involved there?

**Comment by Tyriar** [comment]
But anyway, your screenshots above show that character 18 is correctly being sent to your shell, so it must be an issue with your shell not handling it correctly. VS Code sending that characters is all we need to do on our side. Something in your zsh config or a zsh plugin must be intercepting it and changing the behavior.

**Comment by memee** [comment]
Ok @Tyriar, I'll check that clue. I was just wondering why it works OK on my terminal app though.

**Comment by memee** [comment]
@Tyriar what helped me was `set -o emacs` inside terminal. The question is why in VSCode integrated terminal uses `vi` keybindings instead of default `emacs` keybindings?

**Comment by memee** [comment]
For now I just added explicit `set -o emacs` to my `.zshrc`

**Comment by Tyriar** [comment]
@memee we don't use either, ctrl+r simply gets passed to the terminal, we don't configure it in any particular way.

Maybe you're not expecting to run a login shell? Setting `"terminal.integrated.shellArgs.osx": []` might be the reason?

**Comment by memee** [comment]
No difference whether `"terminal.integrated.shellArgs.osx": []` or `"terminal.integrated.shellArgs.osx": ["-l"]`

**Comment by Tyriar** [comment]
Ah ok, well I'm pretty sure it's a config issue outside of the control of VS Code since VS Code is sending the keystrokes to the shell (https://github.com/microsoft/vscode/issues/109078#issuecomment-722204355), it's the shell that's not handling them right.

**Comment by memee** [comment]
@Tyriar now it's clear that VSCode is sending right keystrokes. I'm rather asking why in my native terminal emulator "emacs" bindings are set by default but in VSCode "vi" bindings are set in integrated terminal.

**Comment by Tyriar** [comment]
The only things I'm aware of that could influence that are how you launch the shell (`terminal.integrated.shellArgs.osx` in VS Code) and what the resulting environment is (`env`).

**Comment by memee** [comment]
@Tyriar Nevertheless thanks for support 😄 !
