### ISSUE TITLE
exclude files/folders from being searched (using ctrl+P)

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#10919]
- VSCode Version: insiders
- OS Version: windows 10

In `.vscode/settings.json` I have:
```js
    "files.exclude": {
        "out": false // set this to true to hide the "out" folder with the compiled JS files
    },    
    "search.exclude": {
        "out": true // set this to false to include "out" folder in search results
    },
```

![image](https://cloud.githubusercontent.com/assets/736697/17950244/6842eac2-6a73-11e6-9add-c17597d243a1.png)

But files in out dir is still in the pick (ctrl+P) result
![image](https://cloud.githubusercontent.com/assets/736697/17950241/5a77d4c0-6a73-11e6-8aec-f16e566b7086.png)

Is it expected behaviour? Is it possible to exclude it from this list?

**Comment by sandy081** [comment]
Yes, if you open the js file manually, Quick open show it in the recently opened section.

**Comment by whitecolor** [comment]
@sandy081 I'm not sure could you comment this:
1) I have `out` in "search.exclude"
2) I want to find files in `/src` (it is not in out)
3) It shows me all the files that is in `out/src`
![image](https://cloud.githubusercontent.com/assets/736697/17976548/6d7a98ac-6b07-11e6-9542-ca7e54496488.png)

I didn't open them at all. Is it possible to hide them at all in quick view? This this setting "search.exclude" seem not for this. Probably it effects "Ctr+Shift+F" (content search).

So is it possible some how to achive what I need? (not to see at all files from `/out` folder in quick open)

**Comment by sandy081** [comment]
I am reopening this for further investigation

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6502

**Comment by bpasero** [comment]
@whitecolor I am assuming that your results are from the editor history. If not, please let me know. Maybe attach a larger screenshot that shows where the results are coming from in that box 👍

**Comment by whitecolor** [comment]
@bpasero I'not sure but it seem to wok ok now, was something fixed in latest insiders?

**Comment by bpasero** [comment]
@whitecolor not really in that area I think...

**Comment by bpasero** [comment]
The key thing is that there a file results in quick open and history results. If your history is empty, you might think the bug is fixed. But as soon as you build up history entries, you will see entries again that are not excluded with the patterns. That is described in #6502

**Comment by esdrasbeleza** [comment]
I use a library that I develop in some of my projects, so it lives in their `vendor` directories. 
I have `vendor ` in `files.exclude`, but I keep editing my vendored files because quick open lists them.

Could we please reopen this? :(

**Comment by Mohamed3on** [comment]
`search.exclude` doesn't hide all the folders I want to hide too. I have a `folder/platforms/` folder that I want to hide, I set it to `true` in `search.exclude` and it still shows in a search.

**Comment by SimonSchick** [comment]
Maybe adding a setting that will exclude even recent and open files would be helpful?
