### ISSUE TITLE
TypeScript Server Error: No project

### ISSUE THREAD

**Issue by dereknelson** [microsoft/vscode#110439]
Been getting this error for over year on various typescript versions. Saw [this tweet](https://twitter.com/drosenwasser/status/1215050252056555522v) and decided to finally do something about it.

Error: 
```
  ERR <semantic> TypeScript Server Error (3.7.3)
No Project.
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:133314:23)
    at ScriptInfo.getDefaultProject (tsserver.js:134061:46)
    at ProjectService.doEnsureDefaultProjectForFile (tsserver.js:136599:48)
    at ProjectService.ensureDefaultProjectForFile (tsserver.js:136594:75)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:140251:87)
    at IOSession.Session.getFileAndProject (tsserver.js:140234:29)
    at IOSession.Session.getDocumentHighlights (tsserver.js:140077:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139501:61)
    at tsserver.js:140929:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140920:28)
    at IOSession.Session.executeCommand (tsserver.js:140929:33)
    at IOSession.Session.onMessage (tsserver.js:140952:35)
    at Interface.<anonymous> (tsserver.js:142267:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <semantic> TypeScript Server Error (3.7.3)
No Project.
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:133314:23)
    at ScriptInfo.getDefaultProject (tsserver.js:134061:46)
    at ProjectService.doEnsureDefaultProjectForFile (tsserver.js:136599:48)
    at ProjectService.ensureDefaultProjectForFile (tsserver.js:136594:75)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:140251:87)
    at IOSession.Session.getFileAndProject (tsserver.js:140234:29)
    at IOSession.Session.getDocumentHighlights (tsserver.js:140077:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139501:61)
    at tsserver.js:140929:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140920:28)
    at IOSession.Session.executeCommand (tsserver.js:140929:33)
    at IOSession.Session.onMessage (tsserver.js:140952:35)
    at Interface.<anonymous> (tsserver.js:142267:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:47388)
	at h.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:206557)
	at h.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:205455)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:204931
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at t.Reader.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:212021)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:211669)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
[Gist of tsserver log](https://gist.github.com/dereknelson/9539392f86b2dfb9e6b35542c7ba8e20) 

**TypeScript Version:**  3.7.3

**Expected behavior:** 
TypeScript server to just work

**Actual behavior:**
Suggestions/hints stop working, autocomplete stops working, under random, extreme circumstances I'll lose syntax highlighting

**Comment by mjbvz** [comment]
This may be fixed by 7c6994d1b5907d688b079c06901505d646e89091, which adds a check to make sure the current file is open before making a request. Having trouble verifying this though since I'm not sure of the exact steps to reproduce the original issue

Let me know if you still see this issue in tomorrow's VS Code build

**Comment by gluxon** [comment]
@mjbvz Thank you!

> Having trouble verifying this though since I'm not sure of the exact steps to reproduce the original issue

It's definitely a difficult issue to reproduce. I suspect killing the tsserver process while it's in the middle of doing *"Find All References"*/"*Rename Symbol*" may reproduce it, but you need a large enough repository so those operations take more than a few seconds.

> This may be fixed by 7c6994d, which adds a check to make sure the current file is open before making a request.

The nuance of this issue is that the "No Project" error is just a symptom of certain editor operations causing tsserver to run out of memory and crash. The specific "No Project" error will likely be fixed by your commit.

But separately, users still see their memory intensive editor operations take a long time and ultimately no-op. To reduce confusion, should VSCode perhaps notify users when tsserver crash? At the moment the crash is fairly transparent without any message in the UI or developer tools console. This behavior leaves users confused and not know what happened with their reference search or rename.

**Comment by mjbvz** [comment]
Marking this as verified since we have not seen recent reports of this issue, although I'll keep an eye on this post 1.52 release

**Comment by Alonski** [comment]
@mjbvz Still happening for me :)
Actually its only started happening recently so pretty weird :)

**Comment by mjbvz** [comment]
@Alonski  Open a new issue
