### ISSUE TITLE
Source Control input box is frozen when typing CJK characters

### ISSUE THREAD

**Issue by mznet** [microsoft/vscode#112621]
- VSCode Version: 1.52.0
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Open Source Control panel and click the plus button to stage untracked files.
2. Type CJK characters(in my case, Korean) into message input box.
3. The message input would be frozen. Latin characters are fine.

Does this issue occur when all extensions are disabled?: Yes

![Dec-16-2020 11-44-26](https://user-images.githubusercontent.com/9622730/102298257-27c71400-3f94-11eb-8626-17671a78d07c.gif)

This issue seems to be started since vscode version 1.52.0. Before the update, this issue was not exists.

**Comment by GranBlueFu** [comment]
It happens after typing while Source Control is doing any background task. When it's done, if there are any remaining characters, the input box is freezing.

**Comment by he0119** [comment]
It also happens to me when using Microsoft Pinyin IME.

**Comment by GranBlueFu** [comment]
Still present in 1.52.1

**Comment by niusounds** [comment]
Please fix this~
I can't write a Japanese commit message because of this bug...

**Comment by 74th** [comment]
It's caused in my Linux and macOS.

**Comment by tsukumijima** [comment]
I'm Japanese, my VS Code is having exactly the same problem.

**Comment by mznet** [comment]
@eamodio any update?

**Comment by mysticatea** [comment]
This bug is on Windows as well:

```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by mysticatea** [comment]
Looks like, there is a ton of similar bug reports:

- https://github.com/microsoft/vscode/issues/112729 - git commit input box crashes
- https://github.com/microsoft/vscode/issues/113278 - can not input the commit message
- https://github.com/microsoft/vscode/issues/113527 - when I commit code to gitlab,vscode can't edit commit message
- https://github.com/microsoft/vscode/issues/113569 - git源代码管理，切换输入法时偶现提交消息输入框卡死
- https://github.com/microsoft/vscode/issues/113617 - Can't type git commit message

**Comment by yume-chan** [comment]
Also #113741

I believe any SCM view refresh will trigger this bug (possibly because it replaced the input box element with a new one), including stage/unstage files, clicking refresh button, etc

![GIF 2021-1-5 9-57-48](https://user-images.githubusercontent.com/1330321/103597990-856bd200-4f3c-11eb-95d9-a02828287a2d.gif)

However, it behaves a little different on my machine, the SCM refresh cancels my text composition, but I can still input more Chinese to the input box.

```
Version: 1.53.0-insider (user setup)
Commit: 98106c48a07d4d07f0f71b4db9b3ff156f223339
Date: 2021-01-01T05:22:15.141Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by yume-chan** [comment]
#113297 'Source Control' commit message input some time block

Maybe another variant.

**Comment by joaomoreno** [comment]
@alexdima Any thoughts here? 🤔

**Comment by yume-chan** [comment]
I remember this problem happened to many old (and poorly-designed) React apps.

Usually the most simple input looks like this:

```jsx
const [value, setValue] = useState('');
const handleChange = e => setValue(e.target.value);
return <input value={value} onChange={handleChange} />
```

However some apps filter input in the event handler, which causes React to re-render the `<input>`, and IMEs will behave incorrectly.

So basically you should not replace the `<input>` element, or set its value programmatically.

**Comment by alexdima** [comment]
@joaomoreno @eamodio Does the tree take the editor off-dom during such a refresh. On my side, I can see that there is composition in progress and the editor gets blurred before the composition ends.

**Comment by alexdima** [comment]
@joaomoreno I've pushed that the editor recovers partially from this case, but it looks like the underlying browser textarea is broken (for a lack of a better word) until focus is manually moved out and back in. Here are the steps to observe that the textarea becomes broken because it is taken off-dom during composition.
* go to `src/vs/editor/browser/controller/textAreaInput.ts` and add a log statement just inside line 195 (`this._register(dom.addDisposableListener(textArea.domNode, 'compositionstart', (e: CompositionEvent) => {`) 
* ![image](https://user-images.githubusercontent.com/5047891/103700426-b5e75680-4fa4-11eb-9403-95c490d1d853.png)
* add another one just inside line 316 (`this._register(dom.addDisposableListener(textArea.domNode, 'input', () => {`):
* ![image](https://user-images.githubusercontent.com/5047891/103700453-c3044580-4fa4-11eb-91c0-228a0a8b963d.png)
* on Windows, install the Japanese input (see steps at https://github.com/microsoft/vscode/wiki/IME-Test#windowsmac-japanese)
* switch OS input method to Japanese and choose Hiragana
* ![image](https://user-images.githubusercontent.com/5047891/103700530-e202d780-4fa4-11eb-9cf4-db522e55ca51.png)
* paste this to the console: `setInterval(() => { console.log(`activeElement`, document.activeElement); }, 3000);`
* have an unstaged change
* click on stage file
* quickly focus the SCM input and type `se` and wait
* observe how composition is suddenly stopped (this is caused by the editor being taken off-dom)
* the focus is still in the editor but any keypress does not result in any input or composition being done by the browser
* if you click outside the editor abd click back in the browser recovers.


![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/103701007-98ff5300-4fa5-11eb-8302-0bd2804bbec6.gif)

**Comment by alexdima** [comment]
:+1: @joaomoreno I verified running from master and I can no longer repro

**Comment by yume-chan** [comment]
I verified on latest insiders build and I can't repro anymore either

```text
Version: 1.53.0-insider (user setup)
Commit: 3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e
Date: 2021-01-11T05:14:06.672Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by 2007lf** [comment]
please fix this bug, still happen.

**Comment by dinglittle** [comment]
please fix this bug, still happen. +1

**Comment by alexdima** [comment]
@2007lf @dinglittle A fix is available on the VS Code Insiders Channel - https://code.visualstudio.com/insiders/ . It will become available in VS Code Stable at the beginning of February.

**Comment by ccloli** [comment]
Is this bug also drives to terminal input? I'm experiencing a similar problem on terminal, when inputing with CJK IME, the selected word will not be filled, or it will ignore some characters. I also tried the latest inside build but can still get this problem. 

![vscode-terminal](https://user-images.githubusercontent.com/8115912/105803068-98237500-5fd7-11eb-8949-7dafe9e79600.gif)

This bug happens at around 1.52.0, and it occurs when you're inputing CJK letters with some CJK IME (for my example, this bug happens with [QQ Pinyin](http://qq.pinyin.cn/), but with Microsoft Pinyin it works fine).

**Comment by mznet** [comment]
@ccloli this issue only limited to source control input not terminal input. But just in case, I tried to input korean characters on terminal and it worked well.

**Comment by ccloli** [comment]
@mznet okay, I just find a related issue and will post it there. Thanks for your testing, and sorry if it distribs you.
