### ISSUE TITLE
Error pushing to git remote with http

### ISSUE THREAD

**Issue by jasabalete** [Microsoft/vscode#1138]
I have configured my git remote like this:

    [remote "origin"]
	    url = http://MY-HOST.../branch-locatlocator-select-ui.git

And when i do a push show me an error:
    
    fatal: Authentication failed for 'http://MY-HOST.../branch-locatlocator-select-ui.git/'

Why Visual Studio Code add the final slash? :(

**Comment by joaomoreno** [comment]
Oh that's terrible, sorry for that!

**Comment by joaomoreno** [comment]
I assume a simple `git push` from the command line works, right?

**Comment by jasabalete** [comment]
Yes,  "git push" from the command línea works

**Comment by joaomoreno** [comment]
Git seems to do this, not VS Code. Here's a snippet from the command line:

```
$ git push
Username for 'https://github.com': joaomoreno
Password for 'https://joaomoreno@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/joaomoreno/node-libarchive.git/'
```

Is your host by any chance GitHub or BitBucket? Which command line exactly are you using?

Closing as dupe of #490. Will reopen if further information reveals this to be an independent issue.

**Comment by jasabalete** [comment]
My repo is GitLab CE

    $ git config remote.origin.url
    http://ISLINGIP01.scisb.isban.corp/portales-branch-locator/branch-locator-select-ui.git

The URL with the final slash only apears in VSCode and if i put this URL in Chrome for example return ERR_TOO_MANY_REDIRECTS

Why VSCode connect with the remote and add a final slash?

**Comment by jasabalete** [comment]
Note: the error is in VSCode when I do a push or a pull in the Git feature

**Comment by joaomoreno** [comment]
Is there any way you can set up a repository in that same server and give me credentials to access it so I can try to repro?

**Comment by jasabalete** [comment]
the same error in gitlab.com repository.

I invite you in a public repository for testing and "master" role :)

**Comment by jasabalete** [comment]
I do this:
1 - Create a public repository 
2 - git clone https://blah/blah.git
3 - Open the folder with VSCode
4 - Commit and push a file
5 - VSCode add final slash "/" and error 
    fatal: Authentication failed for 'https://blah/blah.git/'

**Comment by joaomoreno** [comment]
Thanks for the repo access. There was definitely a problem with VS Code's credential helper. When running the push action, you should have seen this dialog:

![image](https://cloud.githubusercontent.com/assets/22350/11739560/b8ad5832-9fec-11e5-8545-4d40e0bc6a20.png)

The dialog is not showing up in `0.10.3` unfortunately. Fixed it and will be in for the December milestone.

With the fix, I was able to successfully push to the GitLab repo using the credentials I configured in the GitLab website.

**Comment by jasabalete** [comment]
This dialog is showing to me. I put the credentials and show the error

**Comment by joaomoreno** [comment]
I am using the username that I found in the bottom left corner of the GitLab UI. You can't use your e-mail address.

![image](https://cloud.githubusercontent.com/assets/22350/11760987/b77b20c8-a0b1-11e5-989f-187c5213f4c0.png)

And the password set in the following dialog:

![image](https://cloud.githubusercontent.com/assets/22350/11760989/c89fabc6-a0b1-11e5-89bd-bb7db262dd94.png)

Please make sure you are using the right credentials, reset your password, try again, etc.

**Comment by jasabalete** [comment]
I know my credentials. I use this repository from several project with eclipse and command line too and works with ssh and https connections. 

Thank for all :)

**Comment by joaomoreno** [comment]
If you use the SSH remote url, it should all work, since no password prompt will occur.

If you use HTTPS, you should get the prompt. I do, I input the credentials I configured in GitLab and it works for me.

Maybe it's platform specific? Which platform are you on?

**Comment by spongessuck** [comment]
I have a development server on my domain that's running Bonobo Git Server set up to use Windows authentication. My credentials work everywhere except in VS Code. I get a similar authentication error with the trailing slash.

**Comment by jasabalete** [comment]
The new versión of VSCode WORKS :)

Thanks and go on!

**Comment by spongessuck** [comment]
I'm using VSCode 0.10.6 (newest version) and I still have this problem.

**Comment by joaomoreno** [comment]
@spongessuck which protocol does your git server use? Can you show me its URL? Can you create an account on it for me to validate your claim?

**Comment by spongessuck** [comment]
@joaomoreno It's using HTTP- it's a .NET web app running on IIS. You can find the software page here:

https://bonobogitserver.com/

Sorry, the server isn't accessible outside of our domain.

I'm accessing it via LAN. A typical git repo URL looks like:

http://timeweb/git/<repo>.git

**Comment by robbaman** [comment]
I can confirm that this issue still persists to some extent. We are using bitbucket as git store and when pushing from VS Code an additional / is added to the url when pushing (or pulling) and an authentication error is thrown.

Opening a console and doing `git push` works just fine, except that the warning is displayed regarding the new push.default config setting that is still unset. It appears that setting this setting using `git config push.default matching` the error goes away in VS Code

**Comment by plogen** [comment]
Same problem for me with GitLab CE. Visual Studio Code (0.10.6) adds a final forward slash to path and I get:
git fetch
fatal: Authentication failed for 'http://server/plogen/pHomeBackup.git/'
git pull
fatal: Authentication failed for 'http://server/plogen/pHomeBackup.git/'

Despite having no  final forward slash:
{
    "git.path": "http://server/plogen/pHomeBackup.git"
}

**Comment by joaomoreno** [comment]
@robbaman @plogen ignore the slash, it has nothing to do with the problem

When you guys test this, do you get the [authentication dialog](https://cloud.githubusercontent.com/assets/22350/11739560/b8ad5832-9fec-11e5-8545-4d40e0bc6a20.png)? Which OS are you on?

**Comment by robbaman** [comment]
Yes I did get the authentication dialog, but it always failed with the authentication failed message. Since I copy the credentials from a password store I am certain that there were no typos.

When I pushed from the git command line the push succeeded with a warning regarding the push matching method. I set it to *matching* per my preferences. After this, pushing from VS Code worked (and continues to work).

The way I see it either the fact that I pushed once from command line, or the changed matching setting caused the error to disappear. Since this all happened in a period of a few minutes it is unlikely anything else changed in the meantime.

I'm working on Windows 10 Pro

**Comment by agrivas** [comment]
Same issue here with GitHub account. Credentials work fine with cmd / TortoiseGit. VS Code fails. Installed VS code just today on Win 10 Home.

**Comment by web-dave** [comment]
same issue on vscode 0.10.6
i set my gitconfig to use https instead of git
[git config --global url."https://".insteadOf git://]
plattform windows 8.1
repro at github

**Comment by TejasCMehta** [comment]
@web-dave  @agrivas

Today I faced same issue with vscode 0.10.6. I got prompted with bitbucket credential window but when I enter it got failed. I am able to push to BitBucket with same credentials via sourcetree.

I found some steps to follow and then it worked well.

1) configure git to save your credentials locally and automatically append them to push commands generated from Code : Type the below in Git Bash:

```git config credential.helper store ```

2) initial push to GitHub, after that, you will be able to do all the push commands from Code. In Git Bash type:

``` git push –u origin master ```

Ref link : https://azure.microsoft.com/en-in/blog/visual-studio-code-and-azure-app-service-a-perfect-fit/

Hope it will help!

**Comment by web-dave** [comment]
@TejasCMehta 
worket fine thx.
store creds local resolved my probs.

**Comment by stefanvangastel** [comment]
@TejasCMehta; Fixed the problem for me!

**Comment by spongessuck** [comment]
@TejasCMehta 
Also worked for me.

**Comment by lv7777** [comment]
I also arise same bug on windows8.

**Comment by user414** [comment]
I wouldn't use store for this since as per git specs it store the password unencrypted on disk

https://git-scm.com/docs/git-credential-store

I would use 

```
git config credential.helper store
```
instead with optional timeout

https://git-scm.com/docs/git-credential-cache

This is still just a workaround until a proper fix but it works.

**Comment by joaomoreno** [comment]
I support the cache credential helper as a workaround until we tackle this issue head on.

**Comment by BryanConradHart** [comment]
I'm running into this problem too.
Ubuntu 15.10 (inside virtualbox on win10 pro)
VS Code -v 0.10.10

I do _not_ get presented with a credential dialog.
I am able to successfully push from command line.
doing `git config push.default matching `, pushing from commandline and then trying again from vsCode made no difference.

**Comment by jonathanfishbein1** [comment]
Similar set up to BryanConradHart getting the error

**Comment by jfaquinojr** [comment]
same as @jonathanfishbein1. Linux Mint 17.3

**Comment by ansarizafar** [comment]
I am also facing the same problem

**Comment by joaomoreno** [comment]
The authentication dialog was fixed by #1796, it should start coming up on the next release.

Meanwhile, I do suggest using a credential helper.

**Comment by michaelazer** [comment]
I'm running into the same error.
I can git push from the command line, but can't through VS Code.
I get the following error:

> Please make sure you have the correct access rights
and the repository exists.

I downloaded and installed the credential helper then tried both:
`git config credential.helper cache`
as well as 
`git config credential.helper store`
but still doesn't work.

ps. I'm using version 1.2.1

Thanks a lot for your support.

**Comment by jm-rives** [comment]
I was having a similar problem with OSX. I turned OFF 2 - factor authentication and the problem resolved itself.

**Comment by Ron1137** [comment]
I tried pushing to git hub but I got an error message saying couldn't connect to server . What can I do?
I followed all the push instruction , disabled the wifi proxy settings and used LAN cable but still nothing

**Comment by larssb** [comment]
To @jm-rives and others make sure to follow > [Authorizing when using two-factor auth](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)

I hope it helps.
