### ISSUE TITLE
Activity bar icons for extensions disappeared after updating to 1.53.0-insiders

### ISSUE THREAD

**Issue by yoshiotobe** [microsoft/vscode#114743]
- VSCode Version: 1.53.0-insiders
- OS Version: Windows 10 pro 1909 (OS build: 18363.1316)

Steps to Reproduce:

1. Connect to WSL or Virtualbox through Remote SSH (WSL)
2.

Does this issue occur when all extensions are disabled?: Yes

After updating VSCode Insiders to 1.53.0-insiders, when I connect to WSL or Virtualbox, Activity bar icons for extensions disappeared as shown in a photo below.

![vscode](https://user-images.githubusercontent.com/38850403/105460070-97849900-5cce-11eb-9f2c-2315ebe7bac7.jpg)

In those red circles, there should be Bookmark and Gitlens extensions icons. Bookmark extension does not show small images in a code neither. Extensions are working, so, it's a matter of displaying (linking) images.

When I use the editor locally, the icons appear. When I use VSCode (not Insiders), icons appear. I re-installed VScode Insiders, extensions, and re-created VM's of WSL and VirtualBox. However, none of them worked.

If there is any ways to solve the problem, I would appreciate it.

**Comment by gjsjohnmurray** [comment]
Related: #114740

**Comment by deepak1556** [comment]
Fixed was pushed last night https://github.com/microsoft/vscode/commit/70a3118892ba41c41dd54826a7441b73e7499ad9 , will ping here once new insiders is available for testing. Sorry about the issue.

**Comment by deepak1556** [comment]
Insiders released, can you update and verify. Thanks!

\closedWith https://github.com/microsoft/vscode/commit/70a3118892ba41c41dd54826a7441b73e7499ad9

**Comment by deepak1556** [comment]
\closedWith 70a3118

**Comment by plwalsh** [comment]
I updated my Insiders and I'm still seeing the issue. Was the fix incorporated in the release that went out about 4 hours ago?

Version: 1.53.0-insider (user setup)
Commit: ed72c64b87ede96fb51bc16870f9d2ecbf4fcc57
Date: 2021-01-22T17:18:22.679Z (4 hrs ago)
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.16299

![image](https://user-images.githubusercontent.com/43576448/105554090-a79f7700-5cd4-11eb-80cb-af06fe6fc7b8.png)
![image](https://user-images.githubusercontent.com/43576448/105554179-d0277100-5cd4-11eb-9da0-a430b0a21382.png)

**Comment by yoshiotobe** [comment]
Thank you for solving the issue. I use VScode instead for now and wait for the fixed version. I have been always using VScode, it is a great editor!

**Comment by deepak1556** [comment]
@plwalsh yes that release should contain the fix, can you open developer tools and paste the logs from it.

**Comment by Pablushka** [comment]
Same issue here. I'm using latest code-insiders build with remote containers. Logs attached:
![image](https://user-images.githubusercontent.com/1197279/105587833-1d0c5580-5d70-11eb-8d7e-9dbd6743e220.png)

**Comment by plwalsh** [comment]
@deepak1556 here are the errors I'm seeing.

Errors for my sidebar (gitlab and atlassian extension icons):
![image](https://user-images.githubusercontent.com/43576448/105592656-addb3500-5d60-11eb-9820-3600a134b71f.png)

Errors for my gitlens editor icons:
![image](https://user-images.githubusercontent.com/43576448/105593636-f266d080-5d60-11eb-8130-82916c34b0ed.png)

**Comment by deepak1556** [comment]
Thanks! one more, can you start insiders with `code-insiders --log-net-log=<abs-path>/netlog.json` and once you see missing icons, quit the app and attach the netlog file here.

**Comment by tetious** [comment]
Here you go!
[netlog.json.zip](https://github.com/microsoft/vscode/files/5860647/netlog.json.zip)

**Comment by deepak1556** [comment]
Thanks for the logs, should be fixed in next insiders releasing tomorrow.

**Comment by nqdrizzt** [comment]
Even after the latest merge the latest insider buidl is missing some icons, in this cats in tne the WSL Extension Remote Explorer. The Buttons missing are used to jump between different remote folder . Pls see screenshot below:

![image](https://user-images.githubusercontent.com/31509303/105682389-aea3d080-5ef2-11eb-9316-7e40fac44159.png)

**Comment by tetious** [comment]
Confirmed fixed for me too. Thanks very much!

**Comment by tvvignesh** [comment]
The latest update works for me as well 👍
