### ISSUE TITLE
Multi-target debugging bugs

### ISSUE THREAD

**Issue by a-ejs** [microsoft/vscode#118006]
vscode 1.53.2

Workspace:

`.vscode/launch.json`:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "one",
			"program": "${workspaceFolder}/one.js",
			"request": "launch",
			"type": "pwa-node"
		},
		{
			"name": "two",
			"program": "${workspaceFolder}/two.js",
			"request": "launch",
			"type": "pwa-node"
		}
	],
	"compounds": [
		{
			"name": "three",
			"configurations": ["one", "two"]
		}
	]
}
```

`one.js`:
```js
debugger;
```

`two.js`:
```js
setInterval(() => {});
```

Repro:

1. Launch `three` (which is a compound of `one` and `two`)
2. Debugger hits breakpoint in `one`
3. Switch from `one` to `two` either using the debug console dropdown or by clicking it in the sidebar
   * note that the debug console dropdown immediately reverts back to 'one' (*1)
4. Switch back to `one` using debug toolbar dropdown
   * note the absence of breakpoint view (*2)
5. Type something in debug console
   * it doesn't evaluate (*2)
6. Terminate both sessions
7. Launch `two`
8. Switch to `one` using debug console dropdown
9. Try to switch back to `two`
   * (you can't) (*3)

Bugs:

1. Debug console dropdown displays an incorrect item inconsistent with what's actually being debugged/displayed in debug console.
   * Can be observed after step 3 in the repro.
   * Also randomly occurs in a bunch of other scenarios (e.g. when starting/terminating sessions).

2. Debug toolbar dropdown is broken (?).
   * Can be observed after steps 4-5 in the repro.
   * Breakpoint view isn't active after switching to a paused session.
   * Expressions don't evaluate in debug console.
   * Doesn't even trigger bug 1
   * Overall inconsistent behavior with the sidebar and debug console dropdown.

3. Switching to an inactive session causes debug console dropdown to break.
   * Repro is pretty self explanatory.

**Comment by isidorn** [comment]
@a-ejs thanks for this bug with nice repro steps. I just tried with latest VS Code insiders and I could only reproduce:
"note that the debug console dropdown immediately reverts back to 'one' (*1)"

All the other points work fine - I pushed some fixes in this area so this might explain it.

I will not investigate into *1 and hopefully fix that too, once I push that I would ask you to try it out with VS Code insiders starting from Friday to let me know how it goes. Thanks!

**Comment by a-ejs** [comment]
@isidorn
I tried on Insiders yesterday and couldn't reproduce bug 2, so that must've been fixed.

After the update, bug 1 no longer occurs when switching between sessions manually, but I can still repro it when stopping sessions:
* launch `three`
* terminate `one` (view switches to `two`)
* terminate `two` (dropdown now shows `one` but console still shows output of `two`)

Bug 3 still exists for me:
* launch `three`
* stop debugging
* launch `two` alone
* switch to output of `one`
* can't switch back to `two`

PS. Tested on windows

**Comment by isidorn** [comment]
My fix is not yet on Insiders, that is why I said starting from Friday. Today is Thursday (at least in my timezone)
So can you please try again tomorrow?

**Comment by a-ejs** [comment]
aye, my bad

**Comment by isidorn** [comment]
It should be out now.

**Comment by a-ejs** [comment]
Seems to be fixed on the latest insiders.

However bug 3 is still there (with these steps:)
> * launch `three`
> * stop debugging
> * launch `two` alone
> * switch to output of `one`
> * can't switch back to `two`

**Comment by isidorn** [comment]
Thanks. I pushed a fix.

**Comment by a-ejs** [comment]
Tried on latest insiders and could reproduce with slightly different steps:
* Launch `three`
* Terminate both sessions
* Launch `two`
* Launch `one`
* Terminate `two`
* Switch to `two` in debug console
* Can't switch to `one`

**Comment by isidorn** [comment]
@a-ejs thanks, i have pushed a fix for this.
Sorry for the multiple fixes. And thanks for trying this out
