### ISSUE TITLE
VSCode 1.54.1 breaks spawned processes with cwd option

### ISSUE THREAD

**Issue by jeremie-stripe** [microsoft/vscode#118267]
- VS Code Version: 1.54.1
- OS Version: macOS 10.15.17

Steps to Reproduce:

1. Upgrade to VSCode 1.54.1 from 1.53
2. A few of our extensions are failing to start because spawned shell script processes do not work

Does this issue occur when all extensions are disabled?: No

We run a few extensions (including an LSP server) which essentially spawn an external process executing shell wrapper scripts and attempts to manipulate its standard IO.

Since upgrading to 1.54.1 we have noticed a strange behavior where when writing to the external process stdin we get `EBADF` error. This seems specifically to only occur when attempting to execute shell script directly as when we modify the spawn (or similar functions) to invoke the script via `bash` directly it works fine.

This is illustrated by the following test cases executed while debugging VSCode:

```
> cp.execFile("cat", ['-'], options, cb).stdin.write("foo\n")
true
> cp.execFile("scripts/bin/wrapper.sh", ["cat", "-"], options, cb).stdin.write("foo\n")
Uncaught Error: write EBADF
> cp.execFile("bash", ["scripts/bin/wrapper.sh", "cat", "-"], options, cb).stdin.write("foo\n")
true
```
Where `wrapper.sh` ultimately will `exec` the rest of the command line.

**Comment by deepak1556** [comment]
We just released an update to VS Code Insiders that has a fix for this issue. Please try it out and let us know.

**Comment by jeremie-stripe** [comment]
@deepak1556 thanks

I tested with:

Version: 1.55.0-insider (Universal)
Commit: 9b2ee7fb7d970b9a628fdb3545bdd01d67078d16
Date: 2021-03-11T05:15:23.749Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

And the problem persists. With my mentioned test case I'm now getting EPIPE instead of EBADF:

```
require('child_process').execFile("bash", [""scripts/bin/wrapper.sh"", "cat", "-"]).stdin.write("foo\n")
true
require('child_process').execFile(""scripts/bin/wrapper.sh"", ["cat", "-"]).stdin.write("foo\n")
Uncaught Error: write EPIPE
```

**Comment by jeremie-stripe** [comment]
I tested this a bit more and another variant that I have found work is when you now specify the *full* path to the script (despite the cwd option being set correctly).

**Comment by jeremie-stripe** [comment]
To be more descriptive here is test case:

Given this foo.sh file (marked as executable) that is saved at `/Users/jeremie/stripe/sandbox/foo.sh`:
```shell
#!/bin/bash

echo "called" >> /tmp/debugout
```

Trying to execute the following statements in the debug console while debugging VSCode insiders (same version as noted above):

```
→ cp.execFileSync('foo.sh', [], {cwd: '/Users/jeremie/stripe/sandbox/'})
Uncaught Error: spawnSync foo.sh ENOENT
→ cp.execFileSync('/Users/jeremie/stripe/sandbox/foo.sh', [], {cwd: '/Users/jeremie/stripe/sandbox/'})
Uint8Array(0) []
→ cp.execFileSync('/Users/jeremie/stripe/sandbox/foo.sh', [])
Uint8Array(0) []
```

**Comment by deepak1556** [comment]
Thanks for the test case, I was previously testing your cases with absolute path. I see that cwd option for relative path is not respected, will look into it. 

Can you workaround with the absolute paths for your extensions as a temporary workaround ?

**Comment by deepak1556** [comment]
For https://github.com/microsoft/vscode/issues/118267#issuecomment-796860085

```
require('child_process').execFile("scripts/bin/wrapper.sh", ["cat", "-"]).stdin.write("foo\n")
Uncaught Error: write EPIPE
```

Node 12.18.3 which is the same version vscode uses also produces the same result, but seems to have been fixed in recent versions.

```
$ node
Welcome to Node.js v12.18.3.
Type ".help" for more information.
> const cp = require('child_process')
undefined
> cp.execFile('ex.sh', ['cat', '-'], {cwd: '/Users/demohan'}).stdin.write("foo\n")
Uncaught Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
```

**Comment by jeremie-stripe** [comment]
@deepak1556 you right, the command line should say `./foo.sh`

I tested in Node v10.16.0 (old version I had on hand):

```
> cp.execFileSync('./foo.sh', [], {cwd: '/Users/jeremie/stripe/sandbox/'})
<Buffer >
```
works

Back in VSCode insiders (same version) running in the debug console:
```
> cp.execFileSync('./foo.sh', [], {cwd: '/Users/jeremie/stripe/sandbox/'})
Uncaught Error: spawnSync ./foo.sh ENOENT
```

**Comment by jeremie-stripe** [comment]
And I think more specifically our case is the following because we use subpaths to reference our scripts:

Node 10.16.0:
```
> cp.execFileSync('sandbox/foo.sh', [], {cwd: '/Users/jeremie/stripe/'})
<Buffer >
```

VSCode Insiders debug console:
```
> cp.execFileSync('sandbox/foo.sh', [], {cwd: '/Users/jeremie/stripe/'})
Uncaught Error: spawnSync sandbox/foo.sh ENOENT
```

**Comment by deepak1556** [comment]
Thanks for clarifying, can confirm the regression.

**Comment by jvilk-stripe** [comment]
Looking forward to seeing this bug fixed! This bug has Stripe engineering stuck on 1.53 since it impacts so many of our extensions and configurations; one common pattern in our setup is using shell scripts to wrap other tools to set them up properly for our dev environment.

**Comment by deepak1556** [comment]
Fixed with https://domoreexp.visualstudio.com/Teamspace/_git/electron-build/pullrequest/344238, pending new builds.

**Comment by deepak1556** [comment]
Fix didn't account for some edge cases on the failure path and introduced regression https://github.com/microsoft/vscode/issues/122661. Reopening for next iteration.

**Comment by deepak1556** [comment]
This turned out to be a bug in the `posix_spawnp` implementation where a relative executable path will cause it to successfully launch the program, but erroneously return `ENOENT` when used with `posix_spawn_file_actions_addchdir_np` because of the stat call performed on the executable path after the child process is launched. Ref: https://opensource.apple.com/source/Libc/Libc-1439.40.11/sys/posix_spawn.c.auto.html

Have resorted to use `pthread_chdir_np` instead to respect the cwd option, will update here once the updated runtime is available.

**Comment by jeremie-stripe** [comment]
@deepak1556 thanks for figuring it out! I just tested with the latest insiders version (version info below) and I can confirm that our workloads are now properly working again!

```
Version: 1.57.0-insider (Universal)
Commit: 5246162662ffa9f16a70dc2b94f13b0d15511e64
Date: 2021-05-14T08:49:16.464Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.4.0
```
