### ISSUE TITLE
[macOS] docker and docker-compose not recognised if vscode is run with context menu entry

### ISSUE THREAD

**Issue by gr4nt3d** [microsoft/vscode#118372]
OK let me know if you still see it.

_Originally posted by @joaomoreno in https://github.com/microsoft/vscode/issues/92262#issuecomment-607225551_

- VSCode Version: <details><summary>Version: 1.54.1</summary>
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z (1 day ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

</details>

- ms-vscode-remote.remote-containers: v0.163.0
- Local OS Version: macOS Catalina 10.15.6 (19G73)
- Remote Extension/Connection Type: Docker / Docker-Compose
Steps to Reproduce:

Steps to Reproduce:
1. Open vscode via a context menu automator script, please see below [1]
2. Do not set absolute docker path in settings (docker-compose fails nevertheless [2])
3. Try to open a vscode-remote devcontainer with docker / docker-compose

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

#### How to force the right `process.env.PATH` for vscode / for the remote extension ?

#

### Details

[1] I use a automator script via a context menu entry to open files and folders in vscode. Please see [this thread/comment](
https://github.com/microsoft/vscode/issues/92262#issuecomment-607144178)

[2]  `vscode-remote-try-cpp-master` and `vscode-remote-try-python-master` work if `"remote.containers.dockerPath": "/usr/local/bin/docker"` is set in `settings.json` as mentioned [here](https://github.com/microsoft/vscode-remote-release/issues/4224#issuecomment-749545352).

<details><summary> log </summary>

```
[1 ms] Remote-Containers 0.163.0 in VS Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8).
[27 ms] Start: Resolving Remote
[29 ms] Setting up container for folder or workspace: .../vscode-remote-try-cpp-master
[35 ms] Start: Check Docker is running
[35 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[37 ms] spawn docker ENOENT
[38 ms] Docker returned an error code ENOENT, message: spawn docker ENOENT
```

</details>
<details><summary> manually checking in the terminal </summary>

```
user$ docker --version
Docker version 20.10.5, build 55c4c88
user$ docker version --format {{.Server.APIVersion}}
1.41
```

</details>
<details><summary> the script </summary>

```
#!/bin/bash
VSCODE_FORCE_USER_ENV=1 /usr/local/bin/code -n "$1"
```

</details>
<details><summary> <code>process.env.PATH</code>  </summary>

Path when it does not work (via script)
```
process.env.PATH
"/usr/bin:/bin:/usr/sbin:/sbin"
```
Path when it does work (vanilla start)
```
process.env.PATH
"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
```

**Comment by bpasero** [comment]
Maybe related: https://github.com/microsoft/vscode/issues/108804

**Comment by chrmarti** [comment]
Where is `/usr/local/bin` added to the `PATH`? Maybe check with `grep PATH .* | grep /usr/local/bin` in your home folder.

**Comment by gr4nt3d** [comment]
in `~/.bash_profile`
```sh
machine:~ user$ grep PATH .* | grep /usr/local/bin
[...]
.bash_profile:export PATH=/usr/local/bin:$PATH
```

**Comment by chrmarti** [comment]
@bpasero There is currently no logging in shell.ts to understand which shell was picked, could that be added?

I forgot how to add `--verbose` by default, but this case is probably similar to launching from the dock in that the log level will not persist across restarts. Having a setting to set the log level (that can then be overruled by the existing Set Log Level if compatibility is needed) would be helpful in these cases.

**Comment by bpasero** [comment]
Relaying to @joaomoreno who I think added the code to resolve the shell environment.

**Comment by bpasero** [comment]
@chrmarti fyi could be a duplicate of https://github.com/microsoft/vscode/issues/118460

**Comment by joaomoreno** [comment]
@chrmarti: https://github.com/microsoft/vscode/commit/f83b2f46dee5a2123cff7e6de5028633d991716a

**Comment by chrmarti** [comment]
@bpasero Was there a file to add `--verbose` (or any other option) to, so that would be used by default? Having a setting to persist the log level might also be a good idea...

**Comment by joaomoreno** [comment]
Won't `Preferences: Configure Runtime Arguments` work here?

**Comment by bpasero** [comment]
@chrmarti to my knowledge there is currently no way of persisting the log level, maybe @sandy081 knows

**Comment by chrmarti** [comment]
`Preferences: Configure Runtime Arguments` sounds good, but `"verbose": true`, `"log-level": "trace"` and `"logLevel": "trace"` did not work when I tried. 🤔

**Comment by bpasero** [comment]
We only allow a subset of runtime arguments not all.

**Comment by sandy081** [comment]
yes at present we do not persist log level

**Comment by chrmarti** [comment]
@bpasero app.ts seems to read the shell env and the argv.json, can we add support for `"log": "<level>"` to the argv.json? This has come up several times when launching from the Mac dock and we don't have a way to get at the detailed logs to analyze.

**Comment by bpasero** [comment]
Fine with me to add this, can we have a new issue for it? Note that `--verbose` does more things than just setting the log level (I believe).

**Comment by chrmarti** [comment]
@gr4nt3d When #118824 is released in VS Code Insiders (expected next Monday), could you:
- Run `F1` > `Preferences: Configure Runtime Arguments`.
- Add `"log-level": "trace"` to the opened argv.json.
- Close all windows and start VS Code through the context menu to reproduce the problem.
- Run `F1` > `Output: Focus on Output View`.
- Switch to the `Log (Main)` channel.
- Search for the entries containing "shellenv" (`Cmd + F` works), remove any private or secret information and append the entries here.

**Comment by gr4nt3d** [comment]
Freshly installed visual-studio-code-insiders via homebrew and the remote extension.

1. «Add "log-level": "trace" to the opened argv.json.» gives a problem (squiggly lines):
  `argv.json`
  Property log-level is not allowed.

2. trough 5. no problems
3. log gives (a little more but `shellenv` is highlighted - for me at least)<details>
    <summary> Log (Main) </summary>
    
    ```sh
    [2021-03-22 18:32:09.142] [main] [debug] Starting VS Code
    [2021-03-22 18:32:09.142] [main] [debug] from: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app
    [2021-03-22 18:32:09.142] [main] [debug] args: {"_":["/Users/user_name/Desktop/test_folder"],"diff":false,"add":false,"goto":false,"new-window":true,"reuse-window":false,"wait":false,"help":false,"list-extensions":false,"show-versions":false,"version":false,"verbose":false,"log":"trace","status":false,"prof-startup":false,"prof-v8-extensions":false,"disable-extensions":false,"disable-gpu":false,"telemetry":false,"debugRenderer":false,"logExtensionHostCommunication":false,"skip-release-notes":false,"disable-telemetry":false,"disable-updates":false,"disable-keytar":false,"disable-crash-reporter":false,"crash-reporter-id":"41dd21c6-2ddb-49de-ba6f-88bccf3a388b","skip-add-to-recently-opened":false,"unity-launch":false,"open-url":false,"file-write":false,"file-chmod":false,"driver-verbose":false,"force":false,"do-not-sync":false,"trace":false,"force-user-env":false,"force-disable-user-env":false,"open-devtools":false,"__sandbox":false,"no-proxy-server":false,"nolazy":false,"force-renderer-accessibility":false,"ignore-certificate-errors":false,"allow-insecure-localhost":false,"logsPath":"/Users/user_name/Library/Application Support/Code - Insiders/logs/20210322T183209"}
    [2021-03-22 18:32:09.142] [main] [trace] Resolving machine identifier...
    [2021-03-22 18:32:09.142] [main] [trace] Resolved machine identifier: f74c7d02ef15abfe673674683c620cbe2a4ca0d613f068b4f62e16fb16c2ba97
    [2021-03-22 18:32:09.142] [main] [trace] Main->SharedProcess#connect
    [2021-03-22 18:32:09.414] [main] [trace] StorageMainService: creating global storage
    [2021-03-22 18:32:09.415] [main] [trace] lifecycle (main): phase changed (value: 2)
    [2021-03-22 18:32:09.417] [main] [trace] windowsManager#open
    [2021-03-22 18:32:09.418] [main] [trace] windowsManager#open pathsToOpen [{"workspace":{"id":"f16c200b376bcb992eaf97090f54faf8","uri":{"$mid":1,"fsPath":"/Users/user_name/Desktop/test_folder","path":"/Users/user_name/Desktop/test_folder","scheme":"file"}},"exists":true}]
    [2021-03-22 18:32:09.420] [main] [trace] window#validateWindowState: validating window state on 1 display(s) {"mode":1,"x":208,"y":66,"width":1024,"height":768}
    [2021-03-22 18:32:09.420] [main] [trace] window#validateWindowState: 1 monitor working area {"x":0,"y":23,"width":1440,"height":877}
    [2021-03-22 18:32:09.420] [main] [trace] window#ctor: using window state {"mode":1,"x":208,"y":66,"width":1024,"height":768}
    [2021-03-22 18:32:09.656] [main] [trace] StorageMainService: creating workspace storage (f16c200b376bcb992eaf97090f54faf8)
    [2021-03-22 18:32:09.657] [main] [trace] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 1, emptyToRestore: 0, emptyToOpen: 0)
    [2021-03-22 18:32:09.702] [main] [trace] lifecycle (main): phase changed (value: 3)
    [2021-03-22 18:32:09.711] [main] [info] update#setState idle
    [2021-03-22 18:32:09.711] [main] [trace] resolveShellEnv(): skipped (VSCODE_CLI is set)
    [2021-03-22 18:32:11.081] [main] [trace] resolveShellEnv(): skipped (VSCODE_CLI is set)
    [2021-03-22 18:32:15.718] [main] [trace] SharedProcess: on vscode:createSharedProcessMessageChannel
    [2021-03-22 18:32:15.718] [main] [trace] resolveShellEnv(): skipped (VSCODE_CLI is set)
    [2021-03-22 18:32:16.391] [main] [trace] resolveShellEnv(): skipped (VSCODE_CLI is set)
    [2021-03-22 18:32:16.827] [main] [trace] SharedProcess: IPC ready
    [2021-03-22 18:32:16.927] [main] [trace] Main->SharedProcess#connect: connection established
    [2021-03-22 18:32:17.012] [main] [trace] SharedProcess: Overall ready
    [2021-03-22 18:32:18.824] [main] [trace] RequestService#request https://update.code.visualstudio.com/api/update/darwin/insider/469e4f6e2755b220dae3eccb04d1ddc587b84a5a
    [2021-03-22 18:32:24.614] [main] [trace] menubarService#updateMenubar 1
    [2021-03-22 18:32:33.384] [main] [trace] menubarService#updateMenubar 1
    [2021-03-22 18:32:39.715] [main] [trace] update#checkForUpdates, state =  idle
    [2021-03-22 18:32:39.715] [main] [info] update#setState checking for updates
    [2021-03-22 18:32:39.879] [main] [info] update#setState idle
    [2021-03-22 18:32:48.102] [main] [trace] menubarService#updateMenubar 1
    [2021-03-22 18:32:52.556] [main] [trace] menubarService#updateMenubar 1
    [2021-03-22 18:32:52.764] [main] [trace] menubarService#updateMenubar 1
    [2021-03-22 18:32:54.988] [main] [trace] Lifecycle#unload() - window ID 1
    [2021-03-22 18:32:54.994] [main] [trace] Lifecycle#unload() - no veto (window ID 1)
    [2021-03-22 18:32:55.011] [main] [trace] StorageMainService: closed workspace storage (f16c200b376bcb992eaf97090f54faf8)
    [2021-03-22 18:32:55.032] [main] [trace] StorageMainService: creating workspace storage (f16c200b376bcb992eaf97090f54faf8)
    [2021-03-22 18:32:55.256] [main] [trace] resolveShellEnv(): skipped (VSCODE_CLI is set)
    [2021-03-22 18:32:56.453] [main] [trace] SharedProcess: on vscode:createSharedProcessMessageChannel
    [2021-03-22 18:32:56.486] [main] [trace] menubarService#updateMenubar 1
    [...]
    ```
    </spoiler>

**Comment by chrmarti** [comment]
Try using `/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron -n "$1"`. The `code` executable sets the `VSCODE_CLI` environment variable which makes it skip reading the shell environment (it assumes that happened in a shell running as a parent process which is not the case here).

**Comment by gr4nt3d** [comment]
Trying to call it via the terminal like that works and yields:

<details>
    <summary> Log (Main) </summary>

```sh
[2021-03-23 22:38:57.323] [main] [debug] Starting VS Code
[2021-03-23 22:38:57.323] [main] [debug] from: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app
[...]
[2021-03-23 22:38:57.491] [main] [trace] resolveShellEnv(): running (macOS/Linux)
[2021-03-23 22:38:57.495] [main] [trace] getUnixShellEnvironment#runAsNode undefined
[2021-03-23 22:38:57.496] [main] [trace] getUnixShellEnvironment#noAttach undefined
[2021-03-23 22:38:57.499] [main] [trace] getUnixShellEnvironment#env {"SHELL":"/bin/zsh","XPC_FLAGS":"0x0","TERM_PROGRAM_VERSION":"433","HISTSIZE":"1000000","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.cLxZpmsa6V/Listeners","TERM_SESSION_ID":"07AFEF8A-8C21-4752-B1EF-EB0811DDB808","PWD":"/Users/user_name/Desktop","LOGNAME":"user_name","HOME":"/Users/user_name","LANG":"de_DE.UTF-8","TMPDIR":"/var/folders/hd/jtlkxw110cl8rvqcdz_b2y3h0000gn/T/","TERM":"xterm-256color","USER":"user_name","SHLVL":"1","XPC_SERVICE_NAME":"0","PATH":"/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin","HISTFILESIZE":"1000000","TERM_PROGRAM":"Apple_Terminal","_":"/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron","__CF_USER_TEXT_ENCODING":"0x1F5:0:0","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","VSCODE_CWD":"/Users/user_name/Desktop","VSCODE_NLS_CONFIG":"{\"locale\":\"de\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_NODE_CACHED_DATA_DIR":"/Users/user_name/Library/Application Support/Code - Insiders/CachedData/a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e","VSCODE_IPC_HOOK":"/Users/user_name/Library/Application Support/Code - Insiders/1.55.0-insider-main.sock","VSCODE_PID":"99235","ELECTRON_RUN_AS_NODE":"1","ELECTRON_NO_ATTACH_CONSOLE":"1"}
[2021-03-23 22:38:57.499] [main] [trace] getUnixShellEnvironment#spawn '/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron' -p '"1410f59f48c6" + JSON.stringify(process.env) + "1410f59f48c6"'
[2021-03-23 22:38:57.501] [main] [trace] getUnixShellEnvironment#shell /bin/zsh
[2021-03-23 22:38:57.795] [main] [trace] getUnixShellEnvironment#raw 1410f59f48c6{"SHELL":"/bin/zsh","XPC_FLAGS":"0x0","TERM_PROGRAM_VERSION":"433","HISTSIZE":"2000","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.cLxZpmsa6V/Listeners","TERM_SESSION_ID":"07AFEF8A-8C21-4752-B1EF-EB0811DDB808","PWD":"/Users/user_name/Desktop","LOGNAME":"user_name","HOME":"/Users/user_name","LANG":"de_DE.UTF-8","TMPDIR":"/var/folders/hd/jtlkxw110cl8rvqcdz_b2y3h0000gn/T/","TERM":"xterm-256color","USER":"user_name","SHLVL":"1","XPC_SERVICE_NAME":"0","PATH":"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin","HISTFILESIZE":"1000000","TERM_PROGRAM":"Apple_Terminal","__CF_USER_TEXT_ENCODING":"0x1F5:0:0","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","VSCODE_CWD":"/Users/user_name/Desktop","VSCODE_NLS_CONFIG":"{\"locale\":\"de\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_NODE_CACHED_DATA_DIR":"/Users/user_name/Library/Application Support/Code - Insiders/CachedData/a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e","VSCODE_IPC_HOOK":"/Users/user_name/Library/Application Support/Code - Insiders/1.55.0-insider-main.sock","VSCODE_PID":"99235","ELECTRON_RUN_AS_NODE":"1","ELECTRON_NO_ATTACH_CONSOLE":"1","OLDPWD":"/Users/user_name/Desktop","_":"/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron"}1410f59f48c6

[2021-03-23 22:38:57.796] [main] [trace] getUnixShellEnvironment#result {"SHELL":"/bin/zsh","XPC_FLAGS":"0x0","TERM_PROGRAM_VERSION":"433","HISTSIZE":"2000","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.cLxZpmsa6V/Listeners","TERM_SESSION_ID":"07AFEF8A-8C21-4752-B1EF-EB0811DDB808","PWD":"/Users/user_name/Desktop","LOGNAME":"user_name","HOME":"/Users/user_name","LANG":"de_DE.UTF-8","TMPDIR":"/var/folders/hd/jtlkxw110cl8rvqcdz_b2y3h0000gn/T/","TERM":"xterm-256color","USER":"user_name","SHLVL":"1","XPC_SERVICE_NAME":"0","PATH":"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin","HISTFILESIZE":"1000000","TERM_PROGRAM":"Apple_Terminal","__CF_USER_TEXT_ENCODING":"0x1F5:0:0","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","VSCODE_CWD":"/Users/user_name/Desktop","VSCODE_NLS_CONFIG":"{\"locale\":\"de\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_NODE_CACHED_DATA_DIR":"/Users/user_name/Library/Application Support/Code - Insiders/CachedData/a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e","VSCODE_IPC_HOOK":"/Users/user_name/Library/Application Support/Code - Insiders/1.55.0-insider-main.sock","VSCODE_PID":"99235","OLDPWD":"/Users/user_name/Desktop","_":"/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron"}
[2021-03-23 22:38:57.924] [main] [trace] resolveShellEnv(): running (macOS/Linux)
[2021-03-23 22:38:58.563] [main] [trace] SharedProcess: on vscode:createSharedProcessMessageChannel
[2021-03-23 22:38:58.563] [main] [trace] resolveShellEnv(): running (macOS/Linux)
[...]
```
</details>

With the following automator-script though, it does not.

```sh
#!/usr/local/bin/bash
/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron -n "$1"
```

Yields the same error and this is the log:

<details>
    <summary> Log (Main) </summary>
    
```sh
[2021-03-23 23:07:51.637] [main] [debug] Starting VS Code
[2021-03-23 23:07:51.637] [main] [debug] from: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app
[...]
[2021-03-23 23:07:51.813] [main] [trace] resolveShellEnv(): running (macOS/Linux)
[2021-03-23 23:07:51.813] [main] [trace] getUnixShellEnvironment#runAsNode undefined
[2021-03-23 23:07:51.813] [main] [trace] getUnixShellEnvironment#noAttach undefined
[2021-03-23 23:07:51.814] [main] [trace] getUnixShellEnvironment#env {"SHELL":"/bin/zsh","TMPDIR":"/var/folders/hd/jtlkxw110cl8rvqcdz_b2y3h0000gn/T/","USER":"user_name","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.cLxZpmsa6V/Listeners","__CF_USER_TEXT_ENCODING":"0x1F5:0:0","PATH":"/usr/bin:/bin:/usr/sbin:/sbin","LaunchInstanceID":"D71007F7-30F9-454F-854C-C4AC390EEF1A","PWD":"/Users/user_name","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"com.apple.automator.xpc.runner","SHLVL":"1","HOME":"/Users/user_name","LOGNAME":"user_name","_":"/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","VSCODE_CWD":"/Users/user_name","VSCODE_NLS_CONFIG":"{\"locale\":\"de\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_NODE_CACHED_DATA_DIR":"/Users/user_name/Library/Application Support/Code - Insiders/CachedData/a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e","VSCODE_IPC_HOOK":"/Users/user_name/Library/Application Support/Code - Insiders/1.55.0-insider-main.sock","VSCODE_PID":"99721","ELECTRON_RUN_AS_NODE":"1","ELECTRON_NO_ATTACH_CONSOLE":"1"}
[2021-03-23 23:07:51.814] [main] [trace] getUnixShellEnvironment#spawn '/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron' -p '"da73e620de16" + JSON.stringify(process.env) + "da73e620de16"'
[2021-03-23 23:07:51.815] [main] [trace] getUnixShellEnvironment#shell /bin/zsh
[2021-03-23 23:07:52.116] [main] [trace] getUnixShellEnvironment#raw da73e620de16{"SHELL":"/bin/zsh","TMPDIR":"/var/folders/hd/jtlkxw110cl8rvqcdz_b2y3h0000gn/T/","USER":"user_name","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.cLxZpmsa6V/Listeners","__CF_USER_TEXT_ENCODING":"0x1F5:0:0","PATH":"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin","LaunchInstanceID":"D71007F7-30F9-454F-854C-C4AC390EEF1A","PWD":"/Users/user_name","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"com.apple.automator.xpc.runner","SHLVL":"1","HOME":"/Users/user_name","LOGNAME":"user_name","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","VSCODE_CWD":"/Users/user_name","VSCODE_NLS_CONFIG":"{\"locale\":\"de\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_NODE_CACHED_DATA_DIR":"/Users/user_name/Library/Application Support/Code - Insiders/CachedData/a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e","VSCODE_IPC_HOOK":"/Users/user_name/Library/Application Support/Code - Insiders/1.55.0-insider-main.sock","VSCODE_PID":"99721","ELECTRON_RUN_AS_NODE":"1","ELECTRON_NO_ATTACH_CONSOLE":"1","OLDPWD":"/Users/user_name","_":"/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron"}da73e620de16

[2021-03-23 23:07:52.116] [main] [trace] getUnixShellEnvironment#result {"SHELL":"/bin/zsh","TMPDIR":"/var/folders/hd/jtlkxw110cl8rvqcdz_b2y3h0000gn/T/","USER":"user_name","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.cLxZpmsa6V/Listeners","__CF_USER_TEXT_ENCODING":"0x1F5:0:0","PATH":"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin","LaunchInstanceID":"D71007F7-30F9-454F-854C-C4AC390EEF1A","PWD":"/Users/user_name","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"com.apple.automator.xpc.runner","SHLVL":"1","HOME":"/Users/user_name","LOGNAME":"user_name","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","VSCODE_CWD":"/Users/user_name","VSCODE_NLS_CONFIG":"{\"locale\":\"de\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_NODE_CACHED_DATA_DIR":"/Users/user_name/Library/Application Support/Code - Insiders/CachedData/a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e","VSCODE_IPC_HOOK":"/Users/user_name/Library/Application Support/Code - Insiders/1.55.0-insider-main.sock","VSCODE_PID":"99721","OLDPWD":"/Users/user_name","_":"/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron"}
[2021-03-23 23:07:52.276] [main] [trace] resolveShellEnv(): running (macOS/Linux)
[2021-03-23 23:07:52.294] [main] [trace] resolveShellEnv(): running (macOS/Linux)
[2021-03-23 23:07:52.837] [main] [trace] StorageMainService: creating workspace storage (1616537185064)
[2021-03-23 23:07:53.204] [main] [trace] menubarService#updateMenubar 2
[2021-03-23 23:07:53.262] [main] [trace] SharedProcess: on vscode:createSharedProcessMessageChannel
[2021-03-23 23:07:53.262] [main] [trace] resolveShellEnv(): running (macOS/Linux)
[...]
```
</details>

(let me know if I cut too much - or too few)

**Comment by chrmarti** [comment]
`/usr/local/bin` is part of the PATH in both logs, not sure why that does not work. Could you post the log with the error again? (`F1` > `Remote-Containers: Show Log`)

**Comment by gr4nt3d** [comment]
I actually can not reproduce that error anymore. Everything works fine now.
(Except that I had to add `[...] Electron -n "$1" > /dev/null 2>&1 &` in order to finish the automation after starting vscode)
I guess no need to post the log right? If it was useful though, I don't know how to halt the window reloading in order to grab that log.
... with vscode-insiders at least.

With non-insider vscode:

<details>
<summary> ... <code>Remote-Containers: Show Log </code></summary>

```
[240 ms] Remote-Containers 0.163.0 in VS Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8).
[20669 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[20676 ms] spawn docker ENOENT
```
</details>

In non-insider vscode: I had a problem for two attempts, then afterward, for some reason, everything worked fine as well. No idea ... can't be the moon phase, though.

**Comment by chrmarti** [comment]
There is a timeout (of 10s? @bpasero) after which the workbench will continue loading without waiting for the shell environment to load. If your machine was under load, you might have seen that.

**Comment by bpasero** [comment]
This 10s timeout would go away once https://github.com/microsoft/vscode/issues/108804 is addressed.

**Comment by gr4nt3d** [comment]
> There is a timeout (of 10s? @bpasero) after which the workbench will continue loading without waiting for the shell environment to load. If your machine was under load, you might have seen that.

I don't have any delay. I am nowhere near fast enough such that I could copy the log before the window reloads. The only other remote log that I can grab is the one if docker isn't running and the window does not reload.
<details>
<summary><code>Remote-Containers: Show Log</code> </summary>

```
[534 ms] Remote-Containers 0.165.1 in VS Code 1.55.0-insider (d06d2f1d6245ce00b1c36a9cd81a9087d225173e).
[1384 ms] Start: Run: git rev-parse --abbrev-ref --symbolic-full-name @{u}
[8418 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[8578 ms] 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[8599 ms] Start: Run: docker-compose --version
[9852 ms] Start: Run: docker-compose version --short
[10457 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=test_folder_devcontainer --filter label=com.docker.compose.service=ubuntu-in-docker
```
</details>

**Comment by chrmarti** [comment]
Sounds good, let us know if there are any remaining issues. Thanks.

**Comment by gr4nt3d** [comment]
The error still appears mostly in unreproducible situations.
My guess: it does not seem to happen if the application is freshly started with the context menu entry, but it does pop up if the vscode app was running before.

[ vscode not running --> context - `vscode -n` --> remote works --> close window but keep it running --> context `vscode -n` --> remote fails ]

**Comment by chrmarti** [comment]
Reopening for investigation.
