### ISSUE TITLE
Weid characters instead of colors and space when terminal use "Git for Windows"

### ISSUE THREAD

**Issue by gremo** [microsoft/vscode#121093]
- VS Code Version:  1.55.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Use Git for Windows as terminal:

```json5
{
  // ..
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  // ..
}
```

2. Launch any command like `symfony local:php:list` ([CLI app](https://symfony.com/download))
3. Weird characters are show:

![VS Code](https://user-images.githubusercontent.com/1532616/114400566-636c9600-9ba2-11eb-86ce-c7b7e579a5ee.PNG)

4. Opening git bash alone (that is, right-click "Git Bash here""), it works correctly:

![Git for Windows](https://user-images.githubusercontent.com/1532616/114400358-2a342600-9ba2-11eb-8b29-df65dd12650b.PNG)

**Is this something bad with my configuration or isn't supposed to work inside VS Code?**

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
That's because it tries to output control sequences that are compatible with CMD and not with Bash.
Do you see same problem if you launch Git Bash separately and run that command there (not in integrated terminal)?

**Comment by gremo** [comment]
@IllusionMH thanks for the quick reply. As you can see, **point 4**, that is a screenshot of Git Bash running in its own window (right click - "Git Bash Here"). It works OK separately.

**Comment by IllusionMH** [comment]
Yeah, sorry. "In a regular prompt," and with different characters to display table thought that it was about command prompt, but obviously missed first line that is from Git Bash.

**Comment by gremo** [comment]
Ops.. sorry, I'll going to change it 😄

**Comment by meganrogge** [comment]
Does turning off `gpuAcceleration` resolve the problem?

**Comment by IllusionMH** [comment]
@meganrogge it's not related to GPU in any way and still reproducible if set to `off`.

Looks like there is some difference in how `git-bash.exe` and VS Code use `bash.exe`.
In integrated terminal (also on old build Windows Terminal) use what looks like CMD specific escapes.

**Comment by IllusionMH** [comment]
Easy way to reproduce it - use VS Code repo.
Set
```json
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
"terminal.integrated.shellArgs.windows": ["--login", "-i"],
```
open `vscode` and in integrated terminal (which should now be bash) run `./scripts/test.bat` (`.sh` won't work on Windows)

Then open same folder in Windows Explorer and use "Git Bash here" in `vscode` folder and again use `./scripts/test.bat`

![image](https://user-images.githubusercontent.com/1312662/114750711-f2bda900-9d5c-11eb-9279-dba7c9e1e7dc.png)

**Comment by gremo** [comment]
Anyone knows how to completly clear the terminal cache in VS code?

Because I suspect it's something related to my `.minttyrc` (maybe fonts or theme). I removed that file and my "Git bash here" it's now back to defaults. However, VS code still show my old font and colors. I also removed the `Code` folder but still, it remembers the old settings:

![Cattura](https://user-images.githubusercontent.com/1532616/114889571-839e8e00-9e0a-11eb-8c71-de57075def24.PNG)

**Comment by gremo** [comment]
Any update? If you need more info please ask! 👍🏻

**Comment by Tyriar** [comment]
Does this happen when you run in Windows Terminal? My suspicion is it's related to conpty's pty emulation conflicting with mingw.

**Comment by gremo** [comment]
@Tyriar do you mean if I change the default shell in VS Code? In this case, no, it works fine for example using Power Shell.

**Comment by Tyriar** [comment]
@gremo we share the backend with Windows Terminal which you can get here https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701

**Comment by gremo** [comment]
Yes @Tyriar , I've just installed and tested it:

![wt](https://user-images.githubusercontent.com/1532616/116250501-11b13780-a76e-11eb-85ec-e24ef994f3e0.PNG)

My settings:

![wt_settings](https://user-images.githubusercontent.com/1532616/116250526-1675eb80-a76e-11eb-811c-5991ee208776.PNG)

**Comment by Tyriar** [comment]
In that case it's an issue with conpty which the terminal team builds. Check for an issue on https://github.com/microsoft/terminal and create if you can't find. Chances are it is already being tracked.

**Comment by IllusionMH** [comment]
@Tyriar is it still issue in terminal repo if changing `TERM` variable fixes this kind of escapes in some cases?

Fixed for gradle output but still issue in VS Code repo.

**Comment by IllusionMH** [comment]
Setting `export TERM=cygwin` helped with really broken output from Gradle 4, but not with output `./scripts/test.bat`
![image](https://user-images.githubusercontent.com/1312662/116261885-bf2d4680-a780-11eb-8793-6546fc9a6e87.png)

Strange that using Git Bash Here will have correct output form Gradle 4, but has different `TERM` value
```
$ echo $TERM
xterm
```

**Comment by Tyriar** [comment]
With profiles we can now support attaching environment variables, I think `$TERM` we explicitly ignore and replace with our own value but I can make a change to prevent that if it's configured in `env`. I'm thinking next iteration we can change the detected Git Bash profile to be and see if that helps:

```
"terminal.integrated.profiles.windows": {
  "Git Bash": {
    "source": "Git Bash",
    "env": {
      "TERM": "cygwin"
    }
  }
}
```

**Comment by Tyriar** [comment]
Since we set the right value here for our terminal (xterm-256color) and WT does the same, plus the fact that changing it doesn't fix everything, I think we'll leave this as is
