### ISSUE TITLE
Vscode crashes every time after it mistakenly analyses grammar.

### ISSUE THREAD

**Issue by BirdLeeSCUT** [Microsoft/vscode#12241]
- VSCode Version: 1.5.2
- OS Version: Windows 10 x64

Steps to Reproduce:
1. When I write js or jsx code, vsCode will mistakenly analyses grammar some time, then it underlines the "mistaken" code which is no mistake in fact. And after not long, vsCode would crash.
2. This kind of  case happens so many times recently. Especially when I`m writing js, jsx & json code. I use eslint in my project, dose it make influence for this case ?

Following is one piece of code that attend to make this bug occurs:
(mistakenly analyses grammar is `"name": "zyin"`)
![image](https://cloud.githubusercontent.com/assets/10753131/18623557/6468732e-7e71-11e6-9772-b9e977c6335c.png)

```
{
  "name": "zyin",
  "version": "0.0.1",
  "main": "localhost:8005/webpack-dev-server/index.html",
  "node-remote": "http://localhost:8005/*",
  "description": "zyin atm v2",
  "nodejs": true,
  "scripts": {
    "start": "node server.js --env=dev"
  },
  "window": {
    "icon": "zyin-icon.png",
    "title": "zyin-atm-2",
    "width": 1200,
    "height": 720,
    "min_width": 1200,
    "min_height": 720,
    "show_in_taskbar": true,
    "kiosk": false
  },
  "webkit": {
    "page-cache": false
  },
  "devDependencies": {

  },
  "dependencies": {

  }
}
```

**Comment by bpasero** [comment]
Assuming this is an issue with the TS/JS grammar moving to @waderyan . fyi @alexandrudima though

**Comment by BirdLeeSCUT** [comment]
@bpasero Thanks. It seems like it. When this issue occur, my cup utilization increase obviously, sometime approximately 100%

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. On Windows a tool like **Process Explorer** or **Process Hacker** helps.

Once you have the information please update this issue with it. Thanks!

**Comment by BirdLeeSCUT** [comment]
![image](https://cloud.githubusercontent.com/assets/10753131/18626364/36200bc4-7e87-11e6-9283-067de5c25030.png)
I find a process that occupies the 20%+ of CPU all the time. What should I do next ?

**Comment by bpasero** [comment]
@BirdLeeSCUT thanks I think this is good enough, it is the renderer process for the window.

**Comment by kumarharsh** [comment]
I've also noticed eslint being triggered for JSON files (like this package.json), and showing random errors (like in the screenshot above, it has underlined name, seemingly for no reason (unless it's thinking this is a JS file). 
This is the error it gives when it underlines `"name"` in the package.json file.
```
[eslint] Parsing error: Unexpected token
___________________________________________
The name of the package.
```

Also, this happens only intermittently, and the eslint server doesn't turn on sometimes when I open the package.json file.

This is my full eslint config:
```js
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "mocha": true,
    "node": true
  },
  "rules": {
    "no-const-assign": 2,
    "react/no-multi-comp": 0,
    "react/prop-types": 2,
    "react/jsx-no-bind": 2,
    "comma-dangle": [1, "always-multiline"],
    "new-cap": [2, {"capIsNewExceptions": ["Radium", "DragDropContext", "DropTarget", "DragSource"]}],
    "key-spacing": [1, {"mode": "minimum"}],
    "indent": [2, 2, {"SwitchCase": 1}],
    "no-else-return": 0,

    // allow funtions
    "no-use-before-define": [2, "nofunc"]
  },
  "plugins": [
    "react"
  ]
}
```

**Comment by alexandrudima** [comment]
@bpasero That is not the renderer process (notice the indent level being equal to CodeHelper.exe). I believe it is the extension host that somehow comes under incredible stress, most likely from the mentioned eslint

**Comment by alexandrudima** [comment]
fyi @dbaeumer

**Comment by bpasero** [comment]
@BirdLeeSCUT are you able to reproduce this consistently with one file that you could share maybe?

**Comment by joaomoreno** [comment]
@dbaeumer The first screenshot in here shows Microsoft/vscode-eslint#138

**Comment by BirdLeeSCUT** [comment]
@bpasero  I will try to catch a way to reproduce thisissue when it happen again, since this issue happen indeterminately

**Comment by dbaeumer** [comment]
@kumarharsh @alexandrudima the eslint bug got addressed in the latest eslint extension update. I am pretty sure that this is not caused by eslint. I mistakenly validated package.json files with eslint and all that happened was one error I reported. Can not make the extension host go grazy :-).

@BirdLeeSCUT can you reproduce this if you start code with --disable-extensions.

**Comment by alexandrudima** [comment]
@jrieken Freezing ... markers ... is this the same underlying issue you mentioned today?

**Comment by jrieken** [comment]
unsure - only if someone generate 10s of thousands of markers and uses the problems view

**Comment by alexandrudima** [comment]
Without extension host profiling, we're just guessing here ...

**Comment by hville** [comment]
For what it's worth, I have the impression the `package.json` "unexpected token" error is always triggered after I mess around with files in the project (copy/create/rename...). I then need to restart to make it go away.

**Comment by dbaeumer** [comment]
@hville which version of ESLint are you using. I fixed the problem in the eslint extension to not validate package.json files.

**Comment by hville** [comment]
@dbaeumer was using ESLint 3.6.0. Just updated to 3.6.1

**Comment by dbaeumer** [comment]
@hville I was meaning the VS Code eslint extension (https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

**Comment by hville** [comment]
@dbaeumer thanks. More details: EsLint extension 1.06 still faced some issue, apparently with loading data from `json.schemastore.org/package` (ETIMEDOUT) error. I'm guessing you are already aware since a new  1.07 version just appeared while typing this.

**Comment by dbaeumer** [comment]
@hville `json.schemastore.org/package`  (ETIMEDOUT error) is a problem of our JSON schema support and has nothing to do with the ESLint extension itself. Can you please open a separate issue with steps.

**Comment by dbaeumer** [comment]
ESLint analyzing JSON file has been fixed a long time ago. Since no additional information has been provided I will close the issue. Please ping if you still see the issue.
