### ISSUE TITLE
Extensions are becoming dissociated with themselves

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#12281]
- VSCode Version:  1.6.0-Insiders and 1.5.2 Stable
- OS Version: Windows 10

I have been seeing some sort of issue for a while, but finally had time to take a better look into it. I have been seeing that some extensions I know are out of date, but they aren't registering as out of date when I check in Code. It shows the Extension is installed, but when I do a search for it, it does not think the extension is installed and gives me the option of installing it.

Below you can see where it shows the Extension **VSCode Great Icons** as being installed and offers the Uninstall option when looking under installed Extensions.

![greaticonsinstalled](https://cloud.githubusercontent.com/assets/6662208/18644646/ca99eab2-7e6f-11e6-9861-0e4156aa4bae.png)

However, if I do a search for the same extension, you can see if the screenshot below that it shows up as not being installed.

![greaticons](https://cloud.githubusercontent.com/assets/6662208/18644620/abbf1144-7e6f-11e6-97a2-7e877217436f.png)

I have 3 outdated Extensions, but these do not show up in Code as outdated. You can see in the above screenshot that we know that extension is installed and outdated.

![greaticonsoutdated](https://cloud.githubusercontent.com/assets/6662208/18644782/42ee5dd6-7e70-11e6-83a8-e8f62d243ce0.png)

I then started checking all of my extensions to see if others were not properly displaying in VSCode, but were up to date. In total, I have 40 Extensions installed, and here are my results from checking each one. On the right I show their folder fullname with version and on the left their display name and version in Code.

## Show as Installed: 20

* AdamCaviness.theme-monokai-dark-soda-0.0.5    - Monokai Dark Soda 0.0.5
* akamud.vscode-theme-onedark-0.2.6             - One Dark Theme 0.2.6
* anseki.vscode-color-0.1.11                    - Color Picker 0.1.11
* bbenoist.vagrant-0.4.0                        - Vagrant 0.4.0
* be5invis.vscode-icontheme-nomo-dark-1.1.1     - Nomo Dark Icon Theme 1.1.1
* codezombiech.gitignore-0.2.0                  - gitignore 0.2.0
* dbankier.vscode-instant-markdown-0.1.0        - Instant Markdown 0.1.0
* DotJoshJohnson.xml-1.6.0                      - XML Tools 1.6.0
* gerane.Theme-ant-0.0.3                        - ant Theme 0.0.3
* gerane.Theme-monokai-inverse                  - monokai-inverse Theme 0.0.2
* Kasik96.theme-monokaiclear-0.0.1              - Monokai Clear 0.0.1
* Pendrica.Chef-0.6.1                           - Chef Extension for VSCode 0.6.1
* PKief.material-icon-theme-1.0.3               - Material Icon Theme 1.0.3
* qinjia.seti-icons-0.0.9                       - seti-icons 0.0.9
* robertohuertasm.vscode-icons-2.0.5            - vscode-icons 2.0.5
* seanmcbreen.MDTools-1.0.0                     - MDTools 1.0.0
* tht13.python-0.2.3                            - Python for VSCode 0.2.3              -Remove
* TsumiNa.Seti-theme-0.0.1                      - Seti-Theme 0.0.1
* vip32bit.theme-monokai-black-0.1.0            - theme-monokai-black 0.1.0
* zhuangtongfa.Material-theme-1.0.3             - Material-theme 1.0.3

## Show as Missing: 20

* DavidAnson.vscode-markdownlint-0.5.0         - markdownlint 0.5.0
* donjayamanne.githistory-0.0.8                - Git History (git log) 0.0.11
* DougFinke.vscode-pandoc-0.0.8                - vscode-pandoc 0.0.8
* EditorConfig.EditorConfig-0.3.1              - EditorConfig for VS Code 0.3.1
* emilast.LogFileHighlighter-0.9.0             - Log File Highlighter 0.9.0
* emmanuelbeziat.vscode-great-icons-1.0.9      - VSCode Great Icons 1.1.6
* gerane.Theme-CarbonightBlue-0.0.2            - CarbonightBlue Theme 0.0.2
* gerane.Theme-FlatlandBlack-0.0.2             - Flatland_Black Theme 0.0.2
* gerane.Theme-FlatlandDark-0.0.2              - Flatland_Black Theme 0.0.2
* gerane.Theme-FlatlandMonokai-0.0.4           - Flatland Monokai Theme 0.0.4
* gerane.Theme-Zenburn-0.0.3                   - Zenburn Theme 0.0.3
* gerane.TodoTXT                               - TodoTXT 0.0.1
* MattiasPernhult.vscode-todo-0.8.0            - vscode-todo 0.8.0
* minhthai.vscode-todo-parser-1.8.1            - TODO Parser
* ms-vscode.csharp-1.4.1                       - C# 1.4.1
* ms-vscode.PowerShell-0.7.2                   - PowerShell 0.7.2
* ms-vscode.Theme-MarkdownKit-0.1.1            - Markdown Theme Kit 0.1.1
* ms-vscode.Theme-MaterialKit-0.1.1            - Material Theme Kit 0.1.1
* naumovs.color-highlight-1.2.1                - Color Highlight 1.2.1
* rebornix.Ruby-0.5.6                          - Ruby 0.6.0

## Outdated and Missing

Of the 20 Extensions showing as missing, these 3 are out of date.

* donjayamanne.githistory-0.0.8                - Git History (git log) 0.0.11
* emmanuelbeziat.vscode-great-icons-1.0.9      - VSCode Great Icons 1.1.6
* rebornix.Ruby-0.5.6                          - Ruby 0.6.0

My worry here is that if any of my other extensions get out of date, they too will have the same issue as the 3 above. Is there anything else I can do to try to debug this? The only Error I have been seeing in the Debug tools is the following:

```
"Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError"
```

The problem with that error is it doesn't happen all the time and sometimes seems to happen a little while after Code has been started up.

If I check my extensions in the Stable version of Code, I am seeing similar results.

**Comment by joaomoreno** [comment]
This is odd. Can you paste the `package.json` files in disk for one of those extensions. Let's say `donjayamanne.githistory-0.0.8`. You'll find it in `%USERPROFILE%\.vscode-insiders\extensions\donjayamanne.githistory-0.0.8\package.json`.

**Comment by gerane** [comment]
@joaomoreno I already had this one up in an editor. It is for the Great Icons package. I can get the others later if needed. About to head into a meeting.

```json
{
	"name": "vscode-great-icons",
	"displayName": "VSCode Great Icons",
	"description": "A big pack of icons (100+) for your files.",
	"version": "1.0.9",
	"publisher": "emmanuelbeziat",
	"engines": {
		"vscode": "^1.5.0"
	},
	"categories": [
		"Other",
		"Themes"
	],
	"contributes": {
		"iconThemes": [
			{
				"id": "vscode-great-icons",
				"label": "VSCode Great Icons",
				"path": "./icons.json"
			}
		]
	},
	"icon": "images/vscode-great-icons_icon.png",
	"galleryBanner": {
		"color": "#e0e0e0",
		"theme": "light"
	},
	"keywords": [
		"icons",
		"theme",
		"icon-theme",
		"customization"
	],
	"repository": {
		"type": "git",
		"url": "git+https://github.com/EmmanuelBeziat/vscode-great-icons.git"
	},
	"author": {
		"email": "contact@emmanuelbeziat.com",
		"name": "Emmanuel Béziat",
		"url": "https://www.emmanuelbeziat.com"
	},
	"license": "MIT",
	"bugs": {
		"url": "https://github.com/EmmanuelBeziat/vscode-great-icons/issues"
	},
	"homepage": "https://github.com/EmmanuelBeziat/vscode-great-icons#readme",
	"__metadata": {
		"id": "ab4f5b56-0493-4f70-a44b-773909fdbeb3",
		"publisherId": "c6e135ee-f6a2-45cb-b782-fd4de23acc84",
		"publisherDisplayName": "Emmanuel Béziat"
	}
}
```

**Comment by joaomoreno** [comment]
@gerane Can you please confirm the state of those extensions now? Are they exactly the same as they were?

**Comment by joaomoreno** [comment]
@gerane Nevermind.

@vishalkiri @modigrv @hamenon Did the Marketplace change extension IDs recently? We were using them as a way to know which extensions came from the Marketplace and otherwise.

For example, the extension @gerane just pasted shows that at installation time, it had the ID `ab4f5b56-0493-4f70-a44b-773909fdbeb3 `. Looking at it right now gives me the ID `829a192d-496c-44ac-87f3-0a84ce36a853`.

This **badly** breaks us.

**Comment by joaomoreno** [comment]
@gerane Could you zip up the whole extensions directory and send me somehow?

**Comment by roblourens** [comment]
@joaomoreno In my extensions folder, I have multiple versions of some extensions. I assume there should only be the latest. Is that from this? LMK if you want my extensions dir.

![image](https://cloud.githubusercontent.com/assets/323878/18925905/8e5455e0-856a-11e6-8616-5224eb84c2ee.png)

**Comment by joaomoreno** [comment]
@roblourens We've been rolling around with a bug that fails to remove the old extension versions, for which I pushed a fix today. Send me your extensions folder if you see the same dissociation behaviour as @gerane

**Comment by joaomoreno** [comment]
Moving to October since there hasn't been more info. Today is the last fix day.

**Comment by gerane** [comment]
@joaomoreno Sorry for the delay. I got tied up with some unexpected issues.

There is actually 2 separate issues here, one which is not an issue with Code. I have a PowerShell module that can install and update VSCode Extensions. The built in cli commands were not reliable enough and does not return any information. I found that I would often run a command and it just didn't do anything. I am replicating what Code is doing but just in powershell, but I was just unpacking the vsix and not adding the _metadata section. These extensions are not being registered as installed by the marketplace, though this wasn't always the case.

I picked the above package.json because it was one of a handful of the latest I had installed in the last few days. The reason I chose to include that one was because I knew it would not be impacted by my own updating. Prior to the addition of the Auto Updating Extensions setting I was using my own PowerShell Module to check for extension updates and update them when found. I just had this in my profile and it would keep my extensions up to date. When the Auto Update Extensions setting was added I stopped using this method. This has been at least a couple weeks now, so I knew these last extensions were not related to my own updating. I would not have opened the issue if I hadn't immediately seen the last extension I had installed a few days prior was also broken.

Since I have only installed a few extensions since I stopped updating them myself, the package.json I listed above is the only one that is not missing the _metadata section. So it being broken is due to the Extension Id changing for some reason and I have no idea why.

**Comment by gerane** [comment]
@joaomoreno I quickly just wrote a script to add the metadata back to the ones where it was missing. When I launched Code those extensions started working properly again.

I am still not quite sure how the 'VSCode Great Icons' extension got a different extension id though.

**Comment by joaomoreno** [comment]
Good to know, thanks!

An extension will get a different ID if its publisher unpublishes it at any point in time.
