### ISSUE TITLE
Right click in custom editors shows a context menu

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123301]
This is quite breaking for Luna Paint. Repro is to just right click in a custom editor:

<img width="306" alt="Screen Shot 2021-05-07 at 8 48 49 AM" src="https://user-images.githubusercontent.com/2193314/117475600-1b2a6480-af11-11eb-9484-65429d9b38fc.png">

**Comment by mjbvz** [comment]
This was intentionally added in #65310. I added these as enabled default to all webviews since we are unlikely to get much adoption if it's a new options

Does Luna Paint have it's own context menus or do you just want to make these ones never appear on right click? Can you try registering your own `contextmenu` event handler and cancel/stop the event before our built-in code see it?

**Comment by Tyriar** [comment]
I'm guessing I can prevent default, it's just this is a change that breaks right click everywhere in my extension all of a sudden and I'm probably not the only one. It's probably the right change.

Related to this, I'd like even more custom editors could eventually hook into the context menu service to show their own, right now I think we have to re-create our own context menu-looking thing.

**Comment by Tyriar** [comment]
@mjbvz looked into this a bit more, I don't think we should ship with it as is because it's not how browsers handle the default context menu. I already have this where `container` is the parent of the `canvas`:

```
this.register(addDisposableDomListener(container, 'contextmenu', e => e.preventDefault()))
```

This works in browsers but not the webview. `e.stopImmediatePropogation()` is required in order to prevent it in the current insiders webview which is wrong imo. I'm planning on doing a patch release for the extension but I'll hold off on making this change because I think we should fix this up in core.

**Comment by Tyriar** [comment]
But bring the context menu in is not all bad, this is a welcome change:

<img width="243" alt="Screen Shot 2021-05-08 at 3 27 49 AM" src="https://user-images.githubusercontent.com/2193314/117535965-5e3a1580-afad-11eb-9d4a-5ed11d6eeec4.png">

**Comment by mjbvz** [comment]
Still not sure if we can tell if an webview needs to use right click or not. I also don't know what the alternative way to implement this that would let normal `preventDefault` from working. Let me know if you have any suggestions on either front

If we can't come up with a better approach, I still think it may be acceptable to require code changes from the handful of extensions that use right click in interesting ways if it means we could enable context menus for all webviews

**Comment by Tyriar** [comment]
@mjbvz can you use [`defaultPrevented`](https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented)?

**Comment by mjbvz** [comment]
Good idea @Tyriar. I just pushed a fix that uses that property. Please let me know if it doesn't seem to work correctly

I expect this change will still cause issues for a few webview based extensions, but as I said I can't see any other way to add this feature without making it opt-in
