### ISSUE TITLE
Shell migration message not shown once per window reload

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#124854]
<img width="470" alt="Screen Shot 2021-05-28 at 11 40 58 AM" src="https://user-images.githubusercontent.com/2193314/120028559-adbaa280-bfa9-11eb-8f90-3cbbc972e09e.png">

This is my only shell/profile setting:

```
"terminal.integrated.defaultProfile.osx": "bash",
```

**Comment by Tyriar** [comment]
It should also show only once per window reload

**Comment by meganrogge** [comment]
Fixed already

**Comment by meganrogge** [comment]
Not sure how to get it to only show once per window reload. Custom implementation?

**Comment by Tyriar** [comment]
@meganrogge keep a boolean like `let messageShown = false` at the top level of the file to track it.

**Comment by Tyriar** [comment]
This still happens because `messageShown` needs to be at the top level, not a member of TerminalInstance in order to be shared.

**Comment by meganrogge** [comment]
If we only do this for the first terminal that gets created though, if users change their settings and then create terminals, they won't see this message.

**Comment by meganrogge** [comment]
Just tested it and think that's fine

**Comment by Tyriar** [comment]
@meganrogge that's fine, they'd eventually hit it again after a restart. The main thing is that we're annoying people as little as possible.

**Comment by Tyriar** [comment]
Tried to verify, think this is still unreleased.

**Comment by meganrogge** [comment]
I think it should be released already since Alex Dima released a few hours ago an insider's based on release/1.57, which has the changes.

**Comment by Tyriar** [comment]
Works after updating 👍
