### ISSUE TITLE
Debug console

### ISSUE THREAD

**Issue by ullaskunder3** [microsoft/vscode#126967]
Issue Type: <b>Bug</b>

Can any one explain why vs code debug console work like this:

when I use console.log for logging name form array using map, at first log it work. On second log its not showing

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (2.79GB free)|
|Process Argv|--crash-reporter-id b13aa7f5-b359-41cf-928a-e98c0833ffd2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
insert-unicode|bru|0.10.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.40.4
code-runner|for|0.11.4
js-debug-nightly|ms-|2021.5.617
material-icon-theme|PKi|4.7.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.14
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30324779
binariesv615cf:30323120

```

</details>

**Comment by ullaskunder3** [comment]
![debug console](https://user-images.githubusercontent.com/66258652/123060829-b24b6d00-d428-11eb-9fc5-c4e912a1edf4.png)

**Comment by isidorn** [comment]
This works for me, can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes, can you please share a sample short code that I can just copy and try to reproduce?
Thanks

**Comment by ullaskunder3** [comment]
```JavaScript
const characters = [
    {
        name: 'Luke Skywalker',
        height: '172',
        mass: '77',
        iris: 'blue', 
    },
    {
        name: 'Darth Vader',
        height: '202',
        mass: '136',
        iris: 'yellow'
    },
    {
        name: 'Leia Orange',
        height: '150',
        mass: '49',
        iris: 'green'
    },
    {
        name: 'Anakin Skywalker',
        height: '188',
        mass: '84',
        iris: 'blue', 
    },
];

/*******map********/

//get array of all names
const names = characters.map((character) => character.name);
console.log(names);

const heights = characters.map((character) => character.height);
console.log(heights);

// get array of object just with name and height 
const minifiedData = characters.map(character => ({name: character.name, height: character.height}))
console.log(minifiedData);

// get fist name
const firstName = characters.map(character => character.name.split(' ')[0])
console.log(firstName);
```
If I use `javascript debug terminal` or `nodemon` it work (logs) fine as expected but if I debug using Vscode `Debug Console`  it's only log first console.log

> This works for me, can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
> If yes, can you please share a sample short code that I can just copy and try to reproduce?
> Thanks

**Comment by ullaskunder3** [comment]
> This works for me, can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
> If yes, can you please share a sample short code that I can just copy and try to reproduce?
> Thanks

And one more what difference between normal Vs Code and Vs Code Insider

**Comment by isidorn** [comment]
Thanks for the repro steps. I can reproduce this.
The issue seems to be how we are handling events here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugSession.ts#L908

We should fix this, but I will not have time this milestone, thus adding help wanted, and if no nobody from the community helps I can look into it next milestone.

**Comment by erha19** [comment]
Hi ~ I create a PR to fixes this issue, maybe u can have a look @isidorn

**Comment by connor4312** [comment]
This duplicates https://github.com/microsoft/vscode-js-debug/issues/161 and has the potential to be fixed by https://github.com/microsoft/debug-adapter-protocol/issues/85. The PR makes a race slightly _less_ likely but doesn't fix the issue, which can still be hit with slow enough processing or large enough output.
