### ISSUE TITLE
Changing language mode to "Markdown" results in "No renderer found for text/plain"

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#128873]
I have just one keybinding for creating a new code cell, so to create markdown cells I'd like to create a code cell then switch it's mode to markdown, but doing so results in:
![image](https://user-images.githubusercontent.com/8586769/126002736-8d0cbddb-0e3e-42c2-bf39-82ff5abc1cd7.png)

Repo: https://github.com/JacksonKearl/vscode-sonic-pi/

**Comment by sbland** [comment]
I have the same issue. I also get this message if I create a markdown cell before the kernal has been attached. Creating a markdown cell with the hotkeys or +markdown button works fine.

**Comment by rebornix** [comment]
I think this one was already fixed by @mjbvz

**Comment by JacksonKearl** [comment]
Still present. Can try in github issue notebook.

**Comment by rebornix** [comment]
@mjbvz can you help take a look?

**Comment by claudiaregio** [comment]
I am also still reproducing this in the latest version of insiders

**Comment by JacksonKearl** [comment]
Thank you @mjbvz !!

**Comment by alexr00** [comment]
\closedWith 6a0ea074f9f25f15e7a60181d6882945899b5356
