### ISSUE TITLE
Can't open settings.json through SCM view

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#129083]
- Set `"workbench.settings.useSplitJSON": true`
- Change .vscode/settings.json
- Click settings.json in the SCM view
- It doesn't open and my `IEditorResolverService` factory is never called

Is there something else I'm supposed to be doing here @lramos15?

**Comment by lramos15** [comment]
This is a part of #128756 which was some work to prevent other bugs but seems to have regressed a few things.

**Comment by roblourens** [comment]
That issue is fixed now but mine still reproes

**Comment by lramos15** [comment]
Ah sorry, I just assumed it was the same bug that was my bad. I just investigated it and the issue is that you don't register a diff editor factory and opening a file through SCM view expects a diff to be created. I don't know what a split json diff should look like so I would say the behavior right now is ok.

**Comment by roblourens** [comment]
There should be a diff view when you click on changes in SCM. How do I get it to open the normal file diff view like it would without my editor factory involved? Do I have to create an editor input manually for this? I don't want to customize the SCM behavior.

**Comment by roblourens** [comment]
Ah that's pretty simple, thanks!

**Comment by lramos15** [comment]
> Ah that's pretty simple, thanks!

Yeah I think I'm going to push an additional fix so that if it's undefined we assume false as it shouldn't have just broke because you forgot to set an optional setting.
