### ISSUE TITLE
ReferenceError: atob is not defined when rendering images in a jupyter notebook when connected to a remote host

### ISSUE THREAD

**Issue by ghylander** [microsoft/vscode#129393]
Issue Type: <b>Bug</b>

instead of images an error stack is shown, this has been a recent change as last week it worked without issue

VS Code version: Code - Insiders 1.59.0-insider (955a1aca9a2e4473eec4f4bdc70506a3a7c43ca7, 2021-07-26T05:13:58.801Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1051-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.70GB (1.77GB free)|
|Process Argv|--crash-reporter-id 4285aea8-8024-49ba-97f2-9d60622a70f0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: AWS|
|OS|Linux x64 5.4.0-1051-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (8 x 3190)|
|Memory (System)|30.91GB (27.93GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.189.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1066828098

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490

```

</details>

**Comment by rebornix** [comment]
Since we use `atob` in the ipynb serialzier as well, not sure if it's a Jupyter extension issue or the core.

**Comment by DonJayamanne** [comment]
This has been fixed here https://github.com/microsoft/vscode/pull/129282

**Comment by grudloff** [comment]
I am experiencing the same issue on a local server. For me, this happens only with previously run notebooks, if I re-run the notebooks the figures are rendered as usual.

**Comment by DonJayamanne** [comment]
The fix was merged today, please wait for the latest insider build tomorrow.
If the problem still persists, please do let us know & we'll be happy to re-open  this issue, or please feel free to create a new issue.

**Comment by grudloff** [comment]
It is working fine now, thanks!

**Comment by rchiodo** [comment]
I'm still seeing this.

This notebook will repro it:
[plotting.zip](https://github.com/microsoft/vscode/files/6888867/plotting.zip)

**Comment by DonJayamanne** [comment]
@rchiodo Please could you re-run the notebook & test it out, or try with another notebook.
Looking at the notebook, the errors have been saved in the output, hence its not a real error.

![Screen Shot 2021-07-27 at 14 37 49](https://user-images.githubusercontent.com/1948812/127230997-56287491-7e78-444c-8d56-8f91e9c24b0a.png)
![Screen Shot 2021-07-27 at 14 38 29](https://user-images.githubusercontent.com/1948812/127231002-92529352-38dc-41d7-90d2-209d9998825f.png)

**Comment by rchiodo** [comment]
Oh sorry. I should have checked that. Yes rerunning fixes things.
