### ISSUE TITLE
Cannot add `code` to PATH, permission denied

### ISSUE THREAD

**Issue by lukebelliveau** [microsoft/vscode#129884]
Issue Type: <b>Bug</b>

Opening the command palette and trying to add the `code` command to `PATH` results in the following error:

`EACCES: permission denied, unlink '/usr/local/bin/code'`

<img width="264" alt="Screen Shot 2021-07-31 at 8 16 31 AM" src="https://user-images.githubusercontent.com/6233086/127730785-7b596de2-4982-40c2-a2a8-d9237e715013.png">

This is from a fresh install.

VS Code version: Code 1.58.2 (Universal) (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin arm64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by lukebelliveau** [comment]
Note that I got it into my PATH by following the workaround [here](https://stackoverflow.com/a/33831403).

**Comment by nsipplswezey** [comment]
I also just ran into this issue, fresh install m1 macbook air.

**Comment by Lazy-poet** [comment]
Same issue here as well. M1 MacBook Air

**Comment by mrzacsmith** [comment]
Same issue M1 Macbook Air, the above work around did not work. Fresh install, like 3 hours ago.

**Comment by Lazy-poet** [comment]
I found a fix. I simply uninstalled the code command from PATH in vscode and reinstalled. i.e open the command pallete, search "uninstall 'code'" and select the first option to uninstall. Do same for installing too. That should fix it

**Comment by ejok** [comment]
I ran into this as well but I managed to get `code` command to work yesterday but it wasn't working any more today. My problem was that the `code` was referring to an instance in a temporary folder. So I just removed `/usr/local/bin/code` and then added it again from VSCode (after making sure that I launched VSCode from the `Applications`). 

So essentially this: https://apple.stackexchange.com/a/294178

**Comment by haozhao-li** [comment]
> I found a fix. I simply uninstalled the code command from PATH in vscode and reinstalled. i.e open the command pallete, search "uninstall 'code'" and select the first option to uninstall. Do same for installing too. That should fix it

this answer should be pinned to the top, thank you.

**Comment by gururaj3** [comment]
I am also facing the same issue with Mac M1. However, I was able to make it work as suggested by @Lazy-poet . Thank you for the help.

**Comment by JamesOkunlade** [comment]
Apparently, M1 isn't short of issues. I haven't been able to get a docker project that uses elasticsearch set up on a new M1 machine. The above solution to fix code PATH worked for me and I just thought maybe I could ask about the docker issue here perhaps some might have faced and solved it.

**Comment by luizfverissimo** [comment]
> I found a fix. I simply uninstalled the code command from PATH in vscode and reinstalled. i.e open the command pallete, search "uninstall 'code'" and select the first option to uninstall. Do same for installing too. That should fix it

This work for me too! Thank you!

**Comment by MANZILMEHTA** [comment]
> I found a fix. I simply uninstalled the code command from PATH in vscode and reinstalled. i.e open the command pallete, search "uninstall 'code'" and select the first option to uninstall. Do same for installing too. That should fix it

This worked for me as well..Thank You..

**Comment by ayunas** [comment]
> I found a fix. I simply uninstalled the code command from PATH in vscode and reinstalled. i.e open the command pallete, search "uninstall 'code'" and select the first option to uninstall. Do same for installing too. That should fix it

This indeed was the fix for my MacBook-air-M1 running OS X 11.4.  Thank you @Lazy-poet

**Comment by SkySoShy** [comment]
> I found a fix. I simply uninstalled the code command from PATH in vscode and reinstalled. i.e open the command pallete, search "uninstall 'code'" and select the first option to uninstall. Do same for installing too. That should fix it

This worked for me as well..Thank You..

**Comment by GriffinHarris51** [comment]
> I found a fix. I simply uninstalled the code command from PATH in vscode and reinstalled. i.e open the command pallete, search "uninstall 'code'" and select the first option to uninstall. Do same for installing too. That should fix it

Also, make sure you move VS Code out of downloads and into applications. After that this suggestion worked great!

**Comment by Aheesh** [comment]
> I found a fix. I simply uninstalled the code command from PATH in vscode and reinstalled. i.e open the command pallete, search "uninstall 'code'" and select the first option to uninstall. Do same for installing too. That should fix it

Lazy-poet your fix worked. Thank you

**Comment by joaomoreno** [comment]
Glad to know the workaround works!

**Comment by ryu9663** [comment]
> I ran into this as well but I managed to get `code` command to work yesterday but it wasn't working any more today. My problem was that the `code` was referring to an instance in a temporary folder. So I just removed `/usr/local/bin/code` and then added it again from VSCode (after making sure that I launched VSCode from the `Applications`).
> 
> So essentially this: https://apple.stackexchange.com/a/294178

thank you so much! from korea

**Comment by NavinduK** [comment]
> I found a fix. I simply uninstalled the code command from PATH in vscode and reinstalled. i.e open the command pallete, search "uninstall 'code'" and select the first option to uninstall. Do same for installing too. That should fix it

Fixed it.. Ty!

**Comment by haase1020** [comment]
> Same issue M1 Macbook Air, the above work around did not work. Fresh install, like 3 hours ago.

Zac! I just ran into the same issue but doing the uninstall and reinstall did fix the problem. Good to cross paths again!

**Comment by ajamous** [comment]
To solve this:

1- Open Terminal
2- run command `sudo rm /usr/local/bin/code `
3- open VSCode again and run `CMD+SHIFT+p` 

It'll ask you for root password and install successfully.

**Comment by discentem** [comment]
@ajamous's solution doesn't resolve this for me. `code` is no longer found after I kill whenever the current terminal session. This also occurs for me on Macbook Air M1, arm build.

**Comment by joakimhogberg** [comment]
> I found a fix. I simply uninstalled the code command from PATH in vscode and reinstalled. i.e open the command pallete, search "uninstall 'code'" and select the first option to uninstall. Do same for installing too. That should fix it

This works for me @ MacBook Air M1 macOS Monetary 12.0.1
