### ISSUE TITLE
VS Code has Wayland logo on Overview instead of its own logo

### ISSUE THREAD

**Issue by mystiquewolf** [microsoft/vscode#129953]
Issue Type: <b>Bug</b>

Please see the bug description here: https://bugs.kde.org/show_bug.cgi?id=438951

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.11.0-25-lowlatency
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|7.64GB (0.12GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 9cc3662d-ccfb-4569-83fb-26560f111f8b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.1.0
laravel-extra-intellisense|ami|0.6.1
html-class-suggestions|And|1.1.1
vscode-intelephense-client|bme|1.7.1
path-intellisense|chr|2.4.0
vs-code-semicolon-insertion|chr|0.0.6
gitignore|cod|0.7.0
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer-2|Coe|0.2.1
githistory|don|0.6.18
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
php-debug|fel|1.17.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
gc-excelviewer|Gra|3.0.42
output-colorizer|IBM|0.1.2
icon-fonts|idl|2.5.2
vscode-colorize|kam|0.11.1
vscode-gutter-preview|kis|0.27.1
vscode-jumpy|krn|1.0.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.14
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
es6-css-minify|olb|3.3.2
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.13.0
vscode-versionlens|pfl|1.0.9
LiveServer|rit|5.6.1
bash-debug|rog|0.3.9
laravel-artisan|rya|0.0.28
partial-diff|ryu|1.4.3
vscode-javascript-booster|sbu|14.0.1
indenticator|Sir|0.7.0
laravel-goto-controller|ste|0.0.12
code-spell-checker|str|1.10.2
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.6.0
local-history|xyz|1.8.1
material-theme|zhu|3.11.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by mystiquewolf** [comment]
Related: https://github.com/electron/electron/issues/29523#issuecomment-891301203

The fix for this might come from [chromium#1138724](https://bugs.chromium.org/p/chromium/issues/detail?id=1138724)

**Comment by mystiquewolf** [comment]
See https://bugs.chromium.org/p/chromium/issues/detail?id=1138724#c14

**Comment by mystiquewolf** [comment]
I can confirm that the fix which Google Chrome implemented in their 94 release works for the Google Chrome application.

It is pretty much very possible that VS Code also sets wrong app id which causes the same issue. A fix is probably needed on the VS Code side.

**Comment by deepak1556** [comment]
Thanks for linking the upstream bug, unlike chrome which used to case the WM_CLASS before https://chromium-review.googlesource.com/c/chromium/src/+/3071380 electron just used the result of the api [app.setName](https://github.com/electron/electron/blob/main/docs/api/app.md#appsetnamename) from apps https://github.com/electron/electron/blob/6aece4a83d12b6ec610994895e43560ae1aa77dc/shell/browser/native_window_views.cc#L254 and when the api is not called by the apps it will use the value of `NAME` field from the desktop file https://github.com/electron/electron/blob/6aece4a83d12b6ec610994895e43560ae1aa77dc/shell/common/application_info_linux.cc#L38-L48

Currently VSCode uses capitalised value for the field, I can fix this on our end but would rather implement the fix in electron so that each app need not cover this case for wayland.

**Comment by rstrube** [comment]
Could I work around this problem by manually copying the `visual-studio-code.desktop` from `/usr/share/applications` to: `~/.local/share/applications` and editing it? I'm still encountering this issue on KDE plasma 5.24.4 running on Wayland and it's annoying.  I'd love a quick work around to the issue.

This is what my distro's `/usr/share/applications/visual-studio-code.desktop` file looks like:

```
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Refined.
GenericName=Text Editor
Exec=/usr/bin/code --no-sandbox --unity-launch %F
Icon=visual-studio-code
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-visual-studio-code-workspace;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/bin/code --no-sandbox --new-window %F
Icon=visual-studio-code
```

Based on the details I've read, I've experimented with changing the `StartupWMClass` key to `code` but that did not resolve the issue:

![image](https://user-images.githubusercontent.com/4212764/160709297-149c9028-ceee-4eea-b27f-a70b9f7e725d.png)

Any suggestions would be greatly appreciated!

**Comment by Merrit** [comment]
After copying the desktop file to `~/.local/share/applications` and adding `--ozone-platform=wayland` to the `Exec` I am getting a generic icon in the panel / overview.

![image](https://user-images.githubusercontent.com/9575627/178055638-d24cad21-a8cf-4d85-a59a-85e68899049e.png)

Tried `StartupWMClass` as `Code` and `code`, to no effect.

Examining it in `Looking Glass` shows:

```
Get Started - Visual Studio Code
	wmclass:
	<untracked>
```

So it looks like gnome sees a blank wmclass field.

> when the api is not called by the apps it will use the value of NAME field from the desktop file

Not sure how this is supposed to work - for the heck of it I tried setting the `Name` line to `code`, which also had no effect.

**Comment by alejandro097** [comment]
Same here, wm_class is missing under wayland.

![image](https://user-images.githubusercontent.com/47724370/178130438-3acba03e-a4dc-4317-9d06-56a67853a471.png)

**Comment by manuel-plavsic** [comment]
Same issue here. It would be very nice to have this fixed, somehow.

**Comment by ozls** [comment]
Is there any ETA on this?

**Comment by Desmond121** [comment]
> Could I work around this problem by manually copying the `visual-studio-code.desktop` from `/usr/share/applications` to: `~/.local/share/applications` and editing it? I'm still encountering this issue on KDE plasma 5.24.4 running on Wayland and it's annoying. I'd love a quick work around to the issue.
> 
> This is what my distro's `/usr/share/applications/visual-studio-code.desktop` file looks like:
> 
> ```
> [Desktop Entry]
> Name=Visual Studio Code
> Comment=Code Editing. Refined.
> GenericName=Text Editor
> Exec=/usr/bin/code --no-sandbox --unity-launch %F
> Icon=visual-studio-code
> Type=Application
> StartupNotify=false
> StartupWMClass=Code
> Categories=Utility;TextEditor;Development;IDE;
> MimeType=text/plain;inode/directory;application/x-visual-studio-code-workspace;
> Actions=new-empty-window;
> Keywords=vscode;
> 
> [Desktop Action new-empty-window]
> Name=New Empty Window
> Exec=/usr/bin/code --no-sandbox --new-window %F
> Icon=visual-studio-code
> ```
> 
> Based on the details I've read, I've experimented with changing the `StartupWMClass` key to `code` (lower-casing the original value of `Code`) but that did not resolve the issue:
> 
> ![image](https://user-images.githubusercontent.com/4212764/160709297-149c9028-ceee-4eea-b27f-a70b9f7e725d.png)
> 
> Any suggestions would be greatly appreciated!

I tried changing the StartupWMClass to `code-oss-url-handler` and the icon became correct. However, it is still not able to be identified as the same application with the one I pinned to dock.

Still need to run in in XWayland i guess, this bug is kinda annoying.
![截图 2022-09-02 02-10-34](https://user-images.githubusercontent.com/62169603/188038352-a9cac007-86ab-470c-9cf9-1062e7566b69.png)

**Comment by jacokok** [comment]
Same issue as you with latest 1.71 update. Icon now shows at least but not identified.

**Comment by Desmond121** [comment]
## Workaround
In 1.70.x, the `wm_class` value for vscode is empty under wayland.
![](https://user-images.githubusercontent.com/62169603/188122630-f3adbf7f-eba8-483a-ad32-e244eee09001.png)
in 1.71.x (The insider version from AUR), the `wm_class` value is not empty anymore.
![](https://user-images.githubusercontent.com/62169603/188123209-9d9027f6-5954-4547-88a8-1483bd15c33e.png)

Then based on @rstrube 's workaround, change the `StartupWMClass` to `code-insider-url-handler` and it works.
This is how it looks like before changing, the icon is missing the app cannot be identified as the one I'v pinned in dock:
![](https://user-images.githubusercontent.com/62169603/188124091-8149e07c-34fe-4205-b176-2d97e05d54dc.png)
This is how it looks after fixing:
![](https://user-images.githubusercontent.com/62169603/188124282-6c0f459c-440e-4e09-8d2a-debd36692b5f.png)

*The non-insider version in 1.71.x should also work i guess. Just change the `code-insider-url-handler` to `code-url-handler`. 

I'm not familiar with who should take care of the .desktop file. The vscode developer or the package maintainer?

**Comment by kherock** [comment]
It does seem like the only issue on Wayland is that `StartupWMClas`s needs to set to `code-url-handler` on the .desktop entry. This is still present in the September 2022 release.

This isn't an AUR issue since file is rendered with the short name of "Code" in the gulpfile.

https://github.com/microsoft/vscode/blob/main/resources/linux/code.desktop

**Comment by dr-br** [comment]
The problem can also be resolved by modifying the `desktopName` entry in `/opt/visual-studio-code/resources/app/package.json` to `"desktopName": "visual-studio-code.desktop"`.

**Comment by microcai** [comment]
![image](https://user-images.githubusercontent.com/172208/219270559-9a95ca89-85f6-4d43-b449-31151ff9b937.png)
 
using this settings can workarroud this bug in KWin.

**Comment by cbrnr** [comment]
The solution by @kapvode (https://github.com/microsoft/vscode/issues/129953#issuecomment-1315491384) was the only one working for me. Wouldn't it seem like this could be solved in the PKGBUILD after all? Have you considered integrating your patch into the AUR package build? Not sure if it has any negative side effects, but I'm happy that I finally have only one correct icon in my dock!

**Comment by sqrt-7** [comment]
Still an issue on Fedora 40 (Gnome) Wayland

Can be fixed temporarily by editing `/usr/share/code/resources/app/package.json` and changing `desktopName` to `code.desktop`

Has to be done after every vscode update.

**Comment by wayne-werwolf** [comment]
I can confirm the issue mentioned by @sqrt-7. 
Also, as a sideeffect, the "App Details" link to the [Elementary OS Editor](https://github.com/elementary/code/) . Unsurprisingly `code` seems to be an overloaded identifier. 

I am on VSCode `1.93.1` with Fedora 40 and Gnome Wayland.

I want to point out that both workarounds, modifying `/usr/share/code/resources/app/package.json`  or `/usr/share/applications/code.desktop`, seem to work for me. 

I hope that the `.desktop` file is not overwritten with subsequent updates, so I stuck with this option.  I want to point out that, there is a related question on [AskUbuntu](https://askubuntu.com/a/1503121)

**Comment by manuel-plavsic** [comment]
@wayne-werwolf you should leave the original `.desktop` files in `/usr/share/applications`. Move the edited `.desktop` file to `/usr/local/share/applications/code.desktop` or `~/.local/share/applications/code.desktop`. The files in these two directories take precedence over what is in `/usr/share/applications`. This way VSCode updates will not compromise your modifications.

**Comment by ReillyBrogan** [comment]
This is another duplicate of #154693 and was fixed by #231472

CC @deepak1556

**Comment by andreamah** [comment]
@mystiquewolf could you verify that this is fixed on the latest insiders build?

**Comment by joshspicer** [comment]
Please see https://github.com/microsoft/vscode/issues/154693#issuecomment-2439029878.  Verified on our end, please let us know if you're seeing otherwise - thanks!
