### ISSUE TITLE
Node debugger doesn't break on unhandled promise rejection

### ISSUE THREAD

**Issue by ferdaber** [microsoft/vscode#130265]
Issue Type: <b>Bug</b>

When attempting to launch a file using `pwa-node` that runs a script like this:

```js
async function crash() {
  new Promise(resolve => setTimeout(resolve, 1000));
  throw new Error('crash!');
}

crash();
```

With the "Uncaught Exceptions" box checked under **Breakpoints**, the program exits without breaking where I throw the error. The node version I am using is v14.17.4, and was able to reproduce it with v14.16.0 (the one that VSCode uses). I have tried it with all settings and extensions disabled, and even by reinstalling VSCode, and it still doesn't work.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (4.44GB free)|
|Process Argv|--crash-reporter-id d54c4cbe-b545-41d3-b383-05429e18f989|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by justingrant** [comment]
Thanks so much @ferdaber for reporting and @connor4312 for a really quick fix!

Is this going to be released in a patch release of 1.59?  It'd be helpful if so, given that node debugging (at least in my app which is 100% async so every exception thrown is a promise rejection) is a very broken experience now. 

If it won't be patched, any idea when was the last VSCode release where break-on-promise-rejection worked properly?  This would be helpful because I'm planning to downgrade VSCode until this fix is released.

Or did this never work, and I'm now running into it because the code around mine (a wrapper package that I don't control) switched to async calls?

**Comment by connor4312** [comment]
The easiest way to get the fix is to use the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) on [Insiders](https://code.visualstudio.com/insiders/).

**Comment by pursual** [comment]
Nightly build on insiders still does not catch unhanded rejections. They get logged in the debug console, but not with any identifying information.
