### ISSUE TITLE
v1.60: "Auto language select" feature sets "CoffeeScript" language in "Git commit" files

### ISSUE THREAD

**Issue by aleksey-hoffman** [microsoft/vscode#132173]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.60
- OS Version: Win 10

Steps to Reproduce:

1. Update to v1.60
2. run `git commit`
3. Notice selected language was automatically set to "CoffeeScript" instead of "Git commit message"

**Comment by gjsjohnmurray** [comment]
Workaround is probably to set `"workbench.editor.languageDetection": false`

**Comment by aleksey-hoffman** [comment]
@gjsjohnmurray the feature is nice, I'd rather not disable it completely. 
But yeah, I might have do that until the issue is fixed

**Comment by gjsjohnmurray** [comment]
See #131565 for how you should be able to prevent a 'git-commit' file from switching to another language.

**Comment by gjsjohnmurray** [comment]
@TylerLeonhardt maybe https://github.com/microsoft/vscode/blob/70e30bc64e9ec7dd996259a00765f62a5e339f59/extensions/git/package.json#L2315-L2324 should disable language detection by default for 'git-commit' and 'git-rebase'?

**Comment by TylerLeonhardt** [comment]
specific workaround
```
"[git-commit]": {
        "workbench.editor.languageDetection": false
},
```

You can also do this for `git-rebase`

**Comment by TylerLeonhardt** [comment]
That will help with the `dotenv` issue I think too since we don't ship a language extension for that language in box.

**Comment by TylerLeonhardt** [comment]
fixed in ^

**Comment by TylerLeonhardt** [comment]
This will be in the 1.60.1 release targeted for next week.

**Comment by aleksey-hoffman** [comment]
@TylerLeonhardt good job, thank you

**Comment by bcaplan** [comment]
I'm still seeing this issue in 1.60.2. Was there a possible regression? Happy to provide any additional info needed, but the steps to reproduce in the [original issue comment](https://github.com/microsoft/vscode/issues/132173#issue-987232076) still apply.

Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 18.7.0

**Comment by TylerLeonhardt** [comment]
@bcaplan I think you're seeing this race condition:
https://github.com/microsoft/vscode/issues/133506#issuecomment-928414654
which I plan on fixing this week.

**Comment by bcaplan** [comment]
> @bcaplan I think you're seeing this race condition: [#133506 (comment)](https://github.com/microsoft/vscode/issues/133506#issuecomment-928414654) which I plan on fixing this week.

@TylerLeonhardt I think you might be right, the file does open with the correct language selected, then quickly switches. I look forward to the fix, thanks for the response!
