### ISSUE TITLE
No diff colors in non-English Git commit message

### ISSUE THREAD

**Issue by walles** [microsoft/vscode#133888]
Issue Type: <b>Bug</b>

Here's how VSCode highlights an English commit message template (from `git commit -v`). Notice how the diff parts are highlighted.
<img width="803" alt="git-commit-english" src="https://user-images.githubusercontent.com/158201/134964193-b78ff0d9-506a-465b-a8a8-6f217e11636c.png">

Here's how VSCode highlights a Swedish commit message template (from `git commit -v`).  Notice how the diff parts are **not** highlighted.
<img width="803" alt="git-commit-swedish-2" src="https://user-images.githubusercontent.com/158201/134977572-0bb410e4-d924-4f9b-8113-ddc0b0d163f7.png">

# Notes

The instructions in [the grammar file](https://github.com/microsoft/vscode/blob/main/extensions/git/syntaxes/git-commit.tmLanguage.json) says that PRs should be made to upstream here:
https://github.com/textmate/git.tmbundle/blob/master/Syntaxes/Git%20Commit%20Message.tmLanguage

However, that repo has a test suite requiring a Ruby version EOL since 2014 (https://github.com/textmate/git.tmbundle/issues/59), and I failed to run that, so I can't do this.

I also filed this ticket with upstream (https://github.com/textmate/git.tmbundle/issues/59), but the commit message grammar there hasn't been updated since 2016.

---

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T11:59:27.195Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.88GB free)|
|Process Argv|--crash-reporter-id 28bd2ba6-eae4-49b2-a5aa-36ae15a789a1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
troff|ban|1.0.22
markdown-preview-github-styles|bie|0.2.0
insert-unicode|bru|0.13.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.25
bazel-code|Dev|0.1.9
shell-format|fox|7.1.0
go|gol|0.28.1
zentabs|hit|0.0.7
blender-development|Jac|0.0.16
syntax-project-pbxproj|mar|0.1.3
rust-analyzer|mat|0.2.760
rainbow-csv|mec|1.9.1
HTMLHint|mka|0.10.0
language-gettext|mro|0.2.0
vscode-docker|ms-|1.17.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cmake-tools|ms-|1.8.1
cpptools|ms-|1.6.0
gremlins|nho|0.26.0
back-n-forth|nic|3.1.1
prettier-standard-vscode|num|0.8.1
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
LiveServer|rit|5.6.1
annotator|ryu|1.0.0
fish-vscode|sky|0.2.1
rewrap|stk|1.14.0
rst-vscode|tht|3.0.1
shellcheck|tim|0.16.2
cmake|twx|0.0.17
vscode-lldb|vad|1.6.7
vscode-ruby|win|0.28.0
clang-format|xav|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgst2:30361792

```

</details>

**Comment by IllusionMH** [comment]
I think it's not because of non-English text, bit because it's treated as Go language
![image](https://user-images.githubusercontent.com/1312662/134967568-ac29ef8e-6985-487e-9894-1f8e239f514c.png)
instead of Git Commit Message
![image](https://user-images.githubusercontent.com/1312662/134967740-f7ee2349-f58e-4bed-a1ea-8b212c266386.png)

Do you see same problem if you change language mode to Git Commit Message manually?

May be related to automatic language detection. 
Which was reported as #132696 and should be fixed in 1.60.2 already.

Is this issue reproducible in Insiders version? https://code.visualstudio.com/insiders/
Is it reproducible if you turn off automatic language detection?

/assign TylerLeonhardt

**Comment by walles** [comment]
Oops, sorry. Screenshot updated, problem persists.

The grammar has the string `Please enter the commit message` in 7 different places, as well as one `Changes to be committed`, so it's not unlikely that this only works for English:
<https://github.com/microsoft/vscode/blob/main/extensions/git/syntaxes/git-commit.tmLanguage.json>

Try this in Git Commit Message mode and you should see it as well.

What I wish for is for the lines `-foo` and `+bar` to be highlighted.

```

# Ange incheckningsmeddelandet för dina ändringar. Rader som inleds
# med "#" kommer ignoreras, och ett tomt meddelande avbryter incheckningen.
#
# På grenen main
# Ändringar att checka in:
#	ändrad:        hej
#
# ------------------------ >8 ------------------------
# Raden ovan får inte ändras eller tas bort.
# Allt under den kommer tas bort.
diff --git hej hej
index 257cc56..5716ca5 100644
--- hej
+++ hej
@@ -1 +1 @@
-foo
+bar
```

**Comment by TylerLeonhardt** [comment]
@IllusionMH thanks for jumping in!

Based on the previous screenshot it sounded like it was autodetection but with the updated screenshot it appears to be an issue with the textmate grammar. Adding @eamodio and @lszomoru

**Comment by lszomoru** [comment]
Closing this as external until https://github.com/textmate/git.tmbundle/issues/60 is addressed.
As soon as this issue is addressed we will pick the latest version of the grammar and resolve the issue.

**Comment by walles** [comment]
https://github.com/textmate/git.tmbundle is dead, it was last updated in 2019.

I think it would be better to break the dependency on that dead repo and accept changes directly into the (not dead) vscode repo.

@lszomoru could we:
* Change the terms here since that other repo is dead?
* Accept changes directly in here
* Re-open this ticket?

**Comment by lszomoru** [comment]
Adding @alexr00 as she manages the grammar files included in vscode.

**Comment by alexr00** [comment]
Opened https://github.com/microsoft/vscode/issues/168847.
