### ISSUE TITLE
“New terminal” button in locked editor group causes new terminal to open in different editor group

### ISSUE THREAD

**Issue by GrantASL19** [microsoft/vscode#135022]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.0
- OS Version: macOS 11.6

## Steps to Reproduce

1. Create a locked editor group containing a terminal:
    
<img width="903" alt="Screen Shot 2021-10-13 at 1 48 32 PM" src="https://user-images.githubusercontent.com/30265160/137186276-b9412668-7bfb-4d0a-8933-8eb04d7d1169.png">

2. Click the “New terminal” (+) button in the editor group header.
    
## Result

The terminal opens in a different editor group and locks the group:

<img width="903" alt="Screen Shot 2021-10-13 at 1 48 43 PM" src="https://user-images.githubusercontent.com/30265160/137186478-5b54f46b-92e6-465a-8d3e-912c9717acbc.png">

## Expected result

The terminal should open in the same editor group, like so:

<img width="903" alt="Screen Shot 2021-10-13 at 1 52 30 PM" src="https://user-images.githubusercontent.com/30265160/137186748-d98d24f2-912b-44b8-b13a-16deab34734e.png">

(This may be the same issue as #131156 but because it’s been closed I can’t comment in it.)

**Comment by meganrogge** [comment]
This is working for me in insider's, so I believe it was fixed already.

**Comment by meganrogge** [comment]
can't reproduce in insider's, likely fixed now that the terminal editor is a singleton

**Comment by GrantASL19** [comment]
I can still make this happen with the same reproduction steps in the latest Insiders build
(Commit: d12df34e31b4a018735d312a8947d79331132368).

Could this somehow be a macOS-specific bug? I’m trying to think of other reasons different users are seeing different results.

**Comment by meganrogge** [comment]
on Mac
![recording (24)](https://user-images.githubusercontent.com/29464607/146567407-15542b32-fb04-4985-84c0-1bb484bca860.gif)
![recording (25)](https://user-images.githubusercontent.com/29464607/146567558-7eda42e8-cf76-44cb-96a8-a40628d1ad3c.gif)

**Comment by meganrogge** [comment]
you're right reproduces with the editor group on the right

**Comment by GrantASL19** [comment]
I can still reproduce this in the latest Insiders build (Version: 1.65.0-insider Commit: d09aeab62c1f93acf4a89b93e9a8a82419d6249a).

**Comment by Tyriar** [comment]
@bpasero I looked into this but couldn't find an option I can pass in to `IEditorService.openEditor` to force opening in the group if it's locked. It ends up here and passing on the active group:

https://github.com/microsoft/vscode/blob/667d4629dee90744edd5054f13bc2452c8c14490/src/vs/workbench/services/editor/common/editorGroupFinder.ts#L136-L138

Am I missing something or would this need to be a new option to ignore locked?

I think the ask makes sense that doing a plus via the action in the top of the editor should open it in that editor group as it's similar to dropping an editor into the group. I was going to make a new internal command that passes in a special option.

**Comment by bpasero** [comment]
@Tyriar it should bypass if either you pass in the identifier of a group explicitly or `SIDE_GROUP`

**Comment by GrantASL19** [comment]
Thanks for your work on this, but FWIW I can still reproduce [like this](https://github.com/microsoft/vscode/issues/135022#issuecomment-946178491) in the latest Insiders build (`Version: 1.79.0-insider (Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302)`).

**Comment by Tyriar** [comment]
@GrantASL19 thanks for verifying, it should land in the first 1.80.0-insider build

**Comment by GrantASL19** [comment]
> @GrantASL19 thanks for verifying, it should land in the first 1.80.0-insider build

Fix verified in `Version: 1.80.0-insider
Commit: 73eb619afb87cab4aa83a569259c891b6983c11e`, thanks!
