### ISSUE TITLE
After upgrade to MacOS Monterey, vscode unusable, extremely slow rendering

### ISSUE THREAD

**Issue by zajo** [microsoft/vscode#136260]
First, thank you for the great IDE.

My vscode window spans two external monitors. After installing MacOS Monterey, vscode is able to draw about 2 frames per second (it works fine on the laptop display).

Any suggestions on adjusting rendering options?

```
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

```

![about](https://user-images.githubusercontent.com/609498/139799142-b016ae86-d415-4edd-bab3-47ae1d3c8cf5.png)

**Comment by ShubhamVerma1811** [comment]
Experience the same lag on Mac Montery

**Comment by deepak1556** [comment]
Can you attach the following data points to further debug the issue, thanks!

1) Does the issue happen when you launch with `--use-cmd-decoder=passthrough`
2) Does the issue happen when you launch with `--disable-gpu`
3) Can you provide the output of `code --verbose`
4) Can you provide the output of `system_profiler SPDisplaysDataType`

**Comment by ShubhamVerma1811** [comment]
Hey @deepak1556 ,
Tried the steps.
1. The cli says this doing `code --use-cmd-decoder=passthrough`. **_The LAG still happens_**
`Warning: 'use-cmd-decoder' is not in the list of known options, but still passed to Electron/Chromium.`
2. **_The lag still happens_,** tried scroll through lines and switching b/w files.
3. [verbose.txt](https://github.com/microsoft/vscode/files/7464634/verbose.txt)
4. [sysprof.txt](https://github.com/microsoft/vscode/files/7464635/sysprof.txt)

**Comment by deepak1556** [comment]
Can you also attach the profile following these steps https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-sluggish

**Comment by zajo** [comment]
Thank you for looking into this. I can confirm that neither of `--disable-gpu` or `--use-cmd-decoder=passthrough` fixes anything.

**Comment by zajo** [comment]
Another bit of information: the lag seems to grow significantly with the number of vscode windows open, even when they are fully covered by the top-most vscode window. With 7 open vscode windows, even menus are sluggish, the menu selection is updated something like once every 4 seconds (!) on my laptop. Minimizing all but one window makes the menus completely responsive, but the rest (editor scrolling) is still very slow.

**Comment by deepak1556** [comment]
@zajo can you also attach the output of `system_profiler SPDisplaysDataType`. @ShubhamVerma1811 setup does not seem to have an external monitor and you have mentioned originally that the problem does not repro with external monitors disconnected. So looks like there are two different issues here, I don't have a multi-monitor setup but asked my colleague to check on this and they were not able to repro with a single external monitor. So very likely issue is associated with the type of display and gpu driver.

Additionally @zajo can you also attach the profile following the steps below,

```
1) Start the app like

code --enable-gpu-service-tracing --enable-tracing="blink,cc,gpu,renderer.scheduler,sequence_manager,v8,toplevel,viz,disabled-by-default-viz.overdraw" --trace-startup-file="/tmp/vscode_slow_trace.log"

2) Perform all the steps to repro the slowdown
3) Quit the application (Cmd + Q)
3) Log file `vscode_slow_trace.log` will be generated inside `/tmp`
```

**Comment by ShubhamVerma1811** [comment]
I do have a external monitor, but I didn't have it connected when gathered the logs.

For me the issue happens with and without external monitor.

**Comment by deepak1556** [comment]
@ShubhamVerma1811 thanks for confirming, can you test if the slowdown happens when you use the application from the external monitor. Also it would be helpful to get a trace from your setup based on the steps outlined here https://github.com/microsoft/vscode/issues/136260#issuecomment-958645614

**Comment by ShubhamVerma1811** [comment]
Hey @deepak1556 ,
Sorry for the delayed reply.
I tried to just use vscode in external monitor, the slowness still occurs.
Here is the vscode_slow_trace.log
[vscode_slow_trace.log.zip](https://github.com/microsoft/vscode/files/7472418/vscode_slow_trace.log.zip)

**Comment by deepak1556** [comment]
Thanks for the log, first highlight is there is aggressive gpu flushing via `GLContext::FlushForDriverCrashWorkaround`, this was added via https://bugs.chromium.org/p/chromium/issues/detail?id=906453 to avoid trigger bug in certain gpu drivers. Couple of things to check based on this,

1) How is the perf when you start with `code --disable-oop-rasterization`
2) When you use `https://vscode.dev` on chrome or edge on the same machine, do you see similar perf regression ?
3) Quick check on which gpu is problematic, can you try `code --force_high_performance_gpu` and `code --force_low_power_gpu` to see if there is a difference.

**Comment by zajo** [comment]
@deepak1556 I followed your steps but after quitting there was no `/tmp/vscode_slow_trace.log`. In Terminal I got:

```
Warning: 'enable-gpu-service-tracing' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-tracing' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'trace-startup-file' is not in the list of known options, but still passed to Electron/Chromium.
```

Just in case I tried generating a log in the home directory, also no output.

**Comment by ShubhamVerma1811** [comment]
Followed steps from here - https://github.com/microsoft/vscode/issues/136260#issuecomment-961177760
- Slowness happened on vscode.dev
- Tried with `force_high_performance_gpu` and `force_low_power_gpu` flags, Slowness still happened.
- And I got the same warning in terminal like Zajo menitioned above.

**Comment by deepak1556** [comment]
@zajo thanks for trying the debug steps, you can ignore those warnings. The file might take a couple of seconds to generate depending on the active time of the application. Can you ensure there was no code process running after you quit the app.

@ShubhamVerma1811 thanks for testing

> Slowness happened on vscode.dev

As a next step here, can you help open an issue with chromium https://bugs.chromium.org/p/chromium/issues/list using `https://vscode.dev` as an example. The issue should now be addressed in the runtime.

> How is the perf when you start with `code --disable-oop-rasterization`

Did you also try this ?

**Comment by ShubhamVerma1811** [comment]
Yes, I did try with `disable-oop-rasterization`,
The slowness still happened.

You want me to open this issue in bugs .chromium?
Is that right?

**Comment by zajo** [comment]
@deepak1556 I'm pretty sure there was no process running (the indicator on the icon in the MacOS dock went off). It is possible that something didn't work correctly because vcode was running extremely slowly, menu selection moved at 0.5 frames per second (it takes two seconds for the menu selection to follow the mouse cursor).

**Comment by mattfysh** [comment]
I've also noticed performance tank after upgrading to Monterey, most noticeable when selecting text. Clicking and dragging feels slow & unresponsive, and sometimes when hitting cmd+a to select all, it can take a second or two.

**Comment by deepak1556** [comment]
@ShubhamVerma1811 yes, also please use running `https://vscode.dev` on chrome browser as the repro scenario when filing the issue as it will be easier for the developers to triage it faster.

**Comment by ShubhamVerma1811** [comment]
@deepak1556 and everyone here,
I was in the process of opening bug in chromium, and I noticed one thing in VSCcode while testing..

Try this thing,
Remove everything from your settings.json file and make it `{}`. Doing thing is not causing the slowness.
Both  vscode.dev and native VSCode are now working fast like before.

So I believe some property of some extension is causing this effect. I need to perform trial and error to get the extact extension culprit.

**Comment by steida** [comment]
I have the same problem, tried everything mentioned without success.

**Comment by zajo** [comment]
renderWhitespace none makes no difference for me, it's just as slow, very slow.

**Comment by deepak1556** [comment]
> When you use https://vscode.dev on chrome or edge on the same machine, do you see similar perf regression ?

@zajo @steida can you confirm if the issue persists in this setup.

**Comment by zajo** [comment]
It's fine in chrome.

**Comment by deepak1556** [comment]
@zajo thanks for confirming, as a next step I would like to confirm if this problem is specific to a particular Electron runtime version, I am attaching two packages below which runs `https://vscode.dev` on Electron `13.5.2` (chromium 91) and Electron `16.0.0-beta.8` (chromium 96). Can you try the same steps as performed on vscode stable desktop, also try to match the settings via sync if possible and confirm if the slowdown is seen in either.

https://www.dropbox.com/sh/upycmvc0t7ssuei/AADSOJbtbMDVtc9W5rCfeAYIa?dl=0

**Comment by mattfysh** [comment]
Thanks @ShubhamVerma1811 - `editor.renderWhitespace` was indeed the culprit. I'll set this to `none` for now

**Comment by zajo** [comment]
@deepak1556 This weekend I'll try the steps you requested, but for now an update -- `editor.renderWhitespace` definitely does not fix the problem for me. On my setup (I have 3 monitors plugged into my laptop) vscode is so slow that if I have multiple vscode windows open, MacOS can't even keep up moving the mouse cursor smoothly, it affects the whole computer, and it does not go away, as long as the vscode windows are open the computer is nearly unusable. Minimizing the windows one by one speeds things up, but even with one window it is slow.

It looks to me vscode is holding a lock on a mutex where it shouldn't be. Is that possible?

**Comment by zajo** [comment]
@deepak1556 Both of the builds you attached work fast on my system but there is a ton of flickering as I scroll (I did not migrate settings).

**Comment by leon11081991** [comment]
> @deepak1556 and everyone here, I was in the process of opening bug in chromium, and I noticed one thing in VSCcode while testing..
> 
> Try this thing, Remove everything from your settings.json file and make it `{}`. Doing thing is not causing the slowness. Both vscode.dev and native VSCode are now working fast like before.
> 
> So I believe some property of some extension is causing this effect. I need to perform trial and error to get the extact extension.
> 
> EDIT: I might have found the property, it is `editor.renderWhitespace`. It is set to `all`, then lag would occur If it is not set, then lag would occur on selection as mentioned by @mattfysh.
> 
> So in your settings.json add this ` "editor.renderWhitespace": "none"`. Now I think the lag should go away.
> 
> > Having `editor.renderWhitespace:all` only had the slowness effect on chrome and edge.Safari and Firefox didn't lag.
> 
> Although this is just a temporary fix because people like me really what that option to be set to "all".

Thanks a lot @ShubhamVerma1811 
I got the problem after update my mac, even I change mine to another macpro.
But the problem still, after your advise the problem amazing solved !!!!!
Really THANK YOU!!!!

**Comment by zajo** [comment]
Just upgraded to the latest 1.63.0, somehow the rendering on my system got even slower. I'm getting about 2 frames per second when I type or scroll. This is really painful, how can I help to diagnose the issue?

**Comment by ShubhamVerma1811** [comment]
Have you tried removing everything from settings.json to {} ?
That helped me narrow down the property that caused it ..

**Comment by zajo** [comment]
Yep, just tested, it's equally slow with empty settings.json.

**Comment by jscheel** [comment]
I too am noticing some lagging (mbp 16" i9, monterey 12.1). However, I'm noticing that _all_ my typing is crazy laggy when the integrated card is being used, especially in chromium based apps. It's wild how bad it is. If I test https://vscode.dev in Chrome vs Safari, it's absolutely evident. I'm not sure this is a vscode problem, this seems to be a chromium / monterey problem (imho, it's an apple problem, but that's another discussion).

**Comment by zqcccc** [comment]
2019 macbook pro 15.6inch
when I connect with external monitor, vscode will be very slow and lagging, once disconnect the external monitor, vscode recover to the normal perfermance.

**Comment by jscheel** [comment]
I've filed an issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=1291590

**Comment by deepak1556** [comment]
@zajo sorry for the delay on getting back to this thread, can you test our exploration build based on a newer runtime version and see if the lag continues. Thanks!

[macOS universal download](https://az764295.vo.msecnd.net/exploration/8eab3dba050a3bd11dcdd33f6bca2fe807cf3f9c/VSCode-darwin-universal.zip)

**Comment by zajo** [comment]
@deepak1556 Thanks! I think I have some useful information for you, though we're in the unfortunate situation that my configuration has changed since I reported the original issue: previously I was using multiple external monitors, and now I'm using a single 4K external monitor. Another difference is that I've upgraded to the newest macOS Monterey 12.2.

With this changed setup, vscode worked well for weeks until I downloaded this latest update today:

```
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0
```

And now it's very slow again, although probably for a different reason, since the original problem was gone when I switched to one external monitor. I have multiple vscode windows open (which I need, and was not a problem before the today's update), I get this in Activity Monitor:

![Screen Shot 2022-02-06 at 16 00 22](https://user-images.githubusercontent.com/609498/152707989-377f54ca-3144-4dcf-a73e-b7944156ca60.png)

The good news is that the exploration build you attached does not have this problem.

If you want me to run more experiments, let me know.

**Comment by deepak1556** [comment]
@zajo [insiders](https://code.visualstudio.com/insiders) has now been updated to same runtime version as exploration. Can you check if the issue is now present with it, thanks!

**Comment by zajo** [comment]
It's good. I guess we can close the issue now, even though we don't know if it's fixed on my setup when I reported it originally.

**Comment by NorthernMan54** [comment]
@deepak1556 This is good as well.  I was also suffering from sluggish behaviour on my dual monitor setup, but it was only triggered after running my selenium/chromedriver test scripts.  Or that was when I had noticed it.  Installing the insiders version resolved it.

I was also experiencing Electron crashes as well, and these are resolved as well.

**Comment by deepak1556** [comment]
Closing based on insiders testing, thanks for self-hosting with the build!

**Comment by im0qianqian** [comment]
Hello, I've been paying attention to this issue recently.
Thank you very much for the temporary solution provided by @ShubhamVerma1811, which makes me no longer suffer from slow trouble. But after my test today, I found that my problem may have something to do with the font setting. Here is my condensed version of `settings.json`.

```json
{
    "editor.fontFamily": "YaHei Consolas Hybrid, monospace",
    "editor.renderWhitespace": "all",
}
```

- When I set `editor.renderWhitespace: none`, there will be no slow problem. 
- When I remove `YaHei Consolas Hybrid` from `editor.fontFamily`, there also will be no slow problem.

I tried to use `YaHei Consolas Hybrid` font in the vscode insider version, and set `editor.renderWhitespace: all`, but the slow will still exist.
I hope this can provide you with some information.

[YaHei_Consolas_Hybrid_1.12.ttf.zip](https://github.com/microsoft/vscode/files/8094744/YaHei_Consolas_Hybrid_1.12.ttf.zip)

**Comment by deepak1556** [comment]
@im0qianqian thanks for the repro, I can confirm the issue. I have updated https://github.com/microsoft/vscode/issues/111816 with your test case, can you follow that issue for updates, thanks!

**Comment by akhilmhdh** [comment]
Hey there. Thank you so much for finding the culprit. I was having this issue quite a while after upgrade.

`editor.renderWhitespace: none` did save me. ❤️

**Comment by deepak1556** [comment]
Runtime version has been reverted for February milestone https://github.com/microsoft/vscode/pull/143851

**Comment by NorthernMan54** [comment]
I have updated my vscode-insiders release to the latest, and the problem has returned.  I had been using the older version from about 4 weeks ago without issue.  Based on this being closed I had assumed that insiders had been updated, or do I need to wait for next insiders release ?

```
Version: 1.66.0-insider
Commit: 6b7453421201c888b81eae5c04ec822a6423608f
Date: 2022-03-11T05:16:52.815Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.3.0
```

**Comment by Kamlesh502** [comment]
changing the editor.fontFamily solved my issue

**Comment by zajo** [comment]
Broken again after upgrading to macOS Monterey 12.3, see image.

![screenshot](https://user-images.githubusercontent.com/609498/160037484-b7e930ed-3081-475f-a5e8-e94462f8a4c0.png)

Visual Studio Code info:

```
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.4.0
```

**Comment by deepak1556** [comment]
@zajo the fix has not yet made into the stable release, it will be available in `1.66`. Can you check if the issue persists with https://code.visualstudio.com/insiders ?

**Comment by zajo** [comment]
I'd rather wait for the 1.66 release, if you don't mind. I have a suspicion that this may in the end turn out to be a temporary thing, when I originally opened this issue it also was after a OS version update -- is it possible that the new OS is doing some system-specific optimizations that interfere somehow with vscode?

**Comment by zajo** [comment]
My theory seems to be correct: after the MacOS upgrade, for two days vscode was having this issue. Now the issue is gone, without rebooting the OS and without even restarting vscode. As to what's causing it, who knows, maybe the new OS is reindexing files, maybe it's optimizing something, and maybe that interferes somehow with vscode. I hope this info helps.
