### ISSUE TITLE
Powershell Core installed with scoop is not recognized in terminal

### ISSUE THREAD

**Issue by Rafeqm** [microsoft/vscode#137323]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.62
- OS Version: Windows 11 Build 22000

Steps to Reproduce:

1. Install **Powershell Core** from _scoop_.
2. Just open VS Code and its integrated terminal.
3. Default terminal profile is just `powershell`.
4. VS Code does not recognize `pwsh` from scoop **PATH**.
5. Tried to tweak 4 settings in `setting.json` related to terminal profile, but no avail.

Why Windows Terminal recognize `pwsh` from scoop directory while VS Code no does not?

**Comment by Tyriar** [comment]
I believe this was fixed in the recovery build.

**Comment by Rafeqm** [comment]
> I believe this was fixed in the recovery build.

And which version is that build?

**Comment by Tyriar** [comment]
1.62.3

**Comment by Rafeqm** [comment]
Hey sorry for late feedback. But I updated vscode to this latest version and integrated terminal still does not recognize `pwsh` from scoop PATH and default to **_Windows Powershell_** not **Powershell Core**. Here is the screenshot:

![Screenshot (16)](https://user-images.githubusercontent.com/87463084/144068711-1ba40379-11d7-42e8-921c-fbb45e088448.png)

I think this issue should be reopen :(

**Comment by Rafeqm** [comment]
**Update**: I figured it out. I just tweak settings and vscode can now detects it:

```json
    "terminal.integrated.profiles.windows": {
        "PowerShell Core": {
            "path": "pwsh.exe",
            "icon": "terminal-powershell"
        }
    },
```
Just Happy to share it now after three weeks tweaking it 😎.

**Comment by Tyriar** [comment]
I don't think we detect the scoop install: https://github.com/microsoft/vscode/blob/494cbbd02d67e87727ec885f98d19551aa33aad1/src/vs/base/node/powershell.ts#L239-L294

fyi @TylerLeonhardt if this is something you want to add

**Comment by TylerLeonhardt** [comment]
Yeah the scoop usage was pretty low and rather than it installing in the normal location (which is what winget & chocolatey do) it goes to a specific scoop place.

That is why we didn't do it in the PowerShell extension.

In any case, I'll say what I said then... I'm not planning on adding this, but if a PR came in for it, I wouldn't reject it.
