### ISSUE TITLE
Scroll is reset and cell input history is lost when interactive window is hidden and shown (overlaid with a tab, for instance)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#138557]
1) Start an interactive window run that spans enough vertical space to require vertical scrolling.
2) Scroll to the bottom of the window
3) Show a tabbed window on top of the IW. (I used either of the new links from "Output exceeds the size limit. Open the full output data in a text editor").
4) Show the IW again.

Window is scrolled to the top of the history. And the history of cell inputs is also lost. The combination of these problems makes the interactive experience very annoying to deal with.

Ran into this countless times when just doing advent of code puzzles.

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/e447f19ea03f6177e3885105b63e801a1198c18a

**Comment by rchiodo** [comment]
This doesn't seem to have been fixed. At least the history portion of it is still broken.

**Comment by rchiodo** [comment]
@rebornix I'm investigating (assuming you weren't jumping on this)

**Comment by janosh** [comment]
@rchiodo I think your PR does not address #131742 which is also not fixed yet, correct? Could #131742 please be reopened?

**Comment by rchiodo** [comment]
@janosh  #131742 should have already been addressed. I thought @rebornix's first fix for #138857 addressed it. It seems to work for me? Are you using the latest insiders?

**Comment by janosh** [comment]
No, I'm using stable but the first fix e447f19 from over a month ago should be in there right?

**Comment by rchiodo** [comment]
No there hasn't been a build since the beginning of December. VS code skips a build every January.

**Comment by janosh** [comment]
Ah, I see. So will land in stable early Feb?

**Comment by rchiodo** [comment]
Yep should be early February. End game starts next week, so the week after is when it should ship.
