### ISSUE TITLE
Tooltips block clicks

### ISSUE THREAD

**Issue by distinctdan** [microsoft/vscode#141767]
Issue Type: <b>Bug</b>

If I move my mouse over a line of code and click on it, sometimes a tooltip appears just as I'm clicking, blocking the click. The tooltips are actually slightly overlapping the top of the current line. Tooltips also like to appear if I move my mouse too slowly, completely blocking whatever I was trying to click on. These are super annoying and make it difficult to work in VSCode, because I'm constantly having to close popups just to get to my code.

I think there are 2 fixes necessary here:
 - Position tooltips higher so they don't overlap the current line at all
 - Greatly increase the tooltip appearance delay. If I'm just moving my mouse over the code, there's no reason for a bunch of crap to appear and block whatever I'm trying to work on. If I want more information about something, I think a delay of at least 1 second is more appropriate before showing popups.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|--crash-reporter-id 656c6348-b102-4b6b-8ade-e7f56a3faa5f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
go|gol|0.31.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.19.0
vscode-kubernetes-tools|ms-|1.3.6
remote-containers|ms-|0.209.6
cpptools|ms-|1.7.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.3.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710cf:30416617
vsbas813:30426126

```

</details>

**Comment by gjsjohnmurray** [comment]
Delay before the hover appears is already configurable. In 1.63 a bug means the actual delay is only half what you set, but that should be resolved when 1.64 ships next week.

**Comment by distinctdan** [comment]
Thanks, I am aware the delay is configurable, but the default is pretty obnoxious, so I still think this needs to be fixed. Users shouldn't have to go change a bunch of stuff just for basic functionality to feel good. The tooltip positioning is still an issue too.

**Comment by gjsjohnmurray** [comment]
Please retest after 1.64 ships.

**Comment by alexdima** [comment]
@distinctdan Can you please try out our [insiders build](https://code.visualstudio.com/insiders/) which can be installed side-by-side and contains the fix?

**Comment by distinctdan** [comment]
I'm sorry, I'm not willing to go through installing the insiders version at this time. Regarding the tooltip delay, really this is just feedback for you guys that the default is way too low.

Regarding the overlap, it doesn't sound like that's on the radar at the moment?
