### ISSUE TITLE
Notebook UI Bugs: pandas Series not formatted and cell run/delete options overlay is always visible above cell content

### ISSUE THREAD

**Issue by firegate22** [microsoft/vscode#143214]
I did, but it is very hard to find and start in the right repo as well (is it vscode or vscode-jupyter?).

## Environment data

-   VS Code version: 1.65.0- Date: 2022-02-16T05:16:06.667Z (5 hrs ago)
-   Jupyter Extension version (available under the Extensions sidebar): v2022.2.1010480428
-   Python Extension version (available under the Extensions sidebar): v2022.1.1829344769-dev
-   OS (Windows | Mac | Linux distro) and version: mac newest (12.2.1)
-   Python and/or Anaconda version: 3.9/3.10..
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv
-   Jupyter server running: Local |

## Expected behaviour

okay (cell 1) 
![image](https://user-images.githubusercontent.com/37472736/154246781-8ddf7068-500c-42ba-90c8-8840c7d90d3c.png)

not okay (all other cells - don't know if cell 1 is always okay)
![image](https://user-images.githubusercontent.com/37472736/154246805-5b0940ea-a6a1-4880-be07-fcf701ca189f.png)

okay
![image](https://user-images.githubusercontent.com/37472736/154247102-f33c4c21-fbfd-4d89-9746-b3105e6118f7.png)

not okay

![image](https://user-images.githubusercontent.com/37472736/154247172-62079494-0ff5-453d-88f8-5c26471d3cb7.png)

Series are affected, maybe other usually formatted outputs as well. DataFrame works.

## Logs

**Comment by rebornix** [comment]
The line break issue should be fixed in tomorrow's Insiders.

cc @roblourens though for the toolbar overlapping the text

**Comment by roblourens** [comment]
The overlapping toolbar was fixed in https://github.com/microsoft/vscode/issues/143213

**Comment by RaulDelary** [comment]
I also have these formatting issues, any workaround for this?

![image](https://user-images.githubusercontent.com/50054341/154713791-00a74ba4-5687-40b0-be8e-0a6abfb8ba9a.png)

![image](https://user-images.githubusercontent.com/50054341/154714339-f7eda08f-308b-46ac-a1b2-1e3dff5068b0.png)

![image](https://user-images.githubusercontent.com/50054341/154714493-3c621dc7-ef74-4e3e-87f6-9f71b266caca.png)

**Comment by roblourens** [comment]
Is there still an issue with the pandas output format here or can this be closed? Wrong renderer getting selected?

**Comment by Syndorik** [comment]
It used to be like that (example taken from Internet)
![image](https://user-images.githubusercontent.com/28219244/155989888-1e650659-fce4-4578-a352-733a66df204f.png)

**Comment by capyvara** [comment]
I'm having the same problem, series are unaligned, used to work nicely.

![image](https://user-images.githubusercontent.com/1027847/157575339-40a5bcb9-131d-453e-9bca-17ffa6ce8d5a.png)

**Comment by rebornix** [comment]
This is what I'm seeing in latest Insiders 

<img width="699" alt="image" src="https://user-images.githubusercontent.com/876920/159599627-13e9a2d2-a72a-42a0-8d20-015878dc8983.png">
