### ISSUE TITLE
Deployment to Azure Function Fails with reason: read ECONNRESET

### ISSUE THREAD

**Issue by ebrenton** [microsoft/vscode#146470]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.0
- OS Version: Windows 10 

Steps to Reproduce:

1. Attempt to deploy to an Azure Function using Azure Function extension fails with the error "reason: read ECONNRESET"
2. I downgraded VSCode to version 1.65.2 and the deployment started working again
3. I have disabled automatic updates for the time being.

**Comment by DiegoGFritz** [comment]
I have the same problem when deploy to web app

Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by ShawnMcGough** [comment]
I am also experiencing this issue deploying a function app. 

Reverting to version 1.65.2 (user setup) fixed the issue.

**Comment by jrieken** [comment]
Looks like an extension issue but maybe something with our proxy solution has changed?

**Comment by bwateratmsft** [comment]
@jrieken that seems plausible; we released an update about a week ago but a significant volume of comments appeared just yesterday. Also, users have said that downgrading VSCode to 1.65.2 causes it to work again. So it seems like some change in VSCode caused this--either the Node 16 upgrade or proxy changes (sounds more likely).

**Comment by ebrenton** [comment]
> @jrieken that seems plausible; we released an update about a week ago but a significant volume of comments appeared just yesterday. Also, users have said that downgrading VSCode to 1.65.2 causes it to work again. So it seems like some change in VSCode caused this--either the Node 16 upgrade or proxy changes (sounds more likely).

Agreed!
I have been deploying new code to Azure on a daily basis. Everything was working fine until VSCode auto-updated to version 1.66. I have not made any changes or updates to any extensions in several weeks.
Thank you.

**Comment by chrmarti** [comment]
There were no changes to the network proxy support in 1.66.

@ebrenton Do you also see this with the proxy support in user settings disabled?
<img width="403" alt="image" src="https://user-images.githubusercontent.com/9205389/161291895-0d86f61f-37cd-45a9-acdd-a8df6c9495a4.png">

**Comment by ShawnMcGough** [comment]
> There were no changes to the network proxy support in 1.66.
> 
> @ebrenton Do you also see this with the proxy support in user settings disabled? <img alt="image" width="403" src="https://user-images.githubusercontent.com/9205389/161291895-0d86f61f-37cd-45a9-acdd-a8df6c9495a4.png">

@chrmarti 
I can confirm deployment still does not work with 1.66 when setting 'Http: Proxy Support' for extensions to 'off'. Fails in the same way.

**Comment by DiegoGFritz** [comment]
I have this configuration
![image](https://user-images.githubusercontent.com/26330822/161310912-7ec9fa74-4280-4eec-850b-98e03ed72718.png)

**Comment by faceoffers28** [comment]
Sames issue. Running 1.66.0 now. It worked just fine last week. Visual Studio Code 1.66.0 installed on 3/30/22.

**Comment by ChrisMidkiff** [comment]
I am also seeing this issue after upgrade today.

**Comment by alexweininger** [comment]
@jrieken @chrmarti I outlined this in #146577, but will repeat here in case it provides more context to the issue:

I found that setting `NODE_DEBUG=stream` while debugging the Azure Functions extension somehow fixes the issue. Without `NODE_DEBUG=stream`, I can reproduce the issue consistently. Any insight?

**Comment by deepak1556** [comment]
Very likely regressed with https://github.com/libuv/libuv/commit/ce15b8405e9d01e221f8390475deab4a40d26e38, need to test with Nodejs `>= 16.14.0` that contains https://github.com/libuv/libuv/commit/b2614a10a579ae6e9936eb483fe5ce14aa65a212 and https://github.com/nodejs/node/commit/3b5b893abb1d2929673386204d870e5f138ec3d0. Refs https://github.com/nodejs/node/issues/39683

**Comment by Elrinth** [comment]
I am on 1.66.0 and also experience this problem.
Installing https://code.visualstudio.com/updates/v1_65 instead solved the problem.

**Comment by alexweininger** [comment]
> Very likely regressed with [libuv/libuv@ce15b84](https://github.com/libuv/libuv/commit/ce15b8405e9d01e221f8390475deab4a40d26e38), need to test with Nodejs `>= 16.14.0` that contains [libuv/libuv@b2614a1](https://github.com/libuv/libuv/commit/b2614a10a579ae6e9936eb483fe5ce14aa65a212) and [nodejs/node@3b5b893](https://github.com/nodejs/node/commit/3b5b893abb1d2929673386204d870e5f138ec3d0). Refs [nodejs/node#39683](https://github.com/nodejs/node/issues/39683)

@deepak1556 if you could supply a VS Code build with Nodejs >= `16.14.0`, I can check to see if the issue is resolved.

**Comment by deepak1556** [comment]
@alexweininger yup I am working on the build, will update here once it is available for testing. Thanks for the help!

**Comment by deepak1556** [comment]
@alexweininger today's insider contains the fixes mentioned in https://github.com/microsoft/vscode/issues/146470#issuecomment-1087175293, can you check if it addresses the issue. Thanks!

**Comment by klodha** [comment]
@deepak1556 

I just tried insiders build but that doesn't seems to address the issue. Same issue of `ECONNRESET`.  

```
Version: 1.67.0-insider
Commit: f050b17dacedba13962244b13c70084a473d08f7
Date: 2022-04-06T05:26:11.128Z (3 hrs ago)
Electron: 17.3.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0
```

**Comment by alexweininger** [comment]
> today's [insider](https://code.visualstudio.com/insiders) contains the fixes mentioned in [#146470 (comment)](https://github.com/microsoft/vscode/issues/146470#issuecomment-1087175293), can you check if it addresses the issue. Thanks!

@deepak1556

I tested the latest insiders build and the issue still reproduces. As @bwateratmsft mentioned above, it appears that the latest Insiders release is still on Electron v17.3 and Node.JS `16.3.0`.

<details>
<summary>VS Code version details</summary>

Version: 1.67.0-insider (Universal)
Commit: f050b17dacedba13962244b13c70084a473d08f7
Date: 2022-04-06T05:15:27.397Z
Electron: 17.3.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.4.0

</details>

**Comment by deepak1556** [comment]
> I grabbed the latest Insiders build and it seems to still be on Electron v17, so does not have the needed fix yet as I understand. It needed an update to v18 right?

Sorry for the confusion, the electron build numbers don't change, backports have been made to the same version. What would change in these cases is `process.versions["microsoft-build"]`

Since it is confirmed that insiders does not fix the issue, I would need to investigate further with E2E setup. I will update here once there is some progress.

**Comment by LidorPrototype** [comment]
After I downgraded, and tried most of the stuff I found about this issue, that error passed away but now I get the following fail:

`Creating virtual environment...
1:22:05 PM boirndextauto: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -i /tmp/8da1880713886a2 --compress-destination-dir -p virtualenv_name=antenv --log-file /tmp/build-debug.log 
1:22:07 PM boirndextauto: Deployment Failed.
1:22:16 PM boirndextauto: Deployment failed.`

Do you know why is this?

**Comment by deepak1556** [comment]
Just to update on the progress, the azure extension team is working on a minimal repro with Nodejs to see if there is already a fix in newer versions that can be backported and at the same time identify the commit which caused this behavior change.

**Comment by faceoffers28** [comment]
I just tried to deploy my Angular app using the Zip Deployment method. I zipped up the dist folder. I'm now getting the following error.

The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by ShawnMcGough** [comment]
It is still failing with version 1.66.2.

**Important for testing** - if the zip file is ~10 kB or less, _it works_. Make sure your test cases are larger than 10 kB or you'll get false successes. 

```
4:52:13 PM function-test: Starting deployment...
4:52:14 PM function-test: Creating zip package...
4:52:14 PM function-test: Zip package size: 9.91 kB
...
4:52:21 PM function-test: Deployment successful.
```

```
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19042

```

**Comment by alexweininger** [comment]
@ShawnMcGough 

Sorry you're still running into this issue, we're working on a fix in the Azure Functions extension. We have a development build out that you can test to see if it fixes your issues. If you could try it out and report back your results, that'd be a big help.

Details on installing and testing the development build: https://github.com/microsoft/vscode-azurefunctions/issues/2844#issuecomment-1095673285

**Comment by faceoffers28** [comment]
@alexweininger Will this fix deployment issues with apps that aren't Functions? Seems like it will since you folks merged 146577 with this one.

**Comment by alexweininger** [comment]
> Will this fix deployment issues with apps that aren't Functions? Seems like it will since you folks merged 146577 with this one.

@faceoffers28 Yes, this fix is for both Functions and App Service. See https://github.com/microsoft/vscode-azureappservice/issues/2191#issuecomment-1095676938 for the development build for App Service if you want to test it out.

**Comment by isidorn** [comment]
@alexweininger awesome, thanks for working on a fix.
Is there still some work needed on the VS Code side? Sorry if you and @deepak1556 are already in sync and I am jumping in here :)

**Comment by deepak1556** [comment]
@isidorn yup the issue has been isolated to a third-party module used by the extension whose behavior regressed with some changes to the Nodejs streams component. I have been syncing with @alexweininger offline, we can close this issue as it does not require any work from core and can be addressed on the extension side.

**Comment by alexweininger** [comment]
Fix has been released in version [v1.6.2](https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.6.2) of the Azure Functions extension. 🎉

**Comment by ebrenton** [comment]
I can confirm that deployment is now working with VS Code v1.66 and Azure Functions Extension v1.6.2.
Thank you everyone for your help.
