### ISSUE TITLE
Dragging outside of code window halts text selection update with some input devices

### ISSUE THREAD

**Issue by naftalibeder** [microsoft/vscode#146444]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.66.0 (Universal)

Steps to Reproduce:

1. Using a tablet input device, drag to select text in the content area
2. Without lifting the pen, let the drag continue outside of that area.

Expected Behavior:

- The vertical position of the drag continues to influence the selection.

Actual Behavior:

- The position of the cursor has no effect on the selection while outside of the content area.

Notes:

- As shown in the videos, this worked as expected in 1.65.2, and began to fail in 1.66.0.
- This continues to not work as expected in the Insiders build.

https://user-images.githubusercontent.com/2423291/161098679-e36b0bea-0e90-4756-9433-a43c5420b436.mov

https://user-images.githubusercontent.com/2423291/161098686-327eadf4-4069-4f19-806e-174b21665519.mov

**Comment by alexdima** [comment]
I believe this will also be fixed by https://github.com/microsoft/vscode/commit/6fd33cc509b45be16f59fd50a1993708e497b014 .

**Comment by JacksonKearl** [comment]
\closedWith 6fd33cc509b45be16f59fd50a1993708e497b014

**Comment by naftalibeder** [comment]
This now works occasionally, but not all the time.

It's pretty unpredictable - a file where it was previously working often will, on blur and refocus, stop working. Switching to a different tab, and then back to the failing tab, seems to always fix it temporarily.

**Comment by rzhao271** [comment]
Moving to the next milestone because based on the comment above, the issue still seems flaky

**Comment by naftalibeder** [comment]
@alexdima Thanks for the easy test!

> you are using a mac with a special input device which allows you to use a pen on an external tablet [...]

That's correct. I'm using a Huion HS64.

> Could you please try the following page in Chrome?

No problem. Here is a video using the trackpad:

https://user-images.githubusercontent.com/2423291/167661603-4b9f1d58-599a-4297-80ac-23c0f193f457.mov

and a video using the stylus and tablet:

https://user-images.githubusercontent.com/2423291/167661644-37081a5f-f43b-4a78-bede-89bd0743e81d.mov

Note that the above videos were taken after clicking around a few times and then clearing the console. Interestingly, on a hard refresh, I get the following error when attempting to use the stylus:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/2423291/167662092-e372e461-2c28-4704-808d-11c5bfd8bf69.png">

No such error appears when I use the trackpad. And after I've clicked the trackpad even once, the error no longer appears for the stylus, and I get the events recorded in `stylus.mov` above.

**Comment by alexdima** [comment]
@naftalibeder Could you please try out with the [latest Insiders](https://code.visualstudio.com/insiders/)?
