### ISSUE TITLE
Ctrl+Click doesn't take me to line #, only file top

### ISSUE THREAD

**Issue by gianmarcoodorizzi** [microsoft/vscode#156236]
This issue is still present in 1.69.2: https://github.com/microsoft/vscode/issues/146718

Works fine in 1.68.1.

**Comment by fabriziotrenti** [comment]
Same problem here with 1.69.2
I have noticed that ctrl+click on the error opens a new tab even though the file containing the error is already open. The new tab shows the absolute path of the file with backslash instead of slash. I don't know if this can be related to the problem.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by fabriziotrenti** [comment]
I have installed the Insiders build and in this case the ctrl+click on an error copies the filename:line:col in the "search bar" and then you have to hit enter to jump to that location. Is this the expected behaviour? In previous versions, ctrl+click directly jumps to the right place without using the "search bar"

**Comment by meganrogge** [comment]
@fabriziotrenti a gif would be helpful

**Comment by fabriziotrenti** [comment]
I have taken a screenshot where you can see the point where I ctrl+click and the quick open bar that appears at the top. You have to hit enter to jump to the highlighted file and to the right line.

![image](https://user-images.githubusercontent.com/110018124/181432983-73848277-712c-4659-99d4-07401c10916e.png)

**Comment by fabriziotrenti** [comment]
> I have taken a screenshot where you can see the point where I ctrl+click and the quick open bar that appears at the top. You have to hit enter to jump to the highlighted file and to the right line.
> 
> ![image](https://user-images.githubusercontent.com/110018124/181432983-73848277-712c-4659-99d4-07401c10916e.png)

Hi, this problem is still present even in 1.70.0.
Is anyone else experiencing this problem? Any news?
Thanks

**Comment by gyfak** [comment]
version VS CODE 1.70.2 - still reproduce!
