### ISSUE TITLE
Small issue with scss highlighting

### ISSUE THREAD

**Issue by b5414** [microsoft/vscode#157480]
Does this issue occur when all extensions are disabled?: Yes

```js
Version: 1.70.0 (user setup)
Fix: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
ОС: Windows_NT x64 10.0.19044
```

Steps to Reproduce:

1. Create scss file
2. Copy paste the code below

```css
> input:placeholder-shown + .pupa {
	background: red;
}

> input:not(:placeholder-shown) + .lupe {
	background: red;
}
```

https://imgur.com/fCRHV52

**Comment by alexr00** [comment]
I'm not able to reproduce this issue in version 1.72:

![image](https://user-images.githubusercontent.com/38270282/194071956-ce9f5acd-8fe2-4863-b74c-22b78c8144c7.png)

The issue may be caused by one of your installed extensions or it may be that it's been fixed in the mean time.

**Comment by b5414** [comment]
@alexr00 not fixed yet, try add it into `{}`

https://imgur.com/g7TpY3O

**Comment by alexr00** [comment]
@b5414 I tested again, and you're right it isn't fixed. We get our scss syntax highlighting grammar from https://github.com/atom/language-sass, but that's going to be archived. Issue for adopting a new grammar is here: https://github.com/microsoft/vscode/issues/81038
