### ISSUE TITLE
Integrated Terminal Profile (PowerShell 7) launches current working directory with extra quotation marks

### ISSUE THREAD

**Issue by andrewburgess** [microsoft/vscode#160109]
Type: <b>Bug</b>

It seems that launching a custom integrated terminal profile may wrap the `cwd` with an extra set of quotation marks. I did not notice the behavior with the baseline terminals.

### Steps to Reproduce
1. Set `terminal.integrated.shellIntegration.enabled` to `true`
2. Set integrate terminal profile settings as such (using [PowerShell 7](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?WT.mc_id=THOMASMAURER-blog-thmaure&view=powershell-7), unsure if other nonstandard terminals are impacted)
```json
{
    "terminal.integrated.profiles.windows": {
        "PowerShell 7": {
            "path": ["F:\\Program Files\\PowerShell\\7\\pwsh.exe"],
            "icon": "terminal-powershell"
        },
        "PowerShell": null,
        "Command Prompt": null,
        "Git Bash": null
    },
    "terminal.integrated.defaultProfile.windows": "PowerShell 7"
}
```
3. Open integrated terminal
4. Note that the current directory shows an extra `"`
![image](https://user-images.githubusercontent.com/79218/188028809-bbdeb9d1-48d3-4975-b9e6-606a7659e8b3.png)
5. Try to split the terminal and receive an error
![image](https://user-images.githubusercontent.com/79218/188028835-86b67412-4376-42a2-8b53-c27370d0bf82.png)

Turning on Trace logging, the following shows up in the `Pty Host` logs
```json
{
    "shellLaunchConfig": {
        "executable": "F:\\Program Files\\PowerShell\\7\\pwsh.exe",
        "icon": { "id": "terminal-powershell" },
        "color": null,
        "cwd": "\"G:\\Projects\\temp\"",
        "parentTerminalId": 1,
        "useShellEnvironment": true
    }
}
```
Note the `cwd` parameter which is wrapped in `\"`

I had also tried while running `code --disable-extensions` and had the same behavior

---

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (17.33GB free)|
|Process Argv|--crash-reporter-id 69185b9e-c8fd-4b5f-8db6-6a831fddcff2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
gitlens|eam|12.2.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|9.8.0
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.50.0
rainbow-csv|mec|2.4.0
remote-containers|ms-|0.251.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
powershell|ms-|2022.8.5
vsliveshare|ms-|1.0.5705
material-icon-theme|PKi|4.20.0
vscode-thunder-client|ran|1.18.7
code-spell-checker|str|2.7.2
vscode-icons|vsc|11.16.0
markdown-all-in-one|yzh|3.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by rs3d** [comment]
Same on my system: The CWD has extra quotation marks, when I use "Split Terminal".

```
Version: 1.72.0-insider (user setup)
Commit: 6a5e3aad96929a7d35e09ed8d22e87a72bd16ff6
Date: 2022-09-16T05:17:45.677Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes
```


![image](https://user-images.githubusercontent.com/1399149/190584373-3daa8f9f-e4e0-4582-a810-e8504da28b79.png)
Tested also with `code --disable-extensions`

**Comment by meganrogge** [comment]
@TylerLeonhardt adding you bc you made changes in this area recently

**Comment by TylerLeonhardt** [comment]
@meganrogge it's been a minute... can you refresh my memory of where you saw this?

**Comment by meganrogge** [comment]
@TylerLeonhardt no prob I will investigate it as I was heavily involved in the profiles work

**Comment by Tyriar** [comment]
I can't seem to reproduce here, but we can do a sanity check in terminalProcess and strip quotes off the cwd

**Comment by andrewburgess** [comment]
@Tyriar your PR let me dive into the dev tools to see if I could trace where the value was coming from. It seems to be set initially correctly, but then something from `xterm` calls an `EscapeSequenceParser` that then calls [_doHandleSetWindowsFriendlyCwd](https://github.com/microsoft/vscode/blob/e42cb7369715822c9922791ecf87a77e88ef7310/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L423) with the value `9;"G:\Projects\temp"` (triggered by this registered handler [here](https://github.com/microsoft/vscode/blob/e42cb7369715822c9922791ecf87a77e88ef7310/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L228)

So, not sure if maybe it's actually an XTerm issue?

**Comment by Tyriar** [comment]
@andrewburgess 👏 great investigation! Some shells send the `9;9` sequence you see there so this is that shell integration conflicting with our own.

It looks like we need to sanitize this a little better:

https://github.com/microsoft/vscode/blob/c4c4814a826b0041135140a62cf2850c02109bf6/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L431-L435

Maybe just centralizing it here: https://github.com/microsoft/vscode/blob/c4c4814a826b0041135140a62cf2850c02109bf6/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L385-L389, that way it won't ever get into the "shell launch config" to begin with. Let's track that in https://github.com/microsoft/vscode/issues/162456 as the immediate problem is resolved by the commit in this issue.

https://github.com/microsoft/vscode/issues/157570 would have also prevented this but we should sanitize the cwd better 
as above regardless.

**Comment by andrewburgess** [comment]
Glad to help! If it aids at all with debugging, this was the basis for my theme: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/blue-owl.omp.json and initialized with `oh-my-posh init pwsh --config path\to\powershell-theme.json | Invoke-Expression`

@connor4312 I just downloaded the insiders installer (v1.72.0-insider, commit: bcb6c9b7) and still see the same behavior around terminal launching/splitting
