### ISSUE TITLE
Linux build failure: Notebook Editor Integration Test

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#165149]
https://dev.azure.com/vscode/VSCode/_build/results?buildId=77644&view=logs&j=a8a6689c-5a84-59c0-482a-7dd9f21eb2d8&t=1fa6fb8d-7bb3-5acd-5778-bf99aac7f637&l=682

```
  1) Notebook Editor
       Opening a notebook should fire activeNotebook event changed only once:
     Error: Unexpected type
      at assertType (vscode-file://vscode-app/mnt/vss/_work/1/s/out/vs/base/common/types.js:67:19)
      at SimpleNotebookEditorModel.load (vscode-file://vscode-app/mnt/vss/_work/1/s/out/vs/workbench/contrib/notebook/common/notebookEditorModel.js:457:35)
      at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async NotebookModelReferenceCollection.createReferencedObject (vscode-file://vscode-app/mnt/vss/_work/1/s/out/vs/workbench/contrib/notebook/common/notebookEditorModelResolverServiceImpl.js:64:26)
      at async NotebookModelResolverServiceImpl.resolve (vscode-file://vscode-app/mnt/vss/_work/1/s/out/vs/workbench/contrib/notebook/common/notebookEditorModelResolverServiceImpl.js:184:31)
      at async MainThreadNotebookDocuments.$tryOpenNotebook (vscode-file://vscode-app/mnt/vss/_work/1/s/out/vs/workbench/api/browser/mainThreadNotebookDocuments.js:117:25)
```

**Comment by joaomoreno** [comment]
Another one: https://dev.azure.com/vscode/VSCode/_build/results?buildId=77639&view=logs&j=a8a6689c-5a84-59c0-482a-7dd9f21eb2d8&t=1fa6fb8d-7bb3-5acd-5778-bf99aac7f637&l=669

**Comment by joaomoreno** [comment]
Another one: https://dev.azure.com/vscode/VSCode/_build/results?buildId=77631&view=logs&j=a8a6689c-5a84-59c0-482a-7dd9f21eb2d8&t=1fa6fb8d-7bb3-5acd-5778-bf99aac7f637&l=681

**Comment by joaomoreno** [comment]
This is actually preventing a bunch of PRs to make it into `main`.

![image](https://user-images.githubusercontent.com/22350/199235875-78b902ca-adca-406e-829b-0b884587f34d.png)

**Comment by johanstenberg92** [comment]
hello

**Comment by joaomoreno** [comment]
Skipped this test: https://github.com/microsoft/vscode/pull/165150

**Comment by joaomoreno** [comment]
Decided to comment out the entire test suite: https://github.com/microsoft/vscode/pull/165150#issuecomment-1298481109

**Comment by rebornix** [comment]
Thanks for reverting it, this failure is what I was expecting to see but didn't realize it's so common.

Previously we often have NPE for `SimpleNotebookEditorModel.notebook` as after `load`, we guarantee the model is a `IResolvedNotebookEditorModel`. `IResolvedNotebookEditorModel#notebook` is not undefined, however our `isResolved()` check previously only checked for `Boolean(this._workingCopy);` instead of `Boolean(this._workingCopy?.model?.notebookModel);`. Not we fixed `isResolved()` condition, it starts to fail when we do the type assert

https://github.com/microsoft/vscode/blob/8b4642ab23a9b8c7fd00a37c70af545c121cc2ef/src/vs/workbench/contrib/notebook/common/notebookEditorModel.ts#L541-L542

@jrieken can you help take a look at this?

**Comment by jrieken** [comment]
@bpasero This might actually be interesting for your. AFAIK we simply call resolve on the working copy manager but working copy actually isn't resolved. This is all happening here

https://github.com/microsoft/vscode/blob/86127c6cce7f27b71b8b112d0c59cc6ab6d5f4ad/src/vs/workbench/contrib/notebook/common/notebookEditorModel.ts#L511

The working copy doc says that the model is defined once resolve is called but it seems not so (at times)

**Comment by bpasero** [comment]
Maybe running with `--verbose` in that flaky test gives more info, we print a good amount of details for what is going on in the working copy when resolving or saving:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/900690/203819410-b15e53ce-e901-4067-afa7-c4044babc9f5.png">

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/pull/167212 brings the tests back and sets verbose logging for the failing one (I am not sure why the entire suite was disabled).

There is cases where `manager.resolve` can return early and maybe that happens here in this case. For example, when the a disposed working copy is resolved:

https://github.com/microsoft/vscode/blob/557a681736653fb5228db6ecf72b66bef65cf4b5/src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts#L411-L415

Or when providing contents for resolving but the working copy is dirty with user changes:

https://github.com/microsoft/vscode/blob/557a681736653fb5228db6ecf72b66bef65cf4b5/src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts#L420-L424

Anyway, any of these cases should appear in the logs now with verbose logging enabled.

**Comment by bpasero** [comment]
Does not seem to fail anymore

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/900690/205838653-9628cbb9-674f-4a69-9a44-7336e36a39b5.png">
