### ISSUE TITLE
Snippet with `TM_SELECTED_TEXT` does not work well

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [microsoft/vscode#165746]
This problem still occurs even if you disable all extensions. This problem was confirmed in Markdown file.

## To reproduce

1. Create a snippet containing `TM_SELECTED_TEXT`

    like below:

    ```json
    "TM_SELECTED_TEXT": {
      "prefix": "tm_selected_text",
      "body": "the original ${1:$TM_SELECTED_TEXT} is gone.",
      "description": "Snippet included TM_SELECTED_TEXT"
    },
    ```

1. Use the snippet made in 1

![tmSelectedText](https://user-images.githubusercontent.com/75878492/200402231-423e3728-cc3a-493d-b62f-c3bf20bf189b.gif)

## Version

- Windows 11
- VS Code

    ```
    Version  : 1.73.0 (user setup)
    Commit   : 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
    Date     : 2022-11-01T15: 34: 06.111Z
    Electron : 19.0.17
    Chromium : 102.0.5005.167
    Node.js  : 16.14.2
    V8       : 10.2.154.15-electron.0
    OS       : Windows_NT x64 10.0.22000
    Sandboxed: No
    ```

**Comment by Yarakashi-Kikohshi** [comment]
I also checked the Insider version. As in the Stable, `TM_SELECTED_TEXT` didn't work well.

In addition, the Insider version didn't show snippet suggestions. It was displayed by pressing `Ctrl+Space`.

``` 
Version  : 1.74.0-insider (user setup)
Commit   : 2282be522a8031209a739783baede67bfa9fc95a
Date     : 2022-11-08T05: 23: 21.062Z
Electron : 19.1.3
Chromium : 102.0.5005.167
Node.js  : 16.14.2
V8       : 10.2.154.15-electron.0
OS       : Windows_NT x64 10.0.22000
Sandboxed: Yes
```

**Comment by stramin** [comment]
I would like to say, `TM_SELECTED_TEXT` was working the past week, so this issue is recent.

**Comment by Yarakashi-Kikohshi** [comment]
@jrieken 

> You need to use "F1 > Insert Snippet", "F1 > Surround With Snippet", or the surround with quick fix (from the light bulb) for this

I know the functions of `Insert Snippet` and `Surround With Snippet`. However, until now, simply selecting a snippet displayed in the suggestions would insert the selected text at the specified location by `TM_SELECTED_TEXT`.

Is there no longer a way to use snippets as before?

**Comment by jrieken** [comment]
this is a regression from https://github.com/microsoft/vscode/commit/1e662b070fd9f847dfefbdf3f45d0fe538d7e974

**Comment by Yarakashi-Kikohshi** [comment]
Thank you for reopening this issue.  Sorry for the confusion caused by my poor explanation of this issue.

>-  have the echo-snippet provided above
> - in the editor have ddd and select it all
> - type ech, see and accept the snippet suggestion
> - 🐛 only echo is inserted, not echo ddd

The problem presented by this procedure is the very issue I have raised.

**Comment by marcacyr** [comment]
Glad this is opened. Following this one. Hopefully this is resolved quickly.

**Comment by jrieken** [comment]
fixed via https://github.com/microsoft/vscode/pull/165871

**Comment by mreduar** [comment]
> fixed via #165871

Do I have to use the insiders version to test these changes?

**Comment by emremutlu08** [comment]
Still, $TM_SELECTED_TEXT does not work!

**Comment by jlelong** [comment]
It seems there is still something wrong with version 1.74.0.
Consider the following snippet and register it for `plaintext`, `markdown` and `latex` (without LaTeX-Workshop enabled)

```json
	"poo": {
		"prefix": "pair",
		"body": "xx((${0:$TM_SELECTED_TEXT}))xx"
	}
```

Select `some text` and type pair with quick suggestions enabled. Observe that
1. in `.txt` files, `some text` is replaced by `xx((some text))xx` as expected
2. in `.md` or `.tex` files, `some replaced` is replaced by `xx(())xx`.

I can open a new issue if you prefer.

**Comment by Yarakashi-Kikohshi** [comment]
I've found patterns where `$TM_SELECTED_TEXT` doesn't work well. This problem still occurs even if you disable all extensions. And this was confirmed in markdown file.

However, the problem does not reproduce all the time, but occasionally. So sorry I couldn't create a GIF image because the problem doesn't reproduce all the time. However, it is quite irritating when encountered.

1. Create a snippet like this:
    ```json
    {
      "fooBar": {
        "prefix": "foobar",
        "body": "foo${1:$TM_SELECTED_TEXT}bar",
        "description": "fooBar"
      }
    }
    ```
1. Select multiple lines of text containing the string contained in `"body"`. (It works fine if it's just single line)
    - Select whether the string inserted by the snippet adjacents the original string or has only one newline between them.
    ```markdown
    foo bar
    foo bar
    foo bar
    ```
1. Use the snippet. The following results are obtained.
    ```markdown
    foobar
    ```

On the other hands, When using snippets for text such as the following, it was not possible to confirm the behavior that does not work well.

```markdown
baz
foo bar
baz
foo bar
baz
```

### my impressions of the problems

I feel that `$TM_SELECTED_TEXT` does not work well when memory is overloaded... I felt that it was reproduced more often when the extensions was enabled than when all the extensions were disabled.

Additionally, even if once this problem occurs, using `Ctrl+Z` to undo and then using the snippet again works fine.

Sorry for the unclear report.

### Stable version

```version
Version  : 1.74.0 (user setup)
Commit   : 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date     : 2022-12-05T16:38:16.075Z
Electron : 19.1.8
Chromium : 102.0.5005.167
Node.js  : 16.14.2
V8       : 10.2.154.15-electron.0
OS       : Windows_NT x64 10.0.22621
Sandboxed: No
```

**Comment by emremutlu08** [comment]
Now it works for me.

Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by ollalla** [comment]
This is still not working in *.txt, *.md, *.js, *.ts, and *.json files. Works in *.html, *.xml, including *.config, files though.

Version: 1.74.1 (user setup)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:30:51.966Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No
