### ISSUE TITLE
VSCode is sluggish and buggy on Fedora 37 with wayland + Nvidia drivers

### ISSUE THREAD

**Issue by LukaHietala** [microsoft/vscode#169504]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
1.74.1/Insider
- OS Version: 
Fedora 37
- Additional information

| **item**  | **value** |
| ------------- | ------------- |
| Processor        | AMD Ryzen™ 5 5600X × 12                             |
| GPU              | NVIDIA GeForce GTX 1660 Ti; Driver version 525.60.11 |
| GNOME Version    | 43                                                  |
| Windowing system | Wayland                                             |
| OS type          | 64 bit                                              |
| Memory           | 32 GB                                               | 

Similar issue #134255 (closed and didn't solve my issue)

VSCode stable and insider versions are sometimes unresponsive and buggy on my system when I am using Wayland with NVIDIA drivers on Fedora OS. This happens usually when I am typing on a input fields or hovering over buttons. I have tried to find a solutions to this problem like:

- Enabling Vulkan (`--enable-features=Vulkan`) (**doesn't work**)
- Disabling GPU (`--disable-gpu`) (**doesn't work**)
- Switching temporarily to Xorg (**works**)

Full list of problems (What i have noticed so there might be more problems): 

- VSCode window flickers sometimes (black)
- Buttons not always responsive
- Typing on input fields is buggy

Errors (`code --verbose`):

- `'[9130:1218/182922.095257:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.`
- `libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`
- `MESA-LOADER: failed to retrieve device information`
- `MESA-LOADER: failed to open nvidia-drm: /usr/lib64/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri)`
- `failed to load driver: nvidia-drm`
- `MESA-LOADER: failed to open zink: /usr/lib64/dri/zink_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri)`
- `failed to load driver: zink`
- `MESA-LOADER: failed to open kms_swrast: /usr/lib64/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri)`
- `failed to load driver: kms_swrast`
- `MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri)`
- `failed to load swrast driver`

All of those errors come on Wayland, not on Xorg.

Steps to Reproduce:

1. Open VSCode 1.74.1 or VSCode Insider on Fedora 37 with Wayland/NVIDIA

**Comment by LukaHietala** [comment]
I am not sure that is this a problem with Electron or Wayland with Nvidia drivers.

**Comment by LukaHietala** [comment]
I use Chromium as my primary web browser and that works just fine.

**Comment by deepak1556** [comment]
Can you confirm if you are launching the application with `--ozone-platform="wayland" --enable-features="WaylandWindowDecorations"` ?

**Comment by LukaHietala** [comment]
> Can you confirm if you are launching the application with `--ozone-platform="wayland" --enable-features="WaylandWindowDecorations"` ?

Yes, I have tried that and the errors still remain.

**Comment by PleahMaCaka** [comment]
I am seeing the same logs, that logs occurs when running an all of electron app in wayland environment. Other Electron based programs like Discord have same issue for a long time. I think the only way is to pray that it will be resolved.

and I use Arch + Wayland and it outputs the same log but no problem at all.

**Comment by LukaHietala** [comment]
> I am seeing the same logs, that logs occurs when running an all of electron app in wayland environment, and I use Arch + Wayland and it outputs the same log but no problem at all then I think maybe VSCode is slow because of other issue

Yeah, it appears that the issue exist outside of VSCode and likely is related to Electron, which is why this issue has been labeled as an upstream issue.

**Comment by deepak1556** [comment]
@LukaHietala can you check if the issue persists with our [exploration builds](https://az764295.vo.msecnd.net/exploration/68c9758ab2187969747dbcdd18c24bb15a0b42c7/code-exploration-1.75.0-1674141075.el7.x86_64.rpm) that comes with a newer runtime. Thanks!

**Comment by LukaHietala** [comment]
> @LukaHietala can you check if the issue persists with our [exploration builds](https://az764295.vo.msecnd.net/exploration/68c9758ab2187969747dbcdd18c24bb15a0b42c7/code-exploration-1.75.0-1674141075.el7.x86_64.rpm) that comes with a newer runtime. Thanks!

It was WAY more buggier, it was hard to even run the `code --verbose` command.

- Constant flickering
- Crashed once

<details>
<summary>Errors</summary>
```
[6000:0124/213313.259547:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[main 2023-01-24T19:33:13.314Z] [File Watcher (node.js)] Request to start watching: /home/lukahietala/.config/Code/User (excludes: <none>, includes: <all>),/home/lukahietala/.config/Code/User/settings.json (excludes: <none>, includes: <all>)
[main 2023-01-24T19:33:13.320Z] Sending env to running instance...
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[main 2023-01-24T19:33:13.321Z] [File Watcher (node.js)] Started watching: '/home/lukahietala/.config/Code/User'
[main 2023-01-24T19:33:13.321Z] [File Watcher (node.js)] Started watching: '/home/lukahietala/.config/Code/User/settings.json'
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nvidia-drm: /usr/lib64/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: nvidia-drm
MESA-LOADER: failed to open zink: /usr/lib64/dri/zink_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: zink
MESA-LOADER: failed to open kms_swrast: /usr/lib64/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri)
failed to load swrast driver
[main 2023-01-24T19:33:13.356Z] Sent env to running instance. Terminating...
[main 2023-01-24T19:33:13.357Z] Lifecycle#kill()
[main 2023-01-24T19:33:13.357Z] Lifecycle#onWillShutdown.fire()
```
</details>

**Comment by deepak1556** [comment]
There are still issue with loading the dri files, can you check the permission of these files ? Also, try launching with `--disable-gpu-sandbox --ozone-platform=wayland` and see if it helps.

```
failed to open nvidia-drm: /usr/lib64/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri) 
failed to load driver: nvidia-drm MESA-LOADER: failed to open zink: /usr/lib64/dri/zink_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri) 
failed to load driver: zink MESA-LOADER: failed to open kms_swrast: /usr/lib64/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri) 
failed to load driver: kms_swrast MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib64/dri, suffix _dri)
```

You seem to be hitting the same issue as https://bugs.chromium.org/p/chromium/issues/detail?id=1378258

**Comment by LukaHietala** [comment]
The command you provided worked, but did not solve the issue and I also checked permission of nvidia drm files and they are root level things.

![image](https://user-images.githubusercontent.com/95122845/214554840-38f4a844-e8ff-4d48-a07e-9db6a54d90fb.png)

But it's weird that they work on X11 and not on Wayland even though the permissions are the same

**Comment by valentin-cnt** [comment]
I have the same configution except I use Fedora Silverblue 37, and I run vscode in a toolbox. 
But I have often the same problem, vscode tends to be unresponsive sometimes and the screen is flickering in black too.

Without the `--enable-features=UseOzonePlatform --ozone-platform=wayland` arugs I just have a white page.
With them, everything is fine but still with the problems mentioned before.

**Comment by deepak1556** [comment]
There is not much we can do here given this is an issue in the runtime, you can use the Xwayland workaround mentioned in upstream to use `--ozone-platform=X11`

**Comment by LukaHietala** [comment]
> I have the same configution except I use Fedora Silverblue 37, and I run vscode in a toolbox. But I have often the same problem, vscode tends to be unresponsive sometimes and the screen is flickering in black too.
> 
> Without the `--enable-features=UseOzonePlatform --ozone-platform=wayland` args I just have a white window. With them, everything is fine but still with the problems mentioned before.
> 
> Adding `--disable-gpu-sandbox` makes vscode freeze when I want to quit it with the messabe _Disabling backups_
> 
> I can provide logs if needed

Yeah, when I was testing the permissions and stuff and enabled `disabled-gpu-sandbox` I got the same issue with closing VSCode windows

**Comment by onkoe** [comment]
Also having this problem on VSCode on Fedora 37 Wayland on two different laptops. One has an Intel Core 7k chip, where the problem is fixed by disabling Wayland launch flags. The other has a modern AMD Ryzen 6k chip, which has the problems no matter what when running on a Wayland display server. Neither of these machines have dedicated graphics. 

For some reason, I'm not experiencing the problem on my MacBook Pro M1 Pro on Fedora 37 Wayland (w/ Asahi kernel). Which definitely SHOULD break first, but whatever... :face_exhaling: 

Is anyone else facing these problems on these non-NVIDIA machines too?

**Comment by ex1tium** [comment]
I noticed that flickering started when the window wasn't in focus. My problem fixed with `--enable-features=UseOzonePlatform --ozone-platform=wayland` or at least greatly reduced. KDE Plasma 5.26.5, NVIDIA Drivers 525.85.05.

**Comment by ivanvmoreno** [comment]
Similar experience on Fedora 38, using propietary Nvidia drivers (`530.41.03`). Using `--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland` I don't experience unrendered frames nor flickering - and with the `WaylandWindowDecorations` feature the window top bar is displayed. However, bear in mind that font scaling is not being applied after applying this feature flags.

**Comment by mikajed** [comment]
I am experiencing all of the above on my Arch Linux machine with GNOME + Wayland + Nvidia.
But also the writing in the editor feels laggy and slow, the scrolling is acting weird too.

**Comment by nighthink** [comment]
Similar experience on Fedora 38. The nvidia driver is from RPM.

**Comment by juahan** [comment]
> 

Most annoyances were solved for me with those commands. I had menus that were black and only when putting mouse on top of the menu items, the items became visible. Also I had bad and very annoying lag in the file tree, for example when renaming files. Both of these issues are now gone, at least with quick testing.

The permission denied items are still in verbose log. Also, with the start parameters I also get the below warnings.

Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.

Running with Fedora 38, Nvidia driver version 535.54.03 (GTX 1660 Ti).

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.3.8-200.fc38.x86_64

**Comment by abique** [comment]
I have the same problems with nvidia + gnome + wayland on archlinux (up to date).
No `code-flags.conf`.

**Comment by abique** [comment]
The issue is very likely an electron issue right?
There is probably a similar issue on electron bug tracker.

**Comment by LukaHietala** [comment]
> The issue is very likely an electron issue right? There is probably a similar issue on electron bug 

https://bugs.chromium.org/p/chromium/issues/detail?id=1378258

**Comment by SimonMaracine** [comment]
I have similar experiences as well on Fedora 38 with Wayland, since I installed the Nvidia drivers.

**Comment by pacificera** [comment]
Same issue on nixos + wayland + nvidia 535.86.05

**Comment by mikajed** [comment]
> Yep, got the same issues, jumpy cursor, laggy scrolling, black menu bars. All under Wayland on Fedora 38 with Nvidia GTX1650, proprietary 535 akmod driver.

For the laggy scrolling I enabled Smooth Scrolling and for the black menu bars I changed the Title Bar Style to custom.

**Comment by istadem2077** [comment]
> > Yep, got the same issues, jumpy cursor, laggy scrolling, black menu bars. All under Wayland on Fedora 38 with Nvidia GTX1650, proprietary 535 akmod driver.
> 
> For the laggy scrolling I enabled Smooth Scrolling and for the black menu bars I changed the Title Bar Style to custom.

I also get laggy editing. Like when cursor is beside parentheses, when I get away or come back they kinda flash.

**Comment by mikajed** [comment]
> > > Yep, got the same issues, jumpy cursor, laggy scrolling, black menu bars. All under Wayland on Fedora 38 with Nvidia GTX1650, proprietary 535 akmod driver.
> > 
> > 
> > For the laggy scrolling I enabled Smooth Scrolling and for the black menu bars I changed the Title Bar Style to custom.
> 
> I also get laggy editing. Like when cursor is beside parentheses, when I get away or come back they kinda flash.

Yes, me too. This is I couldn't fix. It's not good on Wayland.

**Comment by milden6** [comment]
I have the same issue. Fedora 38, Wayland, RTX4070Ti. Driver 535.86.05. Kernel 6.4.6

**Comment by istadem2077** [comment]
Interestingly, this issue doesn't occur on Ubuntu 22.04 under Wayland, neither in snap not in deb versions. Driver still 535. Dunno about other distros tho.

**Comment by JoelHBierman** [comment]
What I have tried using vscode on and did not have this problem:

1. NixOS with Wayland + Nvidia
2. Linux Mint running Gnome + Wayland
3. Pop!_OS (with X11)
4. Fedora 36,37,38 with X11
5. M1 MacBook Pro running Asahi Fedora Remix + Wayland
6. Virtual machines of several distributions, including Fedora.

What I have experienced this problem on:

1. Fedora 36,37,38 with Wayland + Nvidia.


I also experience similar issues with other electron apps such as Slack, Obsidian, and Discord. No other apps have this issue. It seems like Electron + Wayland + Nvidia drivers from Fedora repositories is a bad combination. I will be trying this with AMD graphics in the coming days so I can find out if this is specific to Nvidia in the coming days.

**Comment by milden6** [comment]
> What I have tried using vscode on and did not have this problem:
> 
>     1. NixOS with Wayland + Nvidia
> 
>     2. Linux Mint running Gnome + Wayland
> 
>     3. Linux Mint with Cinnamon + X11
> 
>     4. Pop!_OS (with X11)
> 
>     5. Fedora 36,37,38 with X11
> 
>     6. M1 MacBook Pro running Asahi Fedora Remix + Wayland
> 
>     7. Virtual machines of several distributions, including Fedora.
> 
> 
> What I have experienced this problem on:
> 
>     1. Fedora 36,37,38 with Wayland + Nvidia.
> 
> 
> I also experience similar issues with other electron apps such as Slack, Obsidian, and Discord. No other apps have this issue. It seems like Electron + Wayland + Nvidia drivers from Fedora repositories is a bad combination; so much so that virtual machines and drivers written from scratch by the Asahi Linux team perform better than the Nvidia drivers from Fedora repositories. I will be trying this with AMD graphics in the coming days so I can find out if this is specific to Nvidia.

@JoelHBierman Hi! Sounds interesting. Do I understand correctly that combination Electron App + Wayland + Nvidia drivers from official site should work fine on Fedora 38?

**Comment by JoelHBierman** [comment]
@milden6 Fedora + Electron + Wayland + nvidia will run but in my experience it is bad enough of an experience to be unusable. This is the only combination where I have experienced this issue. Switching to X11 on Fedora works fine. I also recall turning down the display resolution (mine runs natively at 4K) mitigates this issue somewhat. I swapped out my Nvidia GPU for an AMD one and it works flawlessly. I don’t know what it is about the nvidia drivers on Fedora.

**Comment by istadem2077** [comment]
ok, i dont know how, but after install chromium package(i use it for selenium), the problem dissapeared at all. Idk how, i was using Code in Xorg, doing my work. Then I relogged in Wayland session. Opened VSCode, and the was no such issue anymore. No text highlight flickering, no choppy scrolling, no text editor lagging, no black boxes instead of context menus(i do use custom headerbar tho).

I have no flags, neither in config file, nor in .desktop file. 

If anybody can try to reproduce, try installing chromium and chromium-common(not sure if chromedriver is necessary tho). Idk really what happened...

**Comment by milden6** [comment]
> ok, i dont know how, but after install chromium package(i use it for selenium), the problem dissapeared at all. Idk how, i was using Code in Xorg, doing my work. Then I relogged in Wayland session. Opened VSCode, and the was no such issue anymore. No text highlight flickering, no choppy scrolling, no text editor lagging, no black boxes instead of context menus(i do use custom headerbar tho).
> 
> I have no flags, neither in config file, nor in .desktop file.
> 
> If anybody can try to reproduce, try installing chromium and chromium-common(not sure if chromedriver is necessary tho). Idk really what happened...

@istadem2077 I have installed chromium and relogged in Wayland session, but I have the same issue. What your driver version, kernel and display resolution?

![image](https://github.com/microsoft/vscode/assets/39964648/f6828e80-42f5-4910-bba7-91c8c5e9276e)

**Comment by istadem2077** [comment]
> > ok, i dont know how, but after install chromium package(i use it for selenium), the problem dissapeared at all. Idk how, i was using Code in Xorg, doing my work. Then I relogged in Wayland session. Opened VSCode, and the was no such issue anymore. No text highlight flickering, no choppy scrolling, no text editor lagging, no black boxes instead of context menus(i do use custom headerbar tho).
> > I have no flags, neither in config file, nor in .desktop file.
> > If anybody can try to reproduce, try installing chromium and chromium-common(not sure if chromedriver is necessary tho). Idk really what happened...
> 
> @istadem2077 I have installed chromium and relogged in Wayland session, but I have the same issue. What your driver version, kernel and display resolution?
> 
> ![image](https://user-images.githubusercontent.com/39964648/260932101-f6828e80-42f5-4910-bba7-91c8c5e9276e.png)

Kernel 6.4.6, driver akmod-nvidia-535, 1920x1080 display.

**Comment by deepak1556** [comment]
The upstream issue has been fixed in 113, can you users give the latest insiders a try https://code.visualstudio.com/insiders which is based on Chromium 114 and see if the issue persists.

**Comment by istadem2077** [comment]
> The upstream issue has been fixed in 113, can you users give the latest insiders a try https://code.visualstudio.com/insiders which is based on Chromium 114 and see if the issue persists.

unfortunately issues are still there. Black boxes instead of context menus, laggy editor, flickery highlight, and choppy scrolling. Idk. Well, the issues also came back to VSCode Stable...

**Comment by istadem2077** [comment]
Upd. 1.81. Added `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags. Works well, though idk if that's update's feature, or the fact that I'm on KDE.

**Comment by mikajed** [comment]
> Upd. 1.81. Added `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags.

I thought the flags were there all the time and not only in this update, or am I wrong?

**Comment by istadem2077** [comment]
> > Upd. 1.81. Added `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags.
> 
> I thought the flags were there all the time and not only in this update, or am I wrong?

Sorry, I'm afraid there can be misunderstanding between us. VSCode does not enable these flags by default. And did not add this for a long time.

**Comment by mikajed** [comment]
> > > Upd. 1.81. Added `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags.
> > 
> > 
> > I thought the flags were there all the time and not only in this update, or am I wrong?
> 
> Sorry, I'm afraid there can be misunderstanding between us. VSCode does not enable these flags by default. And did not add this for a long time.

Hmm? Those flags are known for a very long time.

**Comment by istadem2077** [comment]
> > > > Upd. 1.81. Added `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags.
> > > 
> > > 
> > > I thought the flags were there all the time and not only in this update, or am I wrong?
> > 
> > Sorry, I'm afraid there can be misunderstanding between us. VSCode does not enable these flags by default. And did not add this for a long time.
> 
> Hmm? Those flags are known for a very long time.

Yes of course, but for some reason it worked now. Again misunderstanding ig. I meant I didn't add these flags. Ofc VSCode had those flag for quite some time.

**Comment by rossanodr** [comment]
> > > > > Upd. 1.81. Added `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags.
> > > > 
> > > > 
> > > > I thought the flags were there all the time and not only in this update, or am I wrong?
> > > 
> > > 
> > > Sorry, I'm afraid there can be misunderstanding between us. VSCode does not enable these flags by default. And did not add this for a long time.
> > 
> > 
> > Hmm? Those flags are known for a very long time.
> 
> Yes of course, but for some reason it worked now. Again misunderstanding ig. I meant I didn't add these flags. Ofc VSCode had those flag for quite some time.

Can you tell me how to add these flags ? I'm new to fedora

**Comment by istadem2077** [comment]
> > > > > > Upd. 1.81. Added `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags.
> > > > > 
> > > > > 
> > > > > I thought the flags were there all the time and not only in this update, or am I wrong?
> > > > 
> > > > 
> > > > Sorry, I'm afraid there can be misunderstanding between us. VSCode does not enable these flags by default. And did not add this for a long time.
> > > 
> > > 
> > > Hmm? Those flags are known for a very long time.
> > 
> > Yes of course, but for some reason it worked now. Again misunderstanding ig. I meant I didn't add these flags. Ofc VSCode had those flag for quite some time.
> 
> Can you tell me how to add these flags ? I'm new to fedora

From `/usr/local/share/applications/`(it might actually be `/usr/share/applications/`) copy `code.desktop` to `~/.local/share/applications/` and append these flags at the end of line which starts with `Exec`.

**Comment by theIDinside** [comment]
I've struggled with this for months on end (years? probably) with no result.

On Fedora 38, I seem to get it working finally with

code --ozone-platform="wayland" --enable-features="WaylandWindowDecorations"

It _seems_ to be responsive for now and no black pop ups.

**Comment by matihope** [comment]
For anybody wondering if the issue has been fixed by the latest nvidia driver version 545, that supposedly fixes many Wayland-related issues... - no, it hasn't been fixed. Still laggy and unrendered frames.

---

Nvidia Driver Version: 545.29.02

Version: 1.84.1
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:35:31.181Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.9-arch2-1

**Comment by istadem2077** [comment]
> For anybody wondering if these issues have been fixed by the latest nvidia driver version 545, that supposedly fixes many Wayland-related issues... - no, not much has been fixed. Still laggy and unrendered frames.
> 
> Nvidia Driver Version: 545.29.02
> 
> VSCode:
> 
> Version: 1.84.1 Commit: [2b35e1e](https://github.com/microsoft/vscode/commit/2b35e1e6d88f1ce073683991d1eff5284a32690f) Date: 2023-11-06T12:35:31.181Z Electron: 25.9.2 ElectronBuildId: 24603566 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Linux x64 6.5.9-arch2-1

I guess that's Chromium/Electron problem, not Nvidia, interesting enough, I did not discover this issue on Ubuntu. Haven't tried other distributions though, on Fedora KDE issue also exists

**Comment by mikajed** [comment]
> > For anybody wondering if these issues have been fixed by the latest nvidia driver version 545, that supposedly fixes many Wayland-related issues... - no, not much has been fixed. Still laggy and unrendered frames.
> > Nvidia Driver Version: 545.29.02
> > VSCode:
> > Version: 1.84.1 Commit: [2b35e1e](https://github.com/microsoft/vscode/commit/2b35e1e6d88f1ce073683991d1eff5284a32690f) Date: 2023-11-06T12:35:31.181Z Electron: 25.9.2 ElectronBuildId: 24603566 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Linux x64 6.5.9-arch2-1
> 
> I guess that's Chromium/Electron problem, not Nvidia, interesting enough, I did not discover this issue on Ubuntu. Haven't tried other distributions though, on Fedora KDE issue also exists

Yeah this is what I have found about this: https://stackoverflow.com/questions/77100725/why-am-i-getting-rendering-issues-with-vs-code-1-82-1-84

**Comment by abique** [comment]
vscode is literally unusable on Gnome/Wayland/Nvidia/Archlinux.
It flickers like a disco ball.

gnome 45.0-1
code 1.84.2-1
nvidia 545.29.06-2

**Comment by abique** [comment]
Actually if I disable the gpu rendering, then it is OK.

**Comment by GuaiGuaiOnMyComputer** [comment]
I'm using Fedora 38 KDE Plasma desktop environment with Wayland windowing system. GPU model is RTX-3060-LHR and driver version is 545.29.06. If I launch vscode from terminal with
> code --disable-gpu

everything works fine. But without the ```disable-gpu``` flag, vscode flickers and starts dancing.

**Comment by gremo** [comment]
Same problem here:

Fedora 39
Wayland
NVIDIA RTX 4070 with 535 RPM fusion driver


`code --disable-gpu` partially solve the problem (but still getting some flickers in the title bar, changing files)

**Comment by deepak1556** [comment]
Based on the recent comments there is a mix of users who have the issue resolved and others still facing the issue. Can users still facing the issue, confirm that they are running the wayland backend by passing the flag `--ozone-platform=wayland` and also try it with latest insiders https://code.visualstudio.com/insiders, `code-insiders --ozone-platform=wayland`

**Comment by mikajed** [comment]
> Based on the recent comments there is a mix of users who have the issue resolved and others still facing the issue. Can users still facing the issue, confirm that they are running the wayland backend by passing the flag `--ozone-platform=wayland` and also try it with latest insiders https://code.visualstudio.com/insiders, `code-insiders --ozone-platform=wayland`

Yep, all I did was creating a `code-flags.conf` file in my .config folder with this inside (and code - oss works perfect again):
```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```

**Comment by GuaiGuaiOnMyComputer** [comment]
> Based on the recent comments there is a mix of users who have the issue resolved and others still facing the issue. Can users still facing the issue, confirm that they are running the wayland backend by passing the flag `--ozone-platform=wayland` and also try it with latest insiders https://code.visualstudio.com/insiders, `code-insiders --ozone-platform=wayland`

Fixed the problem by doing what @mikajed said, adding the ```code-flags.conf``` file under ```~/.config/```. Im using vscode version 1.85.1 with an Nvidia GPU and Wayland.

**Comment by nlavalle** [comment]
> Based on the recent comments there is a mix of users who have the issue resolved and others still facing the issue. Can users still facing the issue, confirm that they are running the wayland backend by passing the flag `--ozone-platform=wayland` and also try it with latest insiders https://code.visualstudio.com/insiders, `code-insiders --ozone-platform=wayland`

I'm on a fresh install of Fedora 39 workstation running an Nvidia 3060 with wayland, the code-flags.conf didn't seem to work for me, running `code --ozone-platform=wayland` I get a `Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.` and see spinning but then it seems to die out, no notifications. Running `code-insiders --ozone-platform=wayland` returns the same message but loads code insiders and doesn't appear to have the buggy issue.

Happy to try other steps if you'd like.

**Comment by GuaiGuaiOnMyComputer** [comment]
@nlavalle 
> I'm on a fresh install of Fedora 39 workstation running an Nvidia 3060 with wayland, the code-flags.conf didn't seem to work for me, running code --ozone-platform=wayland I get a Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium. and see spinning but then it seems to die out, no notifications. Running code-insiders --ozone-platform=wayland returns the same message but loads code insiders and doesn't appear to have the buggy issue.

I'm guessing you're launching vscode from the terminal by ```code --ozone-platform=wayland``` , resulting in the warning message.
You should create a file in ```~/.config/code-flags.conf```, and write the two lines 
```
--enable-features=UseOzonePlatform
--OzonePlatform=wayland
```
into it.

**Comment by mikajed** [comment]
> > Based on the recent comments there is a mix of users who have the issue resolved and others still facing the issue. Can users still facing the issue, confirm that they are running the wayland backend by passing the flag `--ozone-platform=wayland` and also try it with latest insiders https://code.visualstudio.com/insiders, `code-insiders --ozone-platform=wayland`
> 
> I'm on a fresh install of Fedora 39 workstation running an Nvidia 3060 with wayland, the code-flags.conf didn't seem to work for me, running `code --ozone-platform=wayland` I get a `Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.` and see spinning but then it seems to die out, no notifications. Running `code-insiders --ozone-platform=wayland` returns the same message but loads code insiders and doesn't appear to have the buggy issue.
> 
> Happy to try other steps if you'd like.

You could also try to 
```
"window.titleBarStyle": "custom",
"editor.smoothScrolling": true
```
additional to the `~/.config/code-flags.conf`

**Comment by unkemptArc99** [comment]
Similar experience here. My OS details -
```
❯ cat /etc/os-release
NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```
GPU - NVIDIA GeForce RTX 3050Ti
CPU - AMD Ryzen 7 5800H

```
❯ code --status
Version:          Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:19.222Z)
OS Version:       Linux x64 6.6.13-200.fc39.x86_64
CPUs:             AMD Ryzen 7 5800H with Radeon Graphics (16 x 4441)
Memory (System):  15.47GB (9.15GB free)
Load (avg):       0, 0, 0
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox --force-user-env --unity-launch --crash-reporter-id 7f67fdcf-795b-457a-8ce5-7d2c2305e456
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               disabled_off
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  video_decode:                           enabled
                  video_encode:                           disabled_software
                  vulkan:                                 disabled_off
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 disabled_off

CPU %	Mem MB	   PID	Process
    0	   174	 14200	code main
    0	    32	 14204	   zygote
    0	    32	 14205	   zygote
    6	   269	 14266	window [1] (Welcome - Visual Studio Code)
    0	   127	 14236	   gpu-process
    0	    63	 14244	   utility-network-service
    0	   111	 14356	shared-process
    0	    79	 14357	fileWatcher [1]
    0	   174	 14383	extensionHost [1]
    0	    63	 14544	     electron-nodejs (/var/lib/snapd/snap/code/149/usr/share/code/code --ms-enable-electron-run-as-node /var/lib/snapd/snap/code/149/usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=14383)
    0	    79	 14411	ptyHost
    0	     0	 14552	     /usr/bin/zsh -i
```

Tried to add the options - 
```
--enable-features=UseOzonePlatform
--OzonePlatform=wayland
```
But still facing the same issue.

**Comment by nlavalle** [comment]
> @nlavalle
> 
> I'm guessing you're launching vscode from the terminal by `code --ozone-platform=wayland` , resulting in the warning message. You should create a file in `~/.config/code-flags.conf`, and write the two lines
> 
> ```
> --enable-features=UseOzonePlatform
> --OzonePlatform=wayland
> ```
> 
> into it.

That was what I tried, I added the terminal warning message in case that'd help with troubleshooting. Those two lines in the ~/.config/code-flags.conf don't resolve the issue for me.

> You could also try to
> 
> "window.titleBarStyle": "custom",
> "editor.smoothScrolling": true
> 
> additional to the ~/.config/code-flags.conf

No luck with this either.

**Comment by GuaiGuaiOnMyComputer** [comment]
> @nlavalle
> 
> > I'm on a fresh install of Fedora 39 workstation running an Nvidia 3060 with wayland, the code-flags.conf didn't seem to work for me, running code --ozone-platform=wayland I get a Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium. and see spinning but then it seems to die out, no notifications. Running code-insiders --ozone-platform=wayland returns the same message but loads code insiders and doesn't appear to have the buggy issue.
> 
> I'm guessing you're launching vscode from the terminal by `code --ozone-platform=wayland` , resulting in the warning message. You should create a file in `~/.config/code-flags.conf`, and write the two lines
> 
> ```
> --enable-features=UseOzonePlatform
> --OzonePlatform=wayland
> ```
> 
> into it.

Weird.... After reinstalling vscode through dnf, this method no longer work for me. So for now, I just disable hardware acceleration by ```ctrl+shift+p preference:configure runtime arguments```, and uncomment the line
> "disable-hardware-acceleration": true,

**Comment by larspontoppidan** [comment]
I faced this problem on a fresh KDE Neon (Plasma 6.0.2) install on an AMD platform with an NVIDIA GPU (driver version: 535.161.07). I tried the latest regular code (version: 1.87.2) with various combinations of parameters and nothing fully fixed the black flickering and the jumpiness to the view port and cursor when scrolling.

All the issues went away for me by running the latest code-insider version from the Microsoft PPA (version: 1.88.0-1711043310) with the flags: ` --enable-features=UseOzonePlatform --ozone-platform=wayland`. Like that it works flawlessly and responsively. Frankly, it's the smoothest vscode experience I've had so far.

I wasn't sure how to pass those parameters permanently to code-insiders. The `~/.config/code-flags.conf` file didn't seem to work. What I did instead was to edit the `code-insiders.desktop` launcher so the flags are in the arguments and to make a shell alias (in `~/.bashrc`) like this:

`alias code='code-insiders --enable-features=UseOzonePlatform --ozone-platform=wayland'`

Only slight annoyance is that it prints the `Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.` every time code is started from the terminal.

**Comment by rzippo** [comment]
Same issue persist on Fedora 40 with VS Code 1.89.0, I followed the steps by @larspontoppidan and it worked.
I also had the same issue with Chrome (v 124.0) and the same steps work there as well.

**Comment by istadem2077** [comment]
Reading the replies and stuff, it seems like the issue is not even with Chromium/Electron, but rather the ~Novideo~Nvidia, whose drivers are just broken/do not support neccesary functionality requested by the Chromium/Electron.

Buying nvidia machine I thought that situation with nvidia+Wayland got better. 

> Problem still persists on F40 KDE Spin + Nvidia 550.76 + vscode 1.88.1 Followed the steps mentioned by @larspontoppidan and it worked great. Will this ever be addressed?

**Comment by waweber** [comment]
I am also experiencing the issue on F40 KDE + vscode 1.89.1

VS code does not appear to honor the flags when added to `code-flags.conf` nor `electron-flags.conf`, but it does work when passed explicitly on the command line. These flags also do not appear to be supported by the "Configure Runtime Arguments" preferences.

If you dislike seeing the warning from the terminal, it seems to work for me if I only pass `--ozone-platform=wayland`, so try updating your alias to that.

**Comment by KaeLL** [comment]
@waweber will try that, and if I don't reply to you again, it means it worked.

**Comment by bchanez** [comment]
Same issue.

I added to vscode and chromium-browser and it worked :

In `/usr/share/applications/code.desktop` and in `/usr/share/applications/chromium-browser.desktop`, add `--ozone-platform="wayland"` to the ligne that starts by `Exec`.

**Comment by wuhkuh** [comment]
You may be interested in https://github.com/NVIDIA/open-gpu-kernel-modules/issues/187#issuecomment-2265832905.
They seem to have fixed this on the Nvidia side.

**Comment by wuhkuh** [comment]
On my machine, this is resolved with mainline `seatd`, mainline `wlroots`, mainline `sway`, mainline `egl-wayland` and the latest NVIDIA drivers (560.31.02) for Linux.
Before these patches the performance on Wayland was horrendous. It's pretty solid now, actually.

**Comment by zhengliw** [comment]
sigh, nvidia...

**Comment by jwhipp** [comment]
I found this researching slow performance of vscode on Wayland and I am also seeing this, Fedora 41 and 42.  Terminal is terribly slow, changing focus off and back causes the whole UI to be sluggish.  I'm on an AMD GPU, so I don't believe this is an nvidia specific issue.

**Comment by berkaykrc** [comment]
The issue still persist.

**Comment by iota-008** [comment]
Still the same issue for me with Fedora Workstation 43. The latest VS Code version and NVIDIA drivers
