### ISSUE TITLE
GIT: Unsafe repository 'Mark as Safe' for UNC paths for SMB shares are not working

### ISSUE THREAD

**Issue by jasonhe54** [microsoft/vscode#170422]
Does this issue occur when all extensions are disabled?: Yes

Basically, it's a duplicate of #168344 and #169354 because Insiders build doesn't fix it.

VSCode Insiders About Information:
Version: 1.75.0-insider (user setup)
Commit: 6ed4d436a9b6ae131732f4e2a723868231f4473a
Date: 2022-12-23T05:21:57.802Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Steps to Reproduce:

1. Open VSCode - Insiders
2. Open a git repo that is on a remote computer shared over SMB
3. Get the following prompt and press "Manage Unsafe Repositories"
`The git repository in the current folder is potentially unsafe as the folder is owned by someone other than the current user.`
4. In the popup, select the UNC path for that SMB share. Get the following error: `Git: spawn C:\Program Files\Git\cmd\git.exe ENOENT`.
5. Pressing "Open Git Log" gives the following information (some parts were removed for obvious reasons).
```
2023-01-02 19:23:58.919 [info] > git rev-parse --show-toplevel [240ms]
2023-01-02 19:23:58.920 [info] warning: encountered old-style '//DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame' that should be '%(prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame'
warning: encountered old-style '//DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame' that should be '% (prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame'  
... (same thing repeated 5x)
fatal: detected dubious ownership in repository at '//DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame'
'//DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame' is owned by:
	'some windows user ID'
but the current user is:
	'some different windows user ID'
To add an exception for this directory, call:

	git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame'
```

**Comment by lszomoru** [comment]
@jasonhe54, this should have already been fixed in the latest Insiders release but I might have missed something in case you are still able to reproduce the issue. When you select a repository to be marked as safe VS Code would execute `git config`. The exact command is logged in the "git output window" so I was wondering if you could:
1. Select a repository to be marked as safe
2. Share the contents of the git output window so that I see the exact git command that gets executed

**Comment by jasonhe54** [comment]
I can't seem to get it to show me what `git config` command it is running in the background, but I've attached the entire log below using a different repo. It might be useful to note that I actually can't even get Git to mark the remote repo as a safe repo. Pressing the "Manage Unsafe Repositories" button under "Source Control" brings up a popup (See image 1) and selecting the remote repo, it just throws the same error message (See image 2). Pressing "Open Git Log" just shows the same Output in the log below.

Running the git command that it tells me to run (`git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/vscodeIssueDemo'`) returns the following error msg: "error: wrong number of arguments, should be 2"

Image 1:
![Image 1](https://user-images.githubusercontent.com/68795646/211424480-33eae782-31b3-4044-96ba-e65e1928af08.png)

Image 2:
![image](https://user-images.githubusercontent.com/68795646/211424831-49e575d5-6720-41c2-9a24-35c21a5e7a82.png)


Log Details:
```
2023-01-09 17:40:40.214 [info] Log level: Info
2023-01-09 17:40:40.214 [info] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2023-01-09 17:40:40.253 [info] Using git "2.39.0.windows.2" from "C:\Program Files\Git\cmd\git.exe"
2023-01-09 17:40:40.653 [info] > git rev-parse --show-toplevel [393ms]
2023-01-09 17:40:40.653 [info] fatal: detected dubious ownership in repository at '//DESKTOP-BFO0M0/C Drive/vscodeIssueDemo'
'//DESKTOP-BFO0M0/C Drive/vscodeIssueDemo' is owned by:
	'S-1-5-21-1380885177-3320910798-2175791219-1001'
but the current user is:
	'S-1-5-21-3781998300-1709668928-3529425073-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/vscodeIssueDemo'
2023-01-09 17:40:41.061 [info] > git rev-parse --show-toplevel [133ms]
2023-01-09 17:40:41.061 [info] fatal: detected dubious ownership in repository at '//DESKTOP-BFO0M0/C Drive/vscodeIssueDemo'
'//DESKTOP-BFO0M0/C Drive/vscodeIssueDemo' is owned by:
	'S-1-5-21-1380885177-3320910798-2175791219-1001'
but the current user is:
	'S-1-5-21-3781998300-1709668928-3529425073-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/vscodeIssueDemo'
2023-01-09 17:42:12.944 [info] > git rev-parse --show-toplevel [407ms]
2023-01-09 17:42:12.944 [info] fatal: detected dubious ownership in repository at '//DESKTOP-BFO0M0/C Drive/vscodeIssueDemo'
'//DESKTOP-BFO0M0/C Drive/vscodeIssueDemo' is owned by:
	'S-1-5-21-1380885177-3320910798-2175791219-1001'
but the current user is:
	'S-1-5-21-3781998300-1709668928-3529425073-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/vscodeIssueDemo'
2023-01-09 17:44:47.704 [info] > git rev-parse --show-toplevel [243ms]
2023-01-09 17:44:47.704 [info] fatal: detected dubious ownership in repository at '//DESKTOP-BFO0M0/C Drive/vscodeIssueDemo'
'//DESKTOP-BFO0M0/C Drive/vscodeIssueDemo' is owned by:
	'S-1-5-21-1380885177-3320910798-2175791219-1001'
but the current user is:
	'S-1-5-21-3781998300-1709668928-3529425073-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/vscodeIssueDemo'
2023-01-09 17:47:19.116 [info] > git rev-parse --show-toplevel [541ms]
2023-01-09 17:47:19.116 [info] fatal: detected dubious ownership in repository at '//DESKTOP-BFO0M0/C Drive/vscodeIssueDemo'
'//DESKTOP-BFO0M0/C Drive/vscodeIssueDemo' is owned by:
	'S-1-5-21-1380885177-3320910798-2175791219-1001'
but the current user is:
	'S-1-5-21-3781998300-1709668928-3529425073-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/vscodeIssueDemo'
```

If there's anything I did wrong, or would be helpful for you to know, let me know and I'll try to get back.

**Comment by lszomoru** [comment]
@jasonhe54, thanks for the additional information. I think I know what the issue is.

**Comment by jasonhe54** [comment]
Seems like whatever patch that was released last week didn't fix the issue?

Here's the About Information for VS Code Insiders: 
Version: 1.75.0-insider (user setup)
Commit: 9ccc2b3b30c122afe45bc6722bef0e3901fb2806
Date: 2023-01-20T05:23:24.298Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Likewise, attempting the open a smb shared folder seems like it's causing the same issues that I initially raised. Everything inside the Git output log is the same. Attempting the run the git command that is recommended `git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/vscodeIssueDemo'` returns an error, but I noticed that if you were to map a network share to a drive in Windows, and specify a network drive location, Git will let you add that as a safe directory, but it seems like VS Code Insiders is recognizing the file path as the UNC file-sharing path, which isn't able to be added into safe.directory. Ultimately, "mark as safe" for UNC paths still seem broken.

**Comment by lszomoru** [comment]
@jasonhe54, the current implementation in VS Code is to parse the output that is being returned by `git.exe`, and extract the git command that is recommended. Let's take VS Code out of the picture for a second. Are you saying that if you try to execute the command that is being recommended by git, you are getting an error?

```
git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/vscodeIssueDemo'
```  

If that is the case, that seems like an upstream issue with `git.exe` rather than VSCode. Could you please share the exact output that git returns, as well as the error that you are getting when you try to execute the command? Thanks!

**Comment by jasonhe54** [comment]
Actually, yes. I messed around a bit and seemed to have gotten it working. I'm guessing that VS Code, by default or by design, is using single quotes when running the `git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/vscodeIssueDemo'` command which seems to fail, at least on Windows. It returns the following error: `error: wrong number of arguments, should be 2`. However, changing the single quotes into double quotes fixes the issue (in that the command succeeds). What succeeded: `git config --global --add safe.directory "%(prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/vscodeIssueDemo"`. From there, I just had to press the Source Control button, Manage Unsafe Repo, select the repo location and it works. I'm guessing this latter part shouldn't be necessary if the git command that VSCode is running succeeds.

**Comment by asawhite** [comment]
I also experience the same issue when trying to add a UNC path to Git safe directories via Git Bash and VS Code on Windows.

As @jasonhe54 mentions the recommended git config command from the output of `git.exe` is incorrect. In my case it suggests `git config --global --add safe.directory '%(prefix)///pve/share/asawhite/TestRepo'` (single quote marks) when it should be `git config --global --add safe.directory "%(prefix)///pve/share/asawhite/TestRepo"` (double quote marks).

**Comment by lszomoru** [comment]
@jasonhe54, @asawhite, thank you very much for your input. What's really interesting here that I need to investigate further is that VS Code uses `childprocess.spawn()` and passes in an array of strings as arguments. I will see if there is any control on how the arguments are being used to construct the command that is being executed.

**Comment by asawhite** [comment]
No problem – happy to help.

There is also an open issue in the git-for-windows repo [here](https://github.com/git-for-windows/git/issues/3856). It looks like the command with the UNC path wrapped in single quote marks works for bash but not cmd/PS so not sure that the `git.exe` output will be amended to accomodate for different shells any time soon.

**Comment by lszomoru** [comment]
@jasonhe54, @asawhite, I have run some more tests on my Windows machine and marking as repository as safe using VS Code works as expected. When using VS Code to mark a repository as safe I would expect that you see the following entry in the global git config file. Is that not the entry that you are seeing being added?

```
[safe]
	directory = %(prefix)///pve/share/asawhite/TestRepo
```  

Notice that the entry in the git config file does not use `'`, nor `"`. 
This entry seems to be correctly interpreted by `git version 2.38.1.windows.1`.

**Comment by asawhite** [comment]
@lszomoru, that isn't what I see, no. Interestingly what's added is the Windows UNC path:
```
[safe]
	directory = //pve/share/asawhite/TestRepo
````

This is also what's listed in the drop-down selection after clicking **Manage Unsafe Repositories**, not `%(prefix)///pve/share/asawhite/TestRepo`.

I'm running Git:
`git version 2.39.1.windows.1`

VS Code:
```
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

**Comment by jasonhe54** [comment]
Interesting enough, seems like whatever was committed and pushed for the Insider's version 2 days ago seems to have fixed the issue.

Looks like it's still failing initially but it ends up working.
```
2023-01-25 11:12:55.871 [info] fatal: detected dubious ownership in repository at '//DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/VSCodeNewDemoRepo'
'//DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/VSCodeNewDemoRepo' is owned by:
	'S-1-5-21-1380885177-3320910798-2175791219-1001'
but the current user is:
	'S-1-5-21-3781998300-1709668928-3529425073-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/VSCodeNewDemoRepo'
2023-01-25 11:13:05.046 [info] > git config --global --add safe.directory %(prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/VSCodeNewDemoRepo [49ms]
```

Running `git config --global -l` shows `safe.directory=%(prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/VSCodeNewDemoRepo`. 

```Version: 1.75.0-insider (user setup)
Commit: f1b09237cd400d92987cf7a9681995e8011ef54c
Date: 2023-01-23T11:53:59.088Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes```

**Comment by lszomoru** [comment]
@asawhite, the fix for this issue is only available in VS Code Insiders (1.75) which will be released to Stable next week.
 
> Interesting enough, seems like whatever was committed and pushed for the Insider's version 2 days ago seems to have fixed the issue.

> Looks like it's still failing initially but it ends up working.

@jasonhe54, Are you saying that now with the latest Insiders release marking the repository as safe using VS Code Insiders is working as expected?

**Comment by jasonhe54** [comment]
> 

Yep, I tried with a newly created repo and it's marking the repo as safe. Note that the popup on the lower right hand side saying that you have to mark the repository as safe no longer shows up, but if you manually go into Source Control and press the button that says Manage Safe Repo (or something along those lines) and select the remote location, it does all work.

**Comment by lszomoru** [comment]
@jasonhe54, thanks for the confirmation. Yes, not showing the notification in the lower right hand corner was intentional as we decided that it might be distracting to immediately show a notification when opening a folder/workspace. A notification will only be shown if we cannot use the "Source Control" view.

**Comment by lszomoru** [comment]
Making as verified based on [this comment](https://github.com/microsoft/vscode/issues/170422#issuecomment-1404105290).
