### ISSUE TITLE
Broken syntax highlighting for Bash associative arrays (VS Code v1.75.0)

### ISSUE THREAD

**Issue by caleb531** [microsoft/vscode#173216]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.75.0
- OS Version: macOS Ventura 13.2

Today, when I upgraded to VS Code 1.75.0, I noticed that the syntax highlighting for one of my shell files was broken, even though the syntax is correct (please see screenshots below). I do not recall this issue being present in releases prior to 1.75.0 (although all my devices have upgraded, so I am unable to confirm this).

I have disabled all my extensions, and the issue is still reproducible.

Steps to Reproduce:

1. Open a new document
2. Set the language mode to **Shell Script**
3. Create an associative array in Bash where the key names are strings are the values contain spaces (see below); note that VS Code thinks there is an unterminated string somewhere (but there isn't)

```sh
#!/usr/bin/env bash

declare -A juices=(
    ['apple']='Apple Juice'
    ['orange']='Orange Juice'
)

# This is a comment
echo "${juices['apple']}"
```

You can also see a real-world example of this by pasting https://github.com/caleb531/dotfiles/blob/main/terminal/bash/build_cmds.sh into VS Code.

## Screenshots

<img width="1111" alt="1" src="https://user-images.githubusercontent.com/872474/216461317-dfa7e80c-510e-4b85-96d6-66cc659dd7fe.png">
<img width="1111" alt="2" src="https://user-images.githubusercontent.com/872474/216461325-eaf22adf-ff99-4ace-8245-7b9d9dd6cd44.png">
<img width="1111" alt="3" src="https://user-images.githubusercontent.com/872474/216461327-c27a9868-d530-4388-ad9b-bd793925ebf6.png">

**Comment by RedCMD** [comment]
Can confirm it working correctly in 1.72.2
but has been broken in 1.75.0

Prob should move report to https://github.com/jeff-hykin/better-shell-syntax

related: https://github.com/microsoft/vscode/issues/173224

**Comment by tikkanz** [comment]
I had the same issue (highlighting of associative arrays was broken after upgrading to 1.75.0). 
Installing the https://github.com/jeff-hykin/better-shell-syntax as mentioned by @RedCMD worked to resolve the issue for me in the meantime. Would be good to fix the default highlighting (without Extension) in VSCode.

**Comment by WinkelCode** [comment]
![Code_LoBz9SGI8p](https://user-images.githubusercontent.com/29005772/216600353-af8e96a8-914d-457d-a57d-8091ebdc964f.gif)

The issue appears to affect just arrays in general if a value contains a space.

**Comment by caleb531** [comment]
To @tikkanz's point, [jeff-hykin/better-shell-syntax](https://github.com/jeff-hykin/better-shell-syntax) does help a bit, although it's still not perfect.

<img width="727" alt="Screenshot 2023-02-04 at 11 12 51 AM" src="https://user-images.githubusercontent.com/872474/216785510-e2e84ffe-cbfc-443b-bbd1-a8e37f19490a.png">

**Comment by alexr00** [comment]
@caleb531 can you share a copy/pastable snippet of what you're seeing in https://github.com/microsoft/vscode/issues/173216#issuecomment-1416829667 so we can reproduce the issue easily? VS Code insiders will have the latest from https://github.com/jeff-hykin/better-shell-syntax tomorrow, and the recovery release of 1.75.1 will bring back the grammar from 1.74 (https://github.com/microsoft/vscode/issues/173336).

**Comment by caleb531** [comment]
@alexr00 When better-shell-syntax is enabled, the issue is fixed if I assign to the variable on the same line as the `declare`:

```sh
declare -A build_cmd_map=(
	['gulp:build']='gulp build'
	['gulp:clean']='gulp clean'
	['gulp:develop']='gulp serve'
	['gulp:watch']='gulp build:watch'

	# this is a comment
	['node:start']='npm start'
	['node:build']='npm run build'
	['node:watch']='npm run watch'
	['node:develop']='npm run dev'
	['node:preview']='npm run preview'

	['jekyll:build']='jekyll build'
	['jekyll:develop']='jekyll serve'
	['jekyll:watch']='jekyll build --watch'
)
```

<img width="487" alt="Screenshot 2023-02-06 at 9 38 35 AM" src="https://user-images.githubusercontent.com/872474/217044457-42f2861e-78c9-498e-8b94-503b4a39dcd2.png">

However, if I assign separately (which still executes fine in my shell), then the syntax breaks:

```sh
#!/usr/bin/env bash

declare -A build_cmd_map=
build_cmd_map=(
	['gulp:build']='gulp build'
	['gulp:clean']='gulp clean'
	['gulp:develop']='gulp serve'
	['gulp:watch']='gulp build:watch'

	# this is a comment
	['node:start']='npm start'
	['node:build']='npm run build'
	['node:watch']='npm run watch'
	['node:develop']='npm run dev'
	['node:preview']='npm run preview'

	['jekyll:build']='jekyll build'
	['jekyll:develop']='jekyll serve'
 	['jekyll:watch']='jekyll build --watch'
)
```

<img width="526" alt="Screenshot 2023-02-06 at 9 39 19 AM" src="https://user-images.githubusercontent.com/872474/217044743-3c8c009f-14cd-4de6-9ddd-b0eb9e9e045e.png">

**Comment by alexr00** [comment]
Thanks @caleb531. I pulled the latest changes from the folks in [jeff-hykin/better-shell-syntax](https://github.com/jeff-hykin/better-shell-syntax) into VS Code yesterday and I see both of your examples work now. If you want to use VS Code insiders then the issue should be resolved there. Or, I assume that [jeff-hykin/better-shell-syntax](https://github.com/jeff-hykin/better-shell-syntax) will have another release of the extension with the fix at some point in the near future.

**Comment by cipherdmg** [comment]
This is still broken.

Build 1.77.0-insiders (just updated today).

Doing this breaks syntax highlighting.  The only way for me to stop breaking it is if I put a escape the second entry in the array which is not valid syntax.

declare -A fileKeyFileMap=(["${VAR1}"]="${VAL1}" ["${VAR2}"]="${VAL2}")

I moved back down to 1.7.6 stable and its working ok there.

So is this fixed in the insiders build with the default shell syntax highlighter or do we need to download another one?

Thanks

**Comment by alexr00** [comment]
@cipherdmg your issue is not yet fixed. I have opened https://github.com/jeff-hykin/better-shell-syntax/issues/53 on the upstream repo for it.

**Comment by alexr00** [comment]
@cipherdmg the folks over in https://github.com/jeff-hykin/better-shell-syntax/issues/53 have added a short term fix for your issue. You should see it in the next VS Code insiders build.
