### ISSUE TITLE
Git - diff decorators are not showing in the latest stable release

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#173763]
Copied from https://github.com/microsoft/vscode/issues/173226#issuecomment-1419425284

> @Jason3S, could you please confirm that opening the same workspace yields different outcomes when you use VS Code Stable 1.74.3 and VS Code Stable 1.75 and VS Code Insiders 1.76. Just want to narrow down where the problem might be. Thanks!

I checked.
- 1.74.3 - works just fine.
- 1.75 VS Code Stable - has issues with git changes not showing.
- 1.76 Insiders - seem to be working.

```
Version: 1.76.0-insider
Commit: c9e3ef865539061b5602c6b9ac6030332aa1ce70
Date: 2023-02-06T05:24:10.821Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.2.0
Sandboxed: Yes
```

**Comment by lszomoru** [comment]
@Jason3S, let's use this issue to continue the investigation related to the diff decorations. What seems interesting is that based on this information the diff decorations seem to be broken for you in 1.75, they are working as expected in Insiders 1.76. I am not aware of any changes in this area, but I will take a look at the code to see if I can find the change that resolved the issue. I will keep you posted with my findings.

**Comment by lszomoru** [comment]
@alexr00, could this regression be related to some of the work that you have been doing related to dirty diff decorations?

**Comment by alexr00** [comment]
@lszomoru it could be related to the dirty diff decorations.

@Jason3S, do the missing gutter decorations occur with every repo you open in 1.75? I don't think there have been any changes yet in 1.76.

**Comment by Jason3S** [comment]
@alexr00,

The behavior in 1.75 was inconsistent. Sometimes it would not show up at all, not in the gutter or the scrollbar. Other times it would show up, but be the wrong color. Showing blue when it should be green.

I just not installed 1.75.1, I'll see if it still happens and add some screen shots.

**Comment by ymanton** [comment]
I see it in 1.75.1 as well.

It seems to stop working at a point in time; existing decorations in open tabs remain but opening new files or making further changes doesn't result in any more decorations.

**Comment by Jason3S** [comment]
@alexr00,

I'll keep an eye out.

Sometimes it takes a very long time (many minutes) for the decorations to appear in 1.75.1 stable.

**Comment by alexr00** [comment]
Thanks @Jason3S. The listener leak error that you show doesn't appear to be coming from the diff decorations. @hediet, it looks like the leak is coming from here if you wanted to investigate:

https://github.com/microsoft/vscode/blob/da15b03a10fc2095fa69325c581657da1427ca7a/src/vs/editor/common/model/tokenizationTextModelPart.ts#L61-L62

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/176738, which has since been fixed.

**Comment by Jason3S** [comment]
@alexr00,

How is this a duplicate? The fix only works on Windows.

**Comment by Jason3S** [comment]
@alexr00,

Thank you. I hope it is fixed. I have had to restart VS Code quite a number of times over the past few weeks.

**Comment by galaxytass** [comment]
This issue is fixed in version 1.76.2 for git repositories, however it is not yet fixed for Mercurial (mrcrowl.hg extension).

**Comment by alexr00** [comment]
@galaxytass can you share exact steps that you use to reproduce the issue with Mercurial?

**Comment by rebornix** [comment]
Add [author-verification-requested](https://github.com/microsoft/vscode/labels/author-verification-requested) label as users mentioned that it's not fixed for Mercurial.

**Comment by galaxytass** [comment]
> @galaxytass can you share exact steps that you use to reproduce the issue with Mercurial?

1. Create a Mercurial repository, create a file and commit that file.
2. Install the `Hg' extension (from mrcrowl); version 1.8.1.
3. Open the folder with vscode.
4. Edit the file. Expected to see a blue or green decorator on the left of the edited line. The changes do still show up in the diff editor, but not in the file itself.


Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by alexr00** [comment]
I've just tested with Mercurial and I correctly see the quick diff gutter decorations. My steps:
1. Install Mercurial
2. Create a folder and `hg init`
3. Install mrcrowl.hg 
4. Open the folder in VS Code
5. Add a file to the folder and commit the change.
6. Modify the file. 
7. See the quick diff decoration

![Recording 2023-03-24 at 12 06 50](https://user-images.githubusercontent.com/38270282/227505461-c9c47d90-3d98-4bb1-be99-35ed081bf414.gif)

**Comment by jgriffitts** [comment]
I've also been seeing this problem for several weeks. Gutter diff decorations don't work for hg repositories, but work fine with git. I first noticed it with 1.76.1 early this month. Tried reverting to 1.75.1 and the problem disappeared.

For what it's worth, I just followed the exact procedure alexr00 cited, and the gutter diff does _not_ show up. I tried disabling git and all extensions except Hg, and the problem persists.

The Hg output window shows:
> Using hg 6.3.2 from C:\Program Files\TortoiseHg\hg.exe
> hg root
> hg paths
> hg summary -q
> hg branch
> hg status -C
> hg incoming -q
> hg outgoing -q
> config error: default repository not configured!
> (see 'hg help config.paths')
> 
> abort: repository default not found

Based on this, I retested in an old repository that has paths set up, but the problem persists. I tried it in a new directory created at the root of C:\ but the problem persists. I'm out of ideas about what else to try.

Version: 1.76.2 (system setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by alexr00** [comment]
After discussing with other folks on the VS Code team we've decided not to add a work around for Mercurial. Full details: https://github.com/mrcrowl/vscode-hg/issues/198#issuecomment-1486894809

PR for the change in the extension: https://github.com/mrcrowl/vscode-hg/pull/199
