### ISSUE TITLE
Incorrect layout of welcome page, when there are no suggestions

### ISSUE THREAD

**Issue by HolyBlackCat** [microsoft/vscode#178831]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0
- OS Version: Xubuntu 22.04.2

Steps to Reproduce:

1. Open the Welcome page (`Help` -> `Welcome` if it doesn't open by default)
2. Skip any suggestions (note, I haven't tested how this looks *with* suggestions)
3. Observe the unusual welcome page layout with a lot of empty space on the right:

![screenshot](https://user-images.githubusercontent.com/20289055/229191721-38320472-c0aa-4d3a-83e8-7b077c603e85.png)

This is a regression. The previous version had a different layout, with recent files on the right, and everything else on the left.

The layout seen on the screenshot was only used when you had active suggestions, which occupied the space on the right.

**Comment by OkazakiNagisa** [comment]
I can confirm, on vscode 1.77.0 Win10 x64.

**Comment by Nikita-Presnov** [comment]
Inconvenient design decision, or just a glitch.
 
I can confirm, on vscode 1.77.0 Debian 11.

**Comment by bhavyaus** [comment]
Timing issue between walkthroughs being compiled and walkthroughs rendering.

Currently,
Walkthroughs show up if you have an extension installed which contributes a walkthrough. 
If you don't have an extension which contributes walkthroughs installed, then the built in walkthroughs are also missing -> You can test this by switching to a new empty profile and reloading the welcome page.

**Comment by starball5** [comment]
Related on Stack Overflow: [Is there a way to put the "Recent" list in the welcome page in its own column?](https://stackoverflow.com/q/75936254/11107541)

**Comment by TylerLeonhardt** [comment]
closing since https://github.com/microsoft/vscode/pull/179335 was merged.

**Comment by david-fong** [comment]
I just installed 1.77.3 and see the following:

![image](https://user-images.githubusercontent.com/42986768/231652175-c6895489-3a0e-4b68-8199-27012c0cc2cb.png)

Is it supposed to be like this? I was under the impression that the fix would make the recent listing be in its own column.

**Comment by svipas** [comment]
@bhavyaus I can confirm that layout is still incorrect.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/10441177/232709072-5f748459-98ef-4e5a-a850-7490b9e8ce75.png">

**Comment by miguelsolorio** [comment]
Seems that this is related to a new (?) section on the welcome page for recommended extensions (which I can't find a way to turn off, will file an issue for that). 

<img width="1024" alt="CleanShot 2023-04-18 at 08 49 42@2x" src="https://user-images.githubusercontent.com/35271042/232832706-992ee0a1-e504-43ff-b423-0d5271755530.png">

Even after dismissing it, the layout stays the same so I don't think this was fixed:

<img width="1024" alt="CleanShot 2023-04-18 at 08 52 42@2x" src="https://user-images.githubusercontent.com/35271042/232833307-683d22d8-ea55-4790-881b-bbb5fe96212d.png">

**Comment by Nikita-Presnov** [comment]
Designers are back in their repertoire, let's give the user a function they don't need (seriously, VSCode starts to slow down a lot if there are too many extensions and they are not optimal), while they drop support for the older but up-to-date versions. How nice, IT every year more and more suffers from garbage.

**Comment by HolyBlackCat** [comment]
@meganrogge @TylerLeonhardt This should be reopened.

The ticket is in the [March 2023 Recovery 3](https://github.com/microsoft/vscode/milestone/229?closed=1) milestone, but as of 1.77.3 it's still not fixed. (And neither in the Insiders.)

**Comment by miguelsolorio** [comment]
Any updates @bhavyaus? Seems like this is the same on Insiders (1.78) as well, so I am wondering if this is by design or not (cc @daviddossett):

<img width="1024" alt="CleanShot 2023-05-01 at 08 36 18@2x" src="https://user-images.githubusercontent.com/35271042/235479476-b6c82a79-3e6f-4dc3-96e3-624e26532cfd.png">

**Comment by bhavyaus** [comment]
> Any updates @bhavyaus? Seems like this is the same on Insiders (1.78) as well, so I am wondering if this is by design or not (cc @daviddossett):
> 
> <img alt="CleanShot 2023-05-01 at 08 36 18@2x" width="1024" src="https://user-images.githubusercontent.com/35271042/235479476-b6c82a79-3e6f-4dc3-96e3-624e26532cfd.png">


This was by design so as to not clutter page on addition of the featured extension entry. But given the user input, we can consider a better approach for this.  
**Proposal:**
 - Recent list stays on the left side of the welcome page when either walkthroughs/featured extension tile is displayed. Recent item count limited to 5
-  Recent list moves to the right side of the welcome page when **no** walkthrough/featured extension tile is displayed. Recent item count is also increased to 10. 

@daviddossett thoughts?

**Comment by daviddossett** [comment]
Sounds good 👍
