### ISSUE TITLE
Setting `NODE_UNC_HOST_ALLOWLIST` does not work

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#182019]
**Steps:**
* make sure no `security.allowedUNCHosts` is configured
* configure an environment variable `NODE_UNC_HOST_ALLOWLIST` to be `localhost`
* restart Windows
* run `code --user-data-dir \\localhost\c$\Users\<name>\Desktop\some-empty-folder`
* VS Code should open fine
* open a folder such as `vscode`
* make sure extensions work (e.g. typescript) and you can change user settings

**Comment by dbuddrige** [comment]
Thanks for the workaround, that gets me running vscode (at all).

I note that to run code against the current directory, I  (now) have to type:

code --user-data-dir "\\some\empty\directory" .

rather than:

code .

**Comment by DrCWO** [comment]
Just can't open my files residing on \\192.168.0.193\SambaPi any more. Worked this morning.
What can I do? I can't work any more!

**Comment by sandy081** [comment]
I see the fix is merged to release and main branches. Hence closing.

**Comment by rzhao271** [comment]
It worked until I set update mode to none and tried reloading. The program wasn't able to reload, so I re-ran the command on the now-non-empty user data dir. After that, I noticed that my settings weren't saved successfully, and that I wasn't able to edit any more settings such as the tab size.
![Unable to write file UNC localhost access denied error notification](https://github.com/microsoft/vscode/assets/7199958/e92ac0eb-9925-466c-8828-34aa033b80ce)

**Comment by bpasero** [comment]
@rzhao271 I cannot reproduce, are you sure the environment variable was still set?

Here is what I do:

<img width="1022" alt="image" src="https://github.com/microsoft/vscode/assets/900690/b937c47e-8d7e-4024-bc2a-dcb39a86f030">

And from the downloaded x64 archive, run:

```
bin\code --user-data-dir \\localhost\c$\Users\bpasero\Desktop\foo-ws
```

**Comment by rzhao271** [comment]
I can still reproduce the issue on the candidate Stable (User) build. The environment variable is set, too.
1. Launch with an empty user data dir with a path formatted like in the comments above.
2. Change update.mode to none. Reload when prompted.
3. Wait for the program to reopen. Open settings and search for update.mode.
4. :bug: The setting didn't update.
5. Try to update another setting.
6. :bug: The settings file isn't able to update.

**Comment by rzhao271** [comment]
I wasn't able to repro the issue using the Archive build.
I've attached a verbose log for the User build.
[verbose.log](https://github.com/microsoft/vscode/files/11445873/verbose.log)

**Comment by roblourens** [comment]
This is also working fine for me, so I'll call it verified

**Comment by rzhao271** [comment]
Looks like I was using the wrong version to test this issue, because I downgraded while trying to test another issue.
Confirmed and verified.

**Comment by DrCWO** [comment]
Hi guys, I get crazy with that!
I added the environment variable,. rebootet Win10 and restartet VSCode. 
Next I open my \\192.168.0.193\SambaPi path in a separate Explorer window.
Now I drag one of my javascript files onto the editoe and saw the message displayed below.

Did you guys have any idea how I can make this work again?

![image](https://github.com/microsoft/vscode/assets/65152014/4e2d70be-53fc-4acb-a6ca-9d9188545bd2)

![image](https://github.com/microsoft/vscode/assets/65152014/706e53a0-0837-4bf5-a3d1-747a487a01a7)

I develop on a remote Linux system and accessed all my files like that until yesterday :-(

Help would be appreciated.

Best DrCWO

**Comment by bpasero** [comment]
Keep in mind that the environment variable needs to be a `\` separated string. So for example `server-a\server-b` for `server-a` and `server-b`.

**Comment by DrCWO** [comment]
Thanks' for the hint but still no success:

Here the environment variable:
![image](https://github.com/microsoft/vscode/assets/65152014/14689d4d-096e-4c4e-b45b-36f264eb7be3)

Here what I get if I drag the file into vscode:
![image](https://github.com/microsoft/vscode/assets/65152014/112a45bb-35ea-4d8f-828b-27aca48257f0)

And this is my window in Explorer where I drag the source to the main window of vscode...
![image](https://github.com/microsoft/vscode/assets/65152014/08d56a35-eeb2-4e92-b049-bf08fd9e2e53)

Any ideas what else I can do to make it work again?

**Comment by DrCWO** [comment]
Is there a wav in vscode to see which servers are allowed?

**Comment by bpasero** [comment]
Can you wait for the `1.78.2` release later today and try again.

**Comment by DrCWO** [comment]
Tested with 1.78.2 right now but the issue persists :-(
Did I miss anything?

**Comment by DrCWO** [comment]
Or do anything else but setting the Environment variable???

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by DrCWO** [comment]
Ok, downloaded it started it . 
Version: 1.79.0-insider (user setup)
Commit: 2575777b9d3cdb865d61f9f1dfaac1fea9e1bde6
Date: 2023-05-12T05:21:06.392Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

Bahavior changed...

![image](https://github.com/microsoft/vscode/assets/65152014/8bc1e762-551e-43f0-ad9d-71b8e1816de4)

I said that it shall open and the setting should be remembered. 

Next I saw that:

![image](https://github.com/microsoft/vscode/assets/65152014/c45e5104-b14f-4619-8420-8c55cfff4402)

So except of the additional dialog no improvement :-(

**Comment by bpasero** [comment]
Just to summarise: can you post the exact contents of your `NODE_UNC_HOST_ALLOWLIST` environment variable and the exact contents of your `security.allowedUNCHosts` setting?

**Comment by DrCWO** [comment]
Here the setting for the environment variable.
![image](https://github.com/microsoft/vscode/assets/65152014/1fddccc7-fa30-45c9-bae7-9793f9be513e)
But where is security.allowedUNCHosts. I never had set that anywhere???
All I want that vscode works as before...

**Comment by bpasero** [comment]
You will only have to configure `NODE_UNC_HOST_ALLOWLIST` in rare cases where a setting cannot be configured otherwise, for example when your VS Code application data directory is on a UNC drive. For most cases:
* you can remove the variable
* you open settings and find the `Security` entry
* you add the 3 IP addresses as allowed host to the UNC host allow list

**Comment by DrCWO** [comment]
Setting the hosts in the security settings did the trick!
This also works in v1.78.2.

Thank you very much for your support 🥇

**Comment by Shawn1874** [comment]
What host do we need to enter? is it the name of the NFS server in the case of NFS? So far this solution of adding a host to the security setting is not working for me with version 1.78.2.
