### ISSUE TITLE
`env` set in my fish config prevails over what I set in the env var collection

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#184009]
Testing #182970

```ts
	const term2 = vscode.window.createTerminal({
		name: `Ext Terminal tranisent #${NEXT_TERM_ID++}`,
		isTransient: true,
		shellPath: 'fish'
	} as any);
	const collection = context.environmentVariableCollection;
		collection.replace('FOO', 'REPLACED', { applyAtShellIntegration: true, applyAtProcessCreation: false });
		collection.append('APPENDING', 'appending', { applyAtShellIntegration: true, applyAtProcessCreation: false })
		collection.prepend('PREPENDING', 'prepending', { applyAtShellIntegration: true, applyAtProcessCreation: false });
```
![Screenshot 2023-05-31 at 7 59 39 PM](https://github.com/microsoft/vscode/assets/29464607/acf5338c-06eb-4259-8f14-6768963b37fd)

![Screenshot 2023-05-31 at 8 00 08 PM](https://github.com/microsoft/vscode/assets/29464607/3d306b71-2f9f-43d8-a91b-8f6e5dcd41ea)

**Comment by Tyriar** [comment]
This is because of the same problem that caused https://github.com/microsoft/vscode/issues/184191

**Comment by karrtikr** [comment]
@Tyriar https://github.com/microsoft/vscode/issues/184191 appears to be closed now, does that mean this has been fixed?

**Comment by Tyriar** [comment]
No, this issue is about fish acting atypical in that it applies the environment before fish.config is applied. This is because of how the automatic injection works in fish via an environment variable. Still not sure how we can handle this.

**Comment by karrtikr** [comment]
Discussed offline, maybe we could use the first pre exec hook in fish to run shell integration, instead of `XDG_DATA_DIRS`.

**Comment by meganrogge** [comment]
Nice 👍 

![Image](https://github.com/microsoft/vscode/assets/29464607/d2dc7a2e-31a5-4c76-abb0-bee6f19c9ca2)
