### ISSUE TITLE
HTML tag autocomplete stopped working on JSX files (Code - Insiders)

### ISSUE THREAD

**Issue by rickitan** [Microsoft/vscode#18427]
- VSCode Version: Version 1.9.0-insider (1.9.0-insider) | 2017-01-11T07:05:43.066Z
- OS Version: 10.12.2

I opened this issue https://github.com/Microsoft/vscode/issues/18284 on Monday. I downloaded the nightly build to verify the fix that @aeschli introduced. It did work. 

But I found a possible regression. Autocompleting tags in `javascriptreact` files stopped working:

![new-autocomplete-issue](https://cloud.githubusercontent.com/assets/3137417/21854150/ad01fa72-d7e7-11e6-872a-883ad66edabc.gif)

On stable it is working: 

![autocomplete-working](https://cloud.githubusercontent.com/assets/3137417/21854163/c00fe6ce-d7e7-11e6-9871-41c1c3adbeb5.gif)

Thank you for the hard work guys, I'm loving VS Code.

**Comment by aeschli** [comment]
We now have a separate language id for inside react tags: jsx-tags.
The emmet mode should map that to the mode id it uses.

**Comment by rickitan** [comment]
I just downloaded the latest nightly build and I just confirmed the fix. Thank you @ramya-rao-a ! 🎊

**Comment by accounthandler** [comment]
seems it happened again. vs code ver: 1.10.2 2017-03-08T13:54:01.558Z
mac os 10.12.2

**Comment by ramya-rao-a** [comment]
@accounthandler I just tried on 1.10.2, works fine. What is the language mode on your file? You can see it on the bottom right corner

**Comment by accounthandler** [comment]
javascript (babel) or javascript react (babel) , neither works. But if I switch to html, then it works.
(the file extension is .js, just a boilerplate file created by create-react-app)

It's also weird to me, since it was working yesterday.

**Comment by ramya-rao-a** [comment]
As long as the language mode is "Javascript React", it should work

<img width="395" alt="screen shot 2017-03-12 at 9 27 04 pm" src="https://cloud.githubusercontent.com/assets/16890566/23841449/ab94324c-076a-11e7-9b5e-e7300264cc2b.png">

Can you share a gif/screenshots of what you are seeing with sample code perhaps?

Was this working for you in 1.10.2 ?

**Comment by accounthandler** [comment]
![test](https://cloud.githubusercontent.com/assets/5819795/23842126/56b1bbc8-076f-11e7-96cf-6acec38aa4d7.gif)

It was working. No idea what happened...

**Comment by ramya-rao-a** [comment]
The language mode "Javascript Babel" are you getting that from an extension?

**Comment by accounthandler** [comment]
These are the extensions I installed. Maybe from the first one babel es6/es7. But even after I disable the plugin, the tag autocomplete still doesn't work.

![image](https://cloud.githubusercontent.com/assets/5819795/23917443/9326c8da-08ac-11e7-81f9-d8bf0bb5d55e.png)

**Comment by zhangchi0729** [comment]
Using highlighter plugin Sublime Babel, this issue occurs too.

**Comment by ramya-rao-a** [comment]
I installed both the babel and sublime babel extensions 

<img width="247" alt="screen shot 2017-04-01 at 11 19 44 pm" src="https://cloud.githubusercontent.com/assets/16890566/24584894/d4d73db2-1731-11e7-913d-eb42de0ade66.png">

And emmet expansions work for me both in `.js` and `.jsx` files with language mode as `Javascript React (Babel)` in the Insiders build but not in the Stable build.

@aeschli Did we change something around this?

**Comment by kivohin** [comment]
Not working for me also on stable version 1.14.2 inside JS and JSX files when using `"emmet.useNewEmmet": true`. But with `"emmet.useNewEmmet": false` it works.

However inside HTML files both cases are fine. Has this been fixed yet?

**Comment by ramya-rao-a** [comment]
@kivohin This is fixed in the latest Insiders. Can you give it a try there?

**Comment by luishrd** [comment]
broken for me on Version 1.14.2

**Comment by CodeLittlePrince** [comment]
`
"emmet.includeLanguages": {
        "javascript",
        "html"
    },
`
add this to your settings.json

**Comment by ramya-rao-a** [comment]
VS Code 1.15 will be released soon (mostly tomorrow) in which this should be fixed without any settings change.

**Comment by whs465** [comment]
@ramya-rao-a 
Autocompleting tags in javascriptreact files for components is broken for me on VS Code 1.15.
![react](https://user-images.githubusercontent.com/14139589/29216287-362d21e4-7ed4-11e7-89e6-d077f0291468.gif)

**Comment by ramya-rao-a** [comment]
@whs465 Emmet suggestions will not show up for simple words. We made that decision because other wise you will end up getting a suggestion for every word you type.

We are working on getting `tab` back for emmet. So for components, that should work. Follow the issue number 32243

 And for actual abbreviations like `MyComponent.hello>YourCompnenet` gets emmet suggestions even today

**Comment by ChrisNLott** [comment]
@CodeLittlePrince 
> "emmet.includeLanguages": { "javascript", "html" },
add this to your settings.json

I think you meant: `"emmet.includeLanguages": { "javascript": "html" }`

This works for me

**Comment by smiled0g** [comment]
I have version 1.15.1, still not fixed

I practically cannot work now. Please suggest what to do.

**Comment by ramya-rao-a** [comment]
@smiled0g You need to provide more details on what is not working for you. What settings have you set? Which file are you working on? etc.

Please read the [Emmet docs](https://code.visualstudio.com/docs/editor/emmet)

**Comment by ziison** [comment]
step 1: the setting `emmet.triggerExpansionOnTab` and set it to `true`.
step 2: 
```json
"emmet.includeLanguages": {
    "javascript": "javascriptreact",
    "vue-html": "html",
    "plaintext": "jade"
}
```
