### ISSUE TITLE
Can't run as Administrator - launch-failed code 18

### ISSUE THREAD

**Issue by ianspence-msft** [microsoft/vscode#185057]
Type: <b>Bug</b>

I can't open vscode as administrator. I disabled all extensions to verify, but when I try to run it as admin this error dialog appears: `The window terminated unexpectedly (reason:'launch-failed',code:'18')`, I have an option to open a new window but that does nothing.

![image](https://github.com/microsoft/vscode/assets/119704927/f64321c7-4c54-49cb-be8e-3107c1821719)

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7763 64-Core Processor                 (16 x 2445)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|63.95GB (50.92GB free)|
|Process Argv|--crash-reporter-id 878d6c45-dc4e-45f8-b76e-8bdf700f1534|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
showsbindicator:30760979
pythongtdpathcf:30739705
dh2dc718:30763024
pythonnosm12tcf:30765602

```

</details>

**Comment by josh-hemphill** [comment]
Everyone in my department just started reporting this.

**Comment by deepak1556** [comment]
Please refer to https://code.visualstudio.com/docs/setup/windows#_unable-to-run-as-admin-when-applocker-is-enabled for launching as administrator.

Currently `--no-sandbox` does not work as expected which is being resolved in https://github.com/microsoft/vscode/issues/184687 and fix will be available in `1.79.2`.

**Comment by starball5** [comment]
Related on Stack Overflow: [Visual Studio Code 1.79 launch in admin mode fails with code 18](https://stackoverflow.com/q/76470339/11107541)

**Comment by Devirob** [comment]
Same issue

**Comment by mlindgren** [comment]
I'm still hitting this in 1.79.2 on Windows 11. However, I can successfully launch an admin instance of VSCode **iff** I have a non-admin instance already running.

**Comment by lil131** [comment]
> I'm still hitting this in 1.79.2 on Windows 11. However, I can successfully launch an admin instance of VSCode **iff** I have a non-admin instance already running.

Same here. 1.79.2 doesn't fix the issue on Windows 11. Launching as admin with `--no-sandbox` works for me though.

**Comment by ap3rus** [comment]
It's happening due to #122951
