### ISSUE TITLE
Unjustified "git push"

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#18784]
- VSCode Version:
![2017-01-19_16h33_40](https://cloud.githubusercontent.com/assets/3082812/22108613/0bba1562-de65-11e6-88ea-8b76605e3d78.png)

- OS Version: win7-pro

Steps to Reproduce:

1. Open the project not containing not pushed changes
2. Press to "Synchronize changes"
3. Open git OUTPUT. See that run the command "git push", but the local branch has no changes, not submitted to any remote branch. Instead of "git push" should check for unsent changes only after which you can call "git push".
![2017-01-19_16h29_21](https://cloud.githubusercontent.com/assets/3082812/22108706/7aec68ae-de65-11e6-8e31-e5560b15d2fa.png)

PS:
I think that should prompt for confirmation to send changes to a remote branch, as was done in previous versions of VSCode

**Comment by joaomoreno** [comment]
Fixed in latest.

**Comment by IgorNovozhilov** [comment]
:+1:

**Comment by roblourens** [comment]
Not sure if I understand it, when I click that button and the branch is up to date, I see it run `git pull` and `git push`.

```
git pull
git push
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...origin/master
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
git show :.vscode/tasks.json
```

**Comment by bpasero** [comment]
I also still see a git push happening.

![image](https://cloud.githubusercontent.com/assets/900690/23306522/31c56c2e-faa4-11e6-9ea6-b115ce5315c7.png)

**Comment by isidorn** [comment]
No. It is working nicely, it is just that you all have   `  "git.confirmSync": false` in your settings. ONce you do not have that it will nicely ask you

**Comment by bpasero** [comment]
@isidorn not sure I agree, the author of this issue asks for:

>  Instead of "git push" should check for unsent changes only after which you can call "git push".

**Comment by isidorn** [comment]
Ok. Let's reopen and @joaomoreno can decide

**Comment by joaomoreno** [comment]
> I think that should prompt for confirmation to send changes to a remote branch, as was done in previous versions of VSCode

This is now back in.
