### ISSUE TITLE
Source Control Not Updating for specific repository

### ISSUE THREAD

**Issue by william-clayton** [microsoft/vscode#201099]
Type: <b>Bug</b>

Hey,

Since last friday, my source control menu is no longer updating for only one repository. This only happens with one specific repository, but the git commands (from command line and git-gui) work for this specific repository, so it would seem that the git repository itself is working correctly.

When I open the repo in vscode, it seems to be largely correct - the changes are correctly shown as either staged or changes depending on their state. However, using the controls in the source code will not be reflected in section. This is shown in these images: 

Initially the shown infomation is correct (the terminal is a git bash with 'git status' output shown)

![initial](https://github.com/microsoft/vscode/assets/154112593/920502be-de39-445f-b270-3b45f2ee6824)

Then I use the 'Unstage Changes' button for each file and repeat the git status

![after](https://github.com/microsoft/vscode/assets/154112593/7e87d9ff-c256-469c-be33-eae7bf9b3a9c)

Note that the git status output shows the files have been unstaged, but the Source Control section does not. Furthermore, if I repeat this process with the changes initally unstaged, a similar beahviour occurs, just that the Source Control does not reflect them being staged.

I have tried:

- Re-installing vscode
- Re-installing git
- The insiders version
- Running vscode with no extensions
- Re-cloning the repository

but the same behaviour is seen every time. I have also observed the behaviour to not be present on my colleges device.

Thanks

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (19.79GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id 186140f6-92b9-4d99-a583-380e09ec31d2|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by william-clayton** [comment]
Note this is fixed by downgrading to version 1.84.2

**Comment by lszomoru** [comment]
@william-clayton, thanks for filing this issue and this does look like a regression. Could you please use the "Developer: Toggle Developer Tools" command from the command palette and see if there are any relevant error there? 

Could you tell me more about the branch that is currently checked out: 1) Does the branch have a remote? 2) Does the branch have any special characters in its name? 3) Are you able to reproduce the same on the default branch (ex: `main`) of the repository? 

Does the issue get resolved in you set `scm.showIncomingChanges` and `scm.showOutgoingChanges` settings to `false`?

**Comment by danielevigi** [comment]
I am experiencing a similar issue. This is the error in the developer tools console:

`ERR Failed to execute git: Error: Failed to execute git
	at t.$P.j (c:\Users\mywindowsaccount\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:890158)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.$P.exec (c:\Users\mywindowsaccount\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:889264)
	at async $.exec (c:\Users\mywindowsaccount\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:893981)
	at async $.getCommitCount (c:\Users\mywindowsaccount\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:916095)
	at async M.eb (c:\Users\mywindowsaccount\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:993243)
	at async M.db (c:\Users\mywindowsaccount\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:992935)
	at async M.getCommitCount (c:\Users\mywindowsaccount\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:984180)
	at async t.$Eb.resolveHistoryItemGroupCommonAncestor (c:\Users\mywindowsaccount\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:921155)
	at async U.$resolveHistoryItemGroupCommonAncestor (c:\Users\mywindowsaccount\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:127058)`

**Comment by sivavemulapalli** [comment]
![Recording 2023-12-18 at 21 15 39](https://github.com/microsoft/vscode/assets/21997664/6bfd3d43-1b63-4045-927c-8f0b456aa618)

**Comment by lszomoru** [comment]
@sivavemulapalli, thank you! Could you please invoke the "Git: Show Git Output" and share the logs? I am working on a fix, but I would still like to understand why, the exception is happening. Thanks!

**Comment by william-clayton** [comment]
> @william-clayton, thanks for filing this issue and this does look like a regression. Could you please use the "Developer: Toggle Developer Tools" command from the command palette and see if there are any relevant error there?
> 
> Could you tell me more about the branch that is currently checked out: 1) Does the branch have a remote? 2) Does the branch have any special characters in its name? 3) Are you able to reproduce the same on the default branch (ex: `main`) of the repository?
> 
> Does the issue get resolved in you set `scm.showIncomingChanges` and `scm.showOutgoingChanges` settings to `false`?

1) Yes, the branch has a remote
2) No, the name is 'EnergyManagement'
3) Yes, issue still exists on main

yeah, setting those settings resolves the issue

**Comment by sivavemulapalli** [comment]
> @sivavemulapalli, thank you! Could you please invoke the "Git: Show Git Output" and share the logs? I am working on a fix, but I would still like to understand why, the exception is happening. Thanks!

![Recording 2023-12-19 at 11 19 48](https://github.com/microsoft/vscode/assets/21997664/a84172bb-cb94-4c45-9f4a-452c63504c9b)

2023-12-19 11:17:57.406 [info] > git config --get commit.template [376ms]
2023-12-19 11:17:57.407 [info] > git rev-parse --show-toplevel [365ms]
2023-12-19 11:17:58.247 [info] > git rev-parse --show-toplevel [448ms]
2023-12-19 11:17:58.370 [info] > git check-ignore -v -z --stdin [588ms]
2023-12-19 11:17:58.508 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab refs/remotes/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab [673ms]
2023-12-19 11:17:58.514 [info] > git rev-parse --show-toplevel [254ms]
2023-12-19 11:17:58.788 [info] > git status -z -uall [238ms]
2023-12-19 11:17:59.042 [info] > git config --get commit.template [190ms]
2023-12-19 11:17:59.230 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab refs/remotes/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab [359ms]
2023-12-19 11:17:59.509 [info] > git status -z -uall [247ms]
2023-12-19 11:18:00.571 [info] > git merge-base refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab [187ms]
2023-12-19 11:18:00.759 [info] > git rev-list --count --left-right refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab...refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab [172ms]
2023-12-19 11:18:00.759 [info] fatal: failed to stat 'refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab...refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab': Filename too long
2023-12-19 11:18:01.119 [info] > git merge-base refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab [210ms]
2023-12-19 11:18:01.331 [info] > git rev-list --count --left-right refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab...refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab [202ms]
2023-12-19 11:18:01.332 [info] fatal: failed to stat 'refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab...refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab': Filename too long
2023-12-19 11:19:02.791 [info] > git merge-base refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab [130ms]
2023-12-19 11:19:02.916 [info] > git rev-list --count --left-right refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab...refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab [117ms]
2023-12-19 11:19:02.916 [info] fatal: failed to stat 'refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab...refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab': Filename too long
2023-12-19 11:19:03.791 [info] > git merge-base refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab [163ms]
2023-12-19 11:19:03.928 [info] > git rev-list --count --left-right refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab...refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab [127ms]
2023-12-19 11:19:03.928 [info] fatal: failed to stat 'refs/heads/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab...refs/remotes/origin/feature/VENDCONCENTRIX-1332-ui-dev-build-gda-layout-and-add-other-information-tab': Filename too long

**Comment by sivavemulapalli** [comment]
> @sivavemulapalli, thank you! Could you please invoke the "Git: Show Git Output" and share the logs? I am working on a fix, but I would still like to understand why, the exception is happening. Thanks!

![Recording 2023-12-19 at 11 34 27](https://github.com/microsoft/vscode/assets/21997664/5fc6db7b-d512-4616-96a9-a66a84a142f5)

None of the click functionalities seems to be working in Source control panel correctly. The results of the click actions reflect after we restart the click handler

Here is the git log you requested.

2023-12-19 11:17:57.406 [info] > git config --get commit.template [376ms]
2023-12-19 11:17:57.407 [info] > git rev-parse --show-toplevel [365ms]
2023-12-19 11:17:58.247 [info] > git rev-parse --show-toplevel [448ms]
2023-12-19 11:17:58.370 [info] > git check-ignore -v -z --stdin [588ms]
2023-12-19 11:17:58.508 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [673ms]
2023-12-19 11:17:58.514 [info] > git rev-parse --show-toplevel [254ms]
2023-12-19 11:17:58.788 [info] > git status -z -uall [238ms]
2023-12-19 11:17:59.042 [info] > git config --get commit.template [190ms]
2023-12-19 11:17:59.230 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [359ms]
2023-12-19 11:17:59.509 [info] > git status -z -uall [247ms]
2023-12-19 11:18:00.571 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [187ms]
2023-12-19 11:18:00.759 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [172ms]
2023-12-19 11:18:00.759 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long
2023-12-19 11:18:01.119 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [210ms]
2023-12-19 11:18:01.331 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [202ms]
2023-12-19 11:18:01.332 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long
2023-12-19 11:19:02.791 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [130ms]
2023-12-19 11:19:02.916 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [117ms]
2023-12-19 11:19:02.916 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long
2023-12-19 11:19:03.791 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [163ms]
2023-12-19 11:19:03.928 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [127ms]
2023-12-19 11:19:03.928 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long

**Comment by sivavemulapalli** [comment]
@lszomoru Here is another example with git log

![Recording 2023-12-19 at 13 16 19](https://github.com/microsoft/vscode/assets/21997664/90107f16-3805-4e94-ad8f-231f4a2b7d4d)

2023-12-19 12:17:28.041 [info] Log level: Info
2023-12-19 12:17:28.041 [info] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2023-12-19 12:17:28.345 [info] Using git "2.43.0.windows.1" from "C:\Program Files\Git\cmd\git.exe"
2023-12-19 12:17:28.575 [info] > git rev-parse --show-toplevel [195ms]
2023-12-19 12:17:28.773 [info] > git rev-parse --git-dir --git-common-dir [182ms]
2023-12-19 12:17:28.790 [info] Open repository: c:\Users\K99999\workspace\YYYYY\YYYYYCodebase\smartform-web-app
2023-12-19 12:17:29.008 [info] > git config --get commit.template [193ms]
2023-12-19 12:17:29.026 [info] > git rev-parse --show-toplevel [192ms]
2023-12-19 12:17:29.131 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [278ms]
2023-12-19 12:17:29.216 [info] > git rev-parse --show-toplevel [182ms]
2023-12-19 12:17:29.406 [info] > git status -z -uall [251ms]
2023-12-19 12:17:29.444 [info] > git rev-parse --show-toplevel [214ms]
2023-12-19 12:17:29.698 [info] > git config --get commit.template [251ms]
2023-12-19 12:17:30.153 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [694ms]
2023-12-19 12:17:30.741 [info] > git check-ignore -v -z --stdin [303ms]
2023-12-19 12:17:30.785 [info] > git status -z -uall [325ms]
2023-12-19 12:17:38.488 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [148ms]
2023-12-19 12:17:38.613 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [117ms]
2023-12-19 12:17:38.613 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long
2023-12-19 12:17:38.745 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [123ms]
2023-12-19 12:17:38.868 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [116ms]
2023-12-19 12:17:38.869 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long
2023-12-19 12:17:38.932 [info] > git check-ignore -v -z --stdin [119ms]
2023-12-19 13:15:28.459 [info] > git add -A -- C:\Users\K99999\workspace\YYYYY\YYYYYCodebase\smartform-web-app\src\app\src\mocks\handlers.js [206ms]
2023-12-19 13:15:28.736 [info] > git config --get commit.template [257ms]
2023-12-19 13:15:28.859 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [367ms]
2023-12-19 13:15:28.880 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [226ms]
2023-12-19 13:15:29.119 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [220ms]
2023-12-19 13:15:29.119 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long
2023-12-19 13:15:29.295 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [157ms]
2023-12-19 13:15:29.398 [info] > git status -z -uall [519ms]
2023-12-19 13:15:29.578 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [265ms]
2023-12-19 13:15:29.578 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long
2023-12-19 13:15:29.828 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [214ms]
2023-12-19 13:15:30.037 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [193ms]
2023-12-19 13:15:30.038 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long
2023-12-19 13:15:32.954 [info] > git add -A -- C:\Users\K99999\workspace\YYYYY\YYYYYCodebase\smartform-web-app\src\app\src\mocks\browser.js [139ms]
2023-12-19 13:15:33.160 [info] > git config --get commit.template [186ms]
2023-12-19 13:15:33.224 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [237ms]
2023-12-19 13:15:33.269 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [165ms]
2023-12-19 13:15:33.442 [info] > git status -z -uall [200ms]
2023-12-19 13:15:33.454 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [169ms]
2023-12-19 13:15:33.454 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long
2023-12-19 13:15:33.616 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [151ms]
2023-12-19 13:15:33.780 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [153ms]
2023-12-19 13:15:33.781 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long
2023-12-19 13:15:33.997 [info] > git merge-base refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [197ms]
2023-12-19 13:15:34.149 [info] > git rev-list --count --left-right refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab [132ms]
2023-12-19 13:15:34.149 [info] fatal: failed to stat 'refs/heads/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab...refs/remotes/origin/feature/XXXXXXXXXXXXXX-1332-ui-dev-build-zzz-layout-and-add-other-information-tab': Filename too long

**Comment by lszomoru** [comment]
@sivavemulapalli, thank you very much! That is really helpful.

Today's VS Code Insiders release contains some improvements around error handling, as well as additional logging. Could anyone on this issue download the latest Insiders release and see if they are still able to reproduce the issue where in the Source Control tree is not updating as expected:

```
Version: 1.86.0-insider (Universal)
Commit: a017b12b9caa3475675cfe6fda014fcf5af388c9
Date: 2023-12-19T05:38:28.077Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.1.0 
```

**Comment by sivavemulapalli** [comment]
@lszomoru From my observation, looks like the issue is happening only when the git branch name is long. Source control panel is working fine when the branch name is short. 

Please compare the git logs from this post and my previous post.

![Recording 2023-12-20 at 11 18 04](https://github.com/microsoft/vscode/assets/21997664/86bc38aa-9e76-40b6-ba8d-a54d73c87250)

2023-12-20 11:17:13.356 [info] > git add -A -- C:\Users\EEEEEEE\workspace\YYYYY\YYYYYCodebase\smartform-web-app\src\app\src\pages\Summary\RRR\ConfigurePortal\OtherInfoTab\Voucher\Voucher.tsx [156ms]
2023-12-20 11:17:13.528 [info] > git config --get commit.template [159ms]
2023-12-20 11:17:13.573 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/RRR-Initial-Setup refs/remotes/feature/RRR-Initial-Setup [193ms]
2023-12-20 11:17:13.744 [info] > git status -z -uall [162ms]
2023-12-20 11:17:15.819 [info] > git config --get commit.template [158ms]
2023-12-20 11:17:15.909 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/RRR-Initial-Setup refs/remotes/feature/RRR-Initial-Setup [230ms]
2023-12-20 11:17:16.151 [info] > git status -z -uall [217ms]
2023-12-20 11:17:19.611 [info] > git branch [142ms]
2023-12-20 11:17:19.745 [info] > git reset -q HEAD -- C:\Users\EEEEEEE\workspace\YYYYY\YYYYYCodebase\smartform-web-app\src\app\src\pages\Summary\RRR\ConfigurePortal\OtherInfoTab\Voucher\Voucher.tsx [119ms]
2023-12-20 11:17:19.925 [info] > git config --get commit.template [172ms]
2023-12-20 11:17:19.964 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/RRR-Initial-Setup refs/remotes/feature/RRR-Initial-Setup [202ms]
2023-12-20 11:17:20.147 [info] > git status -z -uall [166ms]
2023-12-20 11:17:22.123 [info] > git config --get commit.template [167ms]
2023-12-20 11:17:22.184 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/feature/RRR-Initial-Setup refs/remotes/feature/RRR-Initial-Setup [215ms]
2023-12-20 11:17:22.444 [info] > git status -z -uall [251ms]

**Comment by owattley-rotageek** [comment]
I can confirm this only seems to happen on branch names that are long. In my case the branch name was 106 chars.

> Does the issue get resolved in you set scm.showIncomingChanges and scm.showOutgoingChanges settings to false?

Yes.

**Comment by owattley-rotageek** [comment]
> @sivavemulapalli, thank you very much! That is really helpful.
> 
> Today's VS Code Insiders release contains some improvements around error handling, as well as additional logging. Could anyone on this issue download the latest Insiders release and see if they are still able to reproduce the issue where in the Source Control tree is not updating as expected:
> 
> ```
> Version: 1.86.0-insider (Universal)
> Commit: a017b12b9caa3475675cfe6fda014fcf5af388c9
> Date: 2023-12-19T05:38:28.077Z
> Electron: 27.1.3
> ElectronBuildId: 25612240
> Chromium: 118.0.5993.159
> Node.js: 18.17.1
> V8: 11.8.172.18-electron.0
> OS: Darwin arm64 23.1.0 
> ```

I confirm it still happens on insiders 1.86.0. See screenshot. Notice there are no "commit" buttons anywhere, nor are there any changes displayed even though I've modified a file.

<img width="766" alt="image" src="https://github.com/microsoft/vscode/assets/133657588/0e59c584-12b5-415d-bdda-45555e1fa314">

**Comment by TrevorDMartin** [comment]
Ran into this issue today. After reading comments I tried renaming my git branch and it fixed it. 

Branch with error MYSCT-3757_outbound-wip_update-dash
Branch without error MYSCT-3757_outbound-wip

Attempted to replicate in a different repo but was not succesful.

**Comment by lszomoru** [comment]
This issue has been fixed starting with today's VS Code Insiders release.
```
Version: 1.86.0-insider (Universal)
Commit: 4caba0473af34a2b128cedc46f6b13316aae9226
Date: 2024-01-08T05:37:49.269Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0
```

**Comment by probit2** [comment]
Same thing occurred to me. I was attempting to find a solution for this issue and reached out to these comments. After reading the comments, I renamed my branch because it happened to a specific branch. I double-checked it with another branch, and after renaming that long branch name, the source control issue was resolved for me.

**Comment by lszomoru** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/200636
