### ISSUE TITLE
ERROR starting extension host

### ISSUE THREAD

**Issue by nikolas6** [Microsoft/vscode#20168]
- VSCode Version: 1.9.0 (portable version)
- OS Version: Win 7 (behind corporate proxy)

After updating to 1.9.0, I keep getting ERROR starting extension host. All of my extensions are not loaded anymore.

1.8.1 version does not have this problem.

**Comment by mgoku** [comment]
Got the same issue.

In my case, it is caused by the new version of ESLint plugin (https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).

At first, everything work fine. And then, there are an update for ESLint plugin (I think it was version 1.2.3), so I update it. After update, all my plugin does not work. I update ESLint plugin to the latest version (1.2.5) but still got the error.

So, just now, I uninstall the ESLint plugin, and everything works fine.

I'm not sure, if I should report this issue here or at ESLint repo.

**Comment by nikolas6** [comment]
I tried to disable and uninstall ESLint plugin, but it's still showing the error and extensions are not loaded.
I'll stick with 1.8.1 for now.

**Comment by dbaeumer** [comment]
I think these are two different issues. As @nikolas6 points out he sees this with even ESLint disabled. @mgoku says it is working with ESlint disabled. Can you both open the developer tools and paste what you see in the console here into this issue. To open the developer tools do `Help -> Toogle Developer Tools`

**Comment by dbaeumer** [comment]
@joaomoreno @alexandrudima  does this ring any bell in terms of VS Code not starting anymore after an extension update. The ESLint extension itself can't stop the extension host from starting.

**Comment by nikolas6** [comment]
@dbaeumer here's the log from console. I added the function where the exception occurs. Hopefully that helps in debugging.

```
Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.

ERROR starting extension host
(anonymous function)  @ extensionHost.ts:170
done  @ winjs.base.raw.js:1378
v @ winjs.base.raw.js:1224
enter @ winjs.base.raw.js:901
_run  @ winjs.base.raw.js:1068
_error  @ winjs.base.raw.js:1041
(anonymous function)  @ extensionHost.ts:214

/** ### (anonymous function)  @ extensionHost.ts:170 - Exception occurs within this function ###
  public start(extensionService: MainProcessExtensionService): void {
    this.extensionService = extensionService;

    TPromise.join<any>([this.tryListenOnPipe(), this.tryFindDebugPort()]).then(data => {
      const [server, hook] = <[Server, string]>data[0];
      const port = <number>data[1];

      let opts = {
        env: objects.mixin(objects.clone(process.env), {
          AMD_ENTRYPOINT: 'vs/workbench/node/extensionHostProcess',
          PIPE_LOGGING: 'true',
          VERBOSE_LOGGING: true,
          VSCODE_WINDOW_ID: String(this.windowService.getWindowId()),
          VSCODE_IPC_HOOK_EXTHOST: hook,
          ELECTRON_NO_ASAR: '1'
        }),
        // We only detach the extension host on windows. Linux and Mac orphan by default
        // and detach under Linux and Mac create another process group.
        // We detach because we have noticed that when the renderer exits, its child processes
        // (i.e. extension host) is taken down in a brutal fashion by the OS
        detached: !!isWindows,
        execArgv: port
          ? ['--nolazy', (this.isExtensionDevelopmentDebugging ? '--debug-brk=' : '--debug=') + port]
          : undefined
      };

      // Run Extension Host as fork of current process
      this.extensionHostProcess = fork(URI.parse(require.toUrl('bootstrap')).fsPath, ['--type=extensionHost'], opts);

      // Support logging from extension host
      this.extensionHostProcess.on('message', msg => {
        if (msg && (<ILogEntry>msg).type === '__$console') {
          this.logExtensionHostMessage(<ILogEntry>msg);
        }
      });

      // Lifecycle
      let onExit = () => this.terminate();
      process.once('exit', onExit);
      this.extensionHostProcess.on('error', (err) => this.onError(err));
      this.extensionHostProcess.on('exit', (code: any, signal: any) => this.onExit(code, signal, onExit));

      // Notify debugger that we are ready to attach to the process if we run a development extension
      if (this.isExtensionDevelopmentHost && port) {
        this.windowService.broadcast({
          channel: EXTENSION_ATTACH_BROADCAST_CHANNEL,
          payload: { port }
        }, this.environmentService.extensionDevelopmentPath /* target */);
      }

      // Help in case we fail to start it
      let startupTimeoutHandle: number;
      if (!this.environmentService.isBuilt || this.isExtensionDevelopmentHost) {
        startupTimeoutHandle = setTimeout(() => {
          const msg = this.isExtensionDevelopmentDebugging
            ? nls.localize('extensionHostProcess.startupFailDebug', "Extension host did not start in 10 seconds, it might be stopped on the first line and needs a debugger to continue.")
            : nls.localize('extensionHostProcess.startupFail', "Extension host did not start in 10 seconds, that might be a problem.");

          this.messageService.show(Severity.Warning, msg);
        }, 10000);
      }

      // Initialize extension host process with hand shakes
      return this.tryExtHostHandshake(server).then(() => clearTimeout(startupTimeoutHandle));
    }).done(undefined, err => {
      console.error('ERROR starting extension host');
      console.error(err);
    });
  }
*/

/** ### (anonymous function)  @ extensionHost.ts:214 - Exception occurs within this function ###
  private tryExtHostHandshake(server: Server): TPromise<any> {

    return new TPromise<IMessagePassingProtocol>((resolve, reject) => {
      let handle = setTimeout(() => reject('timeout'), 5 * 1000);
      server.on('connection', socket => {
        clearTimeout(handle);
        const protocol = new Protocol(socket);
        resolve(protocol);
      });
      // }).then(protocol => {
      //  return protocol;

    }).then(protocol => {

      protocol.onMessage(msg => {
        if (msg === 'ready') {
          // 1) Host is ready to receive messages, initialize it
          return this.createExtHostInitData().then(data => protocol.send(stringify(data)));

        } else if (msg === 'initialized') {
          // 2) Host is initialized
          this.messagingProtocol.resolve(protocol);
        }
      });
    });
  }
 */


timeout
(anonymous function)  @ extensionHost.ts:171
done  @ winjs.base.raw.js:1378
v @ winjs.base.raw.js:1224
enter @ winjs.base.raw.js:901
_run  @ winjs.base.raw.js:1068
_error  @ winjs.base.raw.js:1041
(anonymous function)  @ extensionHost.ts:214

Overwriting extension <<.jsx>> to now point to mime <<text/x-jsx>>
Overwriting extension <<.js>> to now point to mime <<text/x-javascript>>
Overwriting extension <<.js>> to now point to mime <<text/javascript>>
Overwriting extension <<.jsx>> to now point to mime <<text/javascript>>
Overwriting extension <<.css>> to now point to mime <<text/x-postcss>>
Overwriting extension <<.scss>> to now point to mime <<text/x-sass>>
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2602  for  smart.splitIntoLines
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2601  for  bookmarks.toggle
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2602  for  bookmarks.jumpToNext
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2600  for  bookmarks.jumpToPrevious
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2604  for  extension.createNewFile
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  170002978  for  docthis.documentThis
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  170068514  for  docthis.documentEverything
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  171182626  for  docthis.documentEverythingVisible
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2591  for  extension.align
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2581  for  insertSequentialNumbers
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to extension.selectSingleQuote
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to lafe.duplicateCode
Conflict detected, command `smart.splitIntoLines` cannot be triggered by ctrl+alt+l due to bookmarks.jumpToNext
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to extension.selectDoubleQuote
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to extension.selectParenthesis
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to extension.selectBackTick
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to extension.selectSquareBrackets
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to extension.selectCurlyBrackets
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to extension.selectParenthesisOuter
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to extension.selectSquareBracketsOuter
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to extension.selectCurlyBracketsOuter
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to extension.selectAngleBrackets
Conflict detected, command `workbench.action.terminal.clear` cannot be triggered by ctrl+k due to extension.selectInTag
```

**Comment by dbaeumer** [comment]
@nikolas6 thanks a lot for the detailed trace!

**Comment by dbaeumer** [comment]
@alexandrudima marking as important to be on the save side since I don't understand how critical this is.

**Comment by sushruth** [comment]
I have the same issue. Unable to use any plugins.

**Comment by mgoku** [comment]
@dbaeumer It was not work even when I disabled ESLint plugin. The issue only gone after I uninstall the plugin.

Just now I reinstall the ESLint plugin, but can't reproduce the bug. I also update another plugin, but still can't reproduce the bug.

**Comment by sushruth** [comment]
Still have the same issue with VSCode 1.9.1

**Comment by jrieken** [comment]
@sushruth Please attach the output from the console (F1 > Toggle Developer Tools > Console) such that we can make sure its the same issue you are seeing

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/20168#issuecomment-278889953 - it looks like the timeout of 5s is being hit. That means the extension host failed to start and connect to the main process within 5 seconds. @nikolas6 What kind of machine is that? A beefy super fast one or something slow or a VM?

**Comment by sushruth** [comment]
@jrieken Sure. Here is what I see in the console:

```
workbench.main.js:134 - ERROR starting extension host(anonymous function) @ workbench.main.js:134
workbench.main.js:134 - timeout(anonymous function) @ workbench.main.js:134
```

This is the promise that is rejected at line workbench.main.js:134 : 

```js
a.TPromise.join([this.tryListenOnPipe(), this.tryFindDebugPort()]).then(function(i) {
```

One more interesting observation : The above error results in not being able to 'format document' and also I cant use any plugins either.

I deleted all the temporary folders (as much as I could find) for the portable VSCode 1.9.1 that I had running and downloaded the insiders edition portable (yesterday's build) and ran that and this error was not seen. Finally I could use all the plugins. But the second time I ran the insiders edition, this error shows up again. 

Hope this information helps

**Comment by jrieken** [comment]
> One more interesting observation : The above error results in not being able to 'format document' and also I cant use any plugins either.

Yeah, the extension host is the process in which all the goodness happens. So when that doesn't come up or fails to talk back to the renderer there is no formatting, validation, or any other extension goodness. 

Remains the question why that happens... Both process (render and extension host) communicate via a named pipe. It seems that the renderer can open the server connection on but it never sees a client connecting (within [5s](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/extensionHost.ts#L214)). When this happens can you check the process tree? For windows the best tool is [process explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx). Start it, find `code.exe`, and search for a leaf node with an argument `--type=extensionHost`. Like I did in this sample: 
<img width="663" alt="screen shot 2017-02-16 at 16 42 48" src="https://cloud.githubusercontent.com/assets/1794099/23028262/24a4d7f2-f467-11e6-99c7-fa74eabaa5b7.png">

If the process doesn't exist it means the process didn't start of crash, if it's there is means it cannot connect to the renderer..

**Comment by nikolas6** [comment]
@jrieken the machine is quite fast. 16 GB RAM and with SSD. VSCode starts really slow for me (30 - 60 secs). Given that it is a company-issued-machine, most likely there is some software like anti-virus that keeps scanning the machine behind the scene. I read that anti-virus causes performance issue on electron-based-app (A side-note, Atom editor starts as slow for me too). But, I can live with this.

Does 1.8.1 have the 5s timeout?

**Comment by jrieken** [comment]
@nikolas6 Yeah, the slow startup is likely because of AV software delaying things. With 1.9.x we changed the communication to much faster pipes, in 1.8.1 we used a different mechanism that doesn't have a timeout. 

It would be of great help if you can try find the extension host process as I have described here: https://github.com/Microsoft/vscode/issues/20168#issuecomment-280367382

**Comment by sushruth** [comment]
@jrieken Here is what processexp had to say -

![processexp screenshot](http://i.imgur.com/puZCTA6.png)

**Comment by nikolas6** [comment]
@jrieken sorry, my computer blocks running the process explorer tool. I have limited options in terms of software I can run on my machine.

**Comment by jhirth** [comment]
I have the same issue on my slow netbook.

I suggest to make the timeout user-definable and/or to use significantly larger values.

Ideally, this should be handled in the same way as browsers do it. If a script takes too long, the runaway timer kicks in and a dialog pops up which gives the user the option to wait or to stop the script.

**Comment by jrieken** [comment]
I have pushed a change that increases the timeout from 5 seconds to 1 minute. I hope no one actually has such bad startup perf (5s is already bad). Please try with tomorrows insider build.

**Comment by sushruth** [comment]
@jrieken So, today's ? (2017-02-20)

**Comment by jrieken** [comment]
No, 21st

**Comment by sushruth** [comment]
@jrieken Update : 

I ran the Insider's build for Feb 21 2017 and the errors mentioned in the [above comment](https://github.com/Microsoft/vscode/issues/20168#issuecomment-280354211) **do not appear**. However, the original issue is still not fully fixed, in the sense that I wont be able to access 'format document' from command palette or from right click menu for quite a while after openning the app.

I guess this could be considered solved but it may not be working in an optimal way.

Thanks @jrieken for helping us with the issue!

**Comment by jrieken** [comment]
>  I wont be able to access 'format document' from command palette or from right click menu

That seems like a different issue. Formatting availability depends on the language and the installed extensions. By default we only ship with formatting support for a few languages and for most extensions are needed. And then it also makes a difference if the extension support for format a selection or the whole document. If you see issues with that please file a separate issue outline all above things

Closing this issue because the extension host now seems to start successfully

**Comment by sushruth** [comment]
@jrieken I understand your explanation but I was using the fact that `format document` and options alike, which use the extension host, show up only when the extension host is up and can be connected to by the renderer. Also, it was a JS file I was trying to use `format document` on, which I know VSCode supports. Basically the different between when the exrtension host is successfully connected to, and otherwise (in the right click menu) is as below: 

Before Extension host gets connected - 

![Before connection](http://i.imgur.com/49ui3fa.png)

After it gets connected -

![Before connection](http://i.imgur.com/qGjdcoW.png)

Just noting that's all. But this specific issue at hand is definitely gone. Thanks!

**Comment by nikolas6** [comment]
@jrieken thanks for the help.
I tried the insider build today, and I don't see the error anymore. I noticed all the extensions and settings I have in the stable version are missing. Is that expected behaviour of insider build version?
I tried to install some extensions, and they seem to work fine.

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/20168#issuecomment-281414094 - That is the expected behaviour. Even the JavaScript and TypeScript language services runs in the extension host. The only difference is that they are bundled with the product, but technically they are extensions like any other extensions. So, also running in the extension host and also being only available once that has started

**Comment by cleidigh** [comment]
please excuse my brevity ,syntax and formatting - I'm disabled and dictating...

after wrestling with these issues with the standard v1.9.1 code, I have been using the insider code 2-23 Release. I can only intermittently get the debugging to work experimenting with the hello world extension 

OS Windows 7 Professional (VM on Mac Mini) - 16GB with very good performance

if Ithe Boolean stop on entry in the launch file I can sometimes get debugging to work perhaps one out ten times. in the case that it works it hits a breakpoint at line fourteen of bootstrap.js

if I continue at that point any breakpoints I set an extension will be hit as well in the extension will properly function . in all other cases the debug instance of code starts but gives the warning of the debugger host not starting in ten seconds. the breakpoint in bootstrap.js it's never hit. 

I can also see residual processes that do not exit when code is closed. after several experiments.

after reading everything above I can't see how this is closed. am I missing something?

thanks Christopher...

**Comment by jrieken** [comment]
> after reading everything above I can't see how this is closed. am I missing something?

Yeah, this issue isn't about debugging but about the extension host (the process in which extensions, not debuggers reside) which doesnt start due to other software delaying startup by more than 5sec

**Comment by aeschli** [comment]
Marked as verified based on [@nikolas6  comment](https://github.com/Microsoft/vscode/issues/20168#issuecomment-281543453)

**Comment by cleidigh** [comment]
jrieken:

Agree this is about the extension host and start up time co- mingled in this thread.
I don't think my setup is that slow of course not the fastest either. however your comment from four days ago clearly indicated you bumped the time out to one minute. this should be in the two twenty three build, yes? I still see a message timeout at ten seconds. I also understood perhaps incorrectly , settings stop on entry = true avoid this timeout as a workaround. 

either way the extension host remains an issue. so two questions:
1 to I start another issue?
2 any workarounds?

apologize I'm new to this process...6

**Comment by manishkp** [comment]
Hi Team,
I am not sure what am I missing.
I have windows 10 machine with VS code vscode veriosn: 1.12.2 installed.
I have the 'ms-vscode.csharp' extension installed on and the intellisense didnt work.

I get the following console logs:

shell.ts:199 Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.
(anonymous) @ shell.ts:199
extensionHost.ts:172 ERROR starting extension host
(anonymous) @ extensionHost.ts:172
extensionHost.ts:173 timeout
(anonymous) @ extensionHost.ts:173

Process explorer shows the  vscode ---extensionhost is running
![image](https://cloud.githubusercontent.com/assets/5002685/26716898/a7d5b3c6-47be-11e7-8426-24521976ede5.png)

Can you guys help?
thanks
Manish

**Comment by manishkp** [comment]
Finally got this working by manually editing the timeout limit in
C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\electron-browser\workbench.main.js

Can we make this a config value, so that slower machines can be catered for ?

Thanks
Manish

**Comment by beeplin** [comment]
@manishkp I encountered this issue too on my slow machine. Can you specify which part did you changed in the `C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\electron-browser\workbench.main.js`

**Comment by jhirth** [comment]
@beeplin Search for `"timeout"` (with quotes). Change the `6e4` value next to it to `6e5` or whatever.

(For what it's worth, the 1 minute default works fine for my ancient netbook.)

**Comment by beeplin** [comment]
@jhirth thanks!
