### ISSUE TITLE
Disappointment with the Latest VSCode Update

### ISSUE THREAD

**Issue by ArtistArthur** [microsoft/vscode#204269]
Dear VSCode Team,

I am writing to let you know that I am deeply disappointed and frustrated with the latest update to Visual Studio Code. As a dedicated user, I have supported and advocated for VSCode, trusting that the development team values its user base and strives to maintain compatibility across updates.

It has come to my attention that the recent update has introduced significant compatibility issues, which have been disruptive to my work and, I believe, to the work of many others in the community. It is particularly disheartening to see that these issues were known yet seemingly disregarded in the decision to push forward with the release.

I am struggling to understand the rationale behind releasing an update that alienates loyal users, and I am concerned about the direction in which VSCode is heading. This situation has eroded my trust in the product and has left me questioning whether I can rely on VSCode for my future development needs.

I urge the VSCode team to consider the impact of such updates on its user community and to take immediate steps to address these concerns. It is crucial to remember that the success of VSCode is built on the support of its users, and it is those same users who are now feeling neglected.

I hope my message conveys the seriousness of the situation and prompts a re-evaluation of the update strategy. I look forward to a response that acknowledges these issues and outlines how they will be rectified.

Sincerely

**Comment by IllusionMH** [comment]
Is this abstract/generalized feedback or you have concrete issue you want developers to know about?

More concrete examples would be easier to address.

**Comment by ArtistArthur** [comment]
Just for the new requirement of minimum GLIBC >= 2.28.
This problem has had a significant negative impact on our productivity and workflow. It is crucial for our team to have a stable and reliable development environment, and unfortunately, the new version of VSCode does not meet our needs at this time.
Maybe we just not deserve new vscode version.
We and many other teams just can not upgrade glibc version for many reason, have you considered our feelings and future?
Have you truly developed with the user, who have many non-technical consumers, in mind, or are you just a group of academicians?

**Comment by kohs100** [comment]
This is very frustrating issue since the glibc version requirement applies not only for vscode itself, but also the server automatically installed to the target machine when we perform remote development with ssh.

**Comment by RedCMD** [comment]
https://github.com/microsoft/vscode/issues/204238

**Comment by kohs100** [comment]
> #204238

Yeah I followed the related issues from the exact day of 1.86 auto-update happened.

Temporary workaround with skipping the version check or using legacy server binary cannot be the counterargument for this kind of issue.

**Comment by npurson** [comment]
Check the workaround here: https://github.com/npurson/vscode-server-toolchain-workaround.

**Comment by kohs100** [comment]
> Check the workaround here: https://github.com/npurson/vscode-server-toolchain-workaround.

The fact that this kind of workaround exists and works well means that the requirement upgrade was completely unnecessary...
And again, "workaround" can not be appropriate answer for people who want a "stable and reliable development environment".

**Comment by SonGokussj4** [comment]
Happened to me when connecting to Synology NAS 918+ (DSM 7.2)

**Comment by albireox** [comment]
At the risk of adding to what seems more like a rant than a useful discussion about innovation vs stability, I want to defend the VSCode developers, even if myself have been affected by the `glibc` issue.

First and foremost, VSCode is a free and open-source product, even if it's developed and supported by a big tech company. To me that must always change the tone and expectations when communicating with the developers, and the tone used by the OP and some of the posters is, in my opinion, inappropriate.

The requirement for `glibc>=2.28` has been noted as a future deprecation for some time. Arguably, that's not something a lot of people look at, and a better job could have been done explaining what the deprecation entailed, but I think anybody that works in tech knows that deprecations are required in the lifetime of a product. Some of the systems that have stopped being supported are objectively old, even if they are still very much in use and some of them have not reached EOL.

Moreover, the developers have been very active in dealing with the fallback (and very impolite comments) and if one digs a bit it seems clear that a solution to this problem is probably going to be released as a recovery version. So it's hard to argue that the development team does not listen to the users.

But more importantly, if stability is paramount for a user and losing an hour trying to understand why something has stopped working and downgrading is unacceptable, why upgrading in the first place? People wait months, sometimes years to upgrade their OS (which ironically it's part of the reason why we are here), making sure they are fully stable, so why upgrade VSCode the first day a new version is available? My guess is that we do it for the innovations that a new version may bring, but expecting innovation and infinite backwards compatibility seems a bit naive. And it's not as if 1.85.2 has disappeared.

I'm not arguing that this `glibc` has not been a mid-sized clusterf*ck, although I appreciate the development team being willing to accept user feedback on this. But I really think the tone of the OP is not really appropriate here.

**Comment by kohs100** [comment]
> why upgrade VSCode the first day a new version is available?

vscode auto-updates itself by default, like windows.

**Comment by zdietzen** [comment]
So what solutions do I have to fix this complete dumpster fire of an update? I can no longer do any development at work and am stuck trying to get VS Code to work.

**Comment by kohs100** [comment]
> So what solutions do I have to fix this complete dumpster fire of an update? I can no longer do any development at work and am stuck trying to get VS Code to work.

You can wait for 1.86.1 recovery release (maybe next week) or temporarily, reinstall vscode with 1.85 version and disable auto-update.

**Comment by gfub** [comment]
I don't see this post or this situation as negative but rather as an opportunity for VSCode to make improvements.

The issue is not that SSH Remote failed for many users, it's that communication about the issue is unclear. There are dozens of issues created about the issue and it's hard to tell what is a valid issue vs not. Which one do I look for to understand a high-level perspective of the issue, current workarounds, and progress as to when to fix the issue?

VSCode doesn't have a status page highlighting prominent issues with a release and how they are looking to address them. For me, this would help build up people's confidence that a fix is on the way. It doesn't even have to be a status page but it could just be a section on the [updates post](https://code.visualstudio.com/updates/v1_86). Directing people where to look for a fix is very important when an auto-update breaks something.

The closest thing I've found to [an update is on this issue here](https://github.com/microsoft/vscode/issues/203375) or [maybe this one here](https://github.com/microsoft/vscode/issues/204344), and that took me longer to find then it did to downgrade to a previous version.

**Comment by arthurmloureiro** [comment]
Are there plans to roll back or support legacy servers?

The latest update broke for many the ability to use VS Code on remote servers.
It is easier to learn how to use Vim on some remove servers and stop using VS Code than to expect these servers to update to the new requirements VS Code is imposing with no warnings to users.

**Comment by kohs100** [comment]
> Are there plans to roll back or support legacy servers?
> 
> The latest update broke for many the ability to use VS Code on remote servers. It is easier to learn how to use Vim on some remove servers and stop using VS Code than to expect these servers to update to the new requirements VS Code is imposing with no warnings to users.

Recovery update #204344 will give vscode ability to impose warning "connecting to an OS that is unsupported by VS Code" when connecting to the machines with deprecated glibc version by providing old version of binary during initial deployment of code server, not roll-backing the glibc requirement for vscode.

I'm searching alternatives of vscode or considering os upgrade already 😂

**Comment by connor4312** [comment]
1.86.1 has been released that includes the legacy server (https://github.com/microsoft/vscode/issues/204344) for older GLIBC versions

**Comment by tomKl97** [comment]
> 1.86.1 has been released that includes the legacy server (#204344) for older GLIBC versions

I still get an error after update-ing to 1.86.1 that the "The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++", but the connection is successful. Does that mean that, I can ignore the notification and proceed with work?

**Comment by connor4312** [comment]
Yes, however we plan to only support the 'legacy server' for a year.

**Comment by IllusionMH** [comment]
Would it be possible to download legacy server in a year with portable VS Code (and updates disabled) and version for remove extension is fixed?

**Comment by connor4312** [comment]
Yes, just like users who downgraded to 1.85, old versions of VS Code will continue to work

**Comment by tlc** [comment]
> Yes, however we plan to only support the 'legacy server' for a year.

"You are connected to an OS version that is unsupported by Visual Studio Code."

So, supported or unsupported?

**Comment by yubin-ai** [comment]
Amazon Linux 2 system only has 2.26. a tons of instance built on it wont work with the new vs code. the new update is indeed not great.

**Comment by xgdgsc** [comment]
How can people stick with 1.85.2 when https://github.com/microsoft/vscode/issues/204270 is not fixed?
