### ISSUE TITLE
search in files focus resets when line changed

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#20467]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-62-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|glslx-vscode|evanw|0.0.8|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|mono-debug|ms-vscode|0.13.0|
|debugger-for-chrome|msjsdiag|2.5.3|
|arduino-vscode|steveyin|0.2.0|

---

Steps to Reproduce:

1. ctrl-shift-f search for a string that appears at least 3 times
2. hit F4 a TWO times to go to the 2nd result.
  - notice how in the search window the focused result is hilighted
3. now, edit the file (that contains the 2nd search result) so the line in that file no longer matches the search criteria.
 - notice how the 2nd search result disappears from the search results pane, and NO results are hilighted.
4. hit F4 again.
  - BUG: the first search result is hilighted.

expected: F4 should progress to the new 2nd search result (which was previously the 3rd result).

this bug breaks the process of using F4 to skip through results selectively editing, since every time you make an edit you have to start back at the beginning of the result. for hundreds of results, and many to skip repeatedly, this is extremely annoying.

**Comment by Spongman** [comment]
there's a race condition. if you hit F4 _immediately_ after the edit is made, then _sometimes_ it does the right thing.

**Comment by Spongman** [comment]
it even breaks if you insert a blank line above the search result.

eg:
- search
- f4
- home
- enter
- f4

takes you 1st search result *twice*

**Comment by roblourens** [comment]
@bpasero, I want to preserve the focused element across a refresh of the tree, but this isn't really possible because search results don't have an identity across a change in the editor. 

So what I want to do to make this a little better is to record that the, say, 25th match in file X is focused. Then refresh the tree. Then focus the 25th element in file X. We don't have a fast way to determine this from outside the tree, so I would probably implement this in the tree itself (with a option to selectively enable it) to restore the focused item by index after a refresh.

Does that make sense, or any other ideas? I thought it would be easier.

**Comment by bpasero** [comment]
@roblourens please consult with @joaomoreno , but if your tree items have no identity across a refresh I think it will be hard to preserve the selected element. Is it not possible to give the items the same identity?

**Comment by roblourens** [comment]
Sorry I can't keep track of who knows what. After an edit, the selected result will be at a different location, so unless you know what the edit did, you can't know that the selected match at line 5 column 7 is now at line 8 column 2.

**Comment by roblourens** [comment]
Similar case - after deleting a file in the explorer, the next file should be selected. Currently the selection jumps up to the folder that file was in.

**Comment by ramya-rao-a** [comment]
@roblourens Moving to March since you are not here ...

**Comment by rlundy** [comment]
So given that this keeps getting reported and then closed as a duplicate, it seems like a lot of people would really like for this to be fixed.  I'm certainly one of them.

Visual Studio handles this just fine.

Is there a reason Visual Studio Code can't?

**Comment by rbellamy** [comment]
The purpose of a search is often to make changes manually - this bug makes `F4` unusable for anything but the most naive use.

**Comment by grandich** [comment]
VS Code is great, but I miss Notepad++ in this one. Seems difficult to resolve.

**Comment by Daijobou** [comment]
The error is really very annoying. I'm searching in a system that has hundreds of folders and all files in these folders have the same file name. As soon as you change something in a file, the marking of the file disappears from the search file list. This makes you crazy. You can hardly see the markings anyway.

One way to mitigate the problem would be to give the file a prominent icon or marker in the search list (NOT THE CODE LINE).
This way you would at least still see in which file you are and which file you have to view and edit next.

**Comment by roblourens** [comment]
This is actually fixed by https://github.com/microsoft/vscode/issues/126964, rejoice

**Comment by OliverJAsh** [comment]
> expected: F4 should progress to the new 2nd search result (which was previously the 3rd result).

The behaviour I'm seeing is not what was described as the expected behaviour in this issue. The behaviour I'm now seeing: F4 progresses to the new 3rd search result (which was previously the 4th result).

**Comment by roblourens** [comment]
I see... now the list preserves the selected index in the list, but the result for F4 will be effectively skipping an item

We still need an F4 specific fix here. If you expect F4 to move focus to the next item after the removed one, and shift+F4 to move to the previous item before the removed one, there is nowhere we can put list focus that will satisfy this. So F4 needs to check whether the currently focused row index is now a different item that has not yet been revealed in the editor. Not what that actually looks like in code.

**Comment by russelldavis** [comment]
IntelliJ addresses this by never removing any items from the list. If a line is edited and no longer matches, the item remains in the list, but changes to the text "INVALID" (and the color changes to red). Seems like a nice, easy way to fix this.

**Comment by Spongman** [comment]
Visual Studio (since VC++ 2.0, _not_ vscode) handled this by placing temporary, invisible bookmarks in the open file at the matching lines and referred to those bookmarks in the search results. If the open file was edited then the bookmarks would move, but the search results would defer to the correct location.

**Comment by andreamah** [comment]
Actually, I believe this is already fixed in the latest version.

https://github.com/microsoft/vscode/assets/31675041/71607ce1-85f2-4234-8ded-04c3260f571a

**Comment by rcdailey** [comment]
@andreamah Not quite, I think. In your video, after editing the search result, focus moved to the *next* search result but without changing the opened file (which is understandable since you're actively editing it). So when you jump to the next result, you're actually skipping one result I think.

**Comment by andreamah** [comment]
I was testing for the original issue, oops. Thanks for pointing that out.

**Comment by Daijobou** [comment]
Still not working for:
Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

After edit selected line, without change search results, highlight is gone. Searched for ",abc" and changed it to ",123,abc".

**Comment by jaredplowman** [comment]
I can confirm this issue is back and driving me insane.  You'll see in the following video that when I change Id -> Guid the search resets to the first item in the list.

![Fork_iffZFVCZ5X](https://github.com/microsoft/vscode/assets/18597960/a808775f-7f07-47d9-b289-393c6b114508)

**Comment by Daijobou** [comment]
Can this please be corrected, it is so tedious to work through search lists when the marker in the file list keeps disappearing.

**Comment by break11** [comment]
In version 1.94.0 the bug is still there. The search window is now completely broken. You can't search for something and press F4 to cycle through the search results. After editing in any result file the search results window is completely refreshed.

**Comment by break11** [comment]
Is it possible to simply add the setting "update the search list after editing files included in the result". In my experience, it is not important to me that the search result after editing a file changes the line correctly on the fly. It is much more important to save the current edited element when switching to F4. If I need to, I can call the search list update manually - this is not a problem.

**Comment by HFriberg** [comment]
Here is a workaround until the bug is fixed:
 1. Use ctrl-shift-f to get a list of matching files.
 2. Use ctrl-f (with the same query), and press F3 to iterate over matches within a file (works as expected with respect to editing).
 3. When you are done with a file, use the dismiss feature of the ctrl-shift-f menu. This one mouse click sends you to the next matching file where F3 works immediately. 

Until the bug is resolved, this workaround gets the job done with only one mouse click per file, and one F3 per match.

**Comment by joeytwiddle** [comment]
Thanks for the [tip](https://github.com/microsoft/vscode/issues/20467#issuecomment-2456746392) @HFriberg. For anyone who wants to remap that, the command is `search.action.remove`. I couldn't find it in Command Palette. It currenty looks like:
```
{
  "key": "cmd+backspace",
  "command": "search.action.remove",
  "when": "fileMatchOrMatchFocus && searchViewletVisible"
}
```
Not an ideal solution, but better than sticking with the current (mis)behaviour.

**Comment by Spongman** [comment]
i really don't think this can be fixed without implementing a bookmark system that tracks line positions over edits. for example, moving a line that contains a search result up/down in the file using Alt+Up/Dn to move a selected block of lines should also move the bookmark that the search result refers to (and the ordering of the search result potentially updated). any system that links search results to line numbers in files is broken.
