### ISSUE TITLE
VSCode freezes/blocks at startup

### ISSUE THREAD

**Issue by cedelavergne-ledger** [microsoft/vscode#206510]
Hello,

VSCode is very long to start, juste showing a blank window for up to 10 sec. Sometimes, I also have a popup window proposing to kill/restart or wait.
Also, after VSCode is finally started, after a couple of minutes, it freezes for again few seconds (10-20) before being fully operationnal.
This behavior only concern the 1st open window. If I open a new one, no issue.
Also, if I close all the open windows, and then open again VSCode, the issue is reproduced.

I have tried tu play with different options like `--disable-extensions` and `--disable-gpu`, but without any improvements...
I have also tried to fully remove VSCode and the extensions, and then reinstall, but I still have the same behavior.

My system is:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
$ uname -a
Linux LPFR0237 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

## System Info

* Code: 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2)
* OS: linux(6.5.0-21-generic)
* CPUs: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz(8 x 4075)
* Memory(System): 31.06 GB(27.07GB free)
* Memory(Process): 284.92 MB working set(194.28MB private, 0.97MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Attached profiling files (with option `--prof-startup`)

[prof-uwGrxS2H.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/14444635/prof-uwGrxS2H.renderer.cpuprofile.txt)
[prof-uwGrxS2H.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/14444634/prof-uwGrxS2H.main.cpuprofile.txt)

## Attached generated report (with option `--prof-startup`)

[report.md](https://github.com/microsoft/vscode/files/14444720/report.md)

**Comment by Pnlvfx** [comment]
My is crashing on startup

**Comment by roblourens** [comment]
This step seems slow. Nothing happening in the main process. The renderer profile crashes vscode when I try to open it (filed an issue)

`| window.loadUrl() => begin to require(workbench.desktop.main.js) | 18966    | [main->renderer]          | NewWindow                                                  |`

**Comment by BagelOrb** [comment]
Having the same exact issue, with the same versions. 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
$ uname -a
Linux tk-Katana-GF66-12UEOK 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

I've tried vscode 1.87.0, 1.86.2 and 1.86.1, but to no avail.

Is there a workaround?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by cedelavergne-ledger** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Is it just a tests to check as is, or did you really fix something arround that? Because removing evrything (up to the config and extensions) to reinstall a temporary version, and then, maybe, going back to the official one is a little bit paintful...

**Comment by bpasero** [comment]
It can be installed side by side easily. Yeah we constantly fix things.

**Comment by cedelavergne-ledger** [comment]
> It can be installed side by side easily. Yeah we constantly fix things.

ok, good. So a naive question: how to install it side by side (on ubunto 22.04)?

**Comment by bpasero** [comment]
There are packages (DEB, RPM) from https://code.visualstudio.com/insiders/

**Comment by cedelavergne-ledger** [comment]
> There are packages (DEB, RPM) from https://code.visualstudio.com/insiders/

Same result...

**Comment by bpasero** [comment]
Thanks for trying!

Moving to Deepak, since this seems to be time spend in Electron given:

```
window.loadUrl() => begin to require(workbench.desktop.main.js)
```

Which is time spend in Electron as far as I know.

**Comment by BagelOrb** [comment]
I had some CUDA issues as well, but when I fixed those I managed to start vscode without issues. 

I did an `sudo apt purge nvidia-*` and also a `sudo apt purge *nvidia*535*`because I messed up installing new drivers. Then `sudo apt autoremove` and `sudo apt install nvidia-driver-535`. Note that nvidia-driver-535 is not the latest driver, but it is the latest driver supporting my specific laptop GPU.

@cedelavergne-ledger have you checked whether you have driver issues?

**Comment by Destroy666x** [comment]
This optimization  issue occurs also on Windows, see https://github.com/microsoft/vscode/issues/206691#issuecomment-1974899735

**Comment by cedelavergne-ledger** [comment]
Hi,
Any news on this ticket?
Any other idea?

**Comment by kdmurray** [comment]
Still seeing this on 1.88.1; Kubuntu 23.10.

19 seconds to get to the welcome screen (consistently) on a freshly imaged system.

**Comment by Spirit4471** [comment]
Still have same problem, VS Code is really slow at Windows, and WSL2 Ubuntu 22.04. 
Always freeze at start, and has not respond show in the window.
I can't fix this problem even uninstall and install again.

**Comment by VictorSago** [comment]
Same issue on Debian Testing with v1.91.1. It worked fine yesterday, but today it freezes for several minutes on launch.

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux trixie/sid
Release:        n/a
Codename:       trixie
~$ uname -a
Linux ZeronDtp2 6.9.9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.9-1 (2024-07-13) x86_64 GNU/Linux
```

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.9.9-amd64

I tried running it with `--disable-extensions --disable-gpu --disable-software-rasterizer`, but it still freezes. I'm attaching part of the output of running vscode with `--verbose`. This is the point where it freezes for around 5 minutes with no activity that I can see, after which it resumes and seems to work normally.
I also have vscode-insiders installed, but the behaviour is exactly the same!


[vscode-verbose-start-202407191417-edited.txt](https://github.com/user-attachments/files/16312002/vscode-verbose-start-202407191417-edited.txt)

Btw, `--disable-software-rasterizer` isn't a known option.

**Comment by boutell** [comment]
I am experiencing the same thing on Ubuntu 12. I tried:

* --disable-extensions
* --disable-gpu --disable-software-rasterizer
* Uninstalling and uninstalling via the apt route

No dice. Still locking up the vscode process either immediately or as soon as I click into any subfolder.

**Comment by Destroy666x** [comment]
@deepak1556 this is a very serious issue for certain users. Any progress here? If you need more debugging info, please let us know.

**Comment by kdmurray** [comment]
I tried removing the `--disable-gpu --disable-software-rasterizer`  arguments from startup on 1.97.2 and vscode launched normally. Not sure if there's been anything done specifically for this issue or not? Has anyone else managed to replicate the issue on more recent versions?

**Comment by retnag** [comment]
I have the same issue. When running `code --verbose` it also hangs on `[EncryptionMainService] Checking if encryption is available...` - but reinstalling gnome-keyring didn't help in my case... after a short while however it either crashes, or finishes loading succesfully, its still very annoying though.
