### ISSUE TITLE
options field in tasks.json with terminal runner does not seem to actually do anything for "env" or "cwd" parameters

### ISSUE THREAD

**Issue by dolphy01** [Microsoft/vscode#20678]
- VSCode Version: 1.9.1
- OS Version: Ubuntu 16.04 / KDE Neon Developer Edition (Plasma 5.9.2)

```
Version 1.9.1
Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Date 2017-02-08T23:44:55.542Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

Linux hostname 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I can not seem to get the "env" or "cwd" parameters to actually apply to tasks defined in tasks.json.

Steps to Reproduce:

1. create the directory /tmp/options_bug
2. create the subdirectory /tmp/options_bug/test_dir
3. open new vscode instance with the workspace of /tmp/options_bug
4. define a tasks.json file as follows:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "_runner": "terminal",
    "tasks": [
        {
            "taskName": "env-test1",
            "command": "env | grep TESTING_ENV",
            "isShellCommand": true,
            "showOutput": "always",
            "options": {
                "env": {
                    "TESTING_ENV": "THIS IS A TEST"
                },
                "cwd": "test_dir/"
            }
        },
        {
            "taskName": "env-test2",
            "command": "echo Test: ${env.TESTING_ENV}",
            "isShellCommand": true,
            "showOutput": "always",
            "options": {
                "env": {
                    "TESTING_ENV": "THIS IS A TEST"
                },
                "cwd": "test_dir/"
            }
        },
        {
            "taskName": "cwd-test1",
            "command": "pwd",
            "isShellCommand": true,
            "showOutput": "always",
            "options": {
                "env": {
                    "TESTING_ENV": "THIS IS A TEST"
                },
                "cwd": "test_dir/"
            }
        },
        {
            "taskName": "cwd-test2",
            "command": "cd test_dir;pwd",
            "isShellCommand": true,
            "showOutput": "always",
            "options": {
                "env": {
                    "TESTING_ENV": "THIS IS A TEST"
                },
                "cwd": "test_dir/"
            }
        }
    ]
}
```

I expect to see the TESTING_ENV environment variable defined in the environment and accessible. That does not seem to be the case.

I expect the tasks to start in the current working directory of "test_dir", but instead they start in the workspace directory as normal. The "cwd-test2" task exists solely to prove that the directory in question is available and accessible.

Output from the tasks:

**[env-test1]**
`PTYSHELLARG1=env | grep TESTING_ENV`
`Press any key to close the terminal`

**[env-test2]**
`Test:`
`Press any key to close the terminal`

**[cwd-test1]**
`/tmp/options_bug`
`Press any key to close the terminal`

**[cwd-test2]**
`/tmp/options_bug/test_dir`
`Press any key to close the terminal`

**Comment by dbaeumer** [comment]
@dolphy01 if a task defines its own command the command must list all necessary options necessary. There is no inheritance with global options. IMO it simply makes things hard to understand if for example both define env options. 

So in our case you need to reiterate the options settings for each task. But I am open for suggestion how global definable options would best work.

**Comment by dolphy01** [comment]
@dbaeumer I didn't realize that globally applied options for tasks which define their own commands was not supported. I understand moving that to a feature request, thank you! I do have a few thoughts on that behavior, but that conversation can be separated from this issue.

I do still have the same issue, however, even with locally defined options for each task. I will update the description to reflect the new tasks.json file I use for reproducing.

**Comment by dolphy01** [comment]
#20740

**Comment by dbaeumer** [comment]
Need to validate. I am pretty sure I fixed this already for the next release. E.g. honoring envs.

**Comment by dolphy01** [comment]
@dbaeumer I've confirmed with the following Insider build that most of the issues are resolved, but there still seems to be an issue. While the env variables are placed in the shell environment, accessing the env variables using with ${env.VARIABLE} notation still doesn't work:

Version 1.10.0-insider
Commit 40fecfaa77f01672e8a147be71f6f7ccb9cf8a12
Date 2017-02-27T14:13:35.653Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

The task at issue is env-test2:

```
        {
            "taskName": "env-test2",
            "command": "echo Test: ${env.TESTING_ENV}",
            "isShellCommand": true,
            "showOutput": "always",
            "options": {
                "env": {
                    "TESTING_ENV": "THIS IS A TEST"
                },
                "cwd": "${workspaceRoot}/test_dir/"
            }
        },
```

**[env-test2]**
Test:
Press any key to close the terminal

**Comment by dbaeumer** [comment]
@dolphy01 this is a chicken egg problem. The tasks spawns a new process however which gets the env defined in options. ${env.TESTING_ENV} is evaluated when spawning the process. There is nothing I will do about this (it is basically as designed). If you need to get this working please inline the env variable into the command :-).
