### ISSUE TITLE
launch.json preLaunchTask

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#2086]
I have several issues with it:

1. it appears that it at least partially ignores the configuration of the named task in the ``tasks.json``. For example, if I have a task ``watch:scss`` with ``"showOutput": "never"`` there - running it manually doesn't invoke new tab with output, but if I also add it to ``launch.json`` via ``"preLaunchTask": "watch:scss"`` - it opens output every time I re/launch the app. However it seems that it does respect the ``isWatching`` flag, since it doesn't start the app until I terminate the task manually if the setting is false/omitted or it does start the app if the setting is set to true.
2. if the task is a persistent one (``"isWatching": true``) relaunching the app prompts me to terminate the already running one. And it doesn't start the app right away if I chose to terminate it in the prompt - I need to run it again. Which is annoying as hell as you can imagine. There should be an additional setting for either silently restarting the ``preLaunchTask`` or silently skip the task launch and assuming that the already running should run until the end of the current session. And/or there should be a default based on the either - in any case prompting is not an option.
3. ``preLaunchTask`` is hardly present in the documentation at all. I think many more people would complain if they just knew that this option even exist...

thanks in advance.

**Comment by isidorn** [comment]
Thanks for the detailed feedback.

1. It seems like `taskService.run` does not respect configuration specified in `tasks.json` @dbaeumer
2. There has already been some issues regarding this. I personally am not a big fan of that terminate promp. @dbaeumer can comment more
3. I see `preLaunchTask` being mentioned in https://code.visualstudio.com/docs/editor/debugging, though not to a great extenent. Also preLaucnhTask is present in auto completion in `launch.json`. To increase discoverability I added `preLaunchTask: ''` to the initally generated `launch.json`

Since issues 1. and 2. are in the task world forwarding this to @dbaeumer

**Comment by dbaeumer** [comment]
@isidorn 
1. I do :-). As @Spown pointed out everything works when he runs the task directly. Could it be that the debugger brings the output channel to front to inform about problems with the prelaunch task.
2. I don't see what the task runner framework should do. IMO the debugger framework should do the following: for non watching task wait for the promise to finish. For watching tasks don't start if promise is not finish and listen to task events to see if the task is currently active or not. If needed I can add API to differenciate better between watchind and non watching tasks

**Comment by isidorn** [comment]
1. The issue was on my side, just pushed a fix
2. I fixed this 5 days ago and it should be available as part of our next release (start of March) - same as 1.

**Comment by Spown** [comment]
I appreciate the work and staff, but I fail to see how is the "new" mechanic regarding the watching task is different from the one before (original post/subissue 2.)? I get slightly different warning but I still get it. The point was not to be bugged while relaunching. But I still get the prompt[terminate|close] -> regardless of the choice the launch won't occur until the next launch initiated by the user. Thats still 3 actions instead of one.

**Comment by Spown** [comment]
And if i take ``isWatching`` flag away - It starts the task and nothing happens. I need to hit F5 again for the launch to occurs. Actually without ``isWatching`` it works more like it should - since every subsequent relaunch doesn't invoke any prompts. The task is still a watching one, since it keeps running, and VSCode assumes it should continue running. I'm confused.

**Comment by isidorn** [comment]
Thanks for coming back with more feedback. Is your last comment captured in bug #3669?
For the previous comment - regarding subissue 2, I can not reproduce this. So I have a watch task, I start debugging again and you get prompted? I do not see this. Can you please create a new issue if you see this on latest vscode (0.10.10) with reproducable steps - it would be great if you could share your repo.

Thanks

**Comment by daslicht** [comment]
How does the task.json need to look if you want to call it as PreLaunchTask?

I tried it like this, but it fails : 

```
"preLaunchTask": "mytask",
```

```
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "showOutput": "silent",
    "args": [""],
    "problemMatcher": "$tsc",

    "tasks": [
        {
            "taskName": "mytask",
            "args": [],
            "isBuildCommand": true,
            "problemMatcher": "$tsc"
        }
    ]
}
```

**Comment by dbaeumer** [comment]
If you only have one global task you can use the command name as a prelaunch task name.

```json
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "showOutput": "silent",
    "args": [""],
    "problemMatcher": "$tsc"
}

"preLaunchTask": "tsc"
```

**Comment by daslicht** [comment]
OK I tried now : 
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Node",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/app.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}/.",
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "preLaunchTask": "tsc",
            "sourceMaps": true,
            "outDir": null
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858
        }
    ]
}
```
```
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "showOutput": "silent",
    "args": [""],
    "problemMatcher": "$tsc"
}

```
But I get :
```
The preLaunchTask 'tsc' terminated with exit code 2.
```

**Comment by dbaeumer** [comment]
Do you have a tsconfig.json. Then your args need to look like ["-p", "."]

**Comment by daslicht** [comment]
Yes I have the following tsconfig:
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "sourceMap": true,
        "allowJs": true
    },
   "exclude": [
        "node_modules",
        "typings"
    ]
}
```
When I change the args in my tasks.json or launch jscon to 
```
 "args": ["-p","."],
```

I get :  

```
Errors detected while running the preLaunchTask 'tsc'.
```

**Comment by dbaeumer** [comment]
@daslicht is your repository public somewhere. Then I have a look there.

**Comment by daslicht** [comment]
Nope, not yet but I can push it, until that which files would you else need to look at else then above ?
Thank You !

**Comment by dbaeumer** [comment]
Hard to say. Most of the time it is a file layout thing as well. Can you try another thing. Can you run the tasks by pressing Ctrl+Shift+B and then show the output of the Task (Shift+Ctrl+U) and attach it here.

**Comment by daslicht** [comment]
SOLVED !:
I never thought that warning could make the pretask fail.

I had such warning: 
```
daslicht:radio1 daslicht$ tsc 
typings/main/ambient/bluebird/index.d.ts(21,13): error TS2300: Duplicate identifier 'Promise'.
typings/main/ambient/bluebird/index.d.ts(358,11): error TS2300: Duplicate identifier 'Promise'.
typings/main/ambient/bluebird/index.d.ts(670,19): error TS2300: Duplicate identifier 'Promise'.
typings/main/ambient/es6-promise/index.d.ts(14,15): error TS2300: Duplicate identifier 'Promise'.
typings/main/ambient/es6-promise/index.d.ts(45,16): error TS2300: Duplicate identifier 'Promise'.
```

After removing bluebird and all its dependencies the task is running ! 

:dancer: 

Thank you !

**Comment by ipanardian** [comment]
It works! Thanks

Task.json
```
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["-p", "."],
    "showOutput": "silent",
    "problemMatcher": "$tsc"
}
```

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "sourceMaps": true,
            "outFiles": ["${workspaceRoot}/out/*.js"],
            "preLaunchTask": "tsc"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858,
            "outFiles": [],
            "sourceMaps": true
        }
    ]
}
