### ISSUE TITLE
Cannot hide breadcrumb icons

### ISSUE THREAD

**Issue by RobinWragg** [microsoft/vscode#209943]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: Windows 11 and macOS Sonoma

Steps to Reproduce:

1. Go to user settings and uncheck "Breadcrumbs: Icons"
2. View a source file. Breadcrumbs still have icons.

**Comment by marlapativ** [comment]
It looks like this was fixed in 1.88.1

**Comment by aishwarya-chamanoor** [comment]
Me neither. I too tried on 1.88.1.
I tried verifying for xml, text, powershell scripts files.
Unable to repro the issue.

**Comment by TejasQ** [comment]
I think this bug may be open to misinterpretation because _icons_ and _code symbols_ may be confused with each other. To clarify, here's a little video repro where we can observe that unchecking the box indeed hides _icons_, but does not hide the purple symbol. 

Personally I don't think this is a bug, but it may be unexpected behavior because of this conflation.

https://github.com/microsoft/vscode/assets/9947422/3ea51f5e-183d-4126-9907-b61c538ec110

**Comment by RobinWragg** [comment]
@TejasQ Thanks for clarification, I think this is indeed unexpected behavior, as I was confused why the breadcrumbs still contained any images after unchecking the setting. I would argue that the code symbol is also an icon.

I would personally like to see one of these changes made, if others agree?
- Either introduce a new checkbox to hide/show code symbols, and a change in the description of "Breadcrumbs: Icons" to clarify what it does.
- Or change the "Breadcrumbs: Icons" checkbox to hide/show all icons, including the code symbols.

**Comment by RobinWragg** [comment]
Update: I've concluded this is actually a bug, not just unexpected behavior.

The breadcrumbs and the Outline use the same rendering code in documentSymbolsTree.ts. When Outline icons are disabled in the settings, the code symbol icons disappear from the Outline. This doesn't happen in the breadcrumbs.

In breadcrumbsControl.ts, symbol icons are mentioned explicitly at line 326:
```
const options: IBreadcrumbsControlOptions = {
	...this._options,
	showFileIcons: this._options.showFileIcons && showIcons,
	showSymbolIcons: this._options.showSymbolIcons && showIcons
};
```
But the result of `showSymbolIcons` is ignored. That's the cause of the bug.

**Comment by raphaelgpalma** [comment]
There is an issue with version 1.88.0 that is no long available. However, if you update to version 1.88.1, this problem is resolved.

**Comment by RobinWragg** [comment]
@raphaelgpalma Is there a particular bugfix you are referring to? I have updated to the latest 1.88.1 and there are still code symbol icons in the breadcrumbs when "Breadcrumbs: Icons" is unchecked, unlike the Outline, which correctly hides all icons when "Outline: Icons" is unchecked.

**Comment by kousiksatish** [comment]
@raphaelgpalma and @RobinWragg, I am able to reproduce this and if it you can confirm this needs a fix, I can take a stab at fixing this.

@RobinWragg, as you mentioned, the "Outline: Icons" and "Breadcrumbs: Icons" are behaving differently.

@jrieken can you please assign this to me?

**Comment by RobinWragg** [comment]
Thanks @kousiksatish, I do believe this needed a fix. This bug still exists for me in version 1.90.0.

**Comment by y0sh1ne** [comment]
@RobinWragg I think I found the original reason of this problem. [problem code](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/parts/editor/singleEditorTabsControl.ts#L60).
It set the `showSymbolIcons: true`

**Comment by y0sh1ne** [comment]
@RobinWragg 
I have found the code to add the breadcrumbs item ([link](https://github.com/microsoft/vscode/blob/7d06e7bd5ccc364af3ce28a946e2d3369634eb5f/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L331)):
```Typescript
const options: IBreadcrumbsControlOptions = {
				...this._options,
				showFileIcons: this._options.showFileIcons && showIcons,
				showSymbolIcons: this._options.showSymbolIcons && showIcons
			};
const items = model.getElements().map(element => element instanceof FileElement ? new FileItem(model, element, options, this._labels, this._hoverDelegate) : new OutlineItem(model, element, options));
```
Clearly, some problem happen in class `OutlineItem`.

The `showFileIcons` and `showSymbolIcons` only in `options`, that means this 2 property not mentioned in `model` and `element`.

And in class `OutlineItem`, this `options` only used in method `OutlineItem.equals()`, that means this 2 property not mentioned in method `OutlineItem.render()` which I think is used to render the breadcrumbItem.

So I have no ideal about how this `showFileIcons` and `showSymbolIcons` work. 

I think it's most likely something wrong happend in [code](https://github.com/microsoft/vscode/blob/7d06e7bd5ccc364af3ce28a946e2d3369634eb5f/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L87):
```Typescript
class OutlineItem extends BreadcrumbsItem {
        ...
	render(container: HTMLElement): void {
                ....
		const template = renderer.renderTemplate(container);
		renderer.renderElement(<ITreeNode<any, any>>{
			element,
			children: [],
			depth: 0,
			visibleChildrenCount: 0,
			visibleChildIndex: 0,
			collapsible: false,
			collapsed: false,
			visible: true,
			filterData: undefined
		}, 0, template, undefined);
                ....
        }
}
```

**Comment by williamsk91** [comment]
@jrieken first time contributor here, please tell me if I'm doing anything wrong 🙇🏻 

Maybe we can update [src/vs/workbench/contrib/codeEditor/browser/outline/documentSymbolsTree.ts](https://github.com/microsoft/vscode/blob/f3fba4ec23f548876e33a4f4eb32eab6cc37ac96/src/vs/workbench/contrib/codeEditor/browser/outline/documentSymbolsTree.ts#L134) to only prepend the icon when the config is set to true?

```ts
# src/vs/workbench/contrib/codeEditor/browser/outline/documentSymbolsTree.ts:134
	
renderTemplate(container: HTMLElement): DocumentSymbolTemplate {
   ...
   if (this._configurationService.getValue("breadcrumbs.icons")) {
	container.prepend(iconClass);
   }
   ...
}
```

If this looks good, I can open a PR

**Comment by himani-mehra** [comment]
Hi @RobinWragg  , I'm interested in contributing to this issue. Could you please assign it to me? Looking forward to working on it!

**Comment by RobinWragg** [comment]
Hi @himani-mehra, I just logged the bug, I don't have permissions to assign issues.

**Comment by benvillalobos** [comment]
Fixed by https://github.com/microsoft/vscode/pull/216662
