### ISSUE TITLE
VSC crashes almost immediately after launching it. 

### ISSUE THREAD

**Issue by MomSlayerGX** [microsoft/vscode#213041]
* Didn't work
Does this issue occur when all extensions are disabled?: Yes*(I used --disable-extensions parameter in the terminal to achieve that)

- VS Code Version: 1.89.1
- OS Version: Debian 12 with linux kernal 6.6.15

Steps to Reproduce:

1.  Launch code through terminal or app dashboard
2. A window of VSCode pops up with nothing in it, then it crashes after a few seconds.

Steps taken to resolve:

1. Remove any keys related to VSC 
          Result: Same issue persists, there was no key for vsc
2: Run code without gpu or extensions by (`code --disable-extensions --disable-gpu`) in terminal
          Result: Nothing changed
3. Reinstall VSC using apt/nala
          Result: Same issue persists
4. Install insider
          Result: Same as before

Other information
![image](https://github.com/microsoft/vscode/assets/129647390/340530ac-ff3e-4d08-a8ee-272ef3c6ba38)
what vsc looks like before it crashes, ignore the background text that is from --verbose

Result of --verbose with above listed parameters. Only includes some information as it is too long
`
[11029:0520/002048.564240:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[main 2024-05-19T20:50:48.663Z] [File Watcher (node.js)] Request to start watching: /home/quack/.config/Code - Insiders/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/home/quack/.config/Code - Insiders/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
[main 2024-05-19T20:50:48.678Z] Starting VS Code
[main 2024-05-19T20:50:48.678Z] from: /usr/share/code-insiders/resources/app
[main 2024-05-19T20:50:48.678Z] args: {
  _: [],
  diff: false,
  merge: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  'update-extensions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': true,
  'disable-lcd-text': false,
  'disable-gpu': true,
  'disable-chromium-sandbox': false,
  sandbox: false,
  telemetry: false,
  debugRenderer: false,
  'enable-smoke-test-driver': false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'use-inmemory-secretstorage': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '28145a5d-fc2e-4813-b374-cb36002556a7',
  'skip-add-to-recently-opened': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'preserve-env': false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  'disable-gpu-sandbox': false,
  '__enable-file-policy': false,
  'enable-coi': false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  'disable-dev-shm-usage': false,
  'profile-temp': false,
  logsPath: '/home/quack/.config/Code - Insiders/logs/20240520T002048'
}
[main 2024-05-19T20:50:48.679Z] Resolving machine identifier...
[main 2024-05-19T20:50:48.680Z] Resolved machine identifier: 23f6b25a395f8a7f7a2439500703303db53daa51725a20450c251a9c9b9f0b56
[main 2024-05-19T20:50:48.680Z] Main->SharedProcess#connect
[main 2024-05-19T20:50:48.686Z] [File Watcher (node.js)] Started watching: '/home/quack/.config/Code - Insiders/User'
[main 2024-05-19T20:50:48.686Z] [File Watcher (node.js)] ignoring a path for watching who's stat info failed to resolve: /home/quack/.config/Code - Insiders/User/settings.json (error: Error: ENOENT: no such file or directory, stat '/home/quack/.config/Code - Insiders/User/settings.json')
[main 2024-05-19T20:50:48.687Z] StorageMainService: creating application storage
[main 2024-05-19T20:50:48.691Z] ElectronURLListener: waiting for window to be ready to handle URLs...
[main 2024-05-19T20:50:48.691Z] lifecycle (main): phase changed (value: 2)
[main 2024-05-19T20:50:48.691Z] windowsManager#open
[main 2024-05-19T20:50:48.692Z] windowsManager#open pathsToOpen [
  {
    backupPath: '/home/quack/.config/Code - Insiders/Backups/1716151208841',
    remoteAuthority: undefined
  }
]
[main 2024-05-19T20:50:48.692Z] windowsManager#doOpenEmpty {
  restore: true,
  remoteAuthority: undefined,
  filesToOpen: undefined,
  forceNewWindow: true
}
[main 2024-05-19T20:50:48.693Z] IPC Object URL: Registered new channel vscode:12868136-fe49-44af-a237-c05aa4a32be7.
[main 2024-05-19T20:50:48.694Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 448, y: 268, width: 1024, height: 768 }
[main 2024-05-19T20:50:48.694Z] window#validateWindowState: single monitor working area { x: 0, y: 0, width: 1920, height: 1080 }
[main 2024-05-19T20:50:48.694Z] window#ctor: using window state { mode: 1, x: 448, y: 268, width: 1024, height: 768 }
[0520/002048.709956:ERROR:directory_reader_posix.cc(43)] opendir /home/quack/.config/Code - Insiders/Crashpad/attachments/59c50637-32f0-468d-96aa-3db90e3f6b9a: No such file or directory (2)
[main 2024-05-19T20:50:48.752Z] window#load: attempt to load window (id: 1)
[main 2024-05-19T20:50:48.764Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2024-05-19T20:50:48.765Z] lifecycle (main): phase changed (value: 3)
[main 2024-05-19T20:50:48.765Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2024-05-19T20:50:48.766Z] update#setState idle
[0520/002048.785598:ERROR:http_transport_libcurl.cc(472)] curl_easy_perform: Couldn't connect to server (7)
[main 2024-05-19T20:50:48.795Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[11029:0520/002049.256982:ERROR:gpu_process_host.cc(993)] GPU process exited unexpectedly: exit_code=139
[11029:0520/002049.256992:WARNING:gpu_process_host.cc(1364)] The GPU process has crashed 1 time(s)
[0520/002049.394062:ERROR:directory_reader_posix.cc(43)] opendir /home/quack/.config/Code - Insiders/Crashpad/attachments/390301a3-2230-499b-b8c1-c7f748d99b98: No such file or directory (2)
[0520/002049.452297:ERROR:http_transport_libcurl.cc(472)] curl_easy_perform: Couldn't connect to server (7)
[11029:0520/002049.906181:ERROR:gpu_process_host.cc(993)] GPU process exited unexpectedly: exit_code=139
[11029:0520/002049.906190:WARNING:gpu_process_host.cc(1364)] The GPU process has crashed 2 time(s)
[0520/002050.030161:ERROR:directory_reader_posix.cc(43)] opendir /home/quack/.config/Code - Insiders/Crashpad/attachments/866378ea-cb1f-4b7e-92ff-ee7a33802a3e: No such file or directory (2)
[0520/002050.110828:ERROR:http_transport_libcurl.cc(472)] curl_easy_perform: Couldn't connect to server (7)
[11029:0520/002050.554812:ERROR:gpu_process_host.cc(993)] GPU process exited unexpectedly: exit_code=139
[11029:0520/002050.554822:WARNING:gpu_process_host.cc(1364)] The GPU process has crashed 3 time(s)
[0520/002050.676253:ERROR:directory_reader_posix.cc(43)] opendir /home/quack/.config/Code - Insiders/Crashpad/attachments/beb6966c-a6cc-4df9-a074-9500a69bf37e: No such file or directory (2)

`

**Comment by dedWalker18** [comment]
This helped me once.

https://bbs.archlinux.org/viewtopic.php?id=282438

**Comment by MomSlayerGX** [comment]
Adding   "window.titleBarStyle": "custom" results in the application border to disappear and for VSC to become a blue rectaangle. 
Following the steps by gatimus results in me running out of space and nothing else. After reverting the changes from copying the home directory to /etc/skel, VSC gives me new error even without verbose, disable gpu or disable extensions.

sh: 0: getcwd() failed: No such file or directory
Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at O (/usr/share/code/resources/app/out/cli.js:1:2758)
    at out-build/bootstrap-node.js (/usr/share/code/resources/app/out/cli.js:1:2863)
    at /usr/share/code/resources/app/out/cli.js:1:132
    at Object.<anonymous> (/usr/share/code/resources/app/out/cli.js:4:9476)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:101:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
               
sh: 0: getcwd() failed: No such file or directory
Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at O (/usr/share/code/resources/app/out/cli.js:1:2758)
    at out-build/bootstrap-node.js (/usr/share/code/resources/app/out/cli.js:1:2863)
    at /usr/share/code/resources/app/out/cli.js:1:132
    at Object.<anonymous> (/usr/share/code/resources/app/out/cli.js:4:9476)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:101:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

**Comment by isaka-james** [comment]
**Issue Description:**

I have been experiencing a persistent issue with Visual Studio Code on Kali Linux where the editor crashes when opening projects that contain Git files. This issue does not occur when the project does not have Git initialized. Other editors do not seem to have this problem, making me suspect that the issue is specifically related to VS Code's handling of Git repositories.

**Steps to Reproduce:**
1. Open a project in VS Code that does not have a Git repository initialized.
2. Initialize a Git repository in the project (`git init`).
3. Close and reopen the project in VS Code.

**Expected Behavior:**
VS Code should open the project without crashing, regardless of the presence of Git files.

**Actual Behavior:**
VS Code crashes upon attempting to open a project with Git files.

**Screenshots:**

_Crash Screenshot:_
![Crash Screenshot](https://github.com/microsoft/vscode/assets/76619967/4043d3cb-f24d-4214-9423-5896e3e46361)

_Environment Details:_
![Environment Screenshot](https://github.com/microsoft/vscode/assets/76619967/ab2a129b-ca44-4406-a6b0-d467705854c7)

**System Information:**
- **OS:** Kali Linux (been using it for 3 years, issue persists across versions)
- **VS Code Version:** 1.82.2
- **Git Version:** git version 2.43.0


**Additional Information:**
I have to remove the `.git` files to be able to use VS Code. This problem does not occur with other editors on the same system.

**Comment by MomSlayerGX** [comment]
Hi, I have installed Linux Debian on my windows drive as it has more space and is faster and on VSC there is no issue. I can launch it with no parameter like for example --disable-gpu. I still have my old drive with Linux Debian with the malfunctionning VSC to attempt. As for the comments left by [isaka-james](https://github.com/isaka-james), I am not able to open any file or folder in VSC tho I will try running it in a clean folder with no .git.

**Comment by isaka-james** [comment]
@MomSlayerGX  I switched to vim, when they'll resolve this issue I will come back to vscode. So how come you are writing code in 2024 without git? Very frustrating !

**Comment by MomSlayerGX** [comment]
Not sure if it works but if you are using kde can you switch from wayland(or whatever it is called) to xorg/x11 (or whatever it is called), maybe it might solve the issue.
It can be changed in the login screen of linux desktop envoirment

**Comment by isaka-james** [comment]
So how do that relate to vscode quitting when it is associated projects with git?
I will try your suggestion and give feedback.. but recently I tested my friends Kali Linux OS they behave the same way(quitting when projects have git)

**Comment by hierro59** [comment]
In my case the problem is a new version of VSCode from snap. To solve it I had to revert to the previous version with the command 
`snap revert code`

**Comment by isaka-james** [comment]
@hierro59 I installed Vscode using apt. And yesterday I reinstalled again the vscode but still the same problem.

And I tested from my Friend Pc(who is using Kali Linux as me) who said for him it worked fine but when I added git, the vscode started to crash.But when you remove the .git from the project vscode just worked fine.

But how can you code without git 😔

**Comment by isaka-james** [comment]
For my case: 
I was able to update the vscode to 1.91.1 and the problem was successfully solved.

But for all previous versions are encountering with the same issue(Kali Linux).

**Comment by hierro59** [comment]
> For my case: I was able to update the vscode to 1.91.1 and the problem was successfully solved.
> 
> But for all previous versions are encountering with the same issue(Kali Linux).

Correct, everything is solved with the version

**Versión: 1.91.1**
Confirmar: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Fecha: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
SO: Linux x64 6.5.0-41-generic snap

**Comment by LucasMLara** [comment]
Just installed the last version and keeps crashing. 

Using W11. 

intalled in differente ssd's and the first time , last month, worked. (1.95.2) went to a trip, 20 days passed. just arrived home to work and now , dont work either.

installed last version from internet (1.95.3) and still dont work.

**Comment by MomSlayerGX** [comment]
@LucasMLara Can you try completely deleting VSC(config, settings, extensions etc) and reinstalling version 1.19.1 which seems to work for some people, or install the earliest version of VSC that used to work on your computer, in other words the first version of VSC you installed on the computer.

Do backup important data of VSC so it is easier to set it up after a fresh install.

Also, try to update your OS, and see the history of windows updates to see if any update time matches the time when VSC started to crash and perhaps roll them back if possible.

As for anyone else who might have this problem on Linux, something to note is that when I first got this issue on my old install of Linux before I reinstalled it, my Apt source was unstable(Sid)  so I got updates sooner but they might have more problem compare to stable which is default. If your Apt source is not stable, I would recommend you to set it back to stable and update(followed by a restart) to see if VSC code is fixed, as a recent update might have broken it.

**Comment by rzhao271** [comment]
Hi all, it sounds like there could be multiple issues here considering there are multiple platforms being referenced.
For anyone who is still seeing crashes on VS Code 1.96 or later, could you attach a crash report to this issue following the steps at [Creating a Crash Report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report)?
