### ISSUE TITLE
Linux file dialog does not use default file path

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#213780]
Testing #213763

Version: 1.90.0-insider
Commit: fc8762e773c35d4e52e8a7375704af2e24698e5d
Date: 2024-05-29T05:51:07.154Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 5.15.0-107-generic

- open a file in an editor
- run `File > Open FIle`. This opens a file selection dialog initialized to the home folder

> It should open on the folder of the currently active editor

**Comment by aeschli** [comment]
Same problem with open folder dialog

**Comment by manelio** [comment]
VS Code is awesome, but the open file dialog on Linux has been ridiculously buggy for years.

More than two years to fix the problem of the dialog opening in the background.

The fix, in the latest version, involves using a dialog inside a portal with no type-ahead support that opens in $HOME or recent files.

The open/save file dialog is a crucial control in any application. There should be a way to use the native OS dialog.

I'm going to downgrade to the previous version and keep it as long as it takes.

**Comment by bpasero** [comment]
cc @codebytere

**Comment by deepak1556** [comment]
We hadn't patched the portal code to support most of the file dialogs options, it is being addressed via https://github.com/electron/electron/pull/42308.

**Comment by deepak1556** [comment]
This is now addressed in the runtime via https://github.com/electron/electron/pull/42655, fix will be available once we adopt https://github.com/microsoft/vscode/pull/215406

**Comment by deepak1556** [comment]
Reopening since we have reverted the updated due to other regressions https://github.com/microsoft/vscode/pull/223494, will be revisited in August.

**Comment by RES-1** [comment]
https://github.com/electron/electron/issues/42250#issuecomment-2280440103

**Comment by bpasero** [comment]
This issue is not resolved for me, here is for comparison how the file dialog opens in an older version of VS Code vs. now:

**Good** behaviour:


![Image](https://github.com/user-attachments/assets/b15ada76-be82-4895-bfe0-6cbd8a2fdb1a)



**Bad behaviour:**


![Image](https://github.com/user-attachments/assets/0d0d8d61-3528-4a67-aec3-3e1fbb593365)

**Comment by bpasero** [comment]
Filed https://github.com/electron/electron/issues/43310

**Comment by riccardomanfrin** [comment]
I'm on xfce on xubuntu 22.04.
Version **1.89.1-1715060508_amd64** does not have the issue.
Later versions do have it.

The problem is that  instead of forcing the "Open File" path, to that of the current file being edited, vscode delegates the path selection to the operating system, which resolves the "Recent Files" path.


Since recent files is truly not useful in vscode, I can at least pilot the path to be that of the home folder with

    $> gsettings set org.gtk.Settings.FileChooser startup-mode 'cwd'
    
from the previous `recent` value. Clearly this is very inconvenient. Is there any update about it?

**Comment by drankinatty** [comment]
The issue is not resolved for me either. The file-open and directory-open dialogs still do not appear even though built on Electron 30.1.2. This is reproducible 100% of the time in openSUSE Tumbleweed and in Leap.

**Comment by drankinatty** [comment]
The file-open/directory-open or save dialog not being shown remains unresolved on Linux in release 1.93.1 built with electron 30.4.0.

**Comment by drankinatty** [comment]
The file-open/directory-open or file-save dialog not being shown remains unresolved on Linux in release 1.94,

Triggering a file-open/directory-open/file-save dialog is fundamental to do anything useful with an application. I can see one release having one hiccup and there being a temporary issue, but this vital function for Linux users seems to have been broken for an extended period of time. Nothing on my setup has changed, it's a simple x-windows setup that supports native x-windows dialogs, Qt dialogs (KDE) and Gtk dialogs (Gimp Toolkit, now more Gnome toolkit). There are also wx-widgets dialogs available.

The last release to provide a working file-open/save dialog on Linux is:

```none
Version: 1.89.1
Release: 24130
Commit: a045dcfceda27f896936bfd8cbf524f6a93a2f46
Date: 2024-05-09T18:30:40.866Z
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.11.2-1-default
```

Judging from the dialog opened in 1.89 it seems to be triggering the Gtk file-open dialog, the same triggered by file-open in firefox, e.g.

![Image](https://github.com/user-attachments/assets/5e30a795-2ce6-499e-ace8-67b24bb70ce2)

This needs to be fixed. There are many improvements between ver. 1.89 and 1.94 that are simply not available to Linux users (unless they go to extreme measures to manage open files from the command-line, unrealistic)

I'm happy to test if you come up with a scenario that needs testing. I'm currently running openSUSE Tumbleweed, so all packages are standard and are current versions.

**Comment by deepak1556** [comment]
@drankinatty can you start v1.94 with `code --verbose --vmodule=*/ui/*=2`, trigger the open file dialog action and attach the output here.
