### ISSUE TITLE
Tree: Cancelling the file creation by scrolling causes the Explorer shows not correctly

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#22269]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. open a folder such as "vscode-master"
2. expand folder "build" then "monaco"
3. click the "New File" button, then scroll to cancel the file creation
4. do step 3 again (sometimes not needed)
5. collapse and expand "monaco" for several times, the Explorer shows not correctly

When the Explorer shows not correctly, scrolling makes it even worse..
And when something like this happens, we have to reopen VSCode to make it normal.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by King66** [comment]
Seems to still have problem, here is a screenshot of video 0:0:39
![1](https://cloud.githubusercontent.com/assets/11925432/23738840/437ebb14-04d6-11e7-8f68-dabae34e5153.jpg)

[VSCodeExplorer.zip](https://github.com/Microsoft/vscode/files/829974/VSCodeExplorer.zip)

**Comment by bpasero** [comment]
@King66 thanks, I can reproduce!

@joaomoreno looks like another tree bug to me similar to the one we fixed last week!

**Comment by joaomoreno** [comment]
Awesome steps!

**Comment by justincy** [comment]
Closing and opening the Explorer pan will reset it and resolve the problem without having to restart VSCode.

**Comment by justincy** [comment]
Actually closing and reopening the Explorer view just changes the issue. The scrolling problem stops but now I have files disappearing and being out of order.

**Comment by CherryDT** [comment]
By the way, this bug still exists, more than one year after this issue was created.

I'm on this version/system:

```
Version 1.23.0-insider
Commit ab56a0952b9c2ff7add6404f80ebf9398cf8ae51
Date 2018-04-17T05:16:42.105Z
Shell 2.0.0-beta.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64
```

Screencast: http://recordit.co/21kC41SMaB

**Comment by yume-chan** [comment]
Relates to #68821

The behavior is changed in release 1.31, scrolling no longer cancels file creation, but the content of input box is lost when scrolling.

**Comment by joaomoreno** [comment]
This appears fixed.
