### ISSUE TITLE
Snippet tabstop selecting content of previously entered variable only works when separated by space

### ISSUE THREAD

**Issue by codepunkt** [Microsoft/vscode#23728]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Create and load snippet for language javascript:
    ```json
    "import": {
      "prefix": "imp",
      "body": "import ${2:${1:module}} from '${1:module}'$0",
      "description": "Default import"
    }
    ```
2. Open .js file, type `imp`
3. Press `TAB`, type `styled-components` (you now have `import styled-components from 'styled-components'`)
4. Press `TAB` again, cursors don't move and you could now continue typing at the end of what you just typed. This is unexpected.

Expected:

4. Press `TAB` again, the first `styled-components` is selected and you can start typing to overwrite it, e.g. by pressing `TAB` and typing `styled`, creating `import styled from 'styled-components'`

The whole thing works as expected when the snippet body is this: `import ${2: ${1:module}} from '${1:module}'$0` - except that you then have a whitespace where you didn't want one.

**Comment by jrieken** [comment]
For better multi-cursor support we replace the snippet controller and that also fixed this issue

![jun-02-2017 12-13-08](https://cloud.githubusercontent.com/assets/1794099/26721638/ddf41dd0-478c-11e7-95f7-3d9c99b109dd.gif)

**Comment by chrmarti** [comment]
Still an issue when you accept the content assist's proposal instead of exiting content assist with Escape.

**Comment by jrieken** [comment]
@chrmarti You were seeing #27898  which we fixed late

**Comment by chrmarti** [comment]
- VSCode Version: Code - Insiders 1.13.0-insider (eaa887c507e1614f90c9f04a30ceda775759e814, 2017-06-06T10:23:09.381Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|cpptools|ms-vscode|0.11.4|;

Still an issue:
![23728](https://user-images.githubusercontent.com/9205389/26843340-c928b3b4-4aa4-11e7-8bdd-ba32e7d983c1.gif)

**Comment by jrieken** [comment]
not severe for May
