### ISSUE TITLE
Terminal `clear` or `cls` command does not fully clear the screen, leaving behind a scrollbar

### ISSUE THREAD

**Issue by mohiwalla** [microsoft/vscode#239237]
When I execute the clear command in the integrated terminal of VS code, the terminal is not actually cleared. Only the text disappears, scrollbar remains there.

Does this issue occur when all extensions are disabled? Yes

```bash
Version: 1.96.4
Commit: cd4ee3b1c348a13bafd8f9ad8060705f6d4b9cba
Date: 2025-01-16T00:16:19.038Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.96.4 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
```

Steps to Reproduce:

1. Open the integrated terminal in VS Code.
2. Run multiple commands to get some long output, like I used JS code in video or just press enter key multiple times.
3. Execute the `clear` or `cls` command depending upon your OS.

The terminal doesn't get to it original state like a native terminal does, a scrollbar remains.

Expected Behavior: There should be no scrollbar in terminal after clearing it.
Actual Behavior: The text inside the terminal gets cleared, but the size of the terminal window doesn't get back to original.

Additional Context: I have attached a video demonstrating the issue.

https://github.com/user-attachments/assets/81e26e71-3569-4aa5-b20c-bafcf19384cc

**Comment by meganrogge** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Comment by mohiwalla** [comment]
Hey, this issue occurs in VS code on windows as well but the original video clip is from `Arch Linux KDE (plasma)`.
I've tested it on other linux distros Ubuntu, Debian and Kali linux as well and the issue persists everywhere.
And in windows, it doesn't even clear the entire text present if the buffer, just hides it and sometimes even overlapes with new commands due to sticky scroll.

> Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

This bug doesn't occur in any native terminal both on windows and linux.

**Comment by mohiwalla** [comment]
> If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows.
I'm not using and older version of windows its Linux.. 😭
