### ISSUE TITLE
Failed to execute 'createScriptURL' on 'TrustedTypePolicy'

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#240780]
From @bpasero 

When debugging with F5, the following error is seen

```
log.ts:456   ERR Error: Failed to execute 'createScriptURL' on 'TrustedTypePolicy': The provided callback is no longer runnable.
    at amdX.ts:160:33
    at new Promise (<anonymous>)
    at AMDModuleImporter._rendererLoadScript (amdX.ts:137:10)
    at AMDModuleImporter.load (amdX.ts:105:109)
    at importAMDNodeModule (amdX.ts:223:44)
    at encodingExists (encoding.ts:267:22)
    at EncodingOracle.getValidatedEncodingForResource (textFileService.ts:837:16)
    at EncodingOracle.getPreferredReadEncoding (textFileService.ts:811:31)
    at Object.overwriteEncoding (textFileService.ts:318:46)
    at createDecoder (encoding.ts:148:39)
```

**Comment by bpasero** [comment]
A variant of the stack is:

```
ERR Failed to execute 'createScriptURL' on 'TrustedTypePolicy': The provided callback is no longer runnable.: Error: The provided callback is no longer runnable.
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/amdX.js:138:45
    at new Promise (<anonymous>)
    at AMDModuleImporter._rendererLoadScript (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/amdX.js:119:16)
    at AMDModuleImporter.load (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/amdX.js:89:115)
    at importAMDNodeModule (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/amdX.js:197:47)
    at TextMateTokenizationFeature._getOrCreateGrammarFactory (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/textMate/browser/textMateTokenizationFeatureImpl.js:214:70)
    at TextMateTokenizationFeature._createTokenizationSupport (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/textMate/browser/textMateTokenizationFeatureImpl.js:239:47)
    at LazyTokenizationSupport.createSupport (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/textMate/browser/textMateTokenizationFeatureImpl.js:102:96)
    at get tokenizationSupport (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/editor/common/languages.js:599:46)
    at TokenizationSupportFactoryData._create (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/editor/common/tokenizationRegistry.js:114:43)
```

I can reproduce this with a fresh user data dir when F5 debugging and opening a `package.json` file. You can see that coloring is then broken:

<img width="677" alt="Image" src="https://github.com/user-attachments/assets/01cede3d-53ed-40c2-be9c-6de6bbd1c2c0" />

**Comment by deepak1556** [comment]
Some dump for data gathered so far,

* With a custom build that has the log lines in `generated_code_helper` we narrowed the issue happens when the script executes while the page is in paused state https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/generated_code_helper.cc;l=45-48. It also confirmed that the script in question was executing in the main world. So there is no electron specific isolated world stuff interfering with this issue.

* Debugger logs showed a subtle difference that triggers the bug, in the failing case we get `Debugger.ScriptParsed` before `Runtime.runIfWaitingForDebugger`. Question is why does the debugger take longer to send the signal of resuming page execution in the failing case ?

* Also confirmed the frame's pause and resume lifecycle state with the following crash keys

```c++
diff --git a/third_party/blink/renderer/core/execution_context/execution_context.cc b/third_party/blink/renderer/core/execution_context/execution_context.cc
index ead61f60eab68..ba13ae09fe6e3 100644
--- a/third_party/blink/renderer/core/execution_context/execution_context.cc
+++ b/third_party/blink/renderer/core/execution_context/execution_context.cc
@@ -27,6 +27,7 @@
 
 #include "third_party/blink/renderer/core/execution_context/execution_context.h"
 
+#include "base/debug/dump_without_crashing.h"
 #include "base/metrics/histogram_functions.h"
 #include "base/tracing/protos/chrome_track_event.pbzero.h"
 #include "build/build_config.h"
@@ -150,9 +151,28 @@ void ExecutionContext::SetIsInBackForwardCache(bool value) {
 }
 
 void ExecutionContext::SetLifecycleState(mojom::FrameLifecycleState state) {
+  static auto* crash_key = base::debug::AllocateCrashKeyString(
+      "lifecycle_state", base::debug::CrashKeySize::Size32);
   if (lifecycle_state_ == state)
     return;
   lifecycle_state_ = state;
+  std::string state_string = "running";
+  switch (state) {
+    case mojom::FrameLifecycleState::kRunning:
+      break;
+    case mojom::FrameLifecycleState::kFrozen:
+      state_string = "frozen";
+      break;
+    case mojom::FrameLifecycleState::kPaused:
+      state_string = "paused";
+      break;
+    case mojom::FrameLifecycleState::kFrozenAutoResumeMedia:
+      state_string = "frozen_auto_resume_media";
+      break;
+  }
+  base::debug::SetCrashKeyString(crash_key, state_string);
+  base::debug::DumpWithoutCrashing();
+  base::debug::ClearCrashKeyString(crash_key);
   ContextLifecycleNotifier::observers().ForEachObserver(
       [&](ContextLifecycleObserver* observer) {
         if (!observer->IsExecutionContextLifecycleObserver())
```

* Captured runtime trace with the following args to see the flow of navigation and loading, `"blink,blink.resource,browser,content,loading,navigation,renderer,toplevel,v8,disabled-by-default-loading,disabled-by-default-renderer.scheduler,disabled-by-default-v8.inspector,disabled-by-default-v8.stack_trace"`

In the failing case, there is a call to `Document::OpenForDocument` from the document loader which ends up creating the sync html document parser and eventually calls into `HTMLParserScriptRunner::executeScriptsWaitingForParsing` that ends up evaluating `vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/code/electron-sandbox/workbench/workbench.js` while the page is still paused. In the successful case there is no such code path, question is what triggers this flow ?

<img width="1198" alt="Image" src="https://github.com/user-attachments/assets/f128f076-1f1f-4e8b-bd21-3bef416df768" />

**Comment by deepak1556** [comment]
@jrieken shared this to be an known issue filed at https://github.com/microsoft/vscode/issues/164256 but looking at the linked upstream issues I don't see an exisiting report that refers to the flow we are seeing. I will continue to dig further.

/cc @connor4312

**Comment by deepak1556** [comment]
@bpasero can you check with js-debug nightly version (@id:ms-vscode.js-debug-nightly), I had a successful repro of this issue with the following steps,

* F5 debugging
* Open issue reporter which attempts to open an aux window
* Get the error `Failed to execute 'createScriptURL' on 'TrustedTypePolicy': The provided callback is no longer runnable.` from dompurify.sanitize

With https://github.com/microsoft/vscode-js-debug/pull/2196 this seems to have been addressed. Although in your case there is no aux window, would be good to validate if the fix helps your case as well.

**Comment by bpasero** [comment]
I still see this today, when using Exploration builds and the built in debugger:

<img width="435" alt="Image" src="https://github.com/user-attachments/assets/e58379d0-6b7b-4243-ba32-a7ef2ecf0611" />

Do I need to manually install the nightly? I think not, I think we pull in the latest during build time?

**Comment by deepak1556** [comment]
> Do I need to manually install the nightly? I think not, I think we pull in the latest during build time?

Yes the nightly build is not the default, you will need to disable the extension that you see in the screenshot and install `ms-vscode.js-debug-nightly`

**Comment by bpasero** [comment]
It reproduces even with the nightly version. No floating windows are involved.

**Comment by deepak1556** [comment]
Thanks for testing, will follow-up in debt week.
