### ISSUE TITLE
terminal cursor reset as if it was cleared, but content is still there

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#241978]
I clicked into an existing terminal and the cursor jumped to the top, right where it would be if it was a new/cleared terminal.

![Image](https://github.com/user-attachments/assets/057c5f69-3852-4b8f-a5f0-49cfcac1d5ee)

only happened once, not sure why

**Comment by amunger** [comment]
oh, maybe because of that notification lol. I didn't notice that

**Comment by Tyriar** [comment]
Was going to close this as out of scope, but maybe we should just accept that this will always be a possibility on Windows and try only restore the last terminal's content to scrollback, not the viewport.

**Comment by Tyriar** [comment]
@amunger for that case it might have been because you resized in which case we can't do anything about it or detect. Only the reconnect/revive case could we maybe improve

**Comment by Tyriar** [comment]
I think we need to special case resize on conpty-backed terminals and insert empty lines. This is after resizing narrow and back on WT:

![Image](https://github.com/user-attachments/assets/0aae194d-7510-4c57-88f2-55e8974da930)

**Comment by hediet** [comment]
I run into this very frequently:

![Code_-_Insiders_jJaThc4ASi](https://github.com/user-attachments/assets/f09e15cb-122e-44a6-9ae5-3a7830a21586)

**Comment by TheLime1** [comment]
![Image](https://github.com/user-attachments/assets/40f9e36b-2c9a-4689-b35d-73a22e989197)

**Comment by Tyriar** [comment]
xterm.js issue for the resize problem: https://github.com/xtermjs/xterm.js/issues/5319

**Comment by Tyriar** [comment]
This should be fixed in the next build, please keep an eye out for similar issues.

**Comment by amunger** [comment]
just seen in latest insiders

![Image](https://github.com/user-attachments/assets/7e39de12-87a8-43ea-a28c-066f21d47bfd)

**Comment by amunger** [comment]
and from switching monitors

![Image](https://github.com/user-attachments/assets/a6aacb8d-3025-46dc-91b9-93fad67c33f0)

**Comment by rzhao271** [comment]
I still see similar behaviour on the latest Insiders where I type "git status" and the terminal gives me "it status" plus an error message. This behaviour occurs with suggestions disabled as well.

![Image](https://github.com/user-attachments/assets/e7cc35a3-51e7-4e57-9dd1-886ddadbe162)

**Comment by Tyriar** [comment]
@rzhao271 I'm hoping yesterday's conpty revert will fix that.

@amunger note that this still can happen:

![Image](https://github.com/user-attachments/assets/8e3c5ed4-0a08-48d0-b0ae-6a893fe13a34)

It will be much less frequently and the cursor will drift a lot less. Unfortunately it's quite complicated and truly solving this would mean aligning xterm.js' reflow algorithm to what conpty does, which I don't really want to do, and the WT team doesn't either as that logic could change at any time. There may be a better solution down the line, they're aware of the problem.

**Comment by hediet** [comment]
It it is still quite easy to get broken rendering:

![KsBceSxjyR](https://github.com/user-attachments/assets/0f1cc9f1-b6e8-4cb5-b1bf-188919ffa0d5)

**Comment by hediet** [comment]
I also still have the issue that the first character is skipped (wanted to type `vite`):

![Code_-_Insiders_Tw8hapa95n](https://github.com/user-attachments/assets/00abd886-2e93-478f-8add-0285d573949e)

New terminal looks like this:

![Code_-_Insiders_PQ8ufhhEtw](https://github.com/user-attachments/assets/66f24e08-13a9-437c-9553-e73abfd5e0f5)


![Code_-_Insiders_33QV6Rz76m](https://github.com/user-attachments/assets/cf94af24-ffe3-4beb-9743-c3ec43e6fa07)

**Comment by Tyriar** [comment]
@hediet haven't tracked down that clearing of the terminal yet, will try your repro 👍

**Comment by Tyriar** [comment]
@hediet 

> It it is still quite easy to get broken rendering:

Forked the blank terminal problem in https://github.com/microsoft/vscode/issues/241978#issuecomment-2754625283 to https://github.com/microsoft/vscode/issues/244757

> I also still have the issue that the first character is skipped (wanted to type vite):

That's this one which I've reopened as I saw it too https://github.com/microsoft/vscode/issues/243584

**Comment by Tyriar** [comment]
Actually I'll keep this open pending the discussion I'm having with WT.

**Comment by benibenj** [comment]
1. Updated insiders
2. opened terminal
3. started typing

<img width="358" alt="Image" src="https://github.com/user-attachments/assets/f90a9cdb-ba3b-400b-a066-1293c77b1eb1" />

**Comment by hediet** [comment]
Also on lateast insiders:

![Code_-_Insiders_ZZy5rwrDNR](https://github.com/user-attachments/assets/e9bd3390-a473-400b-9602-49586f9cf753)

**Comment by Tyriar** [comment]
@benibenj @hediet the missing input after you reload a window is this one: https://github.com/microsoft/vscode/issues/243584

**Comment by anthonykim1** [comment]
Good repro steps:

1. Have vscode window in smaller window size (not full screen)
2. Go focus on different application.
3. Come back to vscode
4. Make vscode full screen
5. Start typing ---> Bug: Typing in wrong position 

https://github.com/user-attachments/assets/ca9bc1d5-700b-4139-af4e-7f2a62aa44ad
