### ISSUE TITLE
Extension corrupted: vsc-material-theme, equinusocio.vsc-material-theme

### ISSUE THREAD

**Issue by saroroce** [microsoft/vscode#242041]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. when we delete vsc-material-theme ('equinusocio.vsc-material-theme') it's going to do this bug
![Image](https://github.com/user-attachments/assets/beed1b9b-4eb3-4c6d-bc1c-c739b45f9f92)
Translated to English:
We deleted 'equinusocio.vsc-material-theme' extension, which maked problems.

![Image](https://github.com/user-attachments/assets/8f4fc324-9735-44f6-921b-aeb1890b1b72)
Translated to English:
This extension is marked as a problem

3. I deleted extension folder from %USER_FOLDER/.vs_code/extensions/equinusocio.vsc-material-theme
<img width="303" alt="Image" src="https://github.com/user-attachments/assets/76c62fa3-e903-4564-a9e1-d2477a06cdf8" />

but it makes problems and spam i CAN'T FIX IT, pls make something or give me info where is temp data folder to clear info about this plugin and stop this spam,

Thanks Microsoft Team for this product, first bug from all time of usage ( 6 years )

#################################################
Tags for other users to find this issue

equinusocio.vsc-material-theme bug
Extension corrupted
Баг с расширением vscode
Material Theme Bug Vs Code
Сломался vs code из-за расширения

#################################################

**Comment by saroroce** [comment]
Does this issue occur when all extensions are disabled?: Yes
VS Code Version: 1.97.2
OS Version: Darwin arm64 24.3.0

Full Info:

Version: 1.97.2 (Universal)
Fixation: e54c774e0add60467559eb0d1e229c6452cf8447
Date: 2025-02-12T23:20:35.343Z
Electron: 32.2.7
ElectronBuildId: 10982180
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
ОС: Darwin arm64 24.3.0

**Comment by sn0wcat** [comment]
Confiriming the finding, after the extension is deleted, vs code is stuck in endless notification loop. 

![Image](https://github.com/user-attachments/assets/93d0c40d-2e1f-4960-a2f6-14b8d7f07e56)

**Comment by Abo-Fat** [comment]
@sn0wcat that's useful! the warning has bothered me all day!

**Comment by begprod** [comment]
Maybe help https://github.com/microsoft/vscode/issues/241176#issuecomment-2683480426

**Comment by saroroce** [comment]
i fixed it when changed from vs code to cursor, at least is the same

**Comment by djyasdfghjkl** [comment]
刚刚试了，本来想在本地删除文件夹避免错误，但是没找到直接去了C:\Users\用户名\.vscode\extensions\extensions.json搜索material，把这一串删掉就好啦

**Comment by PrasantaScripts** [comment]
@sn0wcat it worked thanks buddy ❤️

**Comment by NicholsonJD** [comment]
I don't have the equinusocio line in my extensions.json file, but I'm still getting this notification repeatedly. Has anyone been able to fix this another way?

**Comment by victorSA99** [comment]
Yo tengo el mismo porblema ya borre la carpeta y lo borre del extension.js y nada

**Comment by gspowley** [comment]
After applying the workaround, I still received the notification when connecting to a remote SSH system.

Applying the workaround to `~/.vscode-server/extensions/extensions.json` on the remote system resolved the issue.

**Comment by sandy081** [comment]
May I know if anyone here is still seeing this issue? If so, I would need your help to find out the root cause to fix this issue permanently. 

Thanks

**Comment by PinkDopeyBug** [comment]
我的也是在vscode扩展商店中删除了equinusocio.vsc-material-theme插件；并且在vscode的扩展文件夹C:\\Users\\username.vscode\\extensions中也删除了这个插件，同时同级目录中的extensions.json文件中也删除了以下条目
```
{"identifier":{"id":"equinusocio.vsc-material-theme","uuid":"dffaf5a1-2219-434b-9d87-cb586fd59260"},"version":"34.7.9","location":{"$mid":1,"path":"/Users/sn0wcat/.vscode/extensions/equinusocio.vsc-material-theme-34.7.9","scheme":"file"},"relativeLocation":"equinusocio.vsc-material-theme-34.7.9","metadata":{"installedTimestamp":1740225670566,"pinned":false,"source":"gallery","id":"45bfc9eb-5e03-487f-bffe-315fa6881d6a","publisherId":"3b9d55d2-da9e-415a-9bea-8d6bc07147d8","publisherDisplayName":"Equinusocio","targetPlatform":"undefined","updated":false,"isPreReleaseVersion":false,"hasPreReleaseVersion":false,"preRelease":false}},
```
依旧会有警告弹窗
我的系统是windows11，以此为参照，分享一下我的解决方法：
1. 卸载vscode
2. 将C:\\Users\\username\\.vscode文件夹删除（vscode配置文件夹）
3. 将C:\\Users\\username\\AppData\\Roaming\\Code文件夹删除（vscode缓存文件夹）
4. 重新安装vscode
再次启动并等待vscode同步完成后就不再有警告弹窗了，希望以上方法对大家能有所帮助

**Comment by sandy081** [comment]
/duplicate

Thanks for the details. Following json entry in the `extensions.json` file explains it

```json
{
  "identifier": {
    "id": "equinusocio.vsc-material-theme",
    "uuid": "dffaf5a1-2219-434b-9d87-cb586fd59260"
  },
  "version": "34.7.9",
  "location": {
    "$mid": 1,
    "path": "/Users/sn0wcat/.vscode/extensions/equinusocio.vsc-material-theme-34.7.9",
    "scheme": "file"
  },
  "relativeLocation": "equinusocio.vsc-material-theme-34.7.9",
  "metadata": {
    "installedTimestamp": 1740225670566,
    "pinned": false,
    "source": "gallery",
    "id": "45bfc9eb-5e03-487f-bffe-315fa6881d6a",
    "publisherId": "3b9d55d2-da9e-415a-9bea-8d6bc07147d8",
    "publisherDisplayName": "Equinusocio",
    "targetPlatform": "undefined",
    "updated": false,
    "isPreReleaseVersion": false,
    "hasPreReleaseVersion": false,
    "preRelease": false
  }
}

```

`uuid` of identifier and `id` of `metadata` are different. This is the root cause of the issue and it got fixed here - https://github.com/microsoft/vscode/issues/239434

Hence marking this as duplicate
