### ISSUE TITLE
broken window border with wayland

### ISSUE THREAD

**Issue by DimanNe** [microsoft/vscode#247054]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.99.3
- OS Version: 

```
Distributor ID: Ubuntu
Description:    Ubuntu 24.10
Release:        24.10
Codename:       oracular
```

Steps to Reproduce:

1. Open code
2. Look at the right

You will see this:

![Image](https://github.com/user-attachments/assets/214d024b-e241-48d4-b8e7-da2c1f7580f1)

While in reality,
### there are two windows! and the border on the right is actually ff:

![Image](https://github.com/user-attachments/assets/17d9d71b-b520-4ed0-85a9-2a9877381e1a)

**Comment by bpasero** [comment]
Does it help to configure `window.titleBarStyle` to `native`?

**Comment by DimanNe** [comment]
It helps
(but then there is another problem: it is native)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by DimanNe** [comment]
@bpasero I reproduced it with your insiders build. Same issue, see the screenshot:

![Image](https://github.com/user-attachments/assets/6940f72c-d522-4f32-a93f-0957c35fa3fd)

**Comment by DimanNe** [comment]
This has not yet been released, right?

![Image](https://github.com/user-attachments/assets/4e7eb2ce-eeaa-44a7-a5d6-ab5d28e87c63)

**Comment by rzhao271** [comment]
@DimanNe could you confirm that the issue has been fixed for you using [VS Code Insiders](https://code.visualstudio.com/insiders/)?

Edit: I just noticed that you were already using Insiders.

**Comment by flying-sheep** [comment]
It isn’t:

```
Version: 1.101.0-insider
Commit: 7197360b79e6da3404ed5ad1fb4d7ea74a8bb5d2
Date: 2025-06-04T05:03:51.910Z
Electron: 35.5.0
ElectronBuildId: 11678209
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Linux x64 6.14.9-zen1-1-zen
```

![Image](https://github.com/user-attachments/assets/da9495cc-021c-4a76-8f68-d11825657619)

**Comment by deepak1556** [comment]
To confirm, is the application running with `--ozone-platform=wayland` ? If not, can you run with the flag and see if the issue repros.

**Comment by flying-sheep** [comment]
I do run it with that flag, yes. I also added it manually in the CLI to be sure and that time got “Option 'ozone-platform' is defined more than once. Using value 'wayland'.”

https://github.com/electron/electron/issues/44540 (which is about both borders and buttons) isn’t fixed yet, so I’m not sure why you thought Electron 35 would fix this here.

/edit: I think it varies between desktop environments:
- here is a GIF where a shadow seems to be present Ubuntu GNOME: https://github.com/electron/electron/issues/45916
- in my above screenshot, you can see how it doesn’t work on KDE Plasma

so I think we need to figure out which window hints Electron sets on Linux, and which platform behaves correctly.

**Comment by deepak1556** [comment]
@flying-sheep thanks for the details, the issue was considered fixed since it was related to https://github.com/electron/electron/issues/46484 and the OP desktop environment matches the upstream issue. Seems like you are facing a different issue and it would be good to open a separate issue for your desktop environment.

@DimanNe can you confirm your desktop environment details.

**Comment by flying-sheep** [comment]
Yeah, let’s wait for @DimanNe to confirm things work in GNOME, then I do that.

Also while I have your attention: Can you please reopen https://github.com/microsoft/vscode/issues/53812? It’s very definitely not fixed anywhere, Electron’s custom window buttons always look like the MS Windows default and get placed on the right.

**Comment by sedax90** [comment]
this issue is still present with 1.101 and Ubuntu 25.04 (gnome wayland)

![Image](https://github.com/user-attachments/assets/8fb2d1c6-2bdb-47ea-aa9d-42a3a5f463fd)

**Comment by pierrebrd** [comment]
Pretty sure this issue is a duplicate of #225073

**Comment by DimanNe** [comment]
@deepak1556 Sorry for late response. **The issue is still here.**

Using latest code-insiders:

```
Version: 1.102.0-insider
Commit: b68fa590ef54bc8f07dd79cd3175bf78e0113d4c
Date: 2025-06-27T05:03:40.827Z
Electron: 35.5.1
ElectronBuildId: 11727614
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Linux x64 6.11.0-26-generic
```

starting it like this:

`code-insiders --ozone-platform=wayland`

(I am using KDE, if it is important)

result:

![Image](https://github.com/user-attachments/assets/e6cab482-5e4a-484f-b3bd-4352f4dbdb72)

**Comment by sedax90** [comment]
seriously what is the difficulty in adding a shadow to a window?

**Comment by CEN90** [comment]
> seriously what is the difficulty in adding a shadow to a window?

Considering how long it's been broken it feels by this point intentional.

**Comment by cbrnr** [comment]
This happens on both GNOME and KDE for me (using Wayland, which is the default in many distributions). I find the lack of window borders a serious usability issue. Other Electron-based apps, which previously also exhibited this problem (e.g., Signal Desktop), have successfully fixed it. Is there anything I (as a user) can do to help track down (and fix) this issue?

**Comment by Arecsu** [comment]
> This happens on both GNOME and KDE for me (using Wayland, which is the default in many distributions). I find the lack of window borders a serious usability issue. Other Electron-based apps, which previously also exhibited this problem (e.g., Signal Desktop), have successfully fixed it. Is there anything I (as a user) can do to help track down (and fix) this issue?

Confirming this. Right now I'm using [Figma-Linux](https://github.com/Figma-Linux/figma-linux) which does use its own window decorations and yet shadows work.

**Comment by ParadaCarleton** [comment]
> seriously what is the difficulty in adding a shadow to a window?

It turns out, on Linux, the answer is [_a lot_](https://www.reddit.com/r/linux_gaming/comments/1cmsuen/a_linux_support_dev_from_a_very_popular_game/), but mainly a lack of consistent standards and a tendency of each desktop environment to just do whatever it wants.

**Comment by ParadaCarleton** [comment]
> True, but the solution already exists from Chrome/Electron. VS Code is literally the only major app that still does not have proper window borders/shadows.

Does it? Where/how? I have lots of Electron apps with broken borders and shadows.

**Comment by ParadaCarleton** [comment]
> Try Chrome and Signal, they both work.

Electron apps (e.g. Signal) use LibDecor/native decorations to generate shadows on Linux. If you're OK with that, you can set `Window: Title Bar Style`  to "native" under the VSCode settings and then VSCode should have shadows and a titlebar that look the same as on those apps.

The [default decorations on Chrome are broken](https://i.redd.it/ph7nuxtl1hlf1.png), although once you log in you get a set of themed GTK-based CSDs that look good. These decorations haven't made their way into Electron, though, since they depend on Chrome specifics (e.g. the window buttons are integrated into the tab bar).

**Comment by iacobucci** [comment]
In the meantime for the fellow Gnome users, this extension https://github.com/flexagoon/rounded-window-corners solves the problem

**Comment by pierrebrd** [comment]
Some good news!
The newly released Insiders build comes with Electron 42, and finally there are shadows when VS Code is launched in native Wayland mode! This should be coming to stable release in version 1.123, next week.

The shadows are similar to what we have on Chrome for example.

<img width="1010" height="696" alt="Image" src="https://github.com/user-attachments/assets/be5c6a6b-0374-4be7-965b-e69bda733225" />

However, there is still no rounded corners, but that's a less important issue. Also, there is a bug when you open multiple windows, the additional windows have a thin frame around the shadows: 

<img width="1322" height="713" alt="Image" src="https://github.com/user-attachments/assets/3ea8e684-1d0b-415f-9600-83b4df7cb0d1" />

@deepak1556

**Comment by cbrnr** [comment]
That's a start. Meanwhile, I've managed to make it work on KDE using window rules and the Rounded Corners extension. Works great!

<img width="1589" height="1118" alt="Image" src="https://github.com/user-attachments/assets/b5aa0d0a-fd20-4758-886a-b638e9858ad4" />

**Comment by sedax90** [comment]
> Some good news! The newly released Insiders build comes with Electron 42, and finally there are shadows when VS Code is launched in native Wayland mode! This should be coming to stable release in version 1.123, next week.
> 
> The shadows are similar to what we have on Chrome for example.
> 
> <img alt="Image" width="1010" height="696" src="https://private-user-images.githubusercontent.com/62522403/599594992-be5c6a6b-0374-4be7-965b-e69bda733225.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODA1NTU3MjQsIm5iZiI6MTc4MDU1NTQyNCwicGF0aCI6Ii82MjUyMjQwMy81OTk1OTQ5OTItYmU1YzZhNmItMDM3NC00YmU3LTk2NWItZTY5YmRhNzMzMjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNjA0VDA2NDM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMjNjYTgzMDk0MDZjNTg4OGIwMWI3ZWU4MWQ2NmJiZWViNzBiZGQyZDQ4YTNkZjlmNDY5YmQwY2I4NjE5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.AMjWs3hzXAgj2RfAyOfZjhKoRO1G41okz44KOBOe0gE">
> However, there is still no rounded corners, but that's a less important issue. Also, there is a bug when you open multiple windows, the additional windows have a thin frame around the shadows:
> 
> <img alt="Image" width="1322" height="713" src="https://private-user-images.githubusercontent.com/62522403/599595496-3ea8e684-1d0b-415f-9600-83b4df7cb0d1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODA1NTU3MjQsIm5iZiI6MTc4MDU1NTQyNCwicGF0aCI6Ii82MjUyMjQwMy81OTk1OTU0OTYtM2VhOGU2ODQtMWQwYi00MTVmLTk2MDAtODNiNGRmN2NiMGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNjA0VDA2NDM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ODIxYzcyYTVmMjI2MWExMjNmY2Y2YmU3MjRjOGExYjE1NTdhYTk4YzlmOTlmOWY4NmM4YzAxYTc4ZDljM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.4_I8ivflU8NT72sKLW2DNUjjdlbn7YC9_yrh9tuJqe4">
> [@deepak1556](https://github.com/deepak1556)

for the rounded corners I think we should wait this: https://github.com/electron/electron/pull/51459

**Comment by sedax90** [comment]
Rounded corners are actually default on linux with Electron 43+ https://github.com/electron/electron/pull/52111

Let's just hope it doesn't take months again before vscode decides to update the electron version...

**Comment by mitchchn** [comment]
> Also, there is a bug when you open multiple windows, the additional windows have a thin frame around the shadows.

Tracking this one here: https://github.com/electron/electron/issues/51456.

**Comment by pierrebrd** [comment]
Solved with VSCode 1.139 (current insiders release) with electron 43, windows now have both shadows and rounded corners.
