### ISSUE TITLE
Backspace can not erase the last one character during Chinese/Japanese IME conversion (macOS)

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#24981]
- VSCode Version: 1.12-Insiders
- OS Version: macOS

The same issue as https://github.com/electron/electron/issues/9173

Reproduce steps:

1. Open any markdown file, preview
2. Go to Search Viewlet or Git Viewlet
3. Switch to Japanese IME
4. Type Japanese, and then delete
5. You have to press Delete twice when deleting last character.

**Comment by rebornix** [comment]
It's actually more severe as if there is any webview, we'll receive wrong composition events in editor as well. So if you are editing markdown files in Japanese with Preview open, you'll run into the same issue. cc @mattbierner

**Comment by bpasero** [comment]
@rebornix any idea for a workaround or fix? this will probably block our electron update...

**Comment by bpasero** [comment]
I just confirmed that this also happens in the editor as long as there is a webview open.

**Comment by rebornix** [comment]
@bpasero when there is a webview, the composition state is not updated at all. Take below as example

* Press `a`, and we get `あ`
* Press Backspace, we get a backspace keydown event, however, we didn't get any composition related event.
* Press another Backspace, we get compositionEnd event.

The events emitted by browser align with the behavior of input box. I can't reproduce this issue with latest Chromium Version 57.0.2987.133 (64-bit).

**Comment by rebornix** [comment]
This is not just Japanese, I can also reproduce this problem with Chinese IME.

**Comment by bpasero** [comment]
Since I am not expecting a fix on our end, moving to backlog until we go for a more recent electron version.

**Comment by rebornix** [comment]
I tried to get an idea of how bad it is by writing a fresh new blog post in Chinese, thinking, writing and tweaking the content. Within 30 minutes, I wrote 900 characters and ran into this issue 7 times. Current behavior is annoying to me, it's just weird. So I'll say it's not a blocker.

Besides, once you open a webview, you'll have this issue always. It means you open Markdown Preview, and then close it, you still have this backspace issue in editor and anywhere else. The only way to get rid of it is restarting VS Code.

**Comment by bpasero** [comment]
Looks like this is a Chrome issue (as reported by Kevin here: https://bugs.chromium.org/p/chromium/issues/detail?id=714771) which means we will not get a fix until Chrome has fixed this or provided a workaround. 

@rebornix given that, do you think we can add a hack to make this work or is there nothing we can do from our end?

**Comment by rebornix** [comment]
@bpasero as it's affecting native input/textarea and js events, I don't have an idea of how to hack it right now.

**Comment by chezou** [comment]
As of now, the Chromium issue has been fixed. Is there any plan to bump it?

**Comment by bpasero** [comment]
@rebornix since we updated to a more recent Electron version, I think this issue is resolved. At least a fix from Chrome was backported: https://github.com/electron/libchromiumcontent/pull/300

**Comment by chezou** [comment]
Has the same issue on Windows with VSCode 1.15.1.

**Comment by rebornix** [comment]
I no longer see this issue in latest Insider (1.16-insider), so this issue would disappear from our next Stable.

**Comment by chezou** [comment]
Does this problem fix with 1.16.1?

This issue still occurs with VSCode v1.16.1 on Windows 10 using Google Japanese IME.

Video: https://youtu.be/Wq2LzSv4p1Q
