### ISSUE TITLE
Ctrl+C does not stop node server in external Command Line

### ISSUE THREAD

**Issue by raelb** [Microsoft/vscode#25195]
From a normal Windows command prompt, `ctrl+c` will stop a node server running.

However, if I start the command prompt via the `VS Code` menu item `Open in Command Prompt`, then pressing `ctrl+c` (even multiple times) does not stop the server as usual.

Running on Windows 10 x64
VS Code 1.11.2

Also asked on SO:
http://stackoverflow.com/questions/43531894/ctrlc-does-not-stop-node-server-in-command-line-from-vs-code

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/9347

**Comment by Tyriar** [comment]
@raelb does this still happen when you add this to your settings?

```js
"terminal.external.windowsExec": "C:\\Windows\\sysnative\\cmd.exe"
```

**Comment by raelb** [comment]
If I add that setting it works fine.

Note after I install VS Code it already has similar setting:

// Place your settings in this file to overwrite the default settings
{
    "window.zoomLevel": 0.5,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\cmd.exe",
    "terminal.external.windowsExec": "C:\\Windows\\sysnative\\cmd.exe"
}

**Comment by Tyriar** [comment]
We should just hardcode 32/64-bit cmd.exe then if that works, right now we point to the `COMSPEC` environment variable that defaults to the 32-bit version of cmd.exe regardless of what version of Windows you're on.

**Comment by oliverjanik** [comment]
I can reproduce. This has been a bug for the longest time.

**Comment by Tyriar** [comment]
I merged https://github.com/Microsoft/vscode/pull/29352 which should select the sysnative version. I noticed two things though, firstly I couldn't reproduce the issue on my machine (Windows 10 64-bit), plus I didn't see it change to Sysnative using the same trick we used to fix a similar issue with 64-bit PowerShell. This may be blocked by shipping a 64-bit version of VS Code.

I'm interested to hear if the problem is fixed in Insiders on Monday.

**Comment by oliverjanik** [comment]
I'll test when this gets released.

**Comment by michelkaporin** [comment]
Works for me, adding verified.

**Comment by Gonkers** [comment]
So what's the status on this? `ctrl+c` still doesn't work for me.
If I use `c:\windows\System32\cmd.exe` the keystroke just gets swallowed somewhere and has no effect.

If I use `C:\WINDOWS\Sysnative\WindowsPowerShell\v1.0\powershell.exe` as my shell, it just replicates `^C` on my console output.

Windows 10 pro fully patched as of today using v1.16.0 of VS Code.
