### ISSUE TITLE
persistent "configure excludes" prompt

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#26337]
- VSCode Version:1.12.1
- OS Version:Win10

I have HTML/JS project with ~300 JS files and ~200 html files.  Even though I have a jsconfig.json that contains excludes, I continually get a "configure excludes" button on the status bar.  Pressing it (and the subsequent prompt) opens the correct JSON file and temporarily hides the "configure excludes" button, but it reappears again after a several minute delay.

I'm assuming the status button indicates a file count threshold has been hit for the project and that javascript intellisense is disabled or defeatured as a result.   If so, is there a way to override the default?  If not, what can I do to provide additional troubleshooting?  

<img width="670" alt="capture" src="https://cloud.githubusercontent.com/assets/3818866/25874688/46696788-34d9-11e7-921b-4aa6d2e96cef.PNG">

jsconfig.json
```JSON
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/test/",
        "**/.vscode/"
    ]
}
```

**Comment by mjbvz** [comment]
Yes, `configure excludes` indicates that TypeScript is trying to load too many files. However 300 files should not trigger this, so something else may be amiss.

As a first step, try using `include` instead of `exclude` in your `jsconfig`. `include` is a whitelist of which files are part of a project vs exclude which is a blacklist of which files not to include in the project.

If you are still running into issues, you can also collect the TSServer log:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart VSCode and reproduce the issue
3. Run the `Open TSServer log File` command and view the `tsserver.log` file

This log will display all the files that are being included in your projects. You can scan through these file lists to see if any unexpected files are being included. If nothing stands out, please share the log so that we can take a look

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mfrost66** [comment]
@mjbvz  Added ```"typescript.tsserver.log": "verbose"``` to workspace settings and relaunched vscode.  Once the ```configure excludes``` showed, I attempted to open log, got "could not open TS Server log file" message.  Suggestions on troubleshooting the troubleshooter?

<img width="799" alt="capture" src="https://cloud.githubusercontent.com/assets/3818866/25900065/ca48fe14-3557-11e7-8610-928e942c40ab.PNG">

**Comment by mjbvz** [comment]
@mfrost66 It looks like you are hitting: https://github.com/Microsoft/vscode/issues/25908 This should be fixed in [current insiders builds](https://code.visualstudio.com/insiders) if you give those a try

**Comment by mfrost66** [comment]
Where is the log folder located?

**Comment by mfrost66** [comment]
@mjbvz Found a bunch of vscode log folders in windows %temp% and removed them.  It appears to have solved both the ```configure excludeds``` prompt and the failure to display the log.  

I suspect some work on graceful exits and re-entry would resolve the issue(s).  If it continues to happen, I'll update here

**Comment by mfrost66** [comment]
@mjbvz ```configure excludes``` error is back.  The error appears to be caused by a recursive symbolic link in a sub-folder (unit test folder).   This generates a 73M log file, so you were correct on #25908.  The folder is excluded both in the ```jsconfig.json``` file and in the workspace settings file via glob ```**/test/```.  It works fine for the workspace settings "excludes" (that is, the folder is exluded from explorer and file search) but appears to fail for tsserver.  

Intellisense appears to work for hours, then randomly fail.  It might simply be that the folder recursion is taking that long to fail, or something else triggers a folder refresh and the exlude fails

I am writing pure JS code, so the only entries I'm making in the jsconfig are simply to enable intellisense. 
For me at least, tsserver should respect the excludes from the workspace settings, otherwise I'm just echoing them to the jsconfig file.

**Comment by mjbvz** [comment]
Could you share / describe a small example project that demonstrates the issue with the recursive link. Also, were there any error messages or stack traces at the end of the tsserver.log file when the error occurred?



You may also want to change your exclude globs to:

```json
    "exclude": [
      "node_modules",
        "**/test/*",
        "**/.vscode/*"
    ]
```

If these folders are all at the top level of your workspace, you should also be able to write:

```json
    "exclude": [
      "node_modules",
        "test",
        ".vscode"
    ]
```

The current ones may not be working as expected here

**Comment by mfrost66** [comment]
You were correct, changing the glob from '**/folder/' to '**/folder/*' successfully excluded the recursive sub-folders.  Note that this glob pattern works in the editor settings exclude path.  The inconsistency between the two  and lack of feedback from tsserver may catch other users by surprise.

**Comment by mjbvz** [comment]
@mfrost66 Glad to hear this worked.

I also agree the current behavior is really confusing, so I've opened https://github.com/Microsoft/TypeScript/issues/16115 to track either treating `**/test/` as a valid glob or generating a warning message for it
