### ISSUE TITLE
Keep support bogus snippets

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#27090]
- VSCode Version: Insiders 1.13.0-insiders (06e162)
- OS Version: MacOS

Steps to Reproduce:

1. `yo code` and create a new Snippet extension (pick javascript language)
2. in `snippets/snippets.json` create this snippet

``` json
{
    "testSnippet": {
        "prefix": "for",
        "body": [
            "for (var ${index} = 0; ${index} < ${array}.length; ${index}++) {",
            "\tvar ${element} = ${array}[${index}];",
            "\t$0",
            "}"
        ],
        "description": "For Loop"
    }
}
```

`F5` to run/debug the extension
open a javascript file
ctrl+space to bring up snippets, look for `testSnippet` and insert it

**Results**: Insiders:

![image](https://cloud.githubusercontent.com/assets/1487073/26327162/2aa0eb2e-3ef3-11e7-8cfe-88287e8871be.png)

**Expected**: Stable:

![image](https://cloud.githubusercontent.com/assets/1487073/26327113/e749d368-3ef2-11e7-96eb-cf5a08dd45e0.png)

In Insiders you now need to add a position number to the placeholder, e.g. `${1:index}`.

this is a breaking change, reported by John Papa as all his Angular snippets stopped working [here is his change](https://github.com/johnpapa/vscode-angular-snippets/commit/4bc7e34c1c5b7884f15845de2546e70fe6341520)

**Comment by johnpapa** [comment]
Thanks. @wardbell also had an issue, I believe with the stable VS Code version. I'll let him chime in

**Comment by jrieken** [comment]
These snippets are using the correct syntax. Our parser got more strict aka correct to interpret variables as such (`${foo}` or `$foo`) and placeholders as such `${1:foo}`. We need to adjust the JS/TS snippets

**Comment by jrieken** [comment]
The syntax is documented here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax. @chrisdias @johnpapa where does that snippet come from? did you copy it somewhere? I cannot find such a sample in our sources or generator

**Comment by jrieken** [comment]
We decided to keep the bug alive. Rule will be: When a variable that cannot be resolves is used, like `${foo}`, we insert its name and turn it into a placeholder.

**Comment by jrieken** [comment]
We now massage snippets that are defined statically by an extension or by a user in a way that turns variables we don't know into a placeholders. Also, it will emit an information message like so

```
[/Users/jrieken/.vscode-oss-dev/extensions/virtual]: The "testSnippet"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details

```

**Comment by jrieken** [comment]
Closing with the changes above, still interested where these snippet came from @chrisdias? Did you go with an old one or did you get that from a generator or samples page?

**Comment by chrisdias** [comment]
@jrieken i copied the snippet from : https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax and then modified it by turning the placeholders (removing `1:`, `2:`, and `3:`) into variables, simply to match @johnpapa's snippets.

**Comment by jrieken** [comment]
Ok, @johnpapa should probably revisit his snippets

**Comment by chrisdias** [comment]
I'm creating a new extension and when I F5 to run it, I get this in the extension development host:

![image](https://cloud.githubusercontent.com/assets/1487073/26515092/08d0e472-422c-11e7-84ea-2418f7d2f6d0.png)

These are warnings about the Docker extension, but I am NOT running that extension, I simply have it installed.

It is good to know that the extension has issues but this message is given to the user of the extension, not the extension author. Could we instead show an error/warning when the extension author tries to run their extension?

This way we would notify the author and the users of the extension continue to have a pleasant experience.

**Comment by johnpapa** [comment]
I already put positions on my snippets. I'm reporting this because it was a breaking change. My snippets worked for over a year then suddenly broke.

**Comment by jrieken** [comment]
> It is good to know that the extension has issues but this message is given to the user of the extension, not the extension author. Could we instead show an error/warning when the extension author tries to run their extension?

Unsure, @sandy081 or @alexandrudima will know. It's using the normal reporting mechanism we have when extensions do invalid stuff. My hope is that it motivates also others to file a bug against the offending extensions. You did that, right @chrisdias ;-)

> I'm reporting this because it was a breaking change. My snippets worked for over a year then suddenly broke.

Yeah, we had a bug in that code because it was without an owner the longest time. The bug is fixed, we will support these kind of snippets when the come from an extension or user snippets. The latter probably longer than the former.

**Comment by chrisdias** [comment]
PowerShell, C#, Docker, i'm seeing lots of extensions with snippets have this issue.  @egamma mentioned we would fix the fact that we are showing warning messages by only showing in the debug console. I'm still seeing it today (insiders 1.13.0-insiders commit 3a6eda7) so I'm opening this issue again (sorry man!) just so we don't forget.  hopefully its fixed already and tomorrow's (Redmond time) insider's build will have it.

and yep i fixed the vscode-docker extension (https://github.com/Microsoft/vscode-docker/commit/52a04658bae921434002b602f3da853ab81f6fed). 

I will submit issue on C#.

**Comment by jrieken** [comment]
@chrisdias One problem == one issue There is #27753
