### ISSUE TITLE
Running find all references and expanding a node removes minimap in outer editor

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#28093]
![minimap](https://cloud.githubusercontent.com/assets/5047891/26819056/8ef40696-4a9d-11e7-965f-3a5676f0a837.gif)

**Comment by alexandrudima** [comment]
The fix is available on the Insiders channel. We looked at it in the endgame, but it did not fit the severity bar for stable.

**Comment by mxrtos** [comment]
Minimap now disappears when running "Go Back" (workbench.action.navigateBack) on code-insiders_1.14.0-1497948192_amd64.deb

**Comment by alexandrudima** [comment]
@mxrtos I could not reproduce. Running "Go Back" many times does not result in the minimap disappearing. Can you please create a new issue with a set of steps that consistently reproduce the problem?

**Comment by jens1o** [comment]
@alexandrudima Suggestion: Could you add the `editor-minimap` label, so I have it easier to find this issue?

**Comment by douglasg14b** [comment]
@alexandrudima  All the issues I can find for this are closed, this issue still occurs.

Peek Definition, then click in the peek windows and the minimap will vanish

**Comment by alexandrudima** [comment]
@douglasg14b have you updated to a newer version of VS Code? If yes, and you can still reproduce, then please create a new issue.
