### ISSUE TITLE
Indentation of tree view item label changes when adding icon

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#28974]
- VSCode Version: 1.13.1
- OS Version: Win 10

Steps to Reproduce:

1. Create custom tree view extension with icons and observe padding of label.
2. It is impossible to have icons and re-create the layout of the built-in explorer.

In the first picture, in the "Git Context" custom tree view (this is an experiment from myself, not released on the market yet), it looks like the `.gitignore` entry belongs to the folder above, but in fact it doesn't.
![image](https://user-images.githubusercontent.com/530988/27264255-740381fc-5472-11e7-8e01-7e3cca9db5d3.png)

Without icons, the layout is correct:
![image](https://user-images.githubusercontent.com/530988/27264263-9ad1802c-5472-11e7-8329-5c56701d572e.png)

EDIT: I just noticed that the "minimal" icon theme of vs code has folder icons and then adjusts the padding accordingly:

![image](https://user-images.githubusercontent.com/530988/27264347-54cd23a4-5474-11e7-8fb6-b5723765f847.png)

**Comment by sandy081** [comment]
@letmaik Looks to me that .gitignore entry is properly aligned. I think the confusion is because the folder `test` does not has icon where as its sibling `.gitignore` has.

**Comment by letmaik** [comment]
No, the alignment is definitely incorrect, please check the screenshots again. The folders in the first screenshot in the explorer have no icons and yet the alignment is correct, contrary to what you see in the custom views. The alignment has to be on the level of the text/labels, not icons.

**Comment by sandy081** [comment]
@letmaik It is similar to how folders/files are shown. Do you also think the alignment there is not correct?

**Comment by letmaik** [comment]
To make it more visual I added some rulers below. Note the spacing between the vertical lines in the explorer vs the custom view.

Correct:
![27264263-9ad1802c-5472-11e7-8329-5c56701d572e](https://user-images.githubusercontent.com/530988/30859339-22fe164a-a2bb-11e7-80de-54671d23426b.png)

Wrong (`.gitignore` doesn't align with `test` and `fixture.ts` is indented too much):
![27264255-740381fc-5472-11e7-8e01-7e3cca9db5d3](https://user-images.githubusercontent.com/530988/30859347-2ece0eb2-a2bb-11e7-8b6c-5fe76e0ba2f5.png)

Wrong (same problem):
![27264347-54cd23a4-5474-11e7-8fb6-b5723765f847](https://user-images.githubusercontent.com/530988/30859350-32275ff0-a2bb-11e7-8152-6637393ada17.png)

**Comment by sandy081** [comment]
Ah you are right, Got it. Thanks for the rulers they helped. I misunderstood with the files/folders explorer view.

**Comment by sandy081** [comment]
Fixed by f94603326de36d952bac46c800328a9b37a237c7

**Comment by letmaik** [comment]
@sandy081 I'm a bit confused by your commit. This seems to add support for one additional specific type of tree node which is a resource (file, folder). And for that case you support better alignment/indentation. The problem is that it is quite rare that a node is actually a resource. It often is something virtual, and for that case the alignment is still broken. Is this fix going in the wrong direction? Why is a general fix not possible?

**Comment by sandy081** [comment]
@letmaik This is a general fix that considers both kinds of nodes (nodes with resource icons and nodes with explicit icons). This makes all trees in the explorer view are aligned similarly (with the file explorer). In the following screenshots the custom view is based on nodes with explicit icons and see that they are properly aligned

![image](https://user-images.githubusercontent.com/10746682/35638588-c820ba50-06b7-11e8-9167-d0789a2cc4db.png)


![image](https://user-images.githubusercontent.com/10746682/35638610-d7f7660e-06b7-11e8-8161-58dbd56cd330.png)

![image](https://user-images.githubusercontent.com/10746682/35638647-ed8384da-06b7-11e8-9cb4-e22940484aa9.png)

Can you please check with your custom view and let me know if they are aligned.

Thanks.

**Comment by letmaik** [comment]
I'm using latest Insiders build from today and still see the issue, I think it happens when you have a mix of icon and no-icon nodes:

![image](https://user-images.githubusercontent.com/530988/35641907-619f9010-06b9-11e8-8fa1-9f08e7ef9983.png)

**Comment by sandy081** [comment]
@letmaik Pushed another fix on top. Looks like I covered all cases finally.

Here are samples from each file icon theme that comes with VS Code

![image](https://user-images.githubusercontent.com/10746682/35700659-d9f81214-0793-11e8-8d42-1dfd75216a6c.png)

![image](https://user-images.githubusercontent.com/10746682/35700614-c73ec1c2-0793-11e8-9e20-92618b0cbf45.png)

![image](https://user-images.githubusercontent.com/10746682/35700639-cfba3d5e-0793-11e8-9d22-e6957cc50c4c.png)

**Comment by letmaik** [comment]
Only in the last screenshot the `.editorconfig` aligns with `test`. So I think it's still broken, no?

**Comment by sandy081** [comment]
Last one is Seti theme, which aligns twisty and icon. So this is expected. 

![image](https://user-images.githubusercontent.com/10746682/35704048-7228c98e-079e-11e8-980e-a9d813443a7b.png)

**Comment by letmaik** [comment]
![uprhoma9](https://user-images.githubusercontent.com/530988/35705799-634f0994-079b-11e8-80b9-a364d1cb41a6.png)

Do you see?

**Comment by sandy081** [comment]
Yes, I see it. This is because, `test` node in the Git tree does not have an icon where as it has icon in the file explorer. And the alignment of icons and twisties happen only in Seti theme.

**Comment by letmaik** [comment]
I'm a bit unsure how I should proceed now if that's the expected behaviour. Do I need to check which theme is active and then decide whether to display a folder icon? I find this a bit weird as that means there's a strong dependency on the semantics of the file explorer, whereas extension views often don't have anything to do with files. I think the problem boils down to the fact that you currently don't know in advance whether the expandable nodes have icons or not. I wouldn't couple this to the file icon themes at all. If you remove that coupling and instead revert to the original behaviour then you could require from developers that either all nodes have icons or none have, otherwise there's no proper alignment. If you want to support the case where expandable nodes for example have no icon but the rest have icons and the alignment should still work (which this issue is about), then this has to be signalled somehow, which could be some kind of style flag when creating the view from an extension. The point is that extension views can use icons for indicating some semantics, and it's not always an option to not display an icon because the file icon theme says so.

So, currently alignment is broken if you use Seti and have icons on all nodes. That should not happen I think.

**Comment by ramya-rao-a** [comment]
@sandy081 Do you want to open another issue to consider https://github.com/Microsoft/vscode/issues/28974#issuecomment-363041973 and mark this one as `verified`?

**Comment by sandy081** [comment]
Reopening it to continue discussion.

**Comment by sandy081** [comment]
@letmaik Thanks for the feedback.

First of all I was bit confused here as I thought you wanted the custom views to be aligned with file explorer based on this [comment](https://github.com/Microsoft/vscode/issues/28974#issuecomment-362416829) and description. 

I agree that extension authors should not be concerned about the theme information. Irrespective of icons/themes, tree nodes has to be aligned by their labels. I see this is the issue you raised if I am not wrong.

I think the crux of the problem here is that trees can have some nodes with icons and some without. If you see in your tree, `test` node has no icon and it's sibling node `.editorconfig` has an icon. To align these two either, I have to push `.editorconfig` node to left which will make it as a sibling to its parent or push `test` node to right, then its alignment w.r.to its parent looks broken.

Right fix here is to align all nodes by label and introduce a place holder icon for nodes missing icons.

So the above tree looks as follows in any theme.

![image](https://user-images.githubusercontent.com/10746682/36037709-db73daee-0dbd-11e8-8870-e1a7d47d762a.png)

Finally, I would recommend to provide icons to avoid these missing icons. You can also provide the `resourceUri` if your node is file/folder from which the icon can be derived.

**Comment by sandy081** [comment]
FYI.. Current placeholder icon is temporary.. will change it if I get a better icon.

**Comment by letmaik** [comment]
I just looked at it and tried different combinations of missing icons, looks good I think! I like that it automatically aligns like Seti if you only have leaf icons. And then as soon as you have a non-leaf icon it switches to icons everywhere including placeholders where necessary. Right?
I think this is good, especially from an extension developers perspective as they now see what they have to do to make it look right (fill in placeholder icons if they use non-leaf icons).

**Comment by sandy081** [comment]
You are right.. twisties and icons are aligned if none of the container(non-leaf) nodes have icons. Very much appreciated with your feedback here to make tree views look much better. 

I will close this once I get a better place holder icon.

**Comment by sandy081** [comment]
@chryw Can you please suggest/provide an icon that can be used as place holders for container nodes  those do not have a icon. For eg: Icon with dotted lines in the following picture

![image](https://user-images.githubusercontent.com/10746682/36037709-db73daee-0dbd-11e8-8870-e1a7d47d762a.png)

**Comment by sandy081** [comment]
@chryw That node can be any as this view is contributed by extensions. Only semantics it has is, it is a node with children.

**Comment by chryw** [comment]
@sandy081 I'm trying to figure out the motivation of adding an "anything" icon here. Is it just for reserving the indentation? Or the icon does need to be informative, like saying what type this node is like other nodes?

**Comment by sandy081** [comment]
@chryw Yes, It is just for indentation and does not need to convey any information.

**Comment by chryw** [comment]
@sandy081 Is it possible to default to folder icon if the node has children? I can't think of a good icon that means "anything" and not confusing. Or maybe leave that space blank if no icon is specified?

**Comment by sandy081** [comment]
Leaving an empty place for the container node makes tree look a bit weird. For now, I am drawing the above icon as placeholder. May be I will continue to have this icon and let extension authors provide proper icon if they do not want place holder icons.

**Comment by sandy081** [comment]
I have to revert and reopen this because extension authors are not liking this placeholder approach to fix the tree alignment issue. I will revisit this with a different approach in next milestone.

**Comment by sandy081** [comment]
Updated current implementation slightly to improve the experience (align the nodes per level). 

Custom alignment for a node is done only when 
- the node is a leaf and has an icon and
- Its parent does not has an icon and
- there is no sibling with children and icon

![image](https://user-images.githubusercontent.com/10746682/37340565-918dff96-26e4-11e8-827e-2084b3f420b3.png)


Otherwise, extension is responsible for the alignment by providing icons. There will not be any placeholder icons.
