### ISSUE TITLE
High CPU overload after update to VSCode 1.14.0

### ISSUE THREAD

**Issue by onury** [Microsoft/vscode#30449]
- VSCode Version: 1.14.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Just open a project. (even without extensions) and Code Helper CPU usage goes too high.

Reproduces without extensions: **Yes**

Arguments of Code Helper process:
```sh
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry --cancellationPipeName /var/folders/c_/gkwddkyn6vs5nkj9cyvf0m8w0000gn/T/vscode-tscancellation-aefeee28373a85d83ef1.sock* --npmLocation "/usr/local/bin/npm"
```

EDIT: Also, Code Helper will not quit after quitting VSCode. I have to force-kill everytime.

**Comment by timosaikkonen** [comment]
Ditto, 1.14 is absolutely murdering my CPU.

**Comment by chrmarti** [comment]
@timosaikkonen Could you check which process and with which arguments this is?

@onury 's command line shows the tsserver.

**Comment by csreddy** [comment]
This is killing my productivity, absolutely unusable. Is there a way to switch to previous version until you release fix for this ?

**Comment by timosaikkonen** [comment]
@chrmarti Damn, didn't think to check that before downgrading. Having too chaotic a day to troubleshoot this further today but I suspect it's tsserver as well, since I'm working on TS projects too.

@csreddy You can grab the previous version from https://code.visualstudio.com/updates/v1_13

**Comment by csreddy** [comment]
@timosaikkonen thank you!

**Comment by alexshak** [comment]
Can confirm this is also happening on Windows 10.

**Comment by mjbvz** [comment]
For anyone running into issues with the VSCode 1.14: you probably don't need to downgrade VSCode, just the TypeScript version. [Here are the instructions on that](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). We previously shipped with TS 2.3.4 so you'll want to try installing that version locally and using it in your workspace

---- 

To help us investigate the CPU usage issue, please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VSCode
1. Reproduce the issue
1. Run the `Open TSServer log File` command and view the `tsserver.log` file

If you can share the ts log file I can take a look through them to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

// fyi @rbuckton

**Comment by dotlouis** [comment]
@mjbvz Having the same issue: vscode lagging and taking up to 25% CPU.
here is my TSlog: https://pastebin.com/MfP4viaV

**Comment by onury** [comment]
@mjbvz downgrading typescript version to 2.3.4 fixes it for now.

**Comment by St1c** [comment]
same here, setting to use workspace version of typescript (2.3.4) didn't help

**Comment by cameron-martin** [comment]
I'm having the same problem and was using the same TS version (2.2.1) as I was using with VSCode version 1.13.1, which does not exhibit this problem.

**Comment by onury** [comment]
@St1c, @cameron-martin  did you first kill Code Helper process?

**Comment by St1c** [comment]
I don't see any Code helper process when I quit Code. When I start it again - with use of workspace typescript (2.3.4) the CPU is still high

**Comment by F0rt1s** [comment]
switching the ts workspace version back to 2.3.4 worked for me.

**Comment by chrmarti** [comment]
@St1c Could you open a new issue so we can investigate separately? (Use: Help > Report Issues to get things pre-filled.)

**Comment by MickeySegal** [comment]
The workaround of disabling TypeScript Hero is discussed in https://github.com/Microsoft/vscode/issues/30486

**Comment by bogomips** [comment]
Same here!
The interface becomes unresponsive for several seconds and I see 
the process /usr/share/code/code using the 100% of the cpu.

GitHub Extension for Visual Studio version: not extensions
Visual Studio version: 1.14.0
I think it happens since the last update, I deactivated every plug-in but it keeps happening.

**Comment by MickeySegal** [comment]
A new version of TypeScript Hero was released with a workaround to this problem.  More information at https://github.com/buehler/typescript-hero/issues/242

**Comment by andy-ms** [comment]
Hi @mjbvz, looking through that log, I noticed that VSCode seems to be asking for `"getApplicableRefactors"` on the same file several times in a row. Is there a way to disable that feature in VSCode so we can see if it's related to the problem?

**Comment by richarddavenport** [comment]
Just venting for a second...I mentioned I had problems with [high cpu](https://github.com/Microsoft/vscode/issues/20893#issuecomment-308179423) and felt like it was pretty much [ignored](https://github.com/Microsoft/vscode/issues/20893#issuecomment-308262869). I suspect that while I was using insiders, this was my problem all along. I really hope that when someone brings up cpu usage problems, the team will take them a little bit more seriously.

**Comment by mjbvz** [comment]
@andy-ms Not on its own but you can try a hack: with a workspace version of typescript, edit the `node_modules/typescript/package.json` version from `2.4.1` to `2.3.9`. This will disable any features that are gated for 2.4, which is mainly the refactoring actions

**Comment by MickeySegal** [comment]
Once people started listing their extensions in https://github.com/Microsoft/vscode/issues/30486 it became clear quickly which extension triggered this bug.  For Insider versions, it is more difficult to get a critical mass of people reporting a problem.  Selectively turning off extensions can get the same information, but since this problem was evident only sporadically on fast computers, the cycle time on getting information wasn't fast.  People with slower computers were better in the role of canaries in the mine.

**Comment by andy-ms** [comment]
@MickeySegal The original post by @onury says this happened without extensions. I presume the same is true for @dotlouis's log.

**Comment by MickeySegal** [comment]
Interesting.  The problems in https://github.com/Microsoft/vscode/issues/30486 went away with disabling extensions.  It seems like there is more than one cause to these CPU issues with VSCode 1.14.0

**Comment by chrmarti** [comment]
@MickeySegal Indeed, this one is about the TypeScript server which is unrelated to #30486. (Thanks for publishing your extension with a workaround!)

**Comment by MickeySegal** [comment]
We have multiple threads here that are getting a bit conflated.  And https://github.com/buehler gets the credit for posting a quick fix for bug that tripped up TypeScript Hero - my role was just to add a thread https://github.com/buehler/typescript-hero/issues/242 that I knew he'd see.

**Comment by mjbvz** [comment]
If you are seeing this issue and have confirmed that the `Code Helper` process with `tsserver` in the arguments is the one with high cpu usage: please share a project that consistently causes this problem. If you can't post the project publicly, you can also email it to me: `matb AT microsoft.com`

---

Based on @andy-ms' initial investigation, I've disabled refactoring with 6297536. We'll continue looking into the problem but the next VSCode insiders build will have refactoring disabled. Once that comes out, please give it a try to see if it resolves the issue

**Comment by zfeher** [comment]
I am experiencing this high CPU load when I try to search in files (on Windows 10 x64). Reverted back to 1.13 for now (where I could not disable the auto update so need to keep one window alive to prevent the auto update).

**Comment by King66** [comment]
@zfeher 
"update.channel": "none"

but you can help to investigate the issue using 1,14

**Comment by dmlemos** [comment]
These two are killing my CPU. Happens when I open the home folder.

```
148.3  7.8  4776876 1302328   ??  R    11:33am   1:36.01 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=searchService
102.2 10.2  4897348 1710032   ??  R    11:33am   2:49.81 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
```

**Comment by mjbvz** [comment]
@dmlemos Can you please open a new issue for the search service cpu usage? @roblourens can help you investigate this

**Comment by dmlemos** [comment]
@mjbvz I am confused. There were a couple issues related to this that were closed.

According to #26726, it was a problem with TypeScript. The issue is closed and I assume it is already on the latest release. Please confirm.

**Comment by roblourens** [comment]
"high cpu" is a very generic issue. Yours indicates an issue with the searchService which is different process than what we're talking about here.

**Comment by dmlemos** [comment]
Indeed. I only commented on one of the issues [here](https://github.com/Microsoft/vscode/issues/26726#issuecomment-301742457). I have had always this issue since then.
My mistake for not putting into into a new issue.

I will create a new one 😄

**Comment by ztolley** [comment]
Windows 10 with plugins disabled on a Ryzen 1800x and a visual studio code process is taking up on average 8% CPU doing nothing at all.  1.14.2

**Comment by tianjianchn** [comment]
I'm using macOS Sierra, and I always use 2 or 3 VSCode Windows at the same time. One for NodeJS project, another for Vue project. It's frequent that VSCode cause CPU high load, one Code and one Code Helper process has 60-70% CPU each. 
I tried 1.14, 1.13, 1.12, 1.11, all are same. 

But, **in 1.9 it's fine**, the problem never happened!

**Comment by tianjianchn** [comment]
Sorry, 1.9 is same as others.
I try to reproduce the problem, and now things may be more clear. 
I'm using [Witch](https://manytricks.com/witch) to switch applications/windows in current space.  That seems to be the problem. Using system shortcut `` cmd+` `` or mouse click to switch windows is OK.

Tested in 1.9, 1.14 with steps below:
1. Disable all extensions, then restart VSCode
2. Open two VSCode windows(use File->New Window)
3. Focus one window, then use witch to switch to another window. one Code process and one Code Helper process will have 80-100% CPU each.
4. It keeps long time, unless I click the `Help` menu then CPU goes down(Other menus don't work)

**Comment by laurb9** [comment]
In my case (OS X), turns out the Code Helper process that remained running after closing VSCode was stuck in an infinite recursive loop reading /Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/.... although I don't understand why it has any business scanning anything other than the project I told it to load.

stat64("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Comic.sfrframe/Contents/Resources/we\0", 0x7FFF5486A460, 0x1000)		 = 0 0
stat64("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Crayon Line.sfrframe\0", 0x7FFF5486AA10, 0x1000)		 = 0 0
stat64("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Crayon Line.sfrframe\0", 0x7FFF5486A970, 0x1000)		 = 0 0
open_nocancel("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Crayon Line.sfrframe\0", 0x1100004, 0x110709D90)		 = 27 0
fstatfs64(0x1B, 0x7FFF54869FA8, 0x110709D90)		 = 0 0
getdirentries64(0x1B, 0x7FF418807C00, 0x1000)		 = 88 0
getdirentries64(0x1B, 0x7FF418807C00, 0x1000)		 = 0 0
close_nocancel(0x1B)		 = 0 0
stat64("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Crayon Line.sfrframe/Contents\0", 0x7FFF5486A830, 0x1000)		 = 0 0
stat64("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Crayon Line.sfrframe/Contents\0", 0x7FFF5486A790, 0x1000)		 = 0 0

**Comment by coreylendo** [comment]
Why do I keep getting these is this my account u all are marketing changes too


Sent from Yahoo Mail for iPhone


On Saturday, August 5, 2017, 13:55, Laurentiu Badea <notifications@github.com> wrote:


In my case (OS X), turns out the Code Helper process that remained running after closing VSCode was stuck in an infinite recursive loop reading /Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/.... although I don't understand why it has any business scanning anything other than the project I told it to load.

stat64("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Comic.sfrframe/Contents/Resources/we\0", 0x7FFF5486A460, 0x1000) = 0 0
stat64("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Crayon Line.sfrframe\0", 0x7FFF5486AA10, 0x1000) = 0 0
stat64("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Crayon Line.sfrframe\0", 0x7FFF5486A970, 0x1000) = 0 0
open_nocancel("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Crayon Line.sfrframe\0", 0x1100004, 0x110709D90) = 27 0
fstatfs64(0x1B, 0x7FFF54869FA8, 0x110709D90) = 0 0
getdirentries64(0x1B, 0x7FF418807C00, 0x1000) = 88 0
getdirentries64(0x1B, 0x7FF418807C00, 0x1000) = 0 0
close_nocancel(0x1B) = 0 0
stat64("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Crayon Line.sfrframe/Contents\0", 0x7FFF5486A830, 0x1000) = 0 0
stat64("Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Volumes/Macintosh HD/Applications/Keynote.app/Contents/Resources/Frames/Crayon Line.sfrframe/Contents\0", 0x7FFF5486A790, 0x1000) = 0 0

**Comment by mjbvz** [comment]
Closing this issue as we addressed the original issue with the TS server. 

If you are still seeing CPU usage issues, please open a new issue and include the command line arguments of the process that is using up the CPU. There are multiple root causes of these sort of bugs so it's generally easier if we track each case in a separate issue

**Comment by chrmarti** [comment]
@laurb9 Does the folder you opened in VSCode have symlinks to outside folders? Could you open a new issue for this? (It looks like `find` might have ended in an error and you are seeing the in-node file traversal.)

**Comment by onury** [comment]
@mjbvz can you tell me how is this addressed? I'm having the same problem with VSCode v1.14.2 and TypeScript v2.4.2 (both latest as of today). I cannot use it unless I downgrade TS to v2.3.4.

This issue is not resolved and this should be re-opened.

**Comment by mjbvz** [comment]
@onury Please try VSCode 1.15 (the current insiders build) and [collect the logs I've asked for](  https://github.com/Microsoft/vscode/issues/30449#issuecomment-314666925). Without these, this issue is not actionable.

I closed the issue because there was no further confirmations of original TSServer issue in the past 20+ days and we fixed some bugs that could have been causing this. Without more information though, it was not possible to confirm if the original problem you reported had been addressed or not

**Comment by onury** [comment]
@mjbvz Tested with VSCode v1.5 and TS v2.4.2
Still, `tsserver` hits the CPU around 120-130% on MacBookPro  Quad-core 2,5 GHz Intel Core i7  
Calms down if I switch to TS v2.3.4

Code Helper process args:
```
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry --cancellationPipeName /var/folders/c_/gkwddkyn6vs5nkj9cyvf0m8w0000gn/T/vscode-tscancellation-6805e77755247eccd402.sock* --logVerbosity verbose --logFile /var/folders/c_/gkwddkyn6vs5nkj9cyvf0m8w0000gn/T/vscode-tsserver-log-fnT9Fc/tsserver.log --npmLocation "/usr/local/bin/npm"
```

**Comment by onury** [comment]
@mjbvz this issue is still NOT resolved. I'm trying VSCode v1.17.2 - still the same. Cannot use it. So pls re-open or I'll have to open another duplicate issue.
