### ISSUE TITLE
Disable Italic Option Feature Request

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/vscode#32579]
- VSCode Version: 1.15.0
- OS Version: Windows 10 Version 1703 Build 15063.540

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

Sometimes authors of themes use italic for `comments`, `language keywords` and for other things. In some cases that's looks not so good (as example what I mean you can read my issue/feature-request on Material Theme https://github.com/equinusocio/vsc-material-theme/issues/81). Of course we can change this in theme source code manually but it will be great to have Disable Italic Option at all in vscode config file.

For example in Sublime Text 3 we have `no_italic` font option to disable italic at all:

```
"font_options":
[
	"no_italic"
],
```

**Comment by tinymins** [comment]
+1

**Comment by alexandrudima** [comment]
@aeschli 

Would this be something doable via user settings? (since those rules get appended to the theme rules anyways?)

**Comment by Korvox** [comment]
I ran into this issue with the Atom One theme, and adding the following setting worked for me:

```javascript
"editor.tokenColorCustomizations": {
    "textMateRules": [
        { 
            "scope": [
                "comment",
            ],
            "settings": {
                "fontStyle": "",
            }
        }
    ]
}
```

So for anyone that wants "normal" font styling on comments, just drop that in your settings.

**Comment by Zx-EvM** [comment]
@Korvox thanks. That's helpful for me:

```
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": [
                "comment",
                "punctuation.definition.comment",
                "variable.language"
            ],
            "settings": {
                "fontStyle": ""
            }
        }
    ]
}
```

`"punctuation.definition.comment"` to disable italic on the characters creating comments (like: `//` and others).

**Comment by mohouyizme** [comment]
Disable it for all:
```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "scope": [
        "comment",
        "comment.block",
        "comment.block.documentation",
        "comment.line",
        "constant",
        "constant.character",
        "constant.character.escape",
        "constant.numeric",
        "constant.numeric.integer",
        "constant.numeric.float",
        "constant.numeric.hex",
        "constant.numeric.octal",
        "constant.other",
        "constant.regexp",
        "constant.rgb-value",
        "emphasis",
        "entity",
        "entity.name",
        "entity.name.class",
        "entity.name.function",
        "entity.name.method",
        "entity.name.section",
        "entity.name.selector",
        "entity.name.tag",
        "entity.name.type",
        "entity.other",
        "entity.other.attribute-name",
        "entity.other.inherited-class",
        "invalid",
        "invalid.deprecated",
        "invalid.illegal",
        "keyword",
        "keyword.control",
        "keyword.operator",
        "keyword.operator.new",
        "keyword.operator.assignment",
        "keyword.operator.arithmetic",
        "keyword.operator.logical",
        "keyword.other",
        "markup",
        "markup.bold",
        "markup.changed",
        "markup.deleted",
        "markup.heading",
        "markup.inline.raw",
        "markup.inserted",
        "markup.italic",
        "markup.list",
        "markup.list.numbered",
        "markup.list.unnumbered",
        "markup.other",
        "markup.quote",
        "markup.raw",
        "markup.underline",
        "markup.underline.link",
        "meta",
        "meta.block",
        "meta.cast",
        "meta.class",
        "meta.function",
        "meta.function-call",
        "meta.preprocessor",
        "meta.return-type",
        "meta.selector",
        "meta.tag",
        "meta.type.annotation",
        "meta.type",
        "punctuation.definition.string.begin",
        "punctuation.definition.string.end",
        "punctuation.separator",
        "punctuation.separator.continuation",
        "punctuation.terminator",
        "storage",
        "storage.modifier",
        "storage.type",
        "string",
        "string.interpolated",
        "string.other",
        "string.quoted",
        "string.quoted.double",
        "string.quoted.other",
        "string.quoted.single",
        "string.quoted.triple",
        "string.regexp",
        "string.unquoted",
        "strong",
        "support",
        "support.class",
        "support.constant",
        "support.function",
        "support.other",
        "support.type",
        "support.type.property-name",
        "support.variable",
        "variable",
        "variable.language",
        "variable.name",
        "variable.other",
        "variable.other.readwrite",
        "variable.parameter"
      ],
      "settings": {
        "fontStyle": ""
      }
    }
  ]
}
```

**Comment by hrvoj3e** [comment]
Just like to add some references for others who want to override specific language or theme style setting.

- TextMate grammar intro
  - https://manual.macromates.com/en/language_grammars
- Excellent extension for pinpointing which TextMate scope (or scope hierarchy) tu use
  - https://marketplace.visualstudio.com/items?itemName=siegebell.scope-info

@mohouyizme [covered](https://github.com/Microsoft/vscode/issues/32579#issuecomment-341502559) a lot of scopes but I wanted to override language specific only and not use all of them atm.

**Comment by gibbok** [comment]
@mohouyizme Great snippet!

In your configurations all italics are disabled expect for "module" example the word "data" in the following snippet for a .tsx file is still in italic

`import { data as scrapReasons } from './testData`
-----------^^

What is the right configuration to set that font to "normal" style too? Thanks!

**Comment by mohouyizme** [comment]
I know it's not the best way to do things but add this line to the list above [Microsoft/vscode#32579 (comment)](https://github.com/Microsoft/vscode/issues/32579#issuecomment-341502559)
```
"meta.import variable.other.readwrite"
```

**Comment by mohouyizme** [comment]
Here is a simple way to find the scopes to add them to this list:
```js
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "scope": [
         // Add scopes name to this array
      ],
      "settings": {
        "fontStyle": ""
      }
    }
  ]
}
```

## First focus your mouse on the italic or bold word:
![screenshot_1](https://user-images.githubusercontent.com/23297439/37405939-de982592-278d-11e8-9316-41ae4aef8ad0.png)
## Then open the Command Palette
![screenshot_2](https://user-images.githubusercontent.com/23297439/37406017-12663fbc-278e-11e8-96c9-927630ca4f91.png)
## Search for: "Developer: Inspect TM Scopes"
![screenshot_3](https://user-images.githubusercontent.com/23297439/37415638-cea1e55e-27a3-11e8-8c69-db03f49c3c4f.png)
## It will appear a popup contains some information about the scope
![screenshot_5](https://user-images.githubusercontent.com/23297439/37416074-cbf0448a-27a4-11e8-9673-165eab73961b.png)
## Add the highlighted part to the scope array mentioned above
```js
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "scope": [
         "meta.import variable.other.readwrite",
         "other scopes ..."
      ],
      "settings": {
        "fontStyle": ""
      }
    }
  ]
}
```
## Finally you can find me on twitter: [@mohouyizme](https://twitter.com/mohouyizme)
![GIF](https://media.giphy.com/media/6HOkD1pSCne4E/giphy.gif)

**Comment by ayaorei** [comment]
@mohouyizme sodo i just paste the code on the user settings? or do i need to put fontstyle?

**Comment by kelset** [comment]
@ayaorei yes, basically you can simply copy any variation of @mohouyizme's [snippet](https://github.com/Microsoft/vscode/issues/32579#issuecomment-341502559) into your User Preferences and you are good to go :)

**Comment by if-jds** [comment]
This popped up yesterday in Material Theme after an upgrade to 1.31.1. All of the sudden every class in my SCSS files became italicized. Instead of slowly losing my mind throughout the day, this post helped me write this settings block:

```
    "editor.tokenColorCustomizations": {
        "textMateRules": [{
            "scope": [
                "entity.other.attribute-name",
            ],                
            "settings":{
                "fontStyle": ""
            }
        }]
    },
```

That's the scope if you're running into weird italicized classes!

**Comment by gdmachado** [comment]
On the spirit of doing it the hacky way, a better solution I found is, instead of adding every single scope to `editor.tokenColorCustomizations`, you can use the [vscode-custom-css](https://github.com/be5invis/vscode-custom-css) extension, and then set this in your custom css file:

```css
.mtki {
    font-style: normal;
}
```

It will apply to every single scope if that's what you're looking for.

**Comment by kiwi0fruit** [comment]
Is there a way to only prevent terrible auto-slant but have italics when the font has them? For example in cases when the main font has italics but fallback CJK font does not?

**Comment by SNikalaichyk** [comment]
+1

**Comment by theAkito** [comment]
Interesting and sad at the same time, how so many workarounds accumulated over time and yet no real fix seems to be implemented in the software, itself, even after roughly 3 years. :/

**Comment by fuadnafiz98** [comment]
Maybe should make a extension that overwrite the settings.json 😞

**Comment by TheBossProSniper** [comment]
Hey guys,

I have disabled it in the settings.json however, it still hasn't worked:

```
{
    "[dart]": {
        "editor.trimAutoWhitespace": false,
        "editor.autoClosingBrackets": "always",
        "diffEditor.ignoreTrimWhitespace": true,
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            80
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "editor.fontFamily": "Cascadia Code",
    "window.zoomLevel": 1.5,
    "workbench.iconTheme": "material-icon-theme",
    "terminal.integrated.fontSize": 15,
    "terminal.integrated.cursorStyle": "line",
    "explorer.confirmDelete": false,
    "files.autoSaveDelay": 300,
    "editor.fontLigatures": true,
    "git.enableSmartCommit": true,
    "[json]": {
        "editor.quickSuggestions": {
            "strings": true
        },
        "editor.suggest.insertMode": "replace"
    },
    "editor.fontSize": 20,
    "editor.minimap.enabled": false,
    "python.pythonPath": "/usr/local/opt/python@3.8/bin/python3.8",
    "editor.suggestSelection": "first",
    "python.languageServer": "Microsoft",
    "kite.showWelcomeNotificationOnStartup": false,
    "python.linting.enabled": true,
    "editor.defaultFormatter": "Dart-Code.dart-code",
    "editor.formatOnSave": true,
    "explorer.confirmDragAndDrop": false,
    "dart.previewBazelWorkspaceCustomScripts": true,
    "dart.previewFlutterUiGuides": true,
    "dart.previewFlutterUiGuidesCustomTracking": true,
    "scm.inputFontFamily": "defaultSF Mono",
    "python.dataScience.askForKernelRestart": false,
    "files.autoSave": "afterDelay",
    "python.dataScience.alwaysTrustNotebooks": true,
    "cSpell.userWords": [
        "sqlite"
    ],
    "git.confirmSync": false,
    "editor.fontWeight": "300",
    "editor.tokenColorCustomizations": {
        "scope": [
            "comment",
            "comment.block",
            "comment.block.documentation",
            "comment.line",
            "constant",
            "constant.character",
            "constant.character.escape",
            "constant.numeric",
            "constant.numeric.integer",
            "constant.numeric.float",
            "constant.numeric.hex",
            "constant.numeric.octal",
            "constant.other",
            "constant.regexp",
            "constant.rgb-value",
            "emphasis",
            "entity",
            "entity.name",
            "entity.name.class",
            "entity.name.function",
            "entity.name.method",
            "entity.name.section",
            "entity.name.selector",
            "entity.name.tag",
            "entity.name.type",
            "entity.other",
            "entity.other.attribute-name",
            "entity.other.inherited-class",
            "invalid",
            "invalid.deprecated",
            "invalid.illegal",
            "keyword",
            "keyword.control",
            "keyword.operator",
            "keyword.operator.new",
            "keyword.operator.assignment",
            "keyword.operator.arithmetic",
            "keyword.operator.logical",
            "keyword.other",
            "markup",
            "markup.bold",
            "markup.changed",
            "markup.deleted",
            "markup.heading",
            "markup.inline.raw",
            "markup.inserted",
            "markup.italic",
            "markup.list",
            "markup.list.numbered",
            "markup.list.unnumbered",
            "markup.other",
            "markup.quote",
            "markup.raw",
            "markup.underline",
            "markup.underline.link",
            "meta",
            "meta.block",
            "meta.cast",
            "meta.class",
            "meta.function",
            "meta.function-call",
            "meta.preprocessor",
            "meta.return-type",
            "meta.selector",
            "meta.tag",
            "meta.type.annotation",
            "meta.type",
            "punctuation.definition.string.begin",
            "punctuation.definition.string.end",
            "punctuation.separator",
            "punctuation.separator.continuation",
            "punctuation.terminator",
            "storage",
            "storage.modifier",
            "storage.type",
            "string",
            "string.interpolated",
            "string.other",
            "string.quoted",
            "string.quoted.double",
            "string.quoted.other",
            "string.quoted.single",
            "string.quoted.triple",
            "string.regexp",
            "string.unquoted",
            "strong",
            "support",
            "support.class",
            "support.constant",
            "support.function",
            "support.other",
            "support.type",
            "support.type.property-name",
            "support.variable",
            "variable",
            "variable.language",
            "variable.name",
            "variable.other",
            "variable.other.readwrite",
            "variable.parameter",
            "source.dart",
          ],
          "settings": {
            "fontStyle": ""
          }
    },
    "workbench.colorTheme": "Dracula"
}
```

However,

When I go back to my editor:

![Screenshot 2020-08-08 at 10 05 58 AM](https://user-images.githubusercontent.com/63039748/89702418-c399a100-d95e-11ea-87c5-fe950477bc61.png)

Here is what to developer token option tells me:
![Screenshot 2020-08-08 at 10 07 07 AM](https://user-images.githubusercontent.com/63039748/89702438-ee83f500-d95e-11ea-8763-55b1aebf53a6.png)


I appreciate your help. Thanks!

**Comment by fuadnafiz98** [comment]
don't know working fine for me with same settings.json :| 
![Screenshot from 2020-08-08 12-38-12](https://user-images.githubusercontent.com/43469396/89704266-33665680-d974-11ea-9d44-4323b08d57fb.png)

**Comment by mrillusi0n** [comment]
I'm sorry, why hasn't this been fixed yet?

**Comment by mohouyizme** [comment]
@mrillusi0n I'm not sure if it's a problem in the first place, the font styles mainly come with themes, you may open an issue or even contribute to your favorite theme and add a variant that comes without font styles, or you can use the snippet above.

**Comment by mrillusi0n** [comment]
Yes, sorry about that. Now that I think about it, if the devs kept on adding every feature that was requested... 😵
BLOAAATSSS.

**Comment by libertypi** [comment]
Instead of adding hundreds of lines to my settings.json, I feel it is easier for me to modify the themes. So I write a dirty python script to do it. The script delete all the italic fonts in themes. But you have to run it every time the theme get updated.

```python
#!/usr/bin/env python3

import json
import os
import re
from pathlib import Path

# the `extensions` dir of your vscode profile,
# in Linux or macOS, this should be:
# extdir = Path("~/.vscode/extensions").expanduser()
# in WSL, should be like this:
extdir = Path("/mnt/c/Users/USERNAME/.vscode/extensions")

# the folder name of the themes you want to modify,
# without version numbers
themes = (
    "equinusocio.vsc-material-theme",
    "equinusocio.vsc-community-material-theme",
    "dracula-theme.theme-dracula",
)


def modify_json(themedir: Path):

    with open(themedir.joinpath("package.json"), "r", encoding="utf-8") as f:
        files = [
            themedir.joinpath(d["path"])
            for d in json.load(f)["contributes"]["themes"]
        ]

    for file in files:
        with open(file, "r+", encoding="utf-8") as f:
            data = json.load(f)
            for colors in data["tokenColors"]:
                settings = colors["settings"]
                font = settings.get("fontStyle", "")
                if "italic" in font:
                    font = re.sub(r"\s*italic\s*", "", font)
                    if font:
                        settings["fontStyle"] = font
                    else:
                        del settings["fontStyle"]
            f.seek(0)
            json.dump(data, f, indent=4, ensure_ascii=False)
            f.truncate()


def main():
    pattern = re.compile(rf'({"|".join(themes)})-[\d.]+', re.I)
    for name in filter(pattern.fullmatch, os.listdir(extdir)):
        modify_json(extdir.joinpath(name))
        print(f"{name} modified.")


if __name__ == "__main__":
    main()
```

**Comment by teresaejunior** [comment]
Please, if this is ever implemented, I would like an option for disabling bold text too! Thanks!

**Comment by dspacejs** [comment]
I'm surprised this still isn't a setting, it's a rudimentary feature. Having to manually set the `fontStyle` for every single scope is a bit of a pain.

**Comment by zaydek** [comment]
@dspacejs This might help.

This was enough for me:

```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "scope": [
        "comment",
        "punctuation.definition.comment",
      ],
      "settings": {
        "fontStyle": ""
      }
    }
  ]
},
```

Sometimes `comment` alone isn’t enough.

The problem is that italics are theme-specific. That being said, you can also override scopes but note this approach is _also_ theme-specific.

[This comment](https://github.com/microsoft/vscode/issues/32579#issuecomment-373090396) explains how to work out how to determine specifically which scopes to use so you don’t have to be exhaustive.

**Comment by dspacejs** [comment]
@zaydek that's cleaner, but users should only have to create a complex configuration if they're looking to only italicise certain nodes. I don't want any italics at all, and I'm guessing there's many users who don't.

**Comment by REYNEP** [comment]
Hey, I found a way to Highlight NON-ASCII Characters,   giving them a Custom TEXTMate Scope

https://github.com/microsoft/vscode/issues/25895#issuecomment-890614837

**Comment by sana-ajani** [comment]
I wonder, could we implement [this](https://github.com/microsoft/vscode/issues/32579#issuecomment-341502559) as a command so it's easier for users to accomplish? I received feedback from a user that italics are difficult and not very readable for visually impaired users (latest comments on the Dracula theme repo: https://github.com/dracula/visual-studio-code/issues/78). Ideally, all users should be able to use themes without text formatting, instead of having theme authors built alternate versions? 

cc @isidorn adding accessibility label to this

**Comment by jeffteixeira** [comment]
Any news?

**Comment by igdev116** [comment]
How can I turn off italic font of VS code destructuring? Thanks a lot! 🎅
![image](https://user-images.githubusercontent.com/70432453/134791381-f2a0dcb6-1b51-4517-99fd-1514f85a7fe4.png)

**Comment by amanov-begli** [comment]
> Instead of adding hundreds of lines to my settings.json, I feel it is easier for me to modify the themes. So I write a dirty python script to do it. The script delete all the italic fonts in themes. But you have to run it every time the theme get updated.
> 
> ```python
> #!/usr/bin/env python3
> 
> import json
> import os
> import re
> from pathlib import Path
> 
> # the `extensions` dir of your vscode profile,
> # in Linux or macOS, this should be:
> # extdir = Path("~/.vscode/extensions").expanduser()
> # in WSL, should be like this:
> extdir = Path("/mnt/c/Users/USERNAME/.vscode/extensions")
> 
> # the folder name of the themes you want to modify,
> # without version numbers
> themes = (
>     "equinusocio.vsc-material-theme",
>     "equinusocio.vsc-community-material-theme",
>     "dracula-theme.theme-dracula",
> )
> 
> 
> def modify_json(themedir: Path):
> 
>     with open(themedir.joinpath("package.json"), "r", encoding="utf-8") as f:
>         files = [
>             themedir.joinpath(d["path"])
>             for d in json.load(f)["contributes"]["themes"]
>         ]
> 
>     for file in files:
>         with open(file, "r+", encoding="utf-8") as f:
>             data = json.load(f)
>             for colors in data["tokenColors"]:
>                 settings = colors["settings"]
>                 font = settings.get("fontStyle", "")
>                 if "italic" in font:
>                     font = re.sub(r"\s*italic\s*", "", font)
>                     if font:
>                         settings["fontStyle"] = font
>                     else:
>                         del settings["fontStyle"]
>             f.seek(0)
>             json.dump(data, f, indent=4, ensure_ascii=False)
>             f.truncate()
> 
> 
> def main():
>     pattern = re.compile(rf'({"|".join(themes)})-[\d.]+', re.I)
>     for name in filter(pattern.fullmatch, os.listdir(extdir)):
>         modify_json(extdir.joinpath(name))
>         print(f"{name} modified.")
> 
> 
> if __name__ == "__main__":
>     main()
> ```

This works for perfectly! Thank you so much!!! And be well!

**Comment by chairmanbrando** [comment]
It's bananas that this is still an issue FIVE YEARS after this feature request was opened! 💀

A word of caution for Google visitors: @libertypi's script doesn't seem to work for themes with C-style comments in their JSON. This was *all* the ones I tried, e.g. Wes Bos's Cobalt2, on my Mac. Python's built-in JSON parser doesn't seem to support such comments. :c

**Comment by Pasynko** [comment]
> It's not a dynamic way but add those lines to your vs code settings:
> 
> ```json
> "editor.tokenColorCustomizations": {
>   "textMateRules": [
>     {
>       "scope": [
>         "comment",
>         "comment.block",
>         "comment.block.documentation",
>         "comment.line",
>         "constant",
>         "constant.character",
>         "constant.character.escape",
>         "constant.numeric",
>         "constant.numeric.integer",
>         "constant.numeric.float",
>         "constant.numeric.hex",
>         "constant.numeric.octal",
>         "constant.other",
>         "constant.regexp",
>         "constant.rgb-value",
>         "emphasis",
>         "entity",
>         "entity.name",
>         "entity.name.class",
>         "entity.name.function",
>         "entity.name.method",
>         "entity.name.section",
>         "entity.name.selector",
>         "entity.name.tag",
>         "entity.name.type",
>         "entity.other",
>         "entity.other.attribute-name",
>         "entity.other.inherited-class",
>         "invalid",
>         "invalid.deprecated",
>         "invalid.illegal",
>         "keyword",
>         "keyword.control",
>         "keyword.operator",
>         "keyword.operator.new",
>         "keyword.operator.assignment",
>         "keyword.operator.arithmetic",
>         "keyword.operator.logical",
>         "keyword.other",
>         "markup",
>         "markup.bold",
>         "markup.changed",
>         "markup.deleted",
>         "markup.heading",
>         "markup.inline.raw",
>         "markup.inserted",
>         "markup.italic",
>         "markup.list",
>         "markup.list.numbered",
>         "markup.list.unnumbered",
>         "markup.other",
>         "markup.quote",
>         "markup.raw",
>         "markup.underline",
>         "markup.underline.link",
>         "meta",
>         "meta.block",
>         "meta.cast",
>         "meta.class",
>         "meta.function",
>         "meta.function-call",
>         "meta.preprocessor",
>         "meta.return-type",
>         "meta.selector",
>         "meta.tag",
>         "meta.type.annotation",
>         "meta.type",
>         "punctuation.definition.string.begin",
>         "punctuation.definition.string.end",
>         "punctuation.separator",
>         "punctuation.separator.continuation",
>         "punctuation.terminator",
>         "storage",
>         "storage.modifier",
>         "storage.type",
>         "string",
>         "string.interpolated",
>         "string.other",
>         "string.quoted",
>         "string.quoted.double",
>         "string.quoted.other",
>         "string.quoted.single",
>         "string.quoted.triple",
>         "string.regexp",
>         "string.unquoted",
>         "strong",
>         "support",
>         "support.class",
>         "support.constant",
>         "support.function",
>         "support.other",
>         "support.type",
>         "support.type.property-name",
>         "support.variable",
>         "variable",
>         "variable.language",
>         "variable.name",
>         "variable.other",
>         "variable.other.readwrite",
>         "variable.parameter"
>       ],
>       "settings": {
>         "fontStyle": ""
>       }
>     }
>   ]
> }
> --.          {
>       "support.me"
>        "cloud"
}

**Comment by chairmanbrando** [comment]
@Pasynko I had to add `keyword.control.return` to that list. I still say it's bananas that we need to add 111 lines to our settings JSON to disable italics instead of checking one box. D:

**Comment by lvfxbr** [comment]
The solutions above didn't worked for me, I am using Ubuntu 22.04 LTS 64-bit, note that the fonts of integrated terminal are affected:

![italic](https://user-images.githubusercontent.com/98402608/184445424-be2f0382-0319-4c4e-b7e8-df93124b2bf1.png)

**Comment by fastmarketo** [comment]
I implemented the above still it completely didn't get me rid of the italics in the "Dark Theme".
![image](https://user-images.githubusercontent.com/6827222/197744894-aafd62f5-eb46-44a2-80dc-dcb6b8a84db7.png)

Full code in settings.json:

```
{
    "workbench.colorTheme": "Dark Theme",
    "editor.fontFamily": "Fira Code, Menlo, Monaco, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "terminal.integrated.fontSize": 20,
    "editor.fontSize": 20,
    "editor.tabSize": 2,
    "editor.tokenColorCustomizations": {   
        "textMateRules": [
          {
            "scope": [
              "comment",
              "comment.block",
              "comment.block.documentation",
              "comment.line",
              "constant",
              "constant.character",
              "constant.character.escape",
              "constant.numeric",
              "constant.numeric.integer",
              "constant.numeric.float",
              "constant.numeric.hex",
              "constant.numeric.octal",
              "constant.other",
              "constant.regexp",
              "constant.rgb-value",
              "emphasis",
              "entity",
              "entity.name",
              "entity.name.class",
              "entity.name.function",
              "entity.name.method",
              "entity.name.section",
              "entity.name.selector",
              "entity.name.tag",
              "entity.name.type",
              "entity.other",
              "entity.other.attribute-name",
              "entity.other.inherited-class",
              "invalid",
              "invalid.deprecated",
              "invalid.illegal",
              "keyword",
              "keyword.control",
              "keyword.operator",
              "keyword.operator.new",
              "keyword.operator.assignment",
              "keyword.operator.arithmetic",
              "keyword.operator.logical",
              "keyword.other",
              "markup",
              "markup.bold",
              "markup.changed",
              "markup.deleted",
              "markup.heading",
              "markup.inline.raw",
              "markup.inserted",
              "markup.italic",
              "markup.list",
              "markup.list.numbered",
              "markup.list.unnumbered",
              "markup.other",
              "markup.quote",
              "markup.raw",
              "markup.underline",
              "markup.underline.link",
              "meta",
              "meta.block",
              "meta.cast",
              "meta.class",
              "meta.function",
              "meta.function-call",
              "meta.preprocessor",
              "meta.return-type",
              "meta.selector",
              "meta.tag",
              "meta.type.annotation",
              "meta.type",
              "punctuation.definition.string.begin",
              "punctuation.definition.string.end",
              "punctuation.separator",
              "punctuation.separator.continuation",
              "punctuation.terminator",
              "storage",
              "storage.modifier",
              "storage.type",
              "string",
              "string.interpolated",
              "string.other",
              "string.quoted",
              "string.quoted.double",
              "string.quoted.other",
              "string.quoted.single",
              "string.quoted.triple",
              "string.regexp",
              "string.unquoted",
              "strong",
              "support",
              "support.class",
              "support.constant",
              "support.function",
              "support.other",
              "support.type",
              "support.type.property-name",
              "support.variable",
              "variable",
              "variable.language",
              "variable.name",
              "variable.other",
              "variable.other.readwrite",
              "variable.parameter"
            ],
            "settings": {
              "fontStyle": ""
            }
          }
        ]
      },
    "oneDarkPro.italic": false,
}


```

**Comment by geekysaurabh001** [comment]
2023 and this accessibility issue is still not fixed.

**Comment by MariuzM** [comment]
For me textMateRules does not work, but this does

```
  "editor.semanticTokenColorCustomizations": {
    "enabled": true,
    "rules": {
      "*": {
        "italic": false
      },
  },
```

**Comment by gma** [comment]
> Tested with Flutter code base and One Dark Pro theme

That's awesome @MariuzM, great discovery. I've disabled my textMateRules settings and tested your rule with a few themes. I've had good (but not perfect) results.

Sarah Drasner's "In Bed by 7pm" theme uses italics for a few things, and your new rule disables most of them. I'm still seeing italics for comments though.

With Sarah's Night Owl theme (the version with italics) this new settings removes lots of the italics, but I'm still seeing italics on `keyword.control` and `entity.name.function` scopes.

I tried Material Theme Darker too, and that also italicises `keyword.control` scopes.

I'm going to keep your `"italic": false` rule, and re-enable my `textMateRules` setting, which is largely based on the info previously shared in this issue.

So far, I've collected the following additions to the scopes reported by others in this issue:

```
"constant.language.json.comments",
"constant.language.boolean.false.tsx",
"constant.language.boolean.true.tsx",
"keyword.control.return",
"support.type.builtin.tsx",
"variable.other.object",
"variable.other.object.property.tsx",
```

**Comment by chairmanbrando** [comment]
I also removed my `textMateRules` to test @MariuzM's method, and I installed that same "In Bed by 7pm" theme as @gma did. Italics out the wazanus:

![Screenshot 2023-07-21 at 5 31 42 PM](https://github.com/microsoft/vscode/assets/25331878/bb975617-ee2f-48d5-960a-60d9578e138c)

...At least in PHP. And, yes, the comments are all italicized too. It's _bananas_ that the Code devs still haven't provided a sane method to turn these off. It shouldn't require adding 700 lines to your settings file!

**Comment by Smecta** [comment]
> 以下是查找范围并将其添加到此列表的简单方法：
> 
> ```js
> "editor.tokenColorCustomizations": {
>   "textMateRules": [
>     {
>       "scope": [
>          // Add scopes name to this array
>       ],
>       "settings": {
>         "fontStyle": ""
>       }
>     }
>   ]
> }
> ```
> 
> ## 首先将鼠标聚焦在斜体或粗体单词上：
> 首先将鼠标聚焦在斜体或粗体单词上：
> ![截图_1](https://user-images.githubusercontent.com/23297439/37405939-de982592-278d-11e8-9316-41ae4aef8ad0.png)
> 
> ## 然后打开命令面板
> 然后打开命令面板
> ![截图_2](https://user-images.githubusercontent.com/23297439/37406017-12663fbc-278e-11e8-96c9-927630ca4f91.png)
> 
> ## 搜索：“开发人员：Inspect TM Scopes”
> 搜索：“开发人员：Inspect TM Scopes”
> ![截图_3](https://user-images.githubusercontent.com/23297439/37415638-cea1e55e-27a3-11e8-8c69-db03f49c3c4f.png)
> 
> ## 将会出现一个弹出窗口，其中包含有关范围的一些信息
> 将会出现一个弹出窗口，其中包含有关范围的一些信息
> ![截图_5](https://user-images.githubusercontent.com/23297439/37416074-cbf0448a-27a4-11e8-9673-165eab73961b.png)
> 
> ## 将突出显示的部分添加到上面提到的范围数组中
> 将突出显示的部分添加到上面提到的范围数组中
> ```js
> "editor.tokenColorCustomizations": {
>   "textMateRules": [
>     {
>       "scope": [
>          "meta.import variable.other.readwrite",
>          "other scopes ..."
>       ],
>       "settings": {
>         "fontStyle": ""
>       }
>     }
>   ]
> }
> ```
> 
> ## 最后你可以在 Twitter 上找到我：[@mohouyizme](https://twitter.com/mohouyizme)
> 最后你可以在 Twitter 上找到我：@mohouyizme
> ![动图](https://camo.githubusercontent.com/71f9b6c7dac4dedaab05394e745cc5253f3546da279441c79978dfff38862433/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f36484f6b44317053436e6534452f67697068792e676966) [ ![GIF](https://camo.githubusercontent.com/71f9b6c7dac4dedaab05394e745cc5253f3546da279441c79978dfff38862433/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f36484f6b44317053436e6534452f67697068792e676966) ](https://camo.githubusercontent.com/71f9b6c7dac4dedaab05394e745cc5253f3546da279441c79978dfff38862433/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f36484f6b44317053436e6534452f67697068792e676966) [ ](https://camo.githubusercontent.com/71f9b6c7dac4dedaab05394e745cc5253f3546da279441c79978dfff38862433/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f36484f6b44317053436e6534452f67697068792e676966)

<img width="835" alt="image" src="https://github.com/microsoft/vscode/assets/30615458/8fd45de2-fd89-4fba-82a0-dcf6969a9ec5">
sad...

**Comment by debemdeboas** [comment]
This should be considered a basic accessibility feature, not a nitpick by a few developers. Using @MariuzM's solution does improve the situation, but not entirely. And it is also less performant than overriding in a per-token basis.
Also this isn't just aimed at italics, but bold and underlines as well.

TLDR: There needs to be a way to globally enable/disable font styling à la the `"editor.fontWeight"` option. Themes could do this by themselves, leaving it up to the themes' maintainers to add an option for this (catppuccin does this pretty well: `"catppuccin.italicKeywords": false`); however, leaving it to the developers doesn't seem like the best option - and sometimes it's best to have a global option.

**Comment by FractalHQ** [comment]
Some themes seem to override all `textMateRules` scopes (even `*`).

Adding this setting (with the [apc-extension](https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension)) is the only way I've managed to disable italics (in comments) for _all_ themes:

```json
"apc.stylesheet": {
    ".mtk8": {
        "font-style": "normal !important",
    }
},
```

The `!important` overrides vscode's css for italics, and `.mtk8` is the classname used for comments.  To target other (non-comment) font, you can use the `Toggle Developer Tools` command to inspect the classnames of the areas you want to target.

The only downside is that it forces _all_ font-styles like `bold`  to be `normal`, as opposed to only `italic` font-styles.

**Comment by lost22git** [comment]
I just want to disable italic but reset styles

**Comment by hidekel-veltri** [comment]
It's August 2024, and I'm still waiting for this

**Comment by SammySnake-d** [comment]
Maybe you can try this configuration; I can use this configuration to turn italic.
```
 "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": [""],
        "settings": {
          "fontStyle": "italic"
        }
      }
    ]
  }
```
Need to change italic to ""

**Comment by xrunes** [comment]
This is 2025, I still wait for this feature after 8 years.

**Comment by CalsRanna** [comment]
> This is 2025, I still wait for this feature after 8 years.

yes indeed, also wondering why no progress on this feat.

**Comment by huanNguyen2204** [comment]
> Here is a simple way to find the scopes to add them to this list:
> 
> "editor.tokenColorCustomizations": {
>   "textMateRules": [
>     {
>       "scope": [
>          // Add scopes name to this array
>       ],
>       "settings": {
>         "fontStyle": ""
>       }
>     }
>   ]
> }
> ## First focus your mouse on the italic or bold word:
> ![screenshot_1](https://user-images.githubusercontent.com/23297439/37405939-de982592-278d-11e8-9316-41ae4aef8ad0.png)
> 
> ## Then open the Command Palette
> ![screenshot_2](https://user-images.githubusercontent.com/23297439/37406017-12663fbc-278e-11e8-96c9-927630ca4f91.png)
> 
> ## Search for: "Developer: Inspect TM Scopes"
> ![screenshot_3](https://user-images.githubusercontent.com/23297439/37415638-cea1e55e-27a3-11e8-8c69-db03f49c3c4f.png)
> 
> ## It will appear a popup contains some information about the scope
> ![screenshot_5](https://user-images.githubusercontent.com/23297439/37416074-cbf0448a-27a4-11e8-9673-165eab73961b.png)
> 
> ## Add the highlighted part to the scope array mentioned above
> "editor.tokenColorCustomizations": {
>   "textMateRules": [
>     {
>       "scope": [
>          "meta.import variable.other.readwrite",
>          "other scopes ..."
>       ],
>       "settings": {
>         "fontStyle": ""
>       }
>     }
>   ]
> }
> ## Finally you can find me on twitter: [@mohouyizme](https://twitter.com/mohouyizme)
> ![GIF](https://camo.githubusercontent.com/39e2ca4335ff61cfc1446b28596a0dce779f62e37e1235c434fde9881dd9a77e/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f36484f6b44317053436e6534452f67697068792e676966) [ ![GIF](https://camo.githubusercontent.com/39e2ca4335ff61cfc1446b28596a0dce779f62e37e1235c434fde9881dd9a77e/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f36484f6b44317053436e6534452f67697068792e676966) ](https://camo.githubusercontent.com/39e2ca4335ff61cfc1446b28596a0dce779f62e37e1235c434fde9881dd9a77e/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f36484f6b44317053436e6534452f67697068792e676966) [ ](https://camo.githubusercontent.com/39e2ca4335ff61cfc1446b28596a0dce779f62e37e1235c434fde9881dd9a77e/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f36484f6b44317053436e6534452f67697068792e676966)

You saved my vscode experience. Thank you <3
