### ISSUE TITLE
Portable version!

### ISSUE THREAD

**Issue by crper** [Microsoft/vscode#329]
You can provide a portable version of it? Or to support the configuration file or plug-sync to the cloud;
Otherwise, each computer must be installed once, configured once. . It is a waste of time;

Thank you

**Comment by joaomoreno** [comment]
There are portable versions of Code for every platform. Including [Windows](https://code.visualstudio.com/Docs/supporting/FAQ#_windows-trouble-with-the-installer).

**Comment by bpasero** [comment]
I dont think we are portable until we allow to specify the directory where data should go (including extensions). Reopening.

**Comment by weeblr** [comment]
Indeed. This is a requirement for people like me, switching from laptop to desktop very often: entire workflow is on an external ssd drive, not relying on local machine storage. As with other portable apps, basically all data pertaining to the app (code, config, any extension)should reside in a single folder, and use relative folders so that that folder can be moved around and app starts up and operate the same.
Thks.

**Comment by weeblr** [comment]
Another thing I noticed is that deleted items are moved to the Trash bin (on win 7). That's also not portable, as it means deleted items will be left on the current machine when moving to another one.

**Comment by bpasero** [comment]
Nice catch :)

**Comment by weeblr** [comment]
Thanks ;) Maybe you can have a look at #851. It's somehow related in that it deals where Code data is stored.

Cheers

**Comment by jrappen** [comment]
Problems reported above **still remain**, but here is a portable download for Windows:

* Win32 stable: [`https://code.visualstudio.com/docs?dv=winzip`](https://code.visualstudio.com/docs?dv=winzip)

**Comment by MarcoPeraza** [comment]
jrappen, any chance that the insider builds can be made available as a zip file as well? I tried this URL and got a 404: https://code.visualstudio.com/Docs/?dv=winzip&build=insiders

**Comment by joaomoreno** [comment]
There ya go: https://vscode-update.azurewebsites.net/latest/win32-archive/insider

**Comment by Tyriar** [comment]
FYI after https://github.com/Microsoft/vscode/issues/3068 you will be able to make vscode mostly portable by downloading the zip and using the `--user-data-dir` flag to specify a readable location. That sets the user configuration directory, however extensions will still look in the same spot.

**Comment by enjikaka** [comment]
Is there a way to get portable configs? In other words, get my badass conf'd VS Code at my work computer to my other computers without manually installing everything?

**Comment by Tyriar** [comment]
@enjikaka there are a few issues related to that:

- Create a portable 'extensions' file https://github.com/Microsoft/vscode/issues/4875
- Merge `.vscode` and `.config/Code` https://github.com/Microsoft/vscode/issues/3884
- Settings sync https://github.com/Microsoft/vscode/issues/2743

**Comment by bpasero** [comment]
@Tyriar I think we are good, the extensions location can be set via `extensionHomePath`

**Comment by RDeluxe** [comment]
Could somebody sum up all this in a readable fashion ? I downloaded the insider zip and tried to launch vs code with --user-data-dir without success (does not prompt anything)

This is a must have for such a lightweight editor (as ST, it's going to sit in my dropbox ;) )

**Comment by CNMan** [comment]
@RDeluxe have same issue

**Comment by Tyriar** [comment]
@bpasero do you know if `~/.cache/Code` is something we need to worry about for this?

**Comment by bpasero** [comment]
@Tyriar I am not sure who creates that folder, what are the contents?

**Comment by Tyriar** [comment]
@bpasero nothing for all variants on my machine. Failing to create the directory might be the reason it's not working currently though.

**Comment by gforcedev** [comment]
I created a batch file with contents `code --user-data-dir="data/" --extensionHomePath="extensions/" `. On launch:
* A data folder is created and populated, this part works fine.
* An extensions folder is created, but nothing appears within it. When I try and `ext install base16`, it doesn't actually load and throws an error when I press escape to get rid of the dialog

**Comment by jrappen** [comment]
Please also consider adding a portable 64bit version (compare #507).

**Comment by tommyshem** [comment]
I am a hobby programmer in python and go. I have been looking at this for a couple of days as it took me a day to install all the components on my computer and compile the original code. 
There are two files with environments settings, I have been using console.log() to output the filename paths. One environment gets changed but the other one does not. Not sure if this is the problem.
File location of the code.
vscode/src/vs/platform/environment/node/environmentService.ts
vscode/src/vs/code/electron-main/env.ts

Not sure why you have two similar files with almost the same code in it.

The --user-data-dir one works as far as I can tell.

This feature would be good as I would like to us it on a usb-stick for go and python.
I am happy to help with this feature, if you can give my some guidance.

**Comment by rlabrecque** [comment]
I want to have my VSCode install in my OneDrive, --user-data-dir is a great start but could we go one step further and change this so that we can run the exe directly without having to use shortcuts or batch?
https://github.com/Microsoft/vscode/blob/cd2cccfbde37ef218c0e98e4931137edd8e5f336/src/main.js#L125
to something like:
`var userData = args['user-data-dir'] || fs.existsSync(path.join(process.cwd(), '.vscode')) || paths.getDefaultUserDataPath(process.platform);`
(or `process.env['VSCODE_CWD']` instead of `process.cwd()`)

And then separately could --extensionHomePath first override a value in the userData config before falling back to the OS specific default?

I'd make a pull request but compiling and testing is non trivial for me currently.

**Comment by gforcedev** [comment]
That all looks good from what I can tell. Are you talking about a line in the userData config that specifies a path to store the extension home path in? If it worked, would there be a way to get a page on the docs about setting that up? Or even an option in the installer to install portable right from the get-go?

**Comment by rlabrecque** [comment]
Yep, exactly that!

I think the one step at a time approach is working well, but yeah eventually this stuff should be made more generally accessible.

Atom was going to do something similar but their autoupdater completely deletes their application folder,  not sure if that's something to be concerned about with VSCode though.

**Comment by gforcedev** [comment]
Hopefully it shouldn't be because the main thing we are looking for is a way to store extension files. From experience, my settings file has stayed between auto updates anyway. Would you like me to attempt to build your changes and test how they work?

**Comment by rlabrecque** [comment]
Go for it!

**Comment by nengxu** [comment]
I am new to VSCode, still mostly using Atom. Would like to see a portable 64bit version on windows. Or should we now use this one instead?

https://github.com/garethflowers/vscode-portable

**Comment by Tyriar** [comment]
@nengxu not sure exactly how it works but I would be concerned about running some exe file of which you're not sure how it was built.

**Comment by Tyriar** [comment]
Can anyone confirm whether there are any issues running this as portable when both `--extensionHomePath` and `--user-data-dir` set? If that's all there is to it, a new .zip/.tar.gz could be packaged which replaces the launch script or includes relative extension and user data paths some other way.

**Comment by rlabrecque** [comment]
I checked this out and the following issues remain:
Launching with: `"D:\Applications\Visual Studio Code\Code.exe" --user-data-dir "./.vscode/" --extensionHomePath "./.vscode/extensions/"`

Opening the extensions dialog causes an error `Marketplace returned 'ECONNREFUSED'. Please check the 'http.proxy' setting.`

Opening the user settings causes [settings.json](https://github.com/Microsoft/vscode/search?p=1&q=%22settings.json%22&type=Code&utf8=%E2%9C%93) to be created in an absolute path based on the drive root. In my case it was `D:\.vscode\User\settings.json` Expected: `D:\Applications\Visual Studio Code\.vscode\User\settings.json`

Those are the two big blockers for this. Once #3884 lands hopefully --extensionHomePath could just be removed?

And then my suggestion here for out of the box portability with a zip would be ideal:
https://github.com/Microsoft/vscode/issues/329#issuecomment-243744061
 1. Check for --user-data-dir
 2. Check for `./vscode/` relative to Code.exe
 3. Platform default location

Very specifically in that order.

**Comment by Tyriar** [comment]
@rlabrecque number 2 should only be an issue if you have another instance open. Since they share settings, closing all sessions and then opening with a `--user-data-dir` should work fine (just checked on Ubuntu 16.04).

I did notice that my normal extensions were being loaded in from the default directory with both of these:

```
code-insiders --user-data-dir ~/test-data-dir --extensionHomePath ~/test-extension-path .
code-insiders --user-data-dir ~/test-data-dir --extensionHomePath=~/test-extension-path .
```

@joaomoreno any ideas on that?

**Comment by joaomoreno** [comment]
It's a possible bug... #12129

**Comment by RDeluxe** [comment]
Where are we on this @Tyriar ?

**Comment by Tyriar** [comment]
@joaomoreno I'm pretty sure https://github.com/Microsoft/vscode/pull/15448 is the reason for setting both paths was failing.

@RDeluxe I believe the 2 big blockers that @rlabrecque called out are resolved in 1.8.0, you could try it in [Insiders](https://code.visualstudio.com/insiders) now by launching via the command line:

```
<path to bin/code-insiders> --user-data-dir <some path> --extensions-dir <some path>
```

**Comment by leoniDEV** [comment]
On Windows 10, using the zipped package of Code 1.8.0 extracted on a USB drive, the user data are loaded as expected from the folder specified with `--user-data-dir`, but the extensions are installed in the default location `%HOMEPATH%\.vscode-insiders\exstensions` ignoring `--extensions-dir`.

**Comment by CNMan** [comment]
@leoniDEV 
try --extensionHomePath=<some path>

**Comment by Tyriar** [comment]
@joaomoreno is there an issue with `--extensions-dir` on insiders?

**Comment by maybeec** [comment]
Neither --extensions-dir nor --extensionHomePath seem to bring a result.
Installing new extensions will not be stored in the configured folder and previously installed extensions in the global folder are shown after startup although they should not as I switched the extensions-dir by the parameter.

**Comment by joaomoreno** [comment]
This is strange. I just ran `code-insiders --user-data-dir userdatadir --extensions-dir extensions` on a fresh build from today and everything worked.

Note that this only works if Code is completely shutdown. This will **not** work for independent windows.

**Comment by maybeec** [comment]
I have gone back to vscode stable. As I recognized, that `--extensionHomePath` already did the job quite well. However, your hint was very good. Is there any parameter to force an isolated start of a new window? I could not find any.

**Comment by joaomoreno** [comment]
There isn't, Code always runs as a singleton.

**Comment by mchels** [comment]
In case this is of use to anybody:
I've hardcoded the command line arguments `user-data-dir` and `extensions-dir` in this commit https://github.com/mchels/vscode/commit/b82fac04ae266145fd8fb058c85db4d697b254eb so that the `extensions` and user-data folders are in the same directory as the Code.exe (or Code - OSS.exe) executable. I've tested it for a few hours and so far it seems to work as expected.

**Comment by jrappen** [comment]
Any updates?

/cc @joaomoreno @bpasero @Tyriar

**Comment by Tyriar** [comment]
@jrappen we're waiting for confirmation that a command like this works fine for everyone's needs:

```
code-insiders --user-data-dir userdatadir --extensions-dir extensions
```

Once we know everything is covered maybe we could distribute a zip for Windows which hardcodes those directories to be relative?

**Comment by jrappen** [comment]
@Tyriar Please also note @weeblr 's comment above about deleted items being moved to the trash, which shouldn't be happening.

**Comment by Tyriar** [comment]
@jrappen I'm not sure I agree that trash should be skipped in a portable install, you're still working with files on that computer. Unless it throws an exception without write access?

Portable to me means it should not need to be "installed" and works from a USB and/or without write access to other parts of the computer, it's not an incognito mode?

**Comment by eyalsk** [comment]
@jrappen It should be a separate feature and an opt-in feature regardless to whether it's portable; otherwise, it might confuse people, they may delete files thinking it will move to trash but it won't.

**Comment by rlabrecque** [comment]
@eyalsk Agreed, not trashing files would be surprising to me. But that feature may be welcome in both portable and non portable mode. I would never use it on my portable version because I only ever would use it on private computers.

**Comment by Tyriar** [comment]
Note that shift+delete works in the explorer to skip trash.

**Comment by ErBlack** [comment]
https://github.com/garethflowers/vscode-portable

**Comment by nengxu** [comment]
@ErBlack Thank you for the link!

**Comment by guilhermeoc97** [comment]
`code.exe --user-data-dir "userdata" --extensions-dir "ext"` is working just fine for me, on the latest stable build. I don't know about the insiders one. The only catch here is that it still creates a `.vscode` directory on the current user's directory, but it doesn't place any files in it.

Also, is this still being worked on or it has been solved? @Tyrian @bpasero @joaomoreno

**Comment by bpasero** [comment]
Not solved, we still need to make our code fit for paths that are provided by the user. For example you cannot change the user data home location as far as I know (~ on macOS and Linux).

**Comment by Tyriar** [comment]
@bpasero I was thinking all we really needed to get this done was to do another package type that has default args something like this:

```
code --user-data-dir <code's_path>/userData --extensions-dir <code's_path>/extensions
```

That was everything is contained within the path vscode is running out of.

**Comment by bpasero** [comment]
@Tyriar you are missing this:

![image](https://cloud.githubusercontent.com/assets/900690/23738041/ea196a36-0496-11e7-86f9-36addebf8c14.png)

**Comment by Tyriar** [comment]
@bpasero `userHome` seems to be used only to 'tildify' paths so that shouldn't change, regardless of whether it's portable `~` should still mean `$HOME`.

On the `userProductHome`, it appears to be used only for the extensions dir so why don't we just remove the path creation call for that and rely on the `mkdirp` on `environmentService.extensionsPath` working?

**Comment by bpasero** [comment]
Only because people are not using the environment service as they should, there is more:

![image](https://cloud.githubusercontent.com/assets/900690/23762078/3de34f3e-04f5-11e7-851c-774facf6fcfd.png)

**Comment by Tyriar** [comment]
@bpasero comments on each instance:

- commands.ts: Good as it's specifying the default for an input box
- git.ts: Good as it's trying to fetch the default git template
- path.ts: Good as it's getting the default app data paths used by the env service (overridden by `--user-dara-dir`)
- environmentService.ts: Not sure about the `profileStartup`, it kind of still makes sense that it would put the in `$HOME` imo
- cli.contribution.ts: Good as it's fetching shell config files
- git.lib.ts: Good, same as git.ts
- terminalInstance.ts: Good as it's getting the default terminal cwd

They could point at `IEnvironmentService` but I don't think the home path should change based on whether it's portable.

**Comment by bpasero** [comment]
@Tyriar awesome, looks like we are not far away after all. I disagree about profileStartup though, we cannot write to os.homeDir() when you run portable. 

The other question is if writing to the OS tmp dir is OK when you run portable. Imho running portable means to not leave ANY traces on the OS disk.

**Comment by Tyriar** [comment]
> Imho running portable means to not leave ANY traces on the OS disk.

@bpasero I feel this is true but only for cache/settings/etc. Using a portable version of VS Code on a USB drive should have the instance of VS Code work the same across machines. `profileStartup` however is an explicit action to generate a performance profile, it's not editor cache information but a file that the user wanted to generate. Putting the profile on the USB drive under the install folder kind of indicates to me that this is app data, don't delete it.

As I mentioned earlier in https://github.com/Microsoft/vscode/issues/329#issuecomment-272530574 about skipping trash, we're not trying to implement some incognito/private mode imo. It's just about the *portability* of the install, we can still create files on the system like trash, new/saved files, performance profiles, etc., we will just need to be more wary of write permissions issues.

**Comment by bpasero** [comment]
I think we have to see the definition of how portable apps should behave before we declare VS Code portable (e.g. http://portableapps.com/about/what_is_a_portable_app#guidelines)

**Comment by Tyriar** [comment]
@bpasero note that's the definition for the PortableApps.com platform (we're not bound to that or anything). I don't think the `profileStartup` thing is a big deal either way.

I was just thinking that ATA in the typescript extension will dump its cache in `~/.cache/typescript/`, we may want to expose a cache directory on the environment service with a CLI arg so `~/.cache/typescript` and `~/.cache/Code` are put in the install dir. /cc @mjbvz 

Not sure if we use the `Code` cache directory for anything, `$XDG_CACHE_HOME/<appname>` may be created by Electron.

**Comment by bpasero** [comment]
@Tyriar well this actually opens the question to what we do with extensions? Any extension today assumes it runs on a real disk and can write anywhere, there is no context provided that tells an extension it runs portable. So yeah, providing a directory for extensions to write data is probably needed.

**Comment by weeblr** [comment]
Hi

> The other question is if writing to the OS tmp dir is OK when you run portable. Imho running portable means to not leave ANY traces on the OS disk.

> t's just about the portability of the install, we can still create files on the system like trash, new/saved files, performance profiles, etc., we will just need to be more wary of write permissions issues.

For me, as a user, the goal is that:

- I can work on my laptop
- shut down VS Code
- unplug the USB stick (which in reality is of course an SSD drive!)
- plug it back in my desktop or any other machine
- fire VSCode and bet back exactly where I left

I have been doing that for a weeks now, with the current implementation, using:

` --user-data-dir="V:\xxxxx\vscode\data" --extensions-dir="V:\xxxx\vscode\extensions"`

and that seems to work fine. I only use VSCode for "light" editing so I may not have hit issues occuring when VSCode is used more intensively, but the approach would be the same.

In other words, if switching machines requires that the typescript cache mentioned by @Tyriar be rebuilt from scratch - and that can be a costly operation, then it should probably be stored in the --user-data-dir folder (or maybe another --user--data-cache or --user-data-tmp?)

In addition, I see no benefit in storing this cache in the user dir?

Rgds

**Comment by Tyriar** [comment]
@weeblr it will need to be rebuilt but it doesn't download a big chunk at once, it will download npm `@types` modules based on what you type to attempt to give clever intellisense. My `~/.cache/typescript` appears to be 8.1mb with about 200 modules cached (including lodash which is 2.9mb by itself).

One benefit of keeping it on the USB is if you jump between online and offline machines the automatic type acquisition cache will follow the machine (provided npm is installed locally).

**Comment by weeblr** [comment]
@Tyriar I don't really judge whether that's OK or not. Obviously, it "feels" better to not redo something that has been done already, and if you think about going the other way around (leaving the office, ie switching from desktop to laptop, there might actually be no internet access at all, as you hinted).

> provided npm is installed locally

In such a scenario, at least in my case, npm - and node, git, php,apache,mysql, python, firefox, Intelij IDEA and everything else, I found only Chrome (and docker obviously) cannot be used that way - is installed on the USB stick. All of it moves along, there is no reason to install something on the machine itself.

Again (and aside from you having to write some code ;) ), is there any benefit in NOT making this data portable?

Rgds

**Comment by eyalsk** [comment]
@Tyriar 

> It's just about the portability of the install, we can still create files on the system like trash, new/saved files, performance profiles, etc., we will just need to be more wary of write permissions issues.

This will make many people sad.

You can't decide for yourself what portability means, it's not exactly a scientific fact but when people think portable they think that the application wouldn't depend on anything outside to its directory.

Whether a file is moved to the trash after is deleted is controlled by the operating system and this behaviour can be toggled by the user, on most platforms the deletion API don't give you the ability to control this behaviour so when an application deletes a file by a request, it shouldn't care whether the file was moved to the trash or not so that's completely fine from portability standpoint. 

However, depending on a system directory such the temp folder wouldn't make sense for a portable application, everything needs to live inside the portable directory.

**Comment by weeblr** [comment]
> However, depending on a system directory such the temp folder wouldn't make sense for a portable application, everything needs to live inside the portable directory.

Actually, I think it doesn't really have to be **in** the portable directory, if you fear this will "pollute" it with too many folders. The key point is that those folders should be settable through command-line options, so that user wanting a portable installation can use it that way

Something like:
/projects
             /project_1
             /project_2
/apps/vscode
                     /code  (the actual VSCode code directory)
                     /tmp
                     /cache
                    
I think you do not have to provide the folders layout, just make it settable by user.

Rgds

**Comment by guilhermeoc97** [comment]
We could look at how another IDE -- Netbeans -- makes itself portable:

 * It needs a cache dir, where it stores cache and temporary files, and it can be set to anywhere you want;
 * It needs a data dir, where it stores configuration and extensions, and it can also be set to anywhere you want;
 * So, if you want to make Netbeans truly portable, just point the cache dir and the data dir to your USB stick / drive / network share, and you're all set;
 * Deleted files, afaik, are not moved to the trash, they're deleted permanently. But as we defined previously, it's not a problem to use the working computer's trash folder, so we could do that instead;
 * Finally, Netbeans only writes to the project directories and the directories (cache/data) that were previously specified. It doesn't write anywhere else.

For me, that works wonders, and VS Code today only does 3 of those items -- 1, 2 and 3 -- as far as I have used it. It works, but not as the user might want.
So, just let the user do what it wants -- just don't let him do something that will break the program.

________________________________________
De: Weeblr [notifications@github.com]
Enviado: sexta-feira, 10 de março de 2017 08:13
Para: Microsoft/vscode
Cc: guilhermeoc97; Manual
Assunto: Re: [Microsoft/vscode] Portable version! (#329)

However, depending on a system directory such the temp folder wouldn't make sense for a portable application, everything needs to live inside the portable directory.

Actually, I think it doesn't really have to be in the portable directory, if you fear this will "pollute" it with too many folders. The key point is that those folders should be settable through command-line options, so that user wanting a portable installation can use it that way

Something like:
/projects
/project_1
/project_2
/apps/vscode
/code (the actual VSCode code directory)
/tmp
/cache

I think you do not have to provide the folders layout, just make it settable by user.

Rgds

**Comment by eyalsk** [comment]
@weeblr By default I'd argue that everything must live inside the portable directory, adding options to control the defaults should be considered separately.

**Comment by weeblr** [comment]
@eyalsk 

> @weeblr By default I'd argue that everything must live inside the portable directory, adding options to control the defaults should be considered separately.

Well, let's not forget that most people will not use a portable version. I still think the default should be to write to the local $HOME and such folders and the "portable mode" should be activated on purpose by users requiring it.

If you do not write to $HOME by default, then you loose the "opposite" feature, which is to share a single computer amongst multiple users.

Now you could then say : we only need one single CLI argument --portable-mode, which would cause VSCode to be self-sufficient, exactly as @guilhermeoc97 described NetBeans or Eclipse can be.

We do already have --user-data-dir and --user-extensions-dir, so I really have no opinion there, it's about what's more simple to get this out of the door I guess?

**Comment by guilhermeoc97** [comment]
Those were exactly my thoughts: It defaults to the working computer's home dir but it can be switched via a single (or multiple) command-line switch(es). We can have a `--portable` switch or a switch for every setting, like `--cache-dir`, `--ext-dir`, `--conf-dir`, and so on.

The only possible problem would be that those are command-line switches: you lose the shortcut or batch file and then you need to do everything again.

________________________________

**Comment by Tyriar** [comment]
Trying to understand everyone.. I think there appear to be two main use cases surfacing, correct me if I'm wrong:

**1: Avoid installing on OS**

This use case is mainly about not installing on the OS, this is my main use of portable apps where I don't want them to touch the registry on Windows or don't want their post install scripts messing with my setup on Linux. This enables someone to have a single VS Code install located on a USB drive or synced via cloud storage (theoretically :wink:). Work is still expected to happen frequently on other drives.

It would make sense to make `$HOME` (`%HOMEDRIVE%/%HOMEPATH%` on Windows) the "default" folder here, for example opening a file in an empty workspace would default here.

**2: All work is done within a USB drive**

This use case seems to be about doing all development from within a USB drive and not touching the outside world under any circumstances.

Here opening a file in an empty workspace would make most sense to default at VS Code's install dir (or its parent, or the install drive root).

---

Am I accurately describing your use case as option 2 @eyalsk @guilhermeoc97

**Comment by weeblr** [comment]
> The only possible problem would be that those are command-line switches: you lose the shortcut or batch file and then you need to do everything again.

I believe this is quite OK, because only well-informed users will probably use this. Also, I have "lost" such setting a couple of times over the years, and it should basically not be an issue: VSCode starts without the expected data and extensions and settings. But then you shut it down and restart it with the appropriate settings, no damage done.

**Comment by eyalsk** [comment]
@weeblr 

>  it's about what's more simple to get this out of the door I guess?

If it's simple and worthless then getting it out of the door wouldn't make sense, I'd say that the portable mode a) needs to be self-contained first and then b) gradually allow people to configure directories if they want it, if it's possible to do both at the same time then that's fine with me but the former should be done as first priority.

To me portability means two things 1) Configuration files are read from and written into the application's dir 2) Zero system dependencies; relying on one of the system directories such as the temp dir is a dependency in my world.

**Comment by weeblr** [comment]
@Tyriar The line is pretty thin betweent those 2 "use case" I believe, because to achieve #1 you basically need #2,. So #1 "comes free" if you have #2.

If talking about #2, which is my use case, but in which I totally appreciate that nothing is written to the Windows registry, I would always want to be able to set the defautl data-dir to one on my USB drive (but we can already do that with --user-data-dir). If missing, indeed defaulting to the install folder is fine

**Comment by RDeluxe** [comment]
I think case 1 is the most comming @Tyriar . I'm actually using most of my app this way now ; PHPStorm, VSCode, ShareX, Cmder, Sublime Text, Android Studio, etc. are sitting in my Dropbox. I'm switching from my laptop to my desktop in total transparency. If I open a file not present in the software path, most software just tells me the file does not exist.

I would rather have a config file (json or whatever) to set the app Home path, Extension path, Cache path (like in PHPStorm) instead of just .exe arguments/options.

Note ; In my case the windows user is the same on both machines. That means that if I open a file stored in dropbox with PHPStorm, it won't have any trouble finding it on the other machine.

**Comment by eyalsk** [comment]
@Tyriar Yes, given that configuration files are stored as part of the application's dir in both cases. :)

**Comment by weeblr** [comment]
@eyalsk 

> If it's simple and worthless then getting it out of the door wouldn't make sense, I'd say that the portable mode a) needs to be self-contained first and then b) gradually allow people to configure directories if they want it, if it's possible to do both at the same time then that's fine with me but the former should be done as first priority.

That's not really what I think we were discussing. The main point is that the non-portable mode should be the default. Then if one enables the portable mode, I think we can agree that:

- the project dir is not going to be inside VSCode install folder (so it must be configurable)
- cache, tmp and extension, I don't care, they just have to be moving along

@RDeluxe 
> I would rather have a config file (json or whatever) to set the app Home path, Extension path, Cache path (like in PHPStorm) instead of just .exe arguments/options.

Indeed, this is nice. It solves the "lost shortcuts" issue mentioned above. It's just a bit more complex in case of updates (as in IDEA), when the file format is changed or a parameter is added, then you have a conflict between the update and the local file. IDEA prompts you when this happens, asking if you want to keep the old file or override it with the new one

**Comment by eyalsk** [comment]
@weeblr 

> That's not really what I think we were discussing. The main point is that the non-portable mode should be the default. Then if one enables the portable mode, I think we can agree that:

You probably misread or I worded it poorly but when I wrote _default_ or _defaults_ in my previous posts I wasn't referring to the mode of VSCode as in portable vs non-portable but to the location of the files that are stored by VSCode in portable mode.

_Just to state the obvious here but I definitely agree and think that when you download the _setup_ binaries of VSCode the default should be non-portable whereas when you download the portable binaries of VSCode the default should be portable._

**Comment by weeblr** [comment]
> You probably misread or I worded it poorly but when I wrote default or defaults in my previous posts I wasn't referring to the mode of VSCode as in portable vs non-portable but to the location of the files that are stored by VSCode in portable mode.

Indeed, I understood that you really meant "default".

**Comment by petersladek** [comment]
In windows setup docs there is a note saying you need to manually update VS Code for each release if installed via zip file (I assume this zip would be the true portable version in future). Is that really true? Portable version should be able to auto update itself too.

**Comment by xttn** [comment]
Hi, any news for portable version??

**Comment by Telokis** [comment]
@xttn `code.exe --user-data-dir "userdata" --extensions-dir "ext"` works fine for me.
What is the matter?

**Comment by xttn** [comment]
@Telokis `"I:\DEV\Microsoft VS Code\Code.exe"  --user-data-dir "userdata" --extensions-dir "ext"`
Like this? I will try :+1:

**Comment by xttn** [comment]
When new updates are available, I can not select the install folder for VScode....

**Comment by Telokis** [comment]
@xttn Just download the portable version.

**Comment by jrappen** [comment]
@Telokis This issue has not been resolved and you are missing several points, compare the thread above which contains the following:

* auto-update
* preconfigured portable vscode
* check for `--user-data-dir`,  `--extensionHomePath` and `.vscode/` relative to `Code.exe`
* ability to disable "delete > move to trash on local machine"
* related issues which are currently still open:
  * #507 (64bit)
  * #851 (custom workspace settings)
  * #2743 (sync)
  * #3884 (folder structure)

**Comment by Telokis** [comment]
@jrappen I don't really know what you are talking about but I use VSCode as a portable software everyday and it works absolutely 100% fine, I have not had a single issue.

**Comment by rlabrecque** [comment]
Portable means different things to different people, there's no set standard.

For example, I only use portable apps across a number of my own different machines that are all configured identically. So I don't care about things like moving to trash happening since I own the machine. If I were using this on a thumb drive in an external environment then I might prefer deleting directly instead as jrappen seems to.

Auto update is the big thing missing for me, Once the folder structure update happens hopefully that will be easier.

**Comment by bahatron** [comment]
+1 

I want to be able to install vscode on OneDrive and keep it synced between all my devices (laptop, PC and work PC)

So far i've made it by creating a symlink between a OneDrive folder and the actual AppData/Roaming/Code folder. I believe if the Code folder is simply moved from AppData/Roaming/Code to vscode installation folder it should work fine

**Comment by mguptawork** [comment]
@bahatron I believe this issue and https://github.com/Microsoft/vscode/issues/22557 can be solved by the same fix.

**Comment by RoyiAvital** [comment]
I would like a portable version with the following properties:

1. All configuration files and data are within the program folder.
2. No registry keys are created or used.
3. No need for any special privileges to run.
4. Doesn't send telemetry data by default.
5. Doesn't have Auto Update process by default.

Any way to achieve this currently?

A dream would be to have it in a PortableApps form.

**Comment by copdips** [comment]
By using the extension "Settings Sync", all the settings I needed are synced for both installable and zip versions.
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

It Syncs : 
All the extensions and complete User Folder that Contains
1. Settings File
2. Keybinding File
3. Launch File
4. Snippets Folder
5. VSCode Extensions Settings
6. Workspaces

**Comment by copdips** [comment]
If you have Internet, by using the extension "Settings Sync", all the settings I needed are synced for both installable and zip versions.
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

It Syncs : 
All the extensions and complete User Folder that Contains
1. Settings File
2. Keybinding File
3. Launch File
4. Snippets Folder
5. VSCode Extensions Settings
6. Workspaces

**Comment by RoyiAvital** [comment]
@copdips , This is exactly the opposite approach.

I want a program with minimal effect on the OS it is running on.
You suggest to add another program to give this program more real estate on the OS.

Windows get slower and slower and slower as more and more programs are installed.
The solution is having them in Portable Mode.

**Comment by eyalsk** [comment]
@RoyiAvital While I agree with you on that:

> I want a program with minimal effect on the OS it is running on.

However, the following statement is incorrect to say the least:

> Windows get slower and slower and slower as more and more programs are installed.

The amount of installed programs has zero impact on the OS in terms of performance, however, the amount of running programs and the kind of work you do has impact on the CPU that may make any OS slower not just Windows.

Your statement might have been correct when programs running on older version of Windows touched the registry but even then in my experience it was mostly due to programs working on the background and the kind of CPU that back then couldn't kept up with it not so much Windows itself.

> The solution is having them in Portable Mode.

Some programs have many dependencies that when uninstalled aren't uninstalled fully and sometimes can fail during the process so having portable version in this case is preferable, still, this might not be the case for VSCode, maybe one of them though.

The reason to have a portable version for VSCode is so we would have everything ready to go without having to setup anything and be a copy operation away from using it.

It might also be useful in cases where you want to compare two or more versions of it.

**Comment by RoyiAvital** [comment]
@eyalsk ,
I will refer you to [What causes Windows to slow down over time?](https://www.quora.com/What-causes-Windows-to-slow-down-over-time) on Quora.

Moreover, it is from my own experience.
My current installation of Windows is almost 2 years old and runs like new one as I haven't installed a single application (All of them are portable).
Back in the days Windows just got slower (More registry entries more processes running in the background, etc... from installed programs).

But really, it doesn't matter, anyone has its own reasons for Portable Application and each one is as good as the other.

The important thing is to have a Portable version of VS Code with footprint on the system.

**Comment by thegreatestminer** [comment]
so... uhhhh,

are we going anywhere with this? has there been progress in making vscode completely portable? :/

**Comment by RoyiAvital** [comment]
Someone put Profile Synchronization as an alternative to Portable Mode.

I really hope others see it differently.
We need Portable mode for many use cases not only being able to move from one computer to another.

**Comment by Telokis** [comment]
In my opinion, VSCode is already portable.
I have it on a usb drive and it works perfectly with some command line arguments.
I don't even understand why this issue is still open.

**Comment by RoyiAvital** [comment]
@Telokis ,

When we say portable it means it leaves nothing behind unless it is in the same folder of the program itself.
Namely:

1. No registry entries.
2. No data in APPDATA folder.
3. No data in USERPROFILE folder.
4. No administrator privileges.

Can you get it all now?
When you install Plug In's do they obey the above?

**Comment by Telokis** [comment]
What I did was installing it normally on my own pc. (Non portable way)
And then copying it over to my usb to access it on a very restricted computer.
There are two command line options to specify the extensions and user directories. I just used those to be in the same directory as the .exe.
That way, I am sure that nothing is left anywhere on that machine.

**Comment by RoyiAvital** [comment]
Could you share how you do it?

Have you checked other folders on the computers?
Can the installation process be in Portable Mode (Namely doesn't create any traces in other places?)?

**Comment by Telokis** [comment]
No, to be fair, I never checked appdata or any other directory on the computer I use the usb drive with.

Actually, as I told you, I simply installed VSCode normally on a computer I don't mind having its registry keys or directories touched.
Then I copied the directory "Microsoft VS Code" onto my usb drive and made a `run.bat` with something like `code.exe --user-data-dir "userdata" --extensions-dir "ext"`.
As you can see, `userdata` and `ext` are relative to the `code.exe` file so I'll have everything store in that directory.
One drawback to that solution is that, for each new update, I have to copy the files from my first computer again. It won't update on the usb drive. (Don't know why)

I'm sure this solution won't be perfect for everyone but I think it is better than nothing and it perfectly suits what I expect from a "portable" app.

**Comment by RoyiAvital** [comment]
You see, you have issues as well.
We would like to have an official portable out of the box experience.

Why would you go against it if you use it by yourself and experience some issues with it (Updates)?

**Comment by Telokis** [comment]
I'm not against it but I didn't understand, at first, what people were clearly requesting here.
I totally agree that there should be some official support for this but I also think that there is a little workaround (not ideal) available while we wait for someone to do it!

**Comment by jlanza** [comment]
I have used:
Code.exe --user-data-dir "userdata" --extensions-dir "extensions"

and it seems to work. However when I pin a shortcut to the taskbar it always create a new icon. Is there any way to make it possible to use the pinned icon?

**Comment by zmni** [comment]
@Tyriar on https://github.com/Microsoft/vscode/issues/329#issuecomment-271944991. It should relative to Code application folder (where Code.exe exist).

Right now (`v1.15.1 x64`), when you launch Code with that parameters from registry (Open with Code context menu) and with cli (`code.cmd`), the parameters is relative to the file you open with it. For example, Code is in `X:\Code` and you open file `D:\somefile.txt`, Code create userdatadir & extensions folder in `D:\` (`D:\userdatadir` & `D:\extensions`), that is not right. Code should always create/use userdatadir and extensions in/from Code's own directory (`X:\Code\userdatadir` & `X:\Code\extensions`).

ST does this correctly, from wherever you launch it, via cli, context menu or the application, it always create/read/write data to/from it's own directory, never leave anything anywhere.

**Comment by jlanza** [comment]
I have decided to put the full path when using userdatadir and extensions. This way it seems it is working and nothing in created when opening a file (previously created userdata and extensions folder) or when using the open folder (previously .vcode folder was created).

**Comment by bardware** [comment]
> Is there any way to make it possible to use the pinned icon?

In Explorer browse to `%APPDATA%\Microsoft\Windows\Start Menu\Programs`. There are the link files for the Start Menu

**Comment by bardware** [comment]
What is the difference between `--extensionHomePath` and `--extensions-dir`?

**Comment by AbhishekTripathi** [comment]
I dislike the approach of using command line switches. The application can be opened in multiple ways. It could be a *desktop icon*, a *pinned icon* in the taskbar, *default file association* or file/directory being sent to VSCode via *Send to* option. Now, what is the easiest way to ensure all such invocation always lead to the execution of binary in the state that it respects local installation path as the root for extension and profile data? In my case, I have it in my dropbox with a shortcut ensuring the proper switch is set pointing the root installation as the desired repository of profile and extension data. I see that my %appdata% is polluted when I double click the file to launch vscode. There should be an **elegant** way to ensure _irrespective of invocation source, the binary respects portability_.

**Comment by jsieler** [comment]
I had same problem with VSCode not being fully portable. Of course, you can run it with command line parameters, but I'm using it as WinSCP editor and with other apps with editor integration as well, and not all of them support command line parameters. So, the my only solution was to create a wrapper for it. This is a small .exe file which allows you to run VSCode fully portable from USB-Stick or where ever you need it. Feel free to use, contribute and share 👍  (source and binary release included)

https://github.com/jsieler/vscode-portable/

**Comment by RoyiAvital** [comment]
@jsieler , Why not use the @PortableApps framework?

**Comment by jsieler** [comment]
@RoyiAvital ofc you can do. I didn't said that. I've just shared my code :)

**Comment by RoyiAvital** [comment]
Well, I wish I knew.
I just offered to redirect your efforts in that direction.
You know, reduce your efforts.

**Comment by Tragen** [comment]
Like AbhishekTripathi said, there should be a config file for default command line parameters or settings.

**Comment by gjguo** [comment]
Maybe this one? It is packaged with a PortableApps.com launcher as a portable app.
[Portable version of the Visual Studio Code editor](https://github.com/garethflowers/vscode-portable)

**Comment by jsieler** [comment]
And eventually with miner inside. Have fun using it.

28 февр. 2018 г. 2:42 пользователь "gjguo" <notifications@github.com>
написал:

**Comment by bardware** [comment]
I start code like `code --extensions-dir "C:\vscode\php\exts" --user-data-dir "C:\vscode\php\data"` to start an instance with PHP specific plugins.
Now code wanted to install an update, requested windows administrator password and restarted.
The restarted instance did not use the extensions-dir and user-data-dir I originally started code with.

**Comment by ugurkoysuren** [comment]
--extensionHomePath "C:\Project\extension" as launch options works in windows 10, **but I don't like this solution.** Since the application can be opened in _multiple_ ways. You might use a desktop icon, a pinned icon in the taskbar etc.

**Comment by jsieler** [comment]
@ugurkoysuren that is why people are looking for much more "portable way" usage of VSCode. The only possibilities are for right now:
1. Creating link (desktop or whatever you want) with parameters
2. Creating .bat file
3. Using some wrapper app like one i've made

**Comment by fbehrens** [comment]
Hi, I just want to report here as I am forced to work under different profiles on `windows` it was suffering from the lack of a portable version. Only after some time I took the time to find out about the `user` and `extensions` directory, and come up with the quite simple solution to copy and then modify the existing `.\bin\code.cmd` wrapper by adding the `--user-data-dir` and  `--extension-dir` parameters. 
```
call "c:\tools\vscode\app\Code.exe" "c:\tools\vscode\app\resources\app\out\cli.js" "--user-data-dir" "c:\tools\vscode\user" "--extension-dir" "c:\tools\vscode\ext" %*
```
The solution is quite simple, but it took me some time and hazzle. 

The portable version should integrate this functionality out-of-the box in some way, to make VSCode more approachable. Thanks and appreciation for this great editor

**Comment by bardware** [comment]
I tried a bit differently today. I called `code . --extensions-dir "C:\vscode\php\exts" --user-data-dir "C:\vscode\php\data" --new-window`.
Two instances of code were started. I saw this behaviour before, when I called `code .`, therefore the additional argument `--new-window`. It seems it is not respected when --extensions-dir and --user-data-dir are provided.

**Comment by stkb** [comment]
Maybe we could agree on a spec that might eventually lead to a PR. Other programs check on startup for the presence of settings files/dirs next to the executable, and if they exist, use those instead of AppData/whatever.

So I'd propose: if a folder `extensions` exists next to `code.exe`, use it for the extensions dir. If a folder `data` exists, use it for the user data.

Or an alternative: just check for a `data` folder and if it exists, store user data there and extensions in an `/extensions` subfolder under that.

Note this is Windows-specific. It's also a little different from I think the portable-apps way of having separate `/app` and `/data` dirs, but I'm not sure that would work.

Thirdly I don't know how this would work with updates. Does the update process blow the whole vscode directory away? Does it touch the files in the userdata folder?

Relevant:
- https://github.com/Microsoft/vscode/pull/828
- https://github.com/Microsoft/vscode/pull/26849

**Comment by notrealdev** [comment]
Three years have passed and MS has not yet supported portable version for VSC lol

**Comment by hellboy81** [comment]
The same issue

**Comment by vanja-san** [comment]
> I do not know all paths where folders are created after VSCode starts, if you know, tell me, I'll check. But these two ways no longer appear in the system (_Extensions_ and _Data_)! Sorry for my English!

At me like works.
I took a variant from above: `--user-data-dir` and `--extension-dir`.
- Downloaded VSCode. Not installer, but archive.
- Unpacked where necessary.
- Created a shortcut from Code.exe.
- In properties of shortcut, added: 
_"C:\Portable Soft\VSCode\Code.exe" --extensions-dir "C:\Portable Soft\VSCode\extensions" --user-data-dir "C:\Portable Soft\VSCode\data"_
![2018-04-28-19-00-03](https://user-images.githubusercontent.com/7201687/39396326-6443e798-4b16-11e8-9677-4f6acb735174.png)

It seems everything works! 
Extensions are also installed in a folder where I indicated.

![2018-04-28-19-04-05_li](https://user-images.githubusercontent.com/7201687/39396513-bd0856cc-4b19-11e8-9717-74210dc92f11.jpg)
-----
![2018-04-28-19-04-46_li](https://user-images.githubusercontent.com/7201687/39396518-c5fd25d2-4b19-11e8-9e75-cd0895ad73dc.jpg)
-----
![2018-04-28-19-05-08_li](https://user-images.githubusercontent.com/7201687/39396520-cf27c2d4-4b19-11e8-86be-94ec8f4f52c3.jpg)

**Comment by rlabrecque** [comment]
I believe as per some of the above comments, there are a couple cases where it still will end up dumping files in AppData with that setup.

**Comment by Ianfinn1994** [comment]
Would there be a way to address this on a Mac?

**Comment by joaomoreno** [comment]
Portable mode is on its way to Insiders with https://github.com/Microsoft/vscode/commit/e43ab4e4c4f69d841dc06bfc15dee69e56344137

Early docs: https://github.com/Microsoft/vscode-docs/blob/vnext/docs/editor/portable.md

**Comment by Ianfinn1994** [comment]
How can I get it working

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AbhishekTripathi** [comment]
Excellent. So now there will be true portability in VSCode. Which stable channel release/version is expected to carry these bits?

**Comment by joaomoreno** [comment]
It will come out in 1.25 (June's release).

**Comment by IzakMarais** [comment]
Is there documentation somewhere for migrating my existing installation to Portable Mode? I assume I would need to copy the contents of some folders and paste them into the new install path somewhere... 

I looked [in the docs](https://code.visualstudio.com/docs/editor/portable) but found nothing. 
I am on Windows.

**Comment by jlanza** [comment]
My guess is copy the extensions and user-data folders to the new data folder.

**Comment by schlamar** [comment]
My instructions in #53653 should work.
