### ISSUE TITLE
Emmet suggests snippets, by searching snippet's values

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#32911]
- VSCode Version: 1.15.1
- OS Version: win7x64

Just trying to type "**overflow: auto;**", but instead of it I get "**overflow: align-self: auto;**"
Emmet suggests snippets, by searching snippet's values, like "auto;"? Not good :)

GIF:
![emmet - overflow-auto](https://user-images.githubusercontent.com/24613274/29541798-1d10ed22-86df-11e7-9325-a254aad9b727.gif)

**Comment by ramya-rao-a** [comment]
Yes Emmet does seem to think that `auto` best expands to `align-self:auto;`
That happens upstream though.

The problem we can fix is that emmet completions shouldn't be triggered when you are updating a property value. 

When writing a new property value pair, yes, emmet should pitch in. Not otherwise.

I probably can tweak the logic that controls the triggering of emmet.

Thanks for reporting!

**Comment by user3323** [comment]
@ramya-rao-a, maybe you already figured that out, but it's better to inform you about one more thing.

The problem is bigger, than I thought.
This wrong searching algorithm works the same with custom Emmet snippets file.

Here is a custom snippet:
```
  "css": {
    "snippets": {
      
      "xx": "xaaaaaa"
    }
  }
```
If you will type one "x" - Emmet will suggest you this "xaaaaaa" snippet.
But, if you will type one more "x" - Emmet will show nothing.
Why? Because his highest searching priority (_or the only one?_) not on properties, like "xx", but on values, like "xaaaaaa".
If you will type "xa" or "xaaa" - you would not have any doubt about it.

**Comment by ramya-rao-a** [comment]
@user3323 The custom snippet issue that you brought up is a duplicate of #33072 Please read my reply there.

If you have any suggestions, we can continue the discussion in #33072

**Comment by ramya-rao-a** [comment]
@user3323 The custom snippet issue is fixed now and tonight's Insiders will have the fix. Can you give it a try?

**Comment by ramya-rao-a** [comment]
The fact that `auto` gets expanded to `align-self: auto;` is due to an upstream issue with Emmet. See https://github.com/emmetio/expand-abbreviation/issues/10

But the fact that even after you add `;` at the end of `auto`, the emmet suggestion still lingers is something I can fix which I did with https://github.com/Microsoft/vscode/commit/a915f4b3d8dc38fddca40700e60a967734ba2104

**Comment by user3323** [comment]
@ramya-rao-a 

> The custom snippet issue is fixed now and tonight's Insiders will have the fix. Can you give it a try?

I checked it. Works great! Thanks!

PS: can you say, is VS Code Insiders totally isolated from stable VS Code? Or they can make a mess with each other?

**Comment by ramya-rao-a** [comment]
@user3323 Insiders and Stable are different and share nothing. One doesn't affect the other.

**Comment by user3323** [comment]
@ramya-rao-a, hello.

ver. 1.17.0-ins

Problem with `"overflow: align-self: auto;"` - is still there. Not fixed.

Here is one more example, and again with `align-self`:

![align-self baseline](https://user-images.githubusercontent.com/24613274/30268537-b70f4f30-96ee-11e7-8ebe-74c4f530c511.gif)

**Comment by ramya-rao-a** [comment]
@user3323 See https://github.com/Microsoft/vscode/issues/32911#issuecomment-326127992

Also I've been thinking of explicitly not triggering emmet at all when one is typing in the value section of the css property value pair. Will need to look into if the current emmet css parser gives me that information

**Comment by ramya-rao-a** [comment]
@user3323 Just pushed a fix in for https://github.com/Microsoft/vscode/issues/34162
The fix will be available in tonight's Insiders build which you can get from https://code.visualstudio.com/insiders

Can you give it a try and let me know if it works for you?
