### ISSUE TITLE
High CPU usage on renderer on Linux (maybe because of git features)

### ISSUE THREAD

**Issue by gmardau** [Microsoft/vscode#33224]
- VSCode Version: 1.15.1
- OS Version: Arch-Linux, kernel 4.12.8-2

Steps to Reproduce:
Just open and wait. It only occurs when I start typing. I suspect it is the autocomplete dropdown helper, due to the delay until it appears.

Edit 1: Also, it only happens on some files, for some reason. They all have the '.h' extension and have no more than 500 lines.

Edit 2: I decided to change to name of the file, and it no longer has this problem. Another thing I noticed is that the the git lines on the side (green and blue) take several seconds to appear (the file only has 100 lines) whereas in other files is almost instant. Perhaps something to do with the git visualisation, since the problem is on the renderer process.

Edit 3: I commited the changes and that file no longer has issues, so definitely something to do with git. Before the problems what I did was copy a folder I had to name+"2", and I started recoding on the file from the original folder. Somehow it messed up with git, perhaps because the diff could just be a rename (the code on the copied folder was kept the same) but then the original file was being modified as well. (In case you want to see the [commit](https://github.com/gmardau/gmd-tree-library/commit/6888f665f6155a6a910657fd1eb99b95f5718bce))

Reproduces without extensions: Yes

``ps aux | grep studio-code``
```
gustavo   4356  0.8  0.6 1595344 104956 ?      Ssl  23:33   0:01 /opt/visual-studio-code/code
gustavo   4359  0.0  0.1 350444 30464 ?        S    23:33   0:00 /opt/visual-studio-code/code --type=zygote --no-sandbox
gustavo   4380  0.5  0.4 461136 81224 ?        Sl   23:33   0:01 /opt/visual-studio-code/code --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,23,71 --gpu-vendor-id=0x10de --gpu-device-id=0x139b --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-secondary-vendor-ids=0x8086 --gpu-secondary-device-ids=0x191b --service-request-channel-token=E421E49F39826372B07C0DFD06730F9C --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
gustavo   4391 33.2  1.3 1861392 228404 ?      Sl   23:33   1:19 /opt/visual-studio-code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=96D5ADE8B96AF945D53F36A4D2A96497 --lang=en-US --node-integration=true --background-color=#1e1e1e --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --service-request-channel-token=96D5ADE8B96AF945D53F36A4D2A96497 --renderer-client-id=4 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
gustavo   4393  0.2  0.5 1110112 90724 ?       Sl   23:33   0:00 /opt/visual-studio-code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=4AD4471B0E9E924B6A4E20FC21389C1E --lang=en-US --node-integration=true --hidden-page --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --service-request-channel-token=4AD4471B0E9E924B6A4E20FC21389C1E --renderer-client-id=6 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
gustavo   4438  1.2  0.6 1107124 111444 ?      Sl   23:33   0:03 /opt/visual-studio-code/code /opt/visual-studio-code/resources/app/out/bootstrap --type=extensionHost
gustavo   4439  0.1  0.3 937972 53128 ?        Sl   23:33   0:00 /opt/visual-studio-code/code /opt/visual-studio-code/resources/app/out/bootstrap --type=watcherService
gustavo   4472  0.5  0.4 1024160 71360 ?       Sl   23:33   0:01 /opt/visual-studio-code/code /home/gustavo/.vscode/extensions/streetsidesoftware.code-spell-checker-1.3.7/node_modules/vscode-languageclient/lib/utils/electronForkStart /home/gustavo/.vscode/extensions/streetsidesoftware.code-spell-checker-1.3.7/server/src/server.js --node-ipc
gustavo   4497  0.1  0.3 911848 57144 ?        Sl   23:34   0:00 /opt/visual-studio-code/code /opt/visual-studio-code/resources/app/extensions/json/node_modules/vscode-languageclient/lib/utils/electronForkStart /opt/visual-studio-code/resources/app/extensions/json/server/out/jsonServerMain.js --node-ipc
gustavo   4752  0.0  0.0  10796  2288 pts/0    S+   23:37   0:00 grep --color=auto studio-code
```

**Comment by joaomoreno** [comment]
Just to confirm... it does reproduce with `code --disable-extensions`?

**Comment by joaomoreno** [comment]
Can you record a screencast?

**Comment by gmardau** [comment]
Yes, it does reproduce.

> Can you record a screencast?

Of?

**Comment by joaomoreno** [comment]
A load monitor side by side with Code. htop would be great as it shows the entire git command line. I'd love to confirm the fact that it only happens on .h files. Maybe I'll see something interesting in the screencast.

After cloning https://github.com/gmardau/gmd-tree-library, what are the steps to reproduce? Just open any .h file and start typing?

**Comment by gmardau** [comment]
Ok, it's quite specific and tricky to reproduce, but I managed to do it.

- Clone the repository
- Copy folder (e.g bits/orthtree)
- On the original folder, remove the code from the files
- (I also had to rename the original folder to another name and then back)
- (and to restart VSCode)
- Copy some code to a file of the original folder (so it has something to run autocomplete from)
- Start typing

It only occurs when the file/tab is open/focused (several seconds until it shows the colored git lines) and when typing (several seconds until the autocomplete dropdown appears). If I stop typing or change window focus, it goes back down. It's quite difficult to make it reach this behaviour, but once it does I can restart VSCode, even the computer, and it keeps doing it.

Screenshot:
![screenshot from 2017-08-29 10-55-23](https://user-images.githubusercontent.com/13813272/29816550-6d578f8e-8cac-11e7-8fd4-83829db40da2.png)

I'm not sure what you meant by "shows the entire git command line".

**Comment by joaomoreno** [comment]
I meant that if it's a git issue, the `git` process should come up in htop, which doesn't seem to happen.

I'm going to have to ask you this again: can you follow those exact steps but start Code with `code --disable-extensions`. What's the outcome?

**Comment by gmardau** [comment]
The outcome is the same.

Screenshot:
![screenshot from 2017-08-29 11-39-28](https://user-images.githubusercontent.com/13813272/29817284-67131c94-8caf-11e7-8ffd-6363f1ea97d7.png)

**Comment by joaomoreno** [comment]
And visually, the git decorations still take several seconds to appear?

**Comment by gmardau** [comment]
Yes, the git decorations take about 3 seconds, whereas in other files is about half a second.
This only occurring in .h files I don't know, it just happens that I only have .h files. If I remove the extension .h from the file it doesn't happen, and if I put it back on, it returns.

But the same applies to the folder name. If I rename the folder, that file (with the .h extension still) no longer has problems. That was the reason that lead me to believe it had something to do with git and its diffs.

**Comment by joaomoreno** [comment]
@alexandrudima Any thoughts?

**Comment by alexandrudima** [comment]
@gmardau If this is something affecting the renderer process, then it should be very easy to profile what's going on:

It could also help if you could try it on our latest stable, 1.15.x or on our daily Insiders version, so we don't digg to deep to find an issue that might have been already resolved.

---

To get a CPU profile of the renderer process:
* Run `F1 > Toggle Developer Tools`
* Go to the `Profiles` tab
* Start a new CPU profile
* Do the actions that lead to slowness
* Save the CPU profile to a file and attach it
![28714](https://user-images.githubusercontent.com/5047891/27470530-b4ace330-57f4-11e7-91b5-2a9cf714336f.gif)

**Comment by gmardau** [comment]
I can confirm that the issue is still present in the latest version (1.15.1)

What I did exactly:
- Cloned the said repository
- Opened VSCode with ``--disable-extensions``
- Opened the folder
- Started profiling
- Copied ``bits/orthtree`` to ``bits/orthree2``
- Removed the code from the three files in ``bits/orthree``, apart from the preprocessor calls on the top and bottom of the files
- Started writing in ``bits/orthree/point_orthree.h`` 

Here is the profle:
[CPU-20170831T134746.zip](https://github.com/Microsoft/vscode/files/1267069/CPU-20170831T134746.zip)

**Comment by joaomoreno** [comment]
It doesn't really seem to be related to the main thread...

**Comment by alexandrudima** [comment]
Yes, I also couldn't spot anything suspicious in the CPU profile. It doesn't seem to me that the main thread is too busy, the UI thread is never blocked for more than a few 10s of ms at a time.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
