### ISSUE TITLE
terminal not painting until resize

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#34554]
Windows
1.17.0-insider
b0c063

The [docker extension](https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker) creates a lot of terminals when running docker commands.  I'm finding that the content of the terminal is not painting until i resize the terminal window.  It looks like the tool is hung, then you resize, then you can see the content.

Here's the docker build command running:

![image](https://user-images.githubusercontent.com/1487073/30525411-ebaf7924-9bba-11e7-8d0f-e65cae73a1c4.png)

Then resize, and now you can see the terminal:

![image](https://user-images.githubusercontent.com/1487073/30525416-0505ba5a-9bbb-11e7-9edf-6162a90197b9.png)

**Comment by Tyriar** [comment]
@chrisdias any errors in the devtools console?

**Comment by chrisdias** [comment]
@Tyriar no.

**Comment by liuliangsir** [comment]
@Tyriar i encountered the issue(some error in the devtools console)
1.17.0-insider 3339ad83f13da2ee8b44b3283df5cefc540aa19e

**Comment by Tyriar** [comment]
@chrisdias are the terminals created in the background and the rendering is not working when first moved to the foreground?

@liuliangsir what's the error?

**Comment by egamma** [comment]
(reopening)
This issue also affects the npm-script-runner extension.
To reproduce the problem:
- yo code to create an extension
- replace activate function with the following code:
```typescript
export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        let terminal = vscode.window.createTerminal('test');
	terminal.show();
        terminal.sendText('echo hello');
    });
    context.subscriptions.push(disposable);
}
```
- run the extension by executing the "Hello World" command.

What you will observe on Windows is that the terminal most of the times remains blank. Resizing will make the contents appear.

**Comment by Tyriar** [comment]
Fix pushed to master and release/1.17

**Comment by Tyriar** [comment]
For the interested, I believe this was caused by a race condition that only seemed to happen on Windows for some reason. The terminal would perform a layout before the terminal instance was visible, this caused the element which measured the character to return 0 width and 0 height which prevents all rendering.

The fix was to force a layout whenever visibility of the terminal was set to true.

**Comment by egamma** [comment]
@Tyriar I failed to repro this on Mac, glad we have a fix, thanks!

**Comment by OriginalEXE** [comment]
I am getting the same bug on:
**Ubuntu 16.04**
Version 1.17.0
Commit be377c0faf7574a59f84940f593a6849f12e4de7
Date 2017-10-04T23:33:45.303Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Resizing the terminal area fixes the issue.

**Comment by fabiospampinato** [comment]
@Tyriar This is very much not fixed yet. I'm running v1.17.1 under macOS 10.13.

This is how to reproduce it:

- Open a random folder
- Install [Terminals](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals)
- Run `Terminals: Edit configuration` and save the file
- Open a terminal
- Run `Terminals: Run Single`
- Select `Single` and hit enter
- The newly create terminal is completely blank

Also when doing this everything except the window control buttons moves very annoyingly up about a couple of pixels. Only if the statusbar is hidden :confused:

**Comment by chrmarti** [comment]
@fabiospampinato This fix will be in the upcoming 1.17.2.
