### ISSUE TITLE
Folders in workspace not expandable after latest release

### ISSUE THREAD

**Issue by rtopiwala** [Microsoft/vscode#35588]
<img width="327" alt="screen shot 2017-10-04 at 1 08 27 pm" src="https://user-images.githubusercontent.com/2275245/31191887-36f100d6-a905-11e7-8330-08a0ae43181d.png">
- VSCode Version: Code - Insiders 1.17.0-insider (81fc22ec957de26d2bf6aada3f16f04e0164741c, 2017-10-03T22:47:28.178Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
indenticator|Sir|0.4.2
python|don|0.7.0
vscode-icons|rob|7.14.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.  Open VSCode Insiders and add folders to workspace
2. Removing and adding folders back does not fix it. The un-expandable bug remains with two top-most folders and one in the middle.

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
Could you check if there is anything in the console? (Help > Toggle Developer Tools)

**Comment by rtopiwala** [comment]
Here's the only error in the console:
```
[IPC Library: Search] (node:38621) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
t.log                                    @ console.ts:123
(anonymous)                     @ ipc.cp.ts:158
e.invoke                             @ callbackList.ts:36
e.fire                                  @ event.ts:123
r                                         @ event.ts:12
emitTwo                            @ events.js:106
emit                                   @ events.js:194
process.nextTick             @ internal/child_process.js:766
_combinedTickCallback  @ internal/process/next_tick.js:73
_tickCallback                    @ internal/process/next_tick.js:104
```

**Comment by sandy081** [comment]
@rtopiwala Can you please open and see the workspace configuration of this workspace and check if there is any thing suspecting?

You can open the workspace configuration file using the command `Open Workspace Configuration File`.

**Comment by mxrtos** [comment]
This happens to me as well in the last folder, even when running without extensions. I do see the expand/contract arrow on the left of the folder, and I can even click it, but vscode is not opening the files inside. I can't even search through files. This is pretty much a show stopper. 

- I open up the console and unlike @rtopiwala  I did not see any console errors.
- My workspace settings are default.
- The folder that does not open has subfolder names in uppercase (this shouldn't be a problem).

I used this command to open vscode:
```bash
code --disable-extensions .
```
My vscode version:
```bash
Version 1.16.1
Commit 27492b6bf3acb0775d82d2f87b25a93490673c6d
Date 2017-09-14T16:26:20.018Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by mxrtos** [comment]
Don't know if this helps but with the developer tools, I went all the way down to the div of the folder that does not expand. And what I saw unusual is the id in that div. it was huge compared to that of the other folders that do open.
```bash
<div class="monaco-tree-row focused selected has-children" draggable="true" role="treeitem" aria-label="Projects, Files Explorer" aria-selected="true" aria-expanded="true" aria-level="1" style="height: 22px; padding-left: 12px;" id="ZmlsZSUzQSUyRiUyRiUyRmhvbWUlMkZoZXJuYWp1YSUyRnBlcmZvcmNlJTJGdXNlcnMlMkZoZXJuYWp1YSUyRjEwMDg3X0RFVl9BUFJJVkFfSU5URVJBQyUzQWZpbGUlM0ElMkYlMkYlMkZob21lJTJGaGVybmFqdWElMkZwZXJmb3JjZSUyRnVzZXJzJTJGaGVybmFqdWElMkYxMDA4N19ERVZfQVBSSVZBX0lOVEVSQUMlMkZEZXZfUHJvamVjdHM="><div class="content"><div class="monaco-icon-label folder-icon projects-name-folder-icon explorer-item" title="~/my/code/path/here" style="display: block;"><a class="label-name">Projects</a><span class="label-description empty"></span></div></div></div>
```

**Comment by rtopiwala** [comment]
@sandy081 Nothing unusual in the workspace configuration. 

Yesterday I pushed some commits to remote repo using vscode. Afterwards the top-most folder regained its arrow and the dir contents were visible. The git push was  for a different project, not 'devops_ansible'. No other steps were performed on vscode.
<img width="358" alt="screen shot 2017-10-05 at 10 33 18 am" src="https://user-images.githubusercontent.com/2275245/31236143-ee626f44-a9b8-11e7-8cc3-2f85ae99a23f.png">

**Comment by isidorn** [comment]
I thought I might have broken this with 8a3b716868
However I see that the original comment is older than my commit.

@rtopiwala if you open a brand new workspace with only those folders which can not be expanded can they still not be expaneded? How about if you only open one of those folders in vscode?

**Comment by rtopiwala** [comment]
Quick note on which folders are not expandable. Its actually tied to the folder position in the workspace rather than folder name, ie. always the two top-most folders and one in the middle.

However I just updated to 
Version 1.18.0-insider (1.18.0-insider) af6ca44db81f5186d3104226c8e76e026789ce20

and the issue is resolved, all folders are expandable now. thanks guys.

**Comment by isidorn** [comment]
@rtopiwala thanks, my fix to resolve folders independetly probably fixed this 8a3b716. Please let us know if you can still see this issue with insiders and we will reopen
