### ISSUE TITLE
Snippet transforms do not handle regex with alternatives or optional matches

### ISSUE THREAD

**Issue by dogoku** [Microsoft/vscode#36089]
- VSCode Version: v1.17
- OS Version: N/A

Snippet transform functions (/upcase, /downcase, /capitalize) do not apply to optional capture groups, such as in case of a regex with alternatives, e.g. the regex in the example below ([explanation](https://regex101.com/r/wgrzaw/2)). Instead the matches get replaced by the literal strings (i.e the string "/upcase").

I had a look at the [grammar](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/browser/snippet.md#L31) and it seems that the EBNF does not specify what `if` and `else` mean for the `format` rule, so I guess the implementation is not technically "wrong". But given that your intention for this feature is to be compatible with TM and ST snippets, then I see this as a bug, since this is possible in ST (albeit with a [different format syntax](http://www.boost.org/doc/libs/1_44_0/libs/regex/doc/html/boost_regex/format/perl_format.html)).

---

Steps to Reproduce:

1. Add the following snippet to your js user snippets
```
"Class name": {
    "prefix": "hclass",
    "body": "${1:${TM_FILENAME/^(.)|(?:-(.))|(\\.js)/${1:+/upcase}${2:+/upcase}/g}}",
    "description": "Converts a hyphenated filename to a class name"
}
```
2. Open a js file with a hyphenated name, e.g `my-awesome-module.js`
3. Type `hclass` and expand the snippet

Expected result: `MyAwesomeModule`
Actual result: `/upcasey/upcasewesome/upcaseodule`

**Comment by MartynasZilinskas** [comment]
I was looking how to change from `kebab-case` to `PascalCase` too. This would be really nice to have.

**Comment by jrieken** [comment]
Yeah, the is something off. It should be `${1:/upcase}` and not `${1:+/upcase}` but it still won't work... I'll investigate

**Comment by dogoku** [comment]
I used the `${1:+/upcase}` because the regex has alternate cases, so the group might not exist. I had to do the same thing for the ST version as well, i.e: `(?1\u$1:)(?2\u$2:)`

Actually i tried `${1:/upcase}` as well, when the first one didn't work, but it throws an exception, cause it cant replace something undefined, which makes sense if you think about it.

**Comment by jrieken** [comment]
Yeah, `/upcase` et al need to be smarter. And the whole regex evaluation needs to be a little smarter...

**Comment by dogoku** [comment]
Let me know if I can help in some way. I haven't looked at the code at all, but I'm willing to help out. Thx

**Comment by ashclarke** [comment]
I'm trying to do something similar with CapitalCase filename -> kebab-case.

I have `${TM_FILENAME_BASE/([A-Z][a-z]+)([A-Z][a-z]+$)?/$1-$2/g}` but no way to downcase it after.

I tried wrapping it with another variable but get an Invalid Arguments warning.

`${templatepath:${TM_FILENAME_BASE/([A-Z][a-z]+)([A-Z][a-z]+$)?/$1-$2/g}/downcase}`

and this result:

`Capital-Case-Name/downcase`

I'm not sure if I've just read the capability of this wrong, or if something is missing in VS Code.

**Comment by jrieken** [comment]
@dogoku I have pushed changes to make the format string smarter (that means not explode when having no match). You can now use this pattern: `${TM_FILENAME/^(.)|(?:-(.))|(\\.js)/${1:/upcase}${2:/upcase}/g}`, which is also how it works in Textmate itself. 


@ashclarke You need to apply the /downcase function on  the match, so `${1:/downcase}` etc. Check out https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/test/browser/snippetVariables.test.ts#L198

**Comment by ashclarke** [comment]
Thanks @jrieken - I will check it out!

**Comment by dogoku** [comment]
Thanks @jrieken, is this patch available in Insider's build?

**Comment by jrieken** [comment]
Yeah, should be available with todays insiders build

**Comment by dogoku** [comment]
@jrieken Sorry to do this again, but I found another bug :(

In the latest insiders build (v1.18.0-86e057cd), transforms are working for optional matches, however not all the transforms are applied if you reused the same variable (e.g $1) in other parts of the snippet.

Given the following simplified example: 

```js
//TM_FILENAME_BASE: `my-awesome-module.js`
[
"function ${1:${TM_FILENAME_BASE/^(.)|-(.)/${1:/upcase}${2:/upcase}/gm}} () {}",
"module.exports = $1;"
]

//Expected
function MyAwesomeModule () {}
module.exports = MyAwesomeModule;

//Actual
function MyAwesomeModule () {}
module.exports = My-awesome-module;
```

In case you missed it, the second use of $1 was not transformed properly, having only the first transform applied to it `${1:/upcase}`, where as the second transform `${2:/upcase}` was not applied at all, resulting in the string `My-awesome-module` instead of `MyAwesomeModule`

Should I open a new ticket for this?

**Comment by ashclarke** [comment]
I noticed this too, before, but it wasn’t the insiders build. It was in the
latest stable release as well.

**Comment by jrieken** [comment]
> Sorry to do this again, but I found another bug :(

Nothing to be sorry about except for not filing a new issue.

**Comment by dogoku** [comment]
> Nothing to be sorry about except for not filing a new issue

No worries @jrieken here you go: #37702
