### ISSUE TITLE
FileSystemProvider: explorer does not pick up new files via FileChange event

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#36946]
- VSCode Version: Version 1.18.0-insider (1.18.0-insider), 509630f
- OS Version: 10.12.6

Steps to Reproduce:
1. Create a file system provider that implements file change notifications
2. Open a provided folder in the explorer view
3. Add a file (resulting in a file-change event for both the file and parent folder)
4. Observe: vscode does not update the contents of the folder to show the new file. (Deleted files *are* removed from the folder.)

*Side note*: `vscode.FileChangeType.Updated`, `vscode.FileChangeType.Added`, and `vscode.FileChangeType.Deleted` seem to be undefined, so I've hardcoded them as 0, 1, 2 respectively.

**Comment by jrieken** [comment]
@isidorn I have fixed some issues around missing types and serialisation but ultimately this is an issue with the explorer and how it always assumes file changes are from the `file`-schema: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L622

**Comment by isidorn** [comment]
@jrieken thanks for finding this. I have removed all asumptions that these resources are `file` specific.
@siegebell can you please try to reproduce this issue in the next insiders (should be out tomorrow)

**Comment by jrieken** [comment]
Thanks @isidorn. I have a simple test (adding a folder to the root) which now works. 

![jan-16-2018 07-48-51](https://user-images.githubusercontent.com/1794099/34997589-bacb10e4-fa91-11e7-84a1-4477450c708f.gif)

**Comment by siegebell** [comment]
@isidorn I'm still having this issue as of 531d713432c82e4ffe341f35d03a461713f96660.

@jrieken where can I find the test case you wrote?

**Comment by jrieken** [comment]
No test, unfortunately but I have a sample that I can share with you. Simply pasting it here, but I can also upload to GH. Then I have wired up a command that creates new files

```ts
    const memfs = new InMemFs();
    vscode.workspace.registerFileSystemProvider('mem', memfs);

    vscode.commands.registerCommand('extension.sayHello', () => {
        memfs.write(
            memfs.root.with({ path: join(memfs.root.path, `somefile-${Math.random().toString(17).slice(-3)}.txt`) }),
            Buffer.from("This is new...")
        );
    })
```

```ts

import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

class Entry implements vscode.FileStat {
    static idPool = 0;
    id: number = Entry.idPool++;
    name: string;
    mtime: number;
    atime: number;
    size: number;
    type: vscode.FileType;
}

class Directory extends Entry {
    type = vscode.FileType.Dir;
    size = 0;
    children = new Map<string, Entry>();
}

export class InMemFs implements vscode.FileSystemProvider {

    // private readonly _entries = new Map<string, Entry>();
    private readonly _root: Directory;
    private readonly _data = new Map<number, Uint8Array>();

    private readonly _onDidChange = new vscode.EventEmitter<vscode.FileChange[]>();

    readonly onDidChange: vscode.Event<vscode.FileChange[]> = this._onDidChange.event;

    root = vscode.Uri.parse('mem://füø/');

    constructor() {
        this._root = new Directory();
        this._root.name = '/';
        this._root.mtime = Date.now();
        this._root.atime = Date.now();
    }

    private _lookUp(path: string): Entry {
        let parts = path.split('/');
        let i = 0;
        let entry: Entry = this._root;
        for (; i < parts.length; i++) {
            let part = parts[i];
            if (!(entry instanceof Directory)) {
                throw new Error('ENOEXIST');
            }
            if (part) {
                entry = entry.children.get(part);
            }
        }
        if (!entry) {
            throw new Error('ENOEXIST');
        }
        return entry;
    }

    async utimes(resource: vscode.Uri, mtime: number, atime: number) {
        const { path } = resource;
        const entry = this._lookUp(resource.path);
        entry.mtime = mtime;
        entry.atime = atime;
        this._onDidChange.fire([{ resource, type: vscode.FileChangeType.Updated }]);
        return entry;
    }

    async stat(resource: vscode.Uri) {
        return this._lookUp(resource.path);
    }

    async read(resource: vscode.Uri, offset: number, length: number, progress: vscode.Progress<Uint8Array>) {
        const entry = this._lookUp(resource.path);
        if (!entry || entry.type !== vscode.FileType.File) {
            throw new Error('EISDIR');
        }
        entry.atime = Date.now();
        const buf = this._data.get(entry.id);
        const bytesRead = Math.min(buf.byteLength - offset, length)
        progress.report(buf.slice(offset, bytesRead));
        return bytesRead;
    }

    async write(resource: vscode.Uri, content: Uint8Array) {
        const parent = this._lookUp(path.dirname(resource.path));
        if (!(parent instanceof Directory)) {
            throw new Error('missing parent');
        }
        let entry = parent.children.get(path.basename(resource.path));
        if (!entry) {
            entry = new Entry();
            entry.name = path.basename(resource.path);
            entry.type = vscode.FileType.File;
            entry.atime = Date.now();
            parent.children.set(entry.name, entry);
            this._onDidChange.fire([{ resource, type: vscode.FileChangeType.Added }]);
        }
        if (entry.type !== vscode.FileType.File) {
            throw new Error('EISDIR');
        }
        this._data.set(entry.id, content);
        entry.size = content.byteLength;
        entry.mtime = Date.now();
        this._onDidChange.fire([{ resource, type: vscode.FileChangeType.Updated }]);
    }

    async mkdir(resource: vscode.Uri) {
        const parent = this._lookUp(path.dirname(resource.path));
        if (!(parent instanceof Directory)) {
            throw new Error('NOPARENT');
        }
        const entry = new Directory();
        entry.name = path.basename(resource.path);
        entry.mtime = Date.now();
        entry.atime = Date.now();
        parent.children.set(entry.name, entry);
        this._onDidChange.fire([{ resource, type: vscode.FileChangeType.Added }]);
        return entry;
    }

    async readdir(resource: vscode.Uri) {
        const entry = this._lookUp(resource.path);
        if (!(entry instanceof Directory)) {
            throw new Error('ENODIR');
        }
        const result: [vscode.Uri, vscode.FileStat][] = [];
        for (const [, child] of entry.children) {
            result.push([resource.with({ path: path.join(resource.path, child.name) }), child]);
        }
        return result;
    }

    async rmdir(resource: vscode.Uri) {
        // const entry = this._lookUp(resource.path);
        throw new Error("Method not implemented.");
    }

    async unlink(resource: vscode.Uri) {
        const parent = this._lookUp(path.dirname(resource.path));
        if (!(parent instanceof Directory)) {
            throw new Error();
        }
        const entry = parent.children.get(path.basename(resource.path));
        this._data.delete(entry.id);
        parent.children.delete(entry.name);
    }

    move(resource: vscode.Uri, target: vscode.Uri): Thenable<vscode.FileStat> {
        throw new Error("Method not implemented.");
    }
}
```

**Comment by siegebell** [comment]
@jrieken In short, the issue happens when the remote folder ends in `/`...

1. Change the root to `vscode.Uri.parse('mem://foo/bar/');`.
2. Add `memfs.mkdir(vscode.Uri.parse('mem://foo/bar'));` immediately after creating `memfs`.
3. Use this workspace:
```
{
  "folders": [
    {
      "uri": "mem://foo/bar/"
    }
  ],
  "settings": {}
}
```

Observe:
* Run `extension.sayHello`: the file is *not added* to the explorer tree. Refreshing will show the file.
* Now change your workspace path to `mem://foo/bar` (i.e. drop the `/` at the end). You'll probably have to restart vscode due to unrelated errors? The add-file event *now works*.

**Comment by jrieken** [comment]
@siegebell Not sure I understand 1. and 2.? You add `men://foo/bar/` as workspace and that inside that workspace create a directory with the same name?

**Comment by siegebell** [comment]
Use this workspace:
```
{
  "folders": [
    {
      "uri": "mem://foo/bar/"
    }
  ],
  "settings": {}
}
```

And here is the full code:
```
'use strict';
import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

class Entry implements vscode.FileStat {
    static idPool = 0;
    id: number = Entry.idPool++;
    name: string;
    mtime: number;
    atime: number;
    size: number;
    type: vscode.FileType;
}

class Directory extends Entry {
    type = vscode.FileType.Dir;
    size = 0;
    children = new Map<string, Entry>();
}

export class InMemFs implements vscode.FileSystemProvider {

    // private readonly _entries = new Map<string, Entry>();
    private readonly _root: Directory;
    private readonly _data = new Map<number, Uint8Array>();

    private readonly _onDidChange = new vscode.EventEmitter<vscode.FileChange[]>();

    readonly onDidChange: vscode.Event<vscode.FileChange[]> = this._onDidChange.event;

    root = vscode.Uri.parse('mem://foo/bar/');

    constructor() {
        this._root = new Directory();
        this._root.name = '/';
        this._root.mtime = Date.now();
        this._root.atime = Date.now();
    }

    private _lookUp(path: string): Entry {
        let parts = path.split('/');
        let i = 0;
        let entry: Entry = this._root;
        for (; i < parts.length; i++) {
            let part = parts[i];
            if (!(entry instanceof Directory)) {
                throw new Error('ENOEXIST');
            }
            if (part) {
                entry = entry.children.get(part);
            }
        }
        if (!entry) {
            throw new Error('ENOEXIST');
        }
        return entry;
    }

    async utimes(resource: vscode.Uri, mtime: number, atime: number) {
        const { path } = resource;
        const entry = this._lookUp(resource.path);
        entry.mtime = mtime;
        entry.atime = atime;
        this._onDidChange.fire([{ resource, type: vscode.FileChangeType.Updated }]);
        return entry;
    }

    async stat(resource: vscode.Uri) {
        return this._lookUp(resource.path);
    }

    async read(resource: vscode.Uri, offset: number, length: number, progress: vscode.Progress<Uint8Array>) {
        const entry = this._lookUp(resource.path);
        if (!entry || entry.type !== vscode.FileType.File) {
            throw new Error('EISDIR');
        }
        entry.atime = Date.now();
        const buf = this._data.get(entry.id);
        const bytesRead = Math.min(buf.byteLength - offset, length)
        progress.report(buf.slice(offset, bytesRead));
        return bytesRead;
    }

    async write(resource: vscode.Uri, content: Uint8Array) {
        const parent = this._lookUp(path.dirname(resource.path));
        if (!(parent instanceof Directory)) {
            throw new Error('missing parent');
        }
        let entry = parent.children.get(path.basename(resource.path));
        if (!entry) {
            entry = new Entry();
            entry.name = path.basename(resource.path);
            entry.type = vscode.FileType.File;
            entry.atime = Date.now();
            parent.children.set(entry.name, entry);
            this._onDidChange.fire([{ resource, type: vscode.FileChangeType.Added }]);
        }
        if (entry.type !== vscode.FileType.File) {
            throw new Error('EISDIR');
        }
        this._data.set(entry.id, content);
        entry.size = content.byteLength;
        entry.mtime = Date.now();
        this._onDidChange.fire([{ resource, type: vscode.FileChangeType.Updated }]);
    }

    async mkdir(resource: vscode.Uri) {
        const parent = this._lookUp(path.dirname(resource.path));
        if (!(parent instanceof Directory)) {
            throw new Error('NOPARENT');
        }
        const entry = new Directory();
        entry.name = path.basename(resource.path);
        entry.mtime = Date.now();
        entry.atime = Date.now();
        parent.children.set(entry.name, entry);
        this._onDidChange.fire([{ resource, type: vscode.FileChangeType.Added }]);
        return entry;
    }

    async readdir(resource: vscode.Uri) {
        const entry = this._lookUp(resource.path);
        if (!(entry instanceof Directory)) {
            throw new Error('ENODIR');
        }
        const result: [vscode.Uri, vscode.FileStat][] = [];
        for (const [, child] of entry.children) {
            result.push([resource.with({ path: path.join(resource.path, child.name) }), child]);
        }
        return result;
    }

    async rmdir(resource: vscode.Uri) {
        // const entry = this._lookUp(resource.path);
        throw new Error("Method not implemented.");
    }

    async unlink(resource: vscode.Uri) {
        const parent = this._lookUp(path.dirname(resource.path));
        if (!(parent instanceof Directory)) {
            throw new Error();
        }
        const entry = parent.children.get(path.basename(resource.path));
        this._data.delete(entry.id);
        parent.children.delete(entry.name);
    }

    move(resource: vscode.Uri, target: vscode.Uri): Thenable<vscode.FileStat> {
        throw new Error("Method not implemented.");
    }
}

export function activate(context: vscode.ExtensionContext) {
    const memfs = new InMemFs();
    memfs.mkdir(vscode.Uri.parse('mem://foo/bar'));
    vscode.workspace.registerFileSystemProvider('mem', memfs);

    vscode.commands.registerCommand('extension.sayHello', () => {
        memfs.write(
            memfs.root.with({ path: path.join(memfs.root.path, `somefile-${Math.random().toString(17).slice(-3)}.txt`) }),
            Buffer.from("This is new...")
        );
    })
}

export function deactivate() {
}
```

Observe: running command "Hello World" does not add new files to the explorer view until you manually refresh the view.

**Comment by jrieken** [comment]
Thanks @siegebell. @isidorn There is more issues with the explorer model as it seems... It should not be using `fsPath` to associate a file with a workspace folder.

<img width="842" alt="screen shot 2018-01-24 at 11 23 41" src="https://user-images.githubusercontent.com/1794099/35327136-1ba86c32-00f9-11e8-8c3f-a7500b55b96c.png">

Apart from that the `isEqual` function seem to be broken, see attached screenshot as it fails to identify `/bar` and `/bar/` as being equal. I believe that's @bpasero 

<img width="806" alt="screen shot 2018-01-24 at 11 23 31" src="https://user-images.githubusercontent.com/1794099/35327135-1b8e437a-00f9-11e8-8c5a-9e0b8466585e.png">

**Comment by bpasero** [comment]
Yeah, it looks like `isEqual` and `isEqualOrParent` should maybe trim trailing slashes from the path 👍

**Comment by isidorn** [comment]
I changed the explorer model to no longer have file path assumptions.
As for changin `isEqual` and `isEqualOrParent` i believe it is smarter to do that in debt week, and not endgame -> February, will do it next week.

**Comment by isidorn** [comment]
For this milestone we have reduced the usage of isResourceOrParent in the explorer, however there is still some debt to be done captured in this itemhttps://github.com/Microsoft/vscode/issues/46549
Once that is tackled we can finally fix this, thus moving for now to April

**Comment by isidorn** [comment]
This is actually fixed for the april milesonte on the explorer side.
In the may milsestone we plan to change the compare functions, but there is an open PR for that thus no need to keep this open
