### ISSUE TITLE
User Snippets don't show up after dot

### ISSUE THREAD

**Issue by rwmb** [microsoft/vscode#37166]
Hi.
I'm having a problem when I try to use a custom snippet for the first time typing the prefix after a dot. It doesn't work at first, so I have to delete the prefix or press Esc to type again or press Ctrl + Space and then it shows up normally.

- VSCode Version: 1.17.2
- OS Version: Windows 10 64 bits

Steps to Reproduce:

1. Create Snippet
```
"Then -> Promise": {
		"prefix": "then",
		"body": [
			"then((${1:args}) => {",
			"\t$0",
			"})"
		],
		"description": "Open Arrow Function"
         }
```
2. Try to use it in any open js file after a dot.

![vscodesnippetsnotworking](https://user-images.githubusercontent.com/20707521/32183845-4b7d4540-bd92-11e7-8929-89087d14a832.png)

Reproduces without extensions: Yes

**Comment by RichardViana** [comment]
After searching more I found out that this can be solved by adding `"typescript.useCodeSnippetsOnMethodSuggest": true` to the settings file.

**Comment by RichardViana** [comment]
After searching I found out that this property `typescript.useCodeSnippetsOnMethodSuggest` set to true should solve the issue but it's not working for me.

**Comment by mjbvz** [comment]
@RichardViana Yes this should be unrelated to `typescript.useCodeSnippetsOnMethodSuggest`

@jrieken Can you please take a look at this. I don't think it is JS specific. In the case:

```
x.then()
x.|
```

The snippet suggest provider returns nothing

**Comment by jrieken** [comment]
Pressing the "dot" is very special because an extension (JS) registered for it and when that's the case we only show its suggestions, not those from other provider. Not sure what the right thing will be

**Comment by rwmb** [comment]
So maybe an extension should fix it.

**Comment by jrieken** [comment]
Needs some thinking. Today, the snippet logic is not even asked when a trigger character, like dot, is being hit. The reason for not asking every provider on trigger characters that they are meant to be used for things like member completion. Getting unrelated suggestions after e.g. `console.` might confuse folks. However, snippets are always special not the same as word-based suggestions for instance. We should consider to check for snippets that start with the trigger character...

**Comment by rwmb** [comment]
Makes sense, thanks @jrieken

**Comment by jrieken** [comment]
This might make people unhappy as things like member completion now is more bloated...


<img width="710" alt="screen shot 2017-12-01 at 15 23 31" src="https://user-images.githubusercontent.com/1794099/33486829-9edafe44-d6ab-11e7-8e9a-825081d3e253.png">

**Comment by rwmb** [comment]
couldn't it be an option in the settings? I don't know what are the requirements for a feature to gain a property in the settings file

**Comment by jrieken** [comment]
Yeah, maybe a setting... Needs for thinking and I am pushing our for Nov

**Comment by usernamehw** [comment]
How about new property in snippet definition that tells if snippet can be shown after dot(trigger characters?)
```javascript
"shownAfterDot": false[default] | true,
```
Having all snippets displayed after dot seems redundant.

**Comment by jrieken** [comment]
Sorry, slipping again with this one...

**Comment by user3323** [comment]
@rwmb 

"needs some thinking"... "needs some thinking" :smiley: 

He needs "some thinking" for more than half a year about this **_annoying as hell "after a dot issue"_**.
And every new issue from any new people he makes a look, like he just heard about that a moment ago.

https://github.com/Microsoft/vscode/issues/32201 - here is this "after a dot issue", created by me on 10 Aug 2017. On 8 Dec 2017, four months later I've asked is there any progress about that - and got hilarious and ridiculous answer about "likes". Something like "only likes give me enough power to work on any issue". And if you did not get enough likes on your issue - you can't even dream about me fixing it. Could be behavior of dev more disgusting, than that?.. 
So he closed issue https://github.com/Microsoft/vscode/issues/32201 , and nobody can add some new comments on it to describe their experience about it. And he himself doesn't even reference to it from other the same issues, or the contrary. Maybe that's how he "fixes" issue, just closing them on github :smiley: 

https://github.com/Microsoft/vscode/issues/39915 - that's another issue, created by me, after he closed the main one. Where I explain literally everything. Every damn feeling. And why the "after the dot" behavior of VS Code snippet area is totally wrong. Also closed.

So, half a year has passed.
And still nothing.
Oh, I am sorry, not nothing, but "thinking process"...

@jrieken, hi there! You can delete this comment, as well as others.

**Comment by rwmb** [comment]
@user3323 I understand your frustration about this, but you have to keep in mind that this is not the only issue opened and VS Code is a great and free software that doesn't ask anything from us to use it. They're getting paid to work on this software, sure, but we don't pay to use it, it's even open source. I've opened this issue having in mind that it's not an amazing feature that will change my professional life, and I knew it's not a big concern for most people and that's the way they have to measure how important an issue is, they won't stop working on a bug that deletes files for all users to work on a feature request that only a few guys here and there thought would be nice, get it? I've opened issues that were indeed problematic bugs that were solved in the same day. I'm not trying to be an ass kisser, it's just that when you get more experience with development you see that solutions don't magically appears in front of your eyes (it would be nice if they did, though), I'm passing through the same problem with Angular 2/4/5/6 being called just Angular when there's an AngularJS already, and this looks very dumb and always makes me lose time on google whenever I have to search a problem regarding Angular (v 2/4/5/6 of course), so I understand your frustration, it's always bad when no one hears us. But if you think they can't solve the issue or would like a solution right now, you can always make a pull request with the solution or create an extension, that's where great features come from, I didn't do it myself because I don't have the time.

Regards,
Richard William

**Comment by user3323** [comment]
@rwmb 

> a feature request that only a few guys here and there thought would be nice

well, I think that you are wrong about "few guys".. I believe, that there are thousands of people, who face it, and who are pissed off because of this issue, but they are just too lazy to report about it and describe the problem, or even find already created issue and give it a :+1:

**Comment by jalovatt** [comment]
Just because I don't see it mentioned anywhere here and it may be of some help in isolating the problem...

In #53460 I found that this issue is linked to the _editor.quickSuggestionsDelay_ setting. With a snippet triggered by typing ```foo.bar```, typing ```foo.``` before the timer runs out will cause issues populating the list. Typing ```foo``` and pausing long enough for the timer to finish before adding the dot will (at least here) bring up the full, correct list every time.

**Comment by user3323** [comment]
@jrieken  a year has passed. **_After the dot_** issue is still alive.

**Comment by jrieken** [comment]
It's not the real deal but you can get snippets after trigger characters when they start with one, e.g. `.then` instead of `then`. Like, so

```json
"Then -> Promise": {
	"prefix": ".then",
	"body": [
		".then((${1:args}) => {",
		"\t$0",
		"})"
	],
	"description": "Open Arrow Function"
},
```
