### ISSUE TITLE
Load extension host after workbench is running and introduce phase

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#38323]
I think we should try again to spawn the extension host only after the workbench is running. I remember @jrieken tried this but then we had clients that would prevent the restoring of editors from happening (via preferences editor).

We should replace `IExtensionService.onReady()` with a `LifecyclePhase` that is always fired after `LifecyclePhase.Running` imho and then we have a consistent picture of phases.

That means revisiting each user of `IExtensionService.onReady()` and making sure it is not blocking the startup. One challenge is that it is hard to prevent deadlocks from happening because we will always add new code that might cause it.

Thoughts?

**Comment by bpasero** [comment]
@sandy081 problematic in settings/keybindings: [`KeybindingsEditorModel.resolve()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/common/keybindingsEditorModel.ts#L145) and [`PreferencesService.resolve()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/preferencesService.ts#L111)

Potentially dangerous (depends on usage): [`IExtensionService.getExtensions()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L262) and [`IExtensionService.readExtensionPointContributions()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L268)

And then a lot in IModeService: [`getOrCreateMode`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/modeServiceImpl.ts#L134), [`getOrCreateModeByLanguageName`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/modeServiceImpl.ts#L160), `getOrCreateModeByFilenameOrFirstLine`, et al

**Comment by jrieken** [comment]
> Thoughts?

We should remove `IExtensionService#onReady`. Maybe make it a lifecycle event but surely never block on it but treat it like an event, e.g. to update something

**Comment by bpasero** [comment]
@jrieken yeah I had that thought as well, if we make it as an event it reduces the chance that someone would chain that promise up all the way to some critical code path.

However, if we have an event, that would be an argument against adding it to the lifecycle service, because there we typically have promises.

**Comment by sandy081** [comment]
Fixed it in Settings editor by removing the dependency on `IExtensionService#onReady` instead listening to default configuration changes - https://github.com/Microsoft/vscode/issues/38329

**Comment by sandy081** [comment]
Re [`KeybindingsEditorModel.resolve()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/common/keybindingsEditorModel.ts#L145), Keybindings editor renders Keybindings and unbound commands. There is already an event that is triggered when keybindings are changed / registered. But not sure there is an event triggered when commands change / registered so that the editor can be updated.

**Comment by alexandrudima** [comment]
@bpasero `IModeService.getOrCreateMode()` blocks on the extensions ready (i.e. extensions scanned and extension points invoked, not necessarily extension host process ready), but that is IMHO inconsequential as it does not block the creation/displaying of a buffer.

**Comment by bpasero** [comment]
@sandy081 well, the idea is to not join your promise on the extensions ready promise. So the event that you are looking for is still the same ("extensions ready") but you should simply update the editor when it happens instead of waiting for it before the editor is loaded.

...I think all of this will be much easier once we replace the promise to be an event.

**Comment by jrieken** [comment]
> There is already an event that is triggered when keybindings are changed / registered. 
Really, where? I'd copy from it

> But not sure there is an event triggered when commands change / registered so that the editor can be updated.

Doesn't exist but can be added

**Comment by sandy081** [comment]
@jrieken [here](https://github.com/microsoft/vscode/blob/master/src/vs/platform/keybinding/common/keybinding.ts#L45)

**Comment by sandy081** [comment]
> the idea is to not join your promise on the extensions ready promise

@bpasero Not sure what you mean here. Settings editor is no longer depending on the extensions ready promise. Also it does not wait for any. It simply updates the editor with newly registered default settings by listening to the configuration change event. More details are here #38329.

I would like to do the same for Keybindings editor. But I am missing an event when commands are registered.

**Comment by bpasero** [comment]
@sandy081 makes sense. I was just saying that as a workaround for now you could still react to the extensions loading promise. But in general if we ever want to support installing an extension without window reload then this would not be a good approach, so an event that is specific is always better 👍

**Comment by sandy081** [comment]
Agreed. We just have specific events rather than general extensions loading promise.

**Comment by bpasero** [comment]
@sandy081 could you introduce a new event from `IExtensionService` that signals extensions have changed? This event could then also be sent when we enable/disable extensions during the session without restart and adopters would be aware that this can happen anytime (like root folders can change anytime even after startup). I see in many cases the current promise is used like an event already.

**Comment by sandy081** [comment]
Sure

**Comment by bpasero** [comment]
@sandy081 I still think we should then maybe go and check for each consumer if a more fine grained event would make sense and would be possible. That could come as a second step.

**Comment by bpasero** [comment]
Things pushed:
* extension host created in `running` phase (previously `restored`)
* renamed `onReady` to `whenInstalledExtensionsRegistered`
* introduced a new event `onDidRegisterExtensions` which will fire after the initial extensions are registered as well when we ever enable to enable extensions during runtime without window reload

I was able to replace `whenInstalledExtensionsRegistered` with the event in some places but had to leave it in for other places. When we approach the topic of allowing to enable extensions without window reload we need to basically revisit each place of `whenInstalledExtensionsRegistered` and adopt the event as well.

I did a check of all remaining users of `whenInstalledExtensionsRegistered` and verified that none would block the startup, so I think we should be OK.
