### ISSUE TITLE
File watcher resulting in high CPU use on Mac/Linux for large folders

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3998]
We are using chokidar for file watching. Chokidar is known for performing bad over large folders (see https://github.com/paulmillr/chokidar/issues/410). To investigate:
- can we consume a newer version of chokidar with the scalability issue fixed
- can we change our watching strategy to only watch what we need instead of always watching root
- can we switch to another watching library that is more efficient

**Workaround**:
Find the large folders in your workspace and add them under the `files.watcherExclude` setting

**Comment by paulmillr** [comment]
@bpasero i'll keep an eye on improving the scalability in chokidar to fit into the release. Let me know if you have a specific test repo (with large folders?) to check the performance.

**Comment by bpasero** [comment]
Some good ones are TypeScript (https://github.com/Microsoft/TypeScript) and of course the full Chromium workspace is probably the largest I know: https://chromium.googlesource.com/chromium/src.git

**Comment by paulmillr** [comment]
Just checked TypeScript, it consumes around 80% of one core for ~2 seconds and then it's back to 0%.

Cloning Chromium.

**Comment by paulmillr** [comment]
Although when `useFsEvents` is `false` (non-default option on OSX), the CPU usage becomes terrible.

I'll investigate the new PR in chokidar too.

**Comment by sibeliusseraphini** [comment]
is there some workarounds for now?

I'm using a macbook air with the latest version of vscode

**Comment by bpasero** [comment]
@sibeliusseraphini there is a way to exclude large folders from watching in settings. It has a downside though that file events are no longer detected in those folders (e.g. the explorer might not update properly for that folder).

**Comment by sibeliusseraphini** [comment]
is there a simple way of marking a folder as an excluded one? like in Webstom?

it should also be possible to invalidate the cache/file watching or restart it as well

**Comment by bpasero** [comment]
Currently not. See http://code.visualstudio.com/updates/vMarch#_workbench and find `Exclude files from watching`

**Comment by rob9** [comment]
How does one determine if [this](https://stackoverflow.com/questions/37601936/visual-studio-code-high-cpu) is bug #3998?

**Comment by rob9** [comment]
There are some peculiar statements about file watchers in these github issues: I have used them extensively, they work, so I expect this here for Linux to be some JavaScript problem.

I installed version 1.1.1 likeso:
`sudo dpkg -i vscode-amd64.deb`

If I do:
`sudo nano /usr/share/code/resources/app/node_modules/chokidar/lib/fsevents-handler.js`
and modify line 7 to:
`try { fsevents = require('fsevents'); } catch (error) {fs.writeFileSync('/tmp/y', 'Error: ' + error.stack)}`
then relaunch Visual Studio Code

I get:
```
less /tmp/y
Error: Error: Cannot find module './build/Release/fse'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules/fsevents/fsevents.js:9:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by rob9** [comment]
So that's just the check for OS X, chokidar instead runs fs.watchFile which is correct.

What is the get-around, how does people immediately make it work in a way that is meaningful?

Apparently it's been around since November, 2015.

**Comment by rob9** [comment]
This is a total buggy bug. I have it on two Linux laptops, all of a sudden one is no longer slow. I'll use that one :)

**Comment by bpasero** [comment]
@rob9 is it the same folder you open in both instances and in one it is slow and in the other not?

**Comment by rob9** [comment]
It's several babel projects on two machines.

A project that was initially slow, suddenly is fast and the problem is gone. It seems horrible task triggered by save keeps restarting until something changes, then things are good. In good state a save is less than 3 s of high cpu. On the computer that is now fast, I can't find a slow project anymore, so maybe it's once per installation.

**Comment by shaneparsons** [comment]
I'm not sure what this "file watcher" is, but all I know is using vscode with unity (in place of mono develop) results in a climbing cpu memory usage (electron helper) that becomes unbearable at a point. At that point, restarting vscode temporarily fixes the issue for me.

I'm assuming this bug is related to the issues I'm having.

What exactly does the file watcher do and is there a way to disable it?
Would disabling it be a bad idea?

**Comment by bpasero** [comment]
@shaneparsons the idea for this setting is to ignore watching folders for file changes that contain resources you do not work with (e.g. do not show in the explorer or search in). Taking out large folders from file watching will have a positive impact on performance.

**Comment by hartbit** [comment]
@shaneparsons @bpasero This is also happening with me and we are using VSCode for Unity development. But what is strange is that I never noticed anything before the latest release 1.3, but now its making the editor completely unusable.

**Comment by shaneparsons** [comment]
> @shaneparsons the idea for this setting is to ignore watching folders for file changes that contain resources you do not work with (e.g. do not show in the explorer or search in). Taking out large folders from file watching will have a positive impact on performance.

What's the difference between the `files.exclude` and the `files.watcherExclude`? Are paths listed in the `exclude` needed in the `watcherExclude` as well?

**Comment by LeonsChun** [comment]
I had set the `files.watcherExclude` to exclude the  roof folder of my program. But the CPU also use over 120%.  The IntelliSense  don't show until 10 or more seconds later. I'm using VSCode 1.3.1 for Unity3D.

**Comment by bpasero** [comment]
files.exclude and the files.watcherExclude are separate settings

**Comment by jsturgis** [comment]
It seems like watcherExclude patterns are handled differently than exclude patterns. For example if I have `"tmp": true` in my files.exclude object then the tmp folder does not appear in the explorer but if I add `"tmp": true` to my files.watcherExclude object then it does not exclude the tmp folder from being watched. Only if I change the pattern to `"**/tmp": true` is it excluded from being watched.

**Comment by hheydarii** [comment]
Seems like this a common problem. I justed posted the same question on SO:
[(https://stackoverflow.com/questions/45195683/vs-code-consumes-cpu-cores-like-crazy)]

What's strange is that even after closing VS Code, watcherService is still there unless I kill it!

**Comment by sarbbottam** [comment]
<img width="800" alt="screen shot 2017-09-01 at 10 38 35 pm" src="https://user-images.githubusercontent.com/949380/29993249-879de368-8f66-11e7-9913-aab3f365520f.png">

Looking forward to a fix for the issue.

**Comment by bpasero** [comment]
@sarbbottam this could be any of our processes, please find out the full command args via `ps aux | grep`

**Comment by sarbbottam** [comment]
@bpasero [as shared earlier](https://github.com/Microsoft/vscode/issues/13311#issuecomment-252308313) it is `watcherService`
```
USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
sabandyo         21629 100.0  1.7  3443632 279484   ??  R    11:45PM   2:35.69 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
```
<img width="1285" alt="screen shot 2017-09-01 at 11 49 49 pm" src="https://user-images.githubusercontent.com/949380/29993592-59852e50-8f70-11e7-8dc4-53d6b8da9950.png">

**Comment by bpasero** [comment]
@sarbbottam as a workaround (for everyone here), you can configure `"files.useExperimentalFileWatcher": true` to switch to our new watcher service.

**Comment by ngouy** [comment]
what about this (which appear only when i run vscode): 
![screen shot 2017-09-07 at 11 02 50](https://user-images.githubusercontent.com/12391171/30155077-3102bcb8-93bc-11e7-96fe-b6634be6caa7.png)

**Comment by p-romanski** [comment]
The same happens (high cpu) on Ubuntu 16.04. First, I narrowed down a problem to single directory. In my case: `$HOME/.wine`. Then I found that there is a symbolic link to root directory inside wine directory. 

Here is how I can reproduce the error:

```
$ mkdir loop
$ ln -s / loop/root
$ code loop
```

**Comment by timothysc** [comment]
Same boat as @ngouy even with ```"files.useExperimentalFileWatcher": true``` 

My machine is loaded with 100's of find -L drops.

**Comment by p-romanski** [comment]
What I found is `"files.useExperimentalFileWatcher": true` solves an initial problem of high CPU, but introduces a bug with symbolic link loop (see my comment above)

**Comment by Phillipus** [comment]
Just chiming in here. The "Code Helper" process uses a constant 142% CPU on my Mac if I have my home folder (~) open in Explorer.

Setting "files.useExperimentalFileWatcher": true reduces CPU level to normal.

**Comment by bpasero** [comment]
@p-romanski can you file that link loop as a separate issue, we should forward it to the file watcher library we are using. Best with reproducible steps!

**Comment by bpasero** [comment]
Chokidar is now disabled by default, unless "`files.useExperimentalFileWatcher`" is set to `false` (the default is `true`).

**Comment by sveinse** [comment]
I'm having the same problems on Ubuntu 16.04 with 1.17.2. The /usr/share/code/resources/app/out/bootstrap --type=watcherService thread is consuming 100% CPU and ultimately crashes vscode due to OOM eventually. I've experimented with all permutations of "files.useExperimentalFileWatcher" true and false, and with the "files.watcherExclude" setting, all to no resolvement.

Unfortunately this is a critical bug for me and I cannot use vscode for this project, since it has a large (50Gb+) build output within it. I had to revert to other editors, which is unfortunate.

Is there something I can do to help out to debug or trace to identify the problem?

**Comment by bpasero** [comment]
@sveinse what if you configure this to disable the file watcher for the workspace:

```json
"files.watcherExclude": {
  "**": true
}
```

**Comment by sveinse** [comment]
I tried

```   
    "files.useExperimentalFileWatcher": true,
    "files.watcherExclude": {
        "**": true
    }
```

Then that work if I set useExperimentalFileWatcher to false. If it is true, then it consumes 100% CPU. Likewise if I put anything else in stead of "**", specifically my build output directory, then this consumes 100% CPU regardless of the experimental flag set true or false.

**Comment by bpasero** [comment]
@sveinse how about setting `"files.useExperimentalFileWatcher": false` and the `files.watcherExclude` only to that one large folder you have?

**Comment by sveinse** [comment]
@bpasero, no that does not help. Setting something else than "**" in exlude, will result in 100% CPU regardless of the experimental flag.

**Comment by bpasero** [comment]
@sveinse what did you try to as setting to exclude that large folder?

**Comment by sveinse** [comment]
@bpasero 

```
    "files.useExperimentalFileWatcher": false,
    "files.watcherExclude": {
        "yocto/build/**": true
    }
```

**Comment by bpasero** [comment]
@sveinse I fear that path needs to either be absolute or it needs to start with a "**" too, e.g. `**/yocto/build/**`

**Comment by sveinse** [comment]
That seems to work -- and I see that the help in the settings actually does mention the need for abs. path or "**" prefix in "files.watcherExclude", which I missed. I blindly assumed that "files.exclude" and "files.watcherExclude" used the same file pattern scheme. My bad.

With a proper "files.watcherExclude" pattern, I need to keep "files.useExperimentalFileWatcher" to false to prevent 100% CPU load. Setting it to true will load the CPU full even with proper exclude pattern.

@bpasero: This resolves "my" issue. There is an issue with the new filewatcher and exclude patterns as mentioned above, but you already know that. Since you reopened this issue based on my report, I vote for closing it again.

**Comment by zhelnio** [comment]
For me works only when 
```
"files.useExperimentalFileWatcher": false,
    "files.watcherExclude": {
        "**/big_folder/**": true
    }
```
And only for one folder opened in VSCode  - **not a Workspace**.

I have tried all the filter combinations to make it work in a Workspace mode. No result.
A workaround is not to use a Workspace and to add symlinks(ln -s) to the additional folders into the single opened folder.

**Comment by deepu105** [comment]
I also notice that the CPU/Memory usage is very high when in workspace mode. It even maxed out my 32gig Xeon octa-core with or without the above settings

**Comment by Fusty** [comment]
It would be nice if large folders didn't cause this issue.  Why does vscode need to watch everything?  Why not just watch the open files?

**Comment by TimeBandit** [comment]
I am flagging the issue here as it seems closely related. When VSCode cant find a module that you are requiring it will result it high CPU load instead of a graceful error message. In the screen shot I am requiring individual methods from the 'express-validator' library. Since VSCode cant find it, it seems to go into free-fall and repeatedly throws the same error message as can be seen from the developer view.

![screenshot from 2018-01-09 12-08-02](https://user-images.githubusercontent.com/2059850/34720791-f280df96-f537-11e7-9456-4a4245a124af.png)

It took me a while to figure out what was going on and I considered going back to Sublime Text after two weeks. The editor should be giving a friendly warning not turning my work station into a fan heater :-)

My work around for now is to simply comment out the code and to restart VSCode.

**Comment by TimeBandit** [comment]
I'm raising this issue against the[ 'import-cost'](https://github.com/wix/import-cost/issues/46) extension, you can close it here if you wish.

**Comment by waldemar-p** [comment]
for me this worked for every environment so far:

`"files.watcherExclude": {
  "**/**": true
}`

**Comment by adamcavendish** [comment]
Is there anyway to automatically apply gitignore files to `files.watcherExclude` ??

**Comment by lolmaus** [comment]
> I'm raising this issue against the 'import-cost' extension, you can close it here

I'm not using `import-cost`, yet I see constant 100% CPU core load on `watcherService`, even in safe mode.

**Comment by lolmaus** [comment]
Wow, this issue has been open for two thirds of VSCode existence. I've just realized I'm running into it on my main project. This is a show stopper for me: my laptop only has two CPU cores. :unamused: 

Top post says:

> Workaround: Find the large folders in your workspace and add them under the `files.watcherExclude` setting

But how do I do that?! The only exclusion pattern that worked for me was `"**"`, which is obviously unusable. I tried various other suggestions from this thread and none of them worked.

HALP!

**Comment by lolmaus** [comment]
Sorry, I've realized I have a huge `tmp/` folder in my project. This helped:

```
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/node_modules/**": true,
        "**/tmp/**": true
    }
```

**Comment by youurayy** [comment]
I'm not having any of these issues on Mac on the VSCode Insiders edition anymore (installed yesterday from .dmg). \o/

**Comment by shepting** [comment]
I am seeing quite constant high CPU usage with VSCode as well. The output of `code --status` for me is: 

```
Version:          Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS Version:       Darwin x64 17.5.0
CPUs:             Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)
Memory (System):  24.00GB (1.21GB free)
Load (avg):       4, 5, 8
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_40970

CPU %	Mem MB	   PID	Process
    0	   147	   334	code main
    0	    74	   384	   gpu-process
    0	    98	   449	   shared-process
    0	   319	 20843	   window (BUCK — apps)
    0	    98	 20844	     extensionHost
  218	   516	 20845	     watcherService

Workspace Stats: 
|  Window (BUCK — apps)
|    Folder (apps): more than 20000 files
|      File types: java(7399) xml(6727) js(3190) kt(801) json(444) png(296)
|                  gradle(153) rb(57) class(29) sq(26)
|      Conf files: settings.json(1)
```

**Comment by shepting** [comment]
Is there a way to see the logs from the `watcherService` to see if I could be ignoring any directories thrashing with changes?

**Comment by nchammas** [comment]
I'm seeing this problem too with VS Code 1.25.1 on macOS. I opened `~/` to edit my `.bashrc` and then left VS Code open. It started consuming lots of CPU.

I see that many people are experiencing this same problem and opening duplicate issues.

As a mitigating measure, would it help to somehow detect when the file watcher has been tasked with watching a directory that's too large, and then display a warning to the user? The warning could recommend a course of action and/or point to this issue.

**Comment by bbugh** [comment]
This issue sometimes happens to me when I return from sleep with VS Code open. Most of the time, this large project works totally fine, but then 30% of the time after I wake from sleep, the CPU is thrashing at 100%. Even if I close VSCode and/or kill Code Helper, it stays at 100% until I restart. I don't believe I've seen it happen outside of this scenario.

MacOS 10.12.6, VSCode 1.26.0

**Comment by sashablazhko** [comment]
@bbugh same problem

**Comment by mdrideout** [comment]
Same having this issue
VS Code: Version 1.27.2 (1.27.2)
macOS 10.13.6

**Comment by Honzys** [comment]
Same issue here.

Also I've posted another issue because File Watcher exclude seems not to work. (https://github.com/Microsoft/vscode/issues/61393)

Also I think the problem with File Watcher exclude is that it tries to scan all the files and folders (and after that initial scan it is not being watched). But my question is: Why it doesn't stop scanning when the root folder which the watcher should ignore is reached? I shall note, this is only the assumption (because after 30 minutes the CPU usage dropped down - I guess that it's the time ) since there's no log for watcherService.

This should really be fixed, because a lot of people may have large directories. It's 2 years now.

**Comment by michaelaye** [comment]
Same issue here.
Status:

```bash
$ code --status                                                                                               (py37)

Version:          Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS Version:       Darwin x64 17.7.0
CPUs:             Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)
Memory (System):  16.00GB (0.23GB free)
Load (avg):       6, 7, 7
VM:               0%
Screen Reader:    no
Process Argv:     -psn_0_110619
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
   14	    49	   634	code main
    0	    16	   681	   gpu-process
    0	    16	   731	   window (region_data.py — planet4)
    0	    16	   833	     extensionHost
    0	    16	  1006	       /Users/klay6683/.vscode/extensions/ms-python.python-2018.9.1/languageServer.0.1.42/Microsoft.Python.LanguageServer
    0	    16	   836	     watcherService
    0	    33	   776	   shared-process
    0	    33	  1478	   window (Welcome — planet4)
    0	    16	  1479	     extensionHost
   99	  2277	  1480	     watcherService
```

**Comment by BobrImperator** [comment]
```
"files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/node_modules/**": true,
        "**/tmp/**": true
    }
``` @lolmaus 

Fixed the problem for me,  used to have around ~30% of CPU usage on my laptop, but ever since I added this to config vscode is not even noticeable, lightweight as a feather ;)

**Comment by michaelaye** [comment]
But that would disable git plugins, I guess?

**Comment by dijitali** [comment]
Took me ages to find this issue when I was troubleshooting this so thought I'd mention **Terraform** here to help others.

Most terraform repos use a `.terraform` working directory which can contain a large number of files.  This was affected by this issue and confirmed resolved by adding:
```
"files.watcherExclude": {
    "**/.terraform/**": true
}
```

**Comment by USSliberty** [comment]
@dijitali Thank you! I had the exact same problem with a terraform project.

**Comment by tpihl** [comment]
if have this in my config:
    "files.watcherExclude": {
        "**": true,
    },

And watcherService is currently consuming:
4,8G virtual memory and 50% CPU..

Environment:
lastest vscode
manjaro linux KDE fully updated.

I'm leaving vscode real soon

**Comment by DamengRandom** [comment]
can go to vscode **settings** and found **workspace** and **Files** column and find the **Watcher Exclude** column and click `Add Pattern` button and choose the folder you don't want the vscode to watch

**Comment by TheHunterDog** [comment]
fix known ??

**Comment by matt-potts** [comment]
for me, @BobrImperator's suggestion of adding this text was the key: 

```
"files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/node_modules/**": true,
        "**/tmp/**": true
    }
```

I had already had the first 2 lines. The third line, excluding the tmp directory, immediately dropped the watcher to 49mb, down from almost 1700. Add it in your excludes. It's in the common settings menu for those unaware (cmd+comma).

**Comment by BobrImperator** [comment]
If someone is having a similar problem but with *ripgrep* instead, I had it fixed with this config
```
    "files.exclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/dist/**": true,
        "**/node_modules/**": true,
        "**/tmp/**": true
    },
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/dist/**": true,
        "**/node_modules/**": true,
        "**/tmp/**": true
    },
    "search.exclude": {
        "**/node_modules/**": true,
        "**/bower_components": true,
        "**/dist/**": true,
        "**/tmp/**": true,
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true
    },
```
I didn't notice any problems while coding, the only thing, is that the `node_modules` for example is not in the tree view, so if you want to inspect it, you'll need to manually open another vscode instance in that directory, which for me happened to be a better way to inspect `ember addons`

**Comment by balinterdi** [comment]
@BobrImperator Thank you. What I'm not getting is that having `"**/.git/**` should take care of all of the directories under `.git`, due to how globs work, shouldn't it?

**Comment by BobrImperator** [comment]
You might be right, I'm not sure why I have it configured this way :D

**Comment by zebralight** [comment]
I currently have this setting:
```
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true,
    "**/tmp/**": true
  },
```
but I'm still seeing ~90% of CPU use from lsof in Code.

**Comment by worldomonation** [comment]
Also on MacOS 10.14.6, MBP 2017. `watcherService` is relentless - it just won't stop, been consuming >50% CPU the whole working day at this point.

Given that MacOS users make up a good chunk of developer community...this is a dealbreaker.

**Comment by theferrit32** [comment]
Any time I write files into a workspace directory, the `bootstrap-fork --type=watcherService` is pinned to 100% cpu for the entirety of the time. I often write nontrivially-sized files for testing, so this happens almost every day. If I'm running some code doing file writes, this issue essentially doubles the cpu utilization of the operation.  

Something really needs to be done about this. There is no reason for VSCode to be notified of every single file modification done. It just needs to know "soon enough" that a file modification has happened. Those event notifications can be chunked by some reasonable interval like 500ms. The chunking interval could even be some sort of slow start increasing logistic S function with a cap of like 1 second. Basically, the `watcherService` should ignore rapid consecutive file modifications that occur within a given interval, and instead issue a single batch event after that interval.

**Comment by paulmillr** [comment]
There is an option to extend intervals. What is your operating system?

**Comment by theferrit32** [comment]
@paulmillr that's good to hear, I'm on Linux.  What do I need to change to make the watch interval longer?

**Comment by paulmillr** [comment]
The interval option is named `interval: 500` etc, see https://github.com/paulmillr/chokidar#api

**Comment by ghuser** [comment]
@zebralight It seems that watcher ignore rules stop working (at least on linux) on workspaces with more than one root folder added to the list (left workspace panel). And that is why cpu goes high.

See how to verify using `strace`: https://github.com/microsoft/vscode/issues/59679#issuecomment-555054743

**Comment by cyberfox1** [comment]
This is a ******* joke.

**Comment by jgbradley1** [comment]
> This is a ******* joke.

Not sure what you're referring to exactly but this type of post and language does not help solve the issue.

**Comment by douglasduartetb** [comment]
Aparently this solve to me:
[https://github.com/microsoft/TypeScript/issues/22702#issuecomment-398871461](url)

Disable this option
typescript.disableAutomaticTypeAcquisition

**Comment by noraj** [comment]
I have an ArchLinux VM with 2vCPU and 4GB RAM.
I'm using VSCode 1.42.1.
In this version VSCode has good default values for `files.watcherExclude` and `search.exclude` (using `files.exclude` too).
While idle with VSCode running it's consuming ~4-8% of CPU and 1.20/3.8 GB RAM.
My workdir is 251MB (including node_modules, .git, etc.) and 31MB without node_modules and .git.
But the default settings are not enought, when I launch a search, the whole VM is freezing and it even make the host partially freezing some part of the host UI.

In my version defaults are (for the watcher):

```json
"files.watcherExclude": {
  "**/.git/objects/**": true,
  "**/.git/subtree-cache/**": true,
  "**/node_modules/**": true
}
```

Which seems nice.

But for the search exclude defaults are as follow + inherits from files.exclude

```json
"search.exclude": {
  "**/node_modules": true,
  "**/bower_components": true,
  "**/*.code-search": true
}
```

But it doesn't feel right to me. Why only excluding `"**/node_modules` and not `"**/node_modules/**` like in `files.watcherExclude`? Does it change something? Why not excluding `bower_components` from the watcher too? Why not using `**/.git/**` in the watcher?

Globally another problem of the exclude option is that the path must specified absolutely (from the FS root as I understand it) and can't from the root of the workdir. Why is this a problem? Because you can't specify something like `**/build/**`, you probably want to exclude `/build/**` from the root of many workdirs as it's useless to watch for it or search into it, for many projects it will be in the .gitignore anyway, but a `build` folder may resides in a path you want to watch so the prefix `**/` will be problematic. If the excludes was working from the the root of the workdir instead of the root of the FS it would be possible and easy to use `/build/**`.

**Comment by michaelaye** [comment]
Excluding **/node_modules should not allow any sniffing inside any node_modules folder as they are being ignored?

**Comment by joshcho** [comment]
It seems crazy that this is a persistent issue and not solved. It makes VS Code unusable to me. Is there still not a workaround? Is this something that happens to a certain subset of macs?

**Comment by paulmillr** [comment]
@joshcho if it’s happening on mac for you, could you provide any additional info? Types of projects this happen on, dir structure

**Comment by michaelaye** [comment]
maybe if this helps others, this is my `files.exclude` setting on my Macs and I'm having a good life with vscode:

```json
    "files.exclude": {
        "**/__pycache__": true,
        "**/.cache": true,
        "**/.eggs": true,
        "**/.ipynb_checkpoints": true,
        "**/.mypy_cache": true,
        "**/.pytest_cache": true,
        "**/*.egg-info": true,
        "**/*.feather": true,
        "**/*.parquet*": true,
        "**/*.pyc": true,
        "**/*.zip": true
    },

```

**Comment by joshcho** [comment]
It's good now, I downloaded the insiders edition and it seems I have had the entire home directory watched for the previous edition D:

**Comment by michaelaye** [comment]
but i do think these settings should be default, as nobody wants to edit binary files or caches in VSCode.

**Comment by nyngwang** [comment]
OKOK I'm downloading the insider version, code_helper nice job, thanks.

**Comment by michaelaye** [comment]
I will just mention that I’m NOT running insider on the Mac and still am problem free with above settings.

**Comment by noraj** [comment]
> but i do think these settings should be default, as nobody wants to edit binary files or caches in VSCode.

The issue is that the defaults are already goods but freezing are still happenings.

**Comment by mdmundo** [comment]
For Javascript developers...
Go to 

    /usr/share/code/resources/app/extensions/node_modules

Delete all content. Probably using `sudo rm -f typescript/` (in my case).

**Comment by j-mroz** [comment]
Having same issue.  I was starting code in `~`. Imagine what happened with CPU usage ...
Can you throttle file watcher? No one really wants code to take down whole system.

**Comment by Rafael-Ramblas** [comment]
@douglasduartetb solution worked for me.

**Comment by leidegre** [comment]
I'm trying to understand why VS Code is scanning all my directories, over and over and over again. This polling behavior is just noise on my machine. I want it to stop. How do I disable this?

**Comment by markhicken** [comment]
In my case, this issue was due to switching branches locally so I could pull master to do a rebase. Restarting VS Code fixes the issue immediately for me. Kinda sucky solution, but it works.

**Comment by nuKs** [comment]
This commands provides subfolders' filecount fast.

```bash
find . -type f | cut -d"/" -f2 | uniq -c
```

**Comment by ghuser** [comment]
>  [..] I want it to stop. How do I disable this?

@leidegre [This way](https://github.com/microsoft/vscode/issues/3998#issuecomment-561587767)

**Comment by leidegre** [comment]
> > [..] I want it to stop. How do I disable this?
> 
> @leidegre Use [this workaround](https://github.com/microsoft/vscode/issues/3998#issuecomment-561587767)

Thanks for the tip. Unfortunately I'm mostly on Windows.

**Comment by nuKs** [comment]
> > > [..] I want it to stop. How do I disable this?
> > 
> > 
> > @leidegre Use [this workaround](https://github.com/microsoft/vscode/issues/3998#issuecomment-561587767)
> 
> Thanks for the tip. Unfortunately I'm mostly on Windows.

Try this one https://github.com/microsoft/vscode/issues/3998#issuecomment-341004916

**Comment by richpodraza** [comment]
I have a pretty large workspace (I am just opening my root git folder, with maybe ~30 medium sized projects in it, but they are all related so it's helpful to have them all open). I see CPU usage way up if the workspace is open. I have my workspace settings like this now:

```
{
  "telemetry.enableTelemetry": false,
  "files.watcherExclude": {
    "**": true
  },
}
```

But it doesn't seem to help. Any ideas? Is there a process other than the file watcher that could be involved here? My version info:

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-62-generic snap

**Comment by kf6kjg** [comment]
To me it looks like there are issues with the file watcher actually excluding correctly.  As you can see below it seems to be missing nested `node_modules` even though it should not.  VSCode is maxing out my already raised inotify limit.

Ubuntu 20.04.1 LTS
VSCode 1.53.0, installed as snap package
BTRFS
node v12.19.0
```sh
$ cat /proc/sys/fs/inotify/max_user_watches
524288
$ cat /etc/sysctl.d/60-rwc.conf 
# RWC 20181202: https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
fs.inotify.max_user_instances=256
fs.inotify.max_user_watches=524288
```

Folder opened in a fresh launch of VSCode: `/home/ricky/development/myfolder` - connected to a private repository that I have no rights to share.
Total number of files in that folder:
```sh
$ find -not -type d | wc -l
677481
$ find -not -type d -and -not -path '*/node_modules/*' -and -not -path '*/.git/*' | wc -l
5372
```

Exclusion settings:
```text
# User settings are the defaults, as shown in the GUI:
**/.git/objects/**
**/.git/subtree-cache/**
**/node_modules/**
**/.hg/store/**

# ~/development/myfolder/.vscode/settings.json contains
...
    "files.watcherExclude": {
        "**/.build/**": true,
        "**/.next/**": true,
        "**/dist/**": true
    }
}
# The GUI for Workspace shows the two lists concatenated.
```

Watches opened, as reported by [notify-consumers](https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers):
```
   INOTIFY
   WATCHER
    COUNT     PID USER     COMMAND
--------------------------------------
  363486  3673137 ricky    /snap/code/53/usr/share/code/code --max-old-space-size=3072 /snap/code/53/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/v
  126120     3481 ricky    /usr/bin/baloo_file
   29045  3673201 ricky    /snap/code/53/usr/share/code/code /snap/code/53/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/ricky/.cache/typescript/4.1 --enableTelemetry --typesMapLocation 
    5440  3673062 ricky    /snap/code/53/usr/share/code/code /snap/code/53/usr/share/code/resources/app/out/bootstrap-fork --type=watcherService
      45     3421 ricky    kded5
# list trimmed for brevity's sake.
```

I homebrewed my own little script to list the files watched by the top consumer, note that it's only designed to work on btrfs and has to be run as root:
```sh
$ find /proc/*/fd -lname anon_inode:inotify -printf '%hinfo/%f\n' 2>/dev/null | xargs grep -c '^inotify' | sort -n -t: -k2 -r | head -n1 | cut -d: -f1 | xargs cat | grep '^inotify' | cut -d' ' -f3 | cut -d: -f2 | sed 's/^/0x/' | xargs -l printf "%d\n" | xargs -I '{}' btrfs inspect-internal inode-resolve '{}' /home | less

/home/ricky/development/myfolder/packages/tests/node_modules/yn
/home/ricky/development/myfolder/packages/tests/node_modules/yargs-unparser
/home/ricky/development/myfolder/packages/tests/node_modules/yargs-parser/lib
/home/ricky/development/myfolder/packages/tests/node_modules/yargs-parser
/home/ricky/development/myfolder/packages/tests/node_modules/yargs/node_modules/strip-ansi
/home/ricky/development/myfolder/packages/tests/node_modules/yargs/node_modules/string-width
/home/ricky/development/myfolder/packages/tests/node_modules/yargs/node_modules/ansi-regex
/home/ricky/development/myfolder/packages/tests/node_modules/yargs/node_modules
/home/ricky/development/myfolder/packages/tests/node_modules/yargs/locales
/home/ricky/development/myfolder/packages/tests/node_modules/yargs/lib
/home/ricky/development/myfolder/packages/tests/node_modules/yargs
/home/ricky/development/myfolder/packages/tests/node_modules/y18n
/home/ricky/development/myfolder/packages/tests/node_modules/xdg-basedir
...
```
Yes that script could do with some optimizations, but for a one-off it took me over an hour anyway so meh.

As you can see it looks like nested node_modules folders are inexplicably being watched.  The contents of `/home/ricky/development/myfolder/node_modules` folder is correctly NOT being watched.

I tried adding `"**/node_modules/**": true,` directly to the workspace `.vscode/settings.json` with no effect.

**Comment by haamis** [comment]
Also ran into this issue when writing data to a gzip file, WatcherService uses about 75% CPU (a bit under one logical CPU/core). The file lives under my WSL home directory and I'm using Remote-WSL. Excluding `**/*.gz` (in user, remote and workspace settings) seems to do nothing even after restarting Code.

**Comment by jugmac00** [comment]
I also encountered this problem.

The workaround (files.watcherExclude... ) worked, but is pretty well hidden.

The Jetbrains IDE's have an entry in the context menu when clicking on a folder - maybe that would be a good idea for VS Code, too.

**Comment by electrovir** [comment]
I just had this issue suddenly start yesterday in a 7.3 GB repo despite not having an issue for the past three years. I already have lots of properties within `files.watcherExclude` (hence no issue before), only one root folder, and had no problem until yesterday (May 5, 2021). The process sticks at 100-400% CPU usage.

**Comment by krsinghshubham** [comment]
Why don't we migrate to some other file watcher service other than chokidar. Excluding the folders will hamper the file update processes.

**Comment by ghuser** [comment]
> Why don't we migrate to some other file watcher service other than chokidar. Excluding the folders will hamper the file update processes.

By debugging vscode's file-watcher code in the past I came to conclusion that [this is what cases the problem](https://github.com/Axosoft/nsfw/issues/101). 
I think it would worth it for microsoft forking that project and providing that feature, in order to avoid all that code refactoring.

**Comment by doubledgedboard** [comment]
ran into this issue on a golang project with some recursive symlink folders inside it (my mac got VERY hot, which I guess was a good thing since I knew something was wrong)

Adding the paths to `files.watcherExclude` helped, but it was a very non-obvious fix that only surfaced after extensive googling of CPU usage, finding the Process Explorer, and confirming the watcherService as the culprit

Version: 1.57.1
OS: Darwin x64 19.6.0

**Comment by karrtikr** [comment]
Can we detect if it's a large folder, and decide whether we want to enable watcher accordingly?

**Comment by A-Sam** [comment]
The ```"files.watcherExclude"``` doesn't work. A huge repo is constantly stuck at 100% all cpus even if i disabled everything:
```"files.watcherExclude": {"**/**" : true}```. Any other workarounds?

**Comment by valhuber** [comment]
Version: 1.62.0-insider (Universal)  
Commit: e96a974  
Date: 2021-10-11T05:14:31.072Z  
Electron: 13.5.1  
Chrome: 91.0.4472.164  
Node.js: 14.16.0  
V8: 9.1.269.39-electron.0  
OS: Darwin x64 20.6.0

Not sure if this is the "tomorrow's build", but just downloaded and seeing this"

![](https://user-images.githubusercontent.com/5579631/136873037-97318626-9845-43a6-a7b4-89e768beb19e.png)

**Comment by A-Sam** [comment]
Tested the master on Linux and this problem doesn't exist anymore.

Thanks @bpasero  and the devs for the efforts it was a real headache to kill it upon every startup.
