### ISSUE TITLE
Custom view (TreeDataProvider) broken in 1.19.0

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#40357]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299

I updated to 1.19.0 on several systems (all Windows) and on all of them my extension https://github.com/letmaik/vscode-git-tree-compare suddenly doesn't work anymore and I see a weird error in the console log:
```
  ERR Please return an array of children.: Error: Please return an array of children.
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:299:343
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:139:729)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:143:568)
...
```
I couldn't find anything in the changelog which was related to breaking changes related to views.
The error message seems to come from https://github.com/Microsoft/vscode/blob/23affbd2b825e0782fc5e6c6a93db47db5511d49/src/vs/base/parts/tree/browser/treeModel.ts#L475 which calls the `getChildren()` method of the provider, but I always return an array, so I'm a bit confused what's going on. I'm also not sure how to debug directly into VS Code source code like `treeModel.ts`, which would help analyze this problem.

**Comment by sandy081** [comment]
@letmaik Is it possible to provide a sample that can reproduce this issue? It will be helpful to diagnose the issue correctly rather than doing some guess works.

**Comment by letmaik** [comment]
Extracting a minimal example will take some effort (I can do it but currently I'm quite busy), I was hoping you guys have some debugger kung fu which would expose the root of the exception easily. In the mean time I was trying to debug the exception under a source-built VS Code (and then simply loading my extension into it via a .vsix file), but I got stuck at the boundary of some extension host proxy for the tree view. Let me know if you'd still like a minimal example, then I'll try to create one within the next weeks.

**Comment by sandy081** [comment]
@letmaik This error can happen due to various reasons. I also have couple of variety of examples which cannot reproduce this. Hence, asking for the sample.

**Comment by mike-lischke** [comment]
I also get that error. I have a tree provider that is refreshed whenever the active editor changes and shows only for certain file types. This is the relevant code:

```
    getChildren(element?: Import): Thenable<Import[]> {
        if (!element) {
            let editor = window.activeTextEditor;
            if (editor && editor.document.languageId === "antlr") {
                let dependencies = this.backend.getDependencies(editor.document.fileName);
                let imports: Import[] = [];
                for (let dep of dependencies) {
                    imports.push(new Import(dep, TreeItemCollapsibleState.None));
                }
                return new Promise(resolve => {
                    resolve(imports);
                });
            }
        }

        return Promise.resolve([]);
    }
```

It all works nicely until the line `return Promise.resolve([]);` is executed (usually for a file with a language id I don't want). From this moment on, switching from such a file to one of the handled types gives me the mentioned error. Switching between the handled types has no such effect.

**Comment by sandy081** [comment]
@mike-lischke Thanks for the snippet. I will use it to reproduce and fix it.

**Comment by anikolaienko** [comment]
Hey guys,

I believe I have the same error on typescript files.
Here is the screenshot of what callstack I found:
<img width="805" alt="screen shot 2018-01-13 at 8 54 49 pm" src="https://user-images.githubusercontent.com/5848010/34909211-1736768c-f8a5-11e7-875b-afba34b28a1e.png">

Not much, but the issue desapeared when I turned off 'TypeScript Hero' extension. HTH.

**Comment by sandy081** [comment]
@letmaik @mike-lischke Unfortunately, I could not reproduce this bug with any of the tree samples I have, even after using the partial sample from @mike-lischke

I pushed an hypothetical fix which will be available in tomorrows insiders. Can you please verify your issue using that?

Thanks

**Comment by letmaik** [comment]
@sandy081 I just pulled from master and ran vs code from there, it's fixed :) If you want to figure out why it's fixed you could install my extension https://github.com/letmaik/vscode-git-tree-compare and see what the behaviour is in the last vs code release vs master (look at the console where an exception will be if you open a git managed folder)

**Comment by sandy081** [comment]
Thanks @letmaik

**Comment by letmaik** [comment]
I think this bug is not fully solved and your fix only hides the problem. I see the same behaviour as back then. Like in the past this issue appears randomly and not always, but it's quite reproducible.

**Comment by sandy081** [comment]
@letmaik Can you please provide steps to reproduce?

**Comment by letmaik** [comment]
Yes, it's not minimal but it's very suitable for debugging:
- Clone the debug-issue40357 branch of https://github.com/letmaik/vscode-git-tree-compare
- Run `npm install` and then run the extension with F5 in vs code
- You will see log output in the debugging console for each call to `getChildren` and `getTreeItem` including the returned values. You will see that in all cases `getChildren` returns a non-array and you will see there is a corresponding number of `getTreeItem` calls following that, again with the correct content.
- If things work correctly, you see at least one tree item, otherwise none.

**Comment by sandy081** [comment]
@letmaik  Thanks for the steps. Since this issue was closed, opened a new issue with the steps described by you.
