### ISSUE TITLE
`files.watcherExclude` setting cannot apply on `nfsw` watcher

### ISSUE THREAD

**Issue by dmnrmr** [microsoft/vscode#40898]
Initial problem is that `npm install` takes twice as long to install dependencies when vscode is running. I've figured out that this is because of file watching for `node_modules` folder so I added it to `files.watcherExclude`. I uses following combinations (but non of them seems to be working):

```
"files.watcherExclude": {
        "**/node_modules": true,
        "**/node_modules/**": true,
        "**/node_modules/*/**": true
    }
```

During `rm -rf node_modules` I notice that `watcherService` is having some load:

![image](https://user-images.githubusercontent.com/7805266/34410882-ddf835c0-ebdb-11e7-9940-dfbd9728080f.png)

- VSCode Version: 1.19
- OS Version: Windows 10

Steps to Reproduce:

1. Add any folder to `watcherExclude` list
2. Perform any operation on said folder (i.e. delete it)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@dmnrmr are you inside a multi-folder workspace or single folder?

**Comment by dmnrmr** [comment]
A multi-folder workspace.

**Comment by lolmaus** [comment]
I'm running into #3998. It suggests manually excluding large folders as a workaround.

The only "large folder" in my project is `node_modules/`. It should be excluded by default, but I try to manually exclude it anyway -- and it won't work.

The only exclusion pattern that works around #3998 for me is `"**"`. How do I properly exclude a folder in a project? :scream: 

PS Single-folder workspace.

**Comment by lolmaus** [comment]
Sorry, I've realized I have a huge `tmp/` folder in my project. This helped:

```
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/node_modules/**": true,
        "**/tmp/**": true
    }
```

**Comment by languitar** [comment]
Facing the same issue with a `.tox` folder for a python project. No way to make the exclude pattern work.

**Comment by jmonster** [comment]
I'm observing this in both a single and double folder workspace and can reproduce it by trashing my node_modules or dist or tmp folders (all containing an enormous number of files)

![image](https://user-images.githubusercontent.com/368767/41924962-21d321b6-7920-11e8-9029-03cf4b3a2ee7.png)

**Comment by anishmittal2020** [comment]
@bpasero Facing the same issue. How to successfully exclude `node_modules` from watch list?

**Comment by dotnetCarpenter** [comment]
If anyone is up for fixing this, here is a good overview of which files that needs to be debugged: https://github.com/Microsoft/vscode/search?q=%22files.watcherExclude%22&unscoped_q=%22files.watcherExclude%22

The glob patterns seems to be the culprit - e.i. they do not match the correct paths.

**Comment by bpasero** [comment]
Is this still happening?

**Comment by dmnrmr** [comment]
Looks like this is no longer a problem.

**Comment by woytowg** [comment]
This is still happening for me, was there a fix, what version?

**Comment by nickisaacs** [comment]
Still happening for me as well.

**Comment by plhosk** [comment]
I ran into a similar issue when working on a React Native project on Linux. It turned out that React Native process was overloading the file handles. I increased the file handles limit in Linux and the problem went away.

**Comment by dotnetCarpenter** [comment]
@bpasero I have just checked in vscode 1.28.1 and it is still happening.

Please verify that an issue is fixed before closing it.

MAX file watches allowed on system: **8192**
Current files in project - excluding node_modules: **213**
Current files in project - including node_modules: **26472**

Using the following from #45295 
```bash
echo "MAX file watches allowed on system"
cat /proc/sys/fs/inotify/max_user_watches

echo "Current files in project - excluding node_modules"
find . -type f -not -path '**/node_modules/**' | wc -l

echo "Current files in project - including node_modules"
find . -type f | wc -l
```

I'm on Linux Mint 19 Tara.

**Comment by Zenwalkerd** [comment]
Hi all,
I am also facing the same issue on the latest version. 
Tweaked the sysctl.conf and also modified settings.json file too as said above. 
Fingers crossed.

PS: Zenwalk linux

**Comment by dotnetCarpenter** [comment]
@Tyriar What info do you need?

**Comment by woytowg** [comment]
I tried the sysctl settings from plhosk, no luck.
PS: Ubuntu 18.04 linux

**Comment by Zenwalkerd** [comment]
> 
> 
> Hi all,
> I am also facing the same issue on the latest version.
> Tweaked the sysctl.conf and also modified settings.json file too as said above.
> Fingers crossed.
> 
> PS: Zenwalk linux

Update from my side:
After a while, things start to work better. I am not getting this pop notification anymore. The VS Code is also scanning all the required file watches. 
However,  i am noticing a bit of spike in CPU and memory usage of VSCode itself on my Linux box.

I shall investigate more and make some screenshot available if it keeps spiking up.

**Comment by ayuzvyak** [comment]
I am experiencing the same problem with watcherExclude configuration. It simply does not work at all on Linux platform (Archlinux in my case). I've tried a dozens of patterns, even "**/**" does not seems to work.

In my case project building causing frequent updates of shaded .jar file while third-party dependencies being included into that .jar. Watching of that single .jar file (with final size of 65MB) increasing Memory consumption by Watcher Service to 700 MB. The whole build process with multiple similar modules making Watcher Service to consume 5Gb of RAM just because of watching shaded JARs. Adding "**/.jar" or "**/target/**" rule to watcherExclude should solve the problem, but since it doesn't work I had to close the VS Code while building using external tools (instead of Maven for Java extension) every time to prevent huge memory leak.

Can someone from the developers finally take a look into Watcher Service and confirm that watcherExclude configuration works correctly or not in Linux or other unix-like environment and fix it if necessary?

**Comment by PD-Extron** [comment]
I am also having issues with watcherExclude on VSCode v1.28.2.  It doesn't work at all.  Currently the virtual memory (VIRT column in htop) for the watcherService is 62 GB (I've seen it go to 254 GB) and the RSS is 165 MB and growing.  I've also tried different pattern combinations but it doesn't make a difference.  I've added patterns at both the workspace and folder levels and it still doesn't work.

You can use the following to look at the inotify handles that VS code uses to implement the watcherService:

# ps aux | grep watcherService
(in my case the PID is 86221)
# cd /proc/86221/fdinfo
# ls -al ../fd | grep inotify
(I get back file descriptors 43 45 46 47 48 and 51)
# cat 43 45 46 47 48 51 | wc -l
( this returns a total count of 27,200 on my system)
# cat 43 45 46 47 48 51
(lists all of them with more details)
inotify wd:a38 ino:163e2a sdev:800001 mask:7c6 ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:2a3e1600365b5934
inotify wd:a37 ino:163e29 sdev:800001 mask:7c6 ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:293e1600355b5934
inotify wd:a36 ino:163e23 sdev:800001 mask:7c6 ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:233e16002f5b5934
...
# find / -inum $((16#163e2a))
/path/to/some/folder
(shows which folder the particular inotify handle refers to - on my system it shows thousands of folders that are supposed to be excluded)

I hope someone is working on a fix for this.

**Comment by dotnetCarpenter** [comment]
@bpasero It too bad but this renders vscode useless on linux. I've been trying out Atom for some days now and haven't had an issue. So I will move to Atom.

If you are seeing a drop in linux users, I would contribute it to mainly these two issues, #40898 and #45295. Make sure you get around to look at these two issues, soon, if you care about linux users.

**Comment by bpasero** [comment]
I have updated the summary, the issue only exists if you are inside a multi-root workspace or when `"files.useExperimentalFileWatcher": true` is configured.

Revisiting our file watcher is something we have to plan for and can never be just a simple fix. I already talked to @egamma to put this on our 6 month roadmap.

**Comment by dotnetCarpenter** [comment]
Thanks for the info @bpasero. I will try to set `"files.useExperimentalFileWatcher": false` and see if that helps. I'm not using a multi-root workspace.

**Comment by woytowg** [comment]
I'm using multi-root with `"files.useExperimentalFileWatcher": false` on linux.
6 months is a long time, is there any workaround?
Has this always been broken in linux? 
Can I revert to an older version where the file watcher works in linux?

**Comment by bpasero** [comment]
@dotnetCarpenter @woytowg sorry for not being clear, this setting is ignored in a multi-root workspace. In there we have one file watching solution and that one unfortunately does not respect our exclude setting.

**Comment by theagilecoder** [comment]
Just here to confirm I am also facing the same issue on VS Code 1.28.2 and Ubuntu 18.04.1 with `"files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true
  }`
and `"files.useExperimentalFileWatcher": false` 
![screenshot from 2018-10-31 19-04-31](https://user-images.githubusercontent.com/5019222/47791524-edf90c00-dd3f-11e8-8bb1-5734a72fed6d.png)

**Comment by bpasero** [comment]
@theagilecoder I tried that scenario (opened a single folder with large `node_modules` folder) and was not able to reproduce that behaviour. I saw the notification popup as soon as I included the `node_modules` folder.

**Comment by dotnetCarpenter** [comment]
@woytowg, no it hasn't always been broken, but it has been broken for a very long time. From the top of my head, I would say 1 year.

**Comment by felipebraga** [comment]
The same here. Workspace e multi folders, f*ck node_modules

Manjaro 18

**Comment by ZenwalkerD** [comment]
> 
> 
> @bpasero It too bad but this renders vscode useless on linux. I've been trying out Atom for some days now and haven't had an issue. So I will move to Atom.
> 
> If you are seeing a drop in linux users, I would contribute it to mainly these two issues, #40898 and #45295. Make sure you get around to look at these two issues, soon, if you care about linux users.
Same here too. I as well moved to Atom. However, to my disappointment, its intellisense for Typescript isnt as good as VSCode.

Mean while, i have downloaded the insider version 1.30. Lemme check the same behavior on that.

**Comment by woytowg** [comment]
A very sub-optimal workaround is to not use multi-root (ie. separate window for each folder) and set "files.useExperimentalFileWatcher": false, then problem does not occur.

**Comment by ayuzvyak** [comment]
@bpasero Sorry, but why would you think that it's related with multi-root workspace? I have single root folder in my workspace and still experiencing this problem. And there are another two people above commented that it's reproducible in a single-root workspace.

**Comment by bpasero** [comment]
@ayuzvyak because I cannot reproduce the issue in single folder workspace. Can you give me details about:
* your OS
* the folder you have opened (e.g. give me the github URL to clone)
* your settings
* the version of VSCode you are using
* under which condition you see a file event happening when you do not expect it

**Comment by 7654098** [comment]
It's seems to me that the problem with "Code Helper 100% CPU" will never be resolved by Microsoft? Hey, it's 2019 now. Are you still not able to reproduce the isuues? Terrible work, terrible company like always (((

**Comment by steve28** [comment]
I am getting the same issue on a Mac.  I have a workspace with a folder in it.  I add the folder to the files.watcherExclude list and "touching" the folder causes a File Watcher event:

![](https://thumbs.gfycat.com/PitifulPortlyComet-size_restricted.gif)

**Comment by dotnetCarpenter** [comment]
I have never used multi-root workspace and I have this issue. Turning off experimental watcher worked for me but I didn't add any custom folder as @steve28 did. So this will apparently not work for everyone.

**Comment by steve28** [comment]
I should point out that I do not use multi-home workspace either - I simply have a folder with some files in it, which are being written to while I'm editing in VSCode.  I'm trying to get VS code to ignore them and not trigger constant git activity

**Comment by felipebraga** [comment]
@dotnetCarpenter which plataform are you using?

**Comment by dotnetCarpenter** [comment]
@felipebraga https://github.com/Microsoft/vscode/issues/40898#issuecomment-429573101

> I'm on Linux Mint 19 Tara.

**Comment by DavidA2014** [comment]
files.watcherExclude is not working for me in a multi-root workspace in VS Code 1.36 on Centos 7.  Any progress on this issue?

**Comment by felipebraga** [comment]
I'm having a similar issue about it.

1.36 :sleeping:

**Comment by kakenbok** [comment]
Seems to still not work these years. I tried to fix by myself, but i don't have any PHP executable on my Windows machine. As a clever workaround I meanwhile stopped working on larger projects with more than 20 files included.

**Comment by dotnetCarpenter** [comment]
@kakenbok 😄 What does PHP now have to do with vscode?

**Comment by ghuser** [comment]
A workaround for completely disabling watcher functionality on vscode.

startcode.sh:

    #!/bin/bash
    #skipping inotify_add_watch syscall, without caller noticing (return 0)
    (strace -f -e inject=inotify_add_watch:retval=0 -etrace=inotify_add_watch /path/to/code 2>&1) > /dev/null

**Comment by NicolasGoeddel** [comment]
We are running VSCode on a Windows machine but are working through SSH on a Linux machine. It seems we've got the same issue here. vscode runs it own server process on the machine and it seems that it also tries to watch for file changes everywhere so the max inotify watches maxes out on the whole machine.
I have to dig a bit deeper in this but it looks like a similar issue to me.

**Comment by zyron1x** [comment]
I find it very strange that this issue has not been addressed in over 3 years.

**Comment by kakenbok** [comment]
Please stop at least watching .git node_modules vendor :D

**Comment by ghuser** [comment]
Some light on the issue:
 
If the workspace has one root directory this watcher service is used: `FileWatcher` ( [watcherService.ts](https://github.com/microsoft/vscode/blob/1.42.1/src/vs/platform/files/node/watcher/nodejs/watcherService.ts) ) which uses node `fs.watch` and (the way it is called) seems to respect watch exclusions.

If the workspace has more that one root directories, this watcher service is used: `NsfwWatcherService` ( [nsfwWatcherService.ts](https://github.com/microsoft/vscode/blob/1.42.1/src/vs/platform/files/node/watcher/nsfw/nsfwWatcherService.ts) ) which uses [nsfw](https://github.com/Axosoft/nsfw) and does not respect watch exclusions. It just filters-out (does not deliver) the events produced by watching all workspace root directories, based on the watch exclusion list.

The decision of which watch service to use is taken in [diskFileSystemProvider.ts](https://github.com/microsoft/vscode/blob/1.42.1/src/vs/platform/files/node/diskFileSystemProvider.ts#L499)

**Comment by jsonsystems** [comment]
I've seen a number of comments in https://github.com/microsoft/vscode/issues/59679 from people experiencing this issue with only one root directory in the workspace.

On my Linux machine my project was in `~/projects/foo` and my `.workspace` file was `~/projects/foo/foo.workspace`. I.e. the workspace file was within my project. I did this so I could easily add the `.workspace` file to my repo.

Thus `cat ~/projects/foo/foo.workspace` yielded:

```json
{
        "folders": [
                {
                        "path": "."
                }
        ],
        "settings": {}
}
```

Despite only haivng one root directory, VSCode was NOT honoring the **Exclusion Patterns** setting. 

By moving the `.workspace` file outside (above) the project folder, to `~/projects/foo.workspace` the contents changed to:
```json
{
        "folders": [
                {
                        "path": "foo"
                }
        ],
        "settings": {}
}
```

VSCode now seems to be honoring the **Exclusion Patterns** setting,

**Comment by kapalkat** [comment]
This problem is also affecting my work. 
I have multi-root workspace.
OS - Windows 10 Pro KB4550945
VSCode: 1.44.2
Nothing is working for me:
using regex global user/workspace settings:
**/node_modules/*/**
**/node_modules/**
or full paths
The biggest problem is when I run npm install and all node_modules are installed; VSCode just hangs and eventually runs out of memory.

**Comment by beltaurus** [comment]
I have not been able to reduce the number of files in my multi-root workspace either...
A quick question:
In my  settings, for `files.watcherExclude`:
1. Does the `true` or `false` have any priority? If I exclude everything with a `true` setting, can I re-enable a subset with a `false` setting:
```json
"**/{*.pl,*.pm}" = true,
"**/ENABLE/{*.pl,*.pm}" = false
```

I haven't found any documentation at all on the impact of `true` or `false` on these settings...

2. I have been trying the same objective (only enable files in a directory that has `ENABLE` as a path segment) as follows:
```
"**/!ENABLE/**": true
```
In reality that should filter my workspace down to just a few files... But I'm still getting:
![image](https://user-images.githubusercontent.com/54114043/81984308-78832280-95e9-11ea-872a-cf82e5240c59.png)

**Comment by n8henrie** [comment]
> By moving the `.workspace` file outside (above) the project folder
> ...
> VSCode now seems to be honoring the **Exclusion Patterns** setting.

This also solved my (basically identical) issue of VSCode not honoring my excludes.

**Comment by okomarov** [comment]
In my **solution**, the Watcher Exclude settings are respected. Use absolute paths to the workspace folders in the `*.code-workspace` file.  

---

I Remote-SSH into Linux from Windows. Opened my `main` folder, and added a `secondary` one to the workspace. Saved the workspace under `main/.vscode`. 

So my **folder structure** is:
```
.
/main
    /.vscode/workspace.code-workspace
/secondary
```

And the `workspace.code-workspace`:
```
{
	"folders": [
		{
			"path": ".."
		},
		{
			"path": "../../secondary"
		}
	],
	"settings": {}
}
```
Notice the relative paths. 

And this is the amount of watches (info redacted to fit, I am using [this utility](https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers)):
```
   INOTIFY
   WATCHER
    COUNT     PID     CMD
----------------------------------------
   17892    12441  /home/vagrant/.vscode-server/bin/...
    9203    12441  /home/vagrant/.vscode-server/bin/...
       5     5560  /home/vagrant/.vscode-server/bin/...
       4    12327  /home/vagrant/.vscode-server/bin/...
```

Then **changing the workspace folder paths** to:
```
{
	"folders": [
		{
			"path": "/main"
		},
		{
			"path": "/secondary"
		}
	],
	"settings": {}
}
```
fixes the issue:
```
   INOTIFY
   WATCHER
    COUNT     PID     CMD
----------------------------------------
    9203    12894  /home/vagrant/.vscode-server/bin/...
       84     5560  /home/vagrant/.vscode-server/bin/...
       49    12883  /home/vagrant/.vscode-server/bin/...
       0    12894  /home/vagrant/.vscode-server/bin/...
```
Note that 9k is roughly the number of watches in my secondary folder.

**Comment by doraeric** [comment]
I tried to reproduce it with minimal setup. Here's the example.
[electron-quick-start.zip](https://github.com/microsoft/vscode/files/4943874/electron-quick-start.zip)

After downloading it, run these scripts
```sh
unzip electron-quick-start.zip
cd electron-quick-start/hello-world/
npx yarn install
cd ..
npm i
npx electron-rebuild
npm start
```
After the electron hello world appears, run the command in another terminal
```sh
curl -s https://raw.githubusercontent.com/fatso83/dotfiles/master/utils/scripts/inotify-consumers | sh
```

You can see electron uses over 5000 inotify, like vscode.
According to the [code](https://github.com/microsoft/vscode/blob/6c21258b65/src/vs/platform/files/node/watcher/nsfw/nsfwWatcherService.ts#L107), to my understanding, vscode use nsfw to watch the given path in multi-root workspace mode, and **files in exclude paths are watched**.
When the system reports file change, vscode checks whether the file is in exclude paths, if it is then do nothing.

So I think it's a wrong implement in vscode? It should not watch the whole directory.

**Comment by ghuser** [comment]
@doraeric 

>  vscode use nsfw to watch the given path in multi-root workspace mode, and files in exclude paths are watched

I agree, this is because they try to support windows/linux/mac file-watching into one single piece of code, which is tricky.

I've also analyzed it [above](https://github.com/microsoft/vscode/issues/40898#issuecomment-596641681),
and added a [feature request](https://github.com/Axosoft/nsfw/issues/101) on `nsfw`, because I doubt `nsfw` will be replaced soon.

By looking the [file-watcher label](https://github.com/microsoft/vscode/issues?q=label%3Afile-watcher+is%3Aclosed) history it seems like the team doesn't want to mess with file-watcher code (I can understand, it may be too risky). Most of the issues are closed without any fix.

**Comment by lantanios** [comment]
Is there any update on this issue?
I have:
**Ubuntu 20.04.1 LTS 64-bit;**
**VS Code 1.51.1**
I don't have **multi-root** workspace.
cat /proc/sys/fs/inotify/max_user_watches = **65536**

I have only 270 files outside node_modules and don't want/need to increase watches.

And I am getting tons of messages like this:
Error from chokidar (/home/testProject/node_modules/@material-ui/icons): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/testProject/node_modules/@material-ui/icons/ZoomOutTwoTone.d.ts'
Error from chokidar (/home/testProject/node_modules/@material-ui/icons): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/testProject/node_modules/@material-ui/icons/ZoomOutTwoTone.js'
Error from chokidar (/home/testProject/node_modules/@material-ui/icons): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/testProject/node_modules/@material-ui/icons/index.d.ts'
Error from chokidar (/home/testProject/node_modules/@material-ui/icons): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/testProject/node_modules/@material-ui/icons/index.js'
Error from chokidar (/home/testProject/node_modules/@material-ui/icons): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/testProject/node_modules/@material-ui/icons/package.json'

**Comment by ghuser** [comment]
@lantanios 

Use [this script](https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers) to see the exact number of watches that is allocated by each process in your system. This will help you provide a more specific feedback. Sometimes it may be another app that causes the issue.

**Comment by peyloride** [comment]
I have same issue on Fedora 33

**Comment by felipebraga** [comment]
Why this still an issue?

**Comment by lantanios** [comment]
It's a punishment from Microsoft for using Linux. My vs code is watching for 48.000 files instead of 300.
To hard to implement a way to exclude node_modules folder, lol.

**Comment by arthurep** [comment]
This is beyond frustrating for Linux users..

**Comment by woytowgme2** [comment]
FWIW - what I have been doing to work around this linux issue for the last few YEARS is not use multi-root at all.
I create a top level directory, put my multiple working copies under that directory, and then "File->Open Folder" on
the top level directory. You don't get all the benefits of multi-root, but you get something "close enough" that
lets you actually get some work done without having all the system resources of your PC used up by your editor :-).

**Comment by oof2win2** [comment]
Welp, at least I'm not the only one who has this issue...

**Comment by cha0s** [comment]
This is still a thing and it's really really bad.

My situation: Not only do I have a multi-root workspace, each one of those multiple roots is a monorepo with roughly a dozen projects, all with their own node_modules inside of them (as well as one for the monorepo). You can imagine that this little inconvenience has blow up into a full-fledged catastrophe given this environment. It's very painful right now!

Even `**` exclude pattern does nothing.

**Comment by cha0s** [comment]
Also the real kicker is that my projects have been `yarn link`ed together and each link of each project to each other are ALL getting traversed in vscode's pathological never-ending search of stupid things to watch in `node_modules` against all command to the contrary. Really sucks!

**Comment by dirkfeytons** [comment]
I also bumped into this issue and while investigating this (before I found this github issue) I created a little piece of code to see which inotify watches are actually being created to confirm whether my watcher excludes were being used or not.
Some might find this helpful so I created a gist for it: https://gist.github.com/dirkfeytons/bf0acb8fe9888dafb1e6635b9de341ed

**Comment by ghuser** [comment]
@oof2win2 What I remeber from the last time I debugged the code was that (at least on linux) if you remove the other workspaces and keep only one, vscode will keep running with the multi-workspace watcher (which has the issue) until you restart it (with 1 workspace), where another watcher is used (non-buggy).

**Comment by oof2win2** [comment]
yup @ghuser, works according to my testing. very annoying that I cant use multi-folder workspaces though. thanks!

**Comment by levnach** [comment]
I was getting the error even in a single folder. However the error had gone away after I created a workspace in this folder.

**Comment by cha0s** [comment]
This is still incredibly bad to the point where I am starting to consider migrating to another IDE on Linux.

For reference, vscode is using over 500,000 watchers to watch a single workspace with 3 monorepos in it.

owncloud is using ~4200 to watch all those files in t he vscode workspace, plus another half dozen monorepos as well as other projects, and a multitude of unrelated other files being synchronized.

This is becoming a show-stopping bug.

**Comment by lgatibel** [comment]
Hello guys i was able to fix the problem, i don't know the real cause and why Vscode perform this check for the error but i did the known fix on the **remote server** and on my **local machine**:

- Add this `fs.inotify.max_user_watches=524288` to /etc/sysctl.conf
- Reload the configuration: `sudo syctl -p`
- Close and reopen Vscode

After that i didn't have the error again!

**Comment by ghuser** [comment]
Finally a light at the end of the tunnel: https://github.com/microsoft/vscode/issues/132483#issuecomment-925585026
