### ISSUE TITLE
Code occasionally connects to the same git repo twice.

### ISSUE THREAD

**Issue by ugam44** [Microsoft/vscode#40923]
- VSCode Version: 1.19.1
- OS Version: Windows 7 Enterprise 64-bit

Steps to Reproduce:

1. Open a project attached to a git repo
2. Make a few edits to files
3. Refresh source control tab with changes
4. Randomness Magic???
5. See duplicate connections to the same repo
6. Right click & close repository
7. Second instance of repo opens automatically

Only thing that solves the issue is to close VSCode and reopen it. However, this is only temporary solution. 

Some information that might be helpful:

- The project I am connecting to is on a VM - not local to my computer. (i.e. //ip.address/path/to/source/project )

- I am SSH'd into the VM via git bash in the integrated terminal.  

- I have separate RSA public keys on my local machine as well as on my VM, both are registered with my git account.

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/11214911/34425938-9e3dd15c-ebee-11e7-9da1-fb9ce97d0456.png)

#   Update:
It seems like I can reproduce the issue fairly regularly by:

1. Connecting to a project on git via Code
2. Close Code & reboot system
3. Reopen Code (git should still be connected)
4. Make edits to a file that is not already under edit
5. Save the changes
6. Git will now show 2 instances of the same git repo in the Source Control tab

This happens regardless of whether I am SSH'd in via the terminal or not. My editor settings have `"git.autofetch": true` and `"git.autorefresh": true`. I tried disabling both and it seems to have fixed it, although this issue has been randomly occurring, so it is hard to tell if it's actually fixed or not. If it did fix it, I guess it narrows it down to the autofetch or autorefresh settings, though.

**Comment by ugam44** [comment]
@joaomoreno Used insider release the entire work day today, never saw the issue. Usually pops up in the first 10-20 minutes of development, so it appears to have been resolved by something in that release? I will continue to use the insider release and update if I see the issue appear. Thanks

**Comment by joaomoreno** [comment]
Alright cool. I'll leave it open. It if comes back in the Insider release let me know.

**Comment by ugam44** [comment]
@joaomoreno Haven't seen the issue after several full work days. I think it may be safe to close now. I'm curious as to what change would have fixed the issue, though. Do you think it could have been just a corrupted install, or is it possible there is a legitimate bug? I have not found anyone else with the same issue I experienced.

**Comment by fishstick22** [comment]
I'm seeing this issue very occasionally running 1.19.0 on win7 64 with my github repo.
after a commit and push one of the two repos still shows unstaged changes.
close code, git fetch origin, git status shows everything in sync
restart code and now it looks right, only one provider and no changes pending

**Comment by joaomoreno** [comment]
@ugam44 There were quite some code changes in this area since 1.19, so they could've fixed it.
