### ISSUE TITLE
Heterogeneous DPI support on Linux

### ISSUE THREAD

**Issue by mzabaluev** [Microsoft/vscode#41345]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.14.11-300.fc27.x86_64

Steps to Reproduce:

1. A Wayland desktop session on a multi-display setup with heterogeneous DPI scaling. Mine is a HiDPI laptop display scaled at 200% and an external monitor using 100% scaling, resulting in xwayland scaled at 100% on all displays. gnome-shell is the compositor.
2. Launch Visual Studio Code.
3. Move the IDE window between the displays.

Like any other X11 application, Visual Studio Code cannot adapt to heterogeneous scaling.
Wayland support, discussed in #1739, is needed to enable this. I feel that opening a new issue is justified by the problem described, which was not mentioned by the commenters on that issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jhasse** [comment]
Does Chromium support this?

**Comment by mzabaluev** [comment]
> Does Chromium support this?

As much as I could find, there have been some efforts last year to develop Wayland display support for Chromium:
https://github.com/intel/ozone-wayland
https://blogs.igalia.com/tonikitoo/2017/05/17/chromium-musozone-update-h12017-wayland-x11/

**Comment by mzabaluev** [comment]
Here's an active development branch for the Ozone port for Wayland: https://github.com/Igalia/chromium/tree/ozone-wayland-dev

**Comment by trickreich** [comment]
Any news on this?

**Comment by qguv** [comment]
This is a huge blocker for me. Any movement on this issue?

**Comment by Nek-** [comment]
@jhasse Nooooope.
![Capture d’écran de 2019-04-21 18-58-43](https://user-images.githubusercontent.com/972456/56473174-92464a80-6467-11e9-8e7e-481031dae0b4.png)

Obviously an issue for VSCode as well.
![Capture d’écran de 2019-04-21 19-00-03](https://user-images.githubusercontent.com/972456/56473190-c588d980-6467-11e9-86b4-854cb8bd52ef.png)

_Previous screens are 1080p on 24" screen. You can imagine how it's not cool to work with..._

**Comment by jkrnak** [comment]
For a _half_ workaround (which is far from ideal as the menu bar still stays huge), you can zoom out with <kbd>CTRL</kbd>+<kbd>-</kbd>. At least your editor will be small.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by LukeCarrier** [comment]
@bpasero there are two upstream bugs which are blocking this:

* https://github.com/electron/electron/issues/10915
* https://bugs.chromium.org/p/chromium/issues/detail?id=578890

Until both of these are closed none of the updated Electron builds will solve the blurriness under Wayland as they'll be running via XWayland which has no means of knowing the DPI of the display it's on. At the moment the window will be upscaled from the lowest display's DPI to the display it's currently on. On a laptop with a 4k display and external 1080p display this means Code will look right on the external display and blurry on the 4k one.

**Comment by hedgepigdaniel** [comment]
I would say that the chromium issue is solved enough to support this, at least for testing purposes.

The current stable chromium release only requires the ozone/wayland build flags to be compiled for ozone/wayland (no downstream patches). It works, and correctly scales the window to match the DPI of the display it's rendered on.

**Comment by LennyPenny** [comment]
@bpasero would be awesome if you could hook us up with such builds

**Comment by bpasero** [comment]
@deepak1556 fyi on https://github.com/microsoft/vscode/issues/41345#issuecomment-552306952

**Comment by kaepora** [comment]
@bpasero These builds did nothing for me. Still experiencing this issue on latest GNOME/latest Fedora with fractional DPI scaling set to 125%.

**Comment by ecnepsnai** [comment]
On Fedora 31 (on a 1440p laptop display) any scale other than 100% results in a blurry window - including 200%
![Screenshot from 2019-11-23 00-40-17](https://user-images.githubusercontent.com/1607109/69476135-c598e100-0d8a-11ea-938c-d124ed68bed9.png)

**Comment by kaepora** [comment]
Any updates on this? VSCode has become painful to use on Linux due to this.

**Comment by tjanez** [comment]
> Any updates on this? VSCode has become painful to use on Linux due to this.

@kaepora, things are moving, see https://github.com/electron/electron/issues/10915#issuecomment-558387649 for recent progress.

**Comment by kaepora** [comment]
@tjanez Thank you, I've switched back to Xorg until this is resolved. Thankfully, VSCode works great on HiDPI on Xorg but I do miss the Wayland advantages across the rest of my computer.

**Comment by schmod** [comment]
It looks like the native Wayland support in Chromium/Electron is just about ready, so hopefully VSCode will soon be able to take advantage of that...

**Comment by superhero75** [comment]
> It looks like the native Wayland support in Chromium/Electron is just about ready, so hopefully VSCode will soon be able to take advantage of that...

This is april 2021. Gnome 40 is already out and neither chrome nor vscode supports hidpi monitor scaling on wayland. I tried all the quick fix on the web but none works. Is there any progress ?

**Comment by qcasey** [comment]
@superhero75 

https://github.com/microsoft/vscode/issues/109176#issuecomment-809370347

**Comment by trickreich** [comment]
> > It looks like the native Wayland support in Chromium/Electron is just about ready, so hopefully VSCode will soon be able to take advantage of that...
> 
> This is april 2021. Gnome 40 is already out and neither chrome nor vscode supports hidpi monitor scaling on wayland. I tried all the quick fix on the web but none works. Is there any progress ?

In fact this was the reason why I've switched off from Linux as my main OS..

**Comment by darkbasic** [comment]
> This is april 2021. Gnome 40 is already out and neither chrome nor vscode supports hidpi monitor scaling on wayland. I tried all the quick fix on the web but none works. Is there any progress ?

Did you try with KDE Plasma and an electron 12 build of vscode? AFAIK it used to work even with XWayland vscode, but it was blurry. Don't know about Gnome though.

**Comment by darkbasic** [comment]
> In fact this was the reason why I've switched off from Linux as my main OS..

I know that feeling, that's really a dealbreaker... A friend of mine got it sort of working with Wayland Plasma, but at the time it was so unstable that he decided to match the dpi of the laptop.

**Comment by carwyn** [comment]
See #109176 and #120034 - The latter has some exploration builds which do run with nice sharp text under Wayland.

**Comment by hfluz** [comment]
> See #109176 and #120034 - The latter has some exploration builds which do run with nice sharp text under Wayland.

@carwyn , do I have to set any variable in those exploration builds? I installed the rpm package on Fedora 34, but it still runs on xwayland.

**Comment by edrex** [comment]
#72759 is a duplicate issue with a number of up-to-date user reports after the recent upgrade from Electron 14 to 17.

With #148507 fixed in insider, this is the first time VSCode is running stably for me as a native Wayland client, so scaling support is the last **blocking** issue for this to be usable.

**Comment by shuhaowu** [comment]
I have noted while using wayland fractional scaling with two monitors at 150% and 100% and launching VS code with the arguments `--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations` gives me a blurry VS code on the 150% screen. Interestingly, only the code editor region is blurry. The menu and the developer tools panel are not blurry. This is suggesting that some thing from VScode is rendering at the lowest scale between the two monitors?
