### ISSUE TITLE
[Localization] Missing resource string across multiple sections.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4204]
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch an app from command line with cmd> code-alpha --locale=de-DE or >code-alpha --locale=fr-FR
2. Verify localized string across different sections.

Actual: localized string is not displaying for:
**
Error messages for extension failures:**
![image](https://cloud.githubusercontent.com/assets/17735796/13757252/d65ecd14-e9e0-11e5-9ad9-4eacba4c5f63.png)

**Command palette : **
Message for Extensions recommendation:
In German: Show extension recommendations : Anzeigen Erweiterung Empfehlungen
In Fr: Show extension recommendations : Afficher recommandations d'extension
![image](https://cloud.githubusercontent.com/assets/17735796/13757422/8d82ca7c-e9e1-11e5-891f-b9db0db0fd2f.png)

**Pop-up: cancel button.**
Genman: cancel: stornieren
FR: Cancel: Annuler
![image](https://cloud.githubusercontent.com/assets/17735796/13757347/42385e1a-e9e1-11e5-863a-59cc6d423f7c.png)

**Debug Window's section tags : **
For German:
Watch: - Uhr , Call Stack:- Call-Stack , Breakpoints:-Haltepunkte , Debug Console:- Debug-Konsole
Cancel: -stornieren
![image](https://cloud.githubusercontent.com/assets/17735796/13757550/5d4ad718-e9e2-11e5-863f-2c01af74d99d.png)

**Comment by aeschli** [comment]
@v-pavanp Please note that minor parts of the product are still not translated. We have in total 136 untranslated strings. If a strings shows up in the user interface untranslated and you want to check if the strings is correctly externalized start in locale=pseudo and check if the string is enclosed in [ ] and has doubled vowels.

**Comment by dbaeumer** [comment]
The missing debugger strings have been fixed. The missing extension strings are 'on purpose'. Currently the market place is not localized so we can't show any localized strings.

The Show Extensions Recommendation as not been translarted yet either.

**Comment by dbaeumer** [comment]
Closing since the strings are proper externalized (minus extensions from the store) and we are waiting to receive the translations from the team.

**Comment by dbaeumer** [comment]
@isidorn can you please verify since debugger was mostly affected.

**Comment by v-pavanp** [comment]
I observed that with 1.0.1-alpha build the debugger strings are not localized and displaying in English, irrespective of provided locale. Looks like this is regression.
![image](https://cloud.githubusercontent.com/assets/17735796/14728371/d449cb52-07e8-11e6-9abd-4230abeb4cde.png)

**Comment by isidorn** [comment]
I also see this when launching `code-alpha --locale=DE`. However these titles still have the localize call - which has not been changed since 1.0.0 (when they were localized).
What changed is when these views are registered, but this should not influence the translations right?

Forwarding to @dbaeumer

**Comment by dbaeumer** [comment]
It doesn't. However have you moved or renamed files or nls keys.? This could explain why these strings are now in English.

**Comment by isidorn** [comment]
@dbaeumer I have renamed the file where these nls string live. But it is still the same nls key.
Does that mean the translation will be picked up with latest?

**Comment by dbaeumer** [comment]
Yes.

**Comment by isidorn** [comment]
Closing this then since it will fixed when we get newer translations
