### ISSUE TITLE
Better Typescript 2.6.2 Auto Import and Tslint Formatting

### ISSUE THREAD

**Issue by th-ko** [Microsoft/vscode#42367]
- VSCode Version: 1.19.3
- OS Version: Win 10

Steps to Reproduce:
1. Open a typescript-project
2. Use the new auto import feature

Import should:
a) be minimal (not ending with /index)
b) respect tslints semicolon settings (as it does with quotemarks see: [#21424](https://github.com/Microsoft/vscode/issues/21424)

**Comment by mjbvz** [comment]
Are you using TS 2.2 in your workspace?

Also, please share information about your project: what is its structure? Do you have a `tsconfig`? What do the expected imports look like vs what the actual added imports look like?

**Comment by th-ko** [comment]
First of all, TS 2.2 was a typo. It should have been 2.6.2 (fixed the title by now).
I am having a tsconfig.json as well as a tslint.json (the project was created via create-react-app-ts).
The mentioned tslint-settings are:
        "quotemark": [true, "single", "jsx-double"],
        "semicolon": [true, "never"],

Assuming I am importing a constant `api` from the file `/state/api/index.ts ` I would expect
`import { api } from '../state/api'`
instead I am getting:
`import { api } from '../state/api/index';`

**Comment by mjbvz** [comment]
@th-ko Let's keep this issue focused on the auto-imports. Please open a separate issue for the tslint stuff.

Can you please share your `tsconfig.json`? I think you may need to set `"module": "commonjs"`

**Comment by mjbvz** [comment]
Also, can you please try our the [latest VS Code insiders builds](https://code.visualstudio.com/insiders/). There have been a number of fixes to auto imports so this may already have been resolved

**Comment by th-ko** [comment]
Using `"module": "commonjs"` might be a problem. Wouldn't that mean that web-packs tree-shaking wouldn't work any more?

tsconfig.json:
```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",

    "strict": true,
    "suppressImplicitAnyIndexErrors": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
```

Regarding the tslint-settings: I would have assumed they are relevant as one point in this issue is the code-style of semicolons. (This one is still valid in the current insider-build)

The `/index`-part of the issue is resolved in the insiders-build. 

BTW: Great work, loving VSCode and especially the autoimport.

**Comment by mjbvz** [comment]
Semi colon part is already tracked by https://github.com/Microsoft/TypeScript/issues/19882 / https://github.com/Microsoft/TypeScript/issues/20161 I believe

I also see the correct stye imports on VS Code insiders when setting:

```json
        "module": "esnext",
        "moduleResolution": "node",
```

Can you try out VS Code insiders?

**Comment by th-ko** [comment]
I already have both of those set (see the posted tsconfig). However the semicolon is still appended. My version is the following:

Version 1.20.0-insider
Commit 757ff83f0dece1ecf43d3a92e91fe467de1cc9dc
Datum 2018-01-29T05:13:39.772Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

**Comment by mjbvz** [comment]
@th-ko I'm only focusing on the import path issue. The semicolon issue is not fixed and tracked by the two bugs I linked

Does 1.20 fix the import path?

**Comment by th-ko** [comment]
As stated above the import path issue is fixed. As the semicolon is tracked by the other bugs I will close the issue. Thanks.
