### ISSUE TITLE
Unable to debug extension, warning message: "Plugin host did not start in 10 seconds"

### ISSUE THREAD

**Issue by narf** [Microsoft/vscode#4308]
- VSCode Version: Work on 0.10.3 problem appear from version 0.10.6 until latest (0.10.11)
- OS Version: ubuntu 14.04 64 bits But tried on another system with same os and it works fine

Steps to Reproduce: 
1. Create an hello world typescript extension using yo code
2. npm install
3. Open it in vsCode 
4. Press F5
5. Wait 10 seconds
6. Warning message appear: "Plugin host did not start in 10 seconds, ...."

**Comment by isidorn** [comment]
What version of node do you have? Do you have the same version on the system where it works and where it does not work.
For starters, giving to @weinand

**Comment by narf** [comment]
Yes, I was using nvm and tried different version of node. I tried with the same version as the one where it worked and even with the same version it was still not working on my machine.

**Comment by weinand** [comment]
@narf the node version makes no difference in this case because the extension host is always using the node that is included in electron.

**Comment by narf** [comment]
Yeah, yhat's what I had in mind. I just tried to change it out of despair.

**Comment by chuckries** [comment]
I am running into this as well. Any guidance? 

```
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version 0.10.11
Commit f291f4ad600767626b24a4b15816b04bee9a3049
Date 2016-03-11T17:10:35.304Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

[OK]
```

```
node --version
v4.3.0
```

**Comment by weinand** [comment]
@chuckries does this happen all the time?

**Comment by chuckries** [comment]
It began happening while I was working on the C# extension. I backed out all my changes, git clean'd, reinstalled VS Code, and restarted my computer and I am still seeing it. When I pause in the debugger I see it stop here: 
![image](https://cloud.githubusercontent.com/assets/6598594/14083306/c0304966-f4c9-11e5-9936-5d1370e0bca3.png)

**Comment by chuckries** [comment]
I downloaded the insiders build and am not seeing the same issue from there. I think somehow my install of the public VS Code has been put in a bad state.

**Comment by weinand** [comment]
@bpasero is there a simple way to increase the timeout on your side?

**Comment by chuckries** [comment]
I don't think it's a matter of the timeout. Something is hung.

**Comment by weinand** [comment]
@chuckries does the launch config have a 'preLaunchTask'? If yes, could you try whether disabling it makes a difference?

**Comment by chuckries** [comment]
There is no preLaunchTask, I am using the default configuration for "Launch Extension":

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceRoot}"
            ],
            "stopOnEntry": false,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/out"
        }
    ]
}
```

**Comment by chuckries** [comment]
I am able to F5 my extension just fine from the insiders build of Code but not from the public build. Uninstalling has no effect. Is there an AppData folder or something equivalent I can wipe out?

**Comment by chuckries** [comment]
I was finally able get past this by uninstalling Code then manually deleting `%USERPROFILE%\AppData\Roaming\Code`

**Comment by KalitaAlexey** [comment]
I had that on my Linux Ubuntu 14.04.3 x64. I have fixed with the following steps:

* I had removed visual-studio-code
```bash
sudo apt purge visual-studio-code
```
* I had removed everything that was not deleted. I had found this with
```bash
find ~ -name '*vscode*'
find /usr -name '*vscode*'
```

**Comment by weinand** [comment]
@KalitaAlexey does this mean you have uninstalled and then installed VS Code again and now extension debugging works fine?

**Comment by KalitaAlexey** [comment]
@weinand Yes.

**Comment by weinand** [comment]
@KalitaAlexey thanks for trying this. I still have no clue why this is problem occurs and why it can be solved by reinstalling VS Code.

@bpasero do you have an explanation?

**Comment by KalitaAlexey** [comment]
@weinand It happens to me after I tried **VSCode for insiders** and then installed **VSCode 1.0**.
I got insiders from https://code.visualstudio.com/download?insiders=true
I got stable from https://code.visualstudio.com/download?insiders=true#stable-downloads

**Comment by kevcunnane** [comment]
@weinand - I am seeing this issue with VSCode and the insiders build on Mac. First it only affected my insiders build install but later it started causing the regular build to require a break point. I've tried reinstalling Node, deleting vscode and any references to it but nothing worked so far. Are there any recommendations for doing a full clean of all dependencies to resolve this issue? It's a known error message in VSCode - does anyone know the cause / fix?

Thanks.

**Comment by marad** [comment]
I'm also having a problem with this warning. I've installed VSCode from AUR on Arch Linux and tried create simple hello-world plugin. Also even though it's reported as a warning, VSCode doesn't seem to load my plugin at all.

**Comment by vladdu** [comment]
I got this problem too. Tried to clean up and reinstall, like mentioned before, but without success. This is with 1.7.1 on Win10, with a HelloWorld extension (neither ts or js variants work). There are zombie code.exe processes left behind, too.

**Comment by szmtcjm** [comment]
I'm also having a problem with this warning. In addition to this, there are also some warnings 'Couldn't find message for key node.xxx.xxx'

**Comment by vicerwang** [comment]
I'm also having the same problem with this warning, i tried vscode 1. 8, 1.7, 1.6 and 1.5, every version debug failed.

**Comment by andy-hanson** [comment]
I tried the [language server example](https://github.com/Microsoft/vscode-languageserver-node-example) and had this same problem. My steps are:

```sh
git clone https://github.com/Microsoft/vscode-languageserver-node-example.git
cd client
npm install
code-insiders .
cd ../server
npm install
code-insiders .
```

* Go to server vscode instance and hit `ctrl-shift-b`.
* Go to client vscode instance and hit `F5`.
* Extension Development Host opens and works. Server is working too (`typescript` is underlined). Breakpoints in client code work.
* Go to server vscode instance and hit `F5`.
* Nothing happens for a while... Then one of these errors will occur:
  - `Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: Parse Error).`
  - `Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:6004).`
  - `Cannot connect to runtime process (timeout after 10000 ms).`

Doing the same instructions with `code` instead of `code-insiders` results in a `Cannot connect to runtime process (timeout after 10000 ms).` error too. My `vscode` version is `1.9.0`. My `vscode-insiders` version is `1.10.0-insider` (date `2017-02-08T07:18:38.941Z`).

**Comment by weinand** [comment]
@andy-hanson this is an issue in Insiders build. Fix is adding a `"protocol": "legacy"` to the corresponding launch config.

**Comment by weinand** [comment]
@andy-hanson I've fixed the launch configuration of the server in the "vscode-languageserver-node-example" repo. Please try again with the latest launch.json and let me know whether that fixes the problem.

**Comment by andy-hanson** [comment]
@weinand Thanks! It works after pulling in that change.

**Comment by vladdu** [comment]
Any progress on this? It is quite unnerving to have to debug by building a vsix, installing it and using the developer tools. Even if uninstalling and cleaning vscode and node would help, it's still not something one would like to do often.

The extension host doesn't start. Can I debug that somehow?

**Comment by weinand** [comment]
@vladdu since I do not have any details about your setup and the reproducible steps, I have no idea what problem you are experiencing. I suggest that you create a new bug with details about your setup and the reproducible steps.

**Comment by vladdu** [comment]
Sorry, there is a comment from november where I mention I have the same problem as the OP: when trying to launch and debug an extension, the extension host doesn't start and there is a timeout. Actually, it may start and hang, because there are zombie code.exe processes afterwards. I am now using 1.9 and also the insiders version, with the same result. Cleaning up as someone suggested didn't help. 

I want to help finding the problem, please guide me.

**Comment by weinand** [comment]
@vladdu I asked for a separate issue because I cannot follow all the various threads that appear in an issue over the course of a year. 95% of all "me too" comments end up in being different issues (and only appeared to be similar on the surface).

To your problem: could you quickly try to create a new VS Code extension with the yeoman generator and see whether you can run this from VS Code successfully? With this we could find out whether the problem you are seeing is a problem of your VS Code installation or whether it is a problem with your specific extension. Just follow the steps in this document until you've reached the last step of this section: https://code.visualstudio.com/docs/extensions/example-hello-world#_running-your-extension.

**Comment by vladdu** [comment]
Sure, sorry again, I use the github UI so all history is there.

I created a hello world extension and the host still hangs. A difference is that now there is a "STOPPED on first line for debugging" message that I didn't see before - but there is a debugger attached (that isn't stopped) so I guess the communication fails somehow?

I can see the "hello world" command, but it does nothing.

**Comment by weinand** [comment]
So something with your setup is broken. We are not aware of any issues in that area on Windows (and I cannot reproduce the problem with VS Code 1.9.1 on Windows 10).

Can you try this:
- shutdown VS Code
- delete  %USERPROFILE%\AppData\Roaming\Code
- start VS Code
- try to reproduce the problem

**Comment by vladdu** [comment]
I tried this all before, but I did it again now:
- uninstalled code and insiders; reinstalled from scratch
- removed appdata/roaming/code
- tried again: doesn't work
- started win10 in safe mode: still doesn't work

I am running Win10 build 15031, if that might make a difference. I tried on different machines, works ok.

**Comment by weinand** [comment]
@vladdu so you are saying that you see the issue only on one machine?
But all machines are running Windows 10?

**Comment by vladdu** [comment]
Yes, I can see it on only my PC. I tried otherwise on both Win7 and Win10 (though not an insiders build) and it worked. I tried with different versions of nodejs. 

The process started with ""C:\Program Files (x86)\Microsoft VS Code\Code.exe" --nolazy --debug-brk=42930 "c:\Program Files (x86)\Microsoft VS Code\resources\app\out\bootstrap" --type=extensionHost" seems to hang, and it remains as a zombie after shutting down the editor. Is there a way to find out what it is waiting for?

**Comment by vladdu** [comment]
I got the problem today on a Win7 machine too, with a fresh install of vscode insiders. Then I installed the stable version and it started working for both versions. Weird!

**Comment by weinand** [comment]
I've tried to mitigate the problem by only starting the extension process with `--debugBrk` when `stopOnEntry` is set to true. This should prevent the extension process from waiting for the debugger.
But we'll have to see whether this helps.

In addition I've added a new trace flag 'eh'. If you see the problem again, please add a `"trace": "eh"` and let me know what you see on the debug console.

**Comment by weinand** [comment]
The change will appear in the next Insider release (probably on Monday).

**Comment by vladdu** [comment]
Thanks! 

Now this is an interesting fact: my insiders installation just got updated to commit 50f8848 and, surprise!, it now works. Unfortunately, I don't know what was my previous version, it would have been interesting to find what was wrong.

**Comment by Jarrio** [comment]
I've just experienced this issue on Linux, elementary os. I have tried rebooting Linux and reinstalling it with the method described near the top of the thread. I can provide the specific events leading up to recognising the issue. 

The extensionHost kept failing but I wasn't getting anything from the debugger, I opened the project on my windows machine and I had a coding issue which now outputted into the debugger.

I fixed the issue and pushed to the repo, booted up into Linux to retry the extension with the code fix and didn't make any difference. It's not much different from the others claims. I haven't installed the insiders build and am running the latest version of vscode.

Adding `trace: "eh"` to package.json doesn't reveal much:
```


```

**Comment by Izhaki** [comment]
I'm having the same issue.

Practically following the [official guide](https://code.visualstudio.com/docs/extensions/example-hello-world) as of yesterday.

OS: Mac 10.12.6
VSCode: 1.17.0

Using the following lunch config (with verbose trace):

```
        {
            "name": "Launch Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": ["--extensionDevelopmentPath=${workspaceRoot}" ],
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot}/out/**/*.js" ],
            "preLaunchTask": "npm: watch",
            "trace": "verbose"
        },
```

Here is the debug console output (Note the last line: `Paused on entry`):

```
Verbose logs are written to:
/var/folders/cm/jzg3svnj7xn_cfww7jjpcwtjkk7xwg/T/vscode-node-debug2.txt
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.10
10:59:32, 2017-10-17
node-debug2: 1.17.6
From client: initialize({"clientID":"vscode","adapterID":"extensionHost","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-gb"})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true},{"label":"Promise Rejects","filter":"promise_reject","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true}}
From client: launch({"name":"Launch Extension","type":"extensionHost","request":"launch","runtimeExecutable":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","args":["--extensionDevelopmentPath=/Users/izhakroe/Development/tryouts/VSCode/hello-world"],"stopOnEntry":false,"sourceMaps":true,"outFiles":["/Users/izhakroe/Development/tryouts/VSCode/hello-world/out/**/*.js"],"preLaunchTask":"npm: watch","trace":"verbose","__sessionId":"711568cb-bbeb-4a7c-8fda-98279f30cd29"})
SourceMaps: preloading sourcemaps for scripts in globs: ["/Users/izhakroe/Development/tryouts/VSCode/hello-world/out/**/*.js"]
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"request":"launch","args":["name","type","request","runtimeExecutable","args","stopOnEntry","sourceMaps","outFiles","preLaunchTask","trace","__sessionId","sourceMapPathOverrides","showAsyncStacks"]}}}
/Applications/Visual Studio Code.app/Contents/MacOS/Electron --debugBrkPluginHost=38480 --debugId=711568cb-bbeb-4a7c-8fda-98279f30cd29 --extensionDevelopmentPath=/Users/izhakroe/Development/tryouts/VSCode/hello-world 
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
SourceMaps: expanded globs and found 3 scripts
SourceMaps: sourcemap url parsed from end of generated content: extension.js.map
SourceMaps.getMapForGeneratedPath: Finding SourceMap for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/extension.js by URI: extension.js.map
SourceMaps.loadSourceMapContents: Reading local sourcemap file from /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/extension.js.map
SourceMaps: sourcemap url parsed from end of generated content: extension.test.js.map
SourceMaps.getMapForGeneratedPath: Finding SourceMap for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/extension.test.js by URI: extension.test.js.map
SourceMaps.loadSourceMapContents: Reading local sourcemap file from /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/extension.test.js.map
SourceMaps: sourcemap url parsed from end of generated content: index.js.map
SourceMaps.getMapForGeneratedPath: Finding SourceMap for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/index.js by URI: index.js.map
SourceMaps.loadSourceMapContents: Reading local sourcemap file from /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/index.js.map
SourceMap: creating for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/extension.js
SourceMap: sourceRoot: 
SourceMap: sources: ["../src/extension.ts"]
SourceMap: no sourceRoot specified, using script dirname: /Users/izhakroe/Development/tryouts/VSCode/hello-world/out
SourceMap: creating for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/extension.test.js
SourceMap: sourceRoot: 
SourceMap: sources: ["../../src/test/extension.test.ts"]
SourceMap: no sourceRoot specified, using script dirname: /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test
SourceMap: creating for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/index.js
SourceMap: sourceRoot: 
SourceMap: sources: ["../../src/test/index.ts"]
SourceMap: no sourceRoot specified, using script dirname: /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test
From client: loadedSources(undefined)
To client: {"seq":0,"type":"response","request_seq":3,"command":"loadedSources","success":true,"body":{"sources":[]}}
Target exited
Killing process with id: 86071
Terminated: Target exited
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStopped","data":{"reason":"Target exited"}}}
Target closed
Terminated: Target closed
Verbose logs are written to:
/var/folders/cm/jzg3svnj7xn_cfww7jjpcwtjkk7xwg/T/vscode-node-debug2.txt
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.10
10:59:34, 2017-10-17
node-debug2: 1.17.6
From client: initialize({"clientID":"vscode","adapterID":"extensionHost","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-gb"})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true},{"label":"Promise Rejects","filter":"promise_reject","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true}}
From client: attach({"name":"Launch Extension","type":"extensionHost","request":"attach","runtimeExecutable":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","args":["--extensionDevelopmentPath=/Users/izhakroe/Development/tryouts/VSCode/hello-world"],"stopOnEntry":false,"sourceMaps":true,"outFiles":["/Users/izhakroe/Development/tryouts/VSCode/hello-world/out/**/*.js"],"preLaunchTask":"npm: watch","trace":"verbose","__sessionId":"711568cb-bbeb-4a7c-8fda-98279f30cd29","port":38480})
SourceMaps: preloading sourcemaps for scripts in globs: ["/Users/izhakroe/Development/tryouts/VSCode/hello-world/out/**/*.js"]
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"request":"attach","args":["name","type","request","runtimeExecutable","args","stopOnEntry","sourceMaps","outFiles","preLaunchTask","trace","__sessionId","port","sourceMapPathOverrides","showAsyncStacks"]}}}
Discovering targets via http://127.0.0.1:38480/json
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"targetCount","data":{"numTargets":1}}}
Attaching to target: {"description":"node.js instance","devtoolsFrontendUrl":"chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:38480/b7fa4973-3bea-4a6a-9594-aa3665e64e48","faviconUrl":"https://nodejs.org/static/favicon.ico","id":"b7fa4973-3bea-4a6a-9594-aa3665e64e48","title":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","type":"node","url":"file://","webSocketDebuggerUrl":"ws://127.0.0.1:38480/b7fa4973-3bea-4a6a-9594-aa3665e64e48"}
WebSocket Url: ws://127.0.0.1:38480/b7fa4973-3bea-4a6a-9594-aa3665e64e48
SourceMaps: expanded globs and found 3 scripts
→ To target: "{\"id\":1,\"method\":\"Console.enable\"}"
→ To target: "{\"id\":2,\"method\":\"Debugger.enable\"}"
→ To target: "{\"id\":3,\"method\":\"Runtime.enable\"}"
→ To target: "{\"id\":4,\"method\":\"Runtime.runIfWaitingForDebugger\"}"
→ To target: "{\"id\":5,\"method\":\"Runtime.run\"}"
← From target: {"id":1,"result":{}}
SourceMaps: sourcemap url parsed from end of generated content: extension.js.map
SourceMaps.getMapForGeneratedPath: Finding SourceMap for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/extension.js by URI: extension.js.map
SourceMaps.loadSourceMapContents: Reading local sourcemap file from /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/extension.js.map
SourceMaps: sourcemap url parsed from end of generated content: extension.test.js.map
SourceMaps.getMapForGeneratedPath: Finding SourceMap for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/extension.test.js by URI: extension.test.js.map
SourceMaps.loadSourceMapContents: Reading local sourcemap file from /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/extension.test.js.map
SourceMaps: sourcemap url parsed from end of generated content: index.js.map
SourceMaps.getMapForGeneratedPath: Finding SourceMap for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/index.js by URI: index.js.map
SourceMaps.loadSourceMapContents: Reading local sourcemap file from /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/index.js.map
SourceMap: creating for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/extension.js
SourceMap: sourceRoot: 
SourceMap: sources: ["../src/extension.ts"]
SourceMap: no sourceRoot specified, using script dirname: /Users/izhakroe/Development/tryouts/VSCode/hello-world/out
SourceMap: creating for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/extension.test.js
SourceMap: sourceRoot: 
SourceMap: sources: ["../../src/test/extension.test.ts"]
SourceMap: no sourceRoot specified, using script dirname: /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test
SourceMap: creating for /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test/index.js
SourceMap: sourceRoot: 
SourceMap: sources: ["../../src/test/index.ts"]
SourceMap: no sourceRoot specified, using script dirname: /Users/izhakroe/Development/tryouts/VSCode/hello-world/out/test
← From target: {"id":2,"result":{}}
← From target: {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"origin":"","name":"Electron Main Context"}}}
← From target: {"id":3,"result":{}}
← From target: {"id":4,"result":{}}
← From target: {"error":{"code":-32601,"message":"'Runtime.run' wasn't found"},"id":5}
→ To target: "{\"id\":6,\"method\":\"Schema.getDomains\"}"
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"29","url":"bootstrap_node.js","startLine":0,"startColumn":0,"endLine":553,"endColumn":0,"executionContextId":1,"hash":"ADDBD5E3690191B9C12B1D37101DC256E6353865","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
→ To target: "{\"id\":7,\"method\":\"Debugger.getPossibleBreakpoints\",\"params\":{\"start\":{\"scriptId\":\"29\",\"lineNumber\":0,\"columnNumber\":0},\"end\":{\"scriptId\":\"29\",\"lineNumber\":1,\"columnNumber\":0},\"restrictToFunction\":false}}"
← From target: {"id":6,"result":{"domains":[{"name":"Runtime","version":"1.2"},{"name":"Debugger","version":"1.2"},{"name":"Profiler","version":"1.2"},{"name":"HeapProfiler","version":"1.2"},{"name":"Schema","version":"1.2"}]}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"30","url":"events.js","startLine":0,"startColumn":0,"endLine":503,"endColumn":66,"executionContextId":1,"hash":"B64678932DDD251148F6D217BB068CD8D5B97AD5","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
→ To target: "{\"id\":8,\"method\":\"Debugger.setAsyncCallStackDepth\",\"params\":{\"maxDepth\":4}}"
← From target: {"id":7,"result":{"locations":[]}}
← From target: {"id":8,"result":{}}
→ To target: "{\"id\":9,\"method\":\"Runtime.evaluate\",\"params\":{\"expression\":\"[process.pid, process.version, process.arch]\",\"returnByValue\":true,\"contextId\":1}}"
To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":true}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"31","url":"util.js","startLine":0,"startColumn":0,"endLine":1084,"endColumn":66,"executionContextId":1,"hash":"DC78ADA1FAAC29235E14B8169B850308FE28DAC6","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"33","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":44,"executionContextId":1,"hash":"22960EE2CC885872F71ED2E747A68B200282CC65","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"id":9,"result":{"result":{"type":"object","value":[86077,"v7.9.0","x64"]}}}
Target node version: v7.9.0 x64
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"nodeVersion","data":{"version":"v7.9.0"}}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"34","url":"buffer.js","startLine":0,"startColumn":0,"endLine":1373,"endColumn":66,"executionContextId":1,"hash":"173DBFD0788E90B8DABEA2D63B4DB8A0CA826965","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"35","url":"internal/util.js","startLine":0,"startColumn":0,"endLine":160,"endColumn":66,"executionContextId":1,"hash":"21B899D3467C5EF8D86B24330C1C766A0CF39742","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"36","url":"internal/buffer.js","startLine":0,"startColumn":0,"endLine":31,"endColumn":66,"executionContextId":1,"hash":"5E9949A3A30814220B0B28442EAB5FD8A0528413","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"37","url":"timers.js","startLine":0,"startColumn":0,"endLine":753,"endColumn":66,"executionContextId":1,"hash":"AC90D9623C74E4A04758D7D57BA72D87B727C251","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"38","url":"internal/linkedlist.js","startLine":0,"startColumn":0,"endLine":72,"endColumn":66,"executionContextId":1,"hash":"28918A5323295CF4EC2FEBD76EDFB30A31143262","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"39","url":"assert.js","startLine":0,"startColumn":0,"endLine":379,"endColumn":66,"executionContextId":1,"hash":"D714D83352AC4D51AB2A9A91B8D2AA99BF2A1125","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"40","url":"","startLine":0,"startColumn":0,"endLine":19,"endColumn":4,"executionContextId":1,"hash":"8F11B5D22567E9308C01A255F05036D5C8D5C4E2","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"41","url":"ELECTRON_ASAR.js","startLine":0,"startColumn":0,"endLine":698,"endColumn":66,"executionContextId":1,"hash":"16121962564FE5AAC4F987F1C7F86ED2EF2ED721","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"42","url":"child_process.js","startLine":0,"startColumn":0,"endLine":541,"endColumn":66,"executionContextId":1,"hash":"E18406925675A827E0D337D68EDF09E3E0766D03","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"43","url":"internal/child_process.js","startLine":0,"startColumn":0,"endLine":902,"endColumn":66,"executionContextId":1,"hash":"A499DB52144F838402F82146A1E26712273DA921","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"44","url":"string_decoder.js","startLine":0,"startColumn":0,"endLine":263,"endColumn":66,"executionContextId":1,"hash":"EC0611F1B3E86CD4221E56401274C0A633DD7B85","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"45","url":"net.js","startLine":0,"startColumn":0,"endLine":1644,"endColumn":66,"executionContextId":1,"hash":"F61C8841A2B112929E253B77A0CE22F90E1E0990","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"46","url":"stream.js","startLine":0,"startColumn":0,"endLine":15,"endColumn":66,"executionContextId":1,"hash":"45464040F2F60CC5A560F33126575A6198F3D442","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"47","url":"internal/streams/legacy.js","startLine":0,"startColumn":0,"endLine":94,"endColumn":66,"executionContextId":1,"hash":"22DEDFC350E8A5682C898413D33E2B46AF058AF6","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"48","url":"_stream_readable.js","startLine":0,"startColumn":0,"endLine":978,"endColumn":66,"executionContextId":1,"hash":"06706A22E6358B4AB993DB30E8E91A04CEC07EF3","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"49","url":"internal/streams/BufferList.js","startLine":0,"startColumn":0,"endLine":73,"endColumn":66,"executionContextId":1,"hash":"0414C4B310E93A65232F71B09693528BFF961167","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"50","url":"_stream_writable.js","startLine":0,"startColumn":0,"endLine":554,"endColumn":66,"executionContextId":1,"hash":"1C3F7640F1BA0238858483715A12654A5E395AF7","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"51","url":"_stream_duplex.js","startLine":0,"startColumn":0,"endLine":58,"endColumn":66,"executionContextId":1,"hash":"2D6623B30E7ED694CE2E91130B38E76A1B80A8A5","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"52","url":"_stream_transform.js","startLine":0,"startColumn":0,"endLine":196,"endColumn":66,"executionContextId":1,"hash":"3B675FE2076F68F0E6AA0C2141FD9B160C3368D5","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"53","url":"_stream_passthrough.js","startLine":0,"startColumn":0,"endLine":23,"endColumn":66,"executionContextId":1,"hash":"ECABD5925616B7679DCD9723504AD833D6D75846","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"54","url":"internal/net.js","startLine":0,"startColumn":0,"endLine":19,"endColumn":66,"executionContextId":1,"hash":"DDC106A0E902299ABDBC12A60F41BD599DABEE11","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"55","url":"dgram.js","startLine":0,"startColumn":0,"endLine":569,"endColumn":66,"executionContextId":1,"hash":"24CBD591FD9084012CDBEE93A1CA6DB8B2BF63A6","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"56","url":"internal/socket_list.js","startLine":0,"startColumn":0,"endLine":105,"endColumn":66,"executionContextId":1,"hash":"365C3A82E9491D2257F9E5A719E5A1D7D34290B2","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"57","url":"path.js","startLine":0,"startColumn":0,"endLine":1598,"endColumn":66,"executionContextId":1,"hash":"3208D1E2A16342C6D3671D25B73B16019246D214","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"58","url":"fs.js","startLine":0,"startColumn":0,"endLine":2143,"endColumn":66,"executionContextId":1,"hash":"EC1A18E27C182374E115889515C24AA4F941B7A2","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"59","url":"internal/fs.js","startLine":0,"startColumn":0,"endLine":101,"endColumn":66,"executionContextId":1,"hash":"C11A25D3371425088108199284C1DA5241A22ED2","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"60","url":"internal/url.js","startLine":0,"startColumn":0,"endLine":1153,"endColumn":66,"executionContextId":1,"hash":"8A91C033C59356C83CDB9040EC58A645C4B092F2","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"61","url":"internal/querystring.js","startLine":0,"startColumn":0,"endLine":16,"endColumn":66,"executionContextId":1,"hash":"ACF379B04C88B044165C7664C47C22804045A5B2","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"62","url":"querystring.js","startLine":0,"startColumn":0,"endLine":447,"endColumn":66,"executionContextId":1,"hash":"F8B50FD32F6913C97213FBF0B5E3F90B4864ED15","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"63","url":"os.js","startLine":0,"startColumn":0,"endLine":96,"endColumn":66,"executionContextId":1,"hash":"0F4C5E3040AF6614944A9528F799E905852C14A6","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"64","url":"module.js","startLine":0,"startColumn":0,"endLine":672,"endColumn":66,"executionContextId":1,"hash":"9BC399E221792445627E5228FBA9A742A7117776","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"65","url":"internal/module.js","startLine":0,"startColumn":0,"endLine":99,"endColumn":66,"executionContextId":1,"hash":"43835381F67562F2D397B623C2196063A7667BB0","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"66","url":"vm.js","startLine":0,"startColumn":0,"endLine":108,"endColumn":66,"executionContextId":1,"hash":"A71F232335A9E353894ECF3557C6214AD63F9373","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"67","url":"internal/process.js","startLine":0,"startColumn":0,"endLine":268,"endColumn":66,"executionContextId":1,"hash":"84377E605E869B318C39C4B1A9EDF704DA959008","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"68","url":"internal/process/warning.js","startLine":0,"startColumn":0,"endLine":50,"endColumn":66,"executionContextId":1,"hash":"21AFED81E120835AC68F6C237C36DA2CFCAF5855","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"69","url":"internal/process/next_tick.js","startLine":0,"startColumn":0,"endLine":162,"endColumn":66,"executionContextId":1,"hash":"79F6F3D32165B23AFCDE53A73495DDC0C1447EE2","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"70","url":"internal/process/promises.js","startLine":0,"startColumn":0,"endLine":102,"endColumn":66,"executionContextId":1,"hash":"EB52F973BAD918F4B1FC7B51D94B70A979FC17D2","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"71","url":"internal/process/stdio.js","startLine":0,"startColumn":0,"endLine":197,"endColumn":66,"executionContextId":1,"hash":"3CD288231EC51E28580BAD642256DD04F0AEB202","isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"72","url":"/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js","startLine":0,"startColumn":0,"endLine":7,"endColumn":66,"executionContextId":1,"hash":"2B51ADC395860E61FC3B2605CEC9EA06282D0C94","isLiveEdit":false,"sourceMapURL":"https://ticino.blob.core.windows.net/sourcemaps/be377c0faf7574a59f84940f593a6849f12e4de7/core/bootstrap.js.map","hasSourceURL":false,"isModule":false}}
SourceMaps.getMapForGeneratedPath: Finding SourceMap for /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js by URI: https://ticino.blob.core.windows.net/sourcemaps/be377c0faf7574a59f84940f593a6849f12e4de7/core/bootstrap.js.map
SourceMaps.loadSourceMapContents: Downloading sourcemap file from https://ticino.blob.core.windows.net/sourcemaps/be377c0faf7574a59f84940f593a6849f12e4de7/core/bootstrap.js.map
← From target: {"method":"Debugger.paused","params":{"callFrames":[{"callFrameId":"{\"ordinal\":0,\"injectedScriptId\":1}","functionName":"","functionLocation":{"scriptId":"72","lineNumber":0,"columnNumber":10},"location":{"scriptId":"72","lineNumber":0,"columnNumber":87},"scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"{\"injectedScriptId\":1,\"id\":1}"},"startLocation":{"scriptId":"72","lineNumber":0,"columnNumber":10},"endLocation":{"scriptId":"72","lineNumber":7,"columnNumber":64}},{"type":"global","object":{"type":"object","className":"global","description":"global","objectId":"{\"injectedScriptId\":1,\"id\":2}"}}],"this":{"type":"object","className":"Object","description":"Object","objectId":"{\"injectedScriptId\":1,\"id\":3}"}},{"callFrameId":"{\"ordinal\":1,\"injectedScriptId\":1}","functionName":"Module._compile","functionLocation":{"scriptId":"64","lineNumber":510,"columnNumber":36},"location":{"scriptId":"64","lineNumber":570,"columnNumber":31},"scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"{\"injectedScriptId\":1,\"id\":4}"},"name":"Module._compile","startLocation":{"scriptId":"64","lineNumber":510,"columnNumber":36},"endLocation":{"scriptId":"64","lineNumber":573,"columnNumber":1}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"{\"injectedScriptId\":1,\"id\":5}"},"startLocation":{"scri[...]
Paused on entry
```
