### ISSUE TITLE
Debugger UI goes into bad state. Cannot restart session

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#45798]
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T10:54:22.798Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

![image](https://user-images.githubusercontent.com/1018196/37430559-af784c36-278f-11e8-8b9c-8974fb77f891.png)

With python ptvsd debugger this happens fairly often. However before someone says it's the fault of extension, a bad extension should not be able to make VSCode go into a bad state forever.

Because of this, I can't start a new session, even for another unrelated debugger like nodejs. 

The only workaround for this is to kill and restart VSCode again.

**Comment by roblourens** [comment]
I think that we lost the ability to kill a debug session that hasn't yet successfully started when multiroot debugging was added. But even when waiting for a debug session to start, we should be able to start another one.

Can you post the launch config?

**Comment by nojvek** [comment]
```
        {
            "name": "Python Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/home/noj/foobar",
            "port": 8123,
            "secret": "foobar",
            "host": "localhost",
            "logToFile": false,
        }
```

**Comment by isidorn** [comment]
@nojvek I agree with you that a bad extenson should not leave vscode in a bad state.
Would you be so kind to try this on latest vscode insiders since we have pushed some fixes in this area which might imporve this experience. Thanks

**Comment by isidorn** [comment]
Pushed more changes which should definetely fix it. So let us know if from tomorrow's insider you still se this. Thank you

**Comment by nojvek** [comment]
will give a shot on insiders

**Comment by isidorn** [comment]
@nojvek please try tomorrow which includes the fix which I pushed 38 minutes ago. Thanks

**Comment by nojvek** [comment]
Makes sense. Will add a reminder. Thanks for the super fast fix. Love VSCode 😍 and how you operate.

**Comment by isidorn** [comment]
Thanks :)

**Comment by roblourens** [comment]
Hey @nojvek did you try the fix?

@isidorn I still can't start another debug session while one session is waiting to start. I mentioned it above, I don't know whether it was expected to be covered by your fix. I'll reopen this but LMK if I should open a new issue.

What I'm trying is

- Run an "attach" config that will fail. It shows a progress bar for 10s or so
- During that time, try to start a different launch config. Nothing happens when I click the start button next to the config dropdown

**Comment by isidorn** [comment]
This is designed behavior. While an session is initalizing we do not allow more sessions to start.
After the initalizision is done (10 seconds in the attach case) we allow more debug sessions.

And that is what this issue is about, thus closing it as expected behavior.

If you think we should allow new sessions to be start while we are initialising please file a new feature request.
However people are filing the oppoiste requets, that no session should be started during intiailisation so no 2 sessions are started by accident
