### ISSUE TITLE
[Linux] Rearranging working files with a long path shows white box

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4780]
- VSCode Version: 0.10.12-alpha or 0.10.13-insiders
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Add keybindings.json to your working files
2. Grab the file and drag it, as if you were going to rearrange the working files.

Actual:
Shows a white bar off the right of the file name since the path is too long. It appears that the length of the bar is related to the length of the full path.
![workingfilesarrange](https://cloud.githubusercontent.com/assets/12900364/14125107/3dada77c-f5be-11e5-9425-05d2526df825.png)

**Comment by Tyriar** [comment]
I can reproduce this on Ubuntu, only on truncated working files entries. Doesn't seem to reproduce in a minimal example https://output.jsbin.com/gatovemeha/edit/

**Comment by bpasero** [comment]
Lets hope this gets fixed with future Chrome updates.

**Comment by bpasero** [comment]
Not sure if this is still happening with new opened editors view.

**Comment by Tyriar** [comment]
Ubuntu 16.04:

![image](https://cloud.githubusercontent.com/assets/2193314/15737035/88f09344-2858-11e6-9aae-c2e8d6d45f57.png)

**Comment by isidorn** [comment]
Verified and this still happens with the latest electron - but maybe not so prominently, I am not getting it 100% of the time.

**Comment by bpasero** [comment]
Fixed.
