### ISSUE TITLE
Open Process Explorer doesn't work on NixOS

### ISSUE THREAD

**Issue by pinage404** [Microsoft/vscode#49612]
Issue Type: <b>Bug</b>

The new [Open Process Explorer](https://code.visualstudio.com/updates/v1_23#_see-the-running-visual-studio-code-processes) doesn't work on [NixOS](https://nixos.org/)

This is because VS Code call `/bin/ps` who doesn't exist in NixOS (basically, there is only `sh` in `/bin/`)
https://github.com/Microsoft/vscode/blob/6b62365d3812b19aab38c39cf6d9ed725166fa83/src/vs/base/node/ps.ts#L177

However `ps` is available in the NixOS's `$PATH`

```sh
$ which ps
/run/current-system/sw/bin/ps
$ echo $PATH
/run/wrappers/bin:/etc/profiles/per-user/pinage404/bin:/home/pinage404/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
```

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.14.39

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3146)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 5|
|Memory (System)|15.56GB (0.24GB free)|
|Process Argv|/nix/store/idh9wf28l8yxdiwjrdlimqnxhz0q65d5-vscode-1.23.0/lib/vscode/code --skip-getting-started --verbose|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/0bab532a332c9e4390c735f99e19db2821adab36

**Comment by sbatten** [comment]
I unfortunately could not figure out how to get the binary to run from archive on nixOS, @RMacfarlane is trying to recreate her setup

**Comment by sbatten** [comment]
verified by relocating ps on Ubuntu

**Comment by pinage404** [comment]
I'm using VSCode on NixOS and still having the issue

VSCode version :

Version : 1.33.1
Validation : 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date : 2019-04-11T08:20:22.771Z
Électron : 3.1.6
Chrome : 66.0.3359.181
Node.js : 10.2.0
V8 : 6.6.346.32
OS : Linux x64 4.19.36

I'm using VSCode from the official repository :

https://github.com/NixOS/nixpkgs/blob/635debeadd6b217c4e021555215c69f4f2ac4534/pkgs/applications/editors/vscode/default.nix#L30

I ran `code --verbose` then ran `Open Process Explorer` and i saw this in the console :

```
[14847:0512/000507.295107:INFO:CONSOLE(303)] "Uncaught (in promise) Error: Command failed: /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
/bin/sh: /bin/ps: No such file or directory
", source: child_process.js (303)
```

So, unfortunately, the `ps`'s path is still `/bin/ps`

---

I tried this small Node script :

```js
const { exec } = require('child_process')

exec('which ps', (err, stdout, stderr) => {
    if (err || stderr) {
        throw new Error('which problem')
    }

    console.log(stdout.toString())
})

exec('ps -aux', (err, stdout, stderr) => {
    if (err || stderr) {
        throw new Error('ps problem')
    }

    // don't need the full output to know if it worked, so take just the first 4 lines
    console.log(stdout.toString().split('\n').slice(0, 4))
})
```

```
/run/current-system/sw/bin/ps

[ 'USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND',
  'root         1  0.0  0.0 169500  3360 ?        Ss   mai11   0:02 systemd',
  'root         2  0.0  0.0      0     0 ?        S    mai11   0:00 [kthreadd]',
  'root         3  0.0  0.0      0     0 ?        I<   mai11   0:00 [rcu_gp]' ]
```

The [Node's documentation](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) say :

> Spawns a shell then executes the `command` within that shell

So i think VSCode should just ```exec(`ps ${args}`)``` without the path in the command and let the spawned shell do the magic with his `$PATH`

---

I don't know how to get VSCode binary without installing [the Nix package manager](https://nixos.org/nix/) or without installing [NixOS](https://nixos.org/)

**Comment by Tyriar** [comment]
@pinage404 that says it's v1.31.1, the fix is only in 1.34 which should be released soon.
