### ISSUE TITLE
[Bug] broken autocomplete 

### ISSUE THREAD

**Issue by Sun1ive** [Microsoft/vscode#49832]
- VSCode Version: 1.23.1-1525968403
- OS Version: Linux ubuntu 16.04

Steps to Reproduce:

1. <img src="https://i.imgur.com/ZXotSUr.gif">

Thing is: after using require('') autocomplete doesnt work
But after a while(like 10-15 mins starts to work again, just happen 1 time for me)
Maybe issue in a language server ?

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
Do you see this issue in VS Code insiders?

**Comment by Sun1ive** [comment]
had it in both like in 1.21 version.. till now
didnt test it in insiders today though

**Comment by Sun1ive** [comment]
Just tested in insiders 1.24
Same issue with no plugins and no custom config installed.

**Comment by Sun1ive** [comment]
Insiders 1.24
<img src="https://i.imgur.com/W6eVjIW.gif">

**Comment by mjbvz** [comment]
I can't repo this. Does this break all intellisense, or just the intellisense for the express import?

Can you please collect the typescript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. In VS Code, run the "Open TS Server logs" command. This should open a folder with e `tsserver.log` file in it. 

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by Sun1ive** [comment]
Hi there.

First of all. I made this gifs at work, where i run: Intel core i5 CPU, 16gb ram;
I thought it can be something with pc. But i just tested it at home, where i have AMD fx6320/16gb ram.
Fresh install 16.04 from off site. Same issue.

>  Does this break all intellisense, or just the intellisense for the express import?

it breaks all intellisense for any kind of packages.

> 
    Add "typescript.tsserver.log": "verbose" to your user settings and restart VSCode.
    Reproduce the issue
    In VS Code, run the "Open TS Server logs" command. This should open a folder with e tsserver.log file in it.

there is the link: [https://pastebin.com/dXFaKUBF](url)

**Comment by mjbvz** [comment]
You are using TypeScript 2.8.3. Please make sure that typescript 2.9.1-insiders is active. This is the default version in VS Code insiders. In a js file, run the [`select typescript version`](https://code.visualstudio.com/Docs/languages/typescript#_using-the-workspace-version-of-typescript) command to make sure you are using the workspace version of typescript

**Comment by Sun1ive** [comment]
Yes. im using 2.9 typescript.
In ts file its working fine though. that require statement doesnt break anything in .ts file.
But still issue in js files.

**Comment by mjbvz** [comment]
@Sun1ive Please collect the logs again when using TS 2.9

**Comment by Sun1ive** [comment]
https://pastebin.com/gFUVbJdu

**Comment by mjbvz** [comment]
Thanks @Sun1ive!

@sheetalkamat Can you please take a look at the logs to see if anything stands out. This has the same symptoms as a few other bugs that were resolved in 2.9

**Comment by sheetalkamat** [comment]
@Sun1ive The log you shared is missing the key information.. It ends a below pasted code where the completion request is triggered after inserting ```require('')```. I would need the log below that to be able to investigate this further.

```
Info 370  [19:9:0.426] request:
    {"seq":50,"type":"request","command":"change","arguments":{"file":"/media/sunlive/5C98349398346DA0/work/WEB/HTML CSS/nodejs/exception/src/index.js","line":1,"offset":21,"endLine":1,"endOffset":21,"insertString":"''"}}
Perf 371  [19:9:0.426] 50::change: async elapsed time (in milliseconds) 0.0789
Info 372  [19:9:0.426] request:
    {"seq":51,"type":"request","command":"completions","arguments":{"file":"/media/sunlive/5C98349398346DA0/work/WEB/HTML CSS/nodejs/exception/src/index.js","line":1,"offset":22,"includeExternalModuleExports":true,"includeInsertTextCompletions":true,"triggerCharacter":"'"}}
Info 373  [19:9:0.427] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 374  [19:9:0.441] DirectoryWatcher:: Added:: WatchInfo: /media/sunlive/5C98349398346DA0/work/WEB/HTML CSS/nodejs/node_modules 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 375  [19:9:0.442] DirectoryWatcher:: Added:: WatchInfo: /media/sunlive/5C98349398346DA0/work/WEB/HTML CSS/nodejs 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
```

**Comment by Sun1ive** [comment]
Hi there.
For some reason its now working good. I cant reproduce this bug anymore. (at home)
Working in both vscode and vscode insiders.

Though, ill test it at work next week.

**Comment by Sun1ive** [comment]
Hi.
Still facing issue at work
This is whole log that i have after repro the bug

https://pastebin.com/ZacjYBrR

**Comment by sheetalkamat** [comment]
@Sun1ive the new logs also don't contain complete information about the completion invoked after typing ``require('')``` . Did you check your output window. Is there any error being displayed? possibly tsserver crash? Are you using latest drop from vscode insiders?

**Comment by sheetalkamat** [comment]
@Sun1ive Can you ensure that there is another operation (eg hover over something) after the completion and then get the log to send it out.

**Comment by sheetalkamat** [comment]
Also I think it might be fixed by Microsoft/TypeScript#24471 . Can you use typescript@3.0.0-dev.20180531 once its available. 

Here is the information for using [typescript nightly drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code).

**Comment by mjbvz** [comment]
Closing as we have not heard back about if this was fixed on the latest typescript@next
