### ISSUE TITLE
Don't merge search ignore patterns across nested workspace folders

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#49928]
- Open a multiroot workspace containing `/foo` and `/foo/bar`.
- Search in `./bar`
- See that search.exclude patterns from `/foo/.vscode` are applied

Supporting this complicates search logic, leads to bugs like #49896, and probably was a bad idea from the start.

**Comment by roblourens** [comment]
This will already be the case with the new searchprovider-based extension, I think I should leave it at that.

**Comment by andywillekens** [comment]
Does this mean it should be fixed in the next update?

**Comment by roblourens** [comment]
Right now we have two builtin search implementations. The new one can be enabled with the `"searchRipgrep.enable"` setting, and it's fixed in there.

**Comment by andywillekens** [comment]
@roblourens My apologies but where exactly do I enable that setting?

**Comment by roblourens** [comment]
In 1.24, it's actually "searchrg.enable"

**Comment by andywillekens** [comment]
After setting "searchrg.enable": true I'm still getting the spawn ENAMETOOLONG error. Even after restart + disabled plugins. Am I missing something?

**Comment by roblourens** [comment]
Could you show the contents of the `search-rg` output channel after doing that search?

**Comment by andywillekens** [comment]
It shows mosly paths from other projects in my Workspace.

![output](https://user-images.githubusercontent.com/5364383/41396492-6786c4a6-6fb1-11e8-91ad-b7bdb09bc859.png)
