### ISSUE TITLE
Changing the capitalization of a filename causes auto-import to open the old filename in a new tab

### ISSUE THREAD

**Issue by theblang** [Microsoft/vscode#50505]
- VSCode Version: 1.23.1
- OS Version: Windows 10 Pro 1803

Steps to Reproduce:

1. Use auto-import in a file named "file.ts"
2. Change the name of "file.ts" to "File.ts"
3. Try to auto-import again and see that "file.ts" opens in a new tab with the import added while the original file, even though showing as changed in the tab, is unaltered.

Does this issue occur when all extensions are disabled?: Yes

Additional Notes:

I've tried using "Clear Editor History", deleting "%APPDATA%/Code", changing the project folder name, and restarting computer; but the issue persists.

I'm also noticing an error when I try to manually import the new file, "[ts] File name 'c:/Users/thebl/Dev/stars/src/Moon/Moon.ts' differs from already included file name 'c:/Users/thebl/Dev/stars/src/moon/moon.ts' only in casing.
module "c:/Users/thebl/Dev/stars/src/moon/moon".

**Update:** I can't make this stop happening. I've uninstalled extensions, uninstalled VSCode, removed both the `%USER%/.vscode` folder and the `%APPDATA%/Code` folder, restarted, removed the folder with the file and recreated it. Here is a screenshot of exactly what happens. I tried to import the `Moon` class and it just opened a `planet.ts` file in a new tab and added the import there. I also noticed that the import in this new tab references the lowercase path to `Moon`, like this: `import { Moon } from '../moon/moon';`.

![capture](https://user-images.githubusercontent.com/1845257/40579254-fc8245ee-60e8-11e8-9a97-8132045f3eb1.PNG)

**Comment by RMacfarlane** [comment]
I'm able to reproduce this with the latest insiders, 1.25.0-insider (07d89abf1522a67f0e8105770505077f454ab021, 2018-06-28T05:19:16.448Z)

**Comment by mjbvz** [comment]
I can't repo this anymore in latest insiders

**Comment by bobwinners** [comment]
I am having this same problem too.  I renamed a folder from an uppercase letter to a lower case and now have the same problem.  If I hover over the filename in the import statement it still shows the uppercase path.  I am using the latest stable build.

**Comment by chrmarti** [comment]
I still see this with:
VS Code version: Code - Insiders 1.26.0-insider (c86cab2211d6dce686e5c89934d915b1e020ba9e, 2018-08-02T05:12:16.245Z)
OS version: Darwin x64 17.7.0

foo.ts:
```ts
baz();
```

bar.ts:
```ts
export function baz() {
}
```

- Run 'import from bar.ts' code action in foo.ts
- Undo
- Rename bar.ts to Bar.ts
- Run 'import from bar.ts' code action again
-> Import uses lowercase 'bar' instead of 'Bar'

**Comment by mjbvz** [comment]
@chrmarti  Can you track that in a different issue? This one was for duplicate files (same file but different cases) opening in VS Code

**Comment by chrmarti** [comment]
Done (#55655). The original report was about a single file it seemed. Does "auto-import" refer to running the code action in the editor?

**Comment by mjbvz** [comment]
Thanks. Yes, the bug was that running that code action used to re-open the file with the old casing (resulting in two copies of the file being open)

**Comment by chrmarti** [comment]
Got it. Verified.

**Comment by briman0094** [comment]
FWIW, I'm still experiencing the original bug in this issue in the latest Insiders build (updated my instance minutes ago). The case of the file itself was never changed, but the casing of the folder containing the file appears to have been changed at some point in the last day or two. Auto-importing opens the file again with the old path casing.
