### ISSUE TITLE
Code - Insiders Helper using 100% cpu after update

### ISSUE THREAD

**Issue by iosdev-republicofapps** [Microsoft/vscode#51404]
- VSCode Version: Version 1.25.0-insider (1.25.0-insider), 43cb490a3bdb7388ef8f919c238f062cc66b4738, 
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Install this latest version of the insiders build.  NO OTHER CHANGES OF ANY KIND.  No extensions changed, nothing.  The only change was VSCode insiders updated itself.
2. Edit a few files.  macOS process explorer shows "Code - Insiders Helper" pegging my cpu at 100%.  It stays at 100%.  Rebooting does not help.  Quitting and relaunching insiders does not help.  Turning off extensions does not help.  Closing tabs and files does not help.

Oddly, your "process explorer" does NOT show 100% usage anywhere, but I trust the macOS process explorer/activity monitor when it says 100% cpu due to "Code - Insiders Helper" because running this latest insiders build definitely pegs my cpu and makes my system sluggish.

Please help, if we can't fix this quickly I'm going to have to go back to the stable build and that was messing up JS imports (removing needed imports).

Thanks for all your work on VSCode.  :-)

Does this issue occur when all extensions are disabled?: Yes

**Comment by iosdev-republicofapps** [comment]
Wow, "Code - Insiders Helper" stays running even after I quit the VSCode app ...  Some kind of stray process from VSCode?

**Comment by iosdev-republicofapps** [comment]
Seems like it spiked again and then your process explorer showed that first npm was going nuts downloading and updating some TS stuff (which I don't use) then some TS stuff was going nuts and pegging at 100% cpu.  This lasted for many minutes.  I don't use TS or have any TS extensions turned on.

Seems to have calmed down now, no longer pegged, but this was  a scary upgrade experience (whereas previous upgrades had been quite smooth)!  :-)

**Comment by runofthemill** [comment]
Similar issue, though not an insider build.

Code helper running between 87-100% CPU, even after quitting VS Code.

macOS 10.13.4
Code 1.24.0 6a6e02cef0f2122ee1469765b704faf5d0e0d859

When re-opening VS Code and opening the Process Explorer, after a short period where `electron_node server.js` runs around 98% CPU, it drops to 0%, but Code Helper process still runs ~100% CPU in System Activity Monitor. Inspecting the process also shows regular memory size of 24mb and virtual memory size of 5.07 GB (?).

**Comment by aeschli** [comment]
@iosdev-republicofapps Can you use the OSX Activity Monitor and take a sample of the process that runs hot?
![image](https://user-images.githubusercontent.com/6461412/41150824-382a4f08-6b0f-11e8-9e18-09572813fcb9.png)

**Comment by yeluoqiuzhi** [comment]
I have fixed this by specify Typescript version as v2.8.3.

**Comment by KytoSai** [comment]
I have same issue with you

VSCode Version: 1.25.1
OS Version: 10.13.6

VSCode have process "Code Helper" always run over 100% CPU
Demo: http://prntscr.com/k89vav

Does this issue occur when all extensions are disabled?: Yes

I have attempt to reboot laptop multiple times. But It still happen run over 100% CPU

**Comment by ayyash** [comment]
@yeluoqiuzhi how did u "specify" the version? by installing it again or how is it done?

**Comment by yeluoqiuzhi** [comment]
@ayyash 

https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions
