### ISSUE TITLE
Unverified breakpoint error with build 1.25

### ISSUE THREAD

**Issue by alanosman** [Microsoft/vscode#53785]
I was debugging server side nodejs code using the latest production build (version 1.25) and it was refusing to respect breakpoints that I set.  I had just upgraded from 1.24 and debugging sessions where working fine before upgrading.  

Breakpoints seem to set ok (i.e. you see the red circle) when the code is not running, but as soon as you start running, the breakpoint turns transparent and the code will not break execution.

Mousing over the breakpoint displays "Unverified breakpoint" in the tooltip.

I am using Windows 10, WSL/ubuntu environment with `useWSL:true`

Here's my launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "protocol": "inspector",
            "request": "launch",
            "name": "Run Elastc",
            "program": "${workspaceFolder}/elastc.js",
            "useWSL": true,
        },
    ]
}
```
![image](https://user-images.githubusercontent.com/2914981/42473847-ba40a388-8393-11e8-8e37-9fc67ed8ec15.png)

The fix is to revert back to 1.24 for now.  You can get it from here: 
https://code.visualstudio.com/updates/v1_24

:-(

**Comment by Ventajou** [comment]
I'm seeing the same issue. I've reinstalled 1.24.1 and my breakpoints work again.
Some details on my setup:
- Windows
- code is TypeScript with sourcemaps
- attaching the debugger to Node in a Docker container

**Comment by Alasano** [comment]
+1 

- Windows 10
- useWSL set to true
- runtimeExecutable is yarn

launch type request, used to work before upgrading today. App is regular 'ole nodejs with fancy flavor of the day JS frameworks.

**Comment by Finkes** [comment]
I have the same problem.
Mac OS X, Visual Studio Code 1.25

When using the debugger for NodeJS with Typescript my breakpoints don't get respected

launch.json 

```
       {
            "name": "Start Server",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/dist/server/start.js",
            "stopOnEntry": false,
            "outputCapture": "std",
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": "compile",
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "sourceMaps": true,
            "outFiles": [
                "${workspaceRoot}/dist/server/**/*.js"
            ]
        },
```


I switched back to 1.24.1 and everything works fine again!

**Comment by roblourens** [comment]
Can someone set `"trace": true` in your launch config, try it again, and upload the log here? Thanks

**Comment by roblourens** [comment]
I think the log in https://github.com/Microsoft/vscode/issues/53891 is the same problem (would appreciate anothe rone to confirm)

**Comment by fxlemire** [comment]
@roblourens 
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2177795/debugadapter.txt)

**Comment by alanosman** [comment]
thanks @fxlemire I was going to get to it, been busy today..

**Comment by roblourens** [comment]
Thanks @fxlemire, same issue. 

The fix will be in tomorrow's insiders, I'd appreciate if anyone tries it out.

**Comment by alanosman** [comment]
@roblourens thanks for the quick turnaround..  will try it out tomorrow.

**Comment by fxlemire** [comment]
I confirm, it works on 1.26.0. Thanks for the quick fix @roblourens ❤️

**Comment by weinand** [comment]
@roblourens two users have confirmed that the fix solved the WSL issue too.

**Comment by alanosman** [comment]
Yup - fixed in insiders build:
```Version: 1.26.0-insider
Commit: adfa9ce9778a6e79197477fcc60cb5420a31979a
Date: 2018-07-10T05:19:09.185Z```

**Comment by alanosman** [comment]
Will this make it to the next production release?

**Comment by roblourens** [comment]
Great, thanks for verifying. Yes it will be in 1.25.1.

**Comment by RoyHP** [comment]
Same issue here on 1.25.0, for all of my engineers

**Comment by RoyHP** [comment]
This is still happening for us on 1.25.1 as it was on 1.25.0. Unverified breakpoints when debugging node remotely (via inspector protocol). No issue on 1.24.

**Comment by roblourens** [comment]
@RoyHP please open a new issue and share your launch config. Would be helpful if you can set `"trace": true`, run it again, and attach the log.

**Comment by jaxxreal** [comment]
Hey @roblourens,

VSCode v1.25.1

Here is my launch config:

```
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 9229,
            "address": "localhost",
            "restart": true,
            "sourceMaps": true,
            "outFiles": ["${workspaceRoot}/app/server/src"],
            "skipFiles": [
                "${workspaceFolder}/app/node_modules/**/*.js"
            ],
            "localRoot": "${workspaceRoot}/app/server/src",
            "remoteRoot": null,
            "smartStep": true,
            "trace": true
        },
```

And [debugadapter.txt](https://gist.github.com/jaxxreal/c50b94050cb444407fe0107e291f551d).

Thanks!
