### ISSUE TITLE
Improved column selection (Alt+select)

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode#5402]
The column selection implemented in #1515 is a start, but it's a bit awkward and unintuitive compared to other editors.

With the following editors or IDEs, you can create a column selection starting from where the mouse is clicked/dragged:

* Atom (with Sublime Style Column Selection)
* Eclipse
* Notepad++ ([assumed](https://github.com/Microsoft/vscode/issues/1515#issuecomment-199464559))
* Programmer's Notepad
* Sublime (assumed)
* Visual Studio 2015

At least Eclipse, Programmer's Notepad, and VS2015 support virtual whitespace as well, creating a complete square/rectangle.

Some of them also don't show multiple cursors, which I think looks better.

Other users were also expecting this behaviour (see [here](https://github.com/Microsoft/vscode/issues/1515#issuecomment-199464559) and [here](https://github.com/Microsoft/vscode/issues/1515#issuecomment-205910037)).

**Comment by dvlsg** [comment]
You can knock the assumed off sublime, I can confirm it works that way.

**Comment by IntelOrca** [comment]
This is our target behaviour, and hopefully possible when virtual space is supported.

![vs](https://cloud.githubusercontent.com/assets/5047891/13401144/47e9ea9e-df0b-11e5-8552-f2646376d763.gif)

**Comment by dvlsg** [comment]
Looks good to me, I think.

Is there any hope of support for multi-cursors that aren't necessarily next to each other?

For a contrived example, say I have JSON with integer values, but they really should be doubles. With multi-cursors, I can accomplish that fairly easily. Will this be possible with the proposed block column selection?
![multi-cursor-select](https://cloud.githubusercontent.com/assets/4721566/14652422/18fc0312-0629-11e6-8a3e-cb288920e5bf.gif)

**Comment by alexandrudima** [comment]
Today, the column selection is piggy-backed onto the multi-cursor support (i.e. it is logically represented and consists of multiple cursors). This makes it indeed behave differently than Visual Studio, for example.

@dvlsg We have multi-cursors since v0.1.0. Please see https://code.visualstudio.com/docs/editor/editingevolved#_selection-multicursor

**Comment by dvlsg** [comment]
Oh awesome! My apologies for missing it in the release notes -- thanks for taking the time to add the link, I appreciate it.

**Comment by nholthaus** [comment]
#11830 may provide a more clear description of the expected behavior.

**Comment by IntelOrca** [comment]
@nholthaus unfortunately I don't this can be implemented until they implement virtual space - that should probably a feature request of its own.

**Comment by alexandrudima** [comment]
@nholthaus From #11830 

Most programs with column mode (visual studio/notepad++/kdevelop/etc) have the following user experience:
1. hold the keyboard shortcut/toggle column mode.
2. click somewhere. This is the selection 'start' anchor.
3. drag somewhere. This is the selection 'end' anchor.

This is not how Visual Studio 2015 behaves for me:
* I click somewhere
* I press and hold shift + alt
* I click and drag somewhere else
* the anchor is the location before pressing shift + alt
![shift-alt-vs](https://cloud.githubusercontent.com/assets/5047891/18433772/a76324f4-78e9-11e6-83b0-db101365e1d9.gif)

**Comment by nholthaus** [comment]
@alexandrudima yeah but visual studio also has an `alt` button column mode that does what I described, which is the only one I'd ever use. Visual studio code doesn't seem to have the equivalent, or if it does it doesn't work on linux.

**Comment by alexandrudima** [comment]
Oh, ok, we only added the `shift+alt+` behaviour. IMHO we first need to make the mouse gestures configurable as `alt+` clicking is occupied by adding a new cursor (a feature VS does not have) and then we can allow customizations of the modifiers + clicking and add this other way of column selection

**Comment by nholthaus** [comment]
Cool. I'm not concerned at all if the shortcuts don't match, as long as the functionality could be accessible somehow.

**Comment by nholthaus** [comment]
@alexandrudima Also (on Kubuntu) `alt+click` moves the window, it doesn't add a cursor. Does that sound like I should file a bug report?

**Comment by alexandrudima** [comment]
We have had the report multiple times. It boils down to supporting customization of mouse shortcuts (#3130)

**Comment by IntelOrca** [comment]
@alexandrudima do you intend to implement virtual space in the furture... e.g. hold alt and click somewhere where there aren't any characters yet still have a caret there? Typing then inserts the spaces up the caret automatically.

**Comment by smuuf** [comment]
1. Is there any specific reason why multi-cursor placing is mapped to **ALT** button instead of Sublime-like **CTRL**? I have a history with Sublime (as opposed to, eg., Visual Studio) and **CTRL** is *more natural* to me (I know `me` is not an argument, but ...). *Is this something that could be configurable? I don't see it in keybindings config. :disappointed:* ... If **ALT** is something only Code does, then I would definitely vote for the quickest possible change to **CTRL**-behaviour, so there are as few people as possible who would have to re-adapt.
2. Is there any specific reason why block-selection mode is made with `SHIFT+ALT+LEFT-MOUSE-CLICK` fingerbreaker instead of just `MIDDLE-MOUSE-BUTTON`? Just why? Give us the `MIDDLE-MOUSE-BUTTON` :) *Or give us a configurable keybindings for this. (I, sadly, don't see any for this.)*

I don't mean to nag :) ... I just wonder these questions every time I work with multiple cursors and block selections in Code. Having these features behaving like in Sublime (from which migrated to Code, mainly because of the debugging tools) would be such a workflow-booster! :heart:

**Comment by jminer** [comment]
Editors that could be added to the list are jEdit (it uses `ctrl` instead of the much more standard `alt`, but otherwise works the same as the other listed editors), Qt Creator, and IAR Embedded Workbench.

I think column selection should definitely use `alt+click` because it is the standard shortcut, and placing multiple cursors should use something else.

**Comment by Fania** [comment]
I'm piggy-backing this issue as I think it fits here. 
I'm not sure how to create a fancy video, but I'd like to add that it would be nice to have column select respect (i.e. ignore) the wrapping of long lines of text.
I encounter this all the time in Latex - writing out a list of sentences and wanting to add the "\item" command in front of all of them but it messes up lines that wrap across the page. 
And no, I wouldn't want to disable line-wrapping every time I want to use column select.
Does that make sense?

**Comment by rjmunro** [comment]
It would be good if I could alt-drag without shift.

In general, a drag means select and alt drag means select rectangle. alt-drag works in many other places including away from coding editors, e.g. MS Word & the default Mac OS terminal.

Shift-click means create a selection from the current cursor location to the mouse position. Subsequently dragging it can be used to make adjustments.

The two are separate things that can be used together, or one at a time. alt-drag should start a new selection from the initial click of the drag. shift-alt-click should start the selection from the current cursor position.

**Comment by Jeyanthinath** [comment]
Any updates on this feature request ? 

Because a long time notepad++ users like me find hard to neglect this feature !

**Comment by jnm2** [comment]
Yes! I've been wanting the same thing for months. I want to be able to `Alt` + left mouse drag a rectangle without being affected by the cursor position prior to starting the drag, just like in editors like Visual Studio or Notepad++ or even Word and Outlook.

**Comment by polkovnikov-ph** [comment]
@nholthaus Yes, Ubuntu has this problem with Alt+Drag movement of windows, and it was a big pain for me too. I haven't heard about the same type of interaction anywhere else, so it's likely an issue for Ubuntu.

@smuuf You make a very good point! Shift is supposed to select ranges, Ctrl is supposed to add items to selection. This is the most expected behaviour, and VSCode _must have_ implemented multiple cursors with Ctrl. That'd better be fixed soon, because otherwise [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) would be already broken by non-compliance to legacy behaviour, and VSCode would go in the nice list of Vim and Emacs. But that's, probably, another issue.

**Comment by EthanRutherford** [comment]
I would also appreciate a proper column select, as well as the current column select (along with other key+click type actions) be configurable via keybindings.json

**Comment by RobertBColton** [comment]
+1 Very important feature that I know friends make frequent use of. Would also be nice to see support for elastic tabstops.
http://nickgravgaard.com/elastic-tabstops/

**Comment by xgqfrms-GitHub** [comment]
https://github.com/xgqfrms/xgqfrms/issues/13

**Comment by BrettMoan** [comment]
Being able to do column selection via the middle mouse wheel is literally whats keeping me frmo making VS Code my main editor.

**Comment by abrahaobittar** [comment]
it is interesting to create a function for sum in column mode, just like in uestudio

**Comment by gouletr** [comment]
Any news on this? Tried latest version of VS Code, and indeed box selection works... BUT there's the major drawback that we have to click *before* we press the shortcut to set the box selection start location. Super annoying! 😠 

As others have mentioned, I would expect:
1. hold the keyboard shortcut/toggle column mode.
2. click somewhere. This is the selection 'start' anchor.
3. drag somewhere. This is the selection 'end' anchor.

**Comment by jnm2** [comment]
It has to be <kbd>Alt</kbd>+drag, where the start point is wherever the drag started and the end point is wherever the drag ended. It's so common and so irritating on a regular basis that VS Code is weird.

**Comment by dasDaniel** [comment]
I know I'm late to the party here, but I would love to be able to use the middle mouse button.
click to set start position, drag to select.
I'm not a fan of this three-step process, it feels awkward and I'm having a tough time being productive with it. I keep switching to ST2 frequently whenever I need to do text wrangling.

**Comment by polkovnikov-ph** [comment]
@dasDaniel You're not late to the party. Issues on github need regular messages in them, otherwise they tend to be closed for "lack of support". This is a hot issue for 2 years, and it's a shame nobody's concerned. It doesn't even have a "bug" tag yet. We still need more people who are late to this party.

**Comment by jdmarsh** [comment]
I really want to use visual studio code but this is the only thing stopping me. I use alt+select a lot in a number of text editors and IDEs and visual studio code's inconsistent implementation is much to cumbersome to get used to.

**Comment by DrewTamashi** [comment]
Though its not super ideal i found a bodge for this in Sublime text.
https://www.granneman.com/webdev/editors/sublime-text/packages/how-to-install-and-use-sublime-alignment/
 this is how i'm using it to add mass comments to python code:
1)middle mouse to select the end of the lines that i want comments on.
2)with the delimiter set to "#" i use the alignment package.
3)if needed i use the middle mouse to select behind the "#"s and add more tabs

![masscommentsublime](https://user-images.githubusercontent.com/25192667/32425157-48ab2626-c26e-11e7-9230-0f2794d580a2.gif)

**Comment by boeningc** [comment]
I too vote for middle button column selection.  Coming from SubLime and doing a lot of text manipulation this is definitely essential.

**Comment by EthanRutherford** [comment]
Column selection was mentioned in the roadmap:
https://github.com/Microsoft/vscode/wiki/Roadmap#editor

**Comment by mofahead** [comment]
Sublime user here, trying out vscode for the first time. I’m finding a lot to like in vscode, but the wonky column select behavior is a real turn-off.

**Comment by gingerbeardman** [comment]
I migrated TextMate > Atom > Sublime > VSC

VSC is the only editor I've used where this kind of block select using Alt+mousedrag cannot be activated. 

I miss this feature!

**Comment by NicolasBuecher** [comment]
Also coming from an editor (Webstorm) where I used to abusively alt+click+drag to perform multiline edit.
It seems totally essential for me now.
I don't think there is a better choice between "ctrl" or "alt" for the key. But at least I think it should not be a combination as "shift+alt".
I would love to see this feature coming really soon !

**Comment by Samrux** [comment]
It is absolutely a must that VS Code implements Alt+Drag for box selection. Any respectable editor has this feature.
Shift+Alt+Drag comes close, but it places the anchor at the current mouse position instead of the initial click position like it should and is expected to. Plus, it's very cumbersome to require an additional key for such a simple feature.

**Comment by jnm2** [comment]
It seems like the team may not realize how many times a day we use this feature in other editors and what impact the half-baked implementation is having.

**Comment by gingerbeardman** [comment]
Even the file editor on GitHub supports alt+drag block selection better than VS Code. Come on Team!

![screen shot 2018-03-13 at 09 59 53](https://user-images.githubusercontent.com/49612/37335004-588d41a0-26a5-11e8-81bc-61cc9f167f36.png)

**Comment by TarAlacrin** [comment]
I  straight up deleted this program because of this. I really liked everything else, but it felt like trying to write code in word or something.

**Comment by jnm2** [comment]
@TarAlacrin To be fair... Word has Alt+drag select. 😜

**Comment by BrettMoan** [comment]
> @TarAlacrin To be fair... Word has Alt+drag select. 😜
Shots fired!

**Comment by flowt-au** [comment]
+1. Real pain coming from Sublime Text. :-(

**Comment by kjakobson** [comment]
+1, hopefully we get to see this feature soon

**Comment by Samrux** [comment]
I actually just switched to Sublime Text today for this issue.

**Comment by oddvalue** [comment]
+1

**Comment by oddvalue** [comment]
:+1:

**Comment by deadlydog** [comment]
It seems most of this discussion has been around mouse box selection, but what about keyboard box selection? I assumed VS Code would have functionality similar to VS. i.e. use `alt`+`shift`+arrow key. You can customize the VS Code keybindings [as described in this SO post](https://stackoverflow.com/a/40263968/602585) to get a clunky version of this functionality, but I expected the functionality to be native and work the same way it does in other apps (e.g. Visual Studio, Notepad++).

**Comment by gingerbeardman** [comment]
Even macOS Terminal does this properly.

**Comment by EduardJS** [comment]
@gingerbeardman Yep, looks like we're going to get it. Two years since this was requested 😃 

Fingers crossed

**Comment by gingerbeardman** [comment]
I'll believe it when I use it @EduardJS 

> ![screen shot 2018-04-24 at 11 56 27](https://user-images.githubusercontent.com/49612/39183033-961811c6-47b6-11e8-8d6f-82f1b6fd1499.png)

**Comment by glen-84** [comment]
It's no longer on deck – it's in the backlog.

**Comment by dasDaniel** [comment]
Looks like the latest release allows middle-click dragging. While this doesn't address the original request to use with Alt, I'm glad to see the middle button multi-column selection working

![image](https://user-images.githubusercontent.com/466865/39612012-ee2aff54-4f18-11e8-864f-fe902ae409af.png)

**Comment by gingerbeardman** [comment]
I think two easy changes to make this work more as expected are:
1. moveTo(cursor, x, y, false); // click location when column modifiers are held
2. change column mode modifiers

Surely not much work at all? If I knew where to look i'd create the PR myself. Any hints?

**Comment by EduardJS** [comment]
While what was done is useful, imagine trying to select all the line endings. Check out sublime, and drag the middle mouse over the end of each row.
It simply selects all line endings, which is very useful in a lot of cases.

An workaround as of now is to do the same with only the first char on all lines, and then use the keyboard arrow to go back to the previous line end.

**Comment by janbaykara** [comment]
@EduardJS you can achieve this by selecting the lines you need, then typing cmd-rightarrow (or cmd-leftarrow for beginning of line).

**Comment by EduardJS** [comment]
Yeah, kind of the same workaround, but, wouldn’t it be intuitive to just do the middle button drag they have just added at the end of the lines and work just as intended ?

Maybe I’m nitty gritty here, its just how I used it in all previous editors.

**Comment by Klypto** [comment]
This was very disappointing to come across.  

Is there no way to implement or override to "standard" functionality of ALT + drag??

**Comment by Y-Less** [comment]
Notepad++:

![npp-multi-select-3](https://user-images.githubusercontent.com/991078/40868470-6fb177fa-660d-11e8-99dd-308238be6ca4.gif)

VSC:

![vsc-multi-select-3](https://user-images.githubusercontent.com/991078/40868475-79c38396-660d-11e8-8336-cc8ffd5975b0.gif)

I dragged the mouse in pretty much the same area on both - I expected the text to appear in the same area.  Also, lines were just skipped entirely.  The April update didn't address the issue at all.  I'm not bothered about what the shortcut is - alt+LMB or MMB, but am bothered that it works.

**Comment by punkUser** [comment]
+1... I love a lot of things about VS code, but I use ALT-drag column select a lot in many other editors and having it not present/not work the same way in VS code is currently a deal breaker :(

**Comment by pjv** [comment]
sorry if i am missing something, but after two years of people complaining about this issue, how is it possible that the key combination for column selection in vscode has not been made configurable?

all i want, and it seems like all many people in this issue are asking for, is to be able to trigger column selection with alt-drag instead of shift-alt-drag.

that can't be a thing, can it?

**Comment by punkUser** [comment]
It's not just the key combination, what's there isn't really what other editors implement per se. It needs some actual work as discussed earlier in the issue.

**Comment by pjv** [comment]
>It's not just the key combination, what's there isn't really what other editors implement per se. It needs some actual work as discussed earlier in the issue.

not saying it doesn't need other work, but being able to use a familiar key-drag combo to get what there is now would be an improvement and it should be cheap.

**Comment by punkUser** [comment]
> not saying it doesn't need other work, but being able to use a familiar key-drag combo to get what there is now would be an improvement and it should be cheap.

The issue is what is in there right now (shift+alt) is kind of related to a "different" feature, so ideally what this issue is asking for is *not* to convert that feature into the more common Alt+drag box select, but rather to implement the Alt+drag version in addition.

**Comment by pjv** [comment]
>The issue is what is in there right now (shift+alt) is kind of related to a "different" feature, so ideally what this issue is asking for is _not_ to convert that feature into the more common Alt+drag box select, but rather to implement the Alt+drag version in addition.

ah so. Got it.

still wouldn't hurt for there to be a settings config for the modifier key for both current and whatever future additional behavior may be added.

**Comment by boeningc** [comment]
+1 million.  :)  Just make it work like Sublime and others.  I think that's what everyone really wants.  Make it more standard instead.

Notepad++, Sublime, UltraEdit, even MS Word and Outlook all support ALT+Drag

Maybe I have something amiss in my settings but SHFT+ALT+Drag doesn't work for me (latest May update).  I have to use CTRL+SHIFT.  Even then, the select doesn't start where I click.  It starts where the cursor was.  So if the cursor is at the bottom of the screen and I want to select something at the top, I have to click where I want to start, release, then CTRL+SHFT+Drag.  It bit nit picky but ... :)

**Comment by jordoreed** [comment]
In the words of someone famous and wise, "Give me alt+select, or give me death."

**Comment by ejabu** [comment]
@nholthaus I used kubuntu 18.04, it's best to change Drag Window from Alt + Drag to Meta + Drag.

Window Behaviour > Window Action > Inner Window

![image](https://user-images.githubusercontent.com/2019630/43092229-abcdbd60-8ed6-11e8-9884-d7034b6ae460.png)

**Comment by pawadski** [comment]
+1 on box selection (similar to notepad++), it can be a separate hotkey, whatever, but it's really sad that it isn't in because I am doing my best to like the editor :(

I suppose virtual whitespace needs to exist before this can be achieved?

**Comment by jchatel** [comment]
Holy shit, open thread for more than 2 years with very experienced coder complaining they don't have a critical tool to perform efficiently, and the VS team don't comment (basically ignore this thread) and go on doing other things. That's what happens when you got so much cash than you don't really care about your users.

Can't believe that's the same thing happening with virtual spaces that would make me switch to VS code in no time. Opened for 2 years... (https://github.com/Microsoft/vscode/issues/13960)

Can someone please smack whoever is responsible for product prioritization here?

**Comment by EduardJS** [comment]
@jchatel at least it got “acknowledgement” lol.

Thats one less step :)

**Comment by jchatel** [comment]
I acknowledged your reply @EduardJS

lol

**Comment by o314** [comment]
@jchatel [Embrace, extend, and extinguish](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish)

Solutions :

1. buy linked in
2. buy github

Ah someone just told me it does not work as intented for Oracle with mysql .
Management from the 90s does not have finish sudying yet...

**Comment by pawadski** [comment]
Is it possible to do this with a plugin or something?

**Comment by boeningc** [comment]
Funny thing is with the latest releases the terminal window will do column select with ALT + Click.

Integrated Terminal

Column selection

Column selection is now supported within the Integrated Terminal via Alt+click.

**Comment by janbaykara** [comment]
So this does actually work in VSCode, with `cmd-shift`.

**Comment by gingerbeardman** [comment]
@janbaykara it doesn't work the same as in other editors (including, but not limited to, position of cursor and columns extending into virtual white space), which is the point of this issue "improved column selection"

**Comment by janbaykara** [comment]
@gingerbeardman yeah roger.

**Comment by boeningc** [comment]
CTRL+SHIFT CLICK DRAG works on Windows as well.  What I don't like is say the cursor is at the bottom of the screen and you CTRL+SHIFT and lick on something towards the top.  Your selection starts from where the cursor is at the bottom not where you clicked.  IMO, the cursor should relocate to where you start your click to start your selection.

**Comment by dasDaniel** [comment]
I agree, if I'm dragging and having live response, I would like to see the selection start where I clicked, not where the cursor was before I started. 

Other than that I'm pretty happy with the feature, and I found I was able to live without it for 2+ years.

**Comment by theslyprofessor** [comment]
Bump! Please fix this issue. This was by far my favorite feature of other text editors and this is a deal breaker for me.

**Comment by jordoreed** [comment]
> IMO, the cursor should relocate to where you start your click to start your selection.
Amen, @boeningc! If I don't get this feature I will probably just curl up in a ball in the corner and starve to death. I can't handle not having it.

**Comment by jnm2** [comment]
Hey, anyone want to put up a PR to do the same block selection as Ctrl+Shift+drag when the user does Alt+drag, but which also begins the selection at the mouse down point of the drag?

**Comment by jhe-** [comment]
+1, this is such a useful feature to have and something Notepad++ does perfectly.

Also, can we not _lock_ tickets like #28757 ("Vertical Selection via Alt + {Mouse Select}") indiscriminately? The answer given was completely not was asked for, and there's no way to indicate where to find the duplicates (aka this ticket) since replies are locked to collaborators only.

@CheetahChrome if you are out there, you're not alone brother...

**Comment by CheetahChrome** [comment]
This situation is like nails on a chalkboard for me. The indiscriminate close felt like a slap in the face. Thx.

**Comment by zjturner** [comment]
You can get box-select with Ctrl+Shift -> Drag.  But what I can't figure out is how to get box-paste.  It inserts new lines at the point of paste instead of pasting over existing lines.  Does anyone know if this is possible?

**Comment by Samrux** [comment]
It is not possible, because VS Code still ignores the integrity of an essential feature such as column selection.

**Comment by rcdailey** [comment]
#MeToo

**Comment by jrobiii** [comment]
This is the one of two issues that is preventing me from moving away from a dying product... PowerShell ISE.

**Comment by rcdailey** [comment]
Honest question: Is there a way I can see if the VS Code team even plans to address this? How do they decide what to work on? Is there a roadmap? I know the decision is greatly impacted by number of thumbs up, but that's it. Instead of pinging this issue over and over which is not helpful, I'd like a way to see *when* this will be addressed, to ease my impatience.

**Comment by gingerbeardman** [comment]
@rcdailey https://github.com/Microsoft/vscode/wiki/Iteration-Plans

"Good luck with that"

**Comment by s2t2** [comment]
https://github.com/Microsoft/vscode/issues/28757

**Comment by s2t2** [comment]
has anyone found a way to column select by dragging (on Mac OS)? 

It doesn't matter to me which keys are involved. Although I'm used to either `shift + control + drag` or `control + drag` or `alt + drag`

**Comment by merrillaldrich** [comment]
One more vote here to replicate the Visual Studio experience for "Alt-" click and "Alt-" drag including block, vertical selection and _also placing the cursor and / or the selection out to the right_ past end of line, cleanly and in a vertical line, not ragged with the existing text. To try this open a text file in Visual Studio and alt-click or alt-drag in the area to the right of the text. The new product should just keep that feature.

**Comment by woehrl01** [comment]
Thanks @janbaykara.  On my windows machine, this works with ```ALT + SHIFT + Click``` .

It still behaves differently from the terminal, as it starts the selection from the current cursor position.

**Comment by gingerbeardman** [comment]
3 YEAR anniversary of this issue on 2019-04-16 🤦‍♂️

**Comment by shreeve** [comment]
@gingerbeardman - Take a look at pull request #66445.

**Comment by aaronbushnell** [comment]
Just noting that the [1.32 release has made this exponentially better!](https://code.visualstudio.com/updates/v1_32#_improved-column-selection)

![column selection](https://code.visualstudio.com/assets/updates/1_32/column-selection-alt-key.gif)

**Comment by pawadski** [comment]
Great! Now we just need virtual whitespace and maybe we can finally close this. :)

I think this reply illustrates what virtual whitespace means in practice: https://github.com/Microsoft/vscode/issues/5402#issuecomment-210905314

ie. selection expands on to areas that have no text

**Comment by glen-84** [comment]
Changing the `Multi Cursor Modifier` to `ctrlCmd` breaks the ability to Ctrl+Click on a symbol to view its definition.

**Comment by gingerbeardman** [comment]
>Changing the `Multi Cursor Modifier` to `ctrlCmd` breaks the ability to Ctrl+Click on a symbol to view its definition.

@glen-84 is that a separate bug or not?

**Comment by rcdailey** [comment]
Is there a separate issue for virtual whitespace someone can link to? Or is
that being addressed here?

**Comment by gingerbeardman** [comment]
@rcdailey there isn't one as far as I can see using issues search. Also, nothing is being addressed here by the official developers as they seem uninterested in this area. The only progress we've had IIRC has been from external developers pitching in.

**Comment by IntelOrca** [comment]
@rcdailey 13960

**Comment by pjv** [comment]
> Changing the Multi Cursor Modifier to ctrlCmd breaks the ability to Ctrl+Click on a symbol to view its definition.

@glen-84 not sure which arch you are on, but on Macos, when I changed to crtlCmd to get the new column selection behavior, it also broke Cmd+Click on a symbol to go to its definition, but now if I Alt+Click on it, it does what Cmd+Click used to.

**Comment by glen-84** [comment]
@gingerbeardman,

> @glen-84 is that a separate bug or not?

No, it's not a bug. See below.

@pjv,

Ah, you're right. It's actually documented in the setting description:

> The Go To Definition and Open Link mouse gestures will adapt such that they do not conflict with the multicursor modifier.

I'm quite used to using `Ctrl + click` for `Go To Definition` and `Open Link` though. TBH, I'd prefer:

* `Alt + click` -> Column selection.
* `Ctrl + click` -> `Go To Definition` and `Open Link`
* (something else – maybe `Alt + Shift + click`?) -> Multi-cursor.

**Comment by Ilias48rus** [comment]
Middle mouse button  may be  considered ergonomic, but was it really so difficult to think up to set the box/column selection to RMB dragging? As Atom's package have from the start.

**Comment by JasonYan2015** [comment]
maybe `Alt + click` could work on windows.On my MBP, I tried `control`, `option` and even `command` to get the new column selection behavior.But I failed and didn't know why.
I didn't know how to do it until I googled it.(still could not find it on updates)
just want to say, plz mention a little more about your new features.

**Comment by glen-84** [comment]
@JasonYan2015,

> just want to say, plz mention new features in more detail.

Wasn't [this](https://code.visualstudio.com/updates/v1_32#_improved-column-selection) enough detail?

**Comment by elijahgagne** [comment]
I'm on Windows and I haven't been able to figure out how make `Alt + click` work. I think the release notes had good detail, but it's not obvious to make what to change to enable the new functionality.

**Comment by glen-84** [comment]
@elijahgagne,

It *literally* says to set `editor.multiCursorModifier` to `ctrlCmd` – that's all there is to it.

**Comment by elijahgagne** [comment]
Thanks. I suspected it was that simple, but hadn't found the right place to make that change. I found https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations, and now see that on Windows it's `%APPDATA%\Code\User\settings.json`

**Comment by lucasbasquerotto** [comment]
@elijahgagne You can open it clicking in the `Settings` icons at the bottom left of the window (or `File -> Preferences -> Settings`, you don't need to go to where the file is located in your machine). You can search for `multiCursorModifier` and change the setting. You can toggle between UI and text (JSON) clicking in the icon at the top right of the editor with curly braces (`{}`) if you prefer to edit it as text.

@glen-84 If I define it as `ctrlCmd` it works, but I prefer using `Ctrl` to go to definition (and it may break other stuff like people said above), but defining it as `Alt` doesn't work (I can place multiple cursors, but can't select like when defining as `ctrlCmd`, [maybe some conflict with other shortcuts](https://github.com/Microsoft/vscode/issues/3130)). 

For now I'm letting it as `Alt` and selecting by **pressing the mouse wheel**, like on Sublime Text (fortunately, the mouse wheel works in both cases).

**Comment by JasonYan2015** [comment]
> @JasonYan2015,
> 
> > just want to say, plz mention new features in more detail.
> 
> Wasn't [this](https://code.visualstudio.com/updates/v1_32#_improved-column-selection) enough detail?

well, [this](https://code.visualstudio.com/updates/v1_32#_improved-column-selection) does not tell me that I need another `shift` to make it happen.

**Comment by glen-84** [comment]
@lucasbasquerotto,

> ... but I prefer using Ctrl to go to definition

[I do too](https://github.com/Microsoft/vscode/issues/5402#issuecomment-470999236).

> ... and selecting by pressing the mouse wheel

Oh, that's quite useful. I'd still prefer `Alt + click`, but I'll probably also use this for now.

---

@JasonYan2015,

> Well, this does not tell me that I need another shift to make it happen.

Oh, that's not good. 😐

**Comment by jhe-** [comment]
> Well, this does not tell me that I need another shift to make it happen.

It appears that when Multi Cursor is set to `Alt`, column selection is `Shift + Alt`.
When Multi Cursor is set to `ctrlCmd`, column selection is `Alt` ([and links are Alt+click?](https://github.com/Microsoft/vscode/issues/5402#issuecomment-470976107)).

It looks like progress is being made! It would be nice if the docs were accurate.

More importantly: a good design does not make one shortcut dependent on another, just to avoid collisions. Every other editor lets you configure each shortcut explicitly and tells you if there are collisions (or prevents you from setting the latter if a collision would result).

We'll get there one of these days. :sweat_smile:

**Comment by glen-84** [comment]
@jhe-,

> It appears that when Multi Cursor is set to Alt, column selection is Shift + Alt.

That column selection is different though – it starts from the text cursor instead of from the mouse cursor.

**Comment by robertmiles3** [comment]
I think there might be a small bug with this. With my multi-cursor set to ctrlCmd, I can now alt-select just like Sublime, however it operates differently based on whether you have an actual column selected or not.

**With no column selected** (drag straight down), if I let up the Alt key first and then let up the mouse click, then the cursors stay properly. 
![code3](https://user-images.githubusercontent.com/944302/61637640-eed32480-ac65-11e9-8fa1-5eb422b0a160.gif)

**With no column selected** (drag straight down), if I let up the mouse click first and then let up Alt (which seems to be my brain's default), then the selection disappears.
![code1](https://user-images.githubusercontent.com/944302/61637399-753b3680-ac65-11e9-8a04-65160720b069.gif)

**With at least one column selected**, all works properly regardless of what I let up first.
![code2](https://user-images.githubusercontent.com/944302/61637406-779d9080-ac65-11e9-9f60-6b1994e9316b.gif)

**Comment by robertmiles3** [comment]
Another annoyance that would be a nice fix is when block selecting past the end of lines. I often do this to put a cursor at the end of each line.

**Sublime** works great by putting a cursor at the end of each line as I block select past the end of the lines:
![sublime](https://user-images.githubusercontent.com/944302/61641114-89366680-ac6c-11e9-9b87-8045872c0760.gif)

**VS Code** puts the cursor on each line at the furthest character of the line where the selection started:
![code1](https://user-images.githubusercontent.com/944302/61641189-b08d3380-ac6c-11e9-965c-ba1e3f116744.gif)

**Comment by barkermn01** [comment]
Ss part of this we need a method to control the key because as mac users are used to using Control Key, Windows users are used to using Alt, and VSCode used Alt+Shift.

So please give us a method to set this, even if it's just an option somewhere in the setting to choose between the three options?

**Comment by othyn** [comment]
@robertmiles3 any solution to this yet that you've discovered? Its a real behavioural annoyance for me!

**Comment by robertmiles3** [comment]
@othyn I think the first thing I posted might be fixed. But the second one (end of line) is not. It's still a major annoyance to me.

**Comment by othyn** [comment]
@robertmiles3 Damn... well that's an annoying annoyance! I'm still having an issue with the first one too, both of which are an annoyance coming from sublime.

**Comment by mbentley00** [comment]
It's a little hard to tell from this very long thread, but is there a plan to make Alt + Shift + Arrow work more uniformly compared to Visual Studio? The specific case that VSCode handles differently is:

REPRO:

1. Place the cursor at the start of a line (let's call this Line 3)
2. Press Alt + Shift + Up so that you've selected 3 lines (Lines 1 - 3)
3. Press Alt + Shift + Down

RESULT:

Lines 1-4 will be selected

EXPECTED:

Only Lines 2-3 should be selected. This behavior would match what Visual Studio, Notepad++, SQL Studio, etc. all do. It also more closely matches how text selection in general works.

Here's a video comparing the bad VS code behavior and the good Notepad++ behavior:
![record_000009](https://user-images.githubusercontent.com/8949289/70932440-9de61300-1fee-11ea-882b-ce0e325ccfab.gif)
![record_000010](https://user-images.githubusercontent.com/8949289/70932449-a0e10380-1fee-11ea-8d57-b1d3a50ac600.gif)

**Comment by PeterJeff** [comment]
That sounds like a different issue @mbentley00

**Comment by keremispirli** [comment]
@mbentley00 It seems to be resolved in v1.42.1

**Comment by kanlukasz** [comment]
Nope. If you select a column with the mouse and release the mouse button first, the selection will disappear

**Comment by keremispirli** [comment]
@kanlukasz I was referring to the latest message just above, it is not about mouse, only keyboard.

About the issue you mention: 

- I tried dragging with `Shift+Alt+LeftClick` then releasing the mouse button first, and in my system the selection stays.
- I tried MidClick with and without `Shift+Alt` and the selection stays in both cases.
- Dragging with `Alt+LeftClick` doesn't do box selection at all in my case.

What is the version of your VS Code?

**Comment by kanlukasz** [comment]
Sorry, I thought you were writing in general

If we talk about my issue, I can do this with `Alt+LeftClick` beacuse i set `"editor.multiCursorModifier": "ctrlCmd"`

My env: `Version: 1.42.1` @ `Win10`

**Comment by tytannial** [comment]
Column selection and copy from visual studio to vscode is easy. But how to back.
Column selection copy from vscode to visual studio, VS can't handle that.😭

Version: 1.43.0

**Comment by Felice-Enellen** [comment]
My mind boggles at the fact that a feature as important to people writing code as this is still on the backlog after multiple years and pages and pages of unhappy people wanting it done.

What needs to be done to get this prioritized? Is anyone involved in VSCode dev even watching this issue anymore?

**Comment by gingerbeardman** [comment]
It's their way or the highway.

**Comment by BHare1985** [comment]
I've been using Visual Studio for 5+ years. Finally decided to try out VScode for a php project and the fact alt+drag doesn't work the same drives me nuts.

**Comment by alexreg** [comment]
Agreed... incredible this isn't in a milestone yet!

**Comment by bryankerr1986** [comment]
still can't switch from notepad++ because this feature is not available.... what's taking so long!

**Comment by Felice-Enellen** [comment]
The problem here is that they're trying to emulate column select with multiple cursors. They aren't the same thing. VSCode needs to handle column select the way it's supposed to work, completely separate from the multiple-cursors feature, which is useful in its own way, but absolutely sucks at emulating column select properly.

Just write a freaking column-select feature from scratch! It's work, yeah, but it'll actually WORK, whereas trying to half-ass it with multiple cursors is just a cursed idea that needs to be discarded.

**Comment by Rowan-Mulder** [comment]
Regarding this topic, I've posted a feature suggestion on Visual Studio's Developer Community.
[Multiline selection snapping on each individual line](https://developercommunity.visualstudio.com/idea/1021773/suggested-feature-multiline-selection-snapping-on-1.html)
If I missed an important detail, feel free to let me know.

**Comment by pawadski** [comment]
@Rowan-Mulder see https://github.com/microsoft/vscode/issues/5402#issuecomment-210905314 for virtual whitespace behavior

**Comment by gazzar** [comment]
@Rowan-Mulder I think it's ironic that you're trying to get a feature implemented in Visual Studio that VSCode already implements, whereas this feature request is about trying to get a feature implemented in VSCode that Visual Studio implements. However, I don't see the two features as related.

**Comment by Rowan-Mulder** [comment]
> 
> 
> @Rowan-Mulder I think it's ironic that you're trying to get a feature implemented in Visual Studio that VSCode already implements

I've searched for quite a while looking for a way to make a multiline selection and expand the selection in the width where the selection snapping currently is handled by snapping to a line of main focus where the selection is just a block. I'm looking for an easy way to make a multiline selection and expand the selection in the width by snapping to the end of a word on each line individually. This can only be accomplished by making multiple manual selections and then it functions the same.

This feature has been seen in Sublime text and Jetbrains products like PHPStorm/IntelliJ.

Feel free to correct me if I'm wrong. As far as I'm aware this specific functionality is not included within Visual Studio and I haven't received a notice yet that is the case, in the response I got, regarding the feature suggestion [here](https://developercommunity.visualstudio.com/content/idea/1021773/suggested-feature-multiline-selection-snapping-on-1.html).

**For example**:
[This is the current situation](https://i.imgur.com/4njcT6y.gif)
[This is what some people need](https://i.imgur.com/fcO8jSJ.gif)

**Comment by Orisil1809** [comment]
Hey guys,
I would really love your help!

I'm using VS code and by accident I pressed some keys and somehow the scroll wheel of the mouse is selecting text rather than scrolling the page up and down. I feel like the mouse wheel press is acting like pressing the "alt" key.

I've tried deleting VS code and deleting extensions and such and it didn't work. The problem persists only in VS code.

Is that problem familiar to you?

Do you know how to fix that?

**Comment by gingerbeardman** [comment]
@Orisil1809 this is not the place for support issues. Try StackOverflow or this Microsoft page (select Developer Tools > Visual Studio Code) https://support.microsoft.com/en-us/supportforbusiness/productselection

**Comment by Orisil1809** [comment]
I've tried both ways. Unfortunately no help from both.
I really tried reaching out to many places before I got here.

It seemed to be a similar discussion to my issue. Please if you can help!

**Comment by gingerbeardman** [comment]
@Orisil1809 the only help I can give is to completely nuke your VS code, and all preferences and support files and start again.

**Comment by othyn** [comment]
@tmewett yeah, the way I get around it at the minute is to always highlight the beginning of the line and just use the word/line skip arrow key modifiers to alter the selection. That being ALT + [Arrow Key] for word and CMD + [Arrow Key] for line start/end.

However, what was really easy to do in Sublime and saved frustration was the ability to place the cursor anywhere on the right side of the document, drag down and have the end of each line selected. It made multiline line selection super quick and easy. With the above work around, I still have to be really careful with cursor placement.

As outlined in this reply to this thread: https://github.com/microsoft/vscode/issues/5402#issuecomment-513819635

It's knit-picking I know, but when you get used to a behaviour which makes sense, its hard to not yearn for it again. Its probably my _only_ gripe with VSCode!

**Comment by bivisss** [comment]
I've installed the extension **Sublime Text Keymap and Settings Importer** and it came with this feature.
It's not the real solution, but it is an alternative

**Comment by othyn** [comment]
That comes as a pre-installed extension if you select the Sublime keymap when using VSCode for the first time. Sure, it applies the _keymap_, but it does **not** apply the expected selection behaviour as seen in Sublime, which is what this issue revolves around.

**Comment by Y-Less** [comment]
The issue is a little mixed to be fair.  Half the people are talking about the selection behaviour, and thus virtual whitespace, which is what the original issue was about.  However, a lot of the comments are about the key mappings for doing so.  To me having to press slightly different keys to do it seems like a far less important issue than being able to block select in the first place, but maybe that's just me.  Even the start point of the selection (click position vs current cursor position), which is another thing frequently mentioned, can be configured, extended, worked around, or learnt once the core problem is solved.

**Comment by EngineLessCC** [comment]
Its getting ridiculous that such an important editor-functionality is after 4 years of being an issue still not fixed/implemented/solved or misunderstood.
I just cant use vscode like it is.
Its weird that notepad++ still beats it for me, whereas vscode is a much proper solution for most needs.

**Comment by dralley** [comment]
I use a mix of Sublime Text and VSCode, and the lacking functionality in this area keeps me on Sublime 90% of the time.  Rectangular / multi-select in VSCode is just so painful in comparison.

**Comment by gingerbeardman** [comment]
I'll be holding a 5 year vigil for this feature on twitter #altselectvscode

> 16 April 2021

Your name is already on the guest list. 

Be there or be a rectangle of selected text.

**Comment by cvbge** [comment]
Is it possible to write an extension for this?

**Comment by gingerbeardman** [comment]
I don't believe it is, due to insufficiencies in the API.

**Comment by elijahgagne** [comment]
I hope VS Code gets this feature some day. I just learned how to do it in Vim. 
```
:set virtualedit=all

ctrl-v (enter visual block mode)
# Select column/rectangle

A (enter insert/append mode)
# Enter text

Esc
```

**Comment by velociwabbit** [comment]
I just tried the new vs code and the default for rubberband (column) select even when you set vscode  key bindings to visual studio is still shift alt. 

why not just make it shift I alt (think about it :) )

This is an unforced error that will really anger visual studio users who are forced to use vscode. It is why vscode has such a terrible reputation as an editor with really experienced software developers. 
 
Even  Balmer would know better (i can think of no greater condemnation) .

**Comment by byehack** [comment]
it is not `feature-request`, it's `bug`. please **FIX** it.

**Comment by robertjpayne** [comment]
Yea coming from Sublime and not being able to remap this it just "alt + drag" is really frustrating :( wish this was something we could customise.

**Comment by AuracleTech** [comment]
This is still not done !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Since 2016 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Can anyone powerup this issue or something, don't you realize how powerful this simple function is?

**Comment by m6502** [comment]
@AuracleTech This needs implementing #13960 first, but that one has been open since 2016 too. I would really, really like to understand how it's possible these basic and common features are not there since day 1.

**Comment by Jijjy** [comment]
6 whole years lads, for a simple and ubiquitous feature. Embarrassing.

**Comment by gingerbeardman** [comment]
Happy Birthday! My daughter is also 6.

**Comment by sirdeniel** [comment]
Use `shift + alt` for rectangle selection. This issue should be closed now.

**Comment by velociwabbit** [comment]
it should be closed because ???? it is not standard, the workaround is not
the same as compatible

Closing implies resolution. Is the resolution that this is a permanent bug
that is not going to be fixed?

Or is this just a cynical closing of a legitimate issue to distort the
statistics of code quality?

**Comment by gingerbeardman** [comment]
That shortcut you mention is not the feature that is being requested. What you're suggesting is linked in th OP as #1515 but it's incomplete and lacking.

**Comment by robertjpayne** [comment]
I think there's two issues being bundled here:

1. Requires virtual space and allows "overselection" where you can just straight up box select"
2. Is already implemented with "middle mouse button" where you can do a multi-line select starting from the mouse.

All I want is a match in Sublime and many many other editors where alt+click and drag starts a multi-line select from the cursor. Basically can we please keybind what the middle mouse down selection is already doing?

**Comment by velociwabbit** [comment]
I am frankly stunned that this issue has not been addressed.

The general consensus among experienced developers is that the vscode editor compared to visual studio is a toy.  This is one single issue that one can point to to show how half baked the product is. 

The ONLY rationale for not fixing this is that it would accelerate the movement from visual studio and its high corporate cost and therefore revenue to vscode.

**Comment by Felice-Enellen** [comment]
> 2. Is already implemented with "middle mouse button" where you can do a multi-line select starting from the mouse.

Pretty sure that's also using multiple cursors to simulate rectangular selection. It's not really rectangular selection, just a quick way to set up a bunch of cursors, each with their own selection attached.

**Comment by arjan-saly-tfs** [comment]
We're very close to 6 years (!!) since this feature was requested. Many other editing solutions support virtual/implicit spaces for column selection. Even SQL Server Management Studio (SSMS), which is primary targeted for database management and also support database development supports this for many years. SSMS doesn't even come close to VSCode capabilities with respect to powerful code editing.

I'm a database & SQL specialist, not a a developer, but cooking at the capabilities of vscode like multi-select/edit, how can it be that vscode developers are not capable to add virtual spaces?

What does it take to get vscode developers to finally adopt this suggestion and implement it?

Until this is implemented, has anybody found an extension that adds this feature?

**Comment by mxmlnkn** [comment]
I'm gonna unsubscribe from this issue. I don't see it happening anytime soon. And after using vscode sporadically, my two other main gripes with it are the memory bloat for something as simple as a text editor. Because of that, other stuff gets OOM-killing, especially during parallel compilation. The other gripe is the lack of responsiveness for simple stuff like scrolling or moving the cursor, especially for things like larger syntax-highlighted markdown files. I'm happy with SciTE + the command line. Maybe I'll even migrate to vim in the next decade, who knows.

**Comment by gingerbeardman** [comment]
Yeah, I'm out too. Life's too short. Deleted VScode.

**Comment by velociwabbit** [comment]
I have concluded that vscode  is a toy created by second rate coders more
interested in getting the right answer from their teachers than getting the
product right.

It is useful for things that do not require creative innovation such as SSL
connections or github.

the rest of it is worse than doggy doo doo

**Comment by Felice-Enellen** [comment]
I agree. VSCode feels more and more like it's written by a bunch of glue-logic "coders" who are committed to feature creep over quality and basic functionality. The electron/cef bloat is ridiculous and the functionality is substandard and implemented with sledgehammers. I'm tired of waiting for simple stuff like this to be done while I see more and more bloat being added with every release. If I wanted to use a js-encrusted browser window to edit code, I'd buy a Chromebook, not a PC.

Time to find something else.

**Comment by m6502** [comment]
> I'm also still waiting for this - thanks for keeping hope alive! I think Visual Studio 2022 has it, in addition to Visual Studio 2015 (!) as noted above.

Of course they have it. This is not an "advanced" or "modern" feature. The "real" Visual Studio had it already in the 1990s. I repeat. DECADES ago. Virtual Space has always been an obvious standard out-of-the-box feature that any editor had, that has been lost to the sands of time only because a series of unfortunate coincidences about what was favored by a series of fads.

**Comment by velociwabbit** [comment]
I did some work at MS a few years ago as a consultant.  I was shocked at
the change in culture from when I worked with them in the 80s and 90s.  It
used to be that ms was notorious for untoward behavior externally but very
tolerant of any behavior that led to getting products done that would
dominate the market.

Their culture has changed dramatically.  They have become a woke version of
1980s HP where perceived social faux pas were fatal but poor product
delivery was tolerated.

HP proved that well-mannered but second-rate employees eventually turn a
competitive company into a consulting zombie.

They have a slam dunk with Azure but will mess it up because a person's
performance has a lower priority than behaving in a  culturally
acceptable fashion.

The only people I met I respected there have left.

**Comment by chaoticbob** [comment]
Anyone else still waiting for Alt + select?

**Comment by Clonkex** [comment]
I find it utterly baffling that it's been OVER 7 YEARS since this was requested and it's still ignored. Not only that, but the keyboard shortcuts make no sense at all. Check out this insane behaviour:

```
editor.multiCursorModifier = alt:
- Ctrl+drag: regular select
- Alt+drag: regular select
- Ctrl+click: go to definition
- Alt+click: create multiple cursors

editor.multiCursorModifier = ctrlCmd:
- Ctrl+drag: regular select
- Alt+drag: block/column select
- Ctrl+click: create multiple cursors
- Alt+click: go to definition
```

??? This proves that modifier+drag select is fully possible and supported. They clearly took the keyboard shortcuts, multi-cursor mode setting and functionality and just threw dice to decide how they should be connected. Not only does modifier+drag select functionality disappear entirely if you use the default `alt` setting, but if you use the `ctrlCmd` setting, the function to create multiple cursors is on a _different key_ to modifier+drag select functionality! Who _does_ that??

**Comment by jgwinner** [comment]
Good grief. I just tried to see what box select was for the Mac and stumbled here.  What a mess. For the record, I use both Mac and PC. 

Subscribing.

**Comment by chaoticbob** [comment]
> I find it utterly baffling that it's been OVER 7 YEARS since this was requested and it's still ignored. Not only that, but the keyboard shortcuts make no sense at all. Check out this insane behaviour:
> 
> ```
> editor.multiCursorModifier = alt:
> - Ctrl+drag: regular select
> - Alt+drag: regular select
> - Ctrl+click: go to definition
> - Alt+click: create multiple cursors
> 
> editor.multiCursorModifier = ctrlCmd:
> - Ctrl+drag: regular select
> - Alt+drag: block/column select
> - Ctrl+click: create multiple cursors
> - Alt+click: go to definition
> ```
> 
> ??? This proves that modifier+drag select is fully possible and supported. They clearly took the keyboard shortcuts, multi-cursor mode setting and functionality and just threw dice to decide how they should be connected. Not only does modifier+drag select functionality disappear entirely if you use the default `alt` setting, but if you use the `ctrlCmd` setting, the function to create multiple cursors is on a _different key_ to modifier+drag select functionality! Who _does_ that??

If it wasn't for the HLSL highlighter, I would've bailed.

**Comment by velociwabbit** [comment]
Because of this insanity and the overall lack of precision of the vs code
editor I  have reverted back to visual studio.

And visual studio search is so bad now that i have implemented my own
system to do complex searching.

Ms internally is a sh__storm of woke stupidity (and i am a progressive)
and the coder quality is at best pedestrian.

I almost prefer the borg version (but not really)

**Comment by Felice-Enellen** [comment]
> Because of this insanity and the overall lack of precision of the vs code
editor I  have reverted back to visual studio.

I feel much the same. This project is doomed to eternal glue-logic and feature creep with very little apparent skill or care. The amount of memory it uses just to be a text editor is atrocious, never mind the lack of movement on basic universal needs while the strangest, most niche platform compatibilities are added ad nauseum has made my mind up for me. I'd never used Sublime before, but now I've tried it and it is absolutely the minimalist editor I want. I don't need an IDE capable of tracking my every thought and integrating with a hundred different languages. I just need a decent code editor. I'm out, goodbye VSCode, it seriously hasn't been nice to know ya.

I recommend someone on the steering team for this project open their eyes to just how horribly bloated and misdirected it is. Recruit some senior software engineers, and I do mean literally senior, and ask them what's wrong with it, and do what they tell you to do, e.g. make it 10x more modular so it's not taking up gigs of memory, focus on getting the actual TEXT EDITING solid and complete, etc.

**Comment by velociwabbit** [comment]
I agree with you.

**Comment by ZiperRom1** [comment]
02/29/2024, still not possible to bind mouse wheel click to

```
editor.multiCursorModifier =
```

And so cannot select multi lines with my mouse only like in JetBrains IDE :sigh:

**Comment by rainbowjose** [comment]
Still waiting

**Comment by TurkeyMan** [comment]
Why is virtual-whitespace still pending? We've been waiting over a decade now!
Rectangle selection doesn't work without virtual whitespace... it's practically unusable; you encounter a line gap and end up with a random cursor at the start of the line where all the others are lined up vertically as they should be.

This is the only reason I don't use VSCode, but the pressure to move to VSCode is constantly increasing as VS-proper continues to lose relevance...

Please can someone actually comment on why this is still pending, and if it's ever coming?

**Comment by Felice-Enellen** [comment]
FYI for other people subbed to this issue, there is work being done on virtual space:

Mentioned at the (current) tail end of #13960, in [this comment](https://github.com/microsoft/vscode/issues/13960#issuecomment-2394182862) by the change's author, @x17jiri. See the comment for details on the fork where it's being worked on and possibly doing testing for them.
