### ISSUE TITLE
Visual studio code stopped working after latest update. Tried uninstall and reinstall still not working

### ISSUE THREAD

**Issue by vsawant1608** [Microsoft/vscode#56810]

**Comment by vsawant1608** [comment]
OS :- Windows 7
VS code setup file used :- VSCodeUserSetup-x64-1.26.1

**Comment by n8harmon** [comment]
I uninstalled the latest update and reverted back to 1.25: https://code.visualstudio.com/updates/v1_25 and I'm back up and running.

**Comment by joaomoreno** [comment]
@vsawant1608 What happens when you try running it?

**Comment by n8harmon** [comment]
@joaomoreno I can't speak for @vsawant1608, but I can tell you the steps that triggered the problem for me as well as the steps I took to troubleshoot it.

1. I installed the 1.26.1 update suggested when I opened up VS Code
1. I waited for the application to open back up after the installation completed, but it did not auto-restart
1. I attempted to start the application by running `code` from the command line.
1. I attempted to manually start the application by clicking on the code.exe file, and even tried starting it with elevated permissions

Each time I attempted to start the application, nothing happened, so I began further troubleshooting:
1. I searched the application logs for errors, but could not find anything out of the ordinary, so
1. I rebooted my system just to ensure a restart didn't resolve the problem
1. I downloaded the latest Windows installer from here: https://code.visualstudio.com/download (VSCodeUserSetup-x64-1.26.1.exe)
1. I uninstalled VS Code and reinstalled using the above installer, and I continued to experience the same problems, so
1. I uninstalled VS Code again and then downloaded and installed 1.25 from the installer found here: https://code.visualstudio.com/updates/v1_25

I'm currently running on version 1.25 without any issues.  Now that I'm looking closer at the latest download page I wonder if this has anything to do with the User installer vs the System installer.  I don't have time at the moment to test out whether the same problem occurs with the System installer, but if I'm able to before you find a resolution to this problem, I'll report back my findings.

**Comment by vsawant1608** [comment]
@joaomoreno I faced the exact issue as described by n8harmon . I just took latest update as suggested by vs code update notification. It did nots tart the visual code automatically. So I went and manually tried to start the vs code. however nothing happened.

I then restarted the system and tried opening vscode again. nothing happend.

I installed previous version and it worked. For that previous version also I tried taking the update and ended up with same situation.

**Comment by TurtleGamingFTW** [comment]
I'm on v1.27 on Insiders and i am having the problem where intellisense doesn't even show up

**Comment by joaomoreno** [comment]
> I uninstalled VS Code and reinstalled using the above installer, and I continued to experience the same problems, so

@n8harmon  This is interesting. Can you try this, but this time run it in a command line with `code --verbose`?

**Comment by n8harmon** [comment]
@joaomoreno I ran `code --verbose` prior to running the update again and received the following output:

> [main 5:04:13 PM] Sending env to running instance...
> [main 5:04:13 PM] Sending some foreground love to the running instance: 6280
> [main 5:04:13 PM] Sent env to running instance. Terminating...
> [main 5:04:13 PM] Lifecycle#kill()

I then ran the 1.26.1 update and executed the `code --verbose` command again.  The application did not start nor was there any output on the command line.  I went ahead and uninstalled and reinstalled with the system installer and received the same results.  I've reverted back to 1.25.1 again and everything is back to normal now.

**Comment by joaomoreno** [comment]
> received the same results

These results are what Code returns if there's already a Code instance running. Can you restart your system, to be sure there's no Code running?

**Comment by SKKOVVURI** [comment]
Same results like everybody mentioned above.. No output for `code --verbose` with **vscode x64 1.26.1**.
No other instance of **code.exe** running on my Win7. Also restarted the system but didn't help.

```
PS C:\Users\skovvuri> code --verbose
PS C:\Users\skovvuri>
```

**Comment by darekkay** [comment]
I did exactly the same as n8harmon described (except that I did not downgraded, yet).
Latest code version won't start, both "regular" and "user" versions. `code --verbose` does not print anything. I did a clean install/reboot and confirmed that no (other) code instance is running.

Maybe this helps debugging the issue: I'm having exactly the same problem with Slack Desktop app version `3.1.0` and up. Nothing happens when the app is started. Slack `3.0.5` is the last working version. I'm only mentioning it, as both VSCode and Slack use Electron under the hood, so this might be connected. 
Additionally, the issue occurs only on Windows 7 (but for everyone on my team using this OS).

**Comment by bpasero** [comment]
@darekkay any difference if you directly execute code.exe instead of our link?

**Comment by darekkay** [comment]
@bpasero There is no difference using:

a) `Visual Studio Code.lnk` on the desktop
b) `Code.exe` in the app folder
c) `Code.exe --verbose` in command line
d) `Code.exe --verbose` in command line with admin rights
e) `Code.exe --verbose` in PowerShell
f) `Code.exe --verbose` in Git Bash

I sometimes see `Code.exe` appear in the Windows Task Manager for a split of a second, but mostly not even that.

**Comment by bpasero** [comment]
I wonder if this is a crash in native code. Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by bpasero** [comment]
@darekkay great, any chance there is a stacktrace or more logs to look at?

**Comment by darekkay** [comment]
Unfortunately, that's all I've got in my `Logs\Crash...` folder. I followed the linked guide, but instead of selecting the `Code.exe` process I just typed it into the input field (as the process never runs to select it from the list). But this rule still creates to attached log files.

**Comment by bpasero** [comment]
@darekkay how about running VSCode from a zip archive directly: [download](https://az764295.vo.msecnd.net/stable/493869ee8e8a846b0855873886fc79d480d342de/VSCode-win32-x64-1.26.1.zip)

**Comment by darekkay** [comment]
Sorry, no difference here (both 32 and 64 bit) :disappointed: 

However, after trying to start Code.exe  a few more times, I got twice a Crash Log including an exception (this was not connected to a specific version):

[vscode-crash-log-with-exception.txt](https://github.com/Microsoft/vscode/files/2339817/vscode-crash-log-with-exception.txt)

**Comment by bpasero** [comment]
@darekkay thanks, I just searched for that exception and some forum suggests to uninstall a software called `EasyConnect`, do you happen to have that installed?

**Comment by darekkay** [comment]
No, I don't have it installed.
However, this is a corporate laptop and assuming this issue is not reproducable for most people, it might be some pre-installed software interfering here.

**Comment by bpasero** [comment]
Ok was worth a try ;)

**Comment by aeciolevy** [comment]
So far on Mac OS X subtleBrackets is broken with 1.26.1 version.

**Comment by darekkay** [comment]
I decided to downgrade to `1.25.1`, too, with no issues so far. 
I hope this issue gets resolved, but I can understand how hard it is, when the maintainers cannot reproduce the problem and we can't offer anything more than "it does nothing" :disappointed:

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by darekkay** [comment]
The issue still exists in this version

**Comment by SebastianMCarreira** [comment]
I was just running with1.27 and found a very similar issue. 

Reinstalled VS because I wanted to have the context menu options I forgot to tick when I installed it in my PC some days ago. After the reinstalling, the issue started.

The window did open but in some ocassions the nonly the gray background was loaded, other times, alse the bottom purple line and the left lighter  bar loaded too but nothing else. The process also spiked my CPU usage for 25% (I7-7700) without doing anything else. Tried running `code --disable-extensions` but still the same. Running `code --verbose` showed a lot of errors of the program trying to read non existant files in the logs directory. Tried deleting the whole code directory in roaming but didn't help. Also tried `code --verbose --disable-extensions` and had the exact same output @n8harmon  had. All this was done in Win 10 with the cmd with administrator privileges.

I have just installed 1.25 and it works just fine. Hope the issue gets fixed soon.

**Comment by keeborg** [comment]
I've got the same issue as **SebastianMCarreira** above. Uninstalled 1.27.0 version and installed 1.25. Hope the issue will be fixed.

**Comment by bpasero** [comment]
I wonder if this is the same as https://github.com/Microsoft/vscode/issues/47883. Do people have non-ASCII characters in their username?

**Comment by bpasero** [comment]
Yeah true story.

**Comment by ndite** [comment]
Same issue here. It doesn't start, regardless of shortcut, executable or "code --verbose" with no output. (Win 7 Pro)

It happened with 1.26.1 as well tried now 1.27.1. I'm back to 1.25 for now...

**Comment by tigerscar** [comment]
True for me, too. There are different instances of Code running in Windows Task Manager (Win 7 Pro).

![grafik](https://user-images.githubusercontent.com/1917355/45948379-031fa400-bff8-11e8-8732-2022ca3dbb5d.png)

**Comment by enisdenjo** [comment]
What happened to me is:
1. `cmd + Q` to shutdown VSCode
2. Immediately after VSCode closed, mac went to sleep all of a sudden (crash to sleep?)
3. Logged back in, VSCode crashes on start... No logs with `--verbose` or any other flag (`--disable-extensions`, `--disable-gpu`, etc.)

`Visual Studio Code - Exploration` starts without problems, however no extensions, presets, configs, nothing...

**Comment by tigerscar** [comment]
This problem could be an issue of our corporate endpoint security. This morning an Firefox update also ended in an non-killable process after applying an update. Have to research more.

**Comment by atticusmiles** [comment]
Ran into this problem since 1.26.0, problem still exists in 1.28.
code --verbose shows no message
back to 1.25.1..

**Comment by tigerscar** [comment]
Our IT department informed me about a folder, which is excluded from the scan functionality of the endpoint security. I installed 1.28.2 in there. Currently without any problem. This seems to fix this issue for me.

**Comment by LiEyWe** [comment]
I experience the same issue after updating to 1.29.1
Going back to an older version doesn't fix the issue.

**Comment by MA-Norouzifar** [comment]
same issue and can't fix it 

https://github.com/Microsoft/vscode/issues/64064


i very very bad and no one answer me or tell me how can i fixed it

**Comment by hossmf** [comment]
> 
> 
> I have the same issue with v1.28.2

The last problem is fixed with 1.29 but now it doesn't open when there is no internet connection. 😂

**Comment by jonathan-zageno** [comment]
I don't know which version I had installed, but this morning I couldn't start code on OSX any longer. So I went back to version 1.25.1 and it works fine.

**Comment by manztihagi** [comment]
Seems has a problem on me also, I use 1.29.1 and sometimes all plugins off even intellisense not working also. need to restart then back to normal. 

but this is very disturbing for me when do coding then all function was stopped. 
I think have to revert to old version 1.25.1 

OS: MacOS Mojave

**Comment by jonathan-zageno** [comment]
For me 1.28.2 works.

**Comment by manztihagi** [comment]
@bpasero : I've been trying for vs code exploration for mac, unfortunately the problem still persist with regular vscode ... all plugins off including intellisense.

@jonathan-zageno where i can get that version ?

**Comment by bpasero** [comment]
If anyone has Cylance Antivirus running on macOS, crashes can be explained (see https://github.com/Microsoft/vscode/issues/62628)

**Comment by jonathan-zageno** [comment]
@manztihagi if you type `code --version` in the command line you'll get the version.

**Comment by GbolahanA** [comment]
I have the same issue with 1.30.1 but apparently it opens as long as there's an Internet connection otherwise it doesn't. All this after uninstalling and then reinstalling only to find out that it needed an Internet connection as @hossmf said

**Comment by TheKamakaZi** [comment]
I recently started running into a similar problem, but do have some output from `code --version`:

`[main 7:00:12 PM] Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:74:478
    at t.e (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:74:792)
    at new t (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:76:307)
    at t.e.with (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:75:521)
    at Object.t.normalizePath (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:88:339)
    at e.parseUri (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:462:72)
    at e.doGetWindowsFromLastSession (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:461:243)
    at e.getPathsToOpen (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:459:410)
    at e.open (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:453:185)
    at t.openFirstWindow (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:499:565)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:495:66
    at t.e.invokeFunction (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:220:247)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:495:30
    at n.Class.define.cancel.then (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:108:201)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:494:959
    at n.Class.define.cancel.then (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:108:201)
    at t.startup (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:494:385)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:506:508
    at Object.v [as _notify] (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:101:572)
    at Object.enter (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:104:924)
    at n.Class.derive._creator._run (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:106:790)
    at n.Class.derive._creator._completed (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:106:231)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[main 7:00:12 PM] Lifecycle#kill()
[main 7:00:12 PM] telemetry/optInStatus { optIn: true }
[main 7:00:12 PM] telemetry/update:win32SetupTarget { target: 'system' }`

Version info:
`[main 7:00:12 PM] Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:74:478
    at t.e (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:74:792)
    at new t (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:76:307)
    at t.e.with (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:75:521)
    at Object.t.normalizePath (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:88:339)
    at e.parseUri (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:462:72)
    at e.doGetWindowsFromLastSession (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:461:243)
    at e.getPathsToOpen (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:459:410)
    at e.open (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:453:185)
    at t.openFirstWindow (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:499:565)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:495:66
    at t.e.invokeFunction (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:220:247)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:495:30
    at n.Class.define.cancel.then (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:108:201)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:494:959
    at n.Class.define.cancel.then (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:108:201)
    at t.startup (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:494:385)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:506:508
    at Object.v [as _notify] (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:101:572)
    at Object.enter (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:104:924)
    at n.Class.derive._creator._run (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:106:790)
    at n.Class.derive._creator._completed (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:106:231)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[main 7:00:12 PM] Lifecycle#kill()
[main 7:00:12 PM] telemetry/optInStatus { optIn: true }
[main 7:00:12 PM] telemetry/update:win32SetupTarget { target: 'system' }`

**Comment by jryannel** [comment]
For me it seems an old instance was running. On Mac use activity monitor (or htop) to search for processes named "code". You should see a bunch of code helper processes. Kill them one by one. I used htop for this *F4 Filter" and then "F9 Kill".

Afterwards vscode opens again.

**Comment by ebukab** [comment]
hey this helped me . Go to the extensions tab , click on an extension (preferably one of less importance ) , disable the extension , then press the reload button to reload vscode again . This worked for me

**Comment by bpasero** [comment]
I am closing this issue as there is no actionable change for VSCode.
