### ISSUE TITLE
Marketplace is offline [workaround found!]

### ISSUE THREAD

**Issue by RevoluPowered** [Microsoft/vscode#57851]
VSCode marketplace is completely down for me.

https://marketplace.visualstudio.com/VSCode - gives me this message

![image](https://user-images.githubusercontent.com/748770/45025478-82423d80-b033-11e8-8682-9f2f6d2fc6b8.png)

Can you please investigate?

**Comment by anwar3606** [comment]
same what happened?

**Comment by alronay** [comment]
same here, looks like it's down

**Comment by RevoluPowered** [comment]
The server died from the looks of it, It will probably be fixed within a few hours or a day or so.

**Comment by AdamModus** [comment]
I also just noticed it. Good luck with fixing it Microsoft!
I'm confident it'll be fixed in a matter of hours 🙂

**Comment by dapen85** [comment]
@RevoluPowered It's clearly a broken robot, his wires are hanging out.

**Comment by JamieG** [comment]
@dapen85 Obviously, the front fell off.

**Comment by deanchalk** [comment]
Damn, have neem toying with the idea of getting into QSharp, went to download it and there's a broken robot. The Multiverse is trying to tell me that Im not in a suitable superposition

**Comment by RevoluPowered** [comment]
I reported it to VSTS on twitter too, so it should eventually be fixed lol, I don't think they're checking github atm.

**Comment by RevoluPowered** [comment]
"Apologies for the inconveniences, Gordon. 

Our team is already working on this issue. Stay tuned for the latest updates here: http://msft.social/wApOP9 .

Regards."

**Comment by MLefebvreICO** [comment]
They should at least implement something in VSCode saying the server is down or something, because right now, you just see that there is no results for your search terms.

**Comment by RevoluPowered** [comment]
They definitely do need to.

**It's pretty serious whats going on: (will definitely have broken other stuff too - on azure) **
Users located in South Central US will be unable to access their account until the underlying issue is resolved. Other regions may experience high failure rates and load times due to dependencies in South Central US. We are working to mitigate the impact for users outside of South Central US to the best of our abilities.

**Comment by calvinanderson** [comment]
Same here in South Africa.  And this on the day that I need to preview some markdown in the browser!

OS X 10.13.6 and VSCode Version 1.26.1, Johannesburg, ZA for reference.

**Comment by mkisp** [comment]
I badly need Prettier. To bad the marketplace is down :package:

**Comment by hungminhtran** [comment]
can't believe it down LUL

**Comment by RevoluPowered** [comment]
It's effecting everyone. No updates.

Offic365, Azure, VSCode, VS Team Services, Windows Update will probably be effected too.

Reports in my office of their other platforms slowing down (Azure, Office365) because of the cooling failure in one data center.

Checked with my sysadmin and he is experiencing issues with it too.

**Comment by mglgmz** [comment]
Inspecting marketplace API responses for visual studio code looks bad:
![image](https://user-images.githubusercontent.com/20958398/45038346-6b9de580-b037-11e8-9852-3fa998e3f9ca.png)

**Comment by RevoluPowered** [comment]
Do you think they're potentially causing VSCode to point at another domain

if so, should we even have it open until this is fixed..?

**Comment by cspotcode** [comment]
@mglgmz FYI the "malicious" key in the response appears to be a long-standing feature for blacklisting scams, etc: https://github.com/Microsoft/vscode/issues/42115 https://github.com/Microsoft/vscode/issues/41608

**Comment by RevoluPowered** [comment]
ah right, that's good to know.

**Comment by mayuroks** [comment]
Just installed Visual Code for the first time and this happened 😄. 

Since this issue has been going on since more than 5 hours, I am guessing it's a big one. I will just wait till tomorrow and keep an eye on this thread.

**Comment by vor0nwe** [comment]
Probably related to Azure problems:

https://azure.microsoft.com/en-us/status/

> Starting at 09:29 UTC on 04 Sep 2018, customers in South Central US may experience difficulties connecting to resources hosted in this region. Engineers have isolated an issue with cooling in one part of the data center, which caused a localized spike in temperature, as the preliminary root-cause, which has now been mitigated. Automated data center procedures to ensure data and hardware integrity went into effect when temperatures hit a specified threshold and critical hardware entered a structured power down process.  Engineers are now in the process of restoring power to affected devices as part of the ongoing mitigation process. 
> 
> Some services may also be experiencing intermittent authentication issues due to downstream Azure Active Directory impact, and engineers are separately working on mitigation options for this also.

**Comment by mglgmz** [comment]
@cspotcode yes, I was just freaking out about that one. thanks.

**Comment by leosussan** [comment]
@mayuroks Same =P

**Comment by tiescoo** [comment]
+1.

**Comment by RevoluPowered** [comment]
We just moved our shit off azure last week. Saved by the migration :)

**Comment by michaelchemani** [comment]
+1

**Comment by mittalyashu** [comment]
Any plans to implement this https://github.com/Microsoft/vscode/issues/57851#issuecomment-418376651

**Comment by issafram** [comment]
It is funny that Azure AD being down will affect almost all services

**Comment by sendittokeith** [comment]
Installing Updates ... this may take a while

**Comment by RevoluPowered** [comment]
@issafram It really outlines how much AD has not moved on since windows NT 4.0 was released.

It's a shame the technology hasn't been upgraded to support multiple master nodes, we had this issue at work, our forest main DC died, and we had to do horrible hacks to promote another server to master.

it has no real good redundancy in this regard.

I wonder if they will have troubles getting the AD services back up, because of this issue.

**Comment by insetavijit** [comment]
same no ext found !! waht's going on

**Comment by ZealJared** [comment]
> a localized spike in temperature
...? It **was** Labor Day.
![datacenterlaborday](https://user-images.githubusercontent.com/6157005/45046509-3ab7b380-b02b-11e8-845d-02755cbcfed0.png)

**Comment by RevoluPowered** [comment]
**MS Employee:** "Sorry, was in the data-centre and was using one of the racks to cook my sausages, it said "Primary AD NODE", it was really hot so I used that."

**Comment by MiguelArmendariz** [comment]
I need a plugin for vue xD and.. it's down..  Guess I'll code without format :D

**Comment by ragaar** [comment]
@mayuroks what did you do !? 😱

**Comment by RevoluPowered** [comment]
I think we should make a sister vscode project, with all the plugins while microsoft resolves this 'issue'.

A plugin to download decentralised plugins from another server would be great.

We could host it on AWS and Google cloud 😆 🤣

**Comment by daiky00** [comment]
when is this going to be fix?

**Comment by RevoluPowered** [comment]
I put the wires back in but, still no luck.

![image](https://user-images.githubusercontent.com/748770/45047916-58f4d200-b072-11e8-8214-8278845a023e.png)

**Comment by RevoluPowered** [comment]
@daiky00 probably in the next 6-72 hours.

**Comment by issafram** [comment]
@daiky00 they are aggressively competing with Comcast with that recovery time window

**Comment by RevoluPowered** [comment]
@issafram but then they would have to give a REAL update with extra downplaying, and super soft "we didn't fuck up, it was the weather"

**Comment by issafram** [comment]
@RevoluPowered funny you say that because they already mentioned temperature
![image](https://user-images.githubusercontent.com/650211/45048636-6eee9c80-b04a-11e8-956f-e165d43d2494.png)

**Comment by daiky00** [comment]
@issafrank you mean this is net neutrality stuff?

**Comment by RevoluPowered** [comment]
Scotty: "our 500 watt electric coolers cant take take it captain, we have too many servers"
Kirk: "dammit scotty, put more servers in the data center; we need more power!"
Scotty: "she cannie take it captain!"
Kirk: "scotty i believe in your abilities"

**Comment by issafram** [comment]
They should host the Azure Status site on AWS or Google Cloud.  500 errors on status pages are always funny

**Comment by RevoluPowered** [comment]
Does anyone know of where the packages are stored?

We could potentially provide a link for people to access them and install them manually?

**Comment by RevoluPowered** [comment]
"Mitigation efforts continue. Services in South Central US and other regions may experience impact. Engineers are seeing signs of recovery for some services. Please refer to your Portal - http://aka.ms/uafpoewF  Status Page -  http://status.azure.com  and/or Twitter for updates."

**(translation)**
AD services still fucked, nothing has changed, MS worries about their share price.

**Comment by RevoluPowered** [comment]
**If you need to get your hands on an extension you can potentially use this old method.**

1. Find the github repo of the plugin you need.
2. Go to releases
3. Download the vsix file from the (stable) release.

This will not work for all plugins, because they might be on other sources

C++ tools can be found here:
https://github.com/Microsoft/vscode-cpptools/releases

Python plugin can be found here:
https://github.com/Microsoft/vscode-python/releases

Omnisharp (C#) plugin can be found here.
https://github.com/OmniSharp/omnisharp-vscode/releases

**Comment by akhilome** [comment]
@mayuroks So code's marketplace went down because you came onboard. 😂

**Comment by issafram** [comment]
They should really start delivering on that cloud data center in the ocean.
Won't get any overheating issues.

**Comment by RevoluPowered** [comment]
Further on this..

sometimes clicking that file doesn't work.

You have to go into vscode and hit install from VSIX.

![image](https://user-images.githubusercontent.com/748770/45050330-e804e880-b078-11e8-8369-fe8a084cf5c7.png)

**Comment by MiguelArmendariz** [comment]
@RevoluPowered Thanks for the advice! it worked for the plugin I needed

**Comment by RevoluPowered** [comment]
@MiguelArmendariz glad that it worked :)

**Comment by vsambor** [comment]
I'm opening `VSC` after like 5 months, just to install a new theme... but guess what, exactly at that moment they are facing problems... It happens the same when I used `npm`... :(  I should probably stop using technology :-|

**Comment by RevoluPowered** [comment]
You could find the theme's github and do my workaround above @vsambor

**Comment by suarezluis** [comment]
And there I was uninstalling and re-installing, resetting my connections and some other witchcraft  lol

**Comment by RevoluPowered** [comment]
@mkisp here is the plugin URL for the prettier thing.

https://github.com/prettier/prettier

Unfortunately they don't have a plugin available to download from their repository.

**Comment by mausworks** [comment]
Thank good for Google and "Install from VSIX", also, for Microsoft publishing their releases to GitHub as well.

Hope you get your poor Azure servers fixed soon! :+1:

**Comment by daiky00** [comment]
So this is not going to be fix today I guess?

**Comment by Medy111** [comment]
lolz man Im just in the setup section  of a course .... and cant install the required plugins xD

**Comment by casualblair** [comment]
@daiky00 https://blogs.msdn.microsoft.com/vsoservice/?p=17405&utm_source=Direct  
Next update is in 14 minutes.

**Comment by casualblair** [comment]
@medy111 Which plugins?  You might be able to download and install the .vsix files manually

**Comment by Ch3ck** [comment]
Seems marketplace is down for me too, I'm trying to install Simple React Snippets and Prettier plugins. Any timeline as to how this might be fixed?

**Comment by casualblair** [comment]
I just built the Prettier plugin.  Download the source code for the VSCode version (I Used 1.6.1).  Open the folder in VSCode.  Open the terminal.  Type npm install, then npm install -g vsce, then vsce package

It will create the vsix package you can install temporarily.

**Comment by klick-barakgall** [comment]
Some plugins you can just download the entire repo files, and unpack it in ~/.vscode/extensions/*/

E.g., https://github.com/ronnidc/vscode-nunjucks

**Comment by adrianoviana87** [comment]
Same here (Brazil).
No extensions are found :cry:

**Comment by bradley-varol** [comment]
Perhaps I'm ignorant but I'd have thought an issue like this would have been resolved much faster considering the size and resources of Microsoft.

**Comment by issafram** [comment]
It is funny because they made their distributed services dependent on
non-regional services. AD breaks and all dependent resources as well.
IMO poor design

**Comment by souths** [comment]
How long will it take

**Comment by syk543277780** [comment]
LOL. people believe MS can fix this in few mins. However it already take few hours. The problem still there. and one of my Azure app service down as well.

**Comment by iscclin** [comment]
It's hard for MS to maintain a software :)
Sucks!

**Comment by umaranis** [comment]
Over 15 hours... still not working :)

**Comment by umaranis** [comment]
Over 15 hours... still not working :(

**Comment by cloudbring** [comment]
I guess I gotta fire up atom...

**Comment by Echo-Peak** [comment]
There are only a couple reasons I can think of why this issue is happening and is not fixed still:
1. Microsoft tried to test Windows 11
2. A small drop of water from an employee fell between the cracks of the "Marketplace" mainframe and caused a "class 4 catastrophe"

**Comment by christian-chen** [comment]
How long does it takes to recover ?

**Comment by Subwater** [comment]
Update?

**Comment by justnowanna** [comment]
+1008611 same here.

**Comment by zigang93** [comment]
can someone share how to share plugin to other vscode? can't wait for fix now..

**Comment by GalileoFinchDudi** [comment]
I can't download about python plugins,I hought is my VPN problem.

**Comment by mammenj** [comment]
still down :( , throw the redundancy out the (ms) window ;)

**Comment by justnowanna** [comment]
@zigang93 There is a solution, just on windows, but I think it's same to Mac OS. Copy C:\Users\your name\.vscode\extensions all folders to other vscode's extensions folder. Hope to help you.

**Comment by zigang93** [comment]
@justnowanna thanks. will try it out

**Comment by zigang93** [comment]
@Subwater can check the update from here : https://azure.microsoft.com/en-us/status/
or follow vscode at twitter

**Comment by LiliPaulucci** [comment]
Still offline in Australia too.
I downloaded the extension I needed from github and added to .vscode/extensions.
Looks fine

**Comment by benwinding** [comment]
Okay... so it's still down, should I use Sublime Text in the mean time?

**Comment by sreemat1993** [comment]
marketplace is up now.Extension is working...

**Comment by bobwhitten** [comment]
Well, I thought it was up...  oh... OK, now it is.

**Comment by auchenberg** [comment]
Hi 👋

Our marketplace is slowly coming back. You should be able to search and download extensions again. 

We are terrible sorry for the inconvenience this outage has caused. 

We'll be following up with a post-mortem of this incident soon.

/k

**Comment by omt66** [comment]
Marketplace still cannot be accessed (as of 5 Sept 2018/Wed)!

**Comment by ramchava** [comment]
The marketplace is up now. I can able to install extensions :)

**Comment by mittalyashu** [comment]
Yes, facing the same problem.

**Comment by zubhav** [comment]
I can access the marketplace now at https://marketplace.visualstudio.com/VSCode. But cant search for any extensions in VS code itself. Running on macOS High Sierra

**Comment by rumbles404** [comment]
i need the extensions :( But thank you for confirming

**Comment by zubhav** [comment]
Hmm, seems like search API is broken at the moment. Cant search on the website or app

**Comment by zubhav** [comment]
@rumbles404 if you need extensions, you can install it via the web for now. Just try google 'extension-name vs code marketplace' and install from there

**Comment by GitForge** [comment]
so its not installation problem at my end .. Server end problem.

**Comment by MLefebvreICO** [comment]
So @auchenberg any chance you can implement https://github.com/Microsoft/vscode/issues/57851#issuecomment-418376651 into VSCode ?

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/57901

**Comment by yojkim** [comment]
Is this problem resolved?

**Comment by desi-kt** [comment]
The problem still exists 'No extensions found' - fedora 27.

**Comment by JannikZed** [comment]
Actually I'm facing the same problem on macOS 10.13.6 , Code Version 1.27.2, no errors in any logfiles.
