### ISSUE TITLE
Corrupted terminal and minimap textures after sleep

### ISSUE THREAD

**Issue by dazzag24** [Microsoft/vscode#58167]
- VSCode Version: 1.27.1
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. Open terminal
2. Sleep laptop
3. When reopened text in terminal is garbage.

![screenshot from 2018-09-07 09-13-01](https://user-images.githubusercontent.com/1055831/45207152-1c49f600-b27f-11e8-8555-a2d5c25a80b5.png)

**Comment by Tyriar** [comment]
This is a bug in Chromium.

**Comment by gocarlos** [comment]
@Tyriar reference to that chromium bug?

**Comment by Tyriar** [comment]
I don't have a link, I believe the first report for this was https://github.com/Microsoft/vscode/issues/30292

**Comment by DarrenCook** [comment]
Same here (I would have left a comment on #30292, but it is locked)

I've been assuming it is something to do with the nvidia driver; though it only happens in vscode. It is not just the terminal, also the minimap, and sometimes other bits of the UI, such as the search box. 

Typing reset in the terminal did not reset it. Resizing the pane also did not.

What does work (both for terminal and the minimap) is altering the zoom. E.g. ctrl + then ctrl - and it is back. So, as long as vscode has a way to recognize when a suspend/restart has happened, it should be able to force the screen rewrite? I.e. what function is triggered by changing the font size, that doesn't get triggered by just changing the pane size?

**Comment by bpasero** [comment]
@Tyriar maybe [`here`](https://github.com/Microsoft/vscode/blob/2c3eb2364cca81c87d590e50ec17c95e57046d85/src/vs/code/electron-main/app.ts#L113) and then send a IPC message to all windows. Alternatively we could expose an event on `IWindowService` everyone in the renderer could register to.

**Comment by Tyriar** [comment]
This is now fixed for the terminal.

@alexandrudima you can fix the minimap issue by forcing a redraw when this event fires:

https://github.com/Microsoft/vscode/blob/1c7194ad5d3b07faddf1297a8e332bf406213c96/src/vs/workbench/parts/terminal/electron-browser/terminalService.ts#L72-L74

I would have done it, but I don't know enough about using electron APIs in monaco components.

**Comment by bpasero** [comment]
I think to be able to use this in the standalone editor it has to be wrapped around some service, unless we want to move this into the codeEditor contrib of the workbench.

**Comment by alexandrudima** [comment]
I've adopted the event in the editor too.

**Comment by supirman** [comment]
@alexandrudima does fb4f36c fix apply to terminal also?

I am running 1.31.0 on Ubuntu. My vscode terminal still have this issue.

**Comment by Tyriar** [comment]
@supirman https://github.com/Microsoft/vscode/commit/1c7194ad5d3b07faddf1297a8e332bf406213c96 fixed it for the terminal, you might be seeing this issue? https://github.com/Microsoft/vscode/issues/68346

**Comment by aibtcare** [comment]
I don't know if this is the right place to post this, but I was getting similar issues in Chrome, so I posted a bug report on their website. Link if anyone has anything to add to it: [https://bugs.chromium.org/p/chromium/issues/detail?id=932219](https://bugs.chromium.org/p/chromium/issues/detail?id=932219)

**Comment by supirman** [comment]
@Tyriar probably that is more accurate, since it no longer corrupted, morelike invisible.
Thanks.
