### ISSUE TITLE
Git: Support opening repositories on symlinked paths

### ISSUE THREAD

**Issue by mrded** [microsoft/vscode#5970]
- VSCode Version: 1.0.0 (1.0.0)
- OS Version: OSX 10.11.4 (15E65)

Steps to Reproduce:
1. Create a new project with git repository initialised.
2. Create a folder /foo/bar
3. Add a symlink from /foo/bar to /bar `ln -s /foo/bar .`
4. Go to **Git** tab on vscode, and stage `/bar` folder.

If now you click on staged `/bar` folder, you'll get an error `Warn: Can't open this git resource.`

**Comment by jeremyjjbrown** [comment]
VS code does not see symlinks at all for me on OSX. This is an absolute blocker to constructing a workspace and steps on "The Principle of Least Astonishment"

**Comment by jeremyjjbrown** [comment]
It would be nice to find nested git repos as well. Some of us are fortunate enough to not code on Monoliths.

**Comment by mightypenguin** [comment]
It would be nice to have an option to NOT do GIT change tracking inside symlinks. If my symlink is to another folder in the same git repo I don't want the changed files showing up twice in Code's Git view.

**Comment by joaomoreno** [comment]
This issue is about displaying symlinks in the git view and what happens when you click them. Neither Code nor git follow (or should follow) the symlinks.

**Comment by mightypenguin** [comment]
Ok, off topic, but I am seeing VScode following symlinks in the git view. Running "git status" does not show these files. Should I create a new issue or discuss this somewhere else?

**Comment by joaomoreno** [comment]
Can you take a screenshot to show me what you mean?

**Comment by mightypenguin** [comment]
I know what causes it.
The git repo is a remotely mounted fuse file system.
The linux terminal shows permissions and symlinks properly, but for some reason vscode isn't.
If I create a simple git repo with a directory and a symlink to that directly it works properly on my local filesystem. If I move that to the fuse mounted file system it confuses vscode.

Here's my mount command:
sshfs hostname:/home/user/ /home/user/ -o sshfs_sync -o sync_readdir -o follow_symlinks -o kernel_cache -o max_background=50 -o big_writes

**Comment by joaomoreno** [comment]
Actually, no more errors when you click it. We handle it nicely, even with decorations.

**Comment by joaomoreno** [comment]
We just can't handle the root being a symlink in itself.

**Comment by hyperfekt** [comment]
Staging ranges of a file opened through a symlink is broken as well, and will lead to weird behavior where instead the file that is the symlink has the selected range staged and every other line from the target is displayed as changes in the symlink file in the git side bar.

**Comment by ryansully** [comment]
This issue, specifically git gutters not displaying but maybe others as well, also occurs for remote symlinked git repos using the [Remote - SSH](https://code.visualstudio.com/docs/remote/ssh) extension.

**Comment by JustinAddams** [comment]
Can confirm, no Git gutter's when using a symlinked path in Remote WSL (Though other Git features seem to work fine)
But if I navigate to the same path using /mnt/c and start up "code ." it all works fine.

**Comment by seanknox** [comment]
is the issue with the Remote SSH extension (and thus bugs/work should be tracked there) or with vscode itself?

**Comment by dulinux** [comment]
Same issue here whn working on a linked folder. If a open the target folder, it works. If a open the symbolic link, gutter annotations won´t work.

**Comment by Throne3d** [comment]
Is there a way to recognize this from the extension, and perhaps provide an error in some log (like the Git log)? I don't know the internals work of these extensions work, but it took me a lot of Googling to find this error – the keyword I was missing was "gutter".

**Comment by dileepkr** [comment]
I am facing the same issue when using RemoteSSH for VSCode. Git gutter works on files with full path but doesn't work on same when opened with relative path.

Is there a solution for this problem?

**Comment by AddictArts** [comment]
Open the non-symlinked path worked for me, but I had the same issue Feb 26, 2020.

**Comment by AddisonG** [comment]
Yeah, this is pretty terrible. I've used all sorts of other OS-level hacks to get around this issue.

**Comment by tungel** [comment]
> Yeah, this is pretty terrible. I've used all sorts of other OS-level hacks to get around this issue.

Do you mind sharing what you did to work around the issue?

**Comment by AddictArts** [comment]
I navigated directly through /mnt/c/... I had the project symlinked from $HOME/project. Just needed to use an absolute path from root.

**Comment by molinav** [comment]
I have a very similar issue, a `$HOME` folder built on login as symlink to a folder in `/mnt/home`. If I open my project with the path containing `$HOME`, all the Git decorations are missing. If I open the same project with the real path that uses `/mnt/home`, then the Git decorations appear as normally.

**Comment by arnauldvm** [comment]
The issue also impacts the "Timeline" view introduced with the March Upgrade.

&rarr; Opening a project through a symlink: no git decorations, timeline view empty

&rarr; Opening a project through "actual" path: all git decorations, timeline view filled with git history

**Comment by TimofeyBiryukov** [comment]
Getting the same issue. Using remote wsl. Can't use `/mnt*` to store any of the project files due to the https://github.com/microsoft/WSL/issues/4197 and running `code .` from symlink in `/mnt/*` will lead to this.

**Comment by hariadiarief** [comment]
I got same problem, I have two WSL on my computer, WSL version 1 and 2.

On my WSL version 1, source control is running well. But on WSL version 2, version control only detects changes after restart vscode. I also have done Symlink but it's still not working.

**Comment by qguv** [comment]
Not much discussion here, but it looks like a lot of people are having the same issue with git integration breaking when symlinks are involved, see #94851, #89464, #82873, microsoft/vscode-remote-release#309, #60010, #57580. Is there any plan to work on fixing this issue?

I don't think the "feature request" label is appropriate here; this appears to be a bug, since the underlying tool (git) doesn't seem to have trouble dealing with symlinks.

**Comment by cotneit** [comment]
In case someone needs a workaround:
```bash
function codeSymlinks() {
  if [[ -e "$1" ]]; 
  then
    code "$(realpath $1)" "${@:2}"
  else
    code "$@"
  fi
}

alias code='codeSymlinks'
```
**Explanation:** 
if directory or file exists, its absolute path will be passed to VS code alongside with other parameters; 
if directory or file doesn't exist, it will just pass all the arguments to VS code
**Usage:** just add it to your .bashrc or .zshrc

Works fine for me, feel free to tweak it if you find any issues

**Comment by PrzemyslawKlys** [comment]
I've just been told my issue with git 2.28 is because of this 4-year-old issue. I use symlinks on Windows. The thing is - it works fine when I'm using Git 2.23. So you may want to try Git 2.23 (originally reported my issue here: https://github.com/microsoft/vscode/issues/103798) 

I link the whole folder from C drive to OneDrive. 

![image](https://user-images.githubusercontent.com/15063294/89552382-5aa21400-d80c-11ea-8197-21ca9047ed3d.png)

You can try 2.23, maybe it will work for you?

**Comment by YuvalFatael** [comment]
Experiencing the same issue (using git 2.23.3), my entire homedir is a symlink. When accessing the workspace with the realpath everything works normally.

**Comment by neilpalima** [comment]
I am using WSL2 and encountered this issue.  I hope this will be fixed soon.

**Comment by xploSEoF** [comment]
4 years of this being an issue - I guess it's low priority. Unfortuantely, most of us who use WSL find `/mnt/c/folder`, or worse `/mnt/c/Users/username/folder` to be way too long and operate on a `/f/folder` kind of basis for our main projects via a symlink.

**Comment by MrHedmad** [comment]
I am but a beginner but I've stumbled in this bug (feature?) while migrating from my Ubuntu workstation to a Windows environment. My VsCode explorer git colours were not showing, until the real path was used instead of the symlink.

For anyone like me who would like some dirty fix, just pipe the resolved path to `code`. From inside the WLS: `realpath [SOMEPATH] | xargs code`. To avoid typing all that every time, define a function (I saved it in my `.zshrc`, but it should work identically in bash):

`function vscode{
    realpath $1 | xargs code
}`

So you'd just go: `vscode [SOMEPATH]` instead of `code [SOMEPATH]`. I really hope this will get sorted out soon(tm).

**Comment by NightMachinary** [comment]
VSCode just crashed my Macbook when editing files inside a symlink that pointed to its parent (`/project/src` -> `/project`). Fix your infinite loops.

**Comment by wscnd** [comment]
@dbaeumer  Was having the same issue described in [microsoft/vscode-eslint#309](https://github.com/microsoft/vscode-eslint/issues/1075), it seems to me that it's related to this one.

**Comment by martindale** [comment]
I'm adding another $300 bounty to this issue; as mind-boggling as it is to see it still be a problem 5 years later, we're still losing productivity to the crashes and long delays associated with the occasional use of SSHFS for remote editing.

**Comment by dragonly** [comment]
Currently the local issue is fixed.
But when I use Remote - SSH extension, and open a symbolic linked git repo, the file changes are gone.

**Comment by excelsi0r** [comment]
> I am but a beginner but I've stumbled in this bug (feature?) while migrating from my Ubuntu workstation to a Windows environment. My VsCode explorer git colours were not showing, until the real path was used instead of the symlink.
> 
> For anyone like me who would like some dirty fix, just pipe the resolved path to `code`. From inside the WLS: `realpath [SOMEPATH] | xargs code`. To avoid typing all that every time, define a function (I saved it in my `.zshrc`, but it should work identically in bash):
> 
> `function vscode{ realpath $1 | xargs code }`
> 
> So you'd just go: `vscode [SOMEPATH]` instead of `code [SOMEPATH]`. I really hope this will get sorted out soon(tm).

Add some issues in bash
This did the trick in `~/.bashrc`:

`function vscode { realpath $1 | xargs code; }`

**Comment by Migelo** [comment]
Just chiming in that I support solving this issue as I lost about a two days trying to get my git gutter indicators to shown only to realize my home folder on the remote machine is symlinked.

**Comment by adekmaulana** [comment]
this is the most annoying bug i've ever encountered yet still not fixed after 5 years

**Comment by macsz** [comment]
Was reported in 1.0.0, I am on 1.61.0-insider and it still does not work 😢  While not a show stopper, it is certainly an inconvenience when working on a distributed setup.

**Comment by fsievers** [comment]
I'm affected by the same bug. I need this symlink support, because all my projects reside in a directory on another mount-point and symlinked into my home directory.

**Comment by AlexHarn** [comment]
Still a very annoying issue for me too. I work a lot on cluster dev nodes via SSH and the entire home dir is dynamically loaded through symlinks, no way of replacing it with absolute paths.

**Comment by wesley-cheek** [comment]
Agreed. This needs to get fixed.

**Comment by samarth-robo** [comment]
This issue affects ROS uses who symlink various directories in the `src` directory of their catkin workspace.

**Comment by marcitqualab** [comment]
# Main description.
I have found different problems when adding a folder to the workspace / open a project when that project is in a path with a symbolic link on a parent directory. 

For example. /home/user/project being a symbolic link to /home/user/other/customer/whatever/projects.

This issue is not related to any language, extension or configuration settings. I had this problem with totally different projects and computers.

# Steps to reproduce:
1. Create a sample project in a directory structure few levels deep in /home/user. i.e /home/user/a/b/c/d/project
2. Create symbolic link /home/user/project -> /home/user/a/b/c/d/project
3. Open folder or Add folder to workspace using the symbolic link /home/user/project
4. Try to run tests using Test Explorer

Actual: Looks like the tests are running but test status never change from not runned status.
Expected: Tests are actually runned and report the correct test status, pass or fail.

# Notes
With this scenario I had found at least two problems. 

1. Git status coloring of changed files was not working well. There is an [open issue](https://github.com/microsoft/vscode/issues/70963#) for this already. 

2. In a Python project, the Test Explorer finds the tests but is not running the tests. The icons to run the tests are not available either when editing test files, at least with pytest. 

I suspect that many other issues would have the same root cause. 

Mean while this is not fixed. Maybe useful to at least add a warning or notes in the main documentation that opening a new project from a path with symbolic links might include some inconsistencies.

**Comment by byerun** [comment]
This problem also occurs on Windows when the drive portion of the path pointing to the git project is a subst drive. For example, if I open vscode as shown below I don't see git related modifications shown in the gutter nor does the commit history show up in the timeline view:

```
subst p: c:\Users\Byron\dev\projects\
code p:\project1
```

**Comment by usoonees** [comment]
In my case, gutter doesn't show if the folder path contains a `.`, like `/home/user.focus/folder`

Change the path to one without `.` works for me.

**Comment by starfishpatkhoo** [comment]
> This problem also occurs on Windows when the drive portion of the path pointing to the git project is a subst drive. For example, if I open vscode as shown below I don't see git related modifications shown in the gutter nor does the commit history show up in the timeline view:
> 
> ```
> subst p: c:\Users\Byron\dev\projects\
> code p:\project1
> ```

I can confirm this behaviour in VSCode 1.67.2 .. both native git gutters without any extensions installed, and with gitlens installed..

If you open the workspace file inside the subst drive, gutter annotations and modifications and file modification status won't show up. But if you open the same workspace file directly from the non-subst drive, then everything shows up and works as expected. Again, true for both native gutter display, and with gitlens installed.

I've also tried to make sure all the folders both subst and original have been trusted by workspace trust - to no avail.

Is there some reason why this does not work? Or some reason why it (seems like) will not be resolved after 6 years and numerous duplicate issues raised and closed? Maybe something in the manual/readme/known issues/wiki.. ?

**Comment by ispanos** [comment]
On Fedora 36:
```
code -v                
1.68.0
4af164ea3a06f701fe3e89a2bcbb421d2026b68f
x64
```
it is not fixed.

**Comment by TimofeyBiryukov** [comment]
On Windows 11 Pro (21H2) with wsl2 Ubuntu 20.04.4 LTS with VSCode 1.68.1
Creating a symlink in `/mnt/c/User/...` to a folder in `~`. 
The problem persists.

**Comment by austinwitherspoon** [comment]
Adding that this issue also exists with DFS file system links (which appear and likely function similar to symlinks.)

The git gutter was working fine, we changed our network storage to use DFS to manage our project files, and suddenly vs code stops showing git changes.

**Comment by H0w4rd** [comment]
Today I decided to test VSCode and encountered this bug. It is really terrible and should be really fixed.

**Comment by hungtcs** [comment]
+1

**Comment by AnonymousWP** [comment]
I don't understand why it suddenly stopped working for me. I always open my repos through GitHub Desktop. The only thing that changed is that I now sign my commits with an SSH-key instead of GPG. If I don't open it through GH Desktop but through a folder, it does work. Is there any workaround?

**Comment by wmmc88** [comment]
I'm still encountering issues with this on W11 + VS Insiders + having a directory junction in the path. The Source Control tab correctly detects changes, but the File Explorer tab + the gutter indications are both not functional. Is someone on the vscode team working to address this issue?

**Comment by frankli0324** [comment]
I propose `git rev-parse --path-format=relative --show-toplevel` instead of just `--show-toplevel`

**Comment by YijiangPang** [comment]
VSCode Version: 1.79.2 (Universal)
OS Version: macOS 13.4 (22F66)
remote OS: Ubuntu 22.04.2 LTS (through extension remote-ssh v0.102.0)

the bug still exists where the changes cannot be tracked by git if the project fold is a soft link.

**Comment by lszomoru** [comment]
@frankli0324, thank you very much for pointing out the `--path-format` flag that was added in git `2.31`. 

Todays VS Code Insiders release (v1.81) contains code changes to better handle repositories that have symbolic links on their path. I have confirmed that 1) diff decorations in the editor as working as expected, 2) resources in the "Source Control" view are opened correctly. The only known issue that I am tracking is that there are cases in which the same repository is duplicated, which I am looking to address early next week.

It would be great if people using symbolic links would download and install the latest VS Code Insiders release, upgrade to git 2.31 and try things out so that we can find some of the issues that are still present that I might have missed. Thank you very much for your help and apologies that it took so long to get this addressed

**Comment by Migelo** [comment]
Works for me! ❤️

**Comment by lszomoru** [comment]
> The only known issue that I am tracking is that there are cases in which the same repository is duplicated, which I am looking to address early next week.

Today's Insiders release (2022-07-11) contains the fix so the issues mentioned above. Let me know if you still see any issues.

**Comment by lszomoru** [comment]
Given the positive feedback and no new issues reported I will go ahead and close this issue as resolved. In case any of you find any issues with the symbolic link support please file a separate issue and mention this one for reference. Thank you!

**Comment by brando90** [comment]
@lszomoru I'm having a similar issue. The issue is due to the permission for https://github.com/microsoft/vscode-remote-release/issues/8731 outlined there.

**Comment by brando90** [comment]
Ok the issue seems to be particular to my cluster that is set up in a ridiculous fashion. There is a odd token kerberos thing that they over manage (mentioned here https://unix.stackexchange.com/questions/724685/how-does-one-authenticate-with-a-command-that-requires-your-password-in-linux) anyway once I run reauth it works. So make sure your permissions are right, for me it was through by getting the token again. The symlinks refreshed by themselvers.

soln: https://stackoverflow.com/questions/76725830/how-to-make-explorer-in-remote-shh-extension-in-visual-studio-code-vscode-do/76732251#76732251
