### ISSUE TITLE
Restarting the debug process fails

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/vscode#60593]
Issue Type: <b>Bug</b>

When I'm restart the debugging process of an ASP.Net Core project, in the latest release of VSCode, the debug process will be killed **after** the build process has started. So the build process fails because the output .dll is still in use and can't be replaced.

Error MSB3027

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.7
xml|Dot|2.3.2
tslint|eg2|1.0.40
beautify|Hoo|1.4.4
angular2-switcher|inf|0.1.9
docomment|k--|0.1.2
mssql|ms-|1.4.0
csharp|ms-|1.16.2
vsliveshare|ms-|0.3.788
debugger-for-chrome|msj|4.10.2
createGUID|nwa|0.0.2
sass-indented|rob|1.4.9

</details>

**Comment by isidorn** [comment]
This is a regressoin from our side.
Previously on restart we would first disconnect and only then run the `preLaunchTask`. Now we would first run the task and only then disconnect.
With the fix, I am bringing back the old proper behavior.
@NCC1701M Can you please try vscode insiders tomorrow and verify this ifxes the issue for you?

Adding candidate to discuss if this fix should be included in the recovery build

**Comment by NCC1701M** [comment]
@isidorn I'm sorry but I'm not in the office until wednesday. But I can check it then.

**Comment by isidorn** [comment]
@NCC1701M better late than never, thanks for reporting this!

**Comment by joaomoreno** [comment]
@isidorn Moving this out to October as discussed.

**Comment by isidorn** [comment]
fyi @gregg-miskelly and @DustinCampbell in case people hit this and complain in your repository that you are aware of this regression we introduced which is fixed in insiders. In stable it will only be availble when we do our next large release start of november.

**Comment by isidorn** [comment]
@gregg-miskelly I see it is three users and the issue imho is not critical because if the user starts debugging again all should be good.
It would be great if you just let those users know that they can use vscode insiders as a workaround. And in the future we should try to increase insiders coverage to hopefully find issues like this earlier

**Comment by winzig** [comment]
Thanks guys, I was one of those users, and can confirm the latest code-insiders is working fine.

**Comment by winzig** [comment]
I take it back, still experiencing it. However, I'm going to assume at this point that the update I picked up today is not the update discussed above.

**Comment by isidorn** [comment]
@winzig if you got a stable update today - that one does not inclue the fix.
The latest vscode insiders includes the fix. Can you please try insiders

**Comment by winzig** [comment]
@isidorn Yeah I was using code-insiders yesterday when I saw it, but today at any rate I'm fully updated on insiders again and cannot reproduce the issue, so appears to be working, thanks!

**Comment by isidorn** [comment]
After discussion we decided to have ths fix for our second stable recovery build which we plan to do next week.
Can you please verify with this build if your issue is fixed? Thanks a lot!
windows: [download](https://az764295.vo.msecnd.net/insider/42a5edfb6da4e9af7ea65123a1dc3cf23541df1b/VSCodeSetup-ia32-1.28.1-insider.exe)
mac: [download](https://az764295.vo.msecnd.net/insider/42a5edfb6da4e9af7ea65123a1dc3cf23541df1b/VSCode-darwin-insider.zip)
linux: [download](https://az764295.vo.msecnd.net/insider/42a5edfb6da4e9af7ea65123a1dc3cf23541df1b/code-insiders_1.28.1-1539357117_amd64.deb)

**Comment by winzig** [comment]
@isidorn I installed the Mac version you listed and can confirm I am no longer experiencing this problem.

**Comment by NCC1701M** [comment]
I tested the Insider version. Looks good.

Thanks for the fast fix.

**Comment by weinand** [comment]
I've verified too that this works now.

**Comment by enesates** [comment]
Hi,

I updated VSCode yesterday. So, I am using 1.28.2 version on MacOs 10.13.6 and Prophet Debugger for Salesforce Commerce Cloud.

I have been getting **_Unable match cartridge: "null"_** error for some cartridges while debugging since yesterday. If I click the Restart button, it works well sometimes. I am not sure if it is related with this issue but wanted let you know.

**Comment by isidorn** [comment]
@enesates this is not related, please file this against the debug extension you are using. Thank you
