### ISSUE TITLE
Multiple monitors: focus is not put to window when opened on different monitor

### ISSUE THREAD

**Issue by nchammas** [Microsoft/vscode#6078]
- VSCode Version: 1.0.0
- OS Version: OS X 10.11.4

Prerequisites:

1. Configure VS Code as your `git` editor.

Steps to Reproduce:

1. Open a project in VS Code and make some changes.
2. Switch to your terminal and `git commit` those changes.
3. A new VS Code window opens for you to write your commit message, but the focus is on your original project window and not on the window that just opened for `git`.

**Comment by bpasero** [comment]
@nchammas does this happen only when code is already running or also when code is not running?

**Comment by bpasero** [comment]
@nchammas or do you mean focus is on another VS Code window, not the one opening?

**Comment by nchammas** [comment]
@bpasero - I updated the description accordingly. This happens when you already have a project open VS Code.

**Comment by bpasero** [comment]
Ok thanks.

**Comment by bpasero** [comment]
@nchammas I cannot reproduce, see the video:

![untitled](https://cloud.githubusercontent.com/assets/900690/15018817/9ab062ce-121b-11e6-9aa7-fa91e82167c8.gif)

**Comment by nchammas** [comment]
Hmm, maybe this is compounded by having multiple monitors? Lemme see if I can make my own video to show you...

**Comment by nchammas** [comment]
@bpasero - What did you use to make that gif, btw?

**Comment by bpasero** [comment]
http://www.cockos.com/licecap/

**Comment by nchammas** [comment]
Sorry @bpasero, I can't get screen capture to work with 2 monitors, but here's my setup:

* Monitor 1: Project is open in VS Code.
* Monitor 2: Terminal is open.

When I run my `git` command from Monitor 2, a new VS Code window opens in Monitor 2, but the focus goes to the VS Code project open in Monitor 1.

**Comment by nchammas** [comment]
And I just tried having the project VS Code window be on the same monitor as the terminal window. In that case the problem doesn't happen (focus goes correctly to the new git VS Code window), so this appears to be limited to those with multi-monitor setups.

**Comment by nchammas** [comment]
Actually @bpasero, this isn't limited to when git opens VS Code. I'm seeing the same behavior when I just run `code something` from a terminal on a different monitor.

**Comment by bpasero** [comment]
@nchammas I am not able to reproduce, maybe it got fixed by our 1.1 update?

**Comment by bpasero** [comment]
My steps are:
* 2 monitors on Mac OS X
* terminal on monitor 2
* open code from terminal on monitor 2
* code opens on monitor 1 (where I left it before)
* focus is in editor

Do you have special settings? do you see a blinking cursor at least?

**Comment by nchammas** [comment]
Hmm... I can't reproduce this anymore, even before upgrading. I *am* using a different machine this time though, so perhaps my issue is limited to the machine I was using before.

I'll reopen if I can figure out more specifically when this problem occurs.

**Comment by akoskm** [comment]
Can we reopen this? It still happens with 1.2.0. I'm using two monitors. When syncing my commits the window that asks for my git username/password appears on my secondary monitor, below all others windows. It  should be easy to reproduce.

**Comment by bpasero** [comment]
@akoskm that sounds like a different issue related to the git password prompt. Can you open a separate issue?

**Comment by akoskm** [comment]
@bpasero thanks, opened https://github.com/Microsoft/vscode/issues/7386.
