### ISSUE TITLE
Copy Value on debug for Node JS project shortens the string

### ISSUE THREAD

**Issue by codyrigney92** [Microsoft/vscode#6165]
- VSCode Version: 1.0.0
- OS Version: Mac OSX Yosemite

Steps to Reproduce:

1. Debug a node project with a long string
2. In the debugger, copy the value of that string
3. The debugger shortens the string, ending it with `... (length: XX)` and that is carried over to the copied value
4. It should copy the original string value

![vscode-bug](https://cloud.githubusercontent.com/assets/3259448/15077015/613fcfce-137a-11e6-8939-a12e1ccf6358.gif)

**Comment by bpasero** [comment]
I think this got fixed in our next release. 
We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by codyrigney92** [comment]
Awesome thanks!

**Comment by samuelms1** [comment]
Seems to still be an issue

**Comment by n370** [comment]
Still an issue as of this version.

![2017-04-20 16_02_18-sockethandler js - calendarproxy - visual studio code](https://cloud.githubusercontent.com/assets/1547648/25247929/c3d790ce-25e2-11e7-9b30-28425ab6f293.png)

**Comment by samuelms1** [comment]
@n370 Do you know how much text was copied when you tried?  At the time I mentioned it was an issue I think I was trying to copy a large value (several KB of text --- html response I think).  anyways...  I think the fix that was applied allows more text to be copied than what was previously available but is still limited to some size which is why I'm curious how much content you were able to copy.  For the most part I'm content with the copy value.

**Comment by n370** [comment]
@samuelms1 here's a sample.

```
"<?xml version="1.0"?>
// There was more text here I omitted for brevity.
 ... (length: 33424)"
```

**Comment by samuelms1** [comment]
@n370 Ya, that's no good.  A LOT more than that should be copied.

**Comment by n370** [comment]
@samuelms1 Do you know why such limitation being placed?
