### ISSUE TITLE
Editing a Markdown file while preview is open creates a scrolling issue

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#62731]
We have written the needed 
Issue Type: <b>Bug</b>

Edit a Markdown file. 
Turn on the preview.
Get to the bottom of the screen and odd 'jumping' occurs. 

Video demonstration: https://www.youtube.com/watch?v=0ppuixZ5q9Q&feature=youtu.be

VS Code version: Code - Insiders 1.29.0-insider (5438af145cf480ce0162bda0799435684b293ec5, 2018-11-07T01:01:54.305Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (4.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.2.0
copy-relative-path|ale|0.0.2
spellright|ban|3.0.6
markdown-preview-github-styles|bie|0.1.4
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.60
prettier-vscode|esb|1.7.1
coldfusion|ili|1.0.1
Angular2|joh|7.0.1
wordcounter|kir|1.4.0
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.9.1
vscode-azurefunctions|ms-|0.12.0
azure-account|ms-|0.5.1
vetur|oct|0.13.0
vscode-snyk|pmb|0.0.2
polacode|pnp|0.2.2
htmlescape-vscode-extension|ray|0.0.4
vscode-yaml|red|0.1.0
vue-vscode-extensionpack|sdr|0.1.3
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.0
vscode-status-bar-format-toggle|tom|1.4.0
vscode-jumpy|wma|0.3.1
nativescript-ng2-snippets|www|2.0.1
JavaScriptSnippets|xab|1.7.1

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Can you please share your markdown file

**Comment by mjbvz** [comment]
Can you please test this in the next 1.31 insiders build. I can't repo this using the example markdown you shared

**Comment by cfjedimaster** [comment]
I think it is fixed now. (I'd close but not sure if that's ok. ;)

**Comment by cfjedimaster** [comment]
Ok sorry, but I'm seeing the issue still. This is with today's Insider Build and this (as of right now) input:

https://gist.github.com/cfjedimaster/3e1adce24f4ed7c86c2d9d6dca93bdce

**Comment by mjbvz** [comment]
Where are you typing in the file? I can't repo in 1.31

**Comment by cfjedimaster** [comment]
At the end of the file.

**Comment by SLLiu96** [comment]
This still occurs in 1.40.2, since several months ago. I've got the exactly same experiment as @cfjedimaster just like the video shows. This issue is NOT related with languages, markdown files, files size, OS, and content types, based on what I've tested.

**Comment by SLLiu96** [comment]
> This still occurs in 1.40.2, since several months ago. I've got the exactly same experiment as @cfjedimaster just like the video shows. This issue is NOT related with languages, markdown files, files size, OS, and content types, based on what I've tested.

By contrast, the extension "Markdown Preview Enhanced" works perfectly with editor.

**Comment by cfjedimaster** [comment]
I can confirm I saw it a few days ago as well - and didn't have time to come back and edit the bug, so thank you @SLLiu96 !

**Comment by cfjedimaster** [comment]
I'm not able to reproduce this with the latest Insiders.

**Comment by cfjedimaster** [comment]
Well, sorry to say I've got it again. I made a screen recording. Latest Insider.

Demo video: https://www.youtube.com/watch?v=vfwrB7I5_yk&feature=youtu.be
