### ISSUE TITLE
Typescript no longer auto importing suggestions

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#63013]
When picking a suggestion from another module, TS no longer auto imports that suggestion. I have to trigger suggest once again, accept the only change and then it gets imported.

![peek 2018-11-13 11-05](https://user-images.githubusercontent.com/22350/48406190-26cbb480-e734-11e8-9dd5-ac3b66ac8291.gif)

**Comment by mjbvz** [comment]
Can you please check the TypeScript Server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem
1. Open the output panel and view the `TypeScript` section

Are there any errors or stack traces printed near the end?

**Comment by joaomoreno** [comment]
https://gist.githubusercontent.com/joaomoreno/76d1e08bfded241499dafcba7241bf4c/raw/6da60ff7304145ab459018296ef419c1c69e1624/ts.log

**Comment by rhyek** [comment]
Can confirm this behavior. I never get auto import suggestions unless I trigger the auto-complete hints a second time.

**Comment by VinceOPS** [comment]
I too need to trigger the intellisense twice, in order to see the import path in the hint, and then trigger the auto-import.

**Comment by selipso** [comment]
Same here, I have to trigger it two or three times in order for the auto-import to show up. This is on Typescript 3.2.0-rc

**Comment by abdulrahman-khankan** [comment]
With vscode **1.29.1**
TS **3.0.3** **works**

`npm install typescript@3.0.3` in your local project or
`sudo npm install -g typescript@3.0.3` to install globally for all projects.

**Comment by bpasero** [comment]
Same here

**Comment by mjbvz** [comment]
There are two cases to try for this:

1. Type quickly to trigger suggest but do not hit enter. In this case, the suggest list item does not contain any details (indicating that auto imports have not been resolved properly). Scrolling through the list or waiting does not help; the details are never resolved

2. Type quickly to trigger suggest and then press enter quickly. Auto imports are also not resolved here.

@jrieken The root cause seems to be our internal handling of cancelation while resolving completion items. The sequence of events:

* Trigger suggest
* The suggestWidget starts trying to resolve a suggestion item in a promise. We cache the promise value here.
* Before this can complete, type some more but make sure that the same suggestion item will still be active. This cancels the ongoing resolution.
* We then try to resolve the same suggestion item again. This just gets the cached promise result so we never properly resolve the suggestion item

There are a few potential things that need fixing:

* Why are we trying to re-resolve the same item in the first place? We should just continue on with the current resolution. The cancellation that seems to cause this is https://github.com/Microsoft/vscode/blob/86052e38f3a25f365e57590cbe2175bb24b84939/src/vs/editor/contrib/suggest/suggestWidget.ts#L714
* We should never cache canceled requests (but we should likely cache other failures).

**Comment by mjbvz** [comment]
@jrieken I submitted a PR that fixes case 1: https://github.com/Microsoft/vscode/pull/64093

Case 2 is still broken. I think we need to make sure that the completion item is resolved when we call `_onDidSelectItem` in `SuggestController`

**Comment by k-knyazev** [comment]
> Is there a workaround for this? It's killing productivity

Can't use TS 3.2.1 now cause of this, sticking to 3.0.3

**Comment by jkim506** [comment]
> > Is there a workaround for this? It's killing productivity
> 
> Can't use TS 3.2.1 now cause of this, sticking to 3.0.3.

Sweet that worked. Thanks k-knyazev.

**Comment by jrieken** [comment]
> Case 2 is still broken. I think we need to make sure that the completion item is resolved when we call _onDidSelectItem in SuggestController

Thanks. I will push a change that ensures we always that we always call `resolve`. This will help all different insertions, like insert on trigger character.

**Comment by jrieken** [comment]
> We should just continue on with the current resolution. The cancellation that seems to cause this is [...]

The problem is that resolving details also [updates the UI](https://github.com/Microsoft/vscode/blob/14b164d410acd26b8e3b34e9582afe7c6d29ccf4/src/vs/editor/contrib/suggest/suggestWidget.ts#L609-L631) and that pending, but outdated, detail-calls would reveal the wrong items. See https://github.com/Microsoft/vscode/issues/60753 for more details.

**Comment by jrieken** [comment]
@mjbvz I merged the PR and I made a tweak on top of it - the IPC layer might reject a promise with a cancellation error if it's canceled before dispatched.

What wonders me is why this only happens with certain version of TypeScript? Was the extra edit not a detail before or what has changed so that these issues are now exposed?

**Comment by mjbvz** [comment]
Thanks @jrieken! I believe this started happening after the `resolve` call in the TS extension went from being a single async operation to two. Previously, if cancellation occurred after the single operation had been dispatched but before `resolve` returned, we'd still return the fully resolved completion item. After the change in TS, on cancellation we bail early and return the unresolved completion item. 

Closing this as the causes of this specific issue have been addressed

**Comment by jlem** [comment]
I am also having this issue. 

VS Code details:

Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Due to legacy code reasons, I am stuck on TypeScript 2.5.3

Any idea when this fix will be available?

**Comment by k-knyazev** [comment]
> Thanks @jrieken! I believe this started happening after the `resolve` call in the TS extension went from being a single async operation to two. Previously, if cancellation occurred after the single operation had been dispatched but before `resolve` returned, we'd still return the fully resolved completion item. After the change in TS, on cancellation we bail early and return the unresolved completion item.
> 
> Closing this as the causes of this specific issue have been addressed

"allowSyntheticDefaultImports: true" breaks auto import, finally tracked the cause of this in my particular case.

Issue do not exist from TS 3.0.3 and still present even till TS@next. Must I open a new issue? Is this TS problem more than vscode?
