### ISSUE TITLE
Multi root workspace: explorer expansion is not preserved

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#63085]
- VSCode Version: Version 1.29.0 (1.29.0), Version 1.30.0-insider (1.30.0-insider)
- OS Version: macOS 10.13.6 (17G3025)

Steps to Reproduce:

1. Open a workspace in VS Code.
2. Expand a folder in Explorer. Close and re-open the workspace, or use `Reload Window`. All folders in Explorer are now collapsed.

This happens in latest stable version (started happening after upgrading to 1.29), and insiders (I'm using the latest version as of this post, since I rarely use Insiders, and just updated it before making this post). If this was a deliberate design decision, then please link me to where it was made, because I can't find it.

My Insiders has no config at all.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce this issue both on stable and insiders on my os x.
Please note there was an issue which we fixed for the stable release https://github.com/Microsoft/vscode/issues/62706

Are you sure you are on latest insiders?
Can you reproduce if you disable all your settings and extensions?

**Comment by isidorn** [comment]
Can you please 
F1 > developer tools > open ExplorerView.ts > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/e7f0b64a1a2a8a4542a85f18be43e1a34bb13db7/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L806)
Have some folders expandend and reload window -> hit the breakpoint, check what is the `targetsToExpand` array. If it contains the resources which should be expanded try to step over and figure out more details.
If it does not contain the resources which need expansion than set a breakpoint [here](https://github.com/Microsoft/vscode/blob/e7f0b64a1a2a8a4542a85f18be43e1a34bb13db7/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L102) reload and check what is `options.viewletState` that is being passed in.

Thanks a lot

**Comment by garyking** [comment]
I have a workspace for the `/Users/gary/Dropbox/Notes` dir. I have the `Notes.md` file open in a tab. I have the `Devices` dir open in Explorer.

`targetsToExpand`:

```json
[
  {
    "$mid": 1,
    "external": "file:///Users/gary/Dropbox/Notes",
    "path": "/Users/gary/Dropbox/Notes",
    "scheme": "file"
  },
  {
    "$mid": 1,
    "external": "file:///Users/gary/Dropbox/Notes/Devices",
    "path": "/Users/gary/Dropbox/Notes/Devices",
    "scheme": "file"
  }
]
```

`options.viewletState`:

```json
{
  "explorer.memento.expandedFolderResources": [
    "file:///Users/gary/Dropbox/Notes",
    "file:///Users/gary/Dropbox/Notes/Devices"
  ],
  "explorer.memento.lastActiveFileResource": "file:///Users/gary/Dropbox/Notes/Notes.md"
}
```

**Comment by garyking** [comment]
I still have this problem in 1.29.1, released today.

I installed 1.28.2, and I can also confirm that the problem does NOT exist there. So the problem is definitely with 1.29.

**Comment by isidorn** [comment]
Ok. We should debug this on your machine since nobody can reproduce.
Do you want to do a debugging session with me using skype or google hangouts some time next week? If yes let me know what time works for you, note that I am in Central Europe Timezone.
If not than I can give you more pointers on how to debug so we try to find the issue here.

**Comment by garyking** [comment]
You can just give me more steps for now, so I can work on it when I have time.

**Comment by garyking** [comment]
I created a new user account on my Mac, and the bug also exists there.

The bug does NOT exist if I open a folder in VSC, then reload the window. Folders remain expanded. The bug only exists if I open a workspace in VSC, then reload the window. Then expanded folders will be collapsed again.

**Comment by isidorn** [comment]
Thanks for providing more details, the cruical thing here is that it only happens for multi root workspaces.
I am not sure what caused this regression, but we plan to move to a new treei mplementation for the exploerer either way which should fix this.

**Comment by garyking** [comment]
This bug was introduced in 79fbea36632bbc6160cb92a72a67992a9c601a68 and fixed in 1c575a2df5e92fcf9ee7ddf17a35ba8e19ad7981

**Comment by isidorn** [comment]
Ok that is weird. Must be timing related
fyi @joaomoreno thanks for randomly fixing it

**Comment by joaomoreno** [comment]
Ahah any time.
