### ISSUE TITLE
1.31.1 update has different checksums on different locations

### ISSUE THREAD

**Issue by dcelasun** [Microsoft/vscode#68621]
- VSCode Version: 1.31.1
- OS Version: Linux

Steps to Reproduce:

1. Download https://vscode-update.azurewebsites.net/1.31.1/linux-x64/stable
2. Check the sha256sum

From the Netherlands, UK, USA and Turkey, the checksum is `154a316eb6785c126e2fccd80a5c76291321ca2d6945e7a2a13f2e262be89bde`, but from Brazil it's `39e953dc16f248399d286cdca1653345ff32927affc0256ea4a62607f8f5f232`.

This was discovered by Arch Linux users [here](https://aur.archlinux.org/packages/visual-studio-code-bin/) (see comments).

**Comment by Chexier** [comment]
I'm also having this problem.

**Comment by Tyriar** [comment]
Will need to wait for @joaomoreno for this one

**Comment by xereda** [comment]
The .tar.gz file provided by the Vscode site is corrupted.

![peek 14-02-2019 07-43](https://user-images.githubusercontent.com/14337850/52778195-93ed2f80-302c-11e9-977c-314569c5d8fb.gif)

**Comment by xereda** [comment]
I did a test downloading the file through a proxy site. I opted for a European server. Now the downloaded file is not corrupted. You can analyze in the simulation illustrated below:

![peek 14-02-2019 07-55](https://user-images.githubusercontent.com/14337850/52779065-96508900-302e-11e9-8980-f47123d783a1.gif)

**Comment by skatiruas** [comment]
If you cannot wait I've used the process described by @xereda to download the proper file, and then moved it to where my AUR builds happen (I'm using Manjaro Linux and its Package Manager).

Since the visual-studio-code-bin folder was not destroyed after the first failed attempt we can just replace the "code_x64_1.31.1.tar.gz" file:
`mv code-stable-1549938209.tar.gz /tmp/pamac-build/visual-studio-code-bin/code_x64_1.31.1.tar.gz`

And when trying again it skips the download process and uses the good file, passing the sha256sum test.

**Comment by eduardomezencio** [comment]
I downloaded the file from Brazil today and the checksum was correct this time.

**Comment by xereda** [comment]
@eduardomezencio Hi Eduardo,
I tried again today, but it's still corrupted.

**Comment by xereda** [comment]
> If you cannot wait I've used the process described by @xereda to download the proper file, and then moved it to where my AUR builds happen (I'm using Manjaro Linux and its Package Manager).
> 
> Since the visual-studio-code-bin folder was not destroyed after the first failed attempt we can just replace the "code_x64_1.31.1.tar.gz" file:
> `mv code-stable-1549938209.tar.gz /tmp/pamac-build/visual-studio-code-bin/code_x64_1.31.1.tar.gz`
> 
> And when trying again it skips the download process and uses the good file, passing the sha256sum test.

@skatiruas 

This palliative is acceptable. Will solve the problem for now.

**Comment by bdouram** [comment]
I am a user of Manjaro and I had the same problem.
For now, while the problem in the Latin American region is not solved, the solution proposed by @xereda works.

Steps:

- I accessed a proxy site in the Europe region.
- I used the link [https://go.microsoft.com/fwlink/?LinkID=620884](url) and downloaded the tar.gz file

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/68736

@xereda Can you try again? This download should be fixed by now.

**Comment by xereda** [comment]
@joaomoreno Not yet resolved.

**Comment by vltr** [comment]
Same error here (_yet_).

**Comment by telmotrooper** [comment]
For the guys still having issues, try erasing your package manager's cache. In my case, deleting `/.cache/yay/visual-studio-code-bin` and then attempting a full system upgrade `yay -Syu` triggered the download of the file with the correct checksum.

**Comment by xereda** [comment]
@joaomoreno @dcelasun 

Congratulations on the help of everyone involved. The problem was solved. I just tested with the ` yay ` package manager.

**Comment by vltr** [comment]
Checksums now match, thanks a lot! :wink:

**Comment by joaomoreno** [comment]
Thanks for the confirmations!
