### ISSUE TITLE
"undefined session received in acceptDebugSessionStarted" introduced in VS Code 1.32

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#69534]
When starting a Dart debugging session in Insiders, I see this error in the console. I'm not sure what's causing it, though I'm seeing another issue (some commands not working) and unsure if it's related.

![screenshot 2019-02-27 at 2 19 42 pm](https://user-images.githubusercontent.com/1078012/53496829-c0786100-3a9a-11e9-83a1-9bbe583c1cea.png)

**Comment by DanTup** [comment]
@weinand this issue has made it to stable and appears to have stopped `acceptDebugSessionStarted` from firing (which has broken many features in the Dart plugin). Do you know whether it's likely something wrong in what I'm doing, or a bug here? (it definitely all worked fine before yesterdays update, I've had a lot of comments at https://github.com/Dart-Code/Dart-Code/issues/1518 since).

**Comment by DanTup** [comment]
Here's what I'm returning from my `resolveDebugConfiguration` method:

```js
{
        "name": "Flutter",
        "request": "launch",
        "type": "dart",
        "program": "/Users/dantup/Dev/Google/flutter/examples/flutter_gallery/lib/main.dart",
        "cwd": "/Users/dantup/Dev/Google/flutter/examples/flutter_gallery",
        "args": [],
        "vmAdditionalArgs": [],
        "dartPath": "/Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/dart",
        "observatoryLogFile": "/Users/dantup/Dev/Dart-Code-Logs/observatory.txt",
        "maxLogLineLength": 99999999,
        "pubPath": "/Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/pub",
        "pubSnapshotPath": "/Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot",
        "pubTestLogFile": "/Users/dantup/Dev/Dart-Code-Logs/pub_test.txt",
        "debugSdkLibraries": false,
        "debugExternalLibraries": true,
        "flutterDebuggerRestartBehaviour": "hotRestart",
        "evaluateGettersInDebugViews": true,
        "forceFlutterVerboseMode": false,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPath": "/Users/dantup/Dev/Google/flutter/bin/flutter",
        "flutterRunLogFile": "/Users/dantup/Dev/Dart-Code-Logs/flutter_run.txt",
        "flutterTestLogFile": "/Users/dantup/Dev/Dart-Code-Logs/flutter_test.txt",
        "deviceId": "1DD6786B-37D4-4355-AA15-B818A87A18B4",
        "deviceName": "iPhone XS Max (ios)",
        "showMemoryUsage": false,
        "debugServer": 51218
    }
```

And I've started a server on that port. It all works fine in my tests, though they use the `DebugClient` class and don't rely on `onDidStartDebugSession` firing.

**Comment by weinand** [comment]
@DanTup the error message on the console just says that a null DebugSession would be passed to "vscode.debug.onDidStartDebugSession" (which is against the spec). Previously we were just passing the null and fire "onDidStartDebugSession" anyway.

@isidorn Since I was sporadicly seeing "null" session objects passed to the debug extension API "vscode.debug.onDidStartDebugSession" I've added a safe guard and console message in https://github.com/Microsoft/vscode/blob/fa93b07de3fc7b670211ef521a1fab500f59f85f/src/vs/workbench/api/electron-browser/mainThreadDebugService.ts#L39.

Could you please investigate why an undefined session is passed to "debugService.onDidNewSession".

**Comment by DanTup** [comment]
The strange thing is, in VS Code 1.31 the Dart debugger works fine, yet it's code is reading properties of the session so I don't believe they could be null:

https://github.com/Dart-Code/Dart-Code/blob/e3ab4bf00f07a7b2df8e26da9d85be478685be17/src/commands/debug.ts#L123

But in 1.32 we see this error, and the event doesn't fire. Is there anything else that changed in this area that might have affected this?

**Comment by isidorn** [comment]
@weinand looking at the code I can not figure out how could you possible get `null`.
Though I rembember I was seeing this error as well, however I can no longer reproduce. Are there some easy repro steps?
Do you get `null` or `undefined`?

**Comment by DanTup** [comment]
I just loaded my extension in 1.31 and added this logging:

<img width="619" alt="screenshot 2019-03-08 at 1 07 45 pm" src="https://user-images.githubusercontent.com/1078012/54030356-42efd780-41a3-11e9-97b6-78ab19364b25.png">

The output looks like this:

<img width="290" alt="screenshot 2019-03-08 at 1 07 49 pm" src="https://user-images.githubusercontent.com/1078012/54030363-47b48b80-41a3-11e9-9004-c3706c18668c.png">

Yet in 1.32 the event never fires and I see the error above. The session is definitely not `null` in 1.31, so I'm not sure why this is triggering :-(

**Comment by DanTup** [comment]
FWIW, the error I'm seeing doesn't isn't the same as the one in the code that @weinand linked to:

console.error('undefined session received in onDidNewSession');

vs

undefined session received in acceptDebugSessionStarted

It's the bottom one I'm seeing, not the top.

**Comment by DanTup** [comment]
Note: this has broken significant debugging functionality for Dart/Flutter and I'm having to tell people downgrade to v1.31. If it turns out to be something in VS Code, it would be great if this could be considered for a recovery release.

**Comment by DanTup** [comment]
If you don't have a good repro for this and want to repro with Dart, you can do this:

- Grab a Dart SDK ZIP from https://www.dartlang.org/tools/sdk/archive
- Extract the zip (can be anywhere)
- Install the Dart extension
- Create a folder and add a file to `bin/main.dart` with the contents `main() {}`
- Open the folder (parent of `bin`) and when the extension says it can't find a Dart SDK, click **Locate** and navigate to the SDK folder you extracted
- Press F5 to run

If you check in the dev tools, you'll see that warning. If you repeat the same thing in 1.31 you won't see a warning (and the session that was received in `onDidStartDebugSession` is *not* null).

If you want to run the extension from source, you can just clone https://github.com/Dart-Code/Dart-Code and it works with just F5 as you'd expect.

As a slight aside, it'd be really nice if we could write debugger tests that went through VS Code's launch process. I have good test coverage here, but because using DebugClient doesn't go through this code, it was not detected. I know how to spawn a debug session using the VS Code command, but then I'm not able to interact with it like I can with DebugClient to set breakpoints etc..

**Comment by weinand** [comment]
I can repro the issue.

**Comment by cesarcamps** [comment]
I can repro this too :(

**Comment by isidorn** [comment]
@weinand are you reproing using Dan's steps or are you reproing using node? If using node can you please provide steps?

**Comment by weinand** [comment]
I mean: I can repro this in the debugger and found out what the problem is.

Some API to find the WorkspaceFolder for a URI (workspaceService.resolveWorkspaceFolder()) has become asynchronous and that has changed the timing behavior. As a consequence the debug session has not yet arrived in the EH host but we are already trying to look it up by UUID. This fails which results in the console error message.

**Comment by weinand** [comment]
@weinand I'm reproing this with a simple hello world program. Debugging works fine. It is just that "vscode.debug.onDidStartDebugSession" is not called...

**Comment by weinand** [comment]
BTW, #69128 was the issue that made me add the code to protect calls to "vscode.debug.onDidStartDebugSession" with an undefined session...

**Comment by isidorn** [comment]
Ok thanks for the details. I will first convert all debug to null checks. This will be a good test if the null checks catch this.

**Comment by weinand** [comment]
And here is the PR that probably introduced the issue: https://github.com/Microsoft/vscode/pull/67216

**Comment by DanTup** [comment]
@weinand Thanks for tracking this down! For some reason I can't get VS Code to build on my PC anymore (gives a weird error about being out of disk space of failing to seek to a position on a file..) but I'll can test it with Dart & Flutter once it's in an insiders build.

**Comment by weinand** [comment]
I've released a fix for Insiders and create a PR as a candidate for the February recovery release.

**Comment by weinand** [comment]
@DanTup yes, it would be great if you could verify the fix in the next Insiders. Thanks a lot.

(BTW, make sure to use node.js 10.15.x when building VS Code. Earlier versions of node.js had the issue to ignore some "heap_size" command line argument.)

**Comment by DanTup** [comment]
Will do - I'm not sure if the timing of insiders - is there another build before Monday?

And thanks for the tip - I'll check my node version later. I had built it previously, but it was a while ago, so who knows what's changed.

**Comment by DanTup** [comment]
> make sure to use node.js 10.15.x

I was on an older version, but I upgraded to v10.15.3 and still see the error below when running `yarn`. Let me know if I should open an issue here about it (it's not clear if it's Code-specific). I'm certainly not short on disk space, and re-cloning and clearing noed_modules doesn't seem to make any difference.

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  is-elevated.cc
  win_delay_load_hook.cc
C:\Users\danny\.node-gyp\iojs-3.1.3\x64\iojs.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x2B4286 [M:\Coding\Applications\vscode\node_modules\native-is-elevated\build\is-elevated.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd M:\Coding\Applications\vscode\node_modules\native-is-elevated
```

**Comment by DanTup** [comment]
Checkdisk reported nothing, so I cleaned all my temp folders (they were getting big) and uninstalled a bunch of stuff, then reboot. Now strangely the error has gone away. Makes no sense - unless it was disk space - but I had about 30GB free! Now I have 45GB free!

Anyway, I will do some testing and see if I can verify the fix on `master`...

**Comment by DanTup** [comment]
Ok, running from source I can repro the issue without ac46ca2 and cannot repro with it. As far as I can see, the fix is good! 👍 

Thanks again for the speedy fix! I'm happy to re-verify in insiders and/or a stable release if you ping me when they're available.

**Comment by mzgnr** [comment]
Downgrading to 1.31 is a temporary fix until this https://github.com/Microsoft/vscode/commit/ac46ca2a5e5aaab3f01cffec46d3e2ac96519f1f patch released with insiders or stable

**Comment by DanTup** [comment]
Tested on the Insiders build that just went out, and it's also working as expected there 👍

**Comment by isidorn** [comment]
@DanTup thanks a lot! Can you also check out the other Dart hot reload issues. They should be fixed with latest insiders, right?
https://github.com/Microsoft/vscode/issues/70057
https://github.com/Microsoft/vscode/issues/70105

**Comment by DanTup** [comment]
@isidorn Yep, those issues both appear to be the same as this. We use the session start event to track all sessions so that we can send editor-side events (like hot reload) to them all.

**Comment by tdyas-stripe** [comment]
Given this is a regression, will the fix for this land in a 1.32.2?

**Comment by DanTup** [comment]
@tdyas-stripe this issue is in the recovery build 2 milestone, so I think that's the plan (though I'm not on the Code team!).

**Comment by weinand** [comment]
@tdyas-stripe yes, the fix will appear in the recovery release (as already announced 4 days ago: https://github.com/Microsoft/vscode/issues/69534#issuecomment-470982409)

**Comment by weinand** [comment]
Verifiers:
You can verify this by running the cluster sample:
```js
const cluster = require('cluster');
const http = require('http');
const numCPUs = require('os').cpus().length / 2;
const Net = require('net');


if (cluster.isMaster) {
	console.log(`Master ${process.pid} is running`);

	console.log(`Forking ${numCPUs} workers.`);
	// Fork workers.
	for (let i = 0; i < numCPUs; i++) {
		cluster.fork();
	}

	cluster.on('exit', (worker, code, signal) => {
		console.log(`worker ${worker.process.pid} died`);
	});

	// start listening on a random port
	//const server = Net.createServer(socket => {
	//}).listen(0);

	//console.log("listening on port: " + server.address().port);

} else {
	// Workers can share any TCP connection
	// In this case it is an HTTP server
	http.createServer((req, res) => {
		res.writeHead(200);
		res.end('hello world\n');
	}).listen(8000);

	console.log(`Worker ${process.pid} started`);
}
```

with this launch config:

```
{
			"type": "node",
			"request": "launch",
			"name": "Cluster",
			"program": "${workspaceFolder}/test.js",
			"autoAttachChildProcesses": true
},
```

**Comment by isidorn** [comment]
Works great. Both regular node debugging and cluster debugging.
No undefined session error in debug console. 
Adding verified label

**Comment by weinand** [comment]
@isidorn thanks!

**Comment by tdyas-stripe** [comment]
@weinand thanks!
