### ISSUE TITLE
CJK character horizontal spacing is incorrect and changes when resizing the window

### ISSUE THREAD

**Issue by WangZishi** [Microsoft/vscode#7062]
- VSCode Version: 1.2.0-insider
- OS Version: Windows 10 Pro Insider Preview 14352

![test](https://cloud.githubusercontent.com/assets/8288105/15676806/50f27c66-277a-11e6-8c58-5ab8447d1043.gif)

**Comment by be5invis** [comment]
Looks like the "hidden terminal" of winpty has some width limit.

**Comment by be5invis** [comment]
And the handle of CJKV characters in NT console behaves differently under cp932/936/949/950 and other CPs (like cp65001).

**Comment by Tyriar** [comment]
This will likely be fixed in the lib after we figure out which one we're going to go with in #6838

**Comment by Tyriar** [comment]
Upleveling xterm fixed this for the most part, the main issue I see with it currently is https://github.com/Microsoft/vscode/issues/8219

**Comment by DerekTso** [comment]
@Tyriar

I searched out those Chinese character issue, and they all came to this single issue. The one i was trying to say is not the character layout issue.

I came accross the Chinese character issue on vs code terminal, after I print out the source code of one page. I have set all those encoding to be 'utf-8', but it still not working.

however, it works fine on sublime text terminal with the same codings.

Could you advise ?

**simple codes:**
```
# -*- coding: utf-8 -*-
import requests

def printPageText():
    r = requests.get('https://www.lagou.com')
    r.encoding = 'utf-8'
    print r.text

printPageText()
```
