### ISSUE TITLE
.gitignore'd files sometimes not greyed-out

### ISSUE THREAD

**Issue by egorovli** [Microsoft/vscode#70963]
Hi 👋

Sometimes files and folders that are in `.gitignore` and normally greyed-out just stop being greyed-out. #70099 may be related, see how in the first image in comment https://github.com/Microsoft/vscode/issues/70099#issuecomment-471596614 `node_modules` directory is not greyed out, however in the second one it is properly greyed-out again.

Here is a quick gif (I do <kbd>⌘</kbd><kbd>⇧</kbd><kbd>P</kbd> — Reload window in the middle of it):

![hello](https://user-images.githubusercontent.com/5165202/54831616-b7f6fd00-4ccb-11e9-97dc-6de8134106fe.gif)

Unfortunately, cannot reproduce 😞

- VSCode Version: 1.32.3
- OS Version: 10.14.3

**Comment by joaomoreno** [comment]
@jrieken I've been getting lots of these lately. I even saw it last week... Anything changed recently?

**Comment by jrieken** [comment]
> Anything changed recently?

Apart from the explorer no, the code hasn't changed since it was written.

**Comment by rendomnet** [comment]
Same here gitignore not graying folders and files

**Comment by DacioRomero** [comment]
I've had a similar issue where it's graying things out that aren't ignored.

For example:
```gitignore
*.env
!*.env.example
```
Will gray out `server.env.example` despite Git tracking it as expected

**Comment by polishedwp** [comment]
I am having the same issue. I am using the [TODO Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) extension, which depends on the `.gitignore` status. Some of my projects, where the `node_module` directory is grayed out properly, the extensions works fine, but other projects it doesn't the extension will pick up the prefix `//TODO ` in the `node-modules` directory. Definitely a problem.

**Comment by sulaysumaria** [comment]
I am facing same issue. But weird thing is if I edit `.gitignore` and save the file. It starts greying out correct files and folders!

**Comment by shadow-light** [comment]
@joaomoreno I believe the following should be reproducible: files that are ignored by global ignore rules. I have some rules in the projects `.gitignore` which are greyed out correctly, but rules that are added in my `~/.config/git/ignore` are not greyed out.

**Comment by shadow-light** [comment]
Actually, never mind. Just switched to a new project and it is greyed out via the global ignore. This bug is hard to pin down! (still happens to my other larger project)

**Comment by rfgamaral** [comment]
Are any of you, perhaps, running with the Remote WSL extension? Because I am and I'm not sure if it's related or not.

For me, grayed-out items and also colored items (Git status) on the explorer tree don't seem to work with a project opened with the Remote WSL extension. If I open this folder locally, everything is colored properly. Also, changing and saving `.gitignore` produces UI changes with the project folder opened locally but not with Remote WSL.

And yes, Git is working inside WSL in both instances. However, local projects are using Git for Windows while Remote WSL projects are using Git installed in WSL.

**Comment by carlodri** [comment]
same problem here today, locally `.gitignore`d files and directories are not grayed out (I have no globally ignored stuff, I think).

**Comment by sebastiantf** [comment]
Facing the same issue. `gitignore`d files except node_modules are not greyed out.

They also show up in `Source Control` which is kind of annoying.

**Comment by marzukia** [comment]
Had the same issue - this was because my project was on a symlinked folder. Moved it to a non symlinked folder and it worked bueno.

**Comment by cpryland** [comment]
VSCode isn't properly interpreting .gitignore. I have a subfolder in my repo called icons-and-symbols, and a .gitignore line 

    icons-and-symbols/.xdignore

but it's not ignoring that file for CHANGES nor is it grayed out.

**Comment by kyegupov** [comment]
Same here, on a Go + Bazel project.

**Comment by kyegupov** [comment]
Note: I've tried building VS Code from source; the issue does not reproduce (even on the same version 1.39.2).
This probably has something to do with the build parameters. Maybe too much data fed into `git check-ignore`?

**Comment by brunoparga** [comment]
I started running into this issue today, out of the blue.

**Comment by pmonty** [comment]
> Are any of you, perhaps, running with the Remote WSL extension? Because I am and I'm not sure if it's related or not.

I am and that seems to be the issue. Anyone found a fix or workaround?

**Comment by rfgamaral** [comment]
I am too.

**Comment by sebastiantf** [comment]
I'm not using a WSL and still facing the issue sometimes

**Comment by derekju** [comment]
Just saw it on my OSX build. Modifying the .gitignore and re-saving fixes it.

**Comment by jjspace** [comment]
I'll double what @derekju said, opening and saving the `.gitignore` file seemed to fix it. 

I ran into this issue when I updated to the October release. The project I had open before I did the update was not showing the grayed out files after it (even after doing `Developer: Reload Window`). I opened `.gitignore` and hit save, no modifications needed. After that all the proper files were grayed out and persist as expected after `Developer: Reload Window`

**Comment by pospi** [comment]
Alas the given instructions have no effect for me, whether I run `Developer: Reload Window` or not.

My situation may be related but different: the issue I experience manifests with project directories that are (git) submodules of other git repositories. In these cases, `.git` is expressed on disk as a text file containing the `gitdir` attribute which points back to the actual repository. It seems that even though `.gitignore` is present at the root of my project directory, it is not loaded. So no directories being ignored / greyed out.

**Comment by ggedde** [comment]
Same issue.
Re-saving .gitignore helped with untracked files, but newly untracked did not work.
So i cleared my git cache and re-added the files and re-committed.  Then re-saved .gitignore once again and it is working now.

Clearing Git Cache:
```
git rm -rf --cache .
git add --all
git commit -m 'Cleared Caches'
```
Then re-save .gitignore

**Comment by LasaleFamine** [comment]
I just had the same problem after pulling a project with an updated `.gitignore`. Solved with a simple save on the `.gitignore` file.

**Comment by nickelghost** [comment]
I had the same issue and I solved it. The problem lied in the folder being opened by a symlink (`ln -s`). Opening the folder with the File -> Open... fixed the issue for me. This also caused some delays with changes appearing in the source control tab.

**Comment by drzamich** [comment]
I am used to opening projects in VScode using the `code` command  in my mac's terminal. I noticed that when the path proviced contains `~`, the issue is there  and ignored files are not greyed out. However, when I replace `~` with the absolute path to my home directory (`/Users/drzamich`), the issue is solved.

**Comment by drzamich** [comment]
I am used to opening VScode projects using the `code` command in my mac's Terminal to speed up the process. Doing so, the greying-out functionality does not work. To have it, I have to firstly open VScode, then using the File -> Open find my project and open it. It takes about 5 times longer, so it would be very nice if the .gitignore feature worked for projects opened with `code` as well.

**Comment by bramankp** [comment]
Problem still present in latest VSCode (as of when I made this post). I am on Windows and nothing special about the project. Making a benign edit to .gitignore and saving it seemed to fix the issue as others have reported.
![2020-04-13](https://user-images.githubusercontent.com/19915618/79120335-a06c3580-7d60-11ea-838d-692c49b004f9.png)

**Comment by bramankp** [comment]
Just a note, closing and then re-opening the project resets to the incorrect (bad) behavior of not marking the ignored items "inactive".

**Comment by egorovli** [comment]
Re-saving the `.gitignore` file, even without changing anything in it, helps, by the way.

**Comment by bramankp** [comment]
@egorovli Sure, but why would I want to have to do that every time I switch projects? I'd rather have the bug squashed. :(

**Comment by egorovli** [comment]
@bramankp I’m not saying it shouldn’t be fixed, just giving the developers more info on this bug’s behavior, as well as giving other people facing the same issue advice on fixing it in-place a little bit faster than reloading window.

**Comment by DrawnActor** [comment]
> 
> 
> Same issue.
> Re-saving .gitignore helped with untracked files, but newly untracked did not work.
> So i cleared my git cache and re-added the files and re-committed. Then re-saved .gitignore once again and it is working now.
> 
> Clearing Git Cache:
> 
> ```
> git rm -rf --cache .
> git add --all
> git commit -m 'Cleared Caches'
> ```
> 
> Then re-save .gitignore

I had the same issue (file not getting greyed out and still being tracked for changes + pushed to remote) and this was the only thing that worked for me. Reloading window, closing and opening vscode, saving .gitignore in the editor etc all did nothing.

**Comment by jtsom** [comment]
Just noticed the same issue here, with the latest Insiders version:
Version: 1.47.0-insider
Commit: 84f52fe1c0124307046ac0f5443493cda946e60f
Date: 2020-06-17T06:56:23.406Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

Doing a Reload Windows brought back my gitignored coloring of folders. I do not have the WSL Remote extension, nor is anything symlinked.

**Comment by CynicalBusiness** [comment]
I know this is a bit of an older issue, but I am still seeing this on the main release. Does not serve any functional difference, but still sometimes spooks me into thinking files that shouldn't be committed had been.

I have it happening consistently in one of my larger projects: no matter what I do, this particular project never has it working. Unfortunately, this project is private and I cannot share it but would be happy to provide some files if any in particular if it helps for resolving this.

Works fine in just about any other repo I open with the same VSC configuration. Slightly modifying the `.gitignore` as mentioned above had no effect.

VSC:
```
Version: 1.48.0 (system setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

My `.gitignore` here is a [gitignore.io windows,visualstudiocode,node,react template](https://www.toptal.com/developers/gitignore/api/windows,visualstudiocode,node,react) with the following two lines added to the bottom:
```
packages/*/lib/
packages/*/data/
```

A quick look in the VSC output tab, and there's a `Git error` that prints every time the window reloads in both `Log (Window)` and `Log (Extension Host)`:
```
[2020-08-19 19:44:22.499] [exthost] [error] {"message":"Git error","stdout":"","stderr":"fatal: c:\\path\\to\\project: 'c:\\path\\to\\project' is outside repository\n","exitCode":128}
```

Hope this helps to track this down. Happy to provide any other info.

**Comment by marioessig** [comment]
Solution: save on .gitignore file and this will update the .gitignore file and then gray out the files.

**Comment by MakePixelsWork** [comment]
I also have this error.

![image](https://user-images.githubusercontent.com/56885246/107978901-dfd96300-6fbd-11eb-97cf-8fab342f545f.png)

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 6.3.9600

**Comment by crystalfp** [comment]
I'm on windows and the procedure suggested by @ggedde (clearing git cache and resave .gitignore) solved the problem! Thanks a lot!

**Comment by jonagoldman** [comment]
I found setting `"explorer.decorations.colors": true` fixed the issue.
Other suggestions like clearing git cache and saving .gitignore did not solved the problem for me.

**Comment by danieldupree** [comment]
> 
> 
> Had the same issue - this was because my project was on a symlinked folder. Moved it to a non symlinked folder and it worked bueno.

This was the fix for me.

**Comment by huzaifahj** [comment]
> Same issue. Re-saving .gitignore helped with untracked files, but newly untracked did not work. So i cleared my git cache and re-added the files and re-committed. Then re-saved .gitignore once again and it is working now.
> 
> Clearing Git Cache:
> 
> ```
> git rm -rf --cache .
> git add --all
> git commit -m 'Cleared Caches'
> ```
> 
> Then re-save .gitignore

This worked for me. Looks like newly untracked files need to be taken into account

**Comment by marcitqualab** [comment]
[slved] I had this error of not greying out the files and directories registered in .gitignore. 
I am using Ubuntu 20.x. 
I have a symbolic link at the home page to the projects folder that is actually inside a deeper structure of directories. Tell me I am a complicated mind, I know. 
Adding the folder to the workspace using the symbolic link was the problem in my case. 
Solution.
1. Remove de folder from the workspace.
2. Add folder to workspace, NOT using the symbolic link, but the actual full path to the folder.

**Comment by marcitqualab** [comment]
I suspect that most of the problems would be somehow caused by loading a project folder from a "non-real", "non-local" file system. i.e symbolic links, virtual volumes or similar things.

**Comment by ggedde** [comment]
I might create a separate issue for this, but it would be nice if clicking on the Refresh icon or refreshing the folder list would also force update the VSCode internal GIT checks. The idea is that it would resolve this issue and also another issue where sometimes I run GIT commands from the terminal and VSCode does not recognize the changes and still shows items as changed and not committed, etc

This isn't a full solution, but since this issue has been around for almost 3 years, I think this would be a good compromise until it is fully resolved.

Thoughts?

**Comment by id-matt-michler** [comment]
In case this helps anyone else, updating my version of git fixed this for me. I upgraded from `2.16.2.windows.1` to `2.36.0.windows.1`, I'm usually on WSL so I didn't realize how far behind my Git for Windows was.

**Comment by vuongvinhvien** [comment]
It work for me: use cmd or git bash... and type:
"`git config --global --add safe.directory D:/project`"
change "D:/project" to your path or just D:/

**Comment by mdotcoder** [comment]
In my case, it was the .env file that was not greying out. 
Solution for me, I deleted the .env file and readded it. It immediately greyed out.

**Comment by vaspoz** [comment]
tried all of the suggestions from above, but nothing works =\ is it still the issue? 
VSC version: 1.71.2

**Comment by vipiny35** [comment]
I had the same issue, it only happens when you open a project which is a symlink folder.
Directly opening the folder in vscode didn't have any greying out issue.

**Comment by KittPhi** [comment]
My fix was to Restart VS Code and then Resave `.gitignore`

**Comment by s-williams** [comment]
Had the same problem today in version 1.73.1 on Windows 10. Restarting VSCode fixed it. 👍

**Comment by SachinShekhar** [comment]
> I am facing same issue. But weird thing is if I edit `.gitignore` and save the file. It starts greying out correct files and folders!

@sulaysumaria Wow! Such an elegant solution. 🔥🔥🔥

**Comment by direc85** [comment]
I'm hitting this on daily basis with 1.76.0 on Manjaro Linux. Re-saving `.gitignore` doesn't usually help, restarting vscode helps, but is inconvenient.

The setup I have is having a project/git repo folder opened in vscode, and the project has a subfolder which has other repositories as its subfolders. When I open vscode and the folder, there's correctly only one repo in Source Control. If I open a file in a subfolder repository, the `.gitignore`d folder gets picked up by vscode _and_ Source Control, and folder gets colored there are now two repos in the side bar tab. After that, the only way to make the folders be ignored again is to restart vscode.

To illustrate:

```text
project-folder (git repo)
|- .gitignore (contains "subfolder/project-*")
|- subfolder
|  |- project-a-folder (git repo)
|  |  |- file-a.txt
|  |- project-b-folder (git repo)
|  |  |- file-b.txt
|- (more files)
```

The coloring and Source Control work as expected as long as I don't touch `file-a.txt` or `file-b.txt` having the root project opened. So I guess in this particular case the culprit is the Source Control picking the file up, bypassing the root project `.gitignore`.

There are reasons why we can't use the repositories as submodules, which might solve both issues as well, but our workflow sadly doesn't support that.

**Comment by wmmc88** [comment]
> I had the same issue, it only happens when you open a project which is a symlink folder. Directly opening the folder in vscode didn't have any greying out issue.

This was the issue for me. When the path of the folder opened includes a symlink, the greying out of .gitignored files breaks.

**Comment by awalker125** [comment]
> Had the same issue - this was because my project was on a symlinked folder. Moved it to a non symlinked folder and it worked bueno.

This fixed my issue. I'd made a junction to move my workspace folder to D:\ while keeping the same structure as everyone else on C:\. When I deleted the junction and moved my workspace back to C:\ it started working straight away.

**Comment by jgardona** [comment]
I can confirm this issue today in linux, in my project also. Happens all the time.

![image](https://github.com/microsoft/vscode/assets/146892539/bd306a21-c15c-4e6d-9005-0d94f2f0d488)

**Comment by virtuallyunknown** [comment]
Same issue here. Reloading VSCode or re-saving .gitignore does not fix the problem.

**Comment by vaspoz** [comment]
@jgardona, `/target` I see is working, did you try with the file to also use `/` in front?

**Comment by jgardona** [comment]
> @jgardona, `/target` I see is working, did you try with the file to also use `/` in front?

I'll try and return with a feedback.

**Comment by vd1371** [comment]
Same problem, I opened the repo with "Open Folder"
Then I saved the workspace in .vscdoe folder in the root folder and opened it using "Opened Workspace From File..."
Solved it for me

**Comment by joshgalvan** [comment]
Restarting VSCode solved this for me

**Comment by montythepython** [comment]
A solution for some that havent been able to solve it with any of the answers given above:
I am working in WSL but I think this should be independent of this.

If you have already commits and then add files to gitignore, they will not be ignored (they will not grey out).
Move the files/folders you want to ignore out of the repository folder (keep them listed in your gitignre file). Do a git add . and then commit.
Now you can bring the files/folders back into the repository folder and if they are properly listed in your gitignore file they will be greyed out after you do another git add/commit/push

**Comment by montythepython** [comment]
Hey neodon, what about explaining why you add thumbs down to comments here if these solutions are working for some people?

**Comment by vaspoz** [comment]
@montythepython , oh man, you should have named yourself MightyPython! =)

**Comment by yaa110** [comment]
same issue here:

```go
Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:14:59.643Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.87.2 Chrome/118.0.5993.159 Electron/27.3.2 Safari/537.36
```

**Comment by TheRealMikeD** [comment]
Still broken in 1.88.1.

**Comment by kturney** [comment]
This wasn't working for me on a new install/machine setup.
Changing `git.openRepositoryInParentFolders` to `always` (from `never`) and suggestion from https://stackoverflow.com/a/65885419 to 

> run `git fetch --all` in CMD inside the project directory

fixed it for me.

**Comment by du33169** [comment]
This problem may be related to the git executable used by VSCode.
I have installed MSYS2 on Windows and added its `/usr/bin` to the PATH so that I can use those Unix tools, including git, outside the MSYS2 shell. The ignored files cannot be greyed out this way.
If I assign the `git.path` in settings.json to a normal [git for windows](https://git-scm.com/downloads/win) installation, the issue disappears.

**Comment by CodeSmith32** [comment]
I'm NOT using WSL, and yes I also have this issue. Glad to know that "Reload Window" from the command palette and fixes it. 👍

Kind of wishing there was a simpler "Restart Git" command as well, similar to "TypeScript: Restart TS Server" / "Restart ESLint Server".

**Comment by kyle-chine-leismore** [comment]
This solves my problem:

Edit anything in my `.gitignore` file. Then save and undo it. --> Issue solved.
