### ISSUE TITLE
'Format Selection' and 'Format Document' not language aware

### ISSUE THREAD

**Issue by Yzrsah** [Microsoft/vscode#70995]
Format Selection `editor.action.formatSelection` and Format Document `editor.action.formatDocument` do not utilize the language mode for the file.

If I'm working with JavaScript and I try to use these commands, I will be prompted to choose from a menu every time:
![Multiple languages](https://i.imgur.com/HuGN07k.png)

Having to select the same redundant selection from a menu every time makes this one too unusable.

There does not seem to be a way to set the "Default Formatter" for a language

**Comment by jrieken** [comment]
See https://github.com/Microsoft/vscode/issues/41882#issuecomment-475281706 for on this but what this means is that have three extensions installed that all advertise that they can configure the current document (not which which that is). The prompt is shown the make clear what happens and to make you disable/uninstall conflicting formatters.

**Comment by jrieken** [comment]
fyi - I have pushed a change so that format document still picks _some_ formatter (it now prints a status bar message which it picked). closing quick pick is a separate command which doesn't take the keybinding away anymore

**Comment by Yzrsah** [comment]
@jrieken Thank you very much for the update.

The update helps and the feature is easier to use, but, it picked the wrong formatter for the project. The reason I have multiple formatters is because different projects are using different formatters. I would love to be able to set the "defaultFormatter" in the workspace settings so that each workspace can use the correct formatter. I hope you will consider that one because I think that people will request it in the future.

**Comment by Yzrsah** [comment]
@jrieken Thank you very much for the update.

The update helps with ease of use, but, it picked the wrong formatter for the project. The reason I have multiple formatters is because different projects are using different formatters. I would love to be able to set the "defaultFormatter" in the workspace settings so that each workspace can use the correct formatter. I hope you will consider that one because I think that people will request it in the future.

In the workspace it could be like
```
    "[javascript]": {
        "editor.defaultFormatter": "Beautify"
    },
```

**Comment by Yzrsah** [comment]
@jrieken There was no solution working because we are forced to enable and disable extensions every time we switch projects, it's an ongoing problem / not resolved

**Comment by jrieken** [comment]
@Yzrsah How about defining the setting on the workspace-level, e.g in the `.vscode/settings.json` file?

**Comment by Yzrsah** [comment]
@jrieken I'm sorry I didn't respond sooner

That would be fantastic! And would be very useful for working with different projects. Thanks so much for your consideration about it.

**Comment by Yzrsah** [comment]
@jrieken I just got a surprise to discover `editor.defaultFormatter` in the Insiders build!

The popup prompted me to select a default formatter and it worked excellently!

Thank you so much, this really helps a lot with the projects
