### ISSUE TITLE
Should maintain row focus after deleting a file

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#71315]
- Use the keyboard to focus a file in the explorer and delete it
- Now the whole tree has focus
- Press the down arrow key
- The first item is selected

I want to get back to where I was looking before. The search tree focuses the next item in the list when one is removed. I don't know whether the explorer did this previously with the old tree. But it would be nice for the explorer to do the same thing.

**Comment by isidorn** [comment]
@joaomoreno currently the tree focuses the tree container when a focused element is no longer in the tree.
Optimally as @roblourens says we shuold just focus the next element in the tree.

Not sure if this should be done on the tree level or on the client level.
Because if we decide to do it in on the client level than we need to imlement this for Search, Explorer, Watch, Breakpoints. Due to multiple clients wanting this same behavior IMHO it makes sense to do this on the tree level.
If you agree to do it on the tree can you provide a code pointer so I look into this?

**Comment by roblourens** [comment]
This could be some reusable helper that lives outside of the tree. I think search's code for this could be made generic:

https://github.com/Microsoft/vscode/blob/09021f9c8c2d5ae24aec1dd2a8fa79e5dda4baf5/src/vs/workbench/contrib/search/browser/searchActions.ts#L438

**Comment by isidorn** [comment]
Let's see what @joaomoreno has to say.
But yeah if we need to implement this all over tha place a helper would make sense.

**Comment by joaomoreno** [comment]
As far as the widget is concerned, it has `[A]` as the focus group. When `A` goes away... why would the focus group become `[B]`? If the focus group would be `[A, C]` instead and `A` would go away... should the focus group become `[C]` or `[B, C]`?

This should be done on the client level. :+1:

**Comment by roblourens** [comment]
If we work on this we could try to fix https://github.com/Microsoft/vscode/issues/20467 at the same time. That is the case where the ID of the focused item changes. Instead of losing the focus we should try to find a smart way to focus something else.

**Comment by brunzefb** [comment]
I don't know if this is the same bug:  In a large tree, mouse-select a file and use keyboard to delete (cmd-del).  The tree scrolls to a random place.  I expect no scrolling to take place and the next element in the tree taking the focus.

**Comment by SaschaCowley** [comment]
This issue is still present in version 1.49.0 and is both a poor and a non-standard user experience.

**Comment by isidorn** [comment]
Agree, we should improve this. Assigning to September to investigate more.

**Comment by isidorn** [comment]
Pushed a fix, try it out with VS Code insiders from Monday and let us know how it behaves. 
To verify simply follow the inital steps @roblourens described.

**Comment by SaschaCowley** [comment]
Deleting the last item in a node does not focus the previous item in that node, or the node's parent.

**Comment by isidorn** [comment]
Makes sense. I have just pushed a fix for this case. Thanks @SaschaCowley

**Comment by SaschaCowley** [comment]
With this fix (8c1015f5e1a7a686d19ec8a5f56a495332f16062),when deleting open files, focus moves only within other opened files in the explorer. This is unexpected and somewhat odd behaviour, and also means that if the current file is the only open file, and it is deleted, focus lands on the treeview, rather than an appropriate node therein.

**Comment by isidorn** [comment]
@SaschaCowley I understand this is unintuitive but this is because of the `explorer.AutoReveal` setting. That setting says that whatever the active editor is it shuold be selected in the explorer. Since you deleted an active editor, another editor gets active thus getting selected.
I suggest you set `"explorer.AutoReveal": false` to work around this behavior.

**Comment by connor4312** [comment]
This seems to work for files, but it looks like this still happens when deleting folders (on Windows).

**Comment by brunzefb** [comment]
I don't think "explorer.AutoReveal" : false is a good solution.  You still want the to see the active editor highlit in the explorer.  I don't know much javascript or vscode code -- when deleting, it may make sense to first change to (activate) the next (or previous) editor in the tree.  I would not go for the parent folder, as this may be visually far from the place you are deleting. Then programmatically return to the previous file, delete the underlying file and remove the editor, and remove the file in the explorer tree.  I am sure this is fixable.

**Comment by isidorn** [comment]
@connor4312 I can not reproduce and I just now tried both on macOS and windows. Whenever I delete a folder all seems good, the focus is still in the explorer and the correct file / folder is focused.
Closing this. Feel free to create a new issue if you have an exact scenario where this does not work.
Thanks

**Comment by bpasero** [comment]
Two things I find a bit unexpected:
* it does not work unless you focus another item than the selected one (e.g. just clicking and then deleting a file moves focus to tree)
* it does not seem to work for folders, at least sometimes (maybe related to compressed folders?)

**Comment by bpasero** [comment]
As discussed, moving to October.

**Comment by isidorn** [comment]
Yeah, we can taclke in October the corenr case. Thanks for finding it Ben.

**Comment by isidorn** [comment]
Pushed a fix for this.
However had to change one minor behavior which I think is fine.
When autoReveal is turned on and the last editor is closed we will no longer clear the tree focus in the explorer. The focus will remain on the last active editor. I think that is fine.

**Comment by bpasero** [comment]
@isidorn it still behaves unexpected for compressed folders imho, shouldn't the selection stay in this case and not move down?

![recording](https://user-images.githubusercontent.com/900690/97691054-23a36d80-1a9e-11eb-891d-9c832a547ab3.gif)

**Comment by isidorn** [comment]
@bpasero thanks. I pushed a fix for this just now.

**Comment by bpasero** [comment]
Ok thanks, will verify after we have a new build then 👍
