### ISSUE TITLE
Mouse back and forward buttons do not work on linux/windows anymore

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode#71318]
Issue Type: <b>Bug</b>

They work in chrome and worked in vs code before. But in 1.32 they don't work anymore. Can't remember exact version where they worked but in chromium these buttons work fine. These buttons are recognized by X as 8 and 9.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.19.31-1-lts

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 2471)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|15.61GB (4.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-hie-server|ala|0.0.25
better-toml|bun|0.3.2
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.2
vscode-dash|dee|2.1.0
xml|Dot|2.4.0
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.8.1
file-icons|fil|1.0.16
code-runner|for|0.9.7
kotlin|fwc|0.1.13
godot-tools|gee|0.3.7
todo-tree|Gru|0.0.125
live-html-previewer|hdg|0.3.0
hoogle-vscode|jca|0.0.7
svn-scm|joh|1.47.10
language-haskell|jus|2.5.0
favorites|kdc|2.4.5
Lisp|mat|0.1.8
vscode-todo-parser|min|1.9.1
vscode-language-pack-ru|MS-|1.32.4
python|ms-|2019.3.6139
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
mono-debug|ms-|0.15.8
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|0.3.1403
debugger-for-chrome|msj|4.11.3
gradle-language|nac|0.2.3
vscode-subword-navigation|ow|1.2.0
phoityne-vscode|pho|0.0.22
java|red|0.41.0
vscode-yaml|red|0.4.0
rust|rus|0.5.4
vscode-hexdump|sle|1.7.2
emmylua|tan|0.2.3
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.5
vscode-svg-previewer|vit|0.5.0
vscode-java-debug|vsc|0.17.0
debug|web|0.23.0
jinja|who|0.0.8
clang-format|xav|1.9.0
vscode-proto3|zxh|0.2.2

</details>

**Comment by Tyriar** [comment]
What did they used to do?

**Comment by Yanpas** [comment]
If I ctrl+clicked on some word in code (go to definition) and clicked back button I would return to my previous cursor position.

I think that they were bound to `workbench.action.navigateBack`, `workbench.action.navigateForward` actions.

**Comment by look-at-me** [comment]
Same issue on Windows now. This works in VS Code 1.35.1 on Windows, but it doesn't in insiders:

```
Version: 1.36.0-insider (system setup)
Commit: 15b7c86d86319b187a5ef255c170184a8519c5af
Date: 2019-06-14T10:37:04.235Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by stssk** [comment]
Same issue on windows: Mouse back and mouse forward does not navigate

> Version: 1.36.0-insider (user setup)
> Commit: 11b88a3323878a98b418e4efca77e7afabd50d01
> Date: 2019-06-17T05:17:47.485Z
> Electron: 4.2.4
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.16299

**Comment by aruproy14** [comment]
+1 for hitting this issue on latest code insider on Windows.

Version: 1.36.0-insider (user setup)
Commit: d04b5d2eb16c156e24dbf44010c315d968694bd6
Date: 2019-06-13T05:19:34.516Z
Electron: 4.2.3
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18915

**Comment by furier** [comment]
same, and it makes me go insane!

```
Version: 1.36.0-insider (user setup)
Commit: fe0c3e785c22c3ed2d5caa7178488c92d62bdb08
Date: 2019-06-28T12:34:35.956Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by bkromhout** [comment]
As others have noted, this bug clearly isn't limited to Linux, navigating back/forward via mouse buttons broke when I updated from 1.35.1 to 1.36.0 (stable) today.
```
Version: 1.36.0 (system setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by bpasero** [comment]
https://github.com/electron/electron/issues/17134 seems to be the origin of this issue.

**Comment by bpasero** [comment]
I have pushed a change to not rely on Electron for these mouse events and rather listen on the `MouseEvent.button` values `3` and `4`. This can also be turned off now with the new setting `workbench.editor.mouseBackForwardToNavigate`

**NOTE:** we NEVER supported mouse navigation on Linux. The solution we had in place was ONLY working on Windows. With my new changes however I can see it working for Linux as well as Windows, however not macOS. There you can configure the `workbench.editor.swipeToNavigate` setting to navigate via swipe gesture.

**Comment by bkromhout** [comment]
Thanks for the quick work @bpasero! Is there any possibility we might be able to get this into the June 2019 Recovery milestone rather than the July 2019 milestone? Having to wait a month for a high-use (and very intuitive, muscle-memory wise) navigation feature like this would be rather painful.

**Comment by bpasero** [comment]
Reopening for discussion.

**Comment by bpasero** [comment]
It would be nice if people could validate the fix on Windows and Linux from our latest (just released) insider build: https://code.visualstudio.com/insiders/

**Comment by look-at-me** [comment]
Still not working for me.

Version: 1.36.0-insider (system setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T08:00:29.662Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
@look-at-me due to a lot of build issues we had to roll back our insiders build and it does not seem to include my fix. 

Here are builds to try it out:
* Windows: [download](https://az764295.vo.msecnd.net/insider/28988230cd15af27b2da8fa895315eacb1243e79/VSCode-win32-x64-1.37.0-insider.zip)
* Linux: [download](https://az764295.vo.msecnd.net/insider/28988230cd15af27b2da8fa895315eacb1243e79/code-insider-1562303537.tar.gz)

**Comment by roger225** [comment]
> @look-at-me due to a lot of build issues we had to roll back our insiders build and it does not seem to include my fix.
> 
> Here are builds to try it out:
> 
> * Windows: [download](https://az764295.vo.msecnd.net/insider/28988230cd15af27b2da8fa895315eacb1243e79/VSCode-win32-x64-1.37.0-insider.zip)
> * Linux: [download](https://az764295.vo.msecnd.net/insider/28988230cd15af27b2da8fa895315eacb1243e79/code-insider-1562303537.tar.gz)

It's working

**Comment by furier** [comment]
> @look-at-me due to a lot of build issues we had to roll back our insiders build and it does not seem to include my fix.
> 
> Here are builds to try it out:
> 
> * Windows: [download](https://az764295.vo.msecnd.net/insider/28988230cd15af27b2da8fa895315eacb1243e79/VSCode-win32-x64-1.37.0-insider.zip)
> * Linux: [download](https://az764295.vo.msecnd.net/insider/28988230cd15af27b2da8fa895315eacb1243e79/code-insider-1562303537.tar.gz)

works for me as well! :)

**Comment by bpasero** [comment]
This will be released next week as a recovery fix to stable. Thanks for testing 👍

**Comment by lanovoy** [comment]
Can we get a hotfix for it into 1.36? Extremely annoying issue making VSCode for me borderline unusable...

**Comment by N3bul0** [comment]
Pretty annoying, I was so used to it! Thanks for your fast response in fixing and releasing that!

**Comment by bradgearon** [comment]
1.37.0-insider seems to work

**Comment by MrMuMu** [comment]
It seems to work however with a change of behaviour:

It was navigating forward/backward based on the cursor position, but it is now navigating based on files.

**Comment by lanovoy** [comment]
So far the best 'workaround' is downgrading to 1.35 (download it here https://code.visualstudio.com/updates/v1_35 )

**Comment by inliquid** [comment]
For me on Windows machine it navigates based on cursor position. Not very precisely, tbh, it misses some intermediary positions, however it works same as when pressing `Alt-Fwd/Back`

**Comment by furier** [comment]
same for me on windows as @inliquid

ons. 10. jul. 2019 kl. 14:53 skrev inliquid <notifications@github.com>:
