### ISSUE TITLE
Scrolling in debug window is behaving strange since 1.33.0

### ISSUE THREAD

**Issue by pkeuter** [Microsoft/vscode#71737]
- VSCode Version: 1.33.0
- OS Version: Win10 x64 1809 (17763.404)

Steps to Reproduce:

1. Start debug session
2. Go to debug console
3. Try to scroll down

The debug window should stay scrolled down when scrolling to the bottom, but since 1.33.0 this is not happening anymore. It stays scrolled down until new data needs to be displayed and then it jumps up.

Does this issue occur when all extensions are disabled?: Don't know because I can't start the debugger with extensions disabled.

**Comment by isidorn** [comment]
I can not reproduce this with the following code sample 

```
setInterval(() => 
    console.log('i like flowers'), 100)
```

This sounds like a duplicate of https://github.com/Microsoft/vscode/issues/70331
However that issue is fixed in latest.
So please try to provide exact reproducable steps. For what program does this happen always to you so I can investigate more on my machine.

**Comment by isidorn** [comment]
Actually I might now what the issue is. The fix for that issue is only applied to the settings editor. Investigating...

**Comment by ccidral** [comment]
I've been experiencing this issue since 3 or 4 updates ago on both Fedora 29 and OS X Mojave when running .NET Core projects with Omnisharp. In my case the issue happens consistently every time I start the debugger. When the Omnisharp debugger starts, it instantly fills up the debug console with lots of debug messages. You have to manually keep scrolling up the contents because it won't automatically scroll when new debug messages are written to the debug console.

**Comment by isidorn** [comment]
Please try it out in tomorrow's vscode insiders and let us know if the commit fixed your issue (it should).
Thanks

**Comment by kevinamorim** [comment]
I still have this issue. Debug console scrolls to top after each evaluation. Programming with Python. 

**Version: **1.33.1
**OS: **Windows 10 x64

**Comment by isidorn** [comment]
Please read my comment, the fix is only in insiders. Will be available in next stable in may

**Comment by kevinamorim** [comment]
@isidorn Thanks! I didn't notice the "insiders" part.

**Comment by kepeterson** [comment]
I'm having the same issue and I've confirmed it's been fixed in the insider build -- any chance you guys cut a hotfix release before next stable in May with commit 2adfa43 included?

This bug really screws with common test runner frameworks and testing workflows.

**Comment by isidorn** [comment]
@kepeterson we will not release a recovery release for this sorry. You can always use vscode insiders.

**Comment by mirao** [comment]
Fixed for me when using latest insider build VSCode 1.34.0-insider with C/C++ extension 0.23.0-insiders (gdb debugger).
I was able to reproduce the bug in VSCode 1.33.1 with C/C++ extension 0.22.1
I'm running Ubuntu 19.04

**Comment by nbara** [comment]
FYI the latest insider build 1.34.20 (macOS 10.14.4) does not solve this issue for me using Python

See gif below : 

![bugscroll](https://user-images.githubusercontent.com/10333715/57841626-34d5bd00-77cb-11e9-9683-a33cd0bd48c1.gif)
