### ISSUE TITLE
document.isDirty appears to report false for dirty untitled document

### ISSUE THREAD

**Issue by guillermooo** [Microsoft/vscode#723]
Context: Vim extension.

```typescript
private doQuit(textEditor : vscode.TextEditor) {  
		if ((textEditor.document.isDirty || textEditor.document.isUntitled)  // if I don't check for this, isDirty reports false for untitled document
			&& !this.args.bang) {  
				throw new Error("unsaved changes");  
		}  
...
}
```

**Comment by jrieken** [comment]
Will investigate

**Comment by jrieken** [comment]
I can reproduce. The save is true for the opposite - after save it's still dirty.

**Comment by jrieken** [comment]
@bpasero A snippet like below missing to be ignored wrt to FILE_SAVED & FILE_DIRTY events:

```
workspace.openTextDocument(Uri.parse('untitled:///Users/jrieken/Desktop/file.txt')).then(doc => {
		console.log(doc.uri);
		console.log(doc.isDirty);

		setTimeout(function() {
			console.log('SAVING')
			doc.save().then(value => {

				console.log(value);
				console.log(doc.isDirty);
				console.log(doc.uri);
			});
		}, 2000)
	});
```

**Comment by jrieken** [comment]
![screen shot 2015-11-27 at 17 02 06](https://cloud.githubusercontent.com/assets/1794099/11444961/9d622860-9528-11e5-8afe-a32dd8b3b3fa.png)

**Comment by jrieken** [comment]
Oh, and the first `true` from isDirty I got after such a change - which I believe isn't proper:

![screen shot 2015-11-27 at 17 02 46](https://cloud.githubusercontent.com/assets/1794099/11444979/c0d3b3e0-9528-11e5-9dcd-cecc05dc7866.png)

**Comment by bpasero** [comment]
There are different events to track untitled files in the workbench: `WorkbenchEventType.UNTITLED_FILE_DIRTY` to track when a untitled file is dirty and `UNTITLED_FILE_DELETED` when an untitled file has been saved or reverted because then it turned into a normal file and the resource is disposed.

An untitled file is never dirty when created in the workbench via Cmd+N until you make changes because it should be possible to quit the workbench without prompt in that case. However, if the untitled file is created with a real path (as in this example) the untitled file is marked as dirty because it is the intent of the user to save the file at the path provided. This can be seen when you run code from the command line with a path argument that does not exist. In that case it would be weird to not show the dirty indicator.

**Comment by jrieken** [comment]
I understand, since we always translate the untitled scheme to something the internals call 'hasResourcePath' we are fine with just signalling dirty from start.

**Comment by jrieken** [comment]
@bpasero wrt the save-behaviour you describe I believe the code lives in the wrong location. It sits all in the [save-action](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.ts#L1511) instead of being part of the service. Given that I see no way reusing the code (getting the same sequence of events). Why doesn't the `save`-function to the trickery of closing the source and reloading and why doesn't the editor service listen to dispose such that it can reopen?

**Comment by bpasero** [comment]
@jrieken whats the scenario? can you not trigger the same save action?

**Comment by jrieken** [comment]
Yeah, I am in [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/common/pluginHostDocuments.ts#L634) and have a service on which I call save

**Comment by bpasero** [comment]
@jrieken I see, so the issue is only for untitled files the behavior is different from the global save action. it does not impact normal files right?

**Comment by jrieken** [comment]
correct @bpasero I like to get the behaviour you have described earlier by calling `save`. [That](https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/workspace.test.ts#L52) test-case describes what I would like to have in the end

**Comment by bpasero** [comment]
@jrieken ok I can look into it. I think I would create a new issue for it though because the original issue from the author is fixed, right?

**Comment by jrieken** [comment]
@bpasero You decide but I would be awesome if it happens in December. It's quite a big one...

**Comment by bpasero** [comment]
Ok: https://github.com/Microsoft/vscode/issues/939

**Comment by jrieken** [comment]
@bpasero If I change the unit test to check that the doc isn't dirty after save it still fails. Am I missing something?

**Comment by jrieken** [comment]
![screen shot 2015-12-16 at 16 09 02](https://cloud.githubusercontent.com/assets/1794099/11844487/57371f58-a40f-11e5-9dac-e61e6f574cc0.png)

**Comment by bpasero** [comment]
@jrieken so from the UI I see that things look ok to me, there is no untitled file left around after the save completes. However the underlying text document is different from the untitled document to the saved document, they have different URIs so they end up to be different models in the model service. 

When an untitled file gets saved, I emit the `UNTITLED_FILE_DELETED` and dispose the untitled document and it is replaced with the file document.

I guess on the PH side what would need to happen is that the untitled document is wired up to the text file document after the save has completed.

**Comment by jrieken** [comment]
yeah, we should bubble up !dirty-state and also set an internal isClosed/Disposed flag on the document.

**Comment by bpasero** [comment]
@jrieken https://github.com/Microsoft/vscode/pull/1408

**Comment by xconverge** [comment]
@bpasero I think that this exists again... was there a test to cover this scenario?

**Comment by bpasero** [comment]
@xconverge I cannot reproduce and we seem to have a similar test to check (https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/workspace.test.ts#L87). The snippet works OK for me on Mac:

```typescript
workspace.openTextDocument(Uri.parse('untitled:///Users/jrieken/Desktop/file.txt')).then(doc => {
        console.log(doc.uri);
        console.log(doc.isDirty);

        setTimeout(function() {
            console.log('SAVING')
            doc.save().then(value => {

                console.log(value);
                console.log(doc.isDirty);
                console.log(doc.uri);
            });
        }, 2000)
    });
```

**Comment by xconverge** [comment]
What about if you press Cmd+N, type a few chars and then check isDirty?

I am not 100% sure I follow what Uri.parse('untitled:///Users/jrieken/Desktop/file.txt') is doing but it looks different than what I would expect Cmd+N to be doing

**Comment by bpasero** [comment]
@xconverge I suggest you try to write a test case for this so that we can add it to our integration tests and fix it if needed 👍

**Comment by xconverge** [comment]
Ok I will try to see if I can build from source, I am guessing something like this:

```
test('New untitled file is dirty when changed', function (done) {
		vscode.commands.executeCommand("workbench.action.files.newUntitledFile");
		assert.ok(!vscode.window.activeTextEditor.document.isDirty);
		vscode.commands.executeCommand('default:type', { text: "abc" });
		assert.ok(vscode.window.activeTextEditor.document.isDirty);
		done();
	});
```

**Comment by bpasero** [comment]
@xconverge I can reproduce with that snippet. I suggest to create a new bug and also ping @jrieken on it.

**Comment by xconverge** [comment]
Right on, thanks for the quick conversation

**Comment by jrieken** [comment]
This could be #11339 but the snippet in https://github.com/Microsoft/vscode/issues/723#issuecomment-252167493 isn't correct because it doesn't wait for the commands to have executed. @xconverge Can you `then` on the promises `executeCommand` returns?

Also, why do you use the `newUntitledFile` command instead of the [API](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3778) we provide for that?

**Comment by xconverge** [comment]
@jrieken This is what we are using in the Vim plugin, the command not the API, not sure the history or why. Yes I agree the test I wrote looks to be the same as 11339 but this is not a timing thing (even though my test makes it look that way). It seems any file I create with the files.newUntitledFile command never get marked dirty.

Yes I know the snippet I sent is not correct, but I can't compile the vscode tests correctly for some reason so I wanted to give a starting point, perhaps the one below.

In my use case, the file is already open with changes, and I just check isDirty on it at some point later and it is false. (I am not trying to do exactly what this test does, the opening of the file is already done in my use case)

```
	test('New untitled file is dirty when changed', function (done) {
		vscode.commands.executeCommand("workbench.action.files.newUntitledFile").then(() => {
			assert.ok(!vscode.window.activeTextEditor.document.isDirty);
		});
        vscode.commands.executeCommand('default:type', { text: "abc" }).then(() => {
			assert.ok(vscode.window.activeTextEditor.document.isDirty);
		});
        done();
    })
```

**Comment by jrieken** [comment]
> what we are using in the Vim plugin, the command not the API, not sure the history or why.

I would strongly recommend to use the API then. There is contract nor guarantee how that command currently and in the future will work.

**Comment by xconverge** [comment]
Will do, however I think I also saw this when just using CMD+n to create a new document, which I assume uses the right API. I will see if I can get vscode to compile eventually and run the tests myself to be able to file a better issue. Thanks

**Comment by xconverge** [comment]
@jrieken Was trying to just make a quick change to use the api you recommended but I can't seem to get the same results with the API as I can with the command... I am just trying to create unique documents, I have even tried something like this:

```
    await vscode.workspace.openTextDocument(vscode.Uri.parse("untitled:" +
          Math.random().toString(36).replace(/[^a-z]+/g, '').substr(0, 10)))
```

And it names them all Untitled-1, I have also tried using a random string as an argument

Everytime I call

```
 await vscode.commands.executeCommand("workbench.action.files.newUntitledFile")
```
however, it is a uniquely named file... Untitled-1, Untitled-2, Untitled-3 based on which are already taken.

**Comment by jrieken** [comment]
This works for me - tho there is something weird as needs the slash-separator after the `untitled` scheme. Also check you developer console for any error

```ts  vscode.workspace.openTextDocument(vscode.Uri.parse('untitled:/autumnwinterspringsommer')).then(doc => { 

            console.log(doc.uri.toString());
            vscode.window.showTextDocument(doc);
        });
```

**Comment by xconverge** [comment]
If you use that to open 3 documents, what are they called in the tab bar? For me they are all Untitled-1, with the command, they are Untitled-1, Untitled-2, Untitled-3

**Comment by jrieken** [comment]
Their name (fullpath) is derived from the URI - in that case `/autumnwinterspringsommer`
