### ISSUE TITLE
Sometimes the Markdown preview stops updating

### ISSUE THREAD

**Issue by EFanZh** [microsoft/vscode#72671]
Issue Type: <b>Bug</b>

----

Sometimes the Markdown preview stops updating when I am typing if the source document is very large.

It is not easy to reproduce, but when it happens, it is very annoying.

Here is a video clip to describe what happened:

![markdown-preview](https://user-images.githubusercontent.com/2160692/56467141-96fe0500-644d-11e9-9b2a-7963ac066d25.gif)

Notice that at the end, no matter how long I wait, the preview never updates (two `r`s are missing from the preview). It is acceptable if the preview has some delay if the source document is very large, but this seems like some scheduling issue that the final updates from the source document is ignored.

The preview should be updated to match the source document if I wait long enough.

----

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.68GB (51.96GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by skprabhanjan** [comment]
@EFanZh , Yes this is happening and I think this happens in the case when you change something and then wait for like 2/3 seconds and change something again and similarly repeat it or stop, Just changing once seems to be working but takes some time.
@mjbvz , I think the refresh preview calls are getting clogged because of the way the user is updating the markdown document , Can you please confirm any way we can fix this ?

**Comment by mjbvz** [comment]
@skprabhanjan Thanks looking into this. I'm having trouble reproducing this issue but there are two places where I believe that updates to the preview could be getting out of sync:

1. In the call to `doUpdate` itself: https://github.com/microsoft/vscode/blob/312b09cc6b414663a2eabd78e6d79e7be0888436/extensions/markdown-language-features/src/features/preview.ts#L415 We're currently stabilizing vscode's master branch but here's a PR that should fix this: https://github.com/Microsoft/vscode/pull/73049

1. In the updates to the webview content itself. Here's the code that runs inside the webview that does the update: https://github.com/microsoft/vscode/blob/fbf201b2fc79684f464f049d8baa1fcc461adb83/src/vs/workbench/contrib/webview/browser/pre/main.js#L239

If you can reproduce this problem, try taking a look the PR and try it out on your local machine to see if it fixes this.

**Comment by skprabhanjan** [comment]
@mjbvz , Not sure exactly how to fix this as the issue is not consistent and when I checked it today it seems to work ( but surely the preview refresh and sync takes some time which is considerable for that large file) , So I leave it open for you to take a call on this.
I would suggest @EFanZh to check it again and give it some time to update.

**Comment by mjbvz** [comment]
@EFanZh  Please test this on the VS Code 1.35 insiders builds that should be coming out at the end of next week

**Comment by mjbvz** [comment]
@EFanZh New insiders builds are out. Can you please test this again using them

**Comment by EFanZh** [comment]
It still happens:

![image](https://user-images.githubusercontent.com/2160692/57962342-324ca200-7948-11e9-8c79-5a1bb9206934.png)

**Comment by mjbvz** [comment]
I'm closing this given that no one else has reported this issue and no one on the vs code team can reproduce it either

@EFanZh Please investigate and submit a fix if you are consistently running into this. I've linked to most of the relevant code locations
