### ISSUE TITLE
The cls command doesn't clear the terminal (Windows 10 1903, ConPTY)

### ISSUE THREAD

**Issue by taminn** [microsoft/vscode#72708]
Issue Type: <b>Bug</b>
I update my windows 10 to 1903 today.
The terminal will show 
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。
尝试新的跨平台 PowerShell https://aka.ms/pscore6
when I open the terminal.
![image](https://user-images.githubusercontent.com/37473907/56499773-76f83f80-653a-11e9-8d63-7ba4cc7e4f75.png)

some message is useless,so I want to clear it,and I find the bug when I enter cls
![image](https://user-images.githubusercontent.com/37473907/56499784-84152e80-653a-11e9-8df6-79f2e162e213.png)
![image](https://user-images.githubusercontent.com/37473907/56499816-aeff8280-653a-11e9-8a80-03d04b6099ad.png)
![image](https://user-images.githubusercontent.com/37473907/56499912-377e2300-653b-11e9-8e21-cc4bff4fc772.png)

and please delete that"尝试新的跨平台 PowerShell https://aka.ms/pscore6"

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (4.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
(1 theme extensions excluded)

**Comment by taminn** [comment]
ok,I find more bug at 1903
![image](https://user-images.githubusercontent.com/37473907/56501114-2c79c180-6540-11e9-9cea-5e3bb645a292.png)
it could alse be caused by terminal

**Comment by taminn** [comment]
cmd alse exist bug
![image](https://user-images.githubusercontent.com/37473907/56501285-c5a8d800-6540-11e9-87bb-884df28d1f17.png)
![image](https://user-images.githubusercontent.com/37473907/56501313-deb18900-6540-11e9-82bc-38769decd0ae.png)

**Comment by taminn** [comment]
and sometimes I close terminal will meet it
![image](https://user-images.githubusercontent.com/37473907/56501410-436ce380-6541-11e9-9024-f7d6aab23456.png)

**Comment by mooretc2** [comment]
I just tested this with both cmd and PS on Windows and `cls` worked as expected for me. Can you give any more information on your setup?

**Comment by taminn** [comment]
> I just tested this with both cmd and PS on Windows and cls worked as expected for me. Can you give any more information on your setup?

This is my windows 10 version 1903 download link from http://msclub.net/res/res
-----------------------------------------------------------
ed2k://%7Cfile%7Ccn_windows_10_consumer_editions_version_1903_x64_dvd_8f05241d.iso%7C4905476096%7CF28FDC23DA34D55BA466BFD6E91DD311%7C/
-----------------------------------------------------------
and language is Simplified Chinese
PowerShell problem has been solved when I update windows
but cmd still has the problem

**Comment by Tyriar** [comment]
I can reproduce it, it happens _sometimes_ on shells using ConPTY. Needs more investigation as to why. Comparing good/bad logs [using this](https://github.com/Microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging) is where I would start if anyone wants to take a stab at this one.

**Comment by aqez** [comment]
Also happens for me. I've tried different shells (cmd, powershell, git bash) all on windows, as well as different renderers (canvas and dom for each). Doesn't appear to affect my linux machine though. 
![image](https://user-images.githubusercontent.com/8353400/56780248-297f0b00-67a4-11e9-9f27-c86a2a776dc5.png)

**Comment by starship863** [comment]
I can also confirm this with both git bash and wsl bash terminals on my Windows 1903.

**Comment by Tyriar** [comment]
@starship863 first step is to validate that ConPTY is indeed sending the wrong data by investigating logs of when it works and when it doesn't using the https://github.com/Microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging, if ConPTY is in the wrong we should them move this issue up to https://github.com/Microsoft/console. We should validate here first though as I don't want to waste their time.

**Comment by kele1997** [comment]
@Tyriar I get the log,[here](https://gist.github.com/kele1997/887355a690a32f025dd476d21bd3eaca).
When I run command on cmd,it works fine.(I run three command on cmd, `dir`,`dir`,`clear`）  
When I run command `wsl`,toggle to wsl shell,it happens.(I run three commands on bash `ls`,`ls`,`clear`) ,and there are so many `Unknown CSI code` errors

**Comment by Tyriar** [comment]
I found the bug, the terminal isn't flagging lines to be re-rendered again after erasing characters. It's only showing itself when conpty is on because it uses this particular escape sequence (CSI Ps X) to clears out cells.

**Comment by starship863** [comment]
> I found the bug, the terminal isn't flagging lines to be re-rendered again after erasing characters. It's only showing itself when conpty is on because it uses this particular escape sequence (CSI Ps X) to clears out cells.

Hurrah!

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/2148

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/pull/74858

**Comment by tipleavalentin** [comment]
vscode 1.35 stable  and insiders 1.36 - "workbench.action.terminal.clear" command clears the terminal but if you switch and come back to you get the same stuff like before...

**Comment by Tyriar** [comment]
@tipleavalentin that's a different issue because of how conpty works, see https://github.com/microsoft/vscode/issues/75141

**Comment by Morgy93** [comment]
Still having the exact same issue with 1.35.1 ?!

![image](https://user-images.githubusercontent.com/7961978/59907473-6d406a80-940b-11e9-9927-4288cbd7c596.png)

![terminal](https://user-images.githubusercontent.com/7961978/59907593-bd1f3180-940b-11e9-9fe9-cf29f9aa0d22.gif)

**Comment by tipleavalentin** [comment]
@Morgy93 same issue I have on 1.35.1. Also 1.36 insider also doesn't clear after I switch terminal tavbs.

**Comment by Tyriar** [comment]
@tipleavalentin what do you mean clear after switching terminal tabs? It's not meant to clear then?

**Comment by tipleavalentin** [comment]
@Tyriar Here's a video I made: https://youtu.be/HsQ2GS_hbjw

**Comment by tipleavalentin** [comment]
The command I run was: workbench.action.terminal.clear

**Comment by tipleavalentin** [comment]
The issue is present in the latest insider version, so no fix was done for this. I run Windows 10 x64 1903 18362.175 with git bash 2.22.0.windows.1.

**Comment by Tyriar** [comment]
@tipleavalentin that's this issue https://github.com/microsoft/vscode/issues/75141
