### ISSUE TITLE
Windows: Color of subpixel rendering changes when opening menu bar

### ISSUE THREAD

**Issue by kroppt** [microsoft/vscode#75615]
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

I also double checked that the problem is on the Insider's Build.

**Steps to Reproduce:**

1. Observe text on screen. It should have gray subpixel rendering.
![1](https://user-images.githubusercontent.com/14015672/59582781-56b2b000-90a7-11e9-9883-77a1524f9e91.png)
2. Open menu bar.
3. Observe text on screen. It should have RGB subpixel rendering.
![2](https://user-images.githubusercontent.com/14015672/59582788-5c0ffa80-90a7-11e9-9a32-7ece84eda963.png)

This issue occurs on all text (except the menu bar submenus). I noticed it, because the text rendering looks better, but only when the menu bar was open! I would prefer all of it to use RGB subpixel rendering, like my other applications.

**Does this issue occur when all extensions are disabled?:** Yes

**Comment by Tyriar** [comment]
Verified this is happening. SPAA gets disabled depending on a bunch of factors.

**Comment by alexr00** [comment]
I'm seeing this revered now.
No menu open, RGB:
![image](https://user-images.githubusercontent.com/38270282/60188900-55fce500-9830-11e9-926e-383c4ecd1241.png)

Menu open, gray:
![image](https://user-images.githubusercontent.com/38270282/60188926-62813d80-9830-11e9-90cf-d7b5f6b3d137.png)

**Comment by sbatten** [comment]
The fix didn't work so I just reverted it, will look for a better after shipping

**Comment by Eldaw** [comment]
In version 1.36.1, I currently see the following:

- Top-level menu items that haven't been clicked: Grey subpixel rendering

- Top-level menu items after being clicked: RGB subpixel rendering

- Submenu items: Grey subpixel rendering

- Tab Headers: Grey subpixel rendering

- Text content of open files: RGB subpixel rendering

**Comment by sbatten** [comment]
tested with latest exploration, not changed

**Comment by bpasero** [comment]
@sbatten @alexr00 I encourage you to try to reproduce running from web and then report it to Chrome. I don't think it is Electron to blame.

**Comment by alexr00** [comment]
I can't repro this with web and alternate menu.

**Comment by bpasero** [comment]
@alexr00 thanks for trying this, I will go ahead and close this given this is possibly fixed by E6 update.

**Comment by Eldaw** [comment]
Before closing, did you also test all of these inconsistencies reported in this thread?

Top-level menu items that haven't been clicked: Grey subpixel rendering

Top-level menu items after being clicked: RGB subpixel rendering

Submenu items: Grey subpixel rendering

Tab Headers: Grey subpixel rendering

Text content of open files: RGB subpixel rendering

Side Bar (Extensions, Search, Explorer, etc.): Grey subpixel rendering

Terminal / PowerShell console content: RGB subpixel rendering

Terminal Headers (Problems, Output, Debug Console, Terminal): Grey subpixel rendering

**Comment by bpasero** [comment]
@Eldaw how about you try our insiders build for a while and report the results back?  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by kroppt** [comment]
Insiders:
RGB subpixel rendering occurs only for the terminal. Gray everywhere else. Thus, the precise problem of this particular issue is not testable.

**Comment by Eldaw** [comment]
@bpasero I already went to the effort of testing all the above scenarios previously. What you're saying is that rather than have somebody at Microsoft try out what I already did, you want to put the onus back on me and ask me to do even more testing on my side. All the while knowing that you'd already decided to simply close the issue anyway. I agree with others that have been saying the VS Code team doesn't seem to show the appropriate level of respect and gratitude for the time and effort spent by others reporting issues.

**Comment by kroppt** [comment]
@Eldaw I think it is more the case that because the Insiders build has a newer version of Electron, a lot of new variables are at play. It's not as though they will go back and fix the stable version just for something minor like this, so it's only worthwhile to work based off the Insiders build. They probably have many issues which they need to complete, so when something is just working, they probably prioritize things currently broken.

**Comment by bpasero** [comment]
> RGB subpixel rendering occurs only for the terminal. Gray everywhere else. Thus, the precise problem of this particular issue is not testable.

I would not give up so early. If we can reproduce this in Chrome alone, then we can start reporting this upstream. This is possible now with: 
* `git clone https://github.com/bpasero/vscode-runner.git`
* `yarn`
* `yarn web`

It should open a VSCode UI in your browser (a lot less functional, but should do it for this purpose).

@Eldaw yes, the intent of my question was to try to reproduce this because insiders ships with a Chrome version of 76, while stable is on 69. That is 7 (!) Chrome versions ahead with thousands of people having worked on it. Often rendering issues like this one are resolved meanwhile if you take the amount of changes into account that went in.

**Comment by sbatten** [comment]
In latest insiders, I can still reproduce the menu issue:

**Top** Menu closed
**Bottom** Menu open
![image](https://user-images.githubusercontent.com/6561887/67117375-634f2e00-f197-11e9-8f49-41de02cd6c82.png)

**Comment by Eldaw** [comment]
Which probably means all/many of the other inconsistencies reported in this issue haven't changed either. The strategy that certain members of the VS Code team advocate, which basically boils down to "leave an issue for a few months, then close it with the reason that the overall codebase has changed a lot over that time so maybe it's not valid anymore" makes no sense. Using that strategy and ethos, nothing would ever get fixed.

**Comment by kroppt** [comment]
@Eldaw Firstly, the fact that it was re-opened (by the person who closed it) after additional information indicates that closing it was a mistake. Second, nobody is advocating that strategy. A basic test was performed to ascertain whether the issue still exists, but it was not rigorous enough to be considered valid. All you have to do when you see a mistake is provide evidence that to the contrary, and that should be enough. Perhaps it would help if you provided methodology for dealing with issues which have many variables like this one. I can't imagine that a situation in which the developers test every potential issue rigorously leaves room for fixing actual problems.

**Comment by Eldaw** [comment]
@kroppt The issue that you logged was inappropriately closed by the developers and I was the first to question why it was closed. And now you're against me? Put simply, an invalid test was done (instead of a valid test of the things I'd highlighted and added to your issue) and that was good enough for the developer to consider that this issue should be closed. Yes, he has corrected that now, after his decision was questioned. What doesn't make any sense is why you want to argue with me now, when I'm trying to help keep your issue open until it is fixed.

**Comment by kroppt** [comment]
@Eldaw  
> The issue that you logged was inappropriately closed by the developers and I was the first to question why it was closed. And now you're against me?

I do not argue against people, but rather against ideas, which you happened to write.

> Put simply, an invalid test was done (instead of a valid test of the things I'd highlighted and added to your issue) and that was good enough for the developer to consider that this issue should be closed. Yes, he has corrected that now, after his decision was questioned.

I agree about the invalid test, as that's what I said above. I appreciate your efforts in documenting the problem.

> What doesn't make any sense is why you want to argue with me now, when I'm trying to help keep your issue open until it is fixed.

I don't think it is helping as much as you think.
We're all here for the same reason. I think you should be more professional is my basic point. Part of that is typing clearly and precisely. I don't really see how some of what you said is relevant to the issue at hand.
So, I think we should stop talking about it on this issue, since the complaints have already been voiced.

**Comment by bpasero** [comment]
Reported as: I wonder if this issue is reproducible when running VSCode in a browser or bare Electron. For that purpose, can you please:
* install `git` if not installed already (https://git-scm.com/)
* install `node.js` if not installed already (https://nodejs.org/en/download/)
* install `yarn` if not installed already (https://yarnpkg.com/lang/en/docs/install)
* `git clone https://github.com/bpasero/vscode-runner.git`
* `yarn`
* Web (Chrome only): `yarn web`
* Electron: `yarn electron`

And report back if you still reproduce the issue **in either or both web and Electron**?

**Comment by kroppt** [comment]
I tried the instructions you listed for VSCode Runner, and it didn't seem to work. Many of such errors:
```
Error: ENOENT: no such file or directory, stat 'C:\Users\User\code\vscode-runner\.build\vscode-web\out\vs\code\browser\workbench\workbench.js'
```
The page is blank for both web and electron. Same errors in both.
Perhaps I missed some implied step? the `.build` folder is empty.

**Comment by jbracer19** [comment]
i believe it ran correctly at least on the web :)

**Comment by bpasero** [comment]
@kroppt @Eldaw quick question: when you close all opened editors and hide the sidebar, does that make any difference with regards to the menu?

**Comment by bpasero** [comment]
This seems to be caused by Chrome putting the submenu on a different layer when expanded:

![image](https://user-images.githubusercontent.com/900690/67394940-5d958600-f5a5-11e9-9bfe-3678fe2af82e.png)

As explained in https://bugs.chromium.org/p/chromium/issues/detail?id=1016062#c18

**Comment by bpasero** [comment]
![before](https://user-images.githubusercontent.com/900690/67395591-8d915900-f5a6-11e9-9c72-2541e8ac19bc.gif)

**Comment by kroppt** [comment]
@bpasero I get that the RGB subpixel rendering only shows up on the menu bar when all files are closed and the sidebar is closed. This behavior is the same for stable and insiders.

**Comment by alexandrudima** [comment]
IMHO I don't think the fact that Chromium decides to create a layer for the menu is a bug. I consider more a bug the fact that the menu, when it is a separate layer, is rendered with sub-pixel AA off.

IMHO the menu should improve its DOM and make sure it respects the following rules (taken from https://www.html5rocks.com/en/tutorials/internals/antialiasing-101/):
![image](https://user-images.githubusercontent.com/5047891/67554251-4bcff200-f70f-11e9-9c92-4cbf4d26a692.png)

That means we might need to give up on shadows or have two dom nodes, each one on a separate layer (layers can be created via `will-change`), one with the shadow and one with the text content.

**Comment by bpasero** [comment]
@kroppt can you try with setting `"editor.disableLayerHinting": true` ?

**Comment by kroppt** [comment]
@bpasero Adding that setting removes RGB subpixel rendering when editing text in the situations in which there is RGB subpixel rendering for text, which is currently only stable (1.39.2).

**Comment by sbatten** [comment]
latest insiders for me is showing greyscale whether the menu is opened or closed, anything that should have changed this @bpasero @deepak1556 ?

**Comment by bpasero** [comment]
Not to my knowledge, can you check in devtools if the menu is put on a separate layer?

![image](https://user-images.githubusercontent.com/900690/67741227-b9826380-fa18-11e9-8f5f-3f604d05191c.png)

**Comment by bpasero** [comment]
Strange, my understanding is that subpixel-aa only gets disabled when the component moves to another layer. But maybe there are more cases...

**Comment by sbatten** [comment]
it may be the result of moving the window controls to icon fonts and using opacity there based on @alexandrudima's comment

**Comment by bpasero** [comment]
This still reproduces even with our latest changes, only when the menu is expanded.

**Comment by sbatten** [comment]
Like our other components, the menu suffers from having a shadow, having an animation, and additionally a transparent border on menu entries. 

While I could fix the transparent border issue, fixing with the shadow and animation requires introducing a new GPU rendering layer and that will break submenus as I can't get them to render properly once they've been explicitly promoted.

Also, getting rid of the shadow or animation really hurts the appearance of menus.

After all this SPAA investigation, it is very disappointing how much time our team has had to sink into an issue that app developer's shouldn't need to worry about.
