### ISSUE TITLE
Copying a file overwrites the original file with an empty file

### ISSUE THREAD

**Issue by thomas-darling** [microsoft/vscode#76861]
- VSCode Version: 1.36.0
- OS Version: macOS 10.14

Steps to Reproduce:

I can't find a way to consistently reproduce this bug, but I've experienced it multiple times, most recently a few minutes ago, in the latest release of VS Code. I think it might have started somewhere around 5-8 weeks ago, but I'm not exactly sure.

The scenario appears to be as follows:

When you try to make a copy of a file, by pressing the option key while dragging the file to the same folder as the file currently resides in, it should create a copy of the file next to the original file, with a number (or in the latest release " copy") appended to the file name. However, when the bug occurs, instead of creating a copy of the file, it instead **overwrites the original file with an empty file**.

This does not appear to be specific to any file or file type, but rather a state VS Code gets into, where copying _any_ file causes this behavior. I'm not sure if the bug also occurs when copying the file using other methods.

I've attached a screen recording showing the bug. Note that I had a build task running at the time, watching all the files. I tried stopping that task after the recording, but the bug continued to occur - however, it magically went away shortly after, so maybe that was somehow a factor - or maybe it was just a coincidence, as I'm pretty sure I've also experienced this with no tasks running.

[Screen Recording 2019-07-08 at 11.07.04.zip](https://github.com/microsoft/vscode/files/3367733/Screen.Recording.2019-07-08.at.11.07.04.zip)

Does this issue occur when all extensions are disabled?:
Don't know, as I cannot reproduce the bug consistently.

**Comment by bpasero** [comment]
This looks scary, but I cannot reproduce. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by thomas-darling** [comment]
Yeah, this definitely caused a couple of scares - luckily I've been saved by version control so far.
The problem is, until yesterday, it had actually been a week or two since I last observed the bug, so it's not really something I can easily test and reproduce 😕

I'll try to collect more info next time it happens, but given how rare this is, it might need a different approach - maybe consider adding some temporary telemetry, to detect if this happens to anyone else?

**Comment by bpasero** [comment]
Yeah possibly. Would also be interesting if it reproduces when extensions are disabled and no external tool is watching.

**Comment by thomas-darling** [comment]
Absolutely - it's just really hard to work for weeks without those things 😉

Regarding the build task, it's a pretty standard Webpack build task, that writes the output to a separate output directory. It's been working flawlessly for more than a year, with no recent code changes - and as mentioned, I tried stopping the task, and the bug still occurred, so it seems unlikely it was involved.

Regarding the extensions, the only extension I could imagine having anything to do with this would be GitLens - the other extensions I have installed are specific to certain file types, and since this happens to all files, of any type, it seems unlikely they would be involved - but that's just a guess, of course.

**Comment by bpasero** [comment]
What I find weird is that even though a copy operation is initiated, you do not actually get a copy of the file, you get an empty file. 

@isidorn could there be any chance that we initiate a copy operation on the same path as target? Because I do delete the target file prior to the copy operation and that could maybe explain why the file turns out to be empty.

**Comment by isidorn** [comment]
@bpasero this check [here](https://github.com/Microsoft/vscode/blob/680ce7a9610281ec78dead8a618154772deec85f/src/vs/workbench/contrib/files/browser/fileActions.ts#L1027 should prevent the case that it overwrites, but it adds it as a new child of the parent. With this check [here](https://github.com/Microsoft/vscode/blob/680ce7a9610281ec78dead8a618154772deec85f/src/vs/workbench/contrib/files/browser/fileActions.ts#L1019)

I mean it can happen that I paste file `a` over `a`, but that will lead us to create a `a copy`

**Comment by bpasero** [comment]
Ok, I added a test that verifies that a file that either gets copied or moved to the same path is not getting emptied. Besides, we also throw an error in that case.

**Comment by thomas-darling** [comment]
Awesome to see such a quick response :+1:

Just a thought, could this have something to do with the casing of the file paths or OS detection?
For example, I noticed this at the end of one of those checks you reference, @isidorn

`!isLinux /* ignorecase */`

**Comment by bpasero** [comment]
I actually found a bug in the file service impl that would delete the file if `move()` method is called where source and target are equal. This still does not really explain why it could have happened from the explorer operation, but I pushed a change to throw an error in that case and make sure the file does not end up empty.

**Comment by bpasero** [comment]
I pushed https://github.com/microsoft/vscode/commit/5a834e71171b1f076a5278845269e1220b01d8c1

**Summary:**
* copy/move to exact same path will be a no-op without error now
* copy to same path with different case will throw an error on case-insensitive file systems

**Comment by isidorn** [comment]
@thomas-darling can you please try vscode insiders from Thursday and if you can no longer reproduce this issue then I think we are good and we can close this one?
Thanks!

**Comment by bpasero** [comment]
Optimistically closing.

**Comment by thomas-darling** [comment]
@bpasero Sorry guys, it looks like this is still happening 🙁 

I just encountered it again with the latest release (1.36.1), this time when option-dragging a folder to create a copy of it - and boom, instead of copying the folder, all the files within just became empty. This time the whole app didn't get into a bad state though, so I couldn't replicate it.

However, I had a look in the dev tools, and noticed this one was the most recent log entry:

```
log.ts:173   ERR URI malformed: URIError: URI malformed
	at decodeURIComponent (<anonymous>)
	at Function.parse (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:122:227)
	at t.createConverter.e (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:179835)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:179866)
	at L (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:185318)
	at Array.map (<anonymous>)
	at asDocumentLinks (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:188904)
```

I don't see any timestamps here, so I'm not sure if this is actually related, but given that this was the most recent entry in the console, and the only one of its kind, it might be worth looking into.
My file paths are perfectly normal by the way - no special characters or anything like that.

Before the above error, I also see several instances of the below error - again, I'm not sure when those occurred, so it's possible they are unrelated to this issue...

```
mainThreadExtensionService.ts:61 TypeError: Cannot read property 'document' of undefined
	at vscode.workspace.onDidChangeTextDocument (/Users/thomas-darling/.vscode/extensions/AureliaEffect.aurelia-1.0.3/dist/src/client/Preview/Register.js:10)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48)
	at c.$acceptDirtyStateChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:532)
	at d._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:653)
	at d._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:653)
	at d._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652)
	at d._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:651)
	at define.constructor._protocol.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:649)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:177)
	at e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:177)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48)
	at n.constructor.e.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:758)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:177)
	at e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:177)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48)
	at y._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:183)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48)
	at f.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:180)
	at define.constructor._register._socket.onData.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:179)
	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:188)
	at Socket.emit (events.js:182)
	at addChunk (_stream_readable.js:283)
	at readableAddChunk (_stream_readable.js:264)
	at Socket.Readable.push (_stream_readable.js:219)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94)
```

**Comment by isidorn** [comment]
@thomas-darling thanks for reporting. However please note that our fix is only part of [vscode insiders](https://code.visualstudio.com/insiders/). It will only be part of the stable release in a week. So it would be great if you try to reproduce with vscode insiders. Or let us know if you hit it again with the latest stable.

In case you hit it with insiders:
The errors do not look related, and I believe they are coming from extensions which you are using.

Let me just get the steps clear
1. You alt + drag a folder with some content in the VS Code explorer
2. When you drop, instead of the whole folder being copied with the content, the original folder gets emptied and there is no copy?

**Comment by thomas-darling** [comment]
Ahh, sorry - I somehow convinced myself there had been a release, but you are right, I'm still on the same version. And yeah, looks like extensions, but thought I'd let you know anyway, as you never know how errors might propagate 🙂

Regarding the reproduction steps, it's essentially the exact same as in the screen recording above, this time just with a folder instead of a file - note that I'm on a Mac:

1. Select a folder in the side bar.
2. Press and hold the `option` key while dragging the folder _to its parent folder_.
3. This _should_ create a copy of the folder, next to the original - but instead, it just clears the contents of all the files within the original folder. No copies are created, and the original files still exist - now they are just completely empty.

**Comment by isidorn** [comment]
Thanks for the repro steps. But let's wait and see if you can reproduce with the new version (since you do not have the fix).

**Comment by lramos15** [comment]
I did about 25 copy operations and was unable to reproduce this error, but it doesn't seem like the repro steps are clear this was the best I could do to "verify" the bug was fixed.

**Comment by isidorn** [comment]
@lramos15 thanks

**Comment by thomas-darling** [comment]
### Ok, let's debug this thing

I just encountered the bug again, and given that it's so hard to reproduce, and thus debug, I decided to go bug hunting for you 🙂 

It's the same scenario as before. I tried to `option` + drag my `slug-input` folder to its parent folder, but instead of creating a copy next to the original, it ended up overwriting all files within the original folder with empty files.

Note that I'm still on the same VS Code version as before (1.36.1) - i.e. not the insider build with the checks you've added. However, the investigation is interesting, as the root cause of this problem appears to hide much deeper in the code. Based on other issues I've seen reported here, I'm guessing there's a whole class of issues that can be traced back to the same root cause as this one.

Based on my debugging here, that root cause appears to be that `ExplorerItem`s representing directories are sometimes in an "unresolved" state. How does that happen? No idea, but I'll leave debugging that as an exercise for the reader 😉 

So, let's dive in: 

#### 1. Why does the target path end up being the same as the source?

`doHandleExplorerDrop` in `explorerViewer.ts` calls `findByPath` in `explorerModel.ts` with the`path`: `"/Users/thomas-darling/GitHub/lingu-io/frontend/src/shared/framework/components/controls/inputs/slug-input"`.

It calls itself recursively, until `this`, which is an `ExplorerItem`, represents the folder `"/Users/thomas-darling/GitHub/lingu-io/frontend/src/shared/framework/components"`.

Here, `this.isDirectory` is `true`, but `this.children` is an empty map - _which is wrong, as files do exist on disk, and are visible in the tree view_.

An interresting observation is that `this.isDirectoryResolved` is `false` here - this appears to be `true` for the parent folder, so I'm guessing this might explain why the children are missing.

![image](https://user-images.githubusercontent.com/6388663/62416529-bc013700-b63c-11e9-93b9-427655e79e63.png)

Since I don't know the details of how this all works, I'll let you take it from here 🙂 

However, a few notes:

- I also tried to copy something _outside_ of that unresolved `components` directory - and that worked perfectly. All files copied as expected - and indeed, there did not appear to be any "unresolved" directories along the way here. So it would appear that, _somehow_, some nodes just get into this "unresolved" state, and then things fail for every node below that.

- I also tried to copy the unresolved `components` directory itself, and that worked correctly too - which was to be expected, given that the problems should only appear once it gets to checking paths agains the _children_ of this directory. 

#### 2. Why does the files end up being empty?

`doHandleExplorerDrop` in `explorerViewer.ts` calls `copy` in `fileService.ts` with identical source and target paths. The `overwrite` parameter is `undefined`.

The `copy` method calls `doMoveCopy`, which calls `doValidateMoveCopy`. It looks like this _should_ have detected that the paths were the same, but it seems to get confused, and thinks this is a path change. (Note: I'm not sure I understand what providers are, so can't comment further)

![image](https://user-images.githubusercontent.com/6388663/62416829-29639680-b642-11e9-86a1-9614c7013dc5.png)

The extra check does determine the file exists, but still passes for the same reason - it thinks this is a case change.

This brings us back to `doMoveCopy`, where the incorrect belief that this is a case change, actually prevents it from deleting the file. It then calls the `copy` method on the `sourceProvider` - still with identical paths and overwrite `false`.

![image](https://user-images.githubusercontent.com/6388663/62416899-6a0fdf80-b643-11e9-8c5e-2c7e262c295a.png)

That `copy` method, which is in the `diskFileSystemProvider.ts` file, calls `validateTargetDeleted` to ensure the target does not exist - and if it does, it _should_ delete it.

![image](https://user-images.githubusercontent.com/6388663/62417655-4eadd000-b655-11e9-8386-ca4ff88ced63.png)

Now, the source maps were a bit messed up by async/await stuff here, but it lookes like it once again thought this was a case change, and therefore _did not_ delete anything. Moving along, it then calls `copy`, imported from `pfs.ts`.

That method _does_ see the source files, and at this point, **the files also still exist on disk, and still have their content**. So yeah, no damage done, yet.

![image](https://user-images.githubusercontent.com/6388663/62417056-ddffb700-b646-11e9-9a38-33e1cb0817a4.png)

Eventually, when copying each file, which at this point does have content on disk, it pipes the `reader` to the `writer` on line 618. This appears to finish successfully, **but in reality, the file on disk is now empty**.

![image](https://user-images.githubusercontent.com/6388663/62417195-148b0100-b64a-11e9-8591-7733792bdb25.png)

So that's why the files end up empty, when source and target path are the same.

**Comment by thomas-darling** [comment]
@bpasero, @isidorn
Just want to make sure you didn't miss the above 🙂 

Based on my findings above, I think it would make sense to reopen this issue - or maybe a new issue should be created, specifically for the directory resolving bug that seem to be the root cause of this.

**Comment by bpasero** [comment]
@thomas-darling very nice analysis. I agree, you seem to be haunting down 2 issues here, from the explorer and from the file service. Since we did not change anything in the explorer so far, I suggest you extract that into a separate issue.

As for the file service: it would be great to replay your study with latest insider that includes all my changes if possible. As you can see from this:

https://github.com/Microsoft/vscode/blob/2a829f92906b5836fb59a8a4140f43288eecdf07/src/vs/platform/files/common/fileService.ts#L557-L559

I added a check to not do anything at all if source and target are identical. So I would not assume you could reproduce that case anymore.
