### ISSUE TITLE
vs code spawns lsof processes which gobble up CPU

### ISSUE THREAD

**Issue by Choongkyu** [microsoft/vscode#78438]
- VSCode Version: 1.36.1
- OS Version: macOS 10.14.5

MacBookPro 2018 2.7 GHz Intel Core i7 16GB 2133 MHz RAM Intel Iris Plus Graphics 655 1536 MB

Steps to Reproduce:

1. Open vs code
2. Open terminal in vs code
3. Open process explorer
(3.5. use vs code or leave idle for varying periods)
4. See multiple lines of `lsof -p 27620`, each with around 64% of cpu usage (90% if extensions are enabled) while laptop fans are whirring

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by Tyriar** [comment]
This should only be firing when you press enter within the terminal, debounced to happen never more than 2 per second, it should run almost instantaneously. What happens when you run the same command in a terminal?

**Comment by jflaflamme** [comment]
I have the same issue with multiple lsof from time to time.  Happens a lot since the last update and don't remember this happening before. Easily can get to over 10 lsof processes taking cpu.

Maybe an extension but which one?

**Comment by Tyriar** [comment]
@jflaflamme What happens when you run the same command in a terminal?

**Comment by jflaflamme** [comment]
> @jflaflamme What happens when you run the same command in a terminal?

I am not sure what you mean, I do a `ps -ef |grep lsof` and see multiple`lsof -p <pid>` all spawning each others. So then easily 5-10 processes taking big chunk of CPU.

**Comment by Tyriar** [comment]
@jflaflamme I mean does just running a single `lsof -p <pid>` in a terminal take an excessive amount of time? The vscode terminal should only be spawning these processes for a single process (the terminal that has activity).

**Comment by leseb** [comment]
Could this be related to the "find all reference" option in vscode? I just hit the exact same issue after using it (never actually used it before), reached out my max user processes, couldn't fork anymore, now I'm left with about 1081 lsof processes impossible to kill (not sure why).

**Comment by zebralight** [comment]
I was able to narrow this down to using terminal in vs code.  I've stopped using terminal in vs code since and haven't experienced this since.

**Comment by Tyriar** [comment]
Yes it's the terminal launching these processes. Please answer the question:

> I mean does just running a single lsof -p <pid> in a terminal take an excessive amount of time?

**Comment by jflaflamme** [comment]
> @jflaflamme I mean does just running a single `lsof -p <pid>` in a terminal take an excessive amount of time? The vscode terminal should only be spawning these processes for a single process (the terminal that has activity).

yes takes a lot of CPU and multiple processed are doing this. Happens with terminal and I took the habit of doing `killall -9 lsof` when my computer starts to be slow.  I have the latest vscode update.

**Comment by Tyriar** [comment]
If you open a terminal and run `lsof -p <pid>` on some process, does it take seconds to execute? It's instant on my machine.

**Comment by jflaflamme** [comment]
Hope this helps @Tyriar 

![image](https://user-images.githubusercontent.com/712558/65835048-e35a4480-e30b-11e9-9e5c-c9c14b32226f.png)

Just some extra info... 

Takes about 5-6 seconds to return to answer your question. MacBook Early 2013, i5, 10.12.6

```
date;lsof -p 69274;date
Sun Sep 29 22:55:09 +07 2019
Sun Sep 29 22:55:38 +07 2019
```

```
ps -ef |grep 'lsof -p'|wc
      16     191    1223
```

```
killall -9 lsof
killall -9 lsof
No matching processes belonging to you were found
date;lsof -p 69274;date  
Sun Sep 29 22:57:45 +07 2019
Sun Sep 29 22:58:01 +07 2019
```

**Comment by jflaflamme** [comment]
Might be related to my issue .. https://apple.stackexchange.com/questions/81140/why-is-lsof-on-os-x-so-ridiculously-slow/243269?noredirect=1#comment412641_243269

**Comment by Tyriar** [comment]
@jflaflamme looks promising

**Comment by jflaflamme** [comment]
> @jflaflamme looks promising

Not sure changing my laptop because of lsof :) 

In the meantime, I just stopped using the terminal within vscode. No more issues. However, I just can imagine how many people with a wide range of OSX version experiencing crazy slow machines without understanding why.

**Comment by Tyriar** [comment]
I don't really have good verification steps for this, probably do it via code review.

If anyone who has been experiencing this issue can verify whether it's fixed in the insiders build that would be great https://code.visualstudio.com/insiders/

**Comment by chrmarti** [comment]
@Tyriar Should you include `-n` to avoid hostname lookups? Or avoid all the extra information and use: `lsof -a -d cwd -F n -p $pid`

**Comment by robin-pham** [comment]
encountered this yesterday on vscode version 1.51.1 and catalina 10.15.7. Have since restarted my computer and the issue disappeared (seems flakey) but if I reproduce it again, will try to investigate.

**Comment by marqvi** [comment]
Although the debouncing works as of 1.52.1, the lsof use is still an issue on macOS 11.1. The command that is spawned to update cwd is `lsof -OPl` which performs hostname resolution. This causes the terminal to hang for up to 1 sec every time you press enter in the terminal. The fix is to add `-n` to disable hostname lookup here:

https://github.com/microsoft/vscode/blob/f3b8f4f765c11247be91bfd4ddd0669245f60ae6/src/vs/workbench/contrib/terminal/node/terminalProcess.ts#L338

**Comment by Tyriar** [comment]
@marqvi the Big Sur problem is actually related to Electron: https://github.com/microsoft/vscode/issues/105446, we should probably add the `-n` regardless though.

**Comment by Tyriar** [comment]
I added the `-n` which will come in the next version, the real fix to this would be a setting that drives it or dynamic detection of whether it's slow and disabling it for that session.

**Comment by Tyriar** [comment]
The [libuv fix](https://github.com/libuv/libuv/pull/3257) is not yet merged but we have it in our official builds, we'll likely fix up the broken cwd support in big sur+ in the upcoming iteration to get https://github.com/microsoft/vscode/issues/105446 working.

**Comment by TylerLeonhardt** [comment]
@jflaflamme you could also help us verify this fix

**Comment by TylerLeonhardt** [comment]
I ran this for a fairly long time and didn't see this issue so marking as verified.
