### ISSUE TITLE
commit message text introduces three lines after commiting

### ISSUE THREAD

**Issue by joaqcid** [microsoft/vscode#80640]
Issue Type: <b>Bug</b>

with changed files, set a commit message and click on commit, 

three new lines are added

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
angular2-snippets|dan|1.0.21
vscode-markdownlint|Dav|0.30.2
gitlens|eam|9.9.3
aio-docs-utils|gka|0.1.8
beautify|Hoo|1.5.0
docthis|joe|0.7.1
Angular2|joh|8.1.1
Angular-BeastCode|Mik|8.0.10
vscode-docker|ms-|0.7.0
csharp|ms-|1.21.2
vscode-yaml|red|0.5.2
autoimport|ste|1.5.3

</details>

**Comment by joaqcid** [comment]
![image](https://user-images.githubusercontent.com/6530160/64612497-5bd38280-d3aa-11e9-8e34-620a807f96f9.png)

**Comment by Cheldon** [comment]
I also am seeing this issue. It can appear when reopening the project as well. I may have had 3-4 repositories open in the source control tab and they all populate the commit message with empty lines.

Version: 1.38.0 (system setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by nspringer-trimble** [comment]
Also seeing this issue on commit.

Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by joaomoreno** [comment]
Do you have a git commit template message set up? https://thoughtbot.com/blog/better-commit-messages-with-a-gitmessage-template

**Comment by joaqcid** [comment]
yup, there a was a commit template :| , dont even know how it got there

Thanks! a lot

**Comment by Cheldon** [comment]
I also have a commit template but I've been using it for over a year. There were not any blank lines showing up in this box prior to this version.

Have not tried insiders. 

I'd expect either nothing to show up or the whole template (including # comment lines) to show up, not just blank lines.

Note: my template is 23 lines long (19 of which are comments) and there are 23 empty lines in my commit message box.

**Comment by jdratlif** [comment]
I do not have a git commit template, and it happens for me too. I'm on CentOS 7 with Code 1.38.1-1568209352.el7. I deleted all my settings, and it made no difference. Every time I open a git repo and go to the SCM panel, there is a blank line. Works fine if I downgrade to 1.37.1.

**Comment by joaomoreno** [comment]
@Cheldon That's https://github.com/microsoft/vscode/issues/80415 which was fixed a couple days ago. Insiders should work better for you now.

@jdratlif Please do re-confirm that you do not have a template or try to repro with `--disable-extensions`.

**Comment by jdratlif** [comment]
Thanks. I didn't realize my work has a default git template that was being used. I overrode it with /dev/null in my local git settings and things seem to work now.

**Comment by jfrux** [comment]
Oops, I had a file at `~/.gitmessage` even though I do not recall ever putting it there.
Removed git message from `~/.gitconfig` and restarted vscode and we all good.

Thanks!

**Comment by Cheldon** [comment]
Was this included in 1.39? I just updated and am still seeing 23 blank lines show up for the 23 lines in my commit template. My template consists of comments and whitespace.

Which of these is the expected behavior?
- Template + comments show up
- Template shows up, comments are removed
- No template shows up (this is what it did prior to 1.38)

Version: 1.39.0 (system setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by Cheldon** [comment]
So a sample line in my commit message is this:
`## ---------- One-line Summary (50 chars) -------|`
and it shows up blank in the commit message. If I add a valid character to the front
`a## ---------- One-line Summary (50 chars) -------|`
it shows up now. This is probably why all the lines in my commit message are showing up blank because they all are whitespace or start with a comment.
