### ISSUE TITLE
The search bar "disappears" (since v1.38.0)

### ISSUE THREAD

**Issue by daneesv** [microsoft/vscode#80826]
- VSCode Version: 1.38.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce (view video on zip).

**-While the search bar is open, at some point it changes its size and "disappears".**
-The error continues when focusing the search box.
-Only when the search text is deleted or modified, the bar returns to normal.
-I have not yet been able to detect what action this behavior produces.
-This began to occur as of update 1.38.0

Does this issue occur when all extensions are disabled?: I haven't tried it.
![searc_bar](https://user-images.githubusercontent.com/19726219/64823981-318eea00-d58f-11e9-8cde-e596a5a050b1.png)

[video.zip](https://github.com/microsoft/vscode/files/3607604/video.zip)

@roblourens

**Comment by alexandrudima** [comment]
@daneesv Do you remember something specific about what you were doing? (steps)

**Comment by daneesv** [comment]
> @daneesv Do you remember something specific about what you were doing? (steps)

@alexandrudima It took me a while to detect the moment when the error occurs.
1. Open Visual Studio Code.
2. Open a standard web project.
3. Open some files.
4. Press CONTROL + F to display the search box.
5. Test several times, everything works correctly.
**6. It is a problem that appears when you resize the search box to the sides (see attached image).**
7. Since that action is taken, the search box starts to malfunction.
8. The problem is solved by restarting the program.
9. When you enlarge the box again, the problem returns.

![screen2](https://user-images.githubusercontent.com/19726219/64873110-cd1b6b80-d61e-11e9-8cc1-5a92e87e204f.png)

**Comment by alexandrudima** [comment]
@daneesv Thank you for following through. I am still having a hard time to reproduce. Here I am following your steps:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/64941009-c5013d00-d865-11e9-8b06-1bd975428198.gif)


Would you mind to do a screen recording, perhaps there is something specific that you are doing which I am not. Thank you!

**Comment by daneesv** [comment]
@alexandrudima  Apparently the problem occurs when **resizing the search box**, and then **switching a tab**.

![7y5VKmXbyT](https://user-images.githubusercontent.com/19726219/64943669-c8cf9800-d842-11e9-8d8e-7103cc6a933e.gif)

**Comment by daneesv** [comment]
@alexandrudima I keep trying ... It seems that the problem occurs when creating a new document by clicking on the tab bar, or when switching with a tab of some document without saving. In combination with the resizing of the search bar. It's strange.

![nThrkiPwl3](https://user-images.githubusercontent.com/19726219/64945612-4d241a00-d847-11e9-8083-f719ebdf7279.gif)

**Comment by alexandrudima** [comment]
Thank you, I was able to reproduce! I could simplify the steps further:
- resize the find widget
- type `asd` in it
- switch to another file

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/64949911-8629b200-d87a-11e9-9db4-f847e1c530b0.gif)

**Comment by alexandrudima** [comment]
The root cause is that the find widget attempts to update its width at a time when it is not in the DOM -- it is still attached to the old view when switching models, so the input box is off-DOM and will incorrectly measure its height as 0 and cache it forever...
