### ISSUE TITLE
Git: Repository not detected if root folder ends in [space]

### ISSUE THREAD

**Issue by clementviolet** [microsoft/vscode#81158]
- VSCode Version: 1.38.1
- OS Version: MacOS High Sierra 10.13.6

Steps to Reproduce:

1. Fresh Git install (git version 2.23.0)
2. Fresh VSCode install (1.38.1)
3. Source Control tab in activity bar shows `no source control provider registered`
4. Settings shows in `settings.json`: `"git.enabled": true`
5. Find git location in terminal `"/usr/local/bin/git"`
6. Added `"git.path": "/usr/local/bin/git"`to `settings.json` to attempt to fix the bug
7. Source Control tab in activity bar shows still shows "no source control provider registered"
8. When clicking on the `+` sign on top right corner of Source Control tab, it add a `.git`folder in the workspace folder.  Confirmed by `ls -al ./`
9. Trying `Git: Show Git Output`=> `Looking for git in: /usr/local/bin/git Using git 2.23.0 from /usr/local/bin/git`
10. Checked `@builtin Git` Extension enabled

Does this issue occur when all extensions are disabled?: Yes

I have just started to use VSCode, but my git installation is not detected by the Source Control Tab.  If I work in a directory without using git, I can initialize a `.git` folder with the `+` sign, but I can't make commit. If I am in a directory with already a git tracking, I still have this `no source control provider registered` message.

**Comment by clementviolet** [comment]
Unfortunately, it doesn't help.

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`, when you open a folder which is a git repo?

**Comment by ExtAnimal** [comment]
I just "up" graded VS code and all source control is gone.

![Screenshot 2019-09-23 at 11 39 45](https://user-images.githubusercontent.com/200516/65415847-debafb00-ddf6-11e9-8940-6614517fcbfb.png)

**Comment by OneHatRepo** [comment]
Same here. Apparently VS Code auto-updated, and now I get the same as ExtAnimal's screenshot.

**Comment by ExtAnimal** [comment]
It really does have a productivity hit when I can't see modified code zones!

**Comment by OneHatRepo** [comment]
Turns out it wasn't VS Code that was the problem, I had recently updated Xcode and had to agree to new TOS. Once I did that git started working again.

**Comment by clementviolet** [comment]
Hi @joaomoreno, here the full output of `Git: Show Git Output`

```
Looking for git in: /usr/local/bin/git
Using git 2.23.0 from /usr/local/bin/git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
```

I would like to give you an update, earlier today I have created an other workspace. For this new workspace Git was automatically detected, but only for this one. 

So for the moment I only have two configured workstations, one with this problem and the second, the new one without.

@OneHatRepo I tried to update Xcode before opening this issue, but unsuccessfully.

**Comment by ExtAnimal** [comment]
It was XCode's fault. I had to start XCode, do "Check for updates", agree to the terms and update. The restart VS Code. Now I have source control.

You should probably flag this up as an issue.

**Comment by joaomoreno** [comment]
Same as https://github.com/microsoft/vscode/issues/81287

@clementviolet Could you check if this is your case too?

**Comment by clementviolet** [comment]
I've just ran `sudo xcodebuild -license` in the terminal. Here my full output :

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

I may have an issue with my Xcode installation...

**Comment by akaroml** [comment]
Another use is reporting similar issue microsoft/vscode-java-pack#222

**Comment by stickrive** [comment]
I also encountered the same problem.
1、uninstall VsCode,
2、remove all the extensions
3、`sudo rm -rf $HOME/.vscode`
then install new VsCode, it is work

**Comment by joaomoreno** [comment]
> I may have an issue with my Xcode installation...

@clementviolet Did you fix it?

**Comment by clementviolet** [comment]
I've fixed it and tried @ExtAnimal solution whiteout succes.

**Comment by joaomoreno** [comment]
You've fixed it? You no longer have the problem?

**Comment by clementviolet** [comment]
Sorry for this misunderstanding. I fixed my Xcode issue, but I did not fix my Git problem.

**Comment by joaomoreno** [comment]
Does `Git: Show Git Output` still show the same? Does `git status` from the command line work?

**Comment by clementviolet** [comment]
Hi! Here what's `Git: Show Git Output` return now:
```
Looking for git in: /usr/local/bin/git
Using git 2.23.0 from /usr/local/bin/git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
```

And `git status` still work fine.

**Comment by joaomoreno** [comment]
So, what does `git rev-parse --show-toplevel` and `git rev-parse --git-dir` return if you run it from your folder?

**Comment by clementviolet** [comment]
I've ran these commands through the VSCode console and I've got this :

```
(base) ClemBook:Homework  clementviolet$ git rev-parse --show-toplevel
/Users/clementviolet/Documents/Rennes 1/Semestre 9 - R1/ICE/Homework 
(base) ClemBook:Homework  clementviolet$ git rev-parse --git-dir
.git
```

**Comment by joaomoreno** [comment]
Can you reproduce the issue on other repositories? Namely, on a path which doesn't have spaces?

**Comment by clementviolet** [comment]
I thought It was due to the spaces, but here an other repo that have spaces and I don't have this issue. 

```
(base) ClemBook:Projet clementviolet$ git rev-parse --show-toplevel
/Users/clementviolet/Documents/Rennes 1/Semestre 9 - R1/ICE/Projet
(base) ClemBook:Projet clementviolet$ git rev-parse --git-dir
.git
```

Unfortunately, I can't reproduce it on other repo, even in which that doesn't have spaces.

**Comment by joaomoreno** [comment]
Can you run `Developer: Set Log Level...` and change it to `Trace` and then check the git output? Maybe more info comes out.

**Comment by clementviolet** [comment]
Here is the result in the repo that is problematic: 

```
Looking for git in: /usr/local/bin/git
Using git 2.23.0 from /usr/local/bin/git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
```

And in the previous repo where I don't have the issue, this is the output:

```
Looking for git in: /usr/local/bin/git
Using git 2.23.0 from /usr/local/bin/git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git config --get commit.template
Open repository: /Users/clementviolet/Documents/Rennes 1/Semestre 9 - R1/ICE/Projet
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse scenario2
> git rev-parse --symbolic-full-name scenario2@{u}
> git rev-list --left-right scenario2...refs/remotes/origin/scenario2
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -v -z --stdin
```

**Comment by joaomoreno** [comment]
Is `Homework` a symlink maybe?

**Comment by clementviolet** [comment]
No it's a directory :
```
drwx------@ 13 clementviolet  staff     416 22 sep 18:42 Homework 
```

**Comment by joaomoreno** [comment]
Can you reclone that repository into another folder? Does that work?

**Comment by clementviolet** [comment]
Ok, I've just figured out how to solve this bug. I had an space at the end of my git repo name. Instead of `/Homework/` I had `Homework\ /`. Removing the extra space fix this issue.

Maybe you could find a fix for handling extra space at the end of a folder? In any case, thank you for your help!

**Comment by joaomoreno** [comment]
I can definitely reproduce. Great catch!
