### ISSUE TITLE
Build Tasks Hang When Specific Built-in Extensions are Disabled

### ISSUE THREAD

**Issue by ssoher** [microsoft/vscode#83939]
- VSCode Version: 1.39.2
- OS Version: Windows 10 x64 1903 Build 18362.388

Steps to Reproduce:

1. Disable the built-in extensions below, reload
```
Grunt support for VS Code
Gulp supoprt for VSCode
Jake support for VS Code
NPM support for VS Code
TypeScript and JavaScript Language Features
```
2. Try running a build task, the status bar will show "Fetching build tasks..." forever

Below is my simple tasks.json that calls a Windows batch file to build a C project using gcc.

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build debug",
            "type": "shell",
            "command": "${workspaceFolder}/build.bat",
            "args": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

**Comment by alexr00** [comment]
@ssoher I can't reproduce this. Is it possible you have an extension that's depending on the built in typescript and javascript languages features are disabled? Can you try disabling all installed extensions and see if it still happens?

**Comment by ssoher** [comment]
@alexr00 I've disabled every single extension both external and built-in and restarted Code. The behavior is the same. Run Build Tasks resumes working immediately as I enable the TypeScript and JavaScript Language Features built-in extension.

**Comment by alexr00** [comment]
Do you have a sample repo I could try with? Have you tried with only the typescript extension and all installed extensions disabled (leaving other built-in extensions enabled)? Do you have any task or extension related settings set?

**Comment by ssoher** [comment]
Yes, I've tried that combination of extensions too. 

Here is a small project I'm encountering this issue on.
[c_opengl.zip](https://github.com/microsoft/vscode/files/3808437/c_opengl.zip)

My settings look unrelated, below is my settings.

```json
{
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "editor.fontFamily": "'Fira Code'",
    "editor.accessibilitySupport": "off",
    "editor.detectIndentation": false,
    "editor.dragAndDrop": false,
    "window.zoomLevel": 0,
    "editor.find.autoFindInSelection": true,
    "glsl-linter.validatorPath": "E:\\glsllangvalidator\\glslangValidator.exe",
    "window.menuBarVisibility": "default",
    "editor.minimap.enabled": false,
    "breadcrumbs.enabled": true,
    "editor.renderWhitespace": "none",
    "editor.renderControlCharacters": false,
    "editor.fontSize": 12,
    "editor.lineHeight": 18,
    "workbench.editor.closeEmptyGroups": false,
    "workbench.colorTheme": "Github Light Theme - Gray",
    "editor.cursorStyle": "block-outline",
    "javascript.suggest.autoImports": false,
    "todo-tree.general.tags": [
        "TODO",
        "FIXME",
        "BUG",
        "NOTE",
        "HACK"
    ],
    "todo-tree.highlights.customHighlight": {
        "TODO": {
            "background": "green",
            "foreground": "white",
            "opacity": "0.25",
            "fontWeight": "500",
            "icon": "checklist",
            "iconColour": "green",
            "type": "text",
        },
        "FIXME": {
            "background": "magenta",
            "foreground": "white",
            "opacity": "0.25",
            "fontWeight": "500",
            "icon": "alert",
            "iconColour": "magenta",
            "type": "text",
        },
        "BUG": {
            "background": "red",
            "foreground": "white",
            "fontWeight": "500",
            "icon": "bug",
            "iconColour": "red",
            "type": "text",
        },
        "NOTE": {
            "background": "cyan",
            "foreground": "white",
            "fontWeight": "500",
            "icon": "bug",
            "type": "text",
            "hideFromTree": "true"
        },
        "HACK": {
            "background": "green",
            "foreground": "white",
            "opacity": "0.25",
            "fontWeight": "500",
            "icon": "bug",
            "type": "text",
            "hideFromTree": "true"
        },
    },
    "workbench.editor.revealIfOpen": true,
    "sync.gist": "08afe2b70f2bc405af6ed3627b7f0008"
}
```

**Comment by alexr00** [comment]
Even with your exact settings and with that sample I cannot see the same issue. Some more questions:
If you open the Developer Tools, do you see anything suspicious in the console?
If you run the Tasks: Run Task command what happens? Are there any tasks listed there besides your build task?
Does the same thing happen if you remove the `group` from your task?

**Comment by ssoher** [comment]
When I re-enable the TypeScript and JavaScript Language Features built-in extension I get this error log in the Developer Tools console.
[-1572951426068.log](https://github.com/microsoft/vscode/files/3808598/-1572951426068.log)

There are no tasks listed besides my "build debug version"

I can't test what happens when I remove the `group` from my task because I'm not able to run it when that built-in extension is disabled. `Run Task` action tries to list tasks with an empty textbox on the screen and the UI element under the textbox that indicates it's looking for stuff going back and forth forever. It cannot find any tasks when that extension is disabled.

**Comment by alexr00** [comment]
The errors from the dev tools appear to be from naumovs.cursor-tools-2.0.0. Can you keep this extension disabled while we figure out what's going on?

Lets try a fresh state. Can you install the insiders build from https://code.visualstudio.com/insiders/ and try do your usual repro (it installs side by side with stable, so you won't be losing anything)? If it doesn't happen there, then either there's a real issue that's fixed in insiders or you have some bad state somewhere. When you try on insiders, can you see if you more errors in the developer

**Comment by ssoher** [comment]
The same problem persists in the Insiders version. I have some new findings though.
The problem goes away if I enable below built-in extensions. It is enough for any single one of these extensions to be enabled to be able to run build task again.
I wonder what is one thing in common for these extensions?

```
Grunt support for VS Code
Gulp supoprt for VSCode
Jake support for VS Code
NPM support for VS Code
TypeScript and JavaScript Language Features
```

While trying the repro, did you disable *all* extensions available int VS Code? Maybe you've left some of these enabled so you didn't encounter the same problem?

**Comment by alexr00** [comment]
I only disabled the typescript extension since that's what the issue is about :) The common thing between those extensions is that they all provide tasks. I'll try disabling all.

**Comment by alexr00** [comment]
I think this issue has been around as long as Tasks has been around. No one must be disabling those extensions. I've pushed a change that should fix it and that change will be available in insiders probably by the end of the week. Thanks for helping track it down!

For what it's worth, you can disable any task related code path that goes through task providers using the `task.autoDetect` setting (insiders only atm, but coming to stable soon). That won't stop those extensions from activating when you run at task related command, but it will stop them from trying to provide tasks (unless you have a task for one of them in tasks.json).
