### ISSUE TITLE
Search/Replace: running replace op should close any preview editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#88293]
Steps to Reproduce:

1. start a search/replace across files
2. open a couple of preview editors
3. complete the search/replace (or alternatively: cancel it)

=> I would expect that any of the 2 actions closes any preview editor I opened

//cc @jrieken for a similar problem in "Preview Refactor" land

**Comment by jrieken** [comment]
👉 WorkbenchState. My idea/wish for preview refactoring is that I can capture and restore the  workbench state. E.g it will know what views/panes and editors are around and enable me to restore such a state, e.g after applying a refactoring close all preview/diff editors and hide the preview refactoring pane.

 /cc @sbatten

**Comment by sandy081** [comment]
I would close the replace preview editors atleast for search/replace.

**Comment by sbatten** [comment]
also mentioned in the UX call was that we don't want to close editors that were opened intentionally during a refactor that aren't necessarily caused by the search/replace or refactor. I've a feeling workbench state is too much information and we just want to keep a track of the preview editors opened during the operation that didn't become pinned (due to some other edits potentially).

As for hiding the refactoring pane in the panel, right now the panel doesn't seem to track the previously used panel in any way. E.g. select output, then terminal, then hide terminal tab. The panel then focuses search instead of output. If we simply introduced this history, making the refactor pane empty would handle it all.

**Comment by jrieken** [comment]
>  I've a feeling workbench state is too much information and we just want to keep a track

I feel like you have perfectly described what a workbench state is.

>  If we simply introduced this history, making the refactor pane empty would handle it all.

Only if the panel also knows to hide if nothing has been showing before.

**Comment by sandy081** [comment]
Actually, it used to be like this (close all previews) when this feature was built and got broken in the past. 

Fixed.

**Comment by jrieken** [comment]
I have also tackled this by myself: https://github.com/microsoft/vscode/blob/68fadbd08ed01fce4c4c276232d8a8bfe8bbed9d/src/vs/workbench/contrib/bulkEdit/browser/bulkEdit.contribution.ts#L71-L93

**Comment by bpasero** [comment]
What is the reason for checking on `!group.isPinned(input)` for closing editor or not? Shouldn't it just always close these editors?

An alternative is what Sandeep is doing now: Simply call `dispose()` on the editor you get back from `openEditor()` and that should result in the editor closing if still opened.

**Comment by jrieken** [comment]
A preview is only pinned when the user wanted to, e.g after an explicit action, and therefore I didn't wanna take it away... E.g when you pin an editor but discard a workspace edit that should still see a diff. But I am open to be more radical here

**Comment by bpasero** [comment]
@jrieken ah I see. thing is, pinning is a setting that can be turned off, I for example never use preview editors (via setting `"workbench.editor.enablePreview": false`) so I think for me it would not work. 

I personally would ignore the pinning and always close. Often the preview editor would probably not make much sense anyway after the refactoring has run.

**Comment by jrieken** [comment]
Great - lets try that
