### ISSUE TITLE
tokenColorCustomizations priorities are wrong (or very confusing)

### ISSUE THREAD

**Issue by RobbertC5** [microsoft/vscode#90379]
In the settings `editor.tokenColorCustomizations.textMateRules`, the scope `"variable"` has more priority than the (in my opinion) more specific scope `"entitiy.name.function"`. This means that I can't manually assign a color to function names without overwriting the whole variable scope when my theme has set a color set for the variable scope.

- VSCode Version: 1.42.0
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Add the following to settings.json:
```
"editor.tokenColorCustomizations": {
      "textMateRules": [
          {"scope": ["entity.name.function"],
          "settings": {
              "foreground": "#61AFEF",
          }},
          {"scope": ["variable"],
          "settings": {
              "foreground": "#FF0000",
          }},
      ]
},
```
2. Observe how the `entity.name.function` gets overridden by the `variable` scope:
![screenshot with a function colored in bright red instead of blue](https://i.imgur.com/MW0TJq9.png)

This issue occurs when all extensions are disabled.
I get no errors or warnings.

**Comment by RobbertC5** [comment]
I just noticed, when I open the window and the program is not done loading, during a short moment I get the correct syntax coloring:
![screenshot with correct coloring](https://i.imgur.com/yf90vgw.png)
But then something finishes loading and the variable scope takes over again:
![screenshot with wrong coloring](https://i.imgur.com/C6qBjxu.png)

Notice how the yellow color of `this` survives, as it has the more specific `variable.language`, but `console` does not, as it is in `support.class` which also gets dominated by `variable`.

**Comment by aeschli** [comment]
t's the semantic highlighting kicking in.
There was an issue that I fixed that variables that have a callable type should be rendered functions.
That is in the latest insiders. Did taht fix your issue?

If no, can you paste a code example? Or let me know what the hover over `getDirectories` shows.

**Comment by Limonische** [comment]
I am experiencing the same issue. For example the only way to set color for key in js object literal is to use variable, variable.other or variable.other.property. Those rules override everything else. 
![image](https://user-images.githubusercontent.com/47951826/74728790-6d239380-5254-11ea-9075-704883320368.png)

**Comment by aeschli** [comment]
Yes the semantic classification overrules the TextMate grammar. That's the idea (as the language server knows more about the symbols). 
Your example is not really related to the one of this issue. Can you create a new issue and describe what you want to have. You don't like that object keys are the same as properties?

**Comment by Limonische** [comment]
> Your example is not really related to the one of this issue. Can you create a new issue and describe what you want to have. You don't like that object keys are the same as properties?

Yes, exactly. Thank you for explanation, I will create a separate issue.

**Comment by RobbertC5** [comment]
In the insiders, functions are highlighted correctly now, thanks for that!

I follow your reasoning that semantic classification knows more than TextMate and should overrule it, but sometimes TextMate is more precise / fine tunable. For example, I think this issue still exists with for example `console`. TextMate knows `console` is special (it has `support.class` or even `support.class.console` for who wants it), but for semantic classification it's just a variable like the variable `pat` above it in the screenshot:
![image](https://user-images.githubusercontent.com/14909256/74832855-8c83f480-5318-11ea-9ca3-969e23630f0f.png)

**Comment by aeschli** [comment]
Yes, the semantic highlight has no understanding of 'built-in' types.
If you want to file an feature request...

**Comment by aeschli** [comment]
I created https://github.com/microsoft/vscode/issues/91090 for supporting different rendering of the 'standard' types and variables.
