### ISSUE TITLE
Dropping a folder onto the editor should open a new tab (macOS) instead of a new window.

### ISSUE THREAD

**Issue by mrleblanc101** [microsoft/vscode#90767]
- VSCode Version: 1.42.1
- OS Version: macOS 10.15.3

Steps to Reproduce:

1. Go to system preference and make sure «Prefer tabs when opening new documents: Always»
2. Make sure that «Title bar appearance: Native»
3. Drag a folder onto the VSCode app icon, it open a new tab
4. Drag a folder onto the main editor, it open a new window instead of a tab
5. Both ways to open a project should have the same behavior

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We have a setting that controls this and it has to be configured as following if you expect windows to open newly when opening from within VSCode:

`"window.openFoldersInNewWindow": "on"`

However, I noticed how drag and drop specifically was forcing to reuse the window on drop, independent from this setting. I pushed a change for that, since the default is to open inside the window this only impacts people with this setting explicitly configured.

I think it makes sense to change it because other areas like File > Open also allow this to be controlled through this setting and do not force one behaviour.

**Verification:**
* configure `"window.openFoldersInNewWindow": "on"`
* drop a single folder into editor area
* verify a new window opens

**Comment by mrleblanc101** [comment]
Thanks for the swift reply.
I indeed had this option enable, forgot to mention this critical information. Glad you still figured it out.
I'm glad you could fix this so quickly. Any ETA on when it will be released ?
Next version or later ? And when can we expert it ? I think VS Code has a monthly release but I'm not 100% sure.

**Comment by bpasero** [comment]
Today! You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
@mrleblanc101  can you verify? Thanks!

**Comment by mrleblanc101** [comment]
Hi, 
Yes, it works but I had to restart VS Code twice for it to work.
Once when enabling `Native tabs` (VS Code prompted me) and again after enabling `Open Folders In New Window` (VS Code did not prompt me).
There's just a small UX issue, dropping a folder on Windows still show split panes highlight even if it will open in a new Window instead of a split pane.
![2020-02-21 10 50 23](https://user-images.githubusercontent.com/17392251/75049453-350c9280-5498-11ea-9c8f-00e365f7805e.gif)

**Comment by bpasero** [comment]
Oh yeah good point, I should not show that highlight possibly.

**Comment by bpasero** [comment]
Actually I cannot fix that because at the time of dragging I have no access to what is dragged so it could either be a file or a folder.

**Comment by mrleblanc101** [comment]
Shouldn't split panes only works for file already in your workspace ? Anyway I don't mind it that much, especially if you can't do anything about it. I'm surprised you can't know what being dragged, I guess it's for security reason ?

**Comment by mrleblanc101** [comment]
Thanks for the very quick fix. I opened the same ticket a while ago and no action were taken as you can see. Should I expect this in the March release ?

**Comment by bpasero** [comment]
Yes for March.

**Comment by bpasero** [comment]
> Shouldn't split panes only works for file already in your workspace ?

No, you can open any file into VSCode even if outside your workspace.
