### ISSUE TITLE
Visual Studio Code cannot find runtime 'node' on PATH

### ISSUE THREAD

**Issue by rao-f** [Microsoft/vscode#9236]
- VSCode Version: 1.3.0
- OS Version: Windows 7

Steps to Reproduce:

1. install node V4.4.2
2. install VSCode 1.3.0
3. configure launch.json
4. press F5 to launch project
5. it shows Error: cannot find runtime 'node' on PATH.

The node is set correctly on System variable PATH. Also node is working under the project folder. 
The launch.json is configured as follows:
![not_found_path](https://cloud.githubusercontent.com/assets/7919511/16819686/720897d8-4902-11e6-8981-fa9c7aa87574.jpg)

It worked fine before, but suddenly broken. Tried to reinstall Visual Studio Code and Node, but not working

**Comment by rao-f** [comment]
The issue happened when I tried to relaunch the same project (nothing changed, just relaunch). The relaunch caused System variable PATH broken, so VSC cannot find node. I fixed the problem by restoring my system.

**Comment by geocine** [comment]
what do you mean by restoring your system?

**Comment by laggingreflex** [comment]
I was having this same problem. It turned out in my case I had [clink][1] installed, awesome utility for cmd but it was inadvertently preventing VSCode from being able to invoke node normally.

I think the error "Code cannot find runtime 'node' on PATH" is too specific and misleading. There was also another issue where "where.exe" wasn't found yet it still showed the same error? It should just be "Couldn't run node" or something..

[1]: https://mridgers.github.io/clink

**Comment by moimikey** [comment]
#14229

**Comment by NimaSoroush** [comment]
I am using nvm and I fixed the issue by adding

`"runtimeExecutable": "/Users/x/.nvm/versions/node/v8.1.3/bin/node",`

to `launch.json`.

to find nvm node executable path run `which node`
