### ISSUE TITLE
Regular expression issues

### ISSUE THREAD

**Issue by suchoss** [microsoft/vscode#95425]
Issue Type: <b>Bug</b>

I need to remove some lines of text from about 80 files (every file has about 2000 rows) at the same time. I wanted to use search&replace tool in vs Code(ctrl+shift+f). 

And my issue consists of two different problems:
## Problem 1  
Given following rows:
```
být=elektronický=zásilka
být=jiný=způsob
být=poskytování=pozáruční
být=poskytování=servisní
být=pozdě=třetí
být=pozáruční
být=pozáruční=servis
být=příslušný=krajský
být=příslušný=poškozený
být=schopný=dodaný
být=servis
být=servisní
být=servisní=služba
být=služba=zahrnující
být=zejména=uvedený
```
where I need to remove whole row with occurence. This works correctly and matches 3+grams: 
`^být=[^=]+=.*`
This incorrectly matches also 2grams:
`^být=[^=]+=.*\n`

Then i thought - ok, I can make some workaround and split it to two regexps which lead to problem 2.

## Problem 2 
When I removed all occurences of this `^být=[^=]+=.*` from all files, then I needed to remove blank lines. I used the same tool for multi search and replace in all files from the same folder.
I used this regexp `^\n` and the button for replace all (it said about 2000 occurences) didn't do almost anything (changed about 3 files from 80). 

Ok I tried to click to replace all button in multisearch window file by file. Reached 3rd file where it stopped to work as well. 

Ok if I click fast enough I might be done soon I thought and clicked on replace for each occurence in multisearch window.

And I was terrified when I later found that it instead of deleting blank lines also deleted lines with text. (e.g. `cena=náhradní=díl`) 

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (20.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
vscode-markdownlint|Dav|0.34.0
jsonpath-extract|dav|1.2.3
gc-excelviewer|Gra|2.1.34
Angular2|joh|9.1.2
rainbow-csv|mec|1.6.0
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.17
vscode-kubernetes-tools|ms-|1.1.1
python|ms-|2020.3.71659
powershell|ms-|2020.3.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-yaml|red|0.7.2
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by IllusionMH** [comment]
> This incorrectly matches also 2grams:

It actually doesn't match just 2grams, but 2grams and whole next line.

when you use Find - regexp matches single line until you add `\n` (this is done for optimization purposes)

Since you have `\n` in your last regexp you will match across multiple lines and `[^=]` matches new line and `být` and then `.+` matches everything to the end of the line.

In your case you need to prevent match of ne line in first character class explicitly disallowing `\n` there `^být=[^=\n]+=.*\n`

With fixed regexp it should work correctly and most likely

>And I was terrified when I later found that it instead of deleting blank lines also deleted lines with text. (e.g. cena=náhradní=díl)

is result of incorrect first regexp

**Comment by suchoss** [comment]
@IllusionMH Thanks, you are correct about regexp part. Although graphically it is quite confusing to see highlighted text like it is in VS code. I tried Sublime for the same regex now (`^být=[^=]+=.*\n`) and from the results it is more obvious:

![sublime left, vs code right](https://user-images.githubusercontent.com/39336141/79463120-b5fb8c80-7ff8-11ea-9ca7-b972c8ab7ffc.png "sublime left, vs code right")

But using correct regexp doesn't solve bug described in problem 2 for multisearch (ctrl+shift+f).  
Trying to remove a lot of blank lines between lines with text for many files at once is buggy. And in my case it removed files with some content.

Now I am testing it again and it is not about removing blank lines. The issue is also for differnet regexp.

## additional info to problem 2
![image](https://user-images.githubusercontent.com/39336141/79465391-90bc4d80-7ffb-11ea-9bdb-644bf6a0eca7.png)

1) Get about 80 files each with about 2000 rows of some text
2) Click on search (ctrl+shift+f) and try to search in all 80 files first regular expression (just to delete all text except \n character). Replace that text with empty string. So it produces blank lines. (Green bordered button from the picture above)
3) Change search input to `^\n` and try to replace all with empty string. (Green bordered button from the picture above).  => **In my case it does absolutely nothing**. No change at all.
4) If green bordered button doesnt work, then try to click quickly on (Red bordered button from the picture above). Click on the same place and it replaces single occurrences. But now it also deletes some lines which are not empty.

**Comment by IllusionMH** [comment]
Have you tried Search: `\n+` Replace `\n` . instead of `^\n`?

**Comment by suchoss** [comment]
@IllusionMH No, I guess it will work. My problem is solved. Right now I am just trying to file an issue to VS code, so it gets fixed in some future release. :)

**Comment by IllusionMH** [comment]
I'd suggest you to split it into 2 separate issues which have separate action items and resolved separately:
1. display of match ranges (basically request to add `editor.findMatchBorder` to default themes)
1. second - attempt to replace with `^\n`.
This one doesn't have any problems with single items replacement, or Replace from find widget, but Replace all in Find in files results in error: `Error: Overlapping ranges are not allowed!`

**Comment by chrmarti** [comment]
There is some indication for multi-line matches:
![image](https://user-images.githubusercontent.com/9205389/79539389-83987080-8086-11ea-971c-61e215e2c81b.png)

@roblourens It's not clear to me what `+1` and `+2` in the search results mean.

Lets use this issue to track that.

**Comment by IllusionMH** [comment]
While user can find what `+1` `+2` mean after couple of multiline searches, this problems still apparent in highlight from Find widget where we don't have any indication. In this case it's impossible to notice that in the middle of the list some of matches takes two lies without navigation one-by-one.

Having borders would help to see start/end of matches in cases when the follow each other. Question is how often this case will occur, but failing to easily see that there are one or separate matches has big impact.

**Comment by suchoss** [comment]
@IllusionMH Well in my case - if it doesn't occur that often then it is even more dangerous, because you don't expect that multiline match is going to be hidden. As you write - it has big impact. And If I didn't commit each step separately in my case I wouldn't even notice my fault there. I would lost about 5 hrs of work with this quite simple multiline regular expression.

Thanks for your time guys. It is appreciated.

**Comment by roblourens** [comment]
Thanks for your help investigating @IllusionMH. So is the remaining issue here not noticing that a result is a multiline match? I don't totally understand your comment

> this problems still apparent in highlight from Find widget where we don't have any indication

Are you just suggesting that we add find match borders to the default themes? I would not be opposed to that, however I wouldn't add them by default unless we draw them nicely like Sublime where the border only goes around the outside of the range. Our border draws lines between lines of the multiline match.

**Comment by IllusionMH** [comment]
Main problem, as I see it: it is impossible to differentiate between cases when match ranges follow each other.

Couple of simplified examples:
In this case  it's hard to tell if I've messed up regexp and matched all imports instead of each import separately (unless you know that there were expected 3 matches instead of 1)
![image](https://user-images.githubusercontent.com/1312662/79576121-76ea3b80-80cb-11ea-9bb8-0c39f6e62108.png)

In this case it's hard to tell if while name is matched or parts.
![image](https://user-images.githubusercontent.com/1312662/79577217-0a703c00-80cd-11ea-9ef4-5035b04f936a.png)

Having borders (as in Sublime) in these cases would help to see exact match ranges
![image](https://user-images.githubusercontent.com/1312662/79577993-4657d100-80ce-11ea-8d01-3e4fa51e9350.png)

> I would not be opposed to that, however I wouldn't add them by default unless we draw them nicely like Sublime where the border only goes around the outside of the range.

Yes, this would be best solution in these cases.

---

I've checked how borders look in VS Code and highlights and see next problems:

1. As you've mentioned - in case of multiline match at lease left/right borders should be omitted to  indicate that this is not the end of the range. Ideally - render single outline of matched range (as in Sublime). Applies only to multiline matches.

1. Looks like it's impossible to apply border to matched range at least I had no luck with `editor.findRangeHighlightBorder` (I expected that it will be applied to elements with `findMatch` in DOM) while `editor.findMatchBorder` applies to current match (with class `currentFindMatch`)

1. Currently ranges that follow each other rendered as single block
![image](https://user-images.githubusercontent.com/1312662/79581825-a2712400-80d3-11ea-9d63-36b1c09b5684.png)
As with left part - there are 3 matches
So even if it will be possible to add borders to match ranges - current behavior needs to be changed as well - there should be separate block for each match.

**Comment by roblourens** [comment]
`findRangeHighlightBorder` is for the "Find in selection" feature, it highlights the range that is being searched.

We have `editor.findMatchHighlightBorder` but like you say, matches next to each other are treated as a single block and are wrapped in a single border. I will leave this as a feature request for @rebornix or @alexdima
