### ISSUE TITLE
Error: Cannot find module 'c:/Program Files/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug-nightly/src/bootloader.js'

### ISSUE THREAD

**Issue by GKennyKwok** [microsoft/vscode#98778]
Issue Type: <b>Bug</b>

<pre>
>npm i qr-image
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'c:/Program Files/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug-nightly/src/bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1133:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:443:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:62:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
</pre>

VS Code version: Code - Insiders 1.46.0-insider (9e439b13d5784538333bee044ca1d1a992bc1c90, 2020-05-28T18:44:47.151Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz (8 x 3093)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.38GB free)|
|Process Argv|--disable-gpu|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.2
vscode-bazel|Baz|0.3.0
cssrem|cip|0.1.0
vscode-svgviewer|css|2.0.0
binary-plist|dni|0.4.0
vscode-html-css|ecm|0.2.3
vscode-pull-request-github|Git|0.16.1
todo-tree|Gru|0.0.176
vscode-nginx-conf-hint|han|0.1.0
syntax-project-pbxproj|mar|0.1.3
code-beautifier|mic|2.3.3
vscode-language-pack-zh-hans|MS-|1.46.0
vscode-edge-devtools|ms-|1.0.7
python|ms-|2020.5.80290
cpptools|ms-|0.28.1
powershell-preview|ms-|2020.5.0
debugger-for-chrome|msj|4.12.8
debugger-for-edge|msj|1.0.14
sqltools|mtx|0.21.9
vetur|oct|0.24.0
java|red|0.62.0
vscode-xml|red|0.11.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|syl|1.8.4
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.1
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.4
vscode-maven|vsc|0.21.4
vscode-todo-highlight|way|1.0.4

</details>

**Comment by connor4312** [comment]
When is this happening?

If it's in a normal terminal and auto attach is not disabled, then you can fix it by setting auto attach to disable, and then turning it back to on/off.

/needsMoreInfo

**Comment by GKennyKwok** [comment]
This is a recent error, there is bootloader.bundle.js in the same folder, but the terminal points to bootloader.js

**Comment by GKennyKwok** [comment]
I got this error after updating

**Comment by connor4312** [comment]
> setting auto attach to disable, and then turning it back to on/off

Does this resolve the issue for you?

**Comment by GKennyKwok** [comment]
Fixed, I always use off for this setting. 
It is no problem to change to disable and restore off

I use Microsoft VS Code Insiders and node-v12.14.1. Node has not been updated, only VS Code has enabled automatic update, and it will be updated every time it is closed. Until half an hour before I submit the issue, using the two commands npm and yarn will not work.

thanks

**Comment by RichieChoo** [comment]
I meet it too ！I hope vscode update should be know by its owner!!!

**Comment by chrmarti** [comment]
![image](https://user-images.githubusercontent.com/9205389/84117737-46bb7b00-aa32-11ea-8d9d-4df1dccc900f.png)

I have `ms-vscode.js-debug-nightly-2020.6.817` in the extensions folder, but not `2020.5.217` as shown in the error.

Still occurred after disabling all extensions. After an additional reload it disappeared. Also toggled the Auto Attach setting which did not seem to change anything, maybe it took the reload to do so. 🤷 

---

Version: 1.46.0-insider
Commit: 9f89da69154ac6c99dfa7c82986e2df95b7bbe0b
Date: 2020-06-08T22:10:59.393Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by connor4312** [comment]
@chrmarti this will happen when upgrading from old versions -- here it looks like you were a couple weeks behind, so when you updated it will break.

Toggling auto attach will require that you click the ⚠️ icon that appears in the terminal and accept the environment variable changes (it's easy to miss if you don't look for it)

**Comment by chrmarti** [comment]
Ok, thanks. Closing as expected.

**Comment by chrmarti** [comment]
@connor4312 I see this again with:
```
Version: 1.47.0-insider
Commit: 7e4cc2c435927e5a2845897961a2af10ee7f784d
Date: 2020-06-12T05:59:19.397Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

The missing version is still the same:
```
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/Users/chrmarti/.vscode-insiders/extensions/ms-vscode.js-debug-nightly-2020.5.217/src/bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1133:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:443:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:62:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v12.14.1 --silent` to unset it.
```

**Comment by connor4312** [comment]
@chrmarti terminal environment variables are set per-workspace. Maybe you're on an older workspace where the variable was previously set?

**Comment by chrmarti** [comment]
I see it with the vscode folder. Toggling auto attach doesn't help. I don't see the warning triangle, would that show up in the statusbar?

**Comment by connor4312** [comment]
To confirm -- you're toggling auto attach through `disabled`, not just `off`?

If so, that's weird: please send an invite for a call at whatever time works for you so we can look at this together. Thanks!

**Comment by chrmarti** [comment]
Correct, I just went through all values of the setting and the error is still there. Interestingly I only see this with the `vscode` folder, not with other folders.

**Comment by connor4312** [comment]
In case anyone else hits this, we figured out what was going wrong: originally the terminal variables were created by `js-debug-nightly`. Starting in the last stable release, we switched from `js-debug-nightly` being built-in to a stable version, `js-debug`. Christoff had both `js-debug` and `js-debug-nightly` installed and active. When we tried to clear variables by going through the `disabled` state, the command was dispatched to `js-debug`, but `js-debug-nightly` was the one who installed them, so it didn't work.

To fix this:

1. Make sure `debug.javascript.usePreview: true` is in your user setting
2. Make sure that _either_ js-debug or js-debug-nightly or enabled
3. Toggle auto attach to disabled (and enabled again, if you'd like). The ⚠️ sign should appear on the upper right of the terminal.

**Comment by paulsimongb** [comment]
I have tried all the above suggestions and I am still getting the same error. Looking at the output it seems that the C:/ should be C:\. However, I don't know where to fix this. The debugger was working before I upgraded to 1.46.

C:\AVueNode\UCoAMDM\Server> cmd /C "set "NODE_OPTIONS=--require "c:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" " && set "VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"\\\\.\\pipe\\node-cdp.11668-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"fileCallback":"C:\\Users\\psim1\\AppData\\Local\\Temp\\9\\node-debug-callback-529c09196c041188"}" && c:\Users\psim1\AppData\Roaming\npm\nodemon.cmd c:\AVueNode\UCoAMDM\Server\js\server.js "
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '"c:/Program'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:812:12)
    at preloadModules (internal/bootstrap/node.js:598:7)
    at startup (internal/bootstrap/node.js:272:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

C:\AVueNode\UCoAMDM\Server>

This is the relevant section of launch.json


      {
          "name": "Debug Node",
          "type": "node",
          "request": "launch",
          "cwd": "${workspaceFolder}/Server",
          "runtimeExecutable": "nodemon",
          "program": "${workspaceFolder}/Server/js/server.js",
          "restart": true,
          "console":"integratedTerminal",
          "internalConsoleOptions": "neverOpen",
          "autoAttachChildProcesses": true,
          "skipFiles": [
            "<node_internals>/**/*.js*/",
            "<node_internals>/**/*..js*/",
            "${workspaceFolder}/Server/node_modules/**/*.js",
            "${workspaceFolder}/Server/mssqlserver/*.log"
          ],
          "smartStep": true,
          "env": { }
      },

This is the relevant part of settings.json

"javascript.updateImportsOnFileMove.enabled": "always",
    "editor.scrollbar.verticalScrollbarSize": 30,
    "editor.scrollbar.verticalScrollbarVisible": true,
    "editor.scrollbar.verticalScrollbarMap": false,
    "editor.scrollbar.horizontalScrollbarSize": 30,
    "editor.find.autoFindInSelection": "always",
    
    "debug.javascript.usePreview": true,

    "workbench.colorCustomizations": {
        // Scrollbar
        "editorOverviewRuler.addedForeground": "#0000",
        "editorOverviewRuler.modifiedForeground": "#0000",
        "editorOverviewRuler.deletedForeground": "#0000",
    
        // Gutter (same as tweaking scm.diffDecorations?)
        "editorGutter.addedBackground": "#0000",
        "editorGutter.modifiedBackground": "#0000",
        "editorGutter.deletedBackground": "#0000",
    },
    "debug.node.autoAttach": "on",

I have tried changing the debug:node.autoAttach to disable, off, etc, but it made no difference.
